### ISSUE TITLE
rpmbuild -rb should set SOURCERPM and SOURCEPKGID

### ISSUE THREAD

**Issue by cottsay** [rpm-software-management/rpm#1000]
Right now, SOURCERPM seems to be a prediction of what the source package name SHOULD be.

Since the source package is given directly when building with `-rb`, the SOURCERPM should be set based on that package and the SHOURCEPKGID should also be set appropriately.

From what I can tell, this would involve plumbing those two values from [rpmbuild.c:main()](https://github.com/rpm-software-management/rpm/blob/58dcfddc376a7c97de1432f0082be0d5f01adbcd/rpmbuild.c#L683) into [rpmbuild.c:buildForTarget()](https://github.com/rpm-software-management/rpm/blob/58dcfddc376a7c97de1432f0082be0d5f01adbcd/rpmbuild.c#L506-L510) so that they can be set on the `rpmSpec` object after the extracted spec is parsed. As long as it wasn't set when `RPMBUILD_PACKAGESOURCE` is specified, I believe that might produced the expected behavior.

Related to (and possibly a solution for) #957

**Comment by pmatilai** [comment]
It's related to #957 allright, in that this request is the very reason for the existence of that ticket. 
Rpm cannot inject SOURCEPKGID on builds where src.rpm is not generated, and copying the id from the one being rebuilt would be wrong. See https://bugzilla.redhat.com/show_bug.cgi?id=1741715 for details.

**Comment by cottsay** [comment]
> copying the id from the one being rebuilt would be wrong

Okay, got it.

Any reason we can't do better than guessing when populating SOURCERPM?
