### ISSUE TITLE
rpm4 can't sign rpm5 packages

### ISSUE THREAD

**Issue by fedya** [rpm-software-management/rpm#1002]
i'm trying to sign rpm5 package from here http://abf-downloads.rosalinux.ru/rosa2016.1/container/3181857/x86_64/main/release-rpm-new/
with rpm --addsign 
rpm version: 4.15.1
my ~/.rpmmacros
```
%_signature gpg
%_gpg_path /root/.gnupg
%_gpg_name 16a853e7
%_gpgbin /usr/bin/gpg
%__gpg_check_password_cmd /bin/true
%__gpg /usr/bin/gpg
%__gpg_sign_cmd %__gpg gpg --no-tty --pinentry-mode loopback --no-armor --no-secmem-warning --sign --detach-sign --sign --detach-sign --output %__signature_filename %__plaintext_filename
%_disable_source_fetch  0
```

what i do:
```
bash-4.4# rpm --addsign firefox-72.0.1-1-rosa2016.1.x86_64.rpm 
firefox-72.0.1-1-rosa2016.1.x86_64.rpm:
error: firefox-72.0.1-1-rosa2016.1.x86_64.rpm: rpmReadSignature failed: signature region 62: tag number mismatch il 7 ril 6 dl 792 rdl 168
```

6-8 months ago everything works with with such way of RPM signing

How to reproduce:

docker run -ti quay.io/ngompa/rosa2019.1-rpm4 bash
dnf install rpm-sign
generate key and macro
wget http://abf-downloads.rosalinux.ru/rosa2016.1/container/3181857/x86_64/main/release-rpm-new/firefox-72.0.1-1-rosa2016.1.x86_64.rpm
rpm --addsign firefox-72.0.1-1-rosa2016.1.x86_64.rpm

and you got an error.

**Comment by Conan-Kudo** [comment]
@fedya Were you using rpm4 to sign six months ago? If so, what version and what distribution?

**Comment by fedya** [comment]
It was OpenMandriva 3.0

**Comment by Conan-Kudo** [comment]
@fedya OpenMandriva 3.0 was rpm5, not rpm4. It isn't normally supported to sign rpm5 packages with rpm4. If it was working with OpenMandriva 4.0 with rpm 4.14, then that's a different story...
