### ISSUE TITLE
RPM Signature Tags MD5 TAG size after --addsign

### ISSUE THREAD

**Issue by DuratarskeyK** [rpm-software-management/rpm#1010]
I have an RPM file in the attachment:
[dos2unix-7.4.1-1-rosa2019.1.x86_64.rpm.gz](https://github.com/rpm-software-management/rpm/files/4060288/dos2unix-7.4.1-1-rosa2019.1.x86_64.rpm.gz)
After addsign the RPMSIGTAG_MD5 has 2 zero bytes added after the hash itself, which is 16 bytes. What is the reason for these 2 additional bytes?

**Comment by pmatilai** [comment]
Without actually looking - alignment, padding?
Why do you care?

**Comment by DuratarskeyK** [comment]
We use a weird version of rpm, which computes data size by subtracting next offset from the current one, which yields 18 bytes and then MD5 check fails.

**Comment by pmatilai** [comment]
That's a bug in your rpm, optimization that gets wrong results on exact data is not a legit optimization.
We actually had the same bug although in slightly limited form, see #398 for the discussion and fix.
