### ISSUE TITLE
%define macro value is not evaluated on rpm 4.11.3

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpm#1013]
## Sumamry

`%define` macro is not evaluated, the value is not set when building a RPM spec file with rpm-4.11.3-40 and `%bcond_without git` is executed.

## Context

I was trying to build a `ruby.spec` file on RHEL7, that is based on the Fedora rawhide current latest `ruby.spec` [URL](https://src.fedoraproject.org/rpms/ruby/blob/345ce0e5b8a3a6d9c962807da12e80bdaee9fb90/f/ruby.spec#_25).

But the built RPM was `ruby-2.7.0-%{release_string}.x86_64.rpm`. The `%{release_string}` value was not set. On Fedora rawhide, the value was set.

The `ruby.spec` code is like this.

```
...
%global release 126
%{!?release_string:%define release_string %{?development_release:0.}%{release}%{?development_release:.%{development_release}}%{?dist}}
...
%bcond_without git
...
Release: %{release_string}
...
```

So, I prepared the simple example to reproduce this issue, with GitHub and Travis CI.

Here is [the reproducing example](https://github.com/junaruga/report-rpm-macro-define), and the [Travis CI result](https://travis-ci.org/junaruga/report-rpm-macro-define/builds/639514301).

Using very simple RPM spec file [foo.spec](https://github.com/junaruga/report-rpm-macro-define/blob/master/foo.spec), and building it by `rpmbuild -ba foo.spec`.

Here is the result. See above Travis CI result.

1. fedora:rawhide / rpm-4.15.1-2.fc32.x86_64 : OK
2. fedora:31 / rpm-4.15.1-1.fc31.x86_64 : OK
3. centos:8.1 / rpm-4.14.2-25.el8.x86_64 : OK
4. centos:7.7 / rpm-4.11.3-40.el7.x86_64 : NG
5. centos:7.7 / rpm-4.11.3-40.el7.x86_64 does not execute `%bcond_without git`: interestingly this case is OK

### OK case

https://travis-ci.org/junaruga/report-rpm-macro-define/jobs/639514306#L510

```
+ echo 'release_string: 2.el7.el7'
release_string: 2.el7.el7
+ echo 'bbb: 2'
bbb: 2
+ echo 'ddd: 2'
ddd: 2
+ echo 'fff: 2'
fff: 2
```

https://travis-ci.org/junaruga/report-rpm-macro-define/jobs/639514306#L556

```
+ find /root/rpmbuild/ -type f
/root/rpmbuild/SRPMS/foo-2.7.0-2.el7.src.rpm
/root/rpmbuild/RPMS/x86_64/foo-2.7.0-2.el7.x86_64.rpm
/root/rpmbuild/BUILD/foo
```

### NG case

https://travis-ci.org/junaruga/report-rpm-macro-define/jobs/639514305#L506

```
+ echo 'release_string: %{release_string}'
release_string: %{release_string}
+ echo 'bbb: %{bbb}'
bbb: %{bbb}
+ echo 'ddd: 2'
ddd: 2
+ echo 'fff: %{fff}'
fff: %{fff}
```

https://travis-ci.org/junaruga/report-rpm-macro-define/jobs/639514305#L552

```
+ find /root/rpmbuild/ -type f
/root/rpmbuild/SRPMS/foo-2.7.0-%{release_string}.src.rpm
/root/rpmbuild/RPMS/x86_64/foo-2.7.0-%{release_string}.x86_64.rpm
/root/rpmbuild/BUILD/foo
```

## Questions

1. Why this issue happens on rpm 4.11.3 when only `%bcond_without git` is executed?
2. When Fedora's `ruby.spec` has to consider backward ccompatibility on CentOS7, what is the best pracitce dealing with `%define` macro? We should not use `%define` macro?

Thank you.

**Comment by junaruga** [comment]
## How to reproduce this issue on your environment

1. Fork the repository: https://github.com/junaruga/report-rpm-macro-define
2. Enable Travis CI for the repository.
3. Check the Travis CI result modifying the `foo.spec` file.

**Comment by pmatilai** [comment]
rpm < 4.14 has weird and broken semantics on macro scoping, that behavior is the main reason for the somewhat misguided "always use %global over %define" recommendation in Fedora guidelines. If compatibility is required, either use %if for the conditionals or use %global to define macros inside %{}.

See 237f35f16f978bb20e4cafd78abfab1f2e5db480 for further info/rationale.

**Comment by junaruga** [comment]
@pmatilai Thanks for your info!

After changing the spec file to use `%if` like this, `%release_string` macro value was set.

```
diff --git a/foo.spec b/foo.spec
index 47a0596..b19233b 100644
--- a/foo.spec
+++ b/foo.spec
@@ -1,5 +1,7 @@
 %global release 2
-%{!?release_string:%define release_string %{release}%{?dist}}
+%if ! 0%{?release_string}
+%define release_string %{release}%{?dist}
+%endif
```

```
+ find /root/rpmbuild/ -type f
/root/rpmbuild/SRPMS/foo-2.7.0-2.el7.src.rpm
/root/rpmbuild/RPMS/x86_64/foo-2.7.0-2.el7.x86_64.rpm
/root/rpmbuild/BUILD/foo
```

**Comment by pmatilai** [comment]
Yup. Just FWIW, another variant which is perhaps a bit more readable:

%if ! %{defined release_string}
...
%endif

**Comment by junaruga** [comment]
Yeah, it's more readable. Thanks for sharing the tip.
