### ISSUE TITLE
Suspicious code in rpmdbRebuild()

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1017]
rpmdb.c's rpmdbRebuild() function contains this:
```
            if (headerIsEntry(h, RPMTAG_HEADERIMAGE)) {
                Header nh = headerReload(headerCopy(h), RPMTAG_HEADERIMAGE);
                rc = rpmdbAdd(newdb, h);
                headerFree(nh);
            } else {
 ```

I guess that the code should read `c = rpmdbAdd(newdb, nh);` instead. (The commit in question
is 27ea3f8624560bd158fc7bc801639310a0ffab10, which moved the headerReload() call out of headerCopy().)

**Comment by pmatilai** [comment]
Good catch, thanks.

These things really just make me want to drop the gauntlet on v3 packages finally. But until then...
