### ISSUE TITLE
Sqlite backend's prefix match cannot deal with '%' characters

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1018]
It should either escape the '%' chars or use a custom match function.

**Comment by mlschroe** [comment]
I learned a bit more about sqlite in another project. Turns out that using a custom match function is much slower than the LIKE version, because of sqlite's LIKE optimization: https://www.sqlite.org/optoverview.html#the_like_optimization

So I think we should go back to use LIKE and escape the % and _ characters.

**Comment by pmatilai** [comment]
Being somewhat slower doesn't make it wrong. I'd rather leave it alone unless the performance actually turns out to be a problem.

**Comment by pmatilai** [comment]
Closing to avoid anybody thinking that %'s can't be handled. Optimizations oare a whole different matter.
