### ISSUE TITLE
%generate_buildrequires should have a page on rpm.org

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#1029]
Although the new cli for rpmbuild is described in the rpmbuild man page the feature is big enough that it deserves a article of its own.

**Comment by xsuchy** [comment]
You can steal the documentation from https://fedoraproject.org/wiki/Changes/DynamicBuildRequires

**Comment by ffesti** [comment]
da55723907418bfb3939cd6ddd941b3fdb4f6887 add a paragraph to the in tree documentation and dynamic build requires are also mentioned elsewhere (e.g. in doc/manual/buildprocess.md).

Rather than making a separate page just for rpm.org we should sync up the in-tree docs with the rpm.org web page: #1666

Closing.
