### ISSUE TITLE
Combination of unordered and ordered dependencies causes order to be ignored

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1030]
A combination of unordered and ordered dependency flags, such as `Requires(pre,posttrans): foo` will cause the whole dependency be discarded during ordering. The ordering code needs fixing to skip the relation only if its not also an ordered relation (including the ones where no special flags are set).

**Comment by ffesti** [comment]
I want to strongly argue that this is an bug in isUnorderedReq(). The name strongly suggests that is answers the question whether this Requires can be ignored for ordering. The question it actually answers is if it is at least in part needed a places that don't need ordering. That's something no one should ever even consider.
I'll submit a patch to fix this.

**Comment by pmatilai** [comment]
Well, semantics can be argued, but if we consider the name to be wrong then the same is true for *all* these isFooReq() macros. I don't see it being wrong as such, because the macro(s) only return true if the dependency is "Foo" - whether it also has some other (even contradictory) features is a different question.

I'd leave the existing macros as-is, and add separate isFooOnlyReq() macros that answer the question that our own uses actually need.

**Comment by ffesti** [comment]
The second patch does not really belong here but it's more convenient here to avoid merge conflicts.
It is a preparation for #1028 which will need to modify when Requires will be ignored within already installed packages.
