### ISSUE TITLE
RFE: declarative user/group handling

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1032]
A long-standing request is to have a declarative spec syntax for user and group addition/removal. Now that file-triggers are commonplace, this is one of the biggest offenders forcing packages to add scriptlets of their own for the mundane task of adding users and groups.

Probably the biggest challenge here is initial installation (into a chroot), where users and groups might not match those of the host, but there's no user/group data or tools to create them in the chroot yet either.

Co-operating with systemd-sysusers where available might be something to look into.

**Comment by lnussel** [comment]
Maybe a provides generator could be used that parses sysusers files to avoid any extra tags the packager has to put in spec files. Then a new kind of trigger that acts on such provides could create the actual user.

**Comment by pmatilai** [comment]
With rpm >= 4.17 (as a side-effect of commit a82251b44ee2d2802ee8aea1b3d89f88beee4bad) there now exists a window where the files have been unpacked but metadata not yet set. That'd be the opportunity to call out to systemd-sysusers (or some other mechanism) create the users based on data in the package itself, before we proceed to set ownership and other permissions to the files.

**Comment by pmatilai** [comment]
Fixed by #2432
