### ISSUE TITLE
Request For Enhancement: Better error output in rpmbuild

### ISSUE THREAD

**Issue by pontaoski** [rpm-software-management/rpm#1034]
Recently I've been working on a project called [alpmbuild](https://github.com/alpmbuild) that builds Arch packages from RPM specfiles.

Among one of the things it offers is quality error output.

![image](https://user-images.githubusercontent.com/20326855/73573279-fbb8a800-4440-11ea-9229-ee12afcb6e3d.png)
![image](https://user-images.githubusercontent.com/20326855/73573287-ffe4c580-4440-11ea-891c-993cdecee3d2.png)
![image](https://user-images.githubusercontent.com/20326855/73573293-0410e300-4441-11ea-9b3e-1422ecd61363.png)
![image](https://user-images.githubusercontent.com/20326855/73573302-08d59700-4441-11ea-9b36-68b46f0ae676.png)

It would be nice to have this style of error output in the actual rpmbuild itself, as that's where people are more likely to be using specfiles—being that specfiles are the native build recipe format of RPM.

Codewise in alpmbuild, this works like so:
The main reading loop looks for keywords in a line indicating what needs function needs to parse the line, and then hands the line number, line, and context to a function. This function is responsible for parsing the line and updating the context, outputting errors if necessary. The function can use the line + line number to call an error/warning function, which takes messages and a range of characters to highlight.

**Comment by pmatilai** [comment]
For expressions (used with %if and macro %[] and %{expr:...}) we actually just added something like that a few months ago, eg:

```
[pmatilai🎩︎lumikko-w rpm]$ ./rpmbuild -bp ~/rpmbuild/SPECS/popt.spec
error: bare words are no longer supported, please use "...":  a == 1
error:                                                        ^
error: /home/pmatilai/rpmbuild/SPECS/popt.spec:17: bad %if condition:  a == 1
[pmatilai🎩︎lumikko-w rpm]$ ./rpmbuild -bp ~/rpmbuild/SPECS/popt.spec
error: syntax error while parsing &&:  "a" & 1
error:                                      ^
error: /home/pmatilai/rpmbuild/SPECS/popt.spec:17: bad %if condition:  "a" & 1
```

Still fairly crude of course, but its something.

**Comment by pmatilai** [comment]
The challenge in rpm is that the macro engine is a separate entity that has no idea about the spec parser, and largely vice versa and this design is quite impossible to change. This is quite different when implementing a separate parser from scratch.

This is such a sweeping topic that it can never be truly "done", but steps towards better error messages have been taken all along. Thanks for the feedback and suggestions!
