### ISSUE TITLE
Order Packages by size during build

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#1045]
We are now creating the packages in parallel during build. But if the small packages get done quickly and only one big package remains there is nothing left to do in parallel.
Ordering the packages by size should improve this and have smaller packages left over for longer during the build. This should reduce the overall build time for many package for very little overhead (as we already know the package size by then).

**Comment by pmatilai** [comment]
Yup. Right now this tends to be backwards as debuginfo packages are typically among the largest ones.

Starting with the largest ones will also help in further allocating resources (eg use more threads for compressing the larger packages) if we some day get that far.

**Comment by dmnks** [comment]
A testing spec file that I used to benchmark this patch:

```
%global _smp_build_nthreads 2

Name:           foo
Version:        1.0
Release:        1%{?dist}
Summary:        testing package for parallel building

License:        GPL

%description

%package light1
Summary:        light subpackage 1
%description light1

%package light2
Summary:        light subpackage 2
%description light2

%package light3
Summary:        light subpackage 3
%description light3

%package light4
Summary:        light subpackage 4
%description light4

%package heavy1
Summary:        heavy subpackage 1
%description heavy1

%install
mkdir -p %{buildroot}/%{_libdir}
dd if=/dev/urandom of=%{buildroot}/%{_libdir}/libfoo_light1.so count=30 bs=10M
dd if=/dev/urandom of=%{buildroot}/%{_libdir}/libfoo_light2.so count=30 bs=10M
dd if=/dev/urandom of=%{buildroot}/%{_libdir}/libfoo_light3.so count=30 bs=10M
dd if=/dev/urandom of=%{buildroot}/%{_libdir}/libfoo_light4.so count=30 bs=10M
dd if=/dev/urandom of=%{buildroot}/%{_libdir}/libfoo_heavy1.so count=120 bs=10M

%files light1
%{_libdir}/libfoo_light1.so
%files light2
%{_libdir}/libfoo_light2.so
%files light3
%{_libdir}/libfoo_light3.so
%files light4
%{_libdir}/libfoo_light4.so
%files heavy1
%{_libdir}/libfoo_heavy1.so

%changelog
* Mon Mar  2 2020 Michal Domonkos <mdomonko@redhat.com>
- 
```

On my laptop, the total build time is `~1:35` and `~1:20` before and after the patch, respectively. Not a huge difference here, but thread utilization is be a bit better now and should help with the really-big packages like the kernel (haven't tried that yet).
