### ISSUE TITLE
%global expands twice

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1049]
Oh wow, I knew that %global expands right away when defining the macro, but I somehow didn't expect that it expands again when the macro is used:
```
$ rpm --eval '
> %define foo %%%%
> %global bar %%%%
> %foo percent, %bar percent'

%% percent, % percent
```
Is that documented anywhere?

Anyway, I'm pretty sure that changing this will break most packages that use %global instead of %define because some guidelines said so, but I'm wondering if we should add two new macros to make it easier to use %global in a safe way:
```
%{literal:%foo}       - expands to the unexpanded body, i.e. `%foo`
%{quotepercent:%foo}  - expands the body and then doubles all % chars, i.e. '%%%%'
```
(I do not like the name `quotepercent`, though)

With those macros, `%global foo %{literal:...}` would be exactly like %define but at global level, whereas `%global foo %{quotepercent:...}` would only expand at the macro definition.

**Comment by pmatilai** [comment]
It's mentioned in https://rpm.org/user_doc/macros.html:
> Note that %define and %global differ in more ways than just scope: the body of a %define’d macro is lazily expanded (ie when used), but the body of %global is expanded at definition time. It’s possible to use %%-escaping to force lazy expansion of %global.

Might even be added by myself, but that's actually a pretty lousy explanation. Yes, body of %global is expanded at the time of definition but to use a macro is to expand it, so any remaining macros in %global's body will be expanded on use. To do anything else would seem strange to me.

As for %{literal:...}, there's already a ticket requesting that functionality (#582). Name-bikeshedding aside, I've nothing against adding such a feature.

I can live with %{quotepercent:...} too, I just wonder if there should instead be a macro type that does *not* expand on use. Eg

%literal foo %{blablah}

(whether its called %literal, %constant or whatever)

**Comment by pmatilai** [comment]
Started adding a %define/%global -style %literal directive for this using the new ME_LITERAL flag, but somehow it feels off the mark. I'm wondering if we should just add options to %define instead to allow finer expansion control (and make %global an alias to that)

**Comment by pmatilai** [comment]
Closing from the perspective of subject: we're not changing %global behavior, too many things depend on it being the way it is. We do have %{macrobody:...} now and could also add a macro primitive to declare literal macros, but that's beyond the scope here I suppose.
