### ISSUE TITLE
PVS-Studio Analysis Results for RPM

### ISSUE THREAD

**Issue by fedya** [rpm-software-management/rpm#1052]
I run latest PVS studio checker over RPM rpm-4.15.1
Full log available here
http://repoclosure.openmandriva.org/fullhtml/

Hope it help you to make rpm better

**Comment by ignatenkobrain** [comment]
It would be much better if you file PR which fixes them, but this is at least something. I checked some of them and definitely those can be fixed. Some of them seem to be useless.

Also, is there something like travis-ci to run pvs studio?

**Comment by pmatilai** [comment]
There's some truly useless stuff in there, such as a "high" warning on "The '_RPMUTIL_H' include guard is already defined in the 'rpmutil.h' header. The 'rpmutil.h' header will be excluded from compilation." ... on the rpmutil.h file itself :roll_eyes: 

However among that cruft there clearly are relevant and even important bugs reported there, that make one wonder why is not any other tool picking those fairly obvious things up. So thanks for the log!

**Comment by ffesti** [comment]
> There's some truly useless stuff in there, such as a "high" warning on "The '_RPMUTIL_H' include guard is already defined in the 'rpmutil.h' header. The 'rpmutil.h' header will be excluded from compilation." ... on the rpmutil.h file itself roll_eyes

It may be picking up the copy in include/

**Comment by ffesti** [comment]
OK, as everyone is just browsing the list...
If you see something that you think needs fixing or thorough investigation or you want to take on yourself please state so here in a comment.
I'll take on the following myself:

- http://repoclosure.openmandriva.org/fullhtml/sources/rpmvs.c_42.html#ln425
- http://repoclosure.openmandriva.org/fullhtml/sources/rpmpgp.c_6.html#ln598

**Comment by fedya** [comment]
@ignatenkobrain i know nothing about CI builds with PVS
but i can do regular rpm builds from git for you on OpenMandriva infrastructure if you need.

**Comment by Conan-Kudo** [comment]
We used to have coverity scans running on rpm. We might want to see if we can get that restored...

**Comment by pmatilai** [comment]
> We used to have coverity scans running on rpm

Did we? That would be news to me.

**Comment by Conan-Kudo** [comment]
Yep. Jeff had enabled it on the project using his account for about a year, I think? I saw some of the reports during that time. He used Coverity with rpm5 and turned it on for rpm too.

**Comment by ignatenkobrain** [comment]
Yes, I set it up at some point. IIRC you push to specific tag and it runs build... Florian might still remember how to do it

**Comment by pmatilai** [comment]
The report is gone from the net, but I think the important bits were salvaged and filed/fixed separately at the time. Setting up coverity would be nice but is a separate topic.

Thanks for the report!
