### ISSUE TITLE
Discussion: How to handle Python extras

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1061]
In Python, we have a concept of [extras](https://packaging.python.org/specifications/core-metadata/#provides-extra-multiple-use) a way to specify an optional dependency with the ability to install the software with that dependency enabled trough the "extra" part of a name in square brackets.

A real world example:
 - `cachecontrol` has an extra called `[filecache]` and it extras_requires `lockfile`
 - `poetry` requires `cachecontrol[filecache]`

This is what happens:
 - `pip install cachecontrol` installs `cachecontrol` without the `lockfile` dependency
 - `pip install cachecontrol[filecache]` installs `cachecontrol` with the `lockfile` dependency
 - `pip install poetry` installs `poetry` with the `cachecontrol[filecache]` dependency (with the `lockfile` dependency)

(I've omitted version specifiers from the examples to make them simpler. `pip install cachecontrol[filecache] < 5` means `cachecontrol < 5` with the `[filecache]` extras.)

## Naïve RPM idea

At first, this is the idea we had:

`python3-lockfile`:
 - Provides `python3.Xdist(lockfile)`

`python3-cachecontrol`:
 - Provides `python3.Xdist(cachecontrol)`
 - Provides `(python3.Xdist(cachecontrol[filecache]) if python3.Xdist(lockfile))`

`python3-poetry`:
 - Requires `python3.Xdist(cachecontrol[filecache])`

We were told that this is not possible:
- Rich provides are not available in RPM yet.
- Rich provides are a can of worms and most likely won't be available ever.

Notes:
- I cannot find where exactly this was said, feel free to provide more accurate information.
- If `[]` are not valid in provides/requires, we can encode this differently, such as `python3.Xdist(cachecontrol:filecache)` or similar -- that part s not so important in this context.

## Subpackages idea

The second idea we had (and packagers already do this somewhat similarly, but manually, in some cases) is to create meta(sub)packages with the extras:

`python3-lockfile`:
 - Provides `python3.Xdist(lockfile)`

`python3-cachecontrol`:
 - Provides `python3.Xdist(cachecontrol)`
 - Suggests `python3-cachecontrol+filecache = %{?epoch:%{epoch}:}%{version}-%{release}` (possibly)

`python3-cachecontrol+filecache`:
 - Provides `python3.Xdist(cachecontrol[filecache])`
 - Requires `python3.Xdist(lockfile)`
 - Requires `python3-cachecontrol = %{?epoch:%{epoch}:}%{version}-%{release}`
 - Has no files.

`python3-poetry`:
 - Requires `python3.Xdist(cachecontrol[filecache])`

The problem with this approach is:
 - Generating subpackages from provides/requires generators is hard (currently not possible?).
 - Possible bloat in total package count (however Python packages don't tend to have dozens of extras).

## Encoding reverse requirements in provides

Here is the new idea I've just got. It is a bit hackish, but I think it should work:

`python3-lockfile`:
 - Provides `python3.Xdist(lockfile)`

`python3-cachecontrol`:
 - Provides `python3.Xdist(cachecontrol)`
 - **Requires `(python3.Xdist(lockfile) if python3.Xextrasreq(cachecontrol[filecache]))`**

`python3-poetry`:
 - Requires `python3.Xdist(cachecontrol)`
 - **Provides `python3.Xextrasreq(cachecontrol[filecache])`**

Here is how that works:
 1. install `python3-poetry`
 2. `python3-cachecontrol` is dragged in, trough classic `python3.Xdist(cachecontrol)` dependency
 3. since `python3-poetry` provides `python3.Xextrasreq(cachecontrol[filecache])`, `python3-cachecontrol` now also requires `python3.Xdist(lockfile)`
 4. profit?

The `python3.Xextrasreq(...)` name is not perfect and might need to change.

We are able to generate those reverse requires/provides using the current tools.

I don't really like the idea that we say what a package depends on trough a field that is supposed to say what other packages may depend on to get this package. However we use Provides for all sorts of things already: `bundled(...)`, `deprecated()` etc. We will obviously need to document that manually requiring `python3.Xextrasreq(...)` is not useful and possibly ban it via policies.

@encukou @ignatenkobrain @Conan-Kudo @gordonmessmer @decathorpe Please provide feedback. I am especially interested in "this doesn't work, because..." kind of feedback and less in "this is so ugly we'd rather not have anything" (however "if we tweak it like this, it's nicer" is also appreciated).

**Comment by decathorpe** [comment]
I think the subpackages approach is simpler, and has a lower cognitive burden on the user than the "reverse provides requires rich dependencies" (that's a mouthful ...). I am also reluctant to introduce another source of "if" rich dependencies, which still aren't really correctly handled by some tools, not even some dnf commands (e.g. repoclosure)

Can we extend pyp2rpm to generate these "extras" subpackages automatically in the .spec files? rust2rpm does it this way for optional crate features.

**Comment by hroncok** [comment]
The idea is that we handle buildrequires and requires fully automatically, generating subpackages statically is a step back.

**Comment by decathorpe** [comment]
Well, it's better than nothing.

I don't think you can attach dependencies to virtual provides? Doing that would solve this issue ...

**Comment by hroncok** [comment]
> attach dependencies to virtual provides

I'm sorry, what do you mean by this?

**Comment by ignatenkobrain** [comment]
Dynamic subpackages is something what's already planned for the future.

**Comment by decathorpe** [comment]
> > attach dependencies to virtual provides
> 
> I'm sorry, what do you mean by this?

That wasn't well-specified, sorry ... I basically meant providing something that can require something - like a proper virtual package specifed by Provides that can also specify Requires. So, like a "virtual subpackage" without it being a "real package". Like you simulate it with your option 3.

**Comment by encukou** [comment]
I won't be able to think through all the edge cases soon to give you "this doesn't work, because..." kind of feedback. But "reverse requirements" do look viable.
I guess my question is: when can this be done, relative to proper support for dynamic subpackages?
* if later, or just a little sooner: Don't bother.
* if a bit sooner: Put it in pyproject macros as an implementation detail, but document that it shouldn't be done manually. As much as possible, ensure it can be easily switched to dynamic subpackages.
* if much sooner (years): Go for it all the way :)

---

@decathorpe
> I am also reluctant to introduce another source of "if" rich dependencies, which still aren't really correctly handled by some tools, not even some dnf commands (e.g. repoclosure)

That sounds like "if" rich dependencies are unfixably unreliable. Should they be deprecated?

@decathorpe
> Can we extend pyp2rpm to generate these "extras" subpackages automatically in the .spec files? rust2rpm does it this way for optional crate features.

pyp2rpm is a nice tool for initial packaging, but not useful for ongoing maintenance. It generates a specfile for you, but to update, you either need to put in upstream changes (good luck noticing changes in extras!), or re-generate the spec (throwing away any changes you made).
To make ongoing maintenance work, anything in pyp2rpm also needs to be doable manually. Instead of "extend pyp2rpm" you want to "change packaging guidelines"; pyp2rpm should follow those (if/when its dev(s) get to it).

@decathorpe
> I basically meant providing something that can require something - like a proper virtual package specifed by Provides that can also specify Requires. So, like a "virtual subpackage" without it being a "real package". Like you simulate it with your option 3.

Sorry, I don't understand. Do you have a better way of doing what "option 3" does, or are you asking if such a better way exists?

**Comment by hroncok** [comment]
> if later, or just a little sooner: Don't bother.
> if a bit sooner: Put it in pyproject macros as an implementation detail, but document that it shouldn't be done manually. As much as possible, ensure it can be easily switched to dynamic subpackages.
> if much sooner (years): Go for it all the way :)

This needs to be in python-rpm-generators, that's why I discuss this here. It can be done "immediately". @ignatenkobrain when can we expect dynamic subpackages?

**Comment by hroncok** [comment]
Note that the subpackages approach has a problem if an extra goes away and it was installed on user machine.

Obviously, if we loose extras that are still dependent on, any approach will generate broken dependencies; but with subpckages, any removed subpackages will need to be obsoleted, and I'm afraid that any rpm level automation cannot possibly have knowledge about "subpackages in the past".

**Comment by pmatilai** [comment]
@hroncok , dynamic sub-packages is nothing but a pink pony in our daydreams ATM, don't hold your breath waiting for that to happen.

**Comment by hroncok** [comment]
@pmatilai Thanks for confirmation :unicorn:

**Comment by ignatenkobrain** [comment]
> This needs to be in python-rpm-generators, that's why I discuss this here. It can be done "immediately". @ignatenkobrain when can we expect dynamic subpackages?

Hopefully as soon as @ffesti has time :)

---

@hroncok, the whole reason to not reimplement the wheel is that we already do this for rust packages.

**Comment by hroncok** [comment]
> we already do this for rust packages

You do what exactly?

**Comment by ignatenkobrain** [comment]
@hroncok generate bunch of subpackages for the optional features (extras) and support them.

**Comment by hroncok** [comment]
Can you do that automatically?

**Comment by ignatenkobrain** [comment]
> Can you do that automatically?

Yes, it is done in rust2rpm. It generates spec file with bunch of subpackages for each feature. And dependency generators support them, based on the name of subpackage, it extracts feature and adjust generation of Provides/Requires.

**Comment by hroncok** [comment]
So only trough an external tool. What we are looking at are possibilities to do this in fully automated fashion from the requirements generators.

**Comment by ignatenkobrain** [comment]
@hroncok of course that would be nice. And something what we have discussed with @ffesti. He even asked me to send sumup how we would use that in Rust: http://lists.rpm.org/pipermail/rpm-ecosystem/2020-February/000730.html

While there is no commitment or anything like that from anybody, I think there is a clear need for this feature and somebody just has to implement it. I guess Florian has some ideas how to actually do it in the code, but better to ask him.

**Comment by hroncok** [comment]
I still have no idea about what we would do with the obsoleted subpackages.

**Comment by ignatenkobrain** [comment]
They would depend on main package tied to NVR, and have broken deps after upgrade. And that should be just auto-removed by DNF (no such feature exists, but it is not very hard to implement in dnf.conf `autoallowremove=*+*`).

**Comment by hroncok** [comment]
So either we have a solution trough subpackages that is somewhat nice, but it requires a feature that is missing in RPM and a feature that is missing in DNF, or we do it trough reverse deps and that can be done right now, but is somewhat ugly?

**Comment by ignatenkobrain** [comment]
You can't properly do it right now. It would need to be expanded on buildtime, but buildtime requirements != runtime requirements.

**Comment by hroncok** [comment]
We know the runtime requirements during the build. What do you mena by this?

**Comment by hroncok** [comment]
Oh. There would be no way to buildrequire an extra. Is that what you mean? That's a problem.

**Comment by gordonmessmer** [comment]
> Note that the subpackages approach has a problem if an extra goes away and it was installed on user machine.

Maybe not a *huge* concern... setuptools' documentation tells developers not to do that.

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies  (final paragraph)

**Comment by hroncok** [comment]
Nice finding.

**Comment by ignatenkobrain** [comment]
You still need to be able to BR them because you'd want to run tests and whatnot.

**Comment by decathorpe** [comment]
@hroncok BTW, looks like there's already at least one python package in fedora that handles extras like rust handles optional features: [python-dask](https://src.fedoraproject.org/rpms/python-dask/blob/master/f/python-dask.spec)

**Comment by QuLogic** [comment]
Indeed, I modelled the subpackages after the Rust ones.

Also, maybe you can't do dynamic subpackages yet, but you could maybe do it with a macro, like Go does for its `-devel` packages.

**Comment by hroncok** [comment]
Here's my idea:

```lua
%python_extras_subpkg(n:i:f:) %{expand:%{lua:
    local value_n = rpm.expand('%{-n*}')
    local value_i = rpm.expand('%{-i*}')
    local value_f = rpm.expand('%{-f*}')
    local args = rpm.expand('%{*}')
    if value_n == '' then
        rpm.expand('%{error:%%%0: missing option -n (name of the base package)}')
    end
    if value_i == '' and value_f == '' then
        rpm.expand('%{error:%%%0: missing option -i (buildroot path to metadata) or -f (builddir path to a filelist)}')
    end
    if value_i ~= '' and value_f ~= '' then
        rpm.expand('%{error:%%%0: simultaneous -i (buildroot path to metadata) and -f (builddir path to a filelist) is not supported}')
    end
    if args == '' then
        rpm.expand('%{error:%%%0 requires at least one argument with "extras" name}')
    end
    local requires = 'Requires: ' .. value_n .. ' = %{?epoch:%{epoch}:}%{version}-%{release}'
    for extras in args:gmatch('%w+') do
        local rpmname = value_n .. '+' .. extras
        local pyname = value_n .. '[' .. extras .. ']'
        local pkgdef = '%package -n ' .. rpmname
        local summary = 'Summary: Metapackage requiring requires for ' .. pyname
        local description = '%description -n ' .. rpmname .. '\\\n' ..
                            'This is a metapackage bringing in requires for ' .. pyname .. '.\\\n' ..
                            'It contains no code, just makes sure the dependencies are installed.\\\n'
        local files
        if value_i ~= '' then
            files = '%files -n ' .. rpmname .. '\\\n' .. '%ghost ' .. value_i
        else
            files = '%files -n ' .. rpmname .. ' -f ' .. value_f
        end
        for i, line in ipairs({pkgdef, summary, requires, description, files, ''}) do
            print(line .. '\\\n')
        end
    end
}}
```

You'd put this to your specfile near other subpackage declarations:

```
%python_extras_subpkg -n python3-setuptools_scm -i %{python3_sitelib}/*.egg-info toml
```

It expands to:

```
%package -n python3-setuptools_scm+toml
Summary: Metapackage requiring requires for python3-setuptools_scm[toml]
Requires: python3-setuptools_scm = %{?epoch:%{epoch}:}%{version}-%{release}
%description -n python3-setuptools_scm+toml
This is a metapackage bringing in requires for python3-setuptools_scm[toml].
It contains no code, just makes sure the dependencies are installed.

%files -n python3-setuptools_scm+toml
%ghost /usr/lib/python3.8/site-packages/*.egg-info
```

The rest would be handled by the Python dist dependency generator (taking package name as argument, parsing out the `+toml` part of it, and finding extras named `toml` in the package, eventually providing `python3dist(setuptools_scm[toml]) = 1.2.3` and requiring whatever that requires. If extras `toml` is not found, the dependency generator will error ([somehow](https://github.com/rpm-software-management/rpm/issues/1183)).

Side note: The `-f` option allows to do:

```
%python_extras_subpkg -n python3-setuptools_scm -f %{python_extras_filelist} toml
```

When other automation is at play.

Side note 2: The subpackage should really require `python3-setuptools_scm%{?_isa}` if arched, but I am unsure how to detect if `python3-setuptools_scm` is arched or noarch, so I will just hope for the best :crossed_fingers:

**Comment by hroncok** [comment]
We have proposed this in Fedora: https://fedoraproject.org/wiki/Changes/PythonExtras

**Comment by ffesti** [comment]
It looks like this has landed in Fedora already. With the Python macros being in a separate package now I am closing this here assuming it is in there already or has to me merged there.
