### ISSUE TITLE
RFE: subdirectory handling in %autosetup

### ISSUE THREAD

**Issue by ueno** [rpm-software-management/rpm#1075]
In our package (nss), the release tarballs contain an extra directory hierarchy `nss-X.XX/nss`, while the upstream repo doesn't have it. So we need to use `pushd nss` and `popd` to apply patches from upstream.  This practice doesn't work well with `%autosetup`, and even if we split the call to `%setup` and `%autopatch`, SCMs other than quilt get confused.

It would be nice if there is a native way to support subdirectory inside tarballs.

**Comment by ffesti** [comment]
In rpm 4.18 %{buildsubdir} is now settable outside %setup. May be this can help with your use case.

The change can be found here: 6caca84c90

**Comment by dmnks** [comment]
FWIW, we're also considering/planning to turn this directive into an actual macro, tracked here: #1953

**Comment by dmnks** [comment]
Closing per above, please reopen if it doesn't resolve it for you.
