### ISSUE TITLE
New setexecfilecon() errors on chroot installs

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1077]
The "obviously correct" fix in commit  ab601b882b9d9d8248250111317615db1aa7b7c6 causes rpm --root installs to spit out errors that were not there before, eg

> error: setexecfilecon: (/usr/sbin/glibc_post_upgrade.x86_64) No such file or directory
  15:bash-4.4.19-2.fc28               ################################# [ 94%]
  16:libsepol-2.7-6.fc28              ################################# [100%]
error: setexecfilecon: (/bin/sh) No such file or directory
error: setexecfilecon: (/bin/sh) No such file or directory
error: setexecfilecon: (/bin/sh) No such file or directory

So setexecfilecon() has been routinely returning -1 but the buggy condition previously masked this.
Our own code that does seemingly the exact same thing "manually" does not exhibit this behavior on chroot installs. Whether its a bug in libselinux or rpm, it needs investigating and fixing.

**Comment by pmatilai** [comment]
Okay, the difference is rpm's own code doing:
```
    if (rc && security_getenforce() < 1)
        rc = RPMRC_OK;
```
versus libselinux setexecfilecon() doing:
```
    if (rc < 0 && security_getenforce() == 0)
        rc = 0;
```

When inside bare chroot with no /sys etc mounts, security_getenforce() fails. Rpm discards this, libselinux does not.

**Comment by ITwrx** [comment]
I'm new to rpm, selinux and systemd-nspawn, and i'm getting these errors when creating my containers. Do i have to wait on rpm 4.16 or is it safe to use the containers as-is?
thanks
