### ISSUE TITLE
Disallow buildrequires: inside %package section

### ISSUE THREAD

**Issue by socketpair** [rpm-software-management/rpm#1083]
Currently, `buildrequires` specified in `%package` work. But I think this is completely wrong and I think RPM should consider such things as mistakes.

In any case, documentation should be updated regarding whether it is allowed to add `buildrequires` inside `%package` section, or not.

**Comment by jasontibbitts** [comment]
I personally agree that it can be confusing, but I can't think of any technical reason why RPM would actively prevent it from working.  I think this is more of a distribution issue; different distributions can choose to enforce different guidelines for stylistic issues such as these if they wish.

**Comment by socketpair** [comment]
Yes, but I thought RPM does not scan %package sections while looking for `buildrequires`. Since it is not clearly documented, I can't consider current behaviour stable.

**Comment by ignatenkobrain** [comment]
Why should it disallow it?

**Comment by socketpair** [comment]
Well, guys. If this is allowed, it should be documented. If core RPM team considers it OK, I have no questions except missing documentation for that case.

**Comment by ffesti** [comment]
Well, if some sub packages are only build conditionally some build requires may also only be needed for this sub package. So having the BuildRequires right there makes the spec file easier and avoids separate conditional sections in the main package.

@socketpair Can you point out where exactly the documentation is unclear or ambiguous about BuildRequires, please?

**Comment by socketpair** [comment]
@ffesti There is no place, since documentation does not tell us whether we may use buildrequires inside `%package` section or not.

Moreover, documentation does not say exactly what macroses we can define right inside `%package` section, except `requires`, `version`, `summary` and `group`. (http://ftp.rpm.org/max-rpm/s1-rpm-subpack-spec-file-changes.html). For example, `license` ? (for cases where a plugin has a different license).

**Comment by pmatilai** [comment]
As a rule of thumb, %package can and is free to use everything that is in the main preamble, that's always been the case and that's why there's no special documentation about it. The "obvious" exception to the rule is Name: which is handled via %package argument.

Buildrequires is no different, and especially with conditional sub-packages the ability to place Buildrequires in the requiring sub-package is highly useful. No bug here.
