### ISSUE TITLE
Year 2038 plan for rpm

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1084]
All timestamps in rpm packages are 32bit and will roll over on 2038, and at least some APIs are also affected. As Enterprise distro lifespans are 10+ years, this is something that needs to be addressed in the near future.

Within rpm this can be relatively easily done using a similar approach as was used with 64bit file sizes, but that wasn't so smooth for the rest of the world which simply went on using the 32bit tags and only now are starting to notice the need to change.

One tempting possibility would be jumping to 64bit values across the board and declare new major version with that...

**Comment by pmatilai** [comment]
Hmm, actually the timestamps are uint32_t so they should be good until 2106, but this does need a proper investigation, and ultimately, move to 64bit types.

**Comment by Conan-Kudo** [comment]
> One tempting possibility would be jumping to 64bit values across the board and declare new major version with that...

I think it'd be a good impetus to examine the rpm format and start making changes to it to make a better package format for said new major version. I think there's definitely other warts we could address as a whole and improve for the rpm ecosystem (and potentially all package management), and this could be the avenue in which we could start exploring it.

**Comment by pmatilai** [comment]
Hold your horses. I'm not talking about a revolutionary new format, just a small evolutionary step to modernize, otherwise it's simply not going to happen.

**Comment by dralley** [comment]
>Hmm, actually the timestamps are uint32_t so they should be good until 2106, but this does need a proper investigation, and ultimately, move to 64bit types.

Just the timestamps, or all tag values?  The [docs](https://github.com/rpm-software-management/rpm/blob/master/docs/manual/tags.md#scalar-types) say that **all** tags are unsigned, but as mentioned on https://github.com/rpm-software-management/rpm/issues/1228 the type handling is pretty inconsistent, and the value itself is stored in an `int32_t`.

**Comment by pmatilai** [comment]
I recently fixed a couple of signed int time usages, the rest of the plan is here:
https://github.com/rpm-software-management/rpm/issues/1229#issuecomment-1920724526

No point breaking compatibility to be 80+ years future compliant.
