### ISSUE TITLE
Add a separate spec section for build configuration

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1086]
Configuring the sources (eg ./configure or cmake) is really a distinct step which is very unlike the actual build, in that the actual build steps are generally equal for all projects using a given build system, but configuration differs greatly once you go beyond the default paths and the like.

This is essentially a pre-requisite for implementing build system templating in spec files.

**Comment by ignatenkobrain** [comment]
Fully agree, what about `%build_prep` or `%configure_build`?

**Comment by pmatilai** [comment]
I'd prefer something shorter and simpler. %config is only special inside %files so that's one possibility, although best would be not having to overload existing directives.
