### ISSUE TITLE
debuginfo generator keeps debug files in buildroot if %excludes are listen in a noarch subpackage

### ISSUE THREAD

**Issue by ppisar** [rpm-software-management/rpm#1094]
I'm refactoring perl.spec and found a nuisance the debuginfo generator. The new form of perl.spec will be:

~~~~
# fullarch main package
%files

# noarch subpackage
%files foo

# full arch subpackge
%if %{condition}
%files bar
%{_libdir}/bar.so
%else
%exclude %{_libdir}/bar.so
%endif
~~~~

If the %condition is false, the build fails with an error that /usr/lib/debug/%{_libdir}/bar.so-%{VRA}.debug is installed but not packaged. The error message looks like the one in [https://github.com/rpm-software-management/rpm/issues/278]. I must emphasize that the %{_libdir}/bar.so library is indeed excluded and it's not included in any binary package.

I believe the reason is that if %condition is false, then the %exclude is placed to the previous noarch subpackage and the debuginfo generator probably ignores %excludes in noarch subpackages.

Would it be possible to improve the debuginfo generator to recognize the %excludes in noarch subpackages and delete corresponding debug files?

**Comment by pmatilai** [comment]
%exclude is not meant to be used this way, it's only intended to signal a file belonging to another subpackage. In rpm >= 4.17 this will be enforced, anything in buildroot must be packaged: #994.

The correct way to deal with this is to rm -f any unwanted content from the buildroot at end of %install.
