### ISSUE TITLE
RFE: ignore BuildRequires with prefix 'external:'

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/rpm#1100]
Can you please ignore in rpmbuild all BuildRequires with prefix 'external:'? E.g.:

  BuildRequires: external:rubygem(foo)
  BuildRequires: external:pypi(bar)

Not everything is packaged as rpm. Sometimes you need one library, but transitively it requires a dozen other modules. While in Fedora/RHEL world you must package all these requirements, in the wild world e.g small shops, hackers can see this as a big obstacle. Especially when you can, in fact, install those modules using native utilities like pip or gem.

The actual work will be done in Mock. Everything we need is just that rpmbuild will ignore those dependencies. The semantics would be that if 'dnf builddep' returns 'external:rubygem(foo)' then Mock will run 'gem install foo' in the buildroot and then run rpmbuild. Rpmbuild will ignore this BR as it should be managed by layered tool (Mock in this case).

Note: I am talking just about build dependencies for now. Runtime dependencies are out of scope.
And I am not saying that this should be actually used in Packaging Guidelines. Just technically possible.

I would guess that we can filter it at:
https://github.com/rpm-software-management/rpm/blob/master/build/spec.c#L346

I am pretty fine if rpmbuild would print some warning when such BR are detected. But it should not be fatal.

**Comment by Conan-Kudo** [comment]
That defeats the point of rpm itself, why would we do this? Rpm aims to be able to have consistent validation of dependencies.

If you want it to be "ignored", you could easily make mock generate a dummy package that would have those satisfied deps, which you can identify by doing something like `rpmspec -q --srpm --requires foo.spec | grep 'external:'` and do the right thing here.

It not sensible to add something like this to rpm's build handler to avoid dependency satisfiability.

**Comment by xsuchy** [comment]
> That defeats the point of rpm itself, why would we do this? Rpm aims to be able to have consistent validation of dependencies

I found it as better (read easier) solution to teach rpm how to handle other package managers (pip, gem...)

> you could easily make mock generate a dummy package that would have those satisfied deps

Hmm, I like this idea.

**Comment by xsuchy** [comment]
I am closing this in favour of http://miroslav.suchy.cz/blog/archives/2020/05/05/new_project_-_create-fake-rpm/index.html
