### ISSUE TITLE
 lsetfilecon: (/proc, system_u:object_r:default_t:s0) Operation not supported

### ISSUE THREAD

**Issue by syyhao1994** [rpm-software-management/rpm#1103]
https://bugzilla.redhat.com/show_bug.cgi?id=1722766

I encountered a problem which has been reported to redhat.

I approve the opinion proposed by Jeff Bastian:
/boot/efi is a vFAT filesystem which does not supported the extended attributes needed to store an SELinux label.  dnf (or rpm or selinux-policy) should not be trying to set a label on these files.

After confirmation, it seems the problem of plugin in rpm:
plugins/selinux.c:53:    sehandle = selabel_open(SELABEL_CTX_FILE, opts, 1);

So when i install the package,  the error comes up.
error: lsetfilecon: (/boot/efi/EFI/openEuler/fonts, system_u:object_r:boot_t:s0) Operation not supported.

This log is not printed of rpm 4.14(it is actually exist but just don not print the error ),when i update the rpm version to 4.15.1, the error is printed out.

Thank you.

**Comment by pmatilai** [comment]
Fixed in commit 4a71a3eccd7e9e14ee0e83b1cb300386a93622cd already, just not in any released version yet.

**Comment by syyhao1994** [comment]
> Fixed in commit [4a71a3e](https://github.com/rpm-software-management/rpm/commit/4a71a3eccd7e9e14ee0e83b1cb300386a93622cd) already, just not in any released version yet.

Thank you. I got it.

**Comment by pmatilai** [comment]
Releasing 4.15.2 is starting to look unlikely, closing. The patch is simple and easy to backport for whoever might need it. Thanks.
