### ISSUE TITLE
Question: the way to check if "load" macro is built-in in a spec file

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpm#1104]
Sorry for my multiple post about this topic.

Yesterday I posted below email to rpm-list mailing list, could you comment for this? 
http://lists.rpm.org/pipermail/rpm-list/2020-March/002013.html

Feel free to close this GitHub issue page, if you like.

Thanks for your help.

**Comment by voxik** [comment]
This is the original `load` macro I have implemented for Ruby with some references:

https://src.fedoraproject.org/rpms/ruby/c/8e2921fd5a3125b7ce2487bb449b2e6db40cc3c0

Not sure what causes the `error: /path/to/ruby/load.inc: line 30: Macro %load is a built-in (%define)` error. It might be some recent change in RPM.

Just FTR, I have tested the SRPM build and it seems to work just fine with `rpm-4.14.2.1-5.fc30.x86_64` while it errors out with `rpm-4.15.1-2.fc32.x86_64`

**Comment by junaruga** [comment]
Possibly here is a part of the logic causing the error.

https://github.com/rpm-software-management/rpm/blob/10127cdb2364de2c1408950a25b730920e665689/rpmio/macro.c#L638-L641

Here is the testing code to test the logic.

https://github.com/rpm-software-management/rpm/blob/10127cdb2364de2c1408950a25b730920e665689/tests/rpmmacro.at#L28-L40

The change causing the error comes from the commit: https://github.com/rpm-software-management/rpm/commit/d86c0c28ab74686c59c81a38d04210f70456ce63 for the logic, and the commit: https://github.com/rpm-software-management/rpm/commit/9343ecd94cd873e6dc1c06428975163cbb9cf9af for testing code.

**Comment by voxik** [comment]
This is intentional change and the explanation is here in the [commit message](https://github.com/rpm-software-management/rpm/commit/9343ecd94cd873e6dc1c06428975163cbb9cf9af). Since you are using new RPM to build SRPM which is targetting older system, now it is probably time to find some workaround. E.g. test the existence of `%load` built-in.

**Comment by junaruga** [comment]
I tried following code in the `ruby.spec`.
But is there a way to check if the `load` builtin macro exists?
The part `%{defined load}` in the following code fails with `error: /home/jaruga/git/rh-packages/scl/rh-ruby27/ruby/ruby.spec: line 99: failed to load macro file 0`.

```
if %{defined load}
%{?load:%{SOURCE4}}
%{?load:%{SOURCE5}}
%else
%include %{SOURCE100}
%{load %{SOURCE4}}
%{load %{SOURCE5}}
%endif
```

Or is there a macro to check the used rpm version is >= 4.12.0 or not?

https://rpm.org/user_doc/macros.html
> %{load:...}         load a macro file (in >= 4.12.0)

**Comment by voxik** [comment]
May be you could use alternative approach:

~~~
%{?load:%{SOURCE4}}
%if %{undefined some_known_macro_from_the_SOURCE4}
%include %{SOURCE100}
%{load %{SOURCE4}}
%endif
~~~

**Comment by mlschroe** [comment]
If you want hacks you can do something like:
```
%if "%{load:/dev/null}" == ""
```

**Comment by junaruga** [comment]
Guys, thanks for your info! It's useful.

For the hacks, it looks working.

With the RPM 4.15.1.

```
$ rpm --version
RPM version 4.15.1

$ rpm -E '%{load:/dev/null}'
 <= empty
```

With the RPM 4.11.3.

```
<mock-chroot> sh-4.2# rpm --version
RPM version 4.11.3

<mock-chroot> sh-4.2# rpm -E '%{load:/dev/null}'
%{load:/dev/null}
```

**Comment by junaruga** [comment]
Many thanks! As I could fixed the issue by the following way, I would close this ticket.

```
# Call load builtin macro if it is defined, otherwise call own load macro
# to avoid an error by creating SRPM in RPM 4.15+
%if "%{load:/dev/null}" == ""
%{?load:%{SOURCE4}}
%{?load:%{SOURCE5}}
%else
%include %{SOURCE100}
%{load %{SOURCE4}}
%{load %{SOURCE5}}
%endif
```
