### ISSUE TITLE
rpmbuild provides python3dist(xxxx) = xx.x, missing 0

### ISSUE THREAD

**Issue by syyhao1994** [rpm-software-management/rpm#1113]
I found that that some python packages provides python3dist(xxxx) with wrong version after i update the rpm to 1.15.1.
https://koji.fedoraproject.org/koji/rpminfo?rpmID=20318804
Such as the link listed, the python3-attrs-19.3.0-2.fc32.noarch.rpm provides python3dist(attrs) = 19.3, but it should be python3dist(attrs) = 19.3.0.
Looking forward from hearing from you.

**Comment by Conan-Kudo** [comment]
This is intentional behavior. It was intentionally changed in 4c8b584074061c606883ce3f18c8c9024d8610f5 to better fit the EVR comparison logic in RPM.

Python versions equate 19.3 and 19.3.0, but RPM does not, so we had to drop the leading zeros to ensure the behavior was the same as Python's.

**Comment by syyhao1994** [comment]
> This is intentional behavior. It was intentionally changed in [4c8b584](https://github.com/rpm-software-management/rpm/commit/4c8b584074061c606883ce3f18c8c9024d8610f5) to better fit the EVR comparison logic in RPM.
> 
> Python versions equate 19.3 and 19.3.0, but RPM does not, so we had to drop the leading zeros to ensure the behavior was the same as Python's.

Thank you for your reply. I got it.
