### ISSUE TITLE
Is there RPM file list accesible in LUA?

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1117]
Looking at the symlink <-> directory replacements scripts [[1]], I wonder if there is a way to access the RPM file list from LUA, because it is rather strange, that the scriptlet is supposed to define the path, which can be pretty random one. It would be much better, if the scope could be limited to the files managed by the current RPM being handled.

[1]: https://docs.fedoraproject.org/en-US/packaging-guidelines/Directory_Replacement/

**Comment by pmatilai** [comment]
It is not.

The thing is, it's not just the package's own file list you'd need, it'd need access to the rpmdb to look up what else might be there, and that isn't what the scripts are for, really.
