### ISSUE TITLE
%force file list directive

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1118]
Thinking about symlink <-> directory conversion, wouldn't be possible to have something like `%force` file list directive? That would do something like "remove whatever is standing in a way, be it file/directory/symlink and place there content from this RPM".

**Comment by voxik** [comment]
Alternatively, I can also imagine more specific `%replace_{symlink,directory}` where RPM would know what was expected there and what is the replacement.

On top of that, RPM could automatically create backup and own the backup, so it is removed when RPM is removed.

**Comment by mlschroe** [comment]
It's not so easy, it needs some changes in rpm's aliasing detection code (i.e. symlinked directories) so that the rpm internals know what's going on.

I'm already working on this, but the development has been stalled the last weeks due to other work needing to be done first.

**Comment by pmatilai** [comment]
Whatever "it" may be, it's not going to be a force anything out of the way. Such a decision cannot be left up to a random package.
