### ISSUE TITLE
Handling of files during installation via hooks

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1120]
This is third idea in my series of handling symlink <-> directory conversion. Would it be possible to mark files, which should have some special treatment and process them via some hook? E.g. if the there is `%hook somefile` listed in `%files` section, for every action above this file, some scriptlet would be called.

E.g. if RPM compares the files on this with what is going to be installed, that would be one action, other action would be the installation itself, etc.

**Comment by ffesti** [comment]
Well, we already have `%pretrans` scriptlets which allow the packagers to do arbitrary stuff. We don't need a second mechanism like that. Labeling the files needing special treatment is a possible solution for the symlink problem but is not something we need a separate ticket for. Closing
