### ISSUE TITLE
Migrate away from Zanata

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1131]
Zanata is apparently in the process of being shut down. Migrate away to some other translation platform.

For added bonus, get rid of that annoying po/ noise in our git tree.

**Comment by Conan-Kudo** [comment]
@Jibec Can you help us move to the new Weblate based setup?

**Comment by Jibec** [comment]
Of course, but most of the job you can do yourself.
@m-blaha : can you please apply the same of what you did for dnf?
I'm unsure you need any help from me now that you did it for four components.

could you please discuss together the full list of project that can be translated in rpm-software-management group? ;)
All of them are welcome, there is no limit.

**Comment by pmatilai** [comment]
Hold your horses - what exactly is dnf using? Weblate okay, but which instance?

**Comment by m-blaha** [comment]
@pmatilai https://translate.fedoraproject.org/projects/dnf/

**Comment by pmatilai** [comment]
Ok, thought so - as a principle, rpm cannot use distro-specific instances to maintain an air of an independent upstream.

**Comment by Conan-Kudo** [comment]
@pmatilai You'll then need to sign up for something with weblate.org.

**Comment by Jibec** [comment]
It make sense. Here are some information to help you to make your choice.

Using Fedora instance only requires user to have a FAS account. No complex workflows or approval of any kind.

Benefits I see is consistency with ecosystem (mostly RPM). And have a structured community to interact with.

We are consistent with Fedora values: we translate upstream content, and not what is specific to Fedora.

We do host projects outside of Fedora perimeter. Just part of the Linux ecosystem (such as pulseaudio).

If translate.fedoraproject.org isn't your choice, hosted.weblate.org may also host you if you ask them.

Just ping me if you need advices in your migration (wherever you go).

**Comment by pmatilai** [comment]
Migrated to Weblate in last August, forgotten to close.
