### ISSUE TITLE
error: parse error in expression:  %{__isa_bits} == 64

### ISSUE THREAD

**Issue by dwrobel** [rpm-software-management/rpm#1133]
Compiling [fixedptc](https://src.fedoraproject.org/rpms/fixedptc/blob/master/f/fixedptc.spec#_57) package failed in koji as follows:
```
error: parse error in expression:  %{__isa_bits} == 64
error:                             ^
error: /builddir/build/SPECS/fixedptc.spec:57: bad %if condition:  %{__isa_bits} == 64
```
Full log is available [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=42724782).

However, I didn't observe similar problem while building in copr [here](https://download.copr.fedorainfracloud.org/results/dwrobel/fixedptc/fedora-rawhide-x86_64/01311349-fixedptc/).

Was there any recent change in the syntax or in the parser?

**Comment by ignatenkobrain** [comment]
No. `0%{__isa_bits} == 64` should be the proper syntax.

**Comment by dwrobel** [comment]
Both versions:
- [%if %{__isa_bits} == 64](https://src.fedoraproject.org/rpms/fixedptc/c/d9cb4b48e03e49b8865b20dacbfb81ef3192896a?branch=a420237f72f3d48a762fa6e967d3c38a443d59b0)   - works on rawhide on local mock and [copr](https://copr.fedorainfracloud.org/coprs/dwrobel/fixedptc/build/1315874/) and fails on [koji](https://koji.fedoraproject.org/koji/taskinfo?taskID=42724782).
- [%if 0%{__isa_bits} >= 64](https://src.fedoraproject.org/rpms/fixedptc/c/a420237f72f3d48a762fa6e967d3c38a443d59b0?branch=a420237f72f3d48a762fa6e967d3c38a443d59b0) - works on rawhide on local mock and [copr](https://copr.fedorainfracloud.org/coprs/dwrobel/fixedptc/build/1315877/) and fails on [koji](https://koji.fedoraproject.org/koji/taskinfo?taskID=42736337)

koji log (excerpt):
```
error: parse error in expression:  0%{__isa_bits} >= 64
error:                              ^
error: /builddir/build/SPECS/fixedptc.spec:57: bad %if condition:  0%{__isa_bits} >= 64
```
How this can be explained?

**Comment by pmatilai** [comment]
You can't use ISA macros in a noarch package.
That it only fails in koji could be considered a bug in how rpm loads the platform macros unless specifically using --target (which is what koji does), but that's beyond the scope here.

**Comment by dwrobel** [comment]
Thank you for the explanation.

> 0%{__isa_bits} == 64 should be the proper syntax.

BTW, I used originally "%if %{__isa_bits} == 64" as I found it in the official documentation [here](https://rpm.org/user_doc/arch_dependencies.html). Please consider to correct it, if without `0` it is somehow incorrect.
