### ISSUE TITLE
"PyCapsule_New called with null pointer" when get package header

### ISSUE THREAD

**Issue by tkdchen** [rpm-software-management/rpm#114]
Get this error when doing in these ways

```
rpm.spec('rpm.spec').packages[0].header
```

However, it works

```
spec = rpm.spec('rpm.spec')
spec.packages[0].header
```

``python2-rpm-4.13.0-0.rc1.46.fc25.x86_64``

**Comment by pmatilai** [comment]
Fixed in commit 34b61a1f82f6f9b675ab4ca820b6255af63680f1
