### ISSUE TITLE
RFE: Add variable arrays to rpm

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#1149]
Right now a lot of things need special tags in rpm just because they can be declared multiple times (for example `Requires`).

Tags are hugely inconvenient to manipulate in spec automations because they all come with their special handling requirements.

Please add real array primitives to rpm, so they can be replaced by bog standard rpm variables (I believe this would simplify lua bindings a lot too; lua makes heavy array use)

ie the usual non rocket science:

```rpm
%global array [a,b,c]
%append array [d,e]
%array %= [a,b,c]
%array %+= [d,e]
```

**Comment by pmatilai** [comment]
Macro arrays would be useful every now and then, yes.

OTOH by the time you need arrays you typically need loops and the like, which is what we have Lua for. I'm not saying "no" to this but in general I rather put an effort into making Lua more usable in macros than implement new things in the macro "language" itself.

**Comment by nim-nim** [comment]
It’s not a lua vs non-lua thing. I’m an heavy lua user myself. I expect that this feature would unlock more lua use, not less.

While very cool and useful, lua is ultimately limited by the stage at which lua expressions are evaluated. So, no matter how much lua you add to a spec, you need, at some point, to communicate with the non-lua part of the spec. Practically, that means rpm variables.

So, the native rpm array primitive is not needed because you can not do arrays in lua itself. It is needed to pass arrays from lua to non lua (and vice versa).

**Comment by pmatilai** [comment]
There are no *variables* in rpm. There are only macros, and %{lua:...} is nothing more, nothing less than a means to generate macro content programmatically.

**Comment by pmatilai** [comment]
That said, I'm thinking more about further blurring the line between %{lua:...} and the native rpm macro subsystem. For example, could we expose Lua tables (and/or other variables) as native macro elements.

**Comment by nim-nim** [comment]
That would be awfully nice. The more native elements (macros variable tags) can be manipulated/set/unset from lua, the less we need to worry about the legacy rpm tangle. I don’t think anyone wants to write and maintain complex logic using the native rpm macro language, it’s just that pushing data over the lua/rpm native wall (in both directions) is not as easy and convenient as it should be.

**Comment by ffesti** [comment]
I guess the overall direction of rpm development is to rather add more lua than adding more to the macro language. So I am closing this here as this is not likely to happen any time soon... well any time actually.
