### ISSUE TITLE
RFE: Reimplement pythondeps.sh as parametric macro generators

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1152]
I want to work on this and I've opened this issue to track it.

`pythondeps.sh` is written in shell and unlike the Python dist generators, it uses no Python, it plainly determines the provide / requirement from the path. As the file is run for every Python file, we are potentially doing hundreds of shelling outs to execute a script that calls grep and sed.

One thing that is not clear to me [from the docs](https://rpm.org/user_doc/dependency_generators.html):

Is the lua implementation supposed to go to the [python.attr](https://github.com/rpm-software-management/rpm/blob/master/fileattrs/python.attr) file directly?

**Comment by pmatilai** [comment]
> Is the lua implementation supposed to go to the [python.attr](https://github.com/rpm-software-management/rpm/blob/master/fileattrs/python.attr) file directly?

Yes. I'll clarify the docs.
