### ISSUE TITLE
RFE: %_duplicate_files_terminate_build

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1158]
Would it be possible to have an option to make files listed twice a hard error?

Similarly how `%_unpackaged_files_terminate_build` works, I imagine `%_duplicate_files_terminate_build`.

Example:

```
%files
/a
/a

...

warning: File listed twice: /a
```

```
%global _duplicate_files_terminate_build 1

%files
/a
/a

...

error: File listed twice: /a
build failed
```

This would come handy when testing some code that generates filelists:

```
%global _duplicate_files_terminate_build 1

%files -l %{myfiles}
# explicitly listed bindir/foo, making sure it is not in myfiles
%{_bindir}/foo
```

Because currently I can only do it this way:

```
%check
# remove bindir/foo, will fail the build if it was listed in myfiles
rm %{buildroot}%{_bindir}/foo

%files -l %{myfiles}
```
And that is rather ugly.

Thanks.

**Comment by pmatilai** [comment]
I'd perhaps call it duplicate_files_terminate_build to avoid wise-ass "but what about three or more" remarks, but other than that, sure. Thanks for the idea.

**Comment by ignatenkobrain** [comment]
If this ever becomes the thing... First we need to fix https://github.com/rpm-software-management/rpm/issues/336.

**Comment by pmatilai** [comment]
This can be implemented whenever, making it a default is a whole other question.

**Comment by hroncok** [comment]
Renamed to `%_duplicate_files_terminate_build`.

**Comment by hroncok** [comment]
To make it clear, I don't want this to be the default. I intent to use this for testing purposes only.

**Comment by pmatilai** [comment]
Yup, that's how I understood it.
