### ISSUE TITLE
Duplicate provides not merged (manual + fileattr)

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1166]
Have this spec file:

```
Name:           python3-double-provides
Version:        0
Release:        0%{?dist}
Summary:        ...
License:        MIT
BuildArch:      noarch

# This adds the provides manually provided below
BuildRequires:  python3-rpm-generators >= 11

# Manually add the provides added by the above
Provides:       python-double-provides = %{version}-%{release}
Provides:       python38-double-provides = %{version}-%{release}

%description
...

%install
touch %{buildroot}/a

%files
/a
```

And build it in Fedora rawhide.

Look at the provides:

```
$ rpm -qp --provides /var/lib/mock/fedora-rawhide-x86_64/result/python3-double-provides-0-0.fc33.noarch.rpm 
python-double-provides = 0-0.fc33
python-double-provides = 0-0.fc33
python3-double-provides = 0-0.fc33
python38-double-provides = 0-0.fc33
python38-double-provides = 0-0.fc33

$ rpmlint /var/lib/mock/fedora-rawhide-x86_64/result/python3-double-provides-0-0.fc33.noarch.rpm 
...
python3-double-provides.noarch: E: useless-provides python-double-provides
python3-double-provides.noarch: E: useless-provides python38-double-provides
...
```

I would expect that duplicate provides are merged.

For example, when doing this:

```
Provides:       python-double-provides = %{version}-%{release}
Provides:       python-double-provides = %{version}-%{release}
Provides:       python-double-provides = %{version}-%{release}
Provides:       python-double-provides = %{version}-%{release}
```

The resuting RPM has the provide only once.

I believe this is a bug when manual provides are merged with manual provides, fileattr provides are merged with fileattr provides, but manual provides are not merged with fileattr provides.

**Comment by pmatilai** [comment]
This is an old problem, not specific to 4.16 at all. Those provides will have different flags in them, which prevents them from being merged (in existing implementation). Similarly this will create three different requires:

```
Requires: /bin/sh
Requires(post): /bin/sh
Requires(pre): /bin/sh
```

Here the latter two could technically be merged, but the first one not because there's no separate bit for a manually specified non-qualified dependency (ie it's flags 0, which can't be combined with others while preserving the information).

**Comment by hroncok** [comment]
Would it be to hackish to merge 0 with whatever is generated by generators, preserving 0 (as in: the manual one wins over the generated one).

**Comment by hroncok** [comment]
And as a side note, I suppose I cannot read the existing provides from the dependency generator?

**Comment by soig** [comment]
Merging manual provides with automatic provides (with manual ones
overriding automatic ones) would prevent us to detect manual provides that
can be removed b/c the automation took care of it…

Le mar. 7 avr. 2020 à 13:09, Miro Hrončok <notifications@github.com> a
écrit :

**Comment by hroncok** [comment]
Fair enough. I'll workaround it by recommending to remove the manual provides.
