### ISSUE TITLE
Ocaml dependency generators running on all ELF files

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1173]
While looking at dependency generation performance, noticed that PR #1070 causes OCaml dependency generators to execute on *all* ELF files it ever encounters, because of this:

```
+%__ocaml_magic         ^(ELF|Objective caml|OCaml) .*$
+%__ocaml_path          .(cma|cmi|cmo|cmx|cmxa|cmxs)$
```

What makes it particularly bad is that this is shipped with rpm-build itself, so it affects *everything*.
For example eg kernel dependency generation to take 50+ seconds on my laptop when previously it was some 30+ seconds. We need to be more selective here, one way or the other. 

The current rule matches *either* magic or path as OCaml files, but was the intention to match only if both match? @olafhering , @rwmjones ?

**Comment by olafhering** [comment]
Well, of course it is supposed to be `magic && path`. Are you saying rpm can not do that?

And if it can do `&&`, how?

**Comment by mlschroe** [comment]
Of course rpm can do that, you need to put "magic_and_path" in the flags.
```
%__ocaml_flags magic_and_path
```

**Comment by pmatilai** [comment]
> Well, of course it is supposed to be magic && path.

Okay, cool, just needed to make sure. I'll submit a PR in a sec.

**Comment by rwmjones** [comment]
At least it doesn't need another OCaml rebuild in Fedora :-)

**Comment by pmatilai** [comment]
Heh, yeah. Thanks guys for the fast replies.
