### ISSUE TITLE
Remove nss backend from rpm

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#1175]
The NSS backend for rpm is slow and painful to deal with. The NSS library often changes in ways that somehow breaks rpm, and these days upstream doesn't care about non-Firefox consumers of NSS.

Let's just drop it so that people don't have to keep suffering.

**Comment by pmatilai** [comment]
In time, sure. Right now seems a bit premature for our glacial nature though.
When it eventually does go, it belongs to a mausoleum to forever remind us of the the pain.

**Comment by Conan-Kudo** [comment]
At least can it be deprecated like beecrypt is?

**Comment by pmatilai** [comment]
Be my guest...
