### ISSUE TITLE
NEVR provides in source package lead to rpmbuild errors

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1189]
This is a regression caused by commit 75ec16e660e784d7897b37cac1a2b9b135825f25. The provides added to the source rpms will be checked against the dependencies of the installed packages. Because of this you will get an error if you try to build an rpm where the package name matches a conflict of an installed package.

I.e.:
```
error: Failed build dependencies:
        bash <= 2.0.4-21 conflicts with (installed) setup-2.8.71-2.fc20.noarch
```

**Comment by pmatilai** [comment]
Ack, I'll look into it. Thanks for reporting.

**Comment by mlschroe** [comment]
I wonder if the added provides also can lead to problems if we have a transaction with both source and binary packages. The provides from the source packages must not satisfy the dependencies of the binary packages.

Another thing to test would be a spec file that has a BuildRequires to one of the packages it builds. For example, gcc.spec might have a `BuildRequires: gcc`.

**Comment by pmatilai** [comment]
> Another thing to test would be a spec file that has a BuildRequires to one of the packages it builds. For example, gcc.spec might have a BuildRequires: gcc.

This case is indeed affected too, but also cured by  #1192. However the commit message end comments in the PR are off the mark a bit, I'll update...

**Comment by mlschroe** [comment]
Why is that cured by #1192? It just changes things for conflicts of installed packages. My example was about a build requires being satisfied by a provides of a source package. I think this needs to be fixed in rpmal.c

**Comment by pmatilai** [comment]
Oops, false testing+thinking on my behalf. Too much disturbance in the force today...

**Comment by pmatilai** [comment]
Okay, now it should really be covered by #1192.
