### ISSUE TITLE
Build failure: Missing AUDIT_SOFTWARE_UPDATE

### ISSUE THREAD

**Issue by h1z1** [rpm-software-management/rpm#1201]
```
audit.c: In function 'audit_tsm_post':
audit.c:83:43: error: 'AUDIT_SOFTWARE_UPDATE' undeclared (first use in this function)
      audit_log_user_comm_message(auditFd, AUDIT_SOFTWARE_UPDATE,
                                           ^
audit.c:83:43: note: each undeclared identifier is reported only once for each function it appears in
```

Added in https://github.com/rpm-software-management/rpm/blob/ad16a04b6e41612cdef6ab8755ad31c8b880a9fd/plugins/audit.c#L83

Requires libaudit userspace >= 2.8.5 

https://github.com/linux-audit/audit-userspace/commit/a6127fd84d0b41fa06282f05e606df17ab1302c7

**Comment by pmatilai** [comment]
Yeah, use a newer library or disable at configure time: `--without-audit`.
