### ISSUE TITLE
4.15.1: multiple "-a<num>" parameters in %autosetup are not handled correctly

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#1204]
Looks like if it is something like:
```
%prep
%autosetup -a1 -a2 -a3
```
only Source0 and Source1 will be unpacked. Probably it will be necessary to copy some parts from %setup so theoretically it should be easy to fix.

**Comment by ignatenkobrain** [comment]
This is known bug. %setup is not really a macro, but rather something which is parsed by RPM internally. However, %autosetup is a real macro, so it parses only last `-a` argument.

**Comment by pmatilai** [comment]
See #462 / #546 , this is a limitation of the macro machinery.

**Comment by nim-nim** [comment]
If you wanted to fix %autosetup for multiple archives you’d need to change it to behave the same way as %forgesetup/%forge_prep:

1. move things you’re used to pass on the macro CLI to control variables attached to a specific source file, using naming tricks to implement the attachment
2. make the bettersetup atom process a single archive
3. loop over archives that need processing, calling one bettersetup atom a time, un-stacking the control variables that correspond to the archive being processed

A single multiplexing call is quite hard to achieve in generic software and completely above the capabilities of the current rpm argument parser.

(the %auto_ framework I posted contains all the basic building blocks to create such looping macros, but you still need to assemble the building blocks in your own bettersetup implementation)
