### ISSUE TITLE
find_lang --all-name --with-qt fails with some KDE packages

### ISSUE THREAD

**Issue by Pulfer** [rpm-software-management/rpm#1205]
find_lang --all-name --with-qt fails to parse locales with some KDE packages. At least with kreport and kirigami2.

$ cat kreport.lang 
%lang(LC_MESSAGES/kreport_qt) /usr/share/locale/af/LC_MESSAGES/kreport_qt.qm
%lang(LC_MESSAGES/kreport_qt) /usr/share/locale/ar/LC_MESSAGES/kreport_qt.qm
%lang(LC_MESSAGES/kreport_barcodeplugin_qt) /usr/share/locale/ast/LC_MESSAGES/kreport_barcodeplugin_qt.qm
%lang(LC_MESSAGES/kreport_mapsplugin_qt) /usr/share/locale/ast/LC_MESSAGES/kreport_mapsplugin_qt.qm
%lang(LC_MESSAGES/kreport_qt) /usr/share/locale/ast/LC_MESSAGES/kreport_qt.qm
%lang(LC_MESSAGES/kreport_webplugin_qt) /usr/share/locale/ast/LC_MESSAGES/kreport_webplugin_qt.qm
...

@proyvind

**Comment by ffesti** [comment]
This seems to be fixed or at least does no longer happen with the current Fedora kreport package.
