### ISSUE TITLE
Built-in %{S:...} and %{P:...} macro stupidity in 4.16

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1206]
> [pmatilai🎩︎lumikko ~]$ rpm --eval '%(date +"%H:%M:%S")'
error: %S: argument expected

This is caused by commit c5909bd8698e56ffa4d1bb380116d61d6b48b8dd, and easily worked around with %%S, but this seems dumb as the built-in primitives don't take arguments in the non-%{} form at all:

> [pmatilai🎩︎lumikko ~]$ rpm --eval '%S'
error: %S: argument expected
[pmatilai🎩︎lumikko ~]$ rpm --eval '%S:1'
error: %S: argument expected
[pmatilai🎩︎lumikko ~]$ rpm --eval '%{S:1}'
%SOURCE1

It's tempting to let the non-bracketed form fall silently through because it cannot take arguments anyway, but then that makes it inconsistent with built-ins that do not take arguments, such as %getconfdir. It's kinda tempting to require brackets for all built-ins, but then there are %define and friends where the bracket form doesn't make any sense (or does strange things).

I suppose a middle ground could be requiring brackets for all the built-ins that are expected to expand to some text (ie having builtins->func set), and just fall through otherwise.

Thoughts?

(Even more tempting would be axing these IMO silly %S/%P shorthand macros, but to my surprise they're so popular that's not really an option.)

**Comment by ignatenkobrain** [comment]
I love those shortcuts for %SOURCE ;) Though I always use `%{S:…}` syntax.

I think

> I suppose a middle ground could be requiring brackets for all the built-ins that are expected to expand to some text (ie having builtins->func set), and just fall through otherwise.

would be good enough.

**Comment by pmatilai** [comment]
The %{S:...} syntax is the only thing that ever worked for the shortcut, so it's the only thing you could've used :)

**Comment by sbrown44** [comment]
This also breaks rpm for spec files with scripts that might try to use date formatting

**Comment by pmatilai** [comment]
> ...seems dumb as the built-in primitives don't take arguments in the non-%{} form at all:

...but they do now:

> $ rpm --eval '%S 1'
%SOURCE1

So this has become kinda moot in the meanwhile.
