### ISSUE TITLE
'#' symbol to ignore a macro statement does not valid. 

### ISSUE THREAD

**Issue by leemgs** [rpm-software-management/rpm#121]
We sometimes use "#" symbol to append some contents in ./spec file. This issue describes incorrect operation of "#" symbol in case that we try to ignore a macro line (e.g. %define . . . ) in ./spec file. For example, the  '#' (hash character) symbol to invalidate a macro statement does not valid as following: 

 * It's not okay.  # symbol is not available even though we try to use "#" symbol. 
```
# %define debug_package                   %{nil}

```

 * It's okay if I remove specified lines:
```
-%define debug_package                   %{nil}
```

 * It's okay if I remove "%" symbol behind "#" symbol:
```
-# define debug_package                   %{nil}
```

 * Reference: http://rpm5.org/docs/api/macros.html

Recently, I have found an instruction to solve this issue from the [Fedora documentation web-page](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/Packagers_Guide/chap-Packagers_Guide-Spec_File_Reference-Comments.html).

**Instruction**: Because macros are expanded first, do not insert any multi-line macros in a comment. If you want to comment out a line with a macro, double the percent signs (%%) as in the following example:

`# %%configure`

**Discussion**: Does we always have to use double percent sign? My question is why we cannot use a single percent sign? Anyone that has a similar experience like me?

**Comment by leemgs** [comment]
\CC: @pmatilai, @ffesti, @ignatenkobrain, @myungjoo , @hk57kim , @jyoungyun

**Comment by pmatilai** [comment]
I dont see what more there is to explain. Macros are expanded everywhere including what appear to be comments in spec. If you need to escape it to avoid expansion then double percent (%%) is the way to do it.

**Comment by myungjoo** [comment]
Yes, we do have a workaround (adding % for every % in a comment). But as long as correcting it at rpm itself is not too complex, why don't we fix it with rpm itself? Adding % to % is just a workaround and not too intuitive for developers causing many build fails.

**Comment by leemgs** [comment]
> Adding % to % is just a workaround and not too intuitive for developers causing many build fails.
Right. Actually, many developers have repetitively been making a incorrect statment in their ./*.spec files.

**Comment by Conan-Kudo** [comment]
Why not just replace `%` with `#`? That's what I generally do...

**Comment by myungjoo** [comment]
@Conan-Kudo If I had just a few packages with a few developers, I would do that. When you have more than a thousand packages with more developers, you can't afford that. Even if you correct hundreds of packages, you will get new incoming commits with yet another violations. You need something automatic: either give a build error (so that the developer can't ignore it) or do not expand the macros (so that the developer may ignore it).

**Comment by pmatilai** [comment]
FWIW, in rpm >= 4.15 there's now a "real" commenting directive in the form of M4-inspired %dnl, see https://github.com/rpm-software-management/rpm/issues/158, https://github.com/rpm-software-management/rpm/commit/44180fc7400ea8e67a13c5581459ad13f1d14103 and https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/7Q3BZ6GTAKFDJMNOLNJJENMWCPQTTET7/ for more info.
