### ISSUE TITLE
RFC: Removing unneeded internal macros (such as %__ranlib)

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#1211]
I was looking into the macros which RPM ships and there are many things like aforementioned %__ranlib which is not used in the RPM at all but has been there forever (at least from 1998).

From what I understand, %__* is supposed to be something which can affect RPM itself, the %_* is for internal variables for macros and %* is for users. Is it time to remove those which are not used by RPM and make distributions to set them up if they need them? Preferably not with double-underscore prefix.

**Comment by ignatenkobrain** [comment]
Basically these macros do not seem to belong to RPM at all:

```diff
--- a/macros.in
+++ b/macros.in
@@ -26,35 +26,18 @@
 %__awk                 @AWK@
 %__bzip2               @__BZIP2@
 %__cat                 @__CAT@
-%__chgrp               @__CHGRP@
 %__chmod               @__CHMOD@
-%__chown               @__CHOWN@
-%__cp                  @__CP@
-%__cpio                        @__CPIO@
-%__file                        @__FILE@
 %__gpg                 @__GPG@
-%__grep                        @__GREP@
 %__gzip                        @__GZIP@
-%__id                  @__ID@
-%__id_u                        %{__id} -u
 %__install             @__INSTALL@
-%__ln_s                        @LN_S@
 %__lrzip               @__LRZIP@
 %__lzip                        @__LZIP@
-# Deprecated, use %__xz instead.
-%__lzma                        %__xz --format=lzma
 %__xz                  @__XZ@
 %__make                        @__MAKE@
 %__mkdir               @__MKDIR@
 %__mkdir_p             @__MKDIR_P@
-%__mv                  @__MV@
 %__patch               @__PATCH@
-%__restorecon          @__RESTORECON@
 %__rm                  @__RM@
-%__rsh                 @__RSH@
-%__sed                 @__SED@
-%__semodule            @__SEMODULE@
-%__ssh                 @__SSH@
 %__tar                 @__TAR@
 %__unzip               @__UNZIP@
 %__zstd                        @__ZSTD@
@@ -67,17 +50,7 @@
 #==============================================================================
 # ---- Build system path macros.
 #
-%__ar                  @AR@
-%__as                  @AS@
-%__cc                  @__CC@
-%__cpp                 @CPP@
-%__cxx                 @CXX@
-%__ld                  @__LD@
-%__nm                  @__NM@
-%__objcopy             @__OBJCOPY@
 %__objdump             @__OBJDUMP@
-%__ranlib              @RANLIB@
-%__remsh               %{__rsh}
 %__strip               @__STRIP@
 
 #==============================================================================
@@ -149,9 +122,6 @@
 #      The interpreter used for build scriptlets.
 %_buildshell           /bin/sh
 
-#      The path to the bzip2 executable (legacy, use %{__bzip2} instead).
-%_bzip2bin             %{__bzip2}
-
 #      The location of the rpm database file(s).
 %_dbpath               %{_var}/lib/rpm
 
@@ -227,9 +197,6 @@ package or when debugging this package.\
 %__global_requires_exclude_from                %{?_docdir:%{_docdir}}
 %__global_provides_exclude_from                %{?_docdir:%{_docdir}}
 
-#      The path to the gzip executable (legacy, use %{__gzip} instead).
-%_gzipbin              %{__gzip}
-
 #      The Unix time of the latest kept changelog entry in binary packages.
 #      Any older entry is not packaged in binary packages.
 %_changelog_trimtime   0
@@ -278,9 +245,6 @@ package or when debugging this package.\
 #      Path to top of build area.
 %_topdir               %{getenv:HOME}/rpmbuild
 
-#      The path to the unzip executable (legacy, use %{__unzip} instead).
-%_unzipbin             %{__unzip}
-
 #==============================================================================
 # ---- Optional rpmrc macros.
 #      Macros that are initialized as a side effect of rpmrc and/or spec
@@ -343,16 +307,6 @@ package or when debugging this package.\
 #      
 %_install_langs        all
 
-#      The value of CLASSPATH in build scriptlets (iff configured).
-#      
-#%_javaclasspath       all
-
-#      Import packaging conventions from jpackage.org (prefixed with _
-#      to avoid name collisions).
-#      
-%_javadir      %{_datadir}/java
-%_javadocdir   %{_datadir}/javadoc
-
 
 #      Set ModularityLabel: for packages being build
 #
```

**Comment by ignatenkobrain** [comment]
Also we probably should rethink  `%_(build|host|target)_*` macro. They are not really used by RPM for anything, rpmPlatform() has its own auto-detection anyway. I guess they were meant for RPM to support cross-compilation, but this never happened from what I know.

Probably best would be to get rid of old cruft and when cross-compilation is the thing for RPM - do it properly?

**Comment by rpm-maint** [comment]
There's the "let's check what's actually used within rpm itself" on one
hand.
On the other hand, there's the principle of reality and there're specs out
there that rely on some of those definitions.
For no real value, yes but still they do are used in the wild and so the
potential for breakage is quite wide…

**Comment by ignatenkobrain** [comment]
> For no real value, yes but still they do are used in the wild and so the potential for breakage is quite wide…

Of course, but it is not different from changing other behaviors of RPM. Those macros are not documented, they are explicitly described as *private to RPM* so I think making such change in next version of RPM (4.17) can be affordable.

**Comment by pmatilai** [comment]
Rather than go mass destruct all at once, it's better to try find things that are obviously entirely unused by everybody, whether through plain obsolescence (such as those long obsoleted %_foo*bin compat macros) or the fact that they cannot be meaningfully used within rpm context. And keep on nipping a little by little.

For example there are requests to set CC from %__cc (and the related stuff) in %configure, I wouldn't be so quick to dismiss those as although %__cc is unused in rpm, we do deal with compiler flags quite a bit.

**Comment by ignatenkobrain** [comment]
@pmatilai in Fedora specs, rough numbers are:

```
%_javadir - 209
%__sed - 168
%_javadocdir - 114
%__cp - 113
%__mv - 76
%__cc - 72
%__ln_s - 24
%__id_u - 20
%__ar - 19
%__cxx - 15
%__grep - 7
%__file - 4
%__as - 3
%__ranlib - 2
%__chgrp - 2
%__restorecon - 1
%__cpp - 1
%_unzipbin - 0
%__ssh - 0
%__semodule - 0
%__rsh - 0
%__remsh - 0
%__objcopy - 0
%__nm - 0
%__lzma - 0
%__ld - 0
%__id - 0
%_gzipbin - 0
%__cpio - 0
%__chown - 0
%_bzip2bin - 0
```

**Comment by ignatenkobrain** [comment]
Most of __id_u occurrences are from BuildRoot definition. The javadir and javadocdir are overriden by javapackages, so I'd proposed to keep:

```
%__sed
%__cp
%__mv
%__cc
%__cxx
%__cpp
```

the rest IMO can be dropped without problems.

**Comment by pmatilai** [comment]
Note that %__remsh (and through that, %__rsh and %__ssh) are actually used by rpm itself (in %___build_cmd) for remote execution of build scripts (a kind of cross-build setup).

The selinux stuff can probably go without further ado, ditto with the id-stuff, including chown/chgrp which you can't do as a regular user anyway (btw, where are you seeing %__chgrp used, I didn't find any?)

As for the compiler stuff %__ld belongs in the same mental group as cc/cxx/cpp, and actually %__as too.  Ar, ranlib, objcopy and nm are in the same general direction but far more obscure and probably could go.

**Comment by ignatenkobrain** [comment]
> Note that %__remsh (and through that, %__rsh and %__ssh) are actually used by rpm itself (in %___build_cmd) for remote execution of build scripts (a kind of cross-build setup).

hmm, probably I did not notice that.

> The selinux stuff can probably go without further ado, ditto with the id-stuff, including chown/chgrp which you can't do as a regular user anyway (btw, where are you seeing %__chgrp used, I didn't find any?)

my bad, I made a typo and it should be %__chown, the %__chgrp is empty.

> As for the compiler stuff %__ld belongs in the same mental group as cc/cxx/cpp, and actually %__as too. Ar, ranlib, objcopy and nm are in the same general direction but far more obscure and probably could go.

Fair enough, I'll send PR then.

**Comment by ignatenkobrain** [comment]
> 

> Note that %__remsh (and through that, %__rsh and %__ssh) are actually used by rpm itself (in %___build_cmd) for remote execution of build scripts (a kind of cross-build setup).

Ah, that is trivial.

```
801:%___build_cmd		%{?_sudo:%{_sudo} }%{?_remsh:%{_remsh} %{_remhost} }%{?_remsudo:%{_remsudo} }%{?_remchroot:%{_remchroot} %{_remroot} }%{___build_shell} %{___build_args}
```

it uses one underscore while I was grepping for two underscores...

So it is actually not used at all :)

**Comment by pmatilai** [comment]
Right, that underscore-mismatch makes me wonder if it ever was used (and whether it works) at all...

If you do PR's, please do so in small pieces at a time, eg only totally non-controversial removals in a one PR.

**Comment by ignatenkobrain** [comment]
@pmatilai too late , but I will split PR in to small commits.

**Comment by pmatilai** [comment]
Not just small commits but small PRs, fed over time. My capacity for dealing with people complaining about breakage is well over quota for this year (not your fault certainly)

**Comment by pmatilai** [comment]
@Conan-Kudo , @mlschroe (or anybody in the know) - is there a place where one could grab the entire collection of Mageia and openSUSE patches similarly to this Fedora daily snapshot by in Fedora: http://pkgs.fedoraproject.org/repo/rpm-specs-latest.tar.xz ? It'd be a very valuable thing to have all these specs at hand for grepping whenever considering rpm changes.

**Comment by Conan-Kudo** [comment]
@pmatilai I think @pterjan might know for Mageia. You might be stuck just doing `svn co svn://svn.mageia.org/packages/cauldron` for that. For openSUSE, @bmwiedemann has a Git mirror of the specs from OBS here: https://github.com/bmwiedemann/openSUSE

**Comment by bmwiedemann** [comment]
There is even online search included: https://github.com/bmwiedemann/openSUSE/search?q=__cc

**Comment by pmatilai** [comment]
Okay, that's useful. Thanks!

**Comment by pterjan** [comment]
For Mageia we recently discussed either publishing a snapshot or exporting regularly to git as several people have checkouts that they use for mass changes but it doesn't exist yet.

`svn co svn://svn.mageia.org/packages/cauldron` is not great because then you get all releases of the package, you need `cauldron/<package name>/current/` or even only `cauldron/<package name>/current/SPECS` if you don't need patches, which is why several of us had some scripts to do so.

I'll try to look into it in the next few days.

**Comment by pterjan** [comment]
Numbers from Mageia, nothing big, and that's easy to cleanup anyway in a single commit:

```
%__cp - 106
%__mv - 79
%__cc - 30
%__ln_s - 28
%__sed - 21
%__grep - 10
%_javadocdir - 3
%_javadir - 3
%__lzma - 3
%__cxx - 3
%__id_u - 2
%__ar - 2
%__file - 2
%__as - 2
%__ranlib - 2
%__chgrp - 2
%__restorecon - 2
%__cpp - 2
%_unzipbin - 2
%__ssh - 2
%__semodule - 2
%__rsh - 2
%__remsh - 2
%__objcopy - 2
%__nm - 2
%__ld - 2
%__id - 2
%_gzipbin - 2
%__cpio - 2
%__chown - 2
%_bzip2bin - 2
```

If someone wants to check other things, I have created a sparse svn checkout (http://pkgsubmit.mageia.org/specs/cauldron-sparse-svn-snapshot.tar.xz 20MB compressed, allows to update and to do mass commits) and one without .svn (http://pkgsubmit.mageia.org/specs/cauldron-no-svn-snapshot.tar.xz 7MB compressed)

**Comment by pmatilai** [comment]
The worst offenders are already gone, closing. If/when there are further leftovers we can deal with them as they come up.
