### ISSUE TITLE
Allow additional data parameter for ts.addErase(name)

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/rpm#1213]
It will unify interface with other function like ts.addReinstall(hdr, data). It also will help to DNF to pair RPM transaction item with DNF DB item.

See also: https://bugzilla.redhat.com/show_bug.cgi?id=1825162

**Comment by pmatilai** [comment]
How would you expect to use that "key" argument? For installed packages, this is handled in the transaction callback but there are no callbacks for erased packages, partly because there's no associated key, because it's unclear as to what to put there for automatically created erasure elements (ie on upgrade/reinstall).

**Comment by j-mracek** [comment]
In dnf-4 it is clear. We create for each operation a separate transaction item. Upgrade is not a single operation but operation of upgrade and upgraded. See dnf/db/group.py:_populate_rpm_ts().

**Comment by pmatilai** [comment]
I know dnf does that, it's what unearthed this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1620275, fixed in commit a144c29831a39ed303d6ea8d2ae91e1c36d64c84.

Rpm simply ignores those separate erasure elements as it has to keep track of the update relations.

**Comment by j-mracek** [comment]
But the same issue is with a single remove step. Try:
dnf install acpi -y
dnf remove acpi # wait till rpm -e acpi is performed in another terminal, then approve it.

At the time of creation of remove operation for rpm ('dnf/db/group.py:_populate_rpm_ts()') the package i already gone, but rpm do not complain. And it was removed by another process before creation rpm transaction.

From the discussion I see that the problem is much wider.

We 100% depend on synchronization rpm transaction with our internal database. The synchronization is required to ensure that we correctly requested operation on rpm. Also we use it to track problems. When transaction failed we would like to know which elements failed and which elements succeed. In case than some element disappeared, we have no idea why and what they status. Any suggestion in this case is not a good idea.

I am looking for a solution of the problem in Python and Fedora 31/RHEL8.

**Comment by pmatilai** [comment]
That's not the same issue at all, even if it appears similar from you point of view.

**Comment by j-mracek** [comment]
@pmatilai Please could you fix it as soon as possible?

**Comment by pmatilai** [comment]
Fix what?

If you mean the "key" argument to addErase(), it's not a simple thing. It's not an optional "data" argument that you're passing to addInstall/addReinstall, but a key which gets passed back to you for the purpose of opening the package file when the time comes. There's nothing similar for erased packages, largely coming down to what I said in the earlier comment: it's not obvious at all how to handle this for automatically added erasures for which the caller will not *have* a key. So rpm would need to invent something, but how does the callee then know how to locate that when it was rpm that invented it - for rpm the key is a totally opaque pointer it cannot touch at all.

You need to start with fixing the invalid assumption(s) that dnf is currently making: rpm can and will make adjustments to transaction, you cannot assume 1:1 relation between what you pass to ts.addFoo() and what ends up being in there.

**Comment by j-mracek** [comment]
> So rpm would need to invent something, but how does the callee then know how to locate that when it was rpm that invented it

@pmatilai Thank you for any changes. Please keep in mind that it was originally requested in bugzilla, and we would like to use it in next RHEL.

> You need to start with fixing the invalid assumption(s) that dnf is currently making: rpm can and will make adjustments to transaction, you cannot assume 1:1 relation between what you pass to ts.addFoo() and what ends up being in there.

@pmatilai I have no problem with changing of work flows in DNF. But in this case I do not care about internal implementation in RPM. I expect that RPM will keep requested list of operation intact. Internally it could optimize steps, skip them, mark them as done, I do not care. We stop to verify transaction by our self as it was recommended by RPM team. Therefore we 100% depend on RPM.

**Comment by pmatilai** [comment]
I just submitted a different kind of approach for comments as #1363.

**Comment by pmatilai** [comment]
Addressed in a more comprehensive manner via #1365, #1366 and #1367 .
