### ISSUE TITLE
rpm --eval "%{lua:rpm.interactive()}" does not immediately print the output

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1215]
I'd liek to use the interactive Lua console, however, it doesn't seem to be very... interactive.

```
$ rpm --eval "%{lua:rpm.interactive()}"

RPM Interactive Lua 5.3 Interpreter
>
```

So far so good...

```
> print"a"
> 
```

Nothing...

```
> print"a"
> print"a"
> print"a"
> print"a"
>
```

Nothing...

```
> ^D
aaaaa
```

Is there a way to receive the output as I put the input?

**Comment by mlschroe** [comment]
This happens because you're in a macro expansion, so all the output is collected and returned to the macro engine.

**Comment by hroncok** [comment]
Can I do anything to have the interneter not in the macro expansion mode?

Dne st 13. 5. 2020 11:03 uživatel Michael Schroeder <
notifications@github.com> napsal:

**Comment by hroncok** [comment]
This gets the job done:

```python
from ctypes import cdll, c_char_p
librpmio = cdll.LoadLibrary("librpmio.so.9")
librpmio.rpmluaRunScript(None, c_char_p(b"rpm.interactive()"), None)
```

**Comment by pmatilai** [comment]
Ouch :rofl: 

The interactive interpreter was added years before my time, but as far as I can recall, you're the first person *ever* to try actually using it. There may be some resident fauna there... :beetle: :bug:

**Comment by hroncok** [comment]
I have it all figured out. Blog post coming. Would you consider adding something like the above to rpm itself?

**Comment by pmatilai** [comment]
If by "something like the above" you mean something that allows actual interactive experience, sure :sweat_smile:

**Comment by hroncok** [comment]
I meant something a bit more sophisticated. I have so far:

```
#!/usr/bin/python3
import sys
from ctypes import cdll, c_char_p


librpmio = cdll.LoadLibrary("librpmio.so.9")

adjust_path = b"""
if os.getenv("LUA_PATH") then
    package.path =  os.getenv("LUA_PATH") .. ";" .. package.path
end
"""

# first argument is an "rpmlua" pointer, but uses global one when NULL
# second argument is code
# third argument is "name", used in errors, reasonable default when NULL
librpmio.rpmluaRunScript(None, c_char_p(adjust_path), None)

if len(sys.argv) > 1:
    sys.argv[-1] = '/dev/stdin' if sys.argv[-1] == '-' else sys.argv[-1]
    # first argument as above, second argument is path
    librpmio.rpmluaRunScriptFile(None, c_char_p(sys.argv[-1].encode("utf-8")))
else:
    librpmio.rpmluaRunScript(None, c_char_p(b"rpm.interactive()"), None)
```

**Comment by voxik** [comment]
I think it could be enough if the documentation give more reasonable example such as:

~~~
rpm.expand("%{echo:some message}")
~~~

Which provides expected output:

~~~
$ rpm --eval "%{lua:rpm.interactive()}"

RPM Interactive Lua 5.3 Interpreter
> rpm.expand("%{echo:some message}")
some message
> rpm.expand("%{echo:%{_bindir}}")
/usr/bin
>
~~~

Or IDK what else one could be interested.

**Comment by voxik** [comment]
Or if there was a way to flush to the output the content collected by the macro engine ....

**Comment by pmatilai** [comment]
Adding a native way to flush the output shouldn't be hard. This is code that for all practical purposes nobody has touched in 16 years so it's not surprising if its a bit rusty and squeaky...

**Comment by hroncok** [comment]
Here is my draft blog post about how to get a nicer console https://hackmd.io/@hroncok/SyNjuxcqL

**Comment by pmatilai** [comment]
Wonderfully weird stuff :smile:

**Comment by pmatilai** [comment]
Just a word of caution: rpmluaRunScript() and rpmluaRunScriptFile() are not considered public API and are not available in the public headers on C side, although the symbols are accessible in the ABI. So they are subject to change without further notice, although the likelihood of that happening doesn't seem that great, they've been exactly the way are since their inception 16 years ago...

**Comment by hroncok** [comment]
My script doesn't seem to see system defined macros. Do I need to call something explicitly to load them?

```
$ rpmlua 

RPM Interactive Lua 5.3 Interpreter
> print(rpm.expand("%python3"))
%python3
> rpm.define("test b")
> print(rpm.expand("%test"))
b
> 


$ rpm --eval "%{lua:rpm.interactive()}"

RPM Interactive Lua 5.3 Interpreter
> print(rpm.expand("%python3"))
> 
/usr/bin/python3
```

**Comment by hroncok** [comment]
This gets the job done:

```python
librpm = cdll.LoadLibrary("librpm.so.9")

# Load general configuration (such as macros defined in standard places)
# Second argument is target platform, NULL is the default
librpm.rpmReadConfigFiles(librpm.rpmcliRcfile, None)
```

**Comment by hroncok** [comment]
Would you accept a pull request that that adds a `rpmlua` executable and makes it behave more or less like my Python script?

Note that my C skills are rusty and my autotools skills are almost nonexistent, so I will probably need some guidance.

**Comment by hroncok** [comment]
Thanks.

**Comment by pmatilai** [comment]
> Would you accept a pull request that that adds a rpmlua executable and makes it behave more or less like my Python script?

Added in #1867 , have fun :smile: 

I've readline history working locally too, just need to massage the autofoo stuff to acceptable state.
