### ISSUE TITLE
RFE: Lua rpm.error() function

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1218]
I'd kindly like to request that the following Lua/RPM code:

```lua
rpm.expand("%{error:...}")
```

Could be made simpler with something like:
```lua
rpm.error("...")
```

Please do let me know if there is an existing better idiom for this.

(Possibly also with `warn` and `echo`.)

**Comment by pmatilai** [comment]
No disagreement there, `rpm.expand("%{error:...}")` is just absurd. And so are many other things hidden behind rpm.expand().

This falls into the same general category of better Lua integration (or in other words, "make using Lua in rpm sane") as #1092.

**Comment by hroncok** [comment]
Also, `rpm.with("foo")` and `rpm.without("foo")` would be lovely.

**Comment by pmatilai** [comment]
Actually, it's not so straightforward.

rpm.error() seems like an obvious thing at first sight, but this only signals a *macro error* and not all Lua content in rpm are macros. Notably, scriptlets are not macros, and signaling a macro error in a scriptlet would be pointless.

While it technically would be possible to offer different functionality to Lua based on the context and might at some point do so for something, in this case I think it's better to simply use Lua's own error() which will correctly signal an error to rpm regardless of the context: inside a macro, it will flag the macro expansion as failed (like %{error:foo} does) and in scriptlets, it'll cause the scriptlet to fail.

**Comment by pmatilai** [comment]
Once #1419 lands, you'll be able to use all macros as native-like Lua functions, eg
`macros.without("foo")` and `macros.error("bad stuff")`.

**Comment by hroncok** [comment]
That is indeed solving this issue for me. Thanks! (Any chance this will land to RHEL 9?)

**Comment by pmatilai** [comment]
With #1419 merged now, I'm considering this done.

This will be in rpm 4.17, to be released in the spring. Other than that I wont make any predictions.
