### ISSUE TITLE
RFE: Allow multiple snippets of the same build script

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#1223]
When automatically generate sub packages it is sometime necessary to also do build steps. Right now this requires adding lines or macros to all the affected sections.
If sections like %prep, %build and %install can be created multiple time all pieces that belong to some part of the package (think documentation, -devel, bindings) can be at one place and generated from a single macro (or other templating means).

The sections would then just be copied into the actual script one after the other. Some priority parameter could be used to get them in the proper order.

**Comment by pmatilai** [comment]
Maybe %prep/%build/%install could simply take an optional name as an argument, just like %package, %files etc do? And actually execute them separately if defined that way. Seems it'd simplify eg conditional sub-packaging quite a bit.

**Comment by pmatilai** [comment]
This use-case is now covered by append/prepend modes (#2728)
