### ISSUE TITLE
RFE: Have priorities for file patterns

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#1226]
To give automatic sub packages more leeway to deal with files there needs to be a way to "steal" files from other packages, so files can end up in different packages depending on which sub package actually get created.
For those cases it is not desired to have the files in more than one package. Adding a priority attribute to the entries in %files allows moving the file to the package with the highest priority while making sure it ends up some where.

**Comment by pmatilai** [comment]
This needs to be considered as part of #329 rather than a separate item. Closing now that it's linked.
