### ISSUE TITLE
Check date/time for consistently using unsigned ints

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#1228]
Signed 32 bit integers run out of space 2038 for unix time. As RPM uses unsigned ints for all tags that should not be a problem.We still need to check that there are no signed 32 bit ints used anywhere near date and time handling

**Comment by ffesti** [comment]
Also check the cpio payload format for issues.

**Comment by pmatilai** [comment]
Reassigned to @ffesti as this largely overlaps with #1940

**Comment by pmatilai** [comment]
Static checking in RHEL discovered exactly one place where we still had time_t conversion to signed integers: getBuildTime(). Fixed that in https://github.com/rpm-software-management/rpm/commit/97aa64d8281974fb369c66d5aef8650515b89c52, I think we can consider this done now.
