### ISSUE TITLE
Add %toolchain macro to differentiate C/C++ toolchains

### ISSUE THREAD

**Issue by tbaederr** [rpm-software-management/rpm#1231]
This is often needed when supporting builds with multiple compilers. Simply looking at `%__cc` is not enough since the actual executable might be called differently, but might still be gcc. Or clang.
Doing a substring search is also problematic since "g++" is a substring of "clang++".

So it would be nice if rpm provided a standard macro for this.

Does this make sense for RPM and does `%toolchain` sound fine? If so, I can work on the actual implementation.
It does seem like the value of `%toolchain` would have to be set for every compiler specially though.

**Comment by pmatilai** [comment]
The issue is certainly valid and applies broadly to all sorts of things, including but not limited to compiler flags from %optflags.

**Comment by voxik** [comment]
I wonder if there is any possible relation to https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/82

**Comment by tbaederr** [comment]
We will solve this differently, in redhat-rpm-config. Thanks.
