### ISSUE TITLE
%{name} is not properly evaluated in sources and %_sourcedir

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#1234]
rpm does not evaluate `%{name}` properly in sources, even when all the sources have been moved to a separate `%sourcelist` section, after the preamble that sets `%{name}`.

That breaks spectool

```console
$ rpmdev-spectool -R -g ~/fedora/fedpkg/fonts-rpm-macros/fonts-rpm-macros.spec 
Downloading: https://pagure.io/fork/nim/fonts-rpm-macros/archive/670c626fdf74d54edc6a9796f66541eb2feed96a/nim-fonts-rpm-macros-670c626fdf74d54edc6a9796f66541eb2feed96a.tar.gz
Download failed:
[Errno 2] No such file or directory: '/var/lib/builder/rpmbuild/SOURCES/%{name}/nim-fonts-rpm-macros-670c626fdf74d54edc6a9796f66541eb2feed96a.tar.gz'
```

**Comment by ignatenkobrain** [comment]
Probably you can paste the spec file here and method how to reproduce? Probably it is `rpmdev-spectool` does something wrong with it…

**Comment by ignatenkobrain** [comment]
Looking into the fedora version of spec, `rpmspec -P` shows:

```
Source:    https://pagure.io/fonts-rpm-macros/archive/3.0.3/fonts-rpm-macros-3.0.3.tar.gz
```

which is somewhat different from what you mentioned above.

**Comment by ignatenkobrain** [comment]
So I have discussed this privately with @decathorpe and the issue here is in rpmdev-spectool as I guessed.

Next time, please open issues with as much information as possible and a minimal reproducer.

Ref: https://pagure.io/rpmdevtools/issue/40

**Comment by ignatenkobrain** [comment]
Btw, I have sent https://github.com/rpm-software-management/rpm/pull/1235 to avoid printing warnings in the CLI when using %{name} in the %{_sourcedir}: https://github.com/rpm-software-management/rpm/pull/1235
