### ISSUE TITLE
RFE: save the parsed spec in src.rpm

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1241]
With the trend of increasingly dynamic content generation for specs (currently via complex macros, in future automatic & dynamic sub packages, #329, #1222 etc) the originating spec and the parsed one might differ by hundreds of lines, making it really hard to grasp how we got from A to B. It seems we should store the parsed spec in the src.rpm somehow. IIRC this has actually been requested before but can't find the reference atm.

**Comment by ffesti** [comment]
rpmSpecGetSection() returns it when passed RPMBUILD_NONE. Guess adding this to the API is what you remember even if it has been a while:
`
c38504c4ba build/rpmspec.h (Panu Matilainen 2011-06-17 13:44:39 +0300 78)  * As a special case, RPMBUILD_NONE as section returns the entire spec in
c38504c4ba build/rpmspec.h (Panu Matilainen 2011-06-17 13:44:39 +0300 79)  * preprocessed (macros expanded etc) format.
`

**Comment by pmatilai** [comment]
No, that was simply to support rpmspec --parse. There was a request to add the spec to the header, or something, someplace, but whether that request was for the *parsed* spec I don't recall.

**Comment by Conan-Kudo** [comment]
There was a request years ago (not sure it was tracked in rpm.org trac) for doing this for reproducible builds, because we want to be able to replay the exact build environment and settings, and the current way is incomplete.

**Comment by nim-nim** [comment]
Generally speaking it would be great to store more build-time information in the spec. I’ve been requested to store the buildroot state for debuging and reproducibility needs, for example.

https://src.fedoraproject.org/fork/nim/rpms/redhat-rpm-config/c/bc4e6a79355f3a2b73abeea7e5c0e1f53b09579e?branch=forge-with-patches-auto-call-auto-changelog-auto-srpm-bump

shows how to store more build-time info in the SRPMs using current unchanged rpm. So it does not even need rpm engine changes.

However one could argue that writing 13 bytes of spaces in sources files in %sourcelist, just so they exist when %build needs to write to them, is not the most elegant solution.

Also calling rpm or rpmspec from within an rpmbuild session is probably not the best of things.

**Comment by pmatilai** [comment]
As a note to self, we could/should probably use RPMFILE_ARTIFACT to flag such files.

**Comment by bmwiedemann** [comment]
I found that unfortunately this change makes many of our rpm builds unreproducible, because our .spec files contain things like `make %{?_smp_mflags}` and that gets expanded depending on the build machine CPU core count.

Is there an easy way to disable this or do you have a different proposal of how to build bit-identical rpms again?

**Comment by pmatilai** [comment]
Please file a new issue on that.
