### ISSUE TITLE
Psmpre and psmpost plugin callbacks executed multiple times per package

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#1254]
As psmpre and psmpost callbacks are basically used to report on the installed/removed packages one would think each of them is called exactly once per package. Unfortunately rpmpsmRun - which triggers them - is also called for other occasions like executing %posttrans and %verify scriptlets and checking the transaction. This is made worse by the callbacks neither providing the goal passed to rpmpsmRun nor an rpmts instance.

**Comment by pmatilai** [comment]
That they get called multiple times could be considered a feature too, for example a plugin could hook in there to be able to do stuff each time a package file is opened.
Rather than try bend those to something different, I think we'd be better off with actual install/erase hooks.

**Comment by pmatilai** [comment]
The other thing with these hooks is that they're prone to misuse anyway. It's easy to end up thinking psmpost means package is all set and done, when it's often not the case: updates are not complete until the erasure part has also executed, and if the package has or takes part in post-trans scriptlets/triggers it's not really ready until the end of the transaction. 

We should actually have data structures to track the state of a package as it goes through the transaction machinery, an API to get that state, and maybe plugin notifications on change. It's a bit hysterical that even rpm itself doesn't actually know when a package has been fully installed, except for coming out of rpmtsRun().

That sort of thing is probably necessary if we ever want to separate scriptlet execution from unpacking as well.

**Comment by pmatilai** [comment]
Closing in favor of the more generic #1536 ticket.

**Comment by pmatilai** [comment]
Ran into this while poking at the syslog plugin, and this really is just a bug that makes these hooks unusable.
