### ISSUE TITLE
error: Couldn't exec metainfo(): No such file or directory

### ISSUE THREAD

**Issue by pnemade** [rpm-software-management/rpm#1261]
Any package Fedora 33/rawhide build that involved installing metainfo files has started giving error in build.log
e.g. See this scratch build https://koji.fedoraproject.org/koji/taskinfo?taskID=45537932 which shows line
```error: Couldn't exec metainfo(): No such file or directory```

rpm-build-4.16.0-0.beta1.2.fc33.1
redhat-rpm-config-160-1.fc33

**Comment by ignatenkobrain** [comment]
Sent patch yesterday https://github.com/rpm-software-management/rpm/pull/1259

**Comment by ignatenkobrain** [comment]
Backported to rawhide & fixed in master.
