### ISSUE TITLE
RFE: Add ability to run lua scripts directly

### ISSUE THREAD

**Issue by jlebon** [rpm-software-management/rpm#1273]
It would be great if we could pass a lua script directly to rpm. The primary motivation for this is so that rpm-ostree can make use of this when running scriptlets. But I suspect it would also be useful for packagers to test their lua scripts more easily without having to rebuild an RPM each time.

For more background on this, see also:
https://github.com/coreos/rpm-ostree/issues/749
http://lists.rpm.org/pipermail/rpm-ecosystem/2016-August/000391.html

**Comment by Conan-Kudo** [comment]
@hroncok has made interesting progress in #1215, you might want to check that.

**Comment by jlebon** [comment]
Ahh yup, that looks promising. @pmatilai You mentioned in [this comment](https://github.com/rpm-software-management/rpm/issues/1215#issuecomment-628594473) that it's not considered public API. Would you be open to exposing them through a CLI switch for now? We could mark it experimental/hidden to begin with so we can trial it in rpm-ostree.

Also, how far off are the environments in these library functions from what a scriptlet environment would be?

**Comment by dustymabe** [comment]
Bump. We sure would like to make progress on this so that rpm-ostree can start supporting lua appropriately and not asking packagers to rewrite their scriptlets.

**Comment by pmatilai** [comment]
You can execute arbitrary Lua with rpmExpand() or --eval with a %{lua:...} macro as it is. But the actual scriptlet running machinery needs all manner of context that only exists inside transactions.

**Comment by jlebon** [comment]
> But the actual scriptlet running machinery needs all manner of context that only exists inside transactions and so is not meaningfully exportable, really.

OK right, that's what I surmised.

How big is that context? Are we talking about automatically defined variables? Is there some way we could provide that context via CLI as well? E.g. basically tell rpm "please run this Lua script as a %post scriptlet for this package running in the context of a fresh install".

**Comment by hroncok** [comment]
In the meantime, I've opened https://pagure.io/rpmdevtools/pull-request/79 as suggested by @xsuchy

**Comment by dustymabe** [comment]
Thanks @hroncok

**Comment by pmatilai** [comment]
I'm going to close this as a WONTFIX because librpm is about providing package management API, not a toolbox for rolling your own. Working on any simulated transaction scriptlet machine just does not fit on any roadmap I can envision, and without that ... you can already execute Lua code within rpm (macro) context, but you cannot execute *scriptlets* in their native context.

We may yet grow some nicer means to execute Lua stuff from the cli for development purposes but it will not be the magic carpet that this ticket is asking for.

**Comment by hroncok** [comment]
> We may yet grow some nicer means to execute Lua stuff from the cli for development purposes 

Should I open a separate ticket?

**Comment by pmatilai** [comment]
Nah, no need. It's the season when even the grumpiest rpm developers soften a little.
See #1867  :santa:
