### ISSUE TITLE
RFE: Offer LMDB as an alternative engine to BDB for rpmdb

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#128]
I think most of us are keenly aware that Berkeley DB 5.x is dead. While Oracle has Berkeley DB 6.x, it is licensed AGPLv3, which seems to make some people rather skittish.

As a potential alternative, why not use [LMDB](https://symas.com/products/lightning-memory-mapped-database/)? Projects like OpenLDAP, CFEngine, Postfix, etc. have moved to LMDB or use it by default from BDB after BDB 6 arrived.

LMDB is available in Fedora, Mageia, and openSUSE already, so the dependency would already be available for us to use. It should also be easy to support having internal LMDB like OpenSUSE does now for BDB (the [LMDB sources](https://github.com/LMDB/lmdb) look like they're built in a rather simple manner, so embedding it shouldn't be terrible).

According to [the LMDB web page on projects using LMDB](https://symas.com/products/lightning-memory-mapped-database/involvement-in-other-projects/):

> Note, because it’s so easy to modify BerkeleyDB-based projects to use LMDB instead, the list of BerkeleyDB-based adaptations is growing quickly.

I'm not sure how true it is, but it seems to bear out with the number of previously BDB users now being LMDB users.

LMDB is licensed under the OpenLDAP license, which is a BSD-style license, so people who freaked out over BDB 6 shouldn't be freaking out over LMDB.

**Comment by robert-scheck** [comment]
At https://bugzilla.redhat.com/show_bug.cgi?id=1086784, there also was kind of discussion about that.

**Comment by Redfoxmoon3** [comment]
LMDB as an alternative to BDB would further help with targetting less-known and new platforms. and as far as I know, make RPM buildable and usable on midipix for example.

**Comment by Conan-Kudo** [comment]
Perhaps @hyc could provide some insight into whether the situation has improved any since the discussions that occurred in Red Hat Bugzilla.

From my point of view, the main issues I see are the following:

* LMDB is not independently released (it's part of the OpenLDAP source tree)
* The library does not have a versioned soname to reflect ABI stability (or lack thereof)
*  There's no pkg-config definition to make it easy to identify it to link

The last two issues are less of an issue if people embed LMDB instead of linking to it, and the second issue is not an issue if we statically link instead of dynamically link.

**Comment by rpm-maint** [comment]
I think that although it's developed inside the OpenLDAP tree, it's released
separately and it doesn't align all of its releases with OpenLDAP ones.  For
example, if you take a look at
http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=summary, you'll see
that OpenLDAP 2.4.44 was released 11 months ago but LMDB got its v0.9.19 release
3 weeks ago.

About the SONAME issue, it seems that everyone has adopted liblmdb.so.0 as
soname.  At the very least cfengine3 and the knot-dns resolver are using that
library dynamically linked (at least in Debian, I can't speak now for others),
which should give us some peace of mind that rpm wouldn't be the first one doing
such bold move.

Anyway, it should be good that someone touches base with Howard so he adds
SONAME support finally to the library.  I'd say that's a must for distributions
(even when I suspect his main resistance is because he doesn't see the point of
linking it dynamically).

**Comment by Conan-Kudo** [comment]
So, in Fedora, we have a pkgconfig definition for it, which is shared by Arch Linux and Debian, so this is a non-issue now. It also not being independently released isn't really a big deal, either, as we do have it as a separate package that can be used without all of OpenLDAP.

The only remaining issue is that we still don't have a versioned soname.

**Comment by leo-yuriev** [comment]
@Conan-Kudo, please take look to https://github.com/ReOpen/libmdbx/tree/devel and https://github.com/PositiveTechnologies/libfpta

**Comment by n3npq** [comment]
@leo-yuriev: libmdbx looks very nice, but there are several issues that need to be fixed in an rpmdb schema before attempting better back ends. See other issues I have reported against RPM ...

**Comment by leo-yuriev** [comment]
@n3npq, be free to ask me for any related improvements in libmdbx.

Additionally, I am glad to boast about new major feature of libdmbx, which is relevant to rpmdb:
 - In comparison with LMDB, nowadays liblmdb provide automatic dynamic sizing of database file, in both directions - growth and shrink.
 - In the other words, libmdbx performs builtin compactification, moreover - with (almost) zero overhead.

**Comment by Conan-Kudo** [comment]
@leo-yuriev Would you please translate the documentation into English? It's a bit hard for me to understand it, as I don't know Russian. :)

**Comment by ignatenkobrain** [comment]
@Conan-Kudo time to learn russian ;)

**Comment by n3npq** [comment]
Google Translate works just fine: time to become pluralistic even if you can't crack a joke in Russian.

**Comment by n3npq** [comment]
This RFE is implemented in issue #281 and can be closed.

**Comment by n3npq** [comment]
@leo-yuriev: libmdbx replacing libdbx may well be the eventual end point. Deploying a format change as painlessly as possible to end-users is rate determining to RPM+LMDB* adoption.

I'll attempt a RPM+:MDBX port ifs/when there is any sign of traction in merging an RPM+LMDB patch, and try to clear up some of the known "legacy compatible" issues that have (historically) slowed down deployment of any change to more than 5 years.
