### ISSUE TITLE
Not ignoring generator failure shows strange issue

### ISSUE THREAD

**Issue by soig** [rpm-software-management/rpm#1285]
rpm's own fontconfig.prov is broken:
http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/updates_testing/20200624045432.daviddavid.duvel.28729/log/plasma-desktop-5.19.2-1.mga8/build.0.20200624045513.log
http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20200623223351.luigiwalser.duvel.10411/log/feh-3.4.1-1.mga8/build.0.20200623223403.log
disabling /usr/lib/rpm/fileattrs/font.attr makes the issue go away

Ex:

$ sudo mv /usr/lib/rpm/fileattrs/font.attr{,.no}
$ LC_ALL=C rpmbuild --short-circuit --define "_topdir $PWD" -ba SPECS/feh.spec  
(…)
Wrote: /home/tv/mga/pkgs/feh/RPMS/x86_64/feh-3.4.1-1.mga8.x86_64.rpm
Wrote: /home/tv/mga/pkgs/feh/RPMS/x86_64/feh-debugsource-3.4.1-1.mga8.x86_64.rpm
Wrote: /home/tv/mga/pkgs/feh/RPMS/x86_64/feh-debuginfo-3.4.1-1.mga8.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.3qCi65
+ umask 022
+ cd /home/tv/mga/pkgs/feh/BUILD
+ cd feh-3.4.1
+ /usr/bin/rm -rf /home/tv/mga/pkgs/feh/BUILDROOT/feh-3.4.1-1.mga8.x86_64
+ RPM_EC=0
++ jobs -p
+ exit 0

$ sudo mv /usr/lib/rpm/fileattrs/font.attr{.no,}
$ LC_ALL=C rpmbuild --short-circuit --define "_topdir $PWD" -ba SPECS/feh.spec  
(…)
error: Requirename generator   failed: /home/tv/mga/pkgs/feh/BUILDROOT/feh-3.4.1-1.mga8.x86_64/usr/share/feh/fonts/yudit.ttf
Provides: application() application(feh.desktop) feh = 3.4.1-1.mga8 feh(x86-64) = 3.4.1-1.mga8 mimehandler(image/bmp) mimehandler(image/gif) mimehandler(image/jpeg) mimehandler(image/jpg) mimehandler(image/pjpeg) mimehandler(image/png) mimehandler(image/tiff) mimehandler(image/webp) mimehandler(image/x-bmp) mimehandler(image/x-pcx) mimehandler(image/x-png) mimehandler(image/x-portable-anymap) mimehandler(image/x-portable-bitmap) mimehandler(image/x-portable-graymap) mimehandler(image/x-portable-pixmap) mimehandler(image/x-tga) mimehandler(image/x-xbitmap)
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: libImlib2.so.1()(64bit) libX11.so.6()(64bit) libXinerama.so.1()(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.11)(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.15)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.7)(64bit) libcurl.so.4()(64bit) libexif.so.12()(64bit) libm.so.6()(64bit) libm.so.6(GLIBC_2.2.5)(64bit) libpng16.so.16()(64bit) libpng16.so.16(PNG16_0)(64bit)
Recommends: imagemagick jpeg-progs

RPM build errors:
    Requirename generator   failed: /home/tv/mga/pkgs/feh/BUILDROOT/feh-3.4.1-1.mga8.x86_64/usr/share/feh/fonts/yudit.ttf

Which is strange as fontconfig.prov returns 0…

The strangest thing is that 'cmd' seems to be an empty string there

**Comment by soig** [comment]
Adding:
+       printf("mname='%s', cmd='%s' (callable=%d)\n", mname, cmd, callable);

Shows the following:
grep _font RES1 -1
mname='__elf_provides', cmd='/usr/lib/rpm/elfdeps --provides  ' (callable=0)
mname='__font_provides', cmd=' ' (callable=0)
mname='__gobjectintrospection_provides', cmd='/usr/lib/rpm/gi-find-deps.sh -P ' (callable=0)
--
mname='__elf_requires', cmd='/usr/lib/rpm/elfdeps --requires  ' (callable=0)
mname='__font_requires', cmd=' ' (callable=0)
mname='__gobjectintrospection_requires', cmd='/usr/lib/rpm/gi-find-deps.sh -R ' (callable=0)
--
mname='__elf_recommends', cmd='' (callable=0)
mname='__font_recommends', cmd='' (callable=0)
mname='__gobjectintrospection_recommends', cmd='' (callable=0)
--
mname='__elf_suggests', cmd='' (callable=0)
mname='__font_suggests', cmd='' (callable=0)
mname='__gobjectintrospection_suggests', cmd='' (callable=0)
--
mname='__elf_supplements', cmd='' (callable=0)
mname='__font_supplements', cmd='' (callable=0)
mname='__gobjectintrospection_supplements', cmd='' (callable=0)
--
mname='__elf_enhances', cmd='' (callable=0)
mname='__font_enhances', cmd='' (callable=0)
mname='__gobjectintrospection_enhances', cmd='' (callable=0)
--
mname='__elf_conflicts', cmd='' (callable=0)
mname='__font_conflicts', cmd='' (callable=0)
mname='__gobjectintrospection_conflicts', cmd='' (callable=0)
--
mname='__elf_obsoletes', cmd='' (callable=0)
mname='__font_obsoletes', cmd='' (callable=0)
mname='__gobjectintrospection_obsoletes', cmd='' (callable=0)

So for both __font_requires  & __font_provides, applyAttr generates a one char (space) command for font…

**Comment by pmatilai** [comment]
Right, there are ... issues with the error code handling in rpmfcExec().

For now, it's best to just revert the "always fail" commit fb5299b2a49460216c38674b7398296d3a6d767c, it's just broken.

Thanks for the report.

**Comment by pmatilai** [comment]
Fixed in master and beta3, thanks again for reporting.
