### ISSUE TITLE
Beta3 has a new broken test (235: rpmsigdig.at:144   rpmkeys -Kv <unsigned> 2       rpmkeys digest)

### ISSUE THREAD

**Issue by soig** [rpm-software-management/rpm#1288]
Beta2 was fine besides "rpmbuild.at:482 Dependency generation 3 build":
http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20200623145307.tv.duvel.658/rpm-4.16.0-0.beta2.1.mga8/

But beta3 introduces a new failure. See build*.log files & look for "Summary of the failures" at:
http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20200624083544.tv.duvel.13457/rpm-4.16.0-0.beta3.1.mga8/
(using // testsuite)

 235: rpmsigdig.at:144   rpmkeys -Kv <unsigned> 2
      rpmkeys digest

## ---------------------- ##

#                             -*- compilation -*-
235. rpmsigdig.at:144: testing rpmkeys -Kv <unsigned> 2 ...
./rpmsigdig.at:146:

if ! [ -d testing/ ]; then
    cp -aP "${RPMTEST}" .
    chmod -R u+w testing/
    mkdir -p testing/build
    ln -s ../data/SOURCES testing/build/
fi
export RPMTEST="${PWD}/testing"
export TOPDIR="${RPMTEST}/build"
export HOME="${RPMTEST}"

rm -rf "${RPMTEST}"`rpm --eval '%_dbpath'`/*
runroot rpm --initdb

runroot rpmbuild -bb --quiet \
	--define "%optflags -O2 -g" \
	--define "%_target_platform noarch-linux" \
	--define "%_binary_payload w.ufdio" \
	--define "%_buildhost localhost" \
	--define "%use_source_date_epoch_as_buildtime 1" \
	--define "%source_date_epoch_from_changelog 1" \
	--define "%clamp_mtime_to_source_date_epoch 1" \
	/data/SPECS/attrtest.spec
for v in SHA256HEADER SHA1HEADER SIGMD5 PAYLOADDIGEST PAYLOADDIGESTALT; do
    runroot rpm -q --qf "${v}: %{${v}}\n" /build/RPMS/noarch/attrtest-1.0-1.noarch.rpm
done
runroot rpmkeys -Kv /build/RPMS/noarch/attrtest-1.0-1.noarch.rpm

--- -	2020-06-24 08:37:24.201578966 +0000
+++ /home/iurt/rpmbuild/BUILD/rpm-4.16.0-beta3/tests/rpmtests.dir/at-groups/235/stdout	2020-06-24 08:37:24.186383200 +0000
@@ -1,6 +1,6 @@
-SHA256HEADER: 6104d0f021dfe58af39b1957fa222762a45cbec221b10915d61d5238858f3c28
-SHA1HEADER: e58516622b8b8960201d07e7b061af8bc21fcaef
-SIGMD5: 09ca69da1b4a85c202c377da3cf20048
+SHA256HEADER: 24790a8639dec5e0d4506f8ebacba0844b41bfd1aeecf7542251cafdebd1f7f3
+SHA1HEADER: 3539a6132ce89ef2296f5db3ce90f7991891e739
+SIGMD5: 4a51b31c3e136b3c5b3971f3d1811a7b
 PAYLOADDIGEST: 749d8980cc5889419da8cdbe9a5b3292742af8a227db3635f84966481b7612a8
 PAYLOADDIGESTALT: 749d8980cc5889419da8cdbe9a5b3292742af8a227db3635f84966481b7612a8
 /build/RPMS/noarch/attrtest-1.0-1.noarch.rpm:
235. rpmsigdig.at:144: 235. rpmkeys -Kv <unsigned> 2 (rpmsigdig.at:144): FAILED (rpmsigdig.at:146)

## ------------- ##

**Comment by pmatilai** [comment]
See http://lists.rpm.org/pipermail/rpm-announce/2020-June/000080.html, you managed to grab the wrong tarball.

**Comment by soig** [comment]
Indeed we can close this one.
https://github.com/rpm-software-management/rpm/issues/1289 is the only remaining issue with beta3
