### ISSUE TITLE
GPG_TTY warning causes test-suite failure in mock

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1290]
Seems that something in mock environment trips up the new GPG_TTY related warning, causing (a bogus) test-suite failure due to the extra output:
https://download.copr.fedorainfracloud.org/results/pmatilai/rpm-snapshot/fedora-rawhide-x86_64/01499743-rpm/build.log.gz

```
 --- /dev/null	2020-06-24 10:47:07.441643129 +0000
+++ /builddir/build/BUILD/rpm-4.16.90-git15102/tests/rpmtests.dir/at-groups/242/stderr	2020-06-24 10:48:56.462891354 +0000
@@ -0,0 +1,2 @@
+warning: Could not set GPG_TTY to stdin: Inappropriate ioctl for device
+warning: Could not set GPG_TTY to stdin: Inappropriate ioctl for device
242. rpmsigdig.at:414: 242. rpmsign --addsign (rpmsigdig.at:414): FAILED (rpmsigdig.at:420)
```

**Comment by dmnks** [comment]
Oh my. Thanks for sharing, I'll check that.

**Comment by pmatilai** [comment]
No worries, it's not the first (or last) time mock trips up something because it's a rather special environment.

**Comment by pmatilai** [comment]
Here's an simple reproducer that doesn't need messing with mock:

> [pmatilai🎩︎lumikko rpm]$ cp tests/data/RPMS/hello-2.0-1.x86_64.rpm /tmp/
[pmatilai🎩︎lumikko rpm]$ ./rpmsign --addsign /tmp/hello-2.0-1.x86_64.rpm < /dev/null
/tmp/hello-2.0-1.x86_64.rpm:
warning: Could not set GPG_TTY to stdin: Inappropriate ioctl for device
[pmatilai🎩︎lumikko rpm]$

Or to reproduce in the test-suite context, `make check < /dev/null`.

So actually the warning is quite appropriate in this situation, that this works at all in the test-suite depends on the key not having a passphrase at all so nothing will need to ask for it. The right thing to do is probably to set GPG_TTY explicitly from the test-suite instead - I'll submit a PR in a minute.

(so typical, I assign this to you but then end up looking at it myself, trying to kill time before vacation...)
