### ISSUE TITLE
Allow to exclude files from %doc

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1298]
I would expect the following to work:

~~~
%files
%doc README.md CHANGELOG.md docs
%exclude %{_datadir}/doc/git-lfs/docs/mangen
%exclude %{_datadir}/doc/git-lfs/docs/man/*.{1,5}
%exclude %{_datadir}/doc/git-lfs/docs/man/mangen.go
~~~

Unfortunately, the `%doc` directive is unexpectedly processed after all the other content of `%files` section:

~~~
Processing files: git-lfs-2.11.0-2.el8.x86_64
warning: File not found: /builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs/docs/mangen
warning: File not found: /builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs/docs/man/*.{1,5}
warning: File not found: /builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs/docs/man/mangen.go
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.GsRXAE
+ umask 022
+ cd /builddir/build/BUILD
+ cd git-lfs-2.11.0
+ DOCDIR=/builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs
+ export LC_ALL=C
+ LC_ALL=C
+ export DOCDIR
+ /usr/bin/mkdir -p /builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs
+ cp -pr README.md /builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs
+ cp -pr CHANGELOG.md /builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs
+ cp -pr docs /builddir/build/BUILDROOT/git-lfs-2.11.0-2.el8.x86_64/usr/share/doc/git-lfs
+ exit 0
~~~

Would it be possible to process the `%doc` earlier to allow the `%exclude` to take its action?

**Comment by ignatenkobrain** [comment]
I think it would be quite useful to implement this and should not be very hard, in theory... Still, you should just wipe those files and not use %exclude for that. I think that is on the roadmap that it will throw unpackaged files if you %exclude files and do not put them anywhere.

**Comment by ignatenkobrain** [comment]
I did take quick look into the code base: for `%doc` the `addSpecialFile()` is used that just inserts file entries. That does not copy files into the %{_docdir}. Rather, it is done from `processPackageFiles() -> processSpecialDir()` at which point it already packages the RPM. The `%exclude` is using `addFile()` with statp argument as NULL that indicates that file/directory does not exist.

Not sure what would be the best solution to this problem code-wise.

**Comment by dmnks** [comment]
The `%doc` directive is just syntactic sugar for:
1. Install the given file in the build directory into the build root
2. Specify its absolute path in `%files`

Now, `%doc` and `%license` are "special" files (as @ignatenkobrain noted) which are only processed *after* the normal file entries, meaning that an `%exclude` on such a file won't have any effect.

There are two ways to work around this (limitation) in the SPEC file:
1. Don't use `%doc` and just install the files manually in the `%install` section (and optionally `%exclude` some afterwards, as usual)
2. Whitelist the desired files in `%doc` (globs are accepted there)

Fixing this in RPM would be possible, I believe, the question is whether we really should. It seems like a rather niche use case and workarounds exist. I'll leave this open for now and discuss with the team.

**Comment by dmnks** [comment]
The `%doc` directive really is just a convenience directive meant to abstract away the details of "where do I put the doc files?". Cherry-picking them into separate subpackages based on the resulting absolute paths using `%exclude` seems to go against the very idea. At that point, you're better off just treating the doc files as normal files which allows you to use `%exclude` as well.

Based on that rationale, I'm closing this ticket. If you think this really deserves another look, feel free to reopen, though.
