### ISSUE TITLE
python bindings are using system RPM instead of in-source one

### ISSUE THREAD

**Issue by jsilhan** [rpm-software-management/rpm#130]
When I build rpm (exact 4.13 release) rpm-python subpackage links against rpm on the system, not the built one.

When I tried to build rpm package providing soname 3 and rpm installed on the system had soname 7, rpm-python had requirement for soname 7 and so cannot be installed. It was reproducible with the rpm-4.13 package having soname 7 and rpm-4.11 having soname 3 too.

See:
```bash
-bash-4.2$ rpm -qi rpm-libs --provides
Name        : rpm-libs
Version     : 4.13.0
Release     : 1.el7.centos
Architecture: x86_64
Install Date: Wed Jan 18 14:56:23 2017
Group       : Development/Libraries
Size        : 664664
License     : GPLv2+ and LGPLv2+ with exceptions
Signature   : (none)
Source RPM  : rpm-4.13.0-1.el7.centos.src.rpm
Build Date  : Tue Jan 17 16:26:43 2017
Build Host  : e9758c379042
Relocations : (not relocatable)
URL         : http://www.rpm.org/
Summary     : Libraries for manipulating RPM packages
Description :
This package contains the RPM shared libraries.
librpm.so.7()(64bit)
librpmio.so.7()(64bit)
rpm-libs = 4.13.0-1.el7.centos
rpm-libs(x86-64) = 4.13.0-1.el7.centos

-bash-4.2$ rpmbuild -ba rpm.spec
...
Wrote: /home/jsilhan/rpmbuild/SRPMS/rpm-4.13.0-1.el7.centos.src.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-libs-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-build-libs-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-devel-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-build-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-sign-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-python-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/noarch/rpm-apidocs-4.13.0-1.el7.centos.noarch.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/noarch/rpm-cron-4.13.0-1.el7.centos.noarch.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-plugin-selinux-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-plugin-syslog-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-plugin-systemd-inhibit-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-plugin-ima-4.13.0-1.el7.centos.x86_64.rpm
Wrote: /home/jsilhan/rpmbuild/RPMS/x86_64/rpm-debuginfo-4.13.0-1.el7.centos.x86_64.rpm
...
+ exit 0

-bash-4.2$ rpm -qp ~/rpmbuild/RPMS/x86_64/rpm-libs-4.13.0-1.el7.centos.x86_64.rpm  --provides
librpm.so.3()(64bit)
librpmio.so.3()(64bit)
rpm-libs = 4.13.0-1.el7.centos
...

-bash-4.2$ rpm -qp ~/rpmbuild/RPMS/x86_64/rpm-python-4.13.0-1.el7.centos.x86_64.rpm --requires
...
librpm.so.7()(64bit)
librpmbuild.so.7()(64bit)
librpmio.so.7()(64bit)
librpmsign.so.7()(64bit)
python(abi) = 2.7
rpm = 4.13.0-1.el7.centos
...
```

**Comment by ignatenkobrain** [comment]
I will make a patch for it

**Comment by Conan-Kudo** [comment]
I've encountered a similar issue when I was building pythonX-rpm by hand on PCLinuxOS when I was attempting to upgrade them from 4.8.1 to 4.12.0.1. There didn't appear to be an obvious way to fix this, as the setuptools is wont to refer to system libraries for linking rather than the ones provided in the build.

**Comment by pmatilai** [comment]
The issue here is pretty convoluted: the setup.py method of building was originally added primarily to support shipping python-bindings as a separate tarball, to support building multiple versions of the bindings. The former never happened, and to support Py 2 vs 3 people have been building the bindings in-tree with the setup.py method, which never really really worked. 

Now that that Python 2 is no longer supported at all, I think the solution to this is either axe the setup.py method entirely, or make it error-out if trying to build in-tree.

**Comment by Conan-Kudo** [comment]
Without the setup.py, we don't have the egg-info data which other projects use to depend on the Python bindings. The Autofoo should probably just be reworked to call setup.py instead.

**Comment by pmatilai** [comment]
Right, that's a fair point.

Ultimately there should indeed be just one way to build the bindings, maintaining multiple ways was never a good idea anyway. OTOH calling setup.py from inside automake sounds like a nightmare too.

**Comment by pmatilai** [comment]
This resurfaced via #2230. So okay, losing egg-info would be a loss, but if one actually looks at this precious egg:
```
etadata-Version: 1.0
Name: rpm
Version: 4.18.0
Summary: Python bindings for rpm
Home-page: http://www.rpm.org/
Author: UNKNOWN
Author-email: rpm-maint@lists.rpm.org
License: GNU General Public License v2
Description: UNKNOWN
Platform: UNKNOWN
```

I think we're able to create such a file without the aid of a Python library :sweat_smile:

**Comment by Conan-Kudo** [comment]
We can probably do this with the CMake build and rip out everything else.

**Comment by pmatilai** [comment]
It's a deal :grin:

**Comment by pmatilai** [comment]
There you go: https://github.com/rpm-software-management/rpm/pull/2231
