### ISSUE TITLE
Question: multi-threaded zstd compression

### ISSUE THREAD

**Issue by marxin** [rpm-software-management/rpm#1300]
I'm curious if `zstd` compression can utilize more threads for a single `.rpm` file?
Is there any control of the threading level?

**Comment by marxin** [comment]
Related to #256.

**Comment by marxin** [comment]
The answer is that threads are not supported right now.
Adding the author of the port (@n3npq), he may be interested in?

**Comment by ffesti** [comment]
As there now is a pull request (#1303) I am closing this ticket here. No need to distribute the discussion to multiple places.
