### ISSUE TITLE
Please that `rpmbuild -ba` includes `-br + -bb`, not `-bs + -bb`

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/rpm#1304]
From the manual page it isn't entirely clear:

```
       -ba    Build binary and source packages (after doing the %prep, %build,
              and %install stages).

       -bb    Build  a  binary  package  (after  doing  the %prep, %build, and
              %install stages).

       -bs    Build just the source package.

       -br    Build just the source package - but calculate  and  include  the
              dynamic build requires.
```

Deducting from behavior, `-ba` produces `-br` source RPM variant (not the `-bs` simple variant).
But this should be clearly obvious from the option description.

**Comment by ffesti** [comment]
Sorry, I am not quite understanding what you are suggesting here. My guess is you want that rpmbuild man page is more clear?

**Comment by praiskup** [comment]
> My guess is you want that rpmbuild man page is more clear

Yes.
