### ISSUE TITLE
librpm and its python bindings should give enough messages in order to debug problems in a black box fashion

### ISSUE THREAD

**Issue by KOLANICH** [rpm-software-management/rpm#1307]
librpm has very bad error messages implementation. It is really hard to determine what is going wrong. It should have more debug messags calls in strategical points - at least before every branch leading to returning failure.

error reporting in python bindings should be fixed too

**Comment by pmatilai** [comment]
Acknowledged, but this is such a broad and sweeping issue that it will never be possible to submit a commit that will "fix this". Also excessive debugging is distracting to the actual code logic, so while diagnostics is important, too much is too much.
