### ISSUE TITLE
How to unpack an rpm file into a dir using librpm python bindings?

### ISSUE THREAD

**Issue by KOLANICH** [rpm-software-management/rpm#1310]
Under unpacking I mean that I should be able to control all the aspects:
* whether the embedded scripts (preinst, postinst, etc) are run
* which args are passed to them
* where exactly each file is unpacked
or
* which is the prefix for all the files that will be unpacked 

And there should be no way for a package to subvert it. I.e. if I it is done by defining some macro, I wonder if a package can redefine that macro.

**Comment by ffesti** [comment]
The ticket system is not a help forum. Please ask questions like this on #rpm.org @freenode or on the mailing lists. See http://rpm.org/community.html for details.
To the question at hand: There is an rpm.archive class. An instances can be obtained from an rpm.files object with the .archive() method. Some documentation on these classes can be found with `pydoc rpm`.
But to my knowledge this code has rarely been used - if ever. So there may be dragons... (like hard links - or worse)

Unless you have good reason consider using rpm2archive or rpm2cpio.

**Comment by KOLANICH** [comment]
Thank you.
