### ISSUE TITLE
When compiling rpm-4.16.0-beta3 from source, following error occurs at make step

### ISSUE THREAD

**Issue by pixdrift** [rpm-software-management/rpm#1316]
When compiling rpm-4.16.0-beta3 from source, following error occurs at `make` step:
```
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I.. -I../include/ -I../misc -D_REENTRANT -Wall -Wpointer-arith -Wmissing-prototypes -Wstrict-prototypes -fno-strict-aliasing -fstack-protector -Wempty-body -fopenmp -g -O2 -MT pack.lo -MD -MP -MF .deps/pack.Tpo -c pack.c  -fPIC -DPIC -o .libs/pack.o
pack.c: In function 'packageBinaries':
pack.c:769:26: error: expected '#pragma omp' clause before 'priority'
  #pragma omp task untied priority(i)
                          ^
make[2]: *** [pack.lo] Error 1
```

Build environment is clean CentOS 7.8
`CentOS Linux release 7.8.2003 (Core)`

Versions of compiler, dependencies etc.
```
cpp-4.8.5-39.el7.x86_64
file-5.11-36.el7.x86_64
file-devel-5.11-36.el7.x86_64
file-libs-5.11-36.el7.x86_64
gcc-4.8.5-39.el7.x86_64
glibc-2.17-307.el7.1.x86_64
glibc-common-2.17-307.el7.1.x86_64
glibc-devel-2.17-307.el7.1.x86_64
glibc-headers-2.17-307.el7.1.x86_64
kernel-headers-3.10.0-1127.13.1.el7.x86_64
libarchive-3.1.2-14.el7_7.x86_64
libarchive-devel-3.1.2-14.el7_7.x86_64
libdb-5.3.21-25.el7.x86_64
libdb-devel-5.3.21-25.el7.x86_64
libdb-utils-5.3.21-25.el7.x86_64
libgcc-4.8.5-39.el7.x86_64
libgcrypt-devel-1.5.3-14.el7.x86_64
libgomp-4.8.5-39.el7.x86_64
libgpg-error-devel-1.12-3.el7.x86_64
libmpc-1.0.1-3.el7.x86_64
lua-devel-5.1.4-15.el7.x86_64
lzo-2.06-8.el7.x86_64
make-3.82-24.el7.x86_64
mpfr-3.1.1-4.el7.x86_64
popt-devel-1.13-16.el7.x86_64
python-magic-5.11-36.el7.noarch
zlib-devel-1.2.7-18.el7.x86_64
```

**Comment by pixdrift** [comment]
Duplicate.

**Comment by wxlg1117** [comment]
> 
> 
> When compiling rpm-4.16.0-beta3 from source, following error occurs at `make` step:
> 
> ```
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I.. -I../include/ -I../misc -D_REENTRANT -Wall -Wpointer-arith -Wmissing-prototypes -Wstrict-prototypes -fno-strict-aliasing -fstack-protector -Wempty-body -fopenmp -g -O2 -MT pack.lo -MD -MP -MF .deps/pack.Tpo -c pack.c  -fPIC -DPIC -o .libs/pack.o
> pack.c: In function 'packageBinaries':
> pack.c:769:26: error: expected '#pragma omp' clause before 'priority'
>   #pragma omp task untied priority(i)
>                           ^
> make[2]: *** [pack.lo] Error 1
> ```
> 
> Build environment is clean CentOS 7.8
> `CentOS Linux release 7.8.2003 (Core)`
> 
> Versions of compiler, dependencies etc.
> 
> ```
> cpp-4.8.5-39.el7.x86_64
> file-5.11-36.el7.x86_64
> file-devel-5.11-36.el7.x86_64
> file-libs-5.11-36.el7.x86_64
> gcc-4.8.5-39.el7.x86_64
> glibc-2.17-307.el7.1.x86_64
> glibc-common-2.17-307.el7.1.x86_64
> glibc-devel-2.17-307.el7.1.x86_64
> glibc-headers-2.17-307.el7.1.x86_64
> kernel-headers-3.10.0-1127.13.1.el7.x86_64
> libarchive-3.1.2-14.el7_7.x86_64
> libarchive-devel-3.1.2-14.el7_7.x86_64
> libdb-5.3.21-25.el7.x86_64
> libdb-devel-5.3.21-25.el7.x86_64
> libdb-utils-5.3.21-25.el7.x86_64
> libgcc-4.8.5-39.el7.x86_64
> libgcrypt-devel-1.5.3-14.el7.x86_64
> libgomp-4.8.5-39.el7.x86_64
> libgpg-error-devel-1.12-3.el7.x86_64
> libmpc-1.0.1-3.el7.x86_64
> lua-devel-5.1.4-15.el7.x86_64
> lzo-2.06-8.el7.x86_64
> make-3.82-24.el7.x86_64
> mpfr-3.1.1-4.el7.x86_64
> popt-devel-1.13-16.el7.x86_64
> python-magic-5.11-36.el7.noarch
> zlib-devel-1.2.7-18.el7.x86_64
> ```

This happened to me, how did you solve this problem in the end?

**Comment by pmatilai** [comment]
Pass `--disable-openmp` to `configure` if your compiler doesn't support OpenMP >= 4.5
