### ISSUE TITLE
Missing concise descriptions for rpm header tags

### ISSUE THREAD

**Issue by drahnr** [rpm-software-management/rpm#1319]
In both 
http://ftp.rpm.org/max-rpm/s1-rpm-file-format-rpm-file-format.html

and the 4.15.1 release there are

```
{ "RPMTAG_FSCONTEXTS", "Fscontexts", RPMTAG_FSCONTEXTS, RPM_STRING_ARRAY_TYPE, RPM_ARRAY_RETURN_TYPE, 1 },
{ "RPMTAG_RECONTEXTS", "Recontexts", RPMTAG_RECONTEXTS, RPM_STRING_ARRAY_TYPE, RPM_ARRAY_RETURN_TYPE, 1 },
```

defined, but description is not very concise what they are.

Since I am looking into impl policy file support as part of https://github.com/Richterrettich/rpm-rs/issues/18 and I would like to know if the above are relevant to policies at all, and what they are (either way).

So far all I can see that is relevant for selinux is 
```
{ "RPMTAG_POLICIES", "Policies", RPMTAG_POLICIES, RPM_STRING_ARRAY_TYPE, RPM_ARRAY_RETURN_TYPE, 0 },
```

Could you shed some light into this? Thank you!

**Comment by drahnr** [comment]
anyone :question:

**Comment by pmatilai** [comment]
The context tags are unused since rpm 4.6 or so. There's some support for packaging SELinux policies in librpmbuild but no corresponding install-time support.

**Comment by drahnr** [comment]
> The context tags are unused since rpm 4.6 or so. There's some support for packaging SELinux policies in librpmbuild but no corresponding install-time support.

Could you elaborate a bit on what "install time support" exactly means?

**Comment by pmatilai** [comment]
In other words, it simply means that rpm doesn't actually *do* anything with it. The only thing rpm does with SELinux is that on install, it queries the system policy for correct file contexts.

**Comment by drahnr** [comment]
The only meaningful reference I could find on packaging policies is https://fedoraproject.org/wiki/PackagingDrafts/SELinux_Independent_Policy  

Looking at memcached, the policy file is simply packaged as a sub-package of the actual package https://src.fedoraproject.org/rpms/memcached/blob/6e70f59bdad0ba4cc1a1a7e5abc237d2e2f1c13a/f/memcached.spec#_120 with a bunch of `pre` and `post` actions.
But there is also an additional explicit dependency on the selinux sub-package declared, `Requires: (%{name}-selinux if selinux-policy-targeted)` which poses the question, what purpose does the header really have?
Is any of those headers actually being used in practice

I really appreciate getting a few answers to my questions, thanks! :+1:

**Comment by pmatilai** [comment]
Like said, rpm has some support for packaging policies BUT nothing inside or outside rpm actually uses that data. So for all practical purposes, rpm has no special support for packaging policies, hence the Fedora style packaging.

The partial support is a leftover from attempted policy support, which might some day be reimplemented in a different way, but there are no actual plans to do so.
