### ISSUE TITLE
how to cross compile fedora source rpm for RISC-V architecture 

### ISSUE THREAD

**Issue by billasurendra** [rpm-software-management/rpm#1327]
Dear all,

Can anyone please help me out, how to cross compile fedora source rpm for RISC-V.

Thanks
Billa Surendra

**Comment by ffesti** [comment]
This is the ticket system for rpm development and not a support forum. General question on using rpm can go on the rpm mailing list or the #rpm.org IRC channel. See  http://rpm.org/community.html for details.

About your question: Bootstrapping a distribution like Fedora is a non trivial task that involved lots of Fedora specific things. Some packages need to be build by hand with a crosscompiler or on another operating system. Some packages may require multiple rebuilds with different dependencies available. You are therefore probabably better of asking this question on the fedora-devel list. AKFAIK there is no longer a secondary arch group in Fedora still there should be a lot of people with actual experience from bootstrapping other architectures.

As we are concerned with developing rpm itself we here have very limited knowledge about the details of such process.
