### ISSUE TITLE
Define shell to use with %()

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/rpm#1334]
It would be nice to be able to define which shell should be used with `%()` given that `/bin/sh` is not the same shell on all distros.  Additionally having to write `$()` macros to the lowest common denominator is just ugly.  It's much nicer to just make _bash_ a `BuildRequires:` and be able to write bashisms in`%$()`.  Particularly given that most(?) distros do use bash for `/bin/sh` and only a few outliers don't.

**Comment by Conan-Kudo** [comment]
My understanding is that this should be tied to the `%_buildshell` macro already.

**Comment by pmatilai** [comment]
%_buildshell is for building, %() is macro engine builtin which has no place following rpmbuild -level macro definitions.

**Comment by dmnks** [comment]
@pmatilai good point. That being said, @Conan-Kudo has pointed out that we do in fact respect `%_buildshell` in other, non-build related areas as well. Doing a quick grep reveals for example:

`macros.in:%__spec_prep_shell    %{___build_shell}`

Still, that doesn't mean we should follow that trend, especially given that macro processing really is a separate step in the whole spec building process. Also, making `%()` suddenly use `%_buildshell` could cause unexpected things to happen in spec file which already redefine it. For consistency's sake, on the other hand, it would make sense to reuse it...

**Comment by dmnks** [comment]
So something like a `%_macroshell` would be a better idea, perhaps. But I'm not sure. I'll need to run a more comprehensive search in the code base first, to be able to make an educated guess :)

**Comment by voxik** [comment]
Can't you run `%(/usr/bin/bash)`?

**Comment by dmnks** [comment]
Sure you can. It's worth noting that this RFE is mostly cosmetic; being able to redefine a macro shell would allow you to replace all the `%(/usr/bin/bash -c "...")` calls with `%(...)`, as well as avoid spawning a shell just to spawn another shell.

**Comment by voxik** [comment]
So will Ruby by supported as well? Not that I really care, but what starts simple might provoke questions like these.

**Comment by brianjmurrell** [comment]
@voxik I can't see why Ruby (or python, or awk, or any other interpreter) would not work.  As for _supported_, that's not my call.

But as you point out, this does allow the spec writer more flexibility in what interpreter their spec evaluates macros, but does require them to define the shell in their spec to get something other than the default `/bin/sh`.

This is not unlike [setting SHELL in Makefiles](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html).

**Comment by dmnks** [comment]
@voxik That's an interesting idea. You can then do something like `%(ruby: ...)` or `%(python: ...)` or what have you. Sounds cool. Not sure about the impact of this in a broader sense, but I don't see any reason it couldn't be done.

That said, doing something just because "we can" doesn't always translate well into the maintenance side of things :) But if there are real-life use cases that would be improved with this, I think we'd open for that.

**Comment by dmnks** [comment]
> This is not unlike [setting SHELL in Makefiles](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html).

+1

**Comment by dmnks** [comment]
Oh, I think I misunderstood. As @brianjmurrell said above, any interpreter would work, yes :)

**Comment by dmnks** [comment]
@brianjmurrell is correct. All we would do is pass the given string enclosed in `%()` to the interpreter of choice, so if that's what you mean by "supported", then sure!

**Comment by dmnks** [comment]
I'm yet to understand if there are any security implications by allowing to redefine the shell in a macro, though. But we already allow that for building anyway, and building a spec file is no different from running a regular shell script after all (you should audit the spec file before doing so).

**Comment by brianjmurrell** [comment]
Looks like a comment got deleted that proposed syntax such as `%(ruby: ...)` or `%(python: ...)` which is interesting because I was thinking of something similar, along the lines of `%('/bin/bash': ...)` where the value before the `:` is the interpreter to use, rather than strings like `ruby` and `python` needing to be translatable into a path of something to execute.

**Comment by dmnks** [comment]
Yeah, I deleted that comment after realizing I misunderstood @voxik's question, but thinking again, it really is not a bad idea at all! It would be easier than having to redefine `%_macroshell` (or whatever we'd call it) and also cleaner, as you say. It would also get  rid of the problem with "how do we pass the script body into a non-shell-like interpreter" that I mentioned above.

**Comment by pmatilai** [comment]
Making everything configurable is not such a hot idea, really. Making the shell macro configurable means you open up the possibility of anybody screwing up the core macro primitive. %() equals popen() which means system shell, whatever that is, and I believe that should be left alone.

**Comment by pmatilai** [comment]
Note that having a *compile-time* way of hardwiring the shell of rpm macro engine would be an entirely different thing. But that would mean abandoning popen() and doing all the lifting by ourselves, popen() is hardwired to /bin/sh. Doesn't seem worth it to me.

**Comment by Conan-Kudo** [comment]
@dmnks There were multiple pull requests to attempt to add `%{python:}` several years ago, unfortunately they didn't go anywhere. If we want to add this functionality, we should probably start from #190 (which was the last attempt to do this).

**Comment by pmatilai** [comment]
We don't want embedded Python now any more than we did back then.

A generic way of grabbing output from a command without invoking the shell in between I might consider, but nothing that adds language specifics into rpm, when we're in the process of getting rid of them alltogether. And I'm dubious about the cost of shell invocation being prohibitive when talking in the context of Python, Perl and the like - the biggest cost is invoking the language itself.

**Comment by dmnks** [comment]
@Conan-Kudo, thanks for the pointers, I had the feeling this had been discussed in the past.

**Comment by brianjmurrell** [comment]
Fair enough on being able to invoke various interpreters.  I don't have enough interest to lobby for that.

But being able to define the posix shell that `%()` uses would be useful and make for more portable specfiles.

**Comment by pmatilai** [comment]
Well, /bin/sh is by definition *the POSIX shell* - if you avoid using any possible extensions there are... (but yes of course accumulating eg bashism is creepishm easy :)

**Comment by brianjmurrell** [comment]
> if you write compatibly and avoid using any possible extensions there are

You end up having to invoke forty-eleven other tools (awk, sed, grep, tr, etc.) to do what bash can do.  :-(

**Comment by pmatilai** [comment]
For complicated macros beyond "grab the output of foo -l" scale, Lua is recommended. It's by far the fastest scripting language available in rpm context, no forks involved to invoke the interpreter or shell etc.

**Comment by pmatilai** [comment]
We can't possibly allow diverting the low-level `%()` primitive to some alternative shell as that is documented to be `/bin/sh` and that's what all the other macros are expecting. If one macro starts expecting something else... it's not going to end well.
