### ISSUE TITLE
RPM must kill all childs on exit (from section?)

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#134]
Imagine, we have some stupid program which forks and doesn't exit until we send SIGTERM/SIGKILL, so build finishes, but process is still running. easy way to reproduce is just run `./hang &` from `%check`.

I think @voxik has some real example in mongodb build while I have only dummy one:

hang.c:
```c
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
 
volatile sig_atomic_t done = 0;
 
static void
term (int signum)
{
  ;
  //done = 1;
}
 
int
main (int   argc,
      char *argv[])
{
  struct sigaction action;
  memset (&action, 0, sizeof (struct sigaction));
  action.sa_handler = term;
  sigaction (SIGTERM, &action, NULL);
                         
  int loop = 0;             
  while (!done)                 
    {                                       
      int t = sleep (3);                                    
      /* sleep returns the number of seconds left if interrupted */
      while (t > 0)                                                 
        {                                                                           
          printf ("Loop run was interrupted with %d "                                                   
                  "sec to go, finishing...\n", t);                                                                                         
          t = sleep(t);
        }                                                                                                                   
      printf("Finished loop run %d.\n", loop++);                            
    }                                                                           
                                 
  printf("done.\n");                
  return 0;                             
}
```

hang.spec:
```rpmspec
Name:           hang
Version:        1
Release:        1%{?dist}
Summary:        Hanging build

License:        Public Domain
URL:            https://fedoraproject.org
Source0:        hang.c

BuildRequires:  gcc

%description
%{summary}.

%prep
%autosetup -c -T

%build
gcc %{__global_cflags} %{__global_ldflags} %{S:0} -o hang

%check
./hang &

%files

%changelog
```

I think easiest way is to catch all childs and send SIGKILL, but if we want to send SIGTERM, we will need to try sending SIGTERM, wait some time, check for still-alive processes and send SIGKILL.
```

**Comment by voxik** [comment]
This is the use case:

http://pkgs.fedoraproject.org/cgit/rpms/rubygem-mongo.git/tree/rubygem-mongo.spec#n79

Please note it works just fine with rpm build or when using mock with (--old-)chroot on the backend

**Comment by voxik** [comment]
But honestly, I am no sure why/how this should be handled on RPM side ...

**Comment by ignatenkobrain** [comment]
@voxik try to compile package as I showed above. You run something in background from RPM, you get RPMs, but process is still running which is IMO not acceptable.

**Comment by pmatilai** [comment]
I tend to agree with @ignatenkobrain, no processes should be left around once build completes.

**Comment by voxik** [comment]
If I remember correctly, I met this issue running rpmbuild inside mock, which is actually using systemd-nspawn, which complained during the container shutdown. Moreover, I think that systemd-run is not available inside mock, so I am not convinced this is the right solution.

**Comment by n3npq** [comment]
None of systemd-nspawn, systemd-run, mock or Koji or (for that matter) bash have much to do with rpmbuild.

Expecting rpmbuild to solve complex issues involving runtime environment cleanup is bad craziness.

You might consider -- say -- reporting an RFE to systemd or mock or koji or bash to kill all children on exit to see why this RFE against rpmbuild is bad craziness. All of systemd/mock/Koji are much better positioned to determine the runtime environment in which rpmbuild runs than rpmbuild is.

Alternatively writing a wrapper (essentially what is already in systemd-run) that invokes rpmbuild and kills all children is entirely feasible.

**Comment by n3npq** [comment]
None of systemd-nspawn, systemd-run, mock or Koji or (for that matter) bash have much to do with rpmbuild.

Expecting rpmbuild to solve complex issues involving runtime environment cleanup is bad craziness.

You might consider -- say -- reporting an RFE to systemd or mock or koji or bash to kill all children on exit to see why this RFE against rpmbuild is bad craziness. All of systemd/mock/Koji are much better positioned to determine the runtime environment in which rpmbuild runs than rpmbuild is.

Alternatively writing a wrapper (essentially what is already in systemd-run) that invokes rpmbuild and kills all children is entirely feasible.

**Comment by n3npq** [comment]
None of systemd-nspawn, systemd-run, mock or Koji or (for that matter) bash have much to do with rpmbuild.

Expecting rpmbuild to solve complex issues involving runtime environment cleanup is bad craziness.

You might consider -- say -- reporting an RFE to systemd or mock or koji or bash to kill all children on exit to see why this RFE against rpmbuild is bad craziness. All of systemd/mock/Koji are much better positioned to determine the runtime environment in which rpmbuild runs than rpmbuild is.

Alternatively writing a wrapper (essentially what is already in systemd-run) that invokes rpmbuild and kills all children is entirely feasible.

**Comment by pmatilai** [comment]
Well I'm not seriously suggesting dragging in systemd for a rare corner case issue. OTOH we're not going to catch *all* children launched from a shell we invoked without something more advanced and non-portable - all of those are likely to look like serious overkill anyway. 

We could of course do something like this:

```
-%___build_post         exit $?
+%___build_post \
+  RPM_EC=$?\
+  for pid in $(jobs -p); do kill ${pid}; done\
+  exit ${RPM_EC}\
+%{nil}
```

...which won't catch a process that forked into background by itself, but it'd catch anything invoked with &. Which would be better than nothing I guess.

**Comment by voxik** [comment]
Just two ideas:

1. What if there was something like begin, ensure, end block? I.e. I could ensure that the executed process is really terminated, although the test suite failed.
2. What if I could somehow register/execute some process in background using some RPM framework? I.e. RPM would be aware there is some process running which should be terminated.

These are not universal

**Comment by pmatilai** [comment]
It's just a plain old shell executing whatever was in the build script, it doesn't know anything about rpm or blocks. Also any co-operative scheme is a fail, what we'd like to catch is accidents.

As of commit 06953879d3e0b1e9a434979056d1225ab4646142 rpm kills any background jobs left from build-scripts, that's the best we can do without venturing into Linux-specific container etc business. For further protection, run builds under something like systemd-run which can actually track all the processes (via cgroups or whatever).
