### ISSUE TITLE
rpm -q --whatrequires loosing packages

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1342]
```
live@rosa2019 ~ $ export LC_ALL=C
live@rosa2019 ~ $ dnf repoquery --whatrequires bootsplash
Last metadata expiration check: 0:01:21 ago on Fri Aug 21 23:12:52 2020.
Rosa-theme-EE-0:2.0.0-115.noarch
bootsplash-themes-0:2.1.0-10.noarch
live@rosa2019 ~ $ rpm -q --whatrequires bootsplash
no package requires bootsplash
live@rosa2019 ~ $ rpm -qR Rosa-theme-EE
/bin/sh
/bin/sh
/bin/sh
bootsplash >= 3.3.0
plymouth-plugin-script >= 0.8.2
plymouth-system-theme
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
live@rosa2019 ~ $
```

`rpm -q --whatrequires bootsplash` must have shown Rosa-theme-EE and bootsplash-themes but has not.
BerkelyDB is used for now.

Seems to be a bug.

If it is useful, this is an out of the box issue in this LiveCD: https://abf.io/platforms/rosa2019.1/products/273/product_build_lists/34888

**Comment by pmatilai** [comment]
If the bootsplash dependency is a pre-scriptlet dependency then this is expected behavior, rpm does not record such dependencies in the database. What does `rpm -qRv Rosa-theme-EE` output?

**Comment by pmatilai** [comment]
Since there's no further activity, I assume this was an install-only dependency. Not the first time somebody is surprised by this.
