### ISSUE TITLE
Make use of %apply_patch easier

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1357]
I need to use git to apply binary patch. Therefore I thought about using `%apply_patch` and I ended up using the following:

~~~
%global __scm git_am
%{expand:%__scm_setup_%{__scm}}
%apply_patch -p1 %{PATCH4}
~~~

This is suboptimal, because I believe that the doubleunderscore macros are implementation detail and should not be used. You might admit that I should use `%autosetup` but I can't use it, because this is the current `%setup` line:

~~~
%setup -n %{gem_name}-%{version} -b 1 -b 3
~~~

i.e. it expands more sources prior expanding the main source and I don't think this is supported by %autosetup. So I have to keep using the `%setup`.

So I thinking about two possible extensions:

1. Allow to disable the `%setup` call from `%autosetup`.
2. Providing something like `%setup_scm` which would actually do the necessary setup for `%apply_patch`.

Please also note that on top of that, I actually need to apply patches in the `%{_builddir}`, so the current implementation is very limiting.

**Comment by soig** [comment]
Le mar. 8 sept. 2020 à 11:21, Vít Ondruch <notifications@github.com> a
écrit :

> I need to use git to apply binary patch. Therefore I thought about using
> %apply_patch and I ended up using the following:
>
> %global __scm git_am
> %{expand:%__scm_setup_%{__scm}}
> %apply_patch -p1 %{PATCH4}
>
> This is suboptimal, because I believe that the doubleunderscore macros are
> implementation detail and should not be used. You might admit that I should
> use %autosetup but I can't use it, because this is the current %setup
> line:
>
> %setup -n %{gem_name}-%{version} -b 1 -b 3
>
> i.e. it expands more sources prior expanding the main source and I don't
> think this is supported by %autosetup. So I have to keep using the %setup.
>

You can always use %autopatch in that case…
%autosetup is basically %setup + %autopatch (modulo some defaults)

So I thinking about two possible extensions:

**Comment by voxik** [comment]
> You can always use %autopatch in that case… %autosetup is basically %setup + %autopatch (modulo some defaults)

Applying single patch, it won't help. If the patch did not contain git binary diff, I would not bother at all. And the `(modulo some defaults)` is actually what I am after.

**Comment by pmatilai** [comment]
If you don't use %autosetup then why not just call 'git' directly?

%apply_patch was never supposed to be called by anybody directly, but I realize now that it looks that way because it lacks underscore-prefixes. I guess I'll submit a PR to change that... (for those using %autosetup, you can pass a range to %autopatch for finer control)

**Comment by voxik** [comment]
> If you don't use %autosetup then why not just call 'git' directly?

I was thinking about it for a second, but it needs quite some boilerplate. 

> %apply_patch was never supposed to be called by anybody directly, but I realize now that it looks that way

Yes it does.

> because it lacks underscore-prefixes. I guess I'll submit a PR to change that...

What can I say :man_shrugging: :disappointed:

**Comment by ffesti** [comment]
Not sure if it really worth changing anything here. Adding underscores won't really improve much. As this hasn't happened yet I'll just close this.
