### ISSUE TITLE
Possible to make DNF create damned package-config files for every installed package?

### ISSUE THREAD

**Issue by addstopbutton** [rpm-software-management/rpm#1371]
Hi guys!

Trying to build MPV player.
Have to install manually many packages (which according to dnf are already present) just to create required .pc files.

How to fix this?
Or maybe it's a known problem?

**Comment by pmatilai** [comment]
This is rpm bug tracker system, not a support forum. Try asking your question in your distributions support forum (mailing list, web forum or whatever).

**Comment by addstopbutton** [comment]
Dear @pmatilai 
it's just a decent "enhancement request" acc to this: https://rpm.org/community.html

**Comment by Conan-Kudo** [comment]
It is not RPM's job to create `.pc` files. It is the job of your code's build script to do that. RPM will just be able to read pc files that are intended to be wrapped in an RPM and generate dependency information from it.
