### ISSUE TITLE
rpmbuild generates srpm with invalid spec file name

### ISSUE THREAD

**Issue by crobinso** [rpm-software-management/rpm#1386]
@ignatenkobrain I bisected an rpmbuild regression to  commit acf5e00281d73a2f8034091241c7b0e2ba00e383

Before:
```console
$ ./rpmbuild -ts ~/src/python-bugzilla/dist/python-bugzilla-3.0.1.tar.gz && rpm -qlp /home/crobinso/rpmbuild/SRPMS/python-bugzilla-3.0.1-1.fc33.src.rpm
Wrote: /home/crobinso/rpmbuild/SRPMS/python-bugzilla-3.0.1-1.fc33.src.rpm
python-bugzilla-3.0.1.tar.gz
python-bugzilla.spec
```

After:
```console
$ ./rpmbuild -ts ~/src/python-bugzilla/dist/python-bugzilla-3.0.1.tar.gz && rpm -qlp /home/crobinso/rpmbuild/SRPMS/python-bugzilla-3.0.1-1.fc33.src.rpm
Wrote: /home/crobinso/rpmbuild/SRPMS/python-bugzilla-3.0.1-1.fc33.src.rpm
python-bugzilla-3.0.1.tar.gz
rpm-tmp.57WuUk
```

Notice the tempfile name is added to the SRPM, not the original spec path. `rpmbuild --rebuild` doesn't seem to mind, but mock errors with: `ERROR: No specfile found in srpm: python-bugzilla-3.0.1-1.fc33.src.rpm`.

I'm hitting this on Fedora 33 so if this is fixed upstream please backport to Fedora too

**Comment by pmatilai** [comment]
Thanks for reporting, we'll look into it.
