### ISSUE TITLE
Out of date translations on Transifex

### ISSUE THREAD

**Issue by piotrdrag** [rpm-software-management/rpm#14]
Translations are correctly downloaded from Transifex, but the POT file is not getting uploaded to <https://www.transifex.com/rpm-team/rpm/>, so it's over a year old.

**Comment by ffesti** [comment]
Set up the resource URL, so it should be updated automatically from now on.

**Comment by piotrdrag** [comment]
Translations has not been pushed/pulled since 2014, any chance of an update?
