### ISSUE TITLE
Macros in script comments are expanded

### ISSUE THREAD

**Issue by ascherer** [rpm-software-management/rpm#140]
At least with **rpmbuild 4.12.0.1** on Kubuntu 16.04 it seems to be impossible to comment parts of script sections. This code
```
%build
# Don't expand %autopatch here
```
_does_ invoke macro `%autopatch` quite inappropriately.

**Comment by ignatenkobrain** [comment]
Use `%%autopatch` to escape macro. But join #124 for discussion of possible solutions.

**Comment by pmatilai** [comment]
FWIW, in rpm >= 4.15 there's now a "real" commenting directive in the form of M4-inspired %dnl, see https://github.com/rpm-software-management/rpm/issues/158, https://github.com/rpm-software-management/rpm/commit/44180fc7400ea8e67a13c5581459ad13f1d14103 and https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/7Q3BZ6GTAKFDJMNOLNJJENMWCPQTTET7/ for more info.
