### ISSUE TITLE
option to disable fsync

### ISSUE THREAD

**Issue by cgwalters** [rpm-software-management/rpm#1401]
For rpm-ostree, we rely on ostree for transactionality - ostree does fsync (or not) per its configuration.

As best I can tell, rpm doesn't offer an API to disable its use of fsync (for the database or for writing files, though I only really care about the former).  There are references to `nofsync` which I *think* is only parsed by the db3 backend?

I know about things like [libeatmydata](https://github.com/stewartsmith/libeatmydata) but the problem of course is that librpm is linked into the same process (rpm-ostree) as the code that is doing the ostree commit.

We already use FUSE for scripts, so I could probably intercept the writes with FUSE but I'd imagine adding an API for this would be fairly straighforward, right?

EDIT: Forgot to mention the immediate motivation for this is that during an rpm-ostree build the part where we're writing the rpmdb is noticeably slow and I traced it to `fsync()` calls.

**Comment by xsuchy** [comment]
Are you aware of 
  https://github.com/kjn/nosync
?

**Comment by cgwalters** [comment]
> Are you aware of https://github.com/kjn/nosync

Looks like the same as what I mentioned above originally:

> I know about things like libeatmydata but the problem of course is that librpm is linked into the same process (rpm-ostree) as the code that is doing the ostree commit.

**Comment by cgwalters** [comment]
There's a recent [change to add volatile to overlayfs](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c86243b090bc) which will mostly mitigate this, although overlayfs isn't available to unprivileged code paths right now.

I guess in the end it is easier to just change the kernel rather than trying to patch various userspace projects.

See also [this twitter subthread](https://twitter.com/ibuildthecloud/status/1318928003422826497).

**Comment by ffesti** [comment]
Yes, we are really not that keen on (re-) adding nofsync support. There is some optimization in there for new installations which are run with only one SQLite transaction for the whole thing but that's as far as we really want to go with that.
