### ISSUE TITLE
%_default_patch_fuzz not applied to %autosetup

### ISSUE THREAD

**Issue by stormi** [rpm-software-management/rpm#1405]
Current implementation of `%autosetup` applies patches with the default fuzz factor of the patch binary, which is 2.

I have looked for a way to set it to 0 and discovered that there exists a `%_default_patch_fuzz` macro, whose value is 0, but it's not taken into account outside `patchX` macros.

I suggest `%autosetup` applies `%_default_patch_fuzz` too.

**Comment by Conan-Kudo** [comment]
We've been doing this since RPM 4.14 already, see 66a6082634687e45b321a5ade9887420d5830162.

Either your version of RPM is too old, or the distribution is setting a fuzz of 2 by default.

**Comment by stormi** [comment]
Oh, I see, I've searched for `_default_patch_fuzz` but missed `%{_default_patch_fuzz}` :1st_place_medal: 
Thanks!
