### ISSUE TITLE
Output of Lua code truncated after NUL character

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1437]
`%{lua:print "\0a"}` expands to the empty string, which is almost certainly not what the programmer intended.  Since NUL characters aren’t allowed in macro expansions, RPM should emit an error in this case.

**Comment by pmatilai** [comment]
I see little harm done in the empty string, compared to the overhead of scanning all strings for embedded \0's just to be able to print errors. Macro performance is something people care about quite deeply.
