### ISSUE TITLE
\x1a (ASCII unit separator) cannot be escaped

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1438]
Right now, I cannot write a Lua function `quote_array` that converts an array of strings to a string that (when used as the argument to a macro) will be interpreted as the initial array.  This is because \\x1a (ASCII unit separator) cannot be escaped.

One solution would be to allow \\x1a to be escaped by doubling it, and have `%{quote:…}` do this automatically.

**Comment by pmatilai** [comment]
Rpm macro engine is just a very simple-minded text processor. Handling binary data is out of scope.

**Comment by DemiMarie** [comment]
Indeed it is, but not being able to write `quote_array` is somewhat concerning, especially since `\x1a` is technically a valid character in filenames.

**Comment by pmatilai** [comment]
It's not legit in *rpm* filenames though. See https://github.com/rpm-software-management/rpm/blob/c1ca2e35025698328edcefa8dedee866d2ea0596/build/files.c#L1329

**Comment by pmatilai** [comment]
As per above, it's not a legitimate character in *rpm* filenames, and the macros do not deal with binary data. I don't see a need to complicate things for this.
