### ISSUE TITLE
%{**} loses whitespace

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1439]
If a macro is passed several arguments separated by some whitespace, I expect that `%{**}` includes the original whitespace.  Instead, this whitespace is lost.

**Comment by dmnks** [comment]
What you're looking for is the `%{quote:...}` macro, documented [here](https://rpm.org/user_doc/macros.html).

Example without the quote macro:
```
$ rpm --define 'hello() %{**}' --eval "%hello 1     2"
1 2
```
And with the macro:
```
$ rpm --define 'hello() %{**}' --eval "%hello 1 %{quote:     2}"
1      2
```

Hope that helps! I'm closing the issue now, please reopen if that's not what you meant. Thanks!
