### ISSUE TITLE
Defining %global macro in %pre results empty in %post

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [rpm-software-management/rpm#1440]
I have to retrieve in the SPEC file the previous installed version of the package. I'm trying to define this custom macro inside %pre:
```spec
%pre
  PREVIOUS_VERSION=$(/path/to/executable --version)
  %global _prevver $(echo $PREVIOUS_VERSION)
```
I will use it in the %post phase:
```spec
%post
  export PREVIOUS_VERSION=%{_prevver}
```
but sadly the %{_prevver} macro is empty inside %post... Is there anything I'm missing? The %global macro should be global and therefore defined also in the %post phase...

**Comment by pmatilai** [comment]
Scriptlets are separate processes, basically the only common thing between them is the parent PID. If you need to share data between scriptlets, you need to put it on the filesystem.

**Comment by giovanni-bertoncelli** [comment]
Thank you...
