### ISSUE TITLE
Restore %requires_eq

### ISSUE THREAD

**Issue by darix** [rpm-software-management/rpm#1452]
it was killed by accident in ba85c95963f9b62f237c0442f6b5aca3e355fa83

and I would be glad if it could also be backported to the fedora 33 rpm version again. so i can remove the copy of %requires_eq in the spec files.

Thank you in advance.

**Comment by pmatilai** [comment]
Removing it was no accident...

**Comment by darix** [comment]
the commit message was talking about the perl and python macros.

%requires_eq is not related to either of those. 

so what was the rational to remove it?

**Comment by pmatilai** [comment]
The perl-macros were using it, and were in fact the only user in rpm.
The other reason for wanting to get rid of it was the implementation (calling rpm from within rpm, discussed eg in #541 )

No plans to bring it back.
