### ISSUE TITLE
RFE: `rpm --macrofile` for using arbitrary macro file directories

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#1469]
Some time back, @daxelrod-datto suggested in https://github.com/debbuild/debbuild/issues/114 that debbuild implement a `--macrofile` option similar to the `--rcfile` option for overriding the macro search path for that invocation. It was noted there that this feature does not exist in RPM, and I would like to see this exist in RPM as well, so that we can have matching syntax and semantics in RPM and debbuild.

From the debbuild issue:

> A new `--macrofile` command line option with the same semantics [as `--rcfile`], but for configuring the path list for loading macro definitions.

Having this feature in RPM would make it easier to do arbitrary tests of macros and macro evaluation behavior in CI.

**Comment by voxik** [comment]
How is that different from #363, apart from file/directory.

**Comment by Conan-Kudo** [comment]
Not too much, but the use-case you wanted it for was not valid, since spec files can declare arbitrary macro files to be loaded. I want to be able to test `rpm --eval` with arbitrary macros in tests, which is quite different and cannot be satisfied with `%{load:}`.

**Comment by pmatilai** [comment]
Um? --macros=<path> exists since beginning of times, any 4.x version certainly.

**Comment by Conan-Kudo** [comment]
🤦🏾
