### ISSUE TITLE
Remove RedHat from HOWTO

### ISSUE THREAD

**Issue by yecril71pl** [rpm-software-management/rpm#1474]
RedHat, or rather Fedora, has deprecated RPM and does not offer any support for it.  Please remove links to RedHat and mentions thereof from the HOWTO document.  (It is, however, unclear that we are licensed to edit it, otherwise it should not be distributed.)

**Comment by Conan-Kudo** [comment]
Uhh, what? That not true. Nobody in Fedora deprecated RPM. Where did you get this information?

**Comment by yecril71pl** [comment]
> Uhh, what? That not true. Nobody in Fedora deprecated RPM. Where did you get this information?

They say DNL is chad now.

**Comment by Conan-Kudo** [comment]
Where? DNF is certainly far from dead...

**Comment by yecril71pl** [comment]
> Where? DNF is certainly far from dead...

By no means, and DNF replaces RPM.

**Comment by Conan-Kudo** [comment]
DNF _can't_ replace RPM, it's built on top of it.

**Comment by yecril71pl** [comment]
> DNF _can't_ replace RPM, it's built on top of it.

That means RPM is needed only for DNF and DNF developers, so no RPM HOWTO is needed.

> Use DNF Instead of RPM Whenever Possible

**Comment by pmatilai** [comment]
:popcorn:

**Comment by xsuchy** [comment]
> They say DNL is chad now.

Any link to source? I am not aware of any such statement.

**Comment by yecril71pl** [comment]
[RPM](https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/RPM/)

**Comment by ffesti** [comment]
This talks about users interacting with the rpm cli and advices them to use dnf as the higher level tool. This has nothing to do with the distribution still being based on rpm or not.

Closing.

**Comment by yecril71pl** [comment]
Since the user does not need to use the RPM CLI, there is no need to redistribute the RPM FAQ.

**Comment by pmatilai** [comment]
People need rpm and especially rpmbuild for all manner of things that dnf cannot do. Also, if you have an issue with Fedora documentation then the rpm upstream is not the place.

**Comment by yecril71pl** [comment]
> Also, if you have an issue with Fedora documentation then the rpm upstream is not the place.

I admit I may be confused here.  Is RPM HOWTO part of RPM or part of Fedora?
