### ISSUE TITLE
Redundant requires from generators are not merged

### ISSUE THREAD

**Issue by Vogtinator** [rpm-software-management/rpm#1476]
I wrote a requires generator for `.qml` files, which converts import statements to RPM capabilities in the format

```
qt5qmlimport(QtQuick.Controls.2) >= 3
qt5qmlimport(QtQuick.Controls.Layouts.2) >= 3
```

This works as expected, but the dependency generator is called for each file, so they accumulate. If one file needs version `2.3` and another needs `2.4`, the final package has:

```
qt5qmlimport(QtQuick.Controls.2) >= 3
qt5qmlimport(QtQuick.Controls.2) >= 4
qt5qmlimport(QtQuick.Controls.Layouts.2) >= 3
qt5qmlimport(QtQuick.Controls.Layouts.2) >= 4
```

The dependency generator is smart enough to only print the highest required version, but that can only work if it's fed with all files inside each package. That doesn't seem to be possible without using the external dep generator...

Would it be possible to merge those in RPM itself? Or even better, introduce a flag so that the generator is called only once for each package? That would also provide a speedup.

**Comment by mlschroe** [comment]
rpm needs to assign dependencies to files so that 'rpm -q --filerequire' works. So it can't simply drop dependencies.

In case you're wondering: rpm does this to ignore dependencies for files that are not installed, e.g. because they have the wrong file color.

**Comment by mlschroe** [comment]
(At least I thought it does that. Maybe that just was wishful thinking...)

**Comment by Vogtinator** [comment]
I see. For this case at least the mapping is not really useful.

How did this work with the old dep generators? Not at all, I assume?

**Comment by Conan-Kudo** [comment]
Pretty much not at all, since RPM shelled out to a program which then returned a blob of text it stored as dependency information.

**Comment by ffesti** [comment]
While there is [work to do in the dependency generation department](https://github.com/rpm-software-management/rpm/projects/11) I don't see us merging those dependencies as they are per file. Closing.
