### ISSUE TITLE
Document trailer invariants

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1481]
When working on #1471 I found that the invariants of the trailer are not documented anywhere I could find.  I expected them to be as follows:

- The trailer must come after the last index entry in the contiguous region.
- The trailer must not overlap with any other header entry, whether in the region or otherwise.
- The trailer must come before any data not in the region.

These should be documented so that code in librpm knows what it can rely on.

**Comment by pmatilai** [comment]
It's not just the region trailer that is undocumented, it's the whole v4 header format with the immutable region and all.

**Comment by DemiMarie** [comment]
Some other invariants I would like to enforce for packages:

- Alignment padding in a package must be kept to a minimum and must be zeroed.
- A header in a package may not have more than one tag data entry with a given tag.
- Tag data entries in a package must be sorted.

I would love to require that package signature headers be a contiguous region, but I understand that that has been shot down.

**Comment by pmatilai** [comment]
The region tag and the trailer are now documented  in #2861. 

I'm not going to document common sense like no data can overlap. This is also not a wishlist, refining further limitations belongs to v6.
