### ISSUE TITLE
RPMv6 proposal: have a “master signature” that signs the signature header

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1504]
The RPM signature header is growing more and more complex, with new types such as per-file and fsverity signatures being added.  This increases the risks of bugs in its parsing.  Since the signature header is not itself signed, these bugs are critical security vulnerabilities.

I propose that RPMv6 include a “master signature” that signs the signature and immutable headers.  This signature:

1. Includes the number of bytes between the end of the master signature and the start of the payload.
2. Includes the package lead, to prevent malleability.
3. Would be required for *all* packages, if signature verification is turned on.  DNF and libdnf would turn signature verification on when querying packages.
4. Is checked before the headers are even parsed.  Including the combined length of all headers makes this possible.  If this length turns out to be wrong, the package is malformed and MUST be rejected.  This ensures that at no point does RPM ever parse untrusted input.

**Comment by pmatilai** [comment]
Thanks for the suggestion, but this is not the kind of material we have in mind for rpm v6.

**Comment by DemiMarie** [comment]
@pmatilai where is the best place to discuss RPMv6 development?  I have several concerns about the current RPM file format that I would like to see addressed in RPMv6.
