### ISSUE TITLE
Documentation for %{expr:..} and %[...] is missing from rpm.org/user_doc/macros.html

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1519]
I was searching for it in https://rpm.org/user_doc/macros.html but found nothing.

**Comment by pmatilai** [comment]
Try the in-tree documentation instead: https://github.com/rpm-software-management/rpm/blob/master/doc/manual/macros.md

We'll need to have the rpm.org content pointing to the in-tree documenation sooner than later...

**Comment by pmatilai** [comment]
The expression section could also use some more concrete examples...

**Comment by pmatilai** [comment]
...such as those in the release notes (expressions section): https://rpm.org/wiki/Releases/4.16.0

**Comment by hroncok** [comment]
Thanks for the pointers.

**Comment by hroncok** [comment]
Related question: There is no `%ifarch` expression, right? E.g. `%{arch:a b c d}`/`%{narch:a b c d}` to evaluate to 0/1.

**Comment by pmatilai** [comment]
No, %if is strictly a spec construct. You can evaluate against the arch macros though, eg
`%[ "%{_target_cpu}" == "x86_64" ? 1 : 0]`

**Comment by hroncok** [comment]
Thanks.

**Comment by hroncok** [comment]
Feel free to close or repurpose this issue, but note that the docs situation is confusing.

**Comment by dmnks** [comment]
Thanks, closing in lieu of https://github.com/rpm-software-management/rpm-web/issues/19.
