### ISSUE TITLE
rpm2archive: Support uncompressed output

### ISSUE THREAD

**Issue by cgwalters** [rpm-software-management/rpm#1530]
See https://github.com/coreos/rpm-ostree/issues/2458
Basically it'd be inefficient for rpm-ostree to use rpm2archive today because it always compresses the output which we'd need to immediately uncompress again.

I looked at patch for this but got slightly lost in learning the ins&outs of popt arg parsing, but if this sounds ok I can try to finish that.

**Comment by ffesti** [comment]
If I had imagined the tool would be used in such a central role I might had added a few more options right from the start. Adding those features should pretty easy though. Feel free to bug me if you need help.

**Comment by ffesti** [comment]
After considering to expose more of libarchive's functionality like many compression methods and archive formats I opted to only add an option for uncompressed output - as requested.
Is the PR what you had in mind?

**Comment by ffesti** [comment]
Guess this is done.
