### ISSUE TITLE
RFE: make the hdrblob API public

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1538]

**Comment by Conan-Kudo** [comment]
Why?

**Comment by DemiMarie** [comment]
The header import code is large and complex.  I would much prefer to be able to iterate over headers in file order without having to invoke it.  In particular, `hdrblobInit` has a much smaller attack surface than `headerImport`.  This is *especially* important before signature verification.

**Comment by pmatilai** [comment]
NAK, it's specifically the kind of interface that we want to keep internal so we can change freely.
