### ISSUE TITLE
RFE: use fingerprints instead of key IDs internally

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1549]
Fingerprints are guaranteed to be unique, where as key IDs are not.

**Comment by pmatilai** [comment]
Yeah, started down this road in 2017 but ran into hidden obstacles or out of steam. Or both.

**Comment by DemiMarie** [comment]
At the very least we can check the fingerprint of a public key against those of its signatures.

**Comment by DemiMarie** [comment]
This will still need to be changed even if #1935 is fixed.

**Comment by pmatilai** [comment]
This has gotten implemented in the course of last 2-3 weeks over multiple PR's, at least #3321 #3369 #3390 are related
