### ISSUE TITLE
rpmdeps not creating basic library provides

### ISSUE THREAD

**Issue by barsnick** [rpm-software-management/rpm#1554]
I have a library where rpmdeps isn't creating the proper basic provides:

```
Processing files: l-smash-lib-2.16.1-0.20200316.git18a9ed2.fc33.2sunshine.x86_64
Executing(%license): /bin/sh -e /var/tmp/rpm-tmp.btpngv
[... unrelated license stuff]
Provides: l-smash-lib = 2.16.1-0.20200316.git18a9ed2.fc33.2sunshine l-smash-lib(x86-64) = 2.16.1-0.20200316.git18a9ed2.fc33.2sunshine
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Processing files: l-smash-debugsource-2.16.1-0.20200316.git18a9ed2.fc33.2sunshine.x86_64
```

This is from a build in Fedora copr:
https://download.copr.fedorainfracloud.org/results/barsnick/non-fed/fedora-33-x86_64/01344419-l-smash/builder-live.log.gz
(Choose any architecture, it doesn't matter.)

On the command line, it looks like this:
```
$ /usr/lib/rpm/rpmdeps --provides $PWD/usr/lib64/liblsmash.so.2
[no output]
$ echo $?
0
```
I'm explicitly missing
```
liblsmash.so.2()(64bit)
liblsmash.so.2(LSMASH_2)(64bit)
```

While for every other library, it looks like this (random example):
```
$ /usr/lib/rpm/rpmdeps --provides /usr/lib64/libgupnp-1.2.so.0.0.0
libgupnp-1.2.so.0()(64bit)
```

The binaries which depend on this library have the correct Depends though:
```
$ /usr/lib/rpm/rpmdeps --requires usr/bin/boxdumper 
libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
liblsmash.so.2()(64bit)
liblsmash.so.2(LSMASH_2)(64bit)
libm.so.6()(64bit)
rtld(GNU_HASH)
```

I can't for the life of me figure out what's different with this library, or special about the way it has been built. I have attached the dynamic lib to the ticket:
[liblsmash.so.2.zip](https://github.com/rpm-software-management/rpm/files/6018280/liblsmash.so.2.zip)

**Comment by pmatilai** [comment]
Missing executable permission on the library?

**Comment by barsnick** [comment]
Thank you, that was spot on. The program's Makefile had a bug, applying perms 644 at installation.
