### ISSUE TITLE
debugedit doesn't recognize DWARF DW_FORM_0x1f20 and DWARF DW_FORM_0x1f21

### ISSUE THREAD

**Issue by doko42** [rpm-software-management/rpm#1557]
Trying to set a build-id for a binary which was already compacted by dwz, you see:

debugedit: <file>: Unknown DWARF DW_FORM_0x1f20
debugedit: <file>: Unknown DWARF DW_FORM_0x1f21

**Comment by doko42** [comment]
warnings only, the build-id is still rewritten

**Comment by pmatilai** [comment]
Debugedit is being split to a separate project and frozen in rpm, please refile in https://sourceware.org/debugedit/

Apologies for the inconvenience.
