### ISSUE TITLE
rpmsign cannot use Ed25519 keys

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1565]
rpmsign successfully creates the signature, but then can’t figure out which tag to use for it.

**Comment by pmatilai** [comment]
Yup, one of the thousand internal projects waiting for something else to proceed.

**Comment by DemiMarie** [comment]
Can we just use `RPMSIGTAG_RSAHEADER`?  Tools like DNF and libdnf will be confused by a new tag number, and RPM itself doesn’t care.  DSA is largely deprecated by now anyway.

**Comment by pmatilai** [comment]
Fixed by #1571 / commit 23770e1a4f28c56a31fe600cae332c77333b60b6
