### ISSUE TITLE
Make the default DB backend macro configurable

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#157]
Currently if rpm is built with --enable-ndb, all newly created databases are in that format. We'll need more control over the format to enable safe testing which is a prerequisite for wider testing.

We need a macro configurable (%_rpmdb_backend or such) to set the default backend for newly created databases and default to BDB regardless of build-time options to be on the safe side. To convert to another format, changing the macro value to another backend and doing `rpmdb --rebuilddb` should be enough as rebuilddb starts by creating a new db.

It should be possible to arbitrarily switch back and forth between backends by --rebuilddb. I suspect currently it only works going from BDB to NDB because the files from the old database are not cleaned out on rebuild, IIRC. So that might need fixing too.

**Comment by ffesti** [comment]
Pushed as e96fde89c6e0ac59da5cb22fa310235a9918aa7a

**Comment by pmatilai** [comment]
Commit e96fde8 doesn't quite cut it:

```
backend/dbi.c: In function ‘dbDetectBackend’:
backend/dbi.c:39:5: warning: not enough variable arguments to fit a sentinel [-Wformat=]
     char *db_backend = rpmExpand("%{?_db_backend}");
     ^~~~
```

Also I think software should honor configuration: if it's configured to use db X then it shouldn't override that through auto-detection. Maybe more like, autodetect if %_db_backend set to "auto" or undefined, otherwise do what the configuration says even if it means erroring out of the situation?

**Comment by ffesti** [comment]
Fixed the warning above.

**Comment by ignatenkobrain** [comment]
@ffesti should we close this issue?

**Comment by pmatilai** [comment]
Yeah I suppose we can close this now, the format detection is less of an issue now that rebuillddb wipes out the old cruft.
