### ISSUE TITLE
RFE: forbid extra packets after a signature

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1601]
RPM currently does not check that a signature contains exactly one packet.  Requiring that a signature have exactly one packet would reduce the attack surface of RPM, but would reject packages with multiple signatures.  If this is not possible, we can at least reject signatures that have non-signature packets.

**Comment by pmatilai** [comment]
Fixed by yourself in commit 5ff86764b17f31535cb247543a90dd739076ec38
