### ISSUE TITLE
%defattr(644,root,root,755) -> %_defaultdocdir gets perm 644

### ISSUE THREAD

**Issue by DimStar77** [rpm-software-management/rpm#162]
There seems to be a weird regression in rpm 4.13.

If a package contains

```
%files
%defattr(644,root,root,755)
%doc README
```

then the file README is copied to %{_defaultdocdir}/%{name} as expected, but said directory is assigned permission 644 (instead of 755). This used to work correct with rpm 4.12

rpm 4.12:
```
rpm -qlvp test-0-0.x86_64.rpm
drwxr-xr-x    2 root    root                        0 Feb 20 23:13 /usr/share/doc/packages/test
-rw-r--r--    1 root    root                       11 Feb 20 23:13 /usr/share/doc/packages/test/dummy
```
rpm 4.13:
```
rpm -qlvp test-0-0.x86_64.rpm 
drw-r--r--    2 root    root                        0 Feb 20 23:19 /usr/share/doc/packages/test
-rw-r--r--    1 root    root                       11 Feb 20 23:19 /usr/share/doc/packages/test/dummy
```

**Comment by pmatilai** [comment]
Yes.  It's also been already fixed in both git master (commit bde88ada3a0fbd17f9b5db9fb5426eb0f1ff5efd) and the just released rpm 4.13.0.1 (http://rpm.org/wiki/Releases/4.13.0.1).

Thanks for the report though :)
