### ISSUE TITLE
RPM is removing gd locale from packages

### ISSUE THREAD

**Issue by gunchleoc** [rpm-software-management/rpm#1620]
The Cawbird project is currently trying to create a package containing a gettext translation into Scottish Gaelic, which is being removed by RPM.

> "removing translation /usr/share/locale/gd/LC_MESSAGES/cawbird.mo: 322 translated messages."

C.f. Twitter thread: https://threadreaderapp.com/thread/1379717512514899968.html

I am the translator and I could provide any locale data you need to solve this.

**Comment by pmatilai** [comment]
Rpm does no such thing.

There could be a distro-specific thing that does such things of course, but we at the upstream are unaware of even that.

**Comment by gunchleoc** [comment]
Indeed, we have tracked it down to https://build.opensuse.org/package/view_file/openSUSE:Factory/rpm/remove-translations.diff?expand=1 now. Sorry for the noise.
