### ISSUE TITLE
RFE: add a digest on the compressed payload content

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#163]
There should be a way to verify the payload before trying to uncompress, and more importantly, unpack it:
- We have digests on the contents of individual files, but detecting corruption in middle of installation, after all sorts of scripts might have already run, is no good at all
- Compresssion libraries have vulnerabilities of their own
- The RPMv3 digest covering the payload is the obsolete MD5, and furthermore it covers the header and the payload, but we want a digest on the payload only. This way it can be included in the main header which in turn can be signed, so the digest is protected.

The main obstacle is that the payload comes after the header during build, so it's necessary to calculate a placeholder header and rewrite with the actual digest value after writing down the payload, much like is done with signature header currently. The digest algorithm should be configurable, but default to something relatively strong, SHA256 perhaps. 

It has also been suggested that this should be implemented as multiple intermediate digest "snapshots" to avoid having to check everything at once and to allow early exit on corrupted content. It would no doubt be beneficial, the challenge is finding a rasonable tradeoff between header size and the snapshot frequency, considering the payload can be anything from a few kilobytes to tens of gigabytes.

Verification of the data is another story with its own set of problems, but lets not go there yet.

**Comment by pmatilai** [comment]
Thinking about it a bit more, there are many other challenges with the multiple intermediate digest snapshots: the compression stream is created on file-by-file basis which isn't well suited for this purpose, as one file might be just a few bytes and the next one gigabytes, we'd presumably want equally sized chunks.

Maybe best to initially punt the multiple snapshots idea but leave room for future expansion: make the digest tag a string array, and define the contents as one or more digest snapshots where the last one covers the entire payload. Or something like that.

**Comment by pmatilai** [comment]
Initial implementation in commit 91aa0786cf3b2e34de01c586427952de6d0d9b40.

**Comment by cgwalters** [comment]
In practice though, people shouldn't be using raw `rpm` to install RPMs.  They should (and 90% of the time are) using a higher level system like zypper, yum, or rpm-ostree.  

These systems all consume "rpm-md/yum" metadata, which obviously today has a checksum over the content, which can be verified without opening the RPM.

I know they're not the same - having a checksum just over the content as opposed to header+content should (AIUI) allow us to GPG sign without invalidating the content checksum (right?).

But it's surprising to me that we'd do something here without (apparently) considering how it interacts with rpm-md.

**Comment by pmatilai** [comment]
What on earth does rpm-md have to do with this? It exists on an entirely different level, and has checksums on the entire package file, at the time of repository generation. Files can get corrupted and truncated in transit from rpmbuild to a repository. That has happened in Fedora repos, people were not so happy when a malformed Thunderbird package found its way through all the alleged signature checking etc.

**Comment by cgwalters** [comment]
Okay, but that'd also be caught by MD5, right?  So...do we expect every package system to verify *both* the rpm-md checksum and this one?  Running SHA256 or whatever *is* pretty cheap, I know.

Perhaps enough people rely on "untrusted rpm-md fetched over http + GPG signed RPMs" that we have to fix this.  But I think greater security comes from pushing everyone to do [cert pinned rpm-md](https://pagure.io/fedora-infrastructure/issue/5372).

**Comment by pmatilai** [comment]
What MD5? Besides being hopelessly outdated and vulnerable, nothing besides rpm -K actually verifies it. Yum/dnf certainly does not. And it lives in the signature header so you can just modify it at will.

Repository formats are just not relevant here, at all, no matter which way they're signed.
