### ISSUE TITLE
Segmentation fault 11 macOS

### ISSUE THREAD

**Issue by YentlFrickx** [rpm-software-management/rpm#1637]
When using the latest version of rpm (4.16.2) installed via brew (`brew install rpm`) we get a Segmentation fault: 11 error when executing `rpmbuild -bb --buildroot /rootfolder specfile` . In the past this was no issue (rpm version 4.15.1 gave no error with the exact same spec file).

**Comment by DemiMarie** [comment]
Can you post the spec file and a backtrace?  Also, if it is not too inconvenient, would you mind rebuilding with Address Sanitizer and Undefined Behavior Sanitizer, then re-running the build?

**Comment by YentlFrickx** [comment]
Hi @DemiMarie, thanks for the reply, this is already the spec file, I removed all files since there are a lot and they pollute the spec file. I don't really have a backtrace, the only response on the command is 'Segmentation fault: 11'. As for your other questions, how should we approach rebuilding with those tools?

```
%define   _topdir /project/project/temp

Name: aem-provision
Version: 89.0.0.beta
Release: 1
Summary: No summary
License: MIT
BuildArch: x86_64
Vendor: Amplexor
Group: Development/Tools
Requires: aem-toolbox

%description
No description

%pre
set -euo pipefail
mkdir -p /var/log/deploy
export LOG_FILE=/dev/stdout
export LOG_LEVEL=INFO
#!/usr/bin/env bash

set +u
source /etc/profile
set -ueo pipefail

if [ "${PILLAR}" == LOCAL ] || [ "${HOSTNAME}" == hostname ]; then
  rm -rf /opt/aem/provision
fi


%post
set -euo pipefail
mkdir -p /var/log/deploy
export LOG_FILE=/dev/stdout
export LOG_LEVEL=INFO
#!/usr/bin/env bash

set +u
source /etc/profile
set -ueo pipefail

source /opt/aem/provision/lib/bootstrap.sh

# shellcheck source=/opt/aem-toolbox/lib/aem.sh
source "${LIB_DIR}/aem.sh"

CHECK_ROOT

rm -rf /opt/aem/tmp/*.dat
rm -rf /opt/aem/tmp/fonts.*
rm -rf /opt/aem/tmp/*.hprof
rm -f /opt/aem/aem_*.dev.kbc.be.jks
rm -f /opt/aem/*.log
rm -rf /opt/aem/crx-quickstart/archived-versions

chmod -v u+x "${PROVISION_BASEDIR}"/bin/*


%files

```

**Comment by pmatilai** [comment]
Tracing segfaults doesn't need building with special libraries. Just run under gdb or valgrind.

**Comment by DemiMarie** [comment]
LLDB (which XCode uses) will also work.

**Comment by ffesti** [comment]
OK, without more details there is nothing we can do. Closing.
Feel free to reopen, with more details attached.
