### ISSUE TITLE
Upgrade to work with lua 5.3 without compat mode

### ISSUE THREAD

**Issue by daurnimator** [rpm-software-management/rpm#166]
rpm currently only works with lua 5.3 if lua is compiled/included in compatibility mode.

The code has taken the odd approach of reimplementing deprecated functions in terms of new functions, rather than updating the code to use the new functions (they were deprecated for a reason!), and potentially having backwards compat macros (such as provided by https://github.com/keplerproject/lua-compat-5.3) to still work with 5.1

**Comment by daurnimator** [comment]
Did some work on a branch over here: https://github.com/rpm-software-management/rpm/compare/master...daurnimator:lua5.3-no-compat

**Comment by Conan-Kudo** [comment]
@daurnimator I'd prefer to see a PR for this to make it easier to review (even if it's marked as "WIP" for now).
