### ISSUE TITLE
Plugin library symbols are not loaded at first

### ISSUE THREAD

**Issue by benierc** [rpm-software-management/rpm#1663]
dlopen load plugins LIBRARY with RTLD_LAZY flag                          
it means the symbols are loaded when references are executed             
so it causes issue when some references are the same than in system      
                                                                         
append RTLD_BINDDEEP allows to first load symbols from the plugin library

e.g. i have a function named file_reset into my plugin and it is the reference file_reset of libmagic that is loaded

**Comment by pmatilai** [comment]
With the exception of `foo_hooks`  needed to initialize the plugin, all symbols in plugins should be static. Fix that and the problem will go away.
