### ISSUE TITLE
Is there a way to dynamically evaluate macro?

### ISSUE THREAD

**Issue by jpalus** [rpm-software-management/rpm#1687]
What I'd like to achieve is to access `%buildsubdir` in `%prep` after `%setup` was called. It appears that RPM first parses and evaluates all macros in `%prep` and only then executes `%setup` which pushes `%buildsubdir`. So my question is there any way to defer macro expansion or is there some dynamic macro evaluation which would enable accessing `%buildsubdir` in `%prep`?

I'm aware `$PWD` is `%buildsubdir` after `%setup` however the goal is to create global macro which works in every spec irrespective of current working directory.

**Comment by ffesti** [comment]
Yes %setup is only executed after all macros have been expanded. So there is not really a way to do that and relying on $PWD is your best option.
