### ISSUE TITLE
Does "rpmdb --verifydb" can completely replace "db_ verify"?

### ISSUE THREAD

**Issue by gaoyi1988** [rpm-software-management/rpm#1695]
I have changed the db from bdb to ndb, and I need a tool to verify the db files. Does "rpmdb --verifydb" can completely replace "db_ verify"? Or I can verify the db though other method?

I find that "rpmdb --verifydb" just verify Packages.db, are there any plans to support Index.db? Or Index.db will not be destroied?

**Comment by pmatilai** [comment]
As per it's name, Index.db is just indexes that can always be recreated from Packages.db so its not particularly vital data. Directly using the `db_*` tools is discouraged even with BDB, those should be only the last resort if everything else fails, `rpmdb --verifydb` is the right thing to use, but in its existing form its of fairly little value.
