### ISSUE TITLE
RFE: Use `%_platform_multiplier'`

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/rpm#1700]
Mock now use and defines `%_platform_multiplier'`. The meaning is that if some platform (e.g. emulated using QEMU) is slower, then this macro defines the factor of slowiness. Right now, Mock sets it to 10 when the build is run in emulated QEMU, but it can be fine-tuned by the admin.
More details can be found in:
  https://github.com/rpm-software-management/mock/pull/730
  https://github.com/rpm-software-management/mock/issues/697

There is a UX issue that the use of this macro is a bit tricky and e.g. timeout has to be written like

    60*%{?_platform_multiplier}%{!?_platform_multiplier:1}

It would be nice if rpm itself can define macro/function `%platform_timeout` with the definition above. I.e. it returns X when `%_platform_multiplier` is not defined and X*`%_platform_multiplier`.

**Comment by pmatilai** [comment]
I think it'd be weird and cumbersome for rpm to define a macro that is only used by mock. 

Ship the definition with mock itself, ie drop a macros.mock file in /usr/lib/rpm/macros.d?

**Comment by xsuchy** [comment]
The idea is that people can use something like:

```
%check
timeout %platform_timeout 60 somescript.sh
```

which would basically expand to

```
%check
timeout 60 somescript.sh
```

on most platforms. But if `%_platform_multiplier` was defined then the timeout will be increased. 

The benefits of having this in rpm itself are that users can expect the presence **always**.  They do not need to fiddle with `%?:`... Just sometimes the function can alter the value.

**Comment by mikhailnov** [comment]
You can define macros via mock config

**Comment by xsuchy** [comment]
> You can define macros via mock config

How does this help to set ecosystem-wide macro?

I am a Mock contributor (and ex-leader). I defined the `%_platform_multiplier` macro in Mock. But now, users have to use `60*%{?_platform_multiplier}%{!?_platform_multiplier:1}` which is clumsy. Hard to use for newbies. I wanted to have some convenient macro across the whole rpm ecosystem, which will utilize `%_platform_multiplier` if it exists. 

@pmatilai if you are against it, then just close this, and I will try to add it to `fedora-srpm-macros`. But I will be sad as Fedora diverges a bit from other rpm-based distros.

**Comment by mikhailnov** [comment]
> How does this help to set ecosystem-wide macro?

I meant setting macros that rpm-build will use inside mock.
Ok, now I see your point.

**Comment by pmatilai** [comment]
I can kinda see your point, but this is just too arbitrary a thing to be added to rpm as such.

There's a more generic use-case behind this: default value for a non-existent macro. Finding a syntax that would be sufficiently short to be useful might be hard though.

**Comment by pmatilai** [comment]
FYI, I created a new ticket for the generic case: #1756
