### ISSUE TITLE
OrderWithRequires deps flags are stripped

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1703]
I noticed that RPMTAG_ORDERNAME is missing in rpmSanitizeDSFlags(), so all flags like `pre` are stripped. Is this interntional?

**Comment by pmatilai** [comment]
I'd think not. @ffesti?

**Comment by ffesti** [comment]
Nope. This is clearly an oversight. Too many places to touch to add a new type of dependency.

Interestingly enough weak dependencies are not stripped although we currently do not support flags for them.
