### ISSUE TITLE
check-rpaths-worker script increases build time considerably for some packages

### ISSUE THREAD

**Issue by stratakis** [rpm-software-management/rpm#1713]
Hello,

I've recently implemented this change for Fedora: https://fedoraproject.org/wiki/Changes/Broken_RPATH_will_fail_rpmbuild

Basically the check-rpaths-worker is running as a buildroot policy script as of F35. Unfortunately after the implementation of the change, some packages saw an increase in their build time, such as the kernel, for which the build time increased by ~14 mins, or glibc.

Relevant mailing list discussion: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/MN7HHEPJZ7RQ6XU6BOHSD2NPLTLSSQQJ/

**Comment by ffesti** [comment]
Yeah, the script runs `readelf` for every regular file in the `$RPM_BUILD_ROOT` - twice and in series. That's something we painstakingly avoided for all the other brp scripts affecting the kernel (and others).
I can switch this over for parallel processing, too. But weeding out the files that need to be looked at would help even more. So some more precise attributed for the `find` command in `check-rpaths` would help. Is it enough to look at executables and .so files?

**Comment by fweimer-rh** [comment]
Yes, `ET_REL` files can be skipped. If you are changing the file anyway, please also add `-W` to the `readelf` invocations, so that the output does not get truncated.

**Comment by ffesti** [comment]
Not quite sure how I detect those. Also we already executed `readelf` by that point, right?

Is there a way of skipping files based on file attributes I can pass to `find` like file name, executable bit etc?

**Comment by ffesti** [comment]
This is fixed by  #1714. Closing.
