### ISSUE TITLE
rpm-4.17.0beta1 fails to build because pandoc is unavailable

### ISSUE THREAD

**Issue by soig** [rpm-software-management/rpm#1729]
https://rpm.org/wiki/Releases/4.17.0

Humm it fails to build:
(…)
make[3]: Leaving directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
make[3]: Entering directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
no -s -t man ./ja/rpmbuild.8.md -o ja/rpmbuild.8
make[3]: no: No such file or directory
make[3]: *** [Makefile:869: ja/rpmbuild.8] Error 127
make[3]: Leaving directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
make[3]: Entering directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
no -s -t man ./ja/rpmgraph.8.md -o ja/rpmgraph.8
make[3]: no: No such file or directory
make[3]: *** [Makefile:869: ja/rpmgraph.8] Error 127
make[3]: Leaving directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
make[3]: Entering directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
no -s -t man ./ko/rpm.8.md -o ko/rpm.8
make[3]: no: No such file or directory
make[3]: *** [Makefile:869: ko/rpm.8] Error 127
make[3]: Leaving directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
make[3]: Entering directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
no -s -t man ./ko/rpm2cpio.8.md -o ko/rpm2cpio.8
make[3]: no: No such file or directory
make[3]: *** [Makefile:869: ko/rpm2cpio.8] Error 127
make[3]: Leaving directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
make[3]: Entering directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
no -s -t man ./gendiff.1.md -o gendiff.1
make[3]: no: No such file or directory
make[3]: *** [Makefile:869: gendiff.1] Error 127
make[3]: Leaving directory '/ff/rpm/BUILD/rpm-4.17.0-beta1/docs/man'
make[2]: *** [Makefile:495: all-recursive] Error 1
error: failed!
make[1]: *** [Makefile:1300: all-recursive] Error 1
make: *** [Makefile:746: all] Error 2
error: Bad exit status from /ff/rpm/BUILDROOT/rpm-tmp.QkTTXA (%build)

Probably due to:
"checking for pandoc... no"
(undetected new dep)

Many distros do not have pandoc available…
(because of the GHC hell/nightmare deps)

So I would blame:
https://github.com/rpm-software-management/rpm/commit/937785005d8ca34805cf6a0eb58ad97691af11d6

**Comment by soig** [comment]
Having to depends on Haskell in order to build rpm is big bullet to swallow !

**Comment by ffesti** [comment]
> Having to depends on Haskell in order to build rpm is big bullet to swallow !
This is not intentional. While pandoc is needed to create the release tarball (or make changes to the man pages) requiring pandoc for building from the release tarball is not intended. The man pages should be shipped pre-build. Looks like this is not quite working though.

**Comment by soig** [comment]
Those fixes should be backported into rpm-4.17.x branch !
