### ISSUE TITLE
Please provide source package name to dependency generators

### ISSUE THREAD

**Issue by fweimer-rh** [rpm-software-management/rpm#1736]
As far as I can see, `rpmfcApply` in `build/rpmfc.c` overwrites `%name` with the subpackage name. It would be nice to be able to pass the current source package name to a dependency generator as an argument. This will allow the dependency generator not to run for certain source packages (e.g., for the package that provides the generator but would otherwise trigger it during its own package build).

**Comment by mikhailnov** [comment]
Wow! I thought that name of source package is passed to generators. If the name of subpackage is passed, it is easier to make generators in case that I wanted to.

**Comment by pmatilai** [comment]
You can get the main/source package information from uppercase macros, eg %{NAME}, %{VERSION} etc.
