### ISSUE TITLE
%epoch is defined globally if is set only in one subpackage

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1745]
I am building RPMs from https://abf.io/mikhailnov/kernel-5.4/tree/cd156877bc

The only subpackage that has Epoch is `kernel-headers`:
[1] https://abf.io/mikhailnov/kernel-5.4/blob/cd156877bc/kernel.spec#lc-776

The problem is that it makes ther macro `%epoch` be defined globally.

Some subpackages with kernel modules are generated here:
[2] https://abf.io/mikhailnov/kernel-5.4/blob/cd156877bc/macros.ksobirator#lc-30
[3] https://abf.io/mikhailnov/kernel-5.4/blob/cd156877bc/kernel.spec#lc-840

Macro is defined in [2] and is used in [3]. Macro `%{EVRD}` is used in [2]. It is defined in ROSA and OpenMandriva in `/usr/lib/rpm/openmandriva/macros` as the following:
`%EVRD %{?epoch:%{epoch}:}%{?version:%{version}}%{?release:-%{release}}`

And here the resulting subpackages are not intallable:

```
DEBUG util.py:621:   Problem 1: conflicting requests
DEBUG util.py:621:    - nothing provides kernel-5.4-generic(x86-64) = 1:5.4.130-1 needed by kernel-module-vboxsf-5.4-generic-5.4.130-1.x86_64
DEBUG util.py:621:   Problem 2: conflicting requests
```

It is because it should have required "kernel-5.4-generic(x86-64) = 5.4.130-1" without Epoch.

So, the macro `%epoch` is leaked from a subpackage to the global world.

**Comment by mikhailnov** [comment]
Minimal reproduction, `rpm-1745.spec`:

```
Name: rpm-1745
Summary: %name
License: no
Version: 0
Release: 0
Group: System/Base

%description
%name

%files
/epoch.txt

#--------------
%package sub1
Summary: sub1
Group: System/Base
Epoch: 2
%description sub1
sub1
%files sub1
#--------------

%prep
%build
%install
echo %{epoch} > %{buildroot}/epoch.txt
```

Build packages: `rpmbuild -bb rpm-1745.spec`

Check epochs:
```
$ rpm -qp --qf '%{epoch}\n' rpm-1745-0-0-rosa2019.1.x86_64.rpm rpm-1745-sub1-0-0-rosa2019.1.x86_64.rpm
(none)
2
```
They are correct. But "2" was written to "epoch.txt".

**Comment by mikhailnov** [comment]
Is it a bug or not?

**Comment by mlschroe** [comment]
I don't think this is a bug, it behaves exactly like `%{version}`. You'll always get the values of the last definition for the macros, i.e. from the last subpackage.

If you want the definitions of the main package, you're supposed to uppercase the macro names, e.g. `%{EPOCH}` and `%{VERSION}`.

**Comment by pmatilai** [comment]
As per above, this is expected behavior. Doesn't necessarily mean it's *sensible* behavior but there's nothing we can do about it.

**Comment by mikhailnov** [comment]
> I don't think this is a bug, it behaves exactly like `%{version}`. You'll always get the values of the last definition for the macros, i.e. from the last subpackage.
> 
> If you want the definitions of the main package, you're supposed to uppercase the macro names, e.g. `%{EPOCH}` and `%{VERSION}`.

Thanks a lot!
