### ISSUE TITLE
%_docdir is not defined

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1746]
`%_docdir` macro is used multiple times in `macros.in`:

```
%__global_requires_exclude_from		%{?_docdir:%{_docdir}}
%__global_provides_exclude_from		%{?_docdir:%{_docdir}}
```

```
%___build_pre	\
<....>
RPM_DOC_DIR=\"%{_docdir}\"\
```

The problem is that this macro is not defined by default. Some usages of it in `macros.in` assume that it can be not defined, but some assume that is is defined.

Also I do not see differences with `%_defaultdocdir`.

soemthing seems to be wrong here

**Comment by pmatilai** [comment]
It's only defined during spec parse, and Docdir: directive may override it.
