### ISSUE TITLE
RFE: export preamble tags as macros

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1753]
I want to build subpackages `%{name}-build-deps` and put them into a separate repository like -debuginfo subpackages.

Such package would depend from what is BuildRequires in the spec/SRPM. The purpose is to work with build-deps repository using `dnf reqpoquery --whatrerquires` dnf `dnf repoclosure`.

Currently I build such packages with a script: https://abf.io/import/rpm-mk-build-deps/blob/rosa2021.1/rpm-mk-build-deps.sh

I tried to do like `%_debuginfo_template`:

```
%package build-deps
Summary: Build dependencies of %{name}
Group: Development/Debug
AutoReq: 0
AutoProv: 0
Requires: %{buildrequires}
%description build-deps
Build dependencies of %{name}
%files build-deps
```

but macro `%buildrequires` does not exist, so I cannot get BuildRequires from inside the same spec.

**Comment by mikhailnov** [comment]
The same problem is with any other spec preamble tag

**Comment by mikhailnov** [comment]
And I cannot add exporting macros easily like:

```diff
diff --git a/build/parsePreamble.c b/build/parsePreamble.c
index ac3d9159e..1e3c55a1b 100644
--- a/build/parsePreamble.c
+++ b/build/parsePreamble.c
@@ -1048,6 +1048,7 @@ static int findPreambleTag(rpmSpec spec,rpmTagVal * tag,
 	    rpmlog(RPMLOG_WARNING, _("line %d: %s is deprecated: %s\n"),
 			spec->lineNum, p->token, spec->line);
 	}
+	rpmPushMacro(NULL, p->token, NULL, spec->line, RMIL_GLOBAL);
 	break;
     }
     if (p == NULL || p->token == NULL)
```

because:

1. BuildRequires can be formed from multiple preamble lines
2. `spec->line` will be not the value of the tag here

**Comment by pmatilai** [comment]
This is intentional, see commit 7ca03925d88d27266a4f8bec7a35e8c3b1117279

Macros are unsuited to the task, you'd need access to the headers under construction and that's a can of worms I'm not willing to look into.

**Comment by mikhailnov** [comment]
Will it work correctly when BRs are generated by a generator (%generate_buildrequires)? Will the `%buldrequires` macro have a correct value including the results of that generation? I am trying to understand why "Macros are unsuited to the task".
