### ISSUE TITLE
error: Missing build-id in /builddir/build/BUILDROOT/...

### ISSUE THREAD

**Issue by jhdulaney** [rpm-software-management/rpm#177]
When scratch building a source rpm (0) in koji (1), I receive the following error in the build log:

error: Missing build-id in /builddir/build/BUILDROOT/guile-2.1.8-1.fc27.x86_64/usr/lib64/guile/2.2/ccache/language/elisp/spec.go
error: Missing build-id in /builddir/build/BUILDROOT/guile-2.1.8-1.fc27.x86_64/usr/lib64/guile/2.2/ccache/language/elisp/falias.go
error: Missing build-id in /builddir/build/BUILDROOT/guile-2.1.8-1.fc27.x86_64/usr/lib64/guile/2.2/ccache/language/elisp/runtime/function-slot.go

I will attempt to reproduce by rebuilding the same srpm (2).

(0)  https://st.jdulaney.com/guile-2.1.8-1.fc25.src.rpm
(1)  https://kojipkgs.fedoraproject.org//work/tasks/1877/18391877/build.log
(2)  https://koji.fedoraproject.org/koji/taskinfo?taskID=18400786

**Comment by rpm-maint** [comment]
On Wed, 2017-03-15 at 10:10 -0700, John Dulaney wrote:
> When scratch building a source rpm (0) in koji (1), I receive the following error in the build log:
> 
> error: Missing build-id in /builddir/build/BUILDROOT/guile-2.1.8-1.fc27.x86_64/usr/lib64/guile/2.2/ccache/language/elisp/spec.go
> error: Missing build-id in /builddir/build/BUILDROOT/guile-2.1.8-1.fc27.x86_64/usr/lib64/guile/2.2/ccache/language/elisp/falias.go
> error: Missing build-id in /builddir/build/BUILDROOT/guile-2.1.8-1.fc27.x86_64/usr/lib64/guile/2.2/ccache/language/elisp/runtime/function-slot.go
> 
> I will attempt to reproduce by rebuilding the same srpm (2).
> 
> (0)  https://st.jdulaney.com/guile-2.1.8-1.fc25.src.rpm
> (1)  https://kojipkgs.fedoraproject.org//work/tasks/1877/18391877/build.log
> (2)  https://koji.fedoraproject.org/koji/taskinfo?taskID=18400786

Thanks for the report.
I couldn't replicate this with the current fedora guile-2.0.14-1
package. There the .go files are not actual ELF files. So rpm will not
complain about them not having a build-id. If that has changed in with
guile 2.1.8 and the .go files are ELF binaries now and it is intended
that they don't have a build-id then you could work around it by
undefining %_missing_build_ids_terminate_build.

I'll try with the src.rpm you provided.

**Comment by rpm-maint** [comment]
On Wed, 2017-03-15 at 20:50 +0100, Mark Wielaard wrote:
> I couldn't replicate this with the current fedora guile-2.0.14-1
> package. There the .go files are not actual ELF files. So rpm will not
> complain about them not having a build-id. If that has changed in with
> guile 2.1.8 and the .go files are ELF binaries now and it is intended
> that they don't have a build-id then you could work around it by
> undefining %_missing_build_ids_terminate_build.
> 
> I'll try with the src.rpm you provided.

And indeed it seems guile switched to producing ELF files.
But note the following from
https://wingolog.org/archives/2014/01/19/elf-in-guile
        
        Note that although Guile uses ELF on all platforms, we do not
        use platform support for ELF. Guile implements its own linker
        and loader. The advantage of using ELF is not sharing code, but
        sharing ideas. ELF is simply a well-designed object file format.

So rpm is correct to warn that the ELF images don't contain build-ids.
As long as guile doesn't produce them you will need to add something
like the following to your spec file:

        # Guile produces ELF images that are just containers for guile and don't
        # include build-ids. https://wingolog.org/archives/2014/01/19/elf-in-guile
        %undefine _missing_build_ids_terminate_build

That lets me rebuild your new guile srpm.

**Comment by pmatilai** [comment]
Okay so rpm is right to warn and a disabler exists to allow dealing with the special case, I think we can close this.
