### ISSUE TITLE
rpm query directory performance

### ISSUE THREAD

**Issue by enerjazzer** [rpm-software-management/rpm#1770]
I'm seeing a problem with executing "rpm -qf <directory>" (rpm 4.11.3)
When I do strace on that command and watch stat() calls, it shows very different behavior depending on what I'm querying for.

If I do "rpm -qf /opt/pkg/mylib/1.100" it does exactly one stat() on the directory I requested.
If I do "rpm -qf /opt/pkg/mylib/1.100/lib" it calls stat() on ALL directories registered in the rpmdb, no matter if they exist or not. This is a huge problem when you have a lot of packages installed: when the former query takes 0.03s, the latter can take up to 2 seconds.
If I do "rpm -qf /opt/pkg/mylib/1.100/lib/libxxx.so" it calls stat() on all directories registered in the rpmdb matching the path /opt/pkg/mylib/*/lib/libxxx.so, which is of course better than stat()-ing everything installed, but still not ideal.

Is it a known issue?
If it's a known bug, is it fixed in later versions?
Are there any known workarounds for rpm 4.11.3 (as it's a system version so I'm stuck with it in the office)?
Maybe there is a patch that could be applied to 4.11.3 without a full upgrade (so I could convince our admins to apply it)?

**Comment by DemiMarie** [comment]
> Are there any known workarounds for rpm 4.11.3 (as it's a system version so I'm stuck with it in the office)?
> Maybe there is a patch that could be applied to 4.11.3 without a full upgrade (so I could convince our admins to apply it)?

RPM 4.11.3 is horribly insecure, so unless you are using `repo_gpgcheck=1` on all of your repositories you have bigger problems.

**Comment by enerjazzer** [comment]
@DemiMarie I'll leave the gpg configuration to our IT guys (in our firm, we use RPM to distribute internally developed packages and can't download external RPMs, so RPM security is not the highest priority).
This ticket is about the query performance as it really affects my everyday work.

**Comment by ffesti** [comment]
The reason for this behaviour is that RPM checks if the file is available at a different location as a symlink. But I am not 100% sure if all those checks are really necessary but it is quite possible that just one stat call is not sufficient.

**Comment by enerjazzer** [comment]
@ffesti Well, it doesn't do it for other queries... 
What if I have a symlink /opt/pkg/mylibxxx/1.100 -> /opt/pkg/mylib/1.100? But as I said before, RPM does exactly one stat() in this case, it doesn't try to find other possible symlinks.
Also, a symlink can have a different name, e.g. /opt/pkg/mylibxxx/1.100yyy -> /opt/pkg/mylib/1.100.
With this logic, it should scan the whole filesystem every time :)

Frankly, what's the point of having RPMDB if it's going to stat everything? I expected it to only check the RPMDB entries and, maybe, do one stat() if it's really needed (which I doubt, because even if the directory was deleted without proper rpm uninstall it's still registered in the RPMDB and it's enough to give the user the name of the rpm which provided this path, no matter if it exists or not - and this has a use case of restoring that accidentally deleted directory by reinstalling the said rpm).

**Comment by pmatilai** [comment]
Rpm looks up paths starting by the basename, which is why something ending in "lib" will turn up a huge amount of results whereas "1.100" probably doesn't. And then when you apply all the symlink checking etc... it turns out to be a lot of stat()'s. But stat() is cheap, trying to optimize a few away just does not benefit anything at all.

**Comment by enerjazzer** [comment]
@pmatilai Sorry, I have to disagree. It's not that cheap, as I said in the ticket itself:
>  when the former query takes 0.03s, the latter can take up to 2 seconds.

In my company, as everything is distributed as RPM packages, we need to query that a lot during the build, to get the RPM dependencies right. This means that `rpm -qf` can easily be called a hundred times - which means 200 seconds (more than 3 minutes!) is spent on waiting for `rpm -qf` alone on every build! I'm sure you will agree that it's a huge waste of time.
Reducing 2 sec to 0.03s, when it's multiplied by hundred, gives a real benefit.
Please reconsider.

Also, if I requested rpm -qf /opt/pkg/mylib/1.100/lib - what's the point of checking, say, /opt/firefox/lib? 
I didn't request just "**/lib" (in this case I would expect it to scan everything), I was very specific - I'm interested in /opt/pkg/mylib/1.100/lib and nothing else, so why scanning anything else at all?

**Comment by pmatilai** [comment]
Lots of people have gone ZOMG over the stat()'s. That's not where the time is spent, it's spent on database hits and verifying fetched headers and whatnot. BDB performance can degrade badly over time,  --rebuilddb can make a *huge* difference to performance, and also --nosignature --nodigest (just to reduce processing).

As for having to stat around for `lib`, rpm is looking for paths that may be identical to that and also provide the same thing. This is known as fingerprinting, and without that eg /usr merge would not have been possible. 

Finally, nothing, I mean *zero*, is going to be done to rpm 4.11 at this point.

**Comment by enerjazzer** [comment]
Understood.
What about other versions? Is this behavior specific to 4.11 or to all later RPM versions as well?

P.S. We rebuilt the DB immediately when we saw the slowness, showed no difference at all. Running `rpm -qf --nosignature --nodigest` takes exactly same as just `rpm -qf`
