### ISSUE TITLE
Adopt PKCS#11 support for fsverity signatures in rpmsign

### ISSUE THREAD

**Issue by wuyuoss** [rpm-software-management/rpm#1786]
We recently made a change to [Kernel fsverity-utils to "Implement PKCS#11 opaque keys support through OpenSSL pkcs11 engine"](https://git.kernel.org/pub/scm/linux/kernel/git/ebiggers/fsverity-utils.git/commit/?id=66b1d8a276cb3836ac275cb9f3f6517a07462737) and is already committed but not yet the new fsverity-utils new version. The change is meant to allow us to use opaque keys confined in hardware security modules (HSMs) and similar hardware tokens without direct access to the
fsverity signing key material, which will then be used to generate fsverity signatures for RPM files with hardware-backed key.

The change in rpmsign side will be just to add new input arguments, and allow users to use these arguments to load the fsverity signing private key in hardware and generate fsverity signatures.

I have done a local testing to check it will be able to generate the proper fsverity signatures for RPMs and won't affect existing approach for private key (which is direct access to the private key path).

The automatic check will [fail in Semaphore](https://semaphoreci.com/rpm-ecosystem/rpm/branches/pull-request-1779/builds/2) because of the "libfsverity.h" loaded doesn't contain the latest commit we made, any idea how we can deal with it?

**Comment by pmatilai** [comment]
The PR died of old age, presumably this can be closed too then.
