### ISSUE TITLE
[regression?] arg[2] to lua scriptlet became a string instead of number

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1790]
The following scriptlet worked ok in rpm 4.15 and 4.16:

```
%post -p <lua>
if arg[2] >= 2 then 
  vr = posix.stat("/var/run")
<...>
```

But it stopped working in rpm 4.17:
```
lua script failed: [string "%post(filesystem-2.1.9-48.x86_64)"]:2: attempt to compare number with string
```

I am not an expert in lua, but `2` here seems to be an integer, not a string.

I can suspect commit https://github.com/rpm-software-management/rpm/commit/717a3f7ecf0af7c453cd1bcb3f49b5ea4941817e "Pass install scriptlet arguments to Lua as real local arguments", it states that "Lua will automatically convert numbers as necessary so this should not break anything", but seems that it broke something.

I "fixed" the problem by just removing that scriptlet because it is not needed any more (https://abf.io/import/filesystem/commit/5806ae4e0504314bdcd0417be94d4637d76d3eb1) but it looks like an unexpected breakage.

**Comment by pmatilai** [comment]
Ugh, right. Lua converts numeric strings to numbers automatically to do math (eg `"1" + 1`) but not comparison. There are probably (good) reasons for that, but it does mean we'll probably need to do something about this.

**Comment by pmatilai** [comment]
Fixing this is not a simple matter of reverting a patch though, as we threw out the entire internal API that the old code was based on: commit 376fef14a61a9748ce004888fe19445719a5d2d5.

**Comment by mlschroe** [comment]
If you can live with a hack, add something like this to runLuaScript (totally untested):
```
    if (arg1 >= 0 || arg2 >= 0) {
        if (arg1 >= 0 && arg2 >= 0)
            scriptbuf = xstrdup("arg[#arg-1] = tonumber(arg[#arg-1]);");
        rstrscat(&scriptbuf, "arg[#arg] = tonumber(arg[#arg]);", script, NULL);
        script = scriptbuf;
    }
```

**Comment by mikhailnov** [comment]
Thanks!
