### ISSUE TITLE
No way to get rid of duplicated packages of ther same NEVR

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1792]
[user@rosa2019 tmp]$ sudo rpm -e --nodeps -vh gnome-session gnome-session-bin
[sudo] пароль для user: 
ошибка: "gnome-session-bin" specifies multiple packages:
  gnome-session-bin-40.1.1-8.x86_64
  gnome-session-bin-40.1.1-8.x86_64
[user@rosa2019 tmp]$ sudo rpm -e --nodeps -vh gnome-session gnome-session-bin-40.1.1-8.x86_64 gnome-session-bin-40.1.1-8.x86_64
ошибка: "gnome-session-bin-40.1.1-8.x86_64" specifies multiple packages:
  gnome-session-bin-40.1.1-8.x86_64
  gnome-session-bin-40.1.1-8.x86_64
ошибка: "gnome-session-bin-40.1.1-8.x86_64" specifies multiple packages:
  gnome-session-bin-40.1.1-8.x86_64
  gnome-session-bin-40.1.1-8.x86_64

I have duplicated packages of the same NEVR, seems that there is no way to delete them using rpm cli.

**Comment by linux-gcc** [comment]
Usually there is only one nvra package in the rpm database, and now why do you have the same nvra package repeated? @mikhailnov
