### ISSUE TITLE
RFE: Clean up Ruby generated `.gemspec` file in `%clean`

### ISSUE THREAD

**Issue by pvalena** [rpm-software-management/rpm#1799]
Ruby `%setup` unpacks `.gem` file (`SOURCE0`), and also generates `.gemspec` file (from the `.gem` file) which is needed for gem build:
https://src.fedoraproject.org/rpms/rubygem-rails/blob/rawhide/f/rubygem-rails.spec#_37

It's generated in the same folder as the unpacked source (to avoid name collision), but it's never removed in `%clean` section.

Is it possible to remove it as well?

Also discussed here: https://src.fedoraproject.org/rpms/rubygem-contracts/pull-request/1#comment-87699

**Comment by ffesti** [comment]
OK, after a bit of digging: `rpmuncompress` does indeed create a `.rpmspec` file beside the buildSubdir when invoked by `%setup` on an gem file.
For some reason the the buildSubdir is not deleted by default unless you pass `--clean` to `rpmbuild` executing the `RPMBUILD_RMBUILD` action. So one would expect that the `.rpmspec` file is not deleted by default either. One could expect that `--clean` should delete it though - which it currently doesn't.
