### ISSUE TITLE
Tags in the signature header are not sorted

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#181]
This is the hex dump of the createrepo_c Archer-3.4.5-6.x86_64.rpm signature header.

RPMSIGTAG_SHA1 follows RPMSIGTAG_MD5 at offset 0xa0, forcing a sort while loading the signature header.
_
00000060: 8ead e801 0000 0000 0000 0005 0000 0054  ...............T
00000070: 0000 003e 0000 0007 0000 0044 0000 0010  ...>.......D....
00000080: 0000 03e8 0000 0004 0000 0000 0000 0001  ................
00000090: 0000 03ec 0000 0007 0000 0004 0000 0010  ................
000000a0: 0000 010d 0000 0006 0000 0014 0000 0001  ................
000000b0: 0000 03ef 0000 0004 0000 0040 0000 0001  ...........@....
_

**Comment by pmatilai** [comment]
Yes there was a bug in rpm 4.9.1.3 - 4.11.1 that causes the tags to be partially out of order. Already fixed three years ago but existing packages can hardly be helped.

**Comment by n3npq** [comment]
Legacy compatibility well understood: not the first time tags were added out-of-order.

Meanwhile ...

You might want to consider checking whether tags are sorted as a side effect of calling hdrblobVerifyInfo() by comparing tagno's while traversing a region and skipping headerSort if/when tags are already sorted: qsort worst case behavior is on already sorted arrays, and there's already a linear "header sanity check" loop verification.

A check on sort order also helps detect fuzzed headers sooner.

See rpmdb/header_internal.c headerVerifyInfo() for the equivalent "header sanity check" code that detects ordering problems as well as specific tag damage from fuzzing. A single if statement there avoids the flaw above. I will likely extend headerVerifyInfo (as suggested) by adding an argument to avoid headerSort when not needed.
