### ISSUE TITLE
Support glibc-hwcaps in rpm

### ISSUE THREAD

**Issue by romulasry** [rpm-software-management/rpm#1812]
"dancermak
    5 days ago by dancermak | Reply

    This sounds very intriguing! I have a few notes about this:
        you might be interested in this (sadly stalled) upstream PR:
https://github.com/rpm-software-management/rpm/pull/1035 which adds better detection of
the currently running microarchitecture
        once rpm gains the ability to automatically generate subpackages
(https://github.com/rpm-software-management/rpm/pull/1485), this could be completely
automated"
https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/message/5GAPNLIJGNCBZCP2L2CDY6I6TZLZD6EB/

Also see: x86_64-v2 in Fedora
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/5EJ7T27EBBSJKMDY2MKCKR5ZIRBCKPJ6/

**Comment by pmatilai** [comment]
The more relevant link would seem to be https://hackweek.opensuse.org/all/projects/support-glibc-hwcaps-and-micro-architecture-package-generation
