### ISSUE TITLE
Adding/moving RPMTAG_PUBKEYS to the signature header

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#182]
RPM package files can include public keys in the metadata header.

So in principle, a package can include the public key used to sign a package and verify the package signature when reading package headers. The RPMTAG_PUBKEYS array is also within the signed immutable region and cannot be altered in signed package metadata.

However, there is a chicken <-> egg problem extracting RPMTAG_PUBKEYS from the not-yet-verified metadata header blob in order to verify the header blob before loading.

Adding/moving RPMTAG_PUBKEYS to the signature header would permit a stronger (than RPMSIGTAG_SHA1) check on the header-only (or header+payload if you insist) metadata blob before loading the metadata header.

(aside)
Verifying the metadata header signature before loading also avoids the need for explicitly implementing stronger digests like RPMSIGTAG_SHA256: the signature itself determines the metadata digest, and -- unlike an additional digest included in the signature header which can be replaced -- is a cryptographically stronger verification.

(aside)
This is mostly a notification of the reason why RPMTAG_PUBKEYS is likely to appear soon in signature headers produced by RPM5 in order to support MANDATORY signature verification.

**Comment by pmatilai** [comment]
You're of course free to do whatever you wish in RPM5 but this is an issue tracker of rpm.org, please limit usage to that purpose. Closing.

**Comment by n3npq** [comment]
The suggestion of moving RPMTAG_PUBKEYS was directed to rpm.org (and you) as a better design for *.rpm packages, particularly if pursuing multiple signatures on multiple plaintext within an RPM package.

*shrug*
