### ISSUE TITLE
RPM does not properly restore the timezone after parsing a changelog date

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1821]
This is a copy of https://bugzilla.redhat.com/show_bug.cgi?id=1881917

We can reproduce this with Python, but I think that any program that uses RPM as a library and does timezone stuff would be impacted.

 1. Upon interpreter or datetime initialization, Python calls `tzset()`
 2. When parsing the changelog, RPM sets the TZ environment variable to UTC and calls `mktime()` (which internally calls `tzset()`)
 3. RPM resets the TZ environment variable to original, but does **not call `tzset()`**
 4. Python assumes the timezone is UTC until and unless `tzset()` is called (e.g. via `mktime()`)

I believe that rpm should call `tzset()` after resetting the TZ environment variable after this code:

https://github.com/rpm-software-management/rpm/blob/4a82a683410918f17c14bb979e75330779664099/build/parseChangelog.c#L173-L178

Reproducer in Python. Have a valid/parseable spec file with changelog ready, e.g.:

```
Name:    foo
Version: 0
Release: 0
License: ...
Summary: ...

%description
...

%changelog
* Fri Nov 05 2021 Foo Bar <foo@bar.com> - 0-0
- Meh
```

Set the TZ variable to a timezone that you can easily distinguish from UTC, e.g. `Pacific/Honolulu`:

```shell
$ TZ=Pacific/Honolulu python3
```

```pycon
>>> import rpm, time, datetime

>>> datetime.datetime.now()  # this returns time in Honolulu
datetime.datetime(2021, 11, 5, 3, 18, 6, 241575)

>>> spec = rpm.spec("foo.spec")  # parse a specfile

>>> datetime.datetime.now()  # this returns time in UTC
datetime.datetime(2021, 11, 5, 13, 18, 23, 105545)

>>> time.mktime(datetime.datetime.now().timetuple())  # calls tzset() interanlly
1636154321.0
>>> datetime.datetime.now()  # this returns time in Honolulu
datetime.datetime(2021, 11, 5, 3, 18, 44, 193766)
```

**Comment by DemiMarie** [comment]
RPM should not be changing the timezone at all.

**Comment by hroncok** [comment]
> RPM should not be changing the timezone at all.

That's well beyond the scope of this bug.  I think we can add the missing `tzset()` call to fix this bug and any further "don't change the timezone" thing can happen later.

**Comment by pmatilai** [comment]
(doh, got the timezone bugs mixed up, RhBug 1715412 is something different so sorry about the noise)

**Comment by hroncok** [comment]
Thanks.
