### ISSUE TITLE
Reserving space in the signature header

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#183]
The signature header contains (optional) information to verify package integrity.

So new tags are added when packages are signed, and a new signature header is created and inserted into a *.rpm package file.

However, the insertion forces a rewrite of the metadata header and payload, which for a distribution signing event, can rewrite a terabyte of information.

Another flaw with a variable sized signature header is that the metadata header and payload are not located at a constant offset, preventing, say, HTTP byte ranges from directly reading the header metadata blob.

One simple solution is to add a "free space" tag to the signature header to reserve space for a signature (or other data) to be added later. This would permit the new signature header to be rewritten in-place with an adjusted "free space" tag instead of rewriting entire packages when signing.

I will have a patch to add a "free space" tag to a signature header for rpm.org soon.

**Comment by pmatilai** [comment]
We've had that for almost three years now so don't bother.

**Comment by n3npq** [comment]
My bad for not noticing.

Good that padding has been added by adding (apparently) 0x1000 to the data size:
`00000060: 8ead e801 0000 0000 0000 0006 0000 1074  ...............t`

Adding a "free space" tag (as @rpm5.org) provides an indication that the signature header is padded.

Meanwhile, the metadata header is not aligned on (say) a 0x1000 offset from beginning of file
`
00001120: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00001130: 0000 0000 0000 003e 0000 0007 ffff ffa0  .......>........
00001140: 0000 0010 0000 0000 8ead e801 0000 0000  ................
00001150: 0000 0039 0000 437e 0000 003f 0000 0007  ...9..C~...?....
00001160: 0000 436e 0000 0010 0000 0064 0000 0008  ..Cn.......d....
`

Conventionally using a known offset would make mmap and HTTP byte ranges easier to use, and
its a bit easier to remember 4096 (or 0x1000) than it is to remember 4424 (ox 0x1148).

But having some constant offset is better than rewriting rpm package files.

(aside)
Adding padding between the metadata header and the payload might also be attempted to align the payload on a page boundary might be useful too.

**Comment by n3npq** [comment]
Ah, you have added RPMSIGTAG_RESERVEDSPACE already which I was not expecting.

The (minor but annoying problems) with the assignment to 1008 is that RPMSIGTAG_RESERVEDSPACE collides with RPMTAG_INSTALLTIME, and will not sort correctly to the end of an immutable region data section as a "free space" tag through headerReload-like operations if any other RPMSIGTAG_FOO is defined. Meanwhile -- because of the tagno assignment collisions between signature and metadata headers -- its rather unlikely that any other RPMSIGTAG_FOO assignments will ever be needed.

The functionally equivalent RPMTAG_SIGPADDING was assigned 0x3fffffff for uniqueness and to permit assigned metadata tags (e.g. RPMTAG_PUBKEYS) to be more easily moved between signature and metadata headers without explicit remapping.
