### ISSUE TITLE
Rpmhook subsystem use cases

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1832]
Sorry if I'm dense, but does anybody use that rpmhook system? I don't see any references to it and google also didn't help.

**Comment by pmatilai** [comment]
Not that I know of. It's an interesting looking thing though, to the point that I haven't wanted to delete it despite not finding a problem it would actually solve in all these years. Not many people know of its existence in the first place, welcome to the club :grin:

**Comment by pmatilai** [comment]
FWIW, as far as I know the hook subsystem was inspired by something similar in apt-rpm (also in Lua, also by Gustavo Niemeyer): https://apt-rpm.org/scripting.shtml

That was a powerful feature of apt-rpm, but on rpm itself this never got off the ground - as you probably noticed there are no slots defined anywhere in rpm, and without such slots it's useless. 
We did recently throw around an idea of Lua plugins which could probably utilize the rpmhook code.

**Comment by mlschroe** [comment]
Thanks for the info!
