### ISSUE TITLE
How rpmbuild can pick python3 instead of python2

### ISSUE THREAD

**Issue by alpana17** [rpm-software-management/rpm#1835]
I am using rpmbuild on Amazon Linux 2 ARM. It is picking python 2 by default.
How can I make it use python3

**Comment by alpana17** [comment]
getting error:
![image](https://user-images.githubusercontent.com/8611615/142342851-2e46e6ee-536f-421a-a1c1-dd26febdb034.png)

**Comment by ffesti** [comment]
I am sorry but I can't figure out how this error is related to PYthon2 vs Python 3. This is more of a Amazon Linux 2 question thatn an rpmbuild question. In general packages decide what other software they build against. Typically by adding `BuildRequires:` lines in the spec file. Changing between major Python versions is probably not a trivial operation.
But this is more of a packaging/distribution question. Rpmbuild does not pick the Python version used.
