### ISSUE TITLE
rpmbuild for aarch64

### ISSUE THREAD

**Issue by alpana17** [rpm-software-management/rpm#1836]
Please share some doc for rpmbuild for aarch64

**Comment by ffesti** [comment]
Sorry, this is a ticket system an not a help forum. If you have question feel free to ask on the IRC channel or the rpm-list@lists.rpm.org mailing list. If you are using rpm on or for a specific distribution their packager documentation and communication channels may be even more helpful. Even if you are interested in aarch64 in general the large distributions like Fedora or OpenSuse may offer helpful information.
