### ISSUE TITLE
check UID_0_USER before we use it.

### ISSUE THREAD

**Issue by Geass-LL** [rpm-software-management/rpm#1838]
Now, rpm set this macro by scaning `/etc/passwd`. But if `/etc/passwd` doesn't exist, UID_0_USER will be set to "".

We encountered this problem when we build our rpm packages on obs, and found Users and Groups of many files (especially those no %attr set in spec file) are not set. After some diging, we can reproduce this problem by removing `/etc/passwd`.

So, maybe we should check UID_0_USER before we use it. i.e. If it's `\0`, we fail or set it to `root` by default.

**Comment by Geass-LL** [comment]
We added `BuildRequires: setup` in rpm.spec to avoid this problem, but maybe it's not the perfect solution.

**Comment by pmatilai** [comment]
Uh. One would think /etc/passwd existence would be guaranteed on a working system. 
Of course, containers and the like are pushing the boundaries in funny directions.
