### ISSUE TITLE
Q: RPMTAG_PAYLOADDIGEST: compute before or after compression?

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#184]
The recently added RPMTAG_PAYLOADDIGEST computes a digest on the compressed payload.

Perhaps now is the time to change the plaintext used to be the uncompressed rather than the compressed archive payload?

The benefit of the digest on the uncompressed archive is that the digest becomes immune to the compression type and format, and it might become possible to change the compression on binary
packages without rebuilding.

Another benefit is that PAYLOADDIGEST can be verified after installation by reconstructing the (usually cpio archive) to verify the payload digest. While PAYLOADDIGEST can also be verified by reconstructing the compressed payload archive, there are always timestamps and implementation changes in external libraries that can cause false failures. A digest on the uncompressed archive would be immune to compression implementation changes.

Now is the time to consider before PAYLOADDIGEST has "legacy compatibility" issues.

(aside)
It also would not be too difficult to change rpmio to configurably compute the digest on either (or even both) uncompressed or compressed plaintext by duplicating the digest computation on an FD_t to handle 2 bits of flags on the pre/post I/O buffers.

**Comment by n3npq** [comment]
(answering my own question)

Short answer: digesting compressed payload instead of compressing the digested payload is expedient.

Long answer: RPM goes to some lengths to preserve streaming-without-peeking-at-magic for *.rpm packages.

The usual RPM approach is/was to add/save tags in the metadata header to determine choices like format/signature/digest/compression algorithm (and parameters) into the metadata header. So doing a digest on the compressed payload permits digest/compression to be more easily setup before examining magic in the plaintext blob for RPM.

There are  consequences for other applications that wish to manipulate the rpm file format that do not use the upper layers of the RPM api where the choices can be buried. The consequences  are added application complexity, with a continual application churn to handle Newer! Better! Bestest! features like RPMTAG_PAYLOAD verification, and a need to pretend "legacy compatibility" with disablers while waiting for application implementations.

The ripple effect of a change like RPMTAG_PAYLOADDIGEST (or rpmarchive/tar payloads, or ECC signatures) throughout the rpm tool chain takes years, and one (at least me ;-) wonders whether the work is even useful if it takes years to achieve widely deployed implementations.

(aside)
I think a better approach going forward in RPM will be to use certificates/signatures (which buries the choices of signature/digest algorithm in "standard" ways), and to add API's to select one-of-N choices (like archive/compression format) lazily using magic in the objects, rather than adding explicit metadata tags.

**Comment by pmatilai** [comment]
This is an issue tracker, not a support forum. Closing.
