### ISSUE TITLE
builtin_macro vs load

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1864]
If I am not mistaken, the `?` in `%{?load:...}` builtin macro is not supported since rpm 4.17, but the manual still claims it works:

https://github.com/rpm-software-management/rpm/blob/3d46bc95c5ebd61330921f131af51fa4b88f2512/docs/manual/macros.md#L157-L164

This should be probably fixed.

Nevertheless, given that it seems the `?` is supported for other builtins, I don't understand why this was changed.

**Comment by pmatilai** [comment]
> given that it seems the ? is supported for other builtins

As of >= 4.17 `?` always simply tests whether the macro is defined or not, and builtins are in no way special there. I thought I'd blocked all the attempts to document the special syntaxes but apparently something slipped past. Will fix, thanks for reporting.

**Comment by voxik** [comment]
But the `%{?load:foo}` completely fails with RPM 4.17, so is it exception? That is part of the question, otherwise I'd submitted PR removing the exception documentation myself.

**Comment by voxik** [comment]
Adding `?` to [this](https://src.fedoraproject.org/rpms/ruby/blob/5d3688479ab299cbd5657f9a503463a04d963d65/f/ruby.spec#_112) line results in:

~~~
$ fedpkg --release f36 srpm
error: line 112: Unknown tag: /home/vondruch/fedora-scm/own/ruby/macros.ruby

Could not execute srpm: Error running rpmspec on "/home/vondruch/fedora-scm/own/ruby/ruby.spec", return code 1
~~~

Removing the argument, it fails with `%load: argument expected`

**Comment by voxik** [comment]
So probably this is the right form:

~~~
%{?load:%{load:%{SOURCE4}}}
~~~

But then I am not sure if it works with older RPM :see_no_evil:

**Comment by pmatilai** [comment]
> But the %{?load:foo} completely fails with RPM 4.17, so is it exception?

No, it just behaves as all the macros: since load is defined, this expands to "foo".

> %{?load:%{load:%{SOURCE4}}}

Not sure what you're trying to achieve with that, but it's unlikely to do what you want and certainly not the same as the old if-the-argument-file-exists logic. See https://github.com/rpm-software-management/rpm/issues/1669
