### ISSUE TITLE
The behavior of `%{?builtin_macro:foo}` is unclear from documentation

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1866]
Based on #1864, I'd like the documentation to be clarified what does the `?` do with builtin macros. The documentation currently says:

> both macro “%{?builtin_macro:value}” and its negative version “%{?!builtin_macro:value}” are expanded exactly like the macro without exclamation mark and question mark “%{builtin_macro:value}”

Given how the other macros work, I'd expect that adding the `?` would just soften the behavior, so there would not be failure if the built in macro is not available. Or IOW, the behavior of `%{?builtin_macro:value} == %{builtin_macro:value}`. But it does something different. So lets try it on some random spec and add there the following line:

~~~
%{exists:%{SOURCE4}}
~~~

The `fedpkg srpm` fails with following error:

~~~
error: line 112: Unknown tag: 1
~~~

Ok, so the macro expands to `1`, so the `SOURCE4` file exists. So far so good.

Now lets try the question mark:

~~~
error: line 112: Unknown tag: /home/vondruch/fedora-scm/own/ruby/macros.ruby
~~~

Hm, so it expands the `SOURCE4` now, but it does not tell anything about functionality. So is the following the correct way to ensure the `exists` does not fail even when not available?

~~~
%{?exists:%{exists:%{SOURCE4}}}
~~~

This results in `error: line 112: Unknown tag: 1` so pretty similar to the initial version.

Nevertheless, I in any way, am not able to decipher this behavior from the initial description. In my opinion, the original descriptions should be modified to following:

~~~
The macro “%{?builtin_macro:value}” is expanded into "value" when the `builtin_macro` is available/implemented.
~~~

And I am quite unsure what is the result of `%{?!builtin_macro:value}`. For available builtins, this is probably no-op.

**Comment by voxik** [comment]
I still suspect there might be bug due to ternary operator as I already mentioned here: https://github.com/rpm-software-management/rpm/issues/1669#issuecomment-839174761

**Comment by pmatilai** [comment]
No no, you really need to forget about using ? to perform additional logic. In >= 4.17 it only ever tests whether said macro is defined or not, so there's nothing further to explain wrt builtins. They are now just like any other macros in almost every way.

As I pointed out in #1669, conditional actions can be achieved via expressions in a far more generic way:

%[%{exists:/some/file}?"%{load:/some/file}":""]

**Comment by pmatilai** [comment]
Added this small blurb to clarify it anyway: b45fde60f92670c18c732de26d2c2659050762a6

**Comment by pmatilai** [comment]
> From the beginning, this was not about "file existence" but about the load builtin existence. The problem is that load is not available in RHEL 7 while it is available in RHEL8+.

Well, good to have that cleared because it wasn't clear to me *at all* what this is about. 
So what you're asking for is backwards compatible way of figuring out whether X is supported or not. There isn't, see #717.

Okay, argument checking differs with builtins in the `%{?foo}` test, maybe there's something that can be done about that. You can work around that with using `%{defined foo}` instead, which in case of a builtin "foo" will give you a hint whether you're on >= 4.17 or older but not whether you're on 4.11 or 4.14.

**Comment by pmatilai** [comment]
> In case of the load builtin, the behavior of %{?load:foo} is significantly different to %{load:foo}

And yeah, it is. It's unfortunate that builtin macros used : as an argument separator. In >= 4.17 you can generally use a macro without having to care whether its built-in or user-defined, eg "%load foo" will try to load file "foo" as you'd expect. There are some inconsistencies left in 4.17.0 at least but eliminating the pointless differences between builtins and other macros is the reason for this all.

**Comment by voxik** [comment]
> Well, good to have that cleared because it wasn't clear to me at all what this is about.

I think it was not clear what is going on, when RPM suddenly starts to complain about some file (while it was merely expansion of the argument after all). Again, this would not happen for other builtins, which are typically used as part of some expression and not at the beginning of the line.

> In >= 4.17 you can generally use a macro without having to care whether its built-in or user-defined, eg "%load foo" will try to load file "foo" as you'd expect.

Ah, this is very nice, step in the right direction. That could have simplify the RHEL7 compatibility, where we are still using the original LUA implementation.

> There are some inconsistencies left in 4.17.0

Yep, apparently `%{?load %{SOURCE4}}` is missing argument :)

So probably lets keep the status quo for the moment. Thx for all the insights :+1:

**Comment by pmatilai** [comment]
The problem with `%{?load %{SOURCE4}}`  is that the macro conditional is only for testing macro existence, and in that context arguments don't make much sense.

**Comment by hroncok** [comment]
Would this work any better? `%{?load:%{load %{SOURCE4}}}`
