### ISSUE TITLE
--qyeryformat doesn't support '\0'

### ISSUE THREAD

**Issue by thmo** [rpm-software-management/rpm#1876]
RPM's man page states
> Query formats are modified versions of the standard printf(3) formatting. The format is made up of static strings (which may include standard C character escapes for newlines, tabs, and other special characters) [...]

However, `\0` doesn't seem to be supported, instead the character '0' is emitted:

```
$ rpm -q --queryformat '%{NAME}\0' rpm | xxd
00000000: 7270 6d30                                rpm0
```

Rationale: In some contexts it would be handy to use '\0' instead of '\n' as a delimiter in queries returning results for multiple packages.

**Comment by pmatilai** [comment]
Yup, \0 terminated strings which rpm uses throughout can't contain embedded \0s. The best we could do is document this...

**Comment by DemiMarie** [comment]
> Yup, \0 terminated strings which rpm uses throughout can't contain embedded \0s. The best we could do is document this...

RPM could be refactored to use counted strings internally here.

**Comment by pmatilai** [comment]
> RPM could be refactored to use counted strings internally here.

If you actually look at it, it's not an internal matter.

**Comment by pmatilai** [comment]
...point being, anything is possible but whether it's worth it is entirely different question. This ain't.

**Comment by DemiMarie** [comment]
Would it be worthwhile to issue a warning here?

**Comment by thmo** [comment]
Stupid question: Does RPM have to expand special characters when internally using the format string? Or could that be delayed until final output?

**Comment by ffesti** [comment]
While you can't use a zero byte as a separator you actually can use any other non printable character

> rpm -q --queryformat "%{NAME}"\`echo -e "\x01"\`"%{VERSION}" rpm | xxd
> 00000000: 7270 6d01 342e 3137 2e30                 rpm.4.17.0

Given that most tags are pretty limited in what they can contain this should work for most use cases.
