### ISSUE TITLE
wrong chroot/fchdir order to break out of chroot?

### ISSUE THREAD

**Issue by vvuk** [rpm-software-management/rpm#1884]
From inspection (based on some issues on non-linux that are too complex to get in here) -- in order to "break out" of chroot, rpm does this:

https://github.com/rpm-software-management/rpm/blob/4afe2d14d33db82ccb41c0a8d5eb1a4db90762fc/lib/rpmchroot.c#L160

Isn't this backwards?  Shouldn't the `fchdir` happen first to set the process working dir to the fd, and then `chroot(".")` would then "break out"?  This all seems to work on linux though, so I'm not sure what's up.

**Comment by ffesti** [comment]
As far as I understand this the working dir is set to `/` before entering the chroot in https://github.com/rpm-software-management/rpm/blob/4afe2d14d33db82ccb41c0a8d5eb1a4db90762fc/lib/rpmchroot.c#L134 . So `(chroot(".")` goes back to `/` (leaving the chroot) and `fchdir` changes the working dir back to the location of the chroot as seen from the outside system. So this seems to be correct to me.

Please feel free to re-open with more details about your particular OS if you want to work on getting this to work there.

**Comment by vvuk** [comment]
I don't believe that's the behaviour of `chroot(".")` -- that can't be an escape, otherwise it would be a trivial chroot escape (not that chroot is all that secure, but it should be secure against this).  Here's a sample program (on Linux):

```
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <fcntl.h>

int main(int argc, char **argv)
{
    char buf[1024];

    getcwd(buf, 1024);
    printf("CWD orig: %s\n", buf);

    if (chdir("/") != 0) {
      perror("chdir");
      exit(1);
    }

    getcwd(buf, 1024);
    printf("CWD 0: %s\n", buf);

    int orig_root = open(".", O_RDONLY | O_DIRECTORY);
    if (orig_root == -1) {
        perror("open 1");
        exit(1);
    }

    if (chroot("/tmp") != 0) {
        perror("chroot");
        exit(1);
    }

    printf("Entered /tmp chroot\n");

    getcwd(buf, 1024);
    printf("CWD 1: %s\n", buf);

    // inside the chroot
    chdir("/");
    int new_root = open(".", O_RDONLY | O_DIRECTORY);
    if (new_root == -1) {
        perror("open 3");
        exit(1);
    }

    chdir(".");

    getcwd(buf, 1024);
    printf("CWD 2: %s\n", buf);

    chroot(".");
    printf("After . chroot\n");
    getcwd(buf, 1024);
    printf("CWD 3: %s\n", buf);

    fchdir(orig_root);
    printf("After fchdir\n");
    getcwd(buf, 1024);
    printf("CWD 4: %s\n", buf);
}
```

This outputs:

```
CWD orig: /home/vladimir/tmp
CWD 0: /
Entered /tmp chroot
CWD 1: (unreachable)/
CWD 2: /
After . chroot
CWD 3: /
After fchdir
CWD 4: (unreachable)/
```

note the last two CWDs-- the `chroot(.)` didn't do anything, because it just changes the root to `.` inside the chroot wd.  After, the working directory after the fchdir (to the actual true root) is still unreachable, meaning we are still inside the chroot; no exit has happened.

If I swap the order of the fchdir and the chroot:

```
CWD orig: /home/vladimir/tmp
CWD 0: /
Entered /tmp chroot
CWD 1: (unreachable)/
CWD 2: /
After fchdir
CWD 4: (unreachable)/
After . chroot
CWD 3: /
```

then I actually break out of the chroot.

**Comment by vvuk** [comment]
(My original comment about "this works fine" was really "rpm doesn't seem to be doing anything wrong" -- but I think that's because rpm does all its work inside the chroot, and this 'exit' is just cleanup)

**Comment by mlschroe** [comment]
It's supposed to work like this:

before rpmChrootIn:
root: /
cwd: /home/user

after rpmChrootIn:
root: /rootdir
cwd: /    (i.e. outside of the /rootdir chroot jail!)

Thus, rpm dies a chroot(.) to restore the original root and a fchdir() to restore the original working directory.

One might argue that rpm should not assume that the cwd is unchanged and that it would be better to also open a fd that points to the original root.

**Comment by vvuk** [comment]
Ah yep, ok; that makes sense, I just assumed that cwd not changing isn't something that can be taken as a given.  (Also assumed that the process running with an unreachable cwd is bound to cause some weird problems especially when forking, but guess not?)
