### ISSUE TITLE
[RFE] Allow RPM to read chained databases

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#1885]
In Fedora, there is push to move RPM database into `/usr` [[1]]. The change claims that: _"The RPM database primarily describes the state of /usr"_. I don't think this it the right premise. It might be true only for OSTree based systems, but I don't think the idea is general enough. However, even prior OSTree, there were systems where `/usr` was NFS mounted. Having NFS mountable location was also one of preconditions for SCLs. So while I don't think that the `/usr` is right place for system wide RPM database location, there always was a need for RPM to provide information about some directory structure outside of the system.

Therefore, is there chance that RPM could be able to read RPM databases from different locations? These locations could be defined during build time or via some environment variable for runtime.

[1]: https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr

**Comment by ffesti** [comment]
Surprisingly this is not the first time this has come up. The answer still is: "yes, with some - but not completely unreasonable - amount of work." The caveat also still is that just reading multiple databases is not enough to create a useful feature. This starts to become interesting when you are trying to change (or more likely - replace) the base database that comes with the system image, chroot, snapshot, whatever. This may break packages in the system/user/local/upper layer(s) RPM DB. So one needs to check for this and - and that's the hard part - offer the user a way to deal with these errors.

So far the the answer to questions like this has been to copy the rpmdb from the base image and apply local changes to that. Yes, it does not allow swapping out the base image. But it does make all the problems that comes with that go away.

**Comment by ffesti** [comment]
Note: If you want to replace the system image you can still try to recreate the RPM DB by adding the locally installed packages to the rpmdb of the base image. There may be a few details that require work but in general this is something that is quite doable and I actually did in the first decade of this century.

**Comment by voxik** [comment]
Yes, I am not surprised somebody had the idea before, but I am surprised that this is denied and to "somehow recreate the database" is suggested instead. Yes, I realize that there are some caveats, but the caveats are not different to e.g. `rm -rf` some file/directory. Also, the "system image" is certainly one of the use cases, but the network mount which was required for SCLs assumes constant possibility of changes, so recreating DB for such use case is probably not viable option.

So please, could you reconsider your stance on this issue and do what can be done and try to polish the outstanding issues once they come? After all, moving RPM db into `/usr` is not better option IMO (while I understand it seems to be no work for RPM upstream).

**Comment by voxik** [comment]
BTW is there any previous ticket for a reference?

**Comment by lnussel** [comment]
Maybe related: #1151. That model would allow to feed a single "database" aka lookup cache from multiple locations. The way the api for storing stuff in the database is implemented in rpm seems to make possible to divert writing the rpm header to disk rather than (or in addition to) the database. If the database gets deleted/corrupted/out of sync it would be mostly a matter of `cat *.rpm|rpmdb --importdb`

**Comment by voxik** [comment]
Only if the #1151 was not rejected similarly to this ;)
