### ISSUE TITLE
Ignore most unhashed subpackets in OpenPGP signatures

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1886]
Unhashed subpackets are not covered by the signature, so they can be set to anything.  Therefore, it is only safe to process subpackets that restrict the validity of the signature.  I recommend going further and ignoring everything except for primary key binding signatures, key ID subpackets, and fingerprint subpackets.

**Comment by DemiMarie** [comment]
If this is a good idea I am willing to make a PR.

**Comment by teythoon** [comment]
>  Therefore, it is only safe to process subpackets that restrict the validity of the signature.

Not quite.  It is only safe to process subpackets that are self-authenticating.  For example, the issuer subpacket is self-authenticating:  It is used as a hint as to which key made the signature.  If that key is found, the signature can be verified with it.  If successful, this authenticates the issuer subpacket.

> I recommend going further and ignoring everything except for primary key binding signatures, key ID subpackets, and fingerprint subpackets.

I'm assuming you mean embedded signature, issuer, and issuer fingerprint subpackets.  That list looks good, yes.

**Comment by DemiMarie** [comment]
> > Therefore, it is only safe to process subpackets that restrict the validity of the signature.
> 
> Not quite. It is only safe to process subpackets that are self-authenticating. For example, the issuer subpacket is self-authenticating: It is used as a hint as to which key made the signature. If that key is found, the signature can be verified with it. If successful, this authenticates the issuer subpacket.

Agreed.  I would go further and reject a signature that has a subpacket which cannot validly be in the unhashed section.

> > I recommend going further and ignoring everything except for primary key binding signatures, key ID subpackets, and fingerprint subpackets.
> 
> I'm assuming you mean embedded signature, issuer, and issuer fingerprint subpackets. That list looks good, yes.

Is there ever a reason to have an embedded signature in a type 0 or type 1 signature?  The only use-case I can think of is timestamping.  At the very least, an embedded signature must not also have an embedded signature to avoid recursion.

**Comment by DemiMarie** [comment]
> > Agreed. I would go further and reject a signature that has a subpacket which cannot validly be in the unhashed section.
> 
> I think that is too far. At the very least, allow unknown and private subpackets there, as they may be self-authenticating.

I am only referring to stuff that is known to *not* be self-authenticating.  Key usage flags and timestamps are examples.

> > Is there ever a reason to have an embedded signature in a type 0 or type 1 signature? The only use-case I can think of is timestamping.
> 
> The predominant use case are primary key binding signatures, but RPM doesn't want to even attempt to canonicalize certificates. Timestamping is a great use case though :) But, for timestamping purposes, we'd want the signature to end up in the hashed subpacket area.

I thought that timestamping signatures were usually of the signature being timestamped, and optionally the public key.  At least that is how I believe they work on Windows and macOS.

> > At the very least, an embedded signature must not also have an embedded signature to avoid recursion.
> 
> That is only interesting if you actually attempt to verify the embedded signature. I don't see RPM doing that anytime soon. First, they don't want to canonicalize certs. Second, for timestamping purposes you'd need the certificate of the timestamping entity. That requires non-local reasoning, and I don't see that on the horizon either, given the state of RPM's OpenPGP implementation.

Indeed.  I do not want RPM to wind up reimplementing (or using!) Cryptographic Message Syntax.  The signature format should become simpler, not more complex.  A raw ed25519 signature (using a distinct tag) would be ideal.

**Comment by teythoon** [comment]
> I thought that timestamping signatures were usually of the signature being timestamped, and optionally the public key. At least that is how I believe they work on Windows and macOS.

I guess there are different ways to implement that.  One prototype "wraps" the notarized signature like that: https://dev.gnupg.org/T4108#129183

> A raw ed25519 signature (using a distinct tag) would be ideal.

Let's agree to disagree :)

**Comment by pmatilai** [comment]
As per #1935, the internal parser is on it's slow way out and should not be further developed.
