### ISSUE TITLE
CONTRIBUTING.md: document that NULL is usually interpreted “invalid argument” or similar

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1901]
See https://github.com/rpm-software-management/rpm/pull/1801#discussion_r733414153 for the motivation for this issue.  Hopefully putting this in CONTRIBUTING.md will help prevent others from making the same mistake I did.

**Comment by ffesti** [comment]
This is not quite the level of details we want the Contributing document to get into. We can't just list all good practices. There are documents and whole books on good C programming and we don't want to write  another one.
