### ISSUE TITLE
Please add stdin support for `rpmspec -P`

### ISSUE THREAD

**Issue by cryptomilk** [rpm-software-management/rpm#1926]
Hello,

I would be nice to have a stdin mode for `rpmspec -P`.

I'm using `rpmspec -P` in my neovim together with [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/) to get warnings and errors directly displayed inside the editor. Currently it uses a temporary file, using stdin would be much faster ...

![rpmspec](https://user-images.githubusercontent.com/545480/154801492-0cfdf9b4-f925-4194-8c22-153b242251c7.png)

```lua
local helpers = require("null-ls.helpers")

local rpmspec = {
    name = "rpmspec",
    method = null_ls.methods.DIAGNOSTICS,
    filetypes = { "spec" },
    generator = null_ls.generator({
        command = "rpmspec",
        args = {
            "-P",
            "$FILENAME"
        },
        to_temp_file = true,
        from_stderr = true,
        format = "line",
        check_exit_code = { 0, 1 },
        on_output = helpers.diagnostics.from_patterns({
            -- error
            {
                pattern = [[(%w+): (.*): line (%d+): (.*)]],
                groups = { "severity", "filename", "row", "message" },
            },
            -- warning (completely differs from error)
            {
                pattern = [[(%w+): (.*) in line (%d+):]],
                groups = { "severity", "message", "row" },
            },
        }),
    }),
}

null_ls.register(rpmspec)
```

Also the error/warning could be a bit more consistent ... ;-)

**Comment by cryptomilk** [comment]
Maybe `rpmspec -P -` to indicate you want stdin. This is already used by various command line tools and you don't have to add another option.

**Comment by ffesti** [comment]
As discussed in the PR this is more complicated than initially expected. So I am closing this as WONTFIX. On Linux you can still just use `/dev/stdin` to achieve the desired behaviour.

If anyone knows why this work although we are opening and reading it multiple times I'd be interested to here that.

**Comment by cryptomilk** [comment]
I think `/dev/stdin` only works with a shell. It doesn't work if you execv(). At least I get `error: Unable to open /dev/stdin: No such device or address`

**Comment by DemiMarie** [comment]
> I think `/dev/stdin` only works with a shell. It doesn't work if you execv(). At least I get `error: Unable to open /dev/stdin: No such device or address`

On what operating system?  On Linux that might happen if stdin is a socket.

**Comment by cryptomilk** [comment]
> > I think `/dev/stdin` only works with a shell. It doesn't work if you execv(). At least I get `error: Unable to open /dev/stdin: No such device or address`
> 
> On what operating system? On Linux that might happen if stdin is a socket.

On Linux (Fedora), where `/dev/stdin` is a symlink to `/proc/self/fd/0`
