### ISSUE TITLE
conditional builds with underscrore don't have _without option

### ISSUE THREAD

**Issue by sergiomb2** [rpm-software-management/rpm#1929]
to avoid many errors we should also have _without as explained  in https://github.com/rpm-software-management/rpm/pull/1520#issuecomment-1046342030,  I recently realized that there is a subtle difference between "with" with a space and "with" with an underscore 
```
%bcond_without static 
%if %{without static} works but %{?without_static: ... } doesn't work , isn't it ?
```

therefore we should make %{?without_static: ... } work. 

reference:
https://github.com/rpm-software-management/rpm/blob/master/docs/manual/conditionalbuilds.md

**Comment by dmnks** [comment]
Related: #1256

**Comment by JetXujing** [comment]
https://github.com/rpm-software-management/rpm/pull/1256 and https ://github.com/rpm-software-management/rpm/blob/master/docs/manual/conditionalbuilds.md have explained in detail whether this issue can be closed.

**Comment by sergiomb2** [comment]
is not well explained IMO it should have explicit write without-counterpart doesn't work

**Comment by sergiomb2** [comment]
when this feature will be available on rpm package ?

**Comment by pmatilai** [comment]
The manual explicitly states:

```
Alternatively, you can test the presence (or lack thereof) of %with_foo macros which is nicer in other situations, e.g.:

%configure \
   %{?with_static:--enable-static} \
   %{!?with_static:--disable-static}

Always test for the with-condition, not the without-counterpart!
```

Doing something undocumented and expecting it to work usually doesn't. This all works fine AFAICS, just stick to what is documented.

**Comment by pmatilai** [comment]
And for some reason you insist on using the one that doesn't work, and isn't documented? That's not intuitive to me either.

**Comment by sergiomb2** [comment]
I don't use it but I found many people that use it (wrongly)  

https://sourcegraph.com/search?q=context:global+r:src.fedoraproject.org+file:.*%5C.spec%24+%5C%3Fwithout_&patternType=regexp&case=yes&sm=0&groupBy=repo
