### ISSUE TITLE
rpmdb functions are not thread-safe

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1943]
Calling rpmdb functions concurrently in multiple threads, even on different databases, can result in undefined behavior, due to unsynchronized global state in [`lib/rpmdb.c`](https://github.com/rpm-software-management/rpm/blob/c4aa971d4ab9d7d698325839b23ceb75f2eaa6e7/lib/rpmdb.c).

**Comment by pmatilai** [comment]
The global state in question removed in commit 35b93119a30029a889346a2b93312f031888524d, but I make no promises about thread safety.

**Comment by pmatilai** [comment]
Well, that sounds strange. The keyring *is* thread-protected (barring bugs of course), and like mentioned elsewhere the rpmdb takes no part in the keyring operation beyond initial population (if used that way)

**Comment by DemiMarie** [comment]
> Well, that sounds strange. The keyring _is_ thread-protected (barring bugs of course), and like mentioned elsewhere the rpmdb takes no part in the keyring operation beyond initial population (if used that way)

Thanks!  Filed https://github.com/QubesOS/qubes-rpm-oxide/pull/16.
