### ISSUE TITLE
Print exit code with rpm -vv (+PATCH)

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#195]
This trivial patch helps diagnose rpm behavior while developing or testing.

`
diff --git a/rpmqv.c b/rpmqv.c
index 8655776..4f448c2 100644
--- a/rpmqv.c
+++ b/rpmqv.c
@@ -354,5 +354,7 @@ int main(int argc, char *argv[])
 
     rpmcliFini(optCon);
 
+    rpmlog(RPMLOG_DEBUG, "exit code: %d\n", ec);
+
     return RETVAL(ec);
 }
`

**Comment by Conan-Kudo** [comment]
@n3npq Pro tip:

You can preserve formatting of diffs by wrapping it in triple backticks and declaring format type, like so:

```diff
--- foo
+++ foo
@@ -1 +1 @@
-bar
+baz
```

Use ` ```diff ` before the first line, and use ` ``` ` after the last line.

**Comment by Conan-Kudo** [comment]
@n3npq Sorry it took so long. I've converted it into a Git patch and submitted PR #252 for this.

Thanks for the patch.

**Comment by ffesti** [comment]
Pushed as #252
