### ISSUE TITLE
The manuals in docs/manual need some love

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#1952]
As you're doing spring related cleanups, please have a look at the files in docs/manual. There's lots of outdated stuff in them, for example:

- buildprocess.md: the new %conf section is missing
- buildroot.md: the buildroot is nowadays always set
- dependencies.md: it says "unspecified epoch" provides all/requires any epoch
- format.md: The "Tools" section seems to be completely outdated
- signatures_digests.md: ed25519 is missing
- signatures.md: talks about calling a pgp executable to verify signatures
- tsort.md: weird stuff. the part about RPMSENSE_SCRIPT_PREP and the like seems to be completely wrong

**Comment by pmatilai** [comment]
Sure, much of that stuff originates from the nineties. Will fix, patches also welcome.
%conf is actually mentioned in buildprocess.md but like most sections, is unexplained in there.

**Comment by pmatilai** [comment]
Cleaned some of that now, it was just so outdated its better not to have it there at all. More to do though.

**Comment by pmatilai** [comment]
With the ordering docs rewritten, I think this can be considered done. For the purposes of eliminating dangerously outdated and misleading docs at least.

Thanks for pointing these out.
