### ISSUE TITLE
scripts/check-buildroot Does not work correctly with newer grep.

### ISSUE THREAD

**Issue by jackorp** [rpm-software-management/rpm#1968]
scripts/check-buildroot does not work correctly on EPEL 9 (CentOS 9 and RHEL 9) and Fedora Rawhide (other Fedoras might be affected as well).

EPEL 8 seems to not suffer this as it has an older grep v3.1

Exactly this line: https://github.com/rpm-software-management/rpm/blob/a6913834d395d6544c2ba1578d6ebd594350b602/scripts/check-buildroot#L32
Does not work as expected, as grep outputs the match of a binary file into STDERR, resulting in having `"$tmp"` empty when it should have content and then the build passes where it should fail.

To demonstrate using a binary file:
Fedora Rawhide:
```console
$ LC_ALL=C.UTF-8 grep -F ruby /usr/lib64/libruby.so.3.1 > result
grep: /usr/lib64/libruby.so.3.1: binary file matches
$ cat result
$ grep --version                                                                                                                                                                                    13:16:49
grep (GNU grep) 3.7
```

RHEL 8
```console
$ grep -F ruby /usr/lib64/libruby.so.2.5 > result
$ cat result 
Binary file /usr/lib64/libruby.so.2.5 matches
$ grep --version
grep (GNU grep) 3.1
```

**Comment by jackorp** [comment]
The change in grep is intentional and happened with grep v3.5
https://savannah.gnu.org/forum/forum.php?forum_id=9820

**Comment by jackorp** [comment]
The issue is visible for example here (full log): https://kojipkgs.fedoraproject.org//packages/ruby/3.1.1/162.fc37/data/logs/x86_64/build.log

Snippet:
```
+ /usr/lib/rpm/check-buildroot
grep: /builddir/build/BUILDROOT/ruby-3.1.1-162.fc37.x86_64/usr/lib/debug/usr/lib64/gems/ruby/debug-1.4.0/debug/debug.so-3.1.1-162.fc37.x86_64.debug: binary file matches
grep: /builddir/build/BUILDROOT/ruby-3.1.1-162.fc37.x86_64/usr/lib/debug/usr/lib64/gems/ruby/rbs-2.1.0/rbs_extension.so-3.1.1-162.fc37.x86_64.debug: binary file matches
+ /usr/lib/rpm/redhat/brp-ldconfig
```
Build goes on, when it should have failed on `check-buildroot` step.

**Comment by pmatilai** [comment]
Ack, thanks for the report.

**Comment by voxik** [comment]
I wish the fix included also test case, because this was unnoticed for quite some time (more then 1 year?)
