### ISSUE TITLE
can `rpm -q --qf` display all STRING_ARRAY values ?

### ISSUE THREAD

**Issue by ktdreyer** [rpm-software-management/rpm#1975]
Is there any way to view entire `STRING_ARRAY` values with `rpm -q --qf`? For example, this command only displays the first `FILESIGNATURES` entry, not all of them:

```
rpm -q --qf '%{FILESIGNATURES}\n' -p bash-5.1.8-3.fc36.src.rpm
```

Is there any other way to display `STRING_ARRAY` values on the shell?

**Comment by DemiMarie** [comment]
Yes: `rpm -q --qf '[%{FILESIGNATURES}\n]'` should work.  That ought to be better documented, though.

**Comment by pmatilai** [comment]
On the contrary, I think this is one of the few things where we have quite adequate documentation:
https://rpm-software-management.github.io/rpm/manual/queryformat.html#arrays

**Comment by ktdreyer** [comment]
Thanks! I checked `man rpm`, searched "array" and did not find anything. But that web page is very helpful.
