### ISSUE TITLE
Don't assert the version of rpm used to create the data in test 267

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#1985]
fa70eca360e39d61504d1c33079892706f2f8af6 added a new test, which checks that the output is exactly:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: rpm-4.17.90

mQENBFjmORgBCAC7TMEk6wnjSs8Dr4yqSScWdU2pjcqrkTxuzdWvowcIUPZI0w/g
...
```

If rpm's version number changes, this will break.  (And it already breaks the sequoia backend.)

**Comment by pmatilai** [comment]
There's a test we need to update whenever the version changes already, we don't really need another one :smile: That was never really the point of that test anyway. Thanks for the patch too.
