### ISSUE TITLE
logging: Use log calls instead of fprintf() in fdstat_print()

### ISSUE THREAD

**Issue by lukash** [rpm-software-management/rpm#1987]
The `fdstat_print()` function: https://github.com/rpm-software-management/rpm/blob/a6913834d395d6544c2ba1578d6ebd594350b602/rpmio/rpmio.c#L220

prints directly to `stderr` (passed via `fp`), thus eluding the logging callback if set. It should instead use the standard log calls (possibly also only log if `rpmio_debug` is enabled).

This is a bit of a blocker for dnf 5, as it can mess up our outputs, the fix should be quite easy.

**Comment by pmatilai** [comment]
Thanks for the report. Those stats haven't been that useful this side of the millenium I think...
Changing rpmio debugging to use rpmlog() throughout seems more trouble than its worth so I just changed the stats to get printed out when --rpmiodebug is specified on rpm command line (ie practically never).
