### ISSUE TITLE
Purge obsolete APIs

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#1989]
Adding this as a place to collect all the garbage that needs taking out before 4.19, preferrably at the start of the cycle.

As of this writing, there's at least
- pgpDig related
- rpmds nopromote related
- rpmsq machinery
- rpmfi dx related
- headerLoad/Unload + friends

**Comment by DemiMarie** [comment]
Can the behavior of `headerImport` with a zero length be added to that list?  It should really be an error.

**Comment by pmatilai** [comment]
This is about removing symbols, not API behavior.
