### ISSUE TITLE
4.17.0: problem with processing macros params

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#1998]
I need macro which needs to use some optional parametr.
That macro looks like:
```spec
%build_foo() %{expand:\\\
        /usr/bin/command -a -b -c %[%{*}?"%{*}":"bar"] -d}
```
So theoreticall if that `%build_foo` macro should be called without parameters it should be unrolled to `/usr/bin/command -a -b -c bar -d`.
If it will be called as `%build_foo something` it shoud be unrolled to `/usr/bin/command -a -b -c somehing -d`.

Issue is that If I'm usig that macro without param it is indeed unrolled to `/usr/bin/command -a -b -c bar -d` however hen it is used with param rpmbuild fails with:
```console
RPM: error: macro expansion returned a bare word, please use "...": %{*}?"%{*}":"bar"
RPM: error:                                                         ^
RPM: error: expanded string: bar
Failed to open: 'test_package.spec', not a valid spec file: can't parse specfile

Error: Some packages could not be found.
error: macro expansion returned a bare word, please use "...": %{*}?"%*":"bar"
error:                                                         ^
error: expanded string: doc-source
  2<      (%build_foo)
  2<      (%)
  1<    (%expand)
  0<  (%build_foo)
```

**Comment by mlschroe** [comment]
Don't you just need to quote the `%{*}`? I.e.:
```
%["%{*}"?"%{*}":"bar"]
```

**Comment by kloczek** [comment]
EXACTLY that was missing!
Thank you 😄 
Closing.
