### ISSUE TITLE
logging: Header verification logged as multiline message

### ISSUE THREAD

**Issue by lukash** [rpm-software-management/rpm#2028]
The following debug level log message from librpm contains multiple newlines, which makes it somewhat ugly and inconsistent, formatting as single line or logged as multiple messages would be better:

```
2022-04-04T11:09:58+0200 [245631] TRACE [rpm]  read h#    1228 
Header V4 RSA/SHA256 Signature, key ID 9867c58f: OK
Header SHA256 digest: OK
Header SHA1 digest: OK
```

The first line (`"read h#    1228"`) is also quite cryptic, so maybe some improvement on that would also be nice.

**Comment by dmnks** [comment]
The `Header` lines come from a different C function which is used also in normal output with `-K, --checksig` and it would be a little painful to reformat those. However, the `read #h` messages could indeed use some improvement, even though they really are just for debugging purposes.

**Comment by dmnks** [comment]
Pondering about this a little more, it really isn't an easyfix as it touches some rather low level code. If it turns out to be important enough for a lot of people, we can revisit but I'll just close now.
