### ISSUE TITLE
Incorrect __progname definition

### ISSUE THREAD

**Issue by moubctez** [rpm-software-management/rpm#203]
__progname defined as
`const char *__progname;`
is not portable. For example, it causes segmentation fault on Darwin.

The correct definition should include **extern** (as in system.h)
`extern const char *__progname;`

To fix, either change the definition or remove the lines where system.h is also included.

Affected files:
lib/poptALL.c
rpm2archive.c
rpm2cpio.c
rpmbuild.c
rpmqv.c
rpmspec.c
tools/rpmdeps.c
tools/rpmgraph.c

**Comment by pmatilai** [comment]
This has been fixed in git master for quite some time, see commit 61109446ac67ca8f3d96a5592814561db908d83c.

When reporting issues, please note the version used and preferably try to check upstream situation first.

**Comment by Conan-Kudo** [comment]
@pmatilai We broke this with fa06b68ed7640c0e42a8a63dd9cb0bf8d4c73525.

Interestingly, it seems Yocto (who hasn't yet caught up to current master), [patched in to enable the internal implementation](https://raw.githubusercontent.com/openembedded/openembedded-core/2358e786ec8d1199d90e181eb5d8d00816f669b4/meta/recipes-devtools/rpm/files/0001-Fix-build-with-musl-C-library.patch) for one of their configurations that OpenEmbedded supports.

We might want to bring back that internal implementation and use a variant of the OE patch to make sure it gets used appropriately.

**Comment by ldv-alt** [comment]
No, fa06b68 is fine; musl provides __progname, all Yocto needs is just use it.

**Comment by pmatilai** [comment]
fa06b68 could not have broken it because the removed part was uncompilable and thus had never been enabled in any setup.
