### ISSUE TITLE
tests about verify colored files ran failed

### ISSUE THREAD

**Issue by Ren0216** [rpm-software-management/rpm#2033]
Recently，when I got the patches from #1967 in use, then met the follow results:

> 308: rpm -e and shared files removed 1.2 FAILED (rpme.at:76)
> 309: rpm -e and verify colored files removed 1.1 FAILED (rpme.at:122)
> 310: rpm -e and verify colored files removed 1.2 FAILED (rpme.at:148)
> 311: rpm -e and verify colored files removed 2.1 ok
> 312: rpm -e and verify colored files removed 2.2 ok
> 313: rpm -e and verify conflicting files removed 1 FAILED (rpme.at:260)

After some testing , I found that the test 307 had forgot to delete hello.i686, and somehow the following tests done as the same. Inserting some 'rpm -e' could fix 308,309,310.
As for 311, the output may be out of sequence for its last two checks probably,    eg:

```
.........    /usr/share/my.version (replaced)
.........    /usr/share/my.version
missing     /usr/share/my.version (replaced)
```

replaced with:

```
.........    /usr/share/my.version
.........    /usr/share/my.version (replaced)
missing     /usr/share/my.version (replaced)
```
then, the check would pass.

Does anyone have the same problem?
I'm not sure it's a problem. If so, too obviously.

Eager for help！

**Comment by pmatilai** [comment]
The patches have a severe regression on their own, don't use.

**Comment by Ren0216** [comment]
OK, got it.
