### ISSUE TITLE
Gem expansion is broken with RPM 4.18.

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#2040]
When the gem expansion was introduced, it expanded the gem into `%{_builddir}/%{?buildsubdir}` and there was also created `%{_builddir}/%{gem_name}-%{gem_version}.gemspec` file. However, now the `.gemspec` file is created as `%{_sourcedir}/%{gem_name}-%{gem_version}.gemspec`. This breaks all rubygem- packages on Fedora.

**Comment by voxik** [comment]
This is the verbose example:

~~~
$ /usr/lib/rpm/rpmuncompress -x /builddir/build/SOURCES/nio4r-2.5.2.gem --verbose
/usr/bin/gem unpack  '/builddir/build/SOURCES/nio4r-2.5.2.gem' && /usr/bin/gem spec '/builddir/build/SOURCES/nio4r-2.5.2.gem' --ruby > '/builddir/build/SOURCES/nio4r-2.5.2.gemspec'
Unpacked gem: '/builddir/nio4r-2.5.2'
~~~

It seems this line is the culprit:

https://github.com/rpm-software-management/rpm/blob/bb36aac905cf8eb470f085574641d92c8d8ca20f/tools/rpmuncompress.c#L106

It used to be:

~~~
	    gemspec = rpmGetPath("%{_builddir}/", gemnameversion, ".gemspec", NULL);
~~~

**Comment by voxik** [comment]
The line I have mentioned is probably OK after all, but the `gemnameversion` does not contain just the gem name + version as it says but it also contains the whole path. Maybe something like this could fix it?

~~~diff
$ git diff
diff --git a/tools/rpmuncompress.c b/tools/rpmuncompress.c
index 609fb0f53..18fff30c7 100644
--- a/tools/rpmuncompress.c
+++ b/tools/rpmuncompress.c
@@ -97,12 +97,12 @@ static char *doUntar(const char *fn)
        if (needtar) {
            rasprintf(&buf, "%s '%s' | %s %s -", zipper, fn, tar, taropts);
        } else if (at->compressed == COMPRESSED_GEM) {
-           size_t nvlen = strlen(fn) - 3;
+           size_t nvlen = strlen(basename(fn)) - 3;
            char *gem = rpmGetPath("%{__gem}", NULL);
            char *gemspec = NULL;
            char gemnameversion[nvlen];
 
-           rstrlcpy(gemnameversion, fn, nvlen);
+           rstrlcpy(gemnameversion, basename(fn), nvlen);
            gemspec = rpmGetPath("", gemnameversion, ".gemspec", NULL);
 
            rasprintf(&buf, "%s '%s' && %s spec '%s' --ruby > '%s'",
~~~

**Comment by pmatilai** [comment]
Thanks for the report and sorry about the regression. I know I tested rubygem unpack with something, but maybe I didn't try entire build :thinking:

**Comment by pmatilai** [comment]
Oh and thanks for the patch as well, that seems to fix it. I'll update Fedora ASAP.

**Comment by voxik** [comment]
Credits for reporting goes to @mtasaka:

https://lists.fedoraproject.org/archives/list/ruby-sig@lists.fedoraproject.org/thread/XXKFM6XEEM3GVIWOC55BDSXDU63WOKEW/

Forgot to mention this in a hurry trying to identify the cause and the medicine. Sorry :disappointed:

**Comment by pmatilai** [comment]
It happens...

BTW, @hroncok added a [Fedora CI test](https://src.fedoraproject.org/rpms/rpm/pull-request/24) for another 4.18 alpha regression affecting python packages, if you have something we could use for rubygems similarly that'd be very welcome.
