### ISSUE TITLE
RFE: Backport %bcond macro down to 4.16 and 4.17 maintanance releases

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#2042]
I've opened this based on [this downstream comment](https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/183#comment-104083). I understand if you want to let it exist in 4.18 for a while, at least until 4.18 final is released.

Thanks

**Comment by pmatilai** [comment]
So this got included in 4.17.1, but as for 4.16, that fell out of upstream support with the release of 4.18, I don't see us doing more maintenance releases for that. Enterprise distros of course do what they see fit.

**Comment by hroncok** [comment]
> Enterprise distros of course do what they see fit.

https://bugzilla.redhat.com/2129060
