### ISSUE TITLE
rpm.pc leaks librpm_sequoia dependency

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2051]
[@pmatilai wrote](https://github.com/rpm-software-management/rpm/pull/2043#discussion_r861688767):

> At the very least @WITH_RPM_SEQUOIA_LIB@ needs to be added to rpm.pc.in so it gets pulled in through that, but I'd prefer hiding this all inside librpmio, which would require some kind of wrapping rather than the direct approach used now. But that's probably out of scope here.

To work around this problem, [I added `@WITH_RPM_SEQUOIA_LIB@` to Libs in the `rpm.pc.in` file](https://github.com/rpm-software-management/rpm/blob/db36ea85aac23620d71ed38cc9a263b6bab3af98/rpm.pc.in#L15).  This means that software linking against librpm will have a `DT_NEEDED` entry for `librpm_sequoia`, which is unnecessary.

I wonder if it is sufficient to just put it in `Libs.private`?  `librpmio.so` has a `DT_NEEDED` entry for `librpm_sequoia`:

```
$ grep Libs rpm.pc
Libs: -L${libdir} -lrpm -lrpmio -L/tmp/rpm/rpm-sequoia/target/release -lrpm_sequoia -lnettle
Libs.private: -lpopt -lrt -lpthread -llzma -lbz2 -lz -llua5.4
$ PKG_CONFIG_PATH=. pkg-config --libs rpm
-L/usr/local/lib -L/tmp/rpm/rpm-sequoia/target/release -lrpm -lrpmio -lrpm_sequoia -lnettle -lpopt
$ objdump -p /tmp/rpm/rpm/b/rpmio/.libs/librpmio.so | grep NEEDED
  NEEDED               librpm_sequoia.so
...
```

**Comment by pmatilai** [comment]
Hmm. If librpmio.so has DT_NEEDED for librpm_sequoia, then how come the rpmpgpcheck test program needs explicit linkage?

**Comment by nwalfield** [comment]
Hmm... good question.

**Comment by pmatilai** [comment]
Maybe it gets "optimized out" because there are no actual references from librpmio to the sequoia library.

**Comment by nwalfield** [comment]
I spent some time investigating the issue.  It appears that a library does not reexport another library's symbols.  This is why a program foo that depends on librpmio has to explicitly link against librpm_sequoia.  I sent [a mail](http://lists.rpm.org/pipermail/rpm-maint/2022-May/020469.html) to the libtool maintainers and the `rpm-maint` mailing list asking for advice.  [@pmatilai replied](http://lists.rpm.org/pipermail/rpm-maint/2022-May/020472.html):

> The simple and straightforward solution is to leave the rpm API into 
> librpmio, and use a separate one for the PGP backend. Ie the backend 
> implements an API which librpmio calls, and therefore we have the right 
> dependencies automatically.

The referenced PR does exactly that.  Note: this requires [this change](https://gitlab.com/sequoia-pgp/rpm-sequoia/-/merge_requests/13) to rpm_sequoia.  I'll merge that if we agree that this is the right way forward.
