### ISSUE TITLE
lists.rpm.org failing certificate validation

### ISSUE THREAD

**Issue by chantra** [rpm-software-management/rpm#2055]
The link to the mailing list mentioned in https://github.com/rpm-software-management/rpm/discussions/2013 is failing cert validation because the only CN/Alt  Names are for osuosl.org/*.osuosl.org which fails when accessing the mailing list under lists.rpm.org .

**Comment by ffesti** [comment]
Yeah, our mailing list are hosted by the OSUOSL for historic reasons. With the mailing lists loosing more and more in importance I doubt we want to bother the OSUOSL to change their HTTPS certificates.

Still thanks for reporting!
