### ISSUE TITLE
linting warnings cause test failures

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2071]
The recently added [linting warnings] cause several tests to fail with using the Sequoia backend:

```
271: rpmkeys --import, signed with an expired subkey FAILED (rpmsigdig.at:385)
272: rpmkeys --import, signed with a revoked subkey  FAILED (rpmsigdig.at:452)
273: rpmkeys --import invalid keys                   FAILED (rpmsigdig.at:524)
```

The failures are all similar and look like this:

```
271. rpmsigdig.at:382: testing rpmkeys --import, signed with an expired subkey ...
../../tests/rpmsigdig.at:385:
...
--- /dev/null	2022-04-22 22:03:25.100325727 +0000
+++ .../rpm/b/tests/rpmtests.dir/at-groups/271/stderr	2022-05-13 09:55:15.677911158 +0000
@@ -0,0 +1,3 @@
+warning: Certificate B3A771BFEB04E625:
+  Subkey 1F71177215217EE0 is expired: The subkey is not live
+  Certificate does not have any usable signing keys
271. rpmsigdig.at:382: 271. rpmkeys --import, signed with an expired subkey (rpmsigdig.at:382): FAILED (rpmsigdig.at:385)
```

I tried doing `rpmkeys --quiet --import`, but `--quiet` still shows warnings.  Changing the warning to use `RPMLOG_NOTICE` instead of `RPMLOG_WARNING` means that the warning is still emit by default, but can be suppressed through the use of `--quiet`.  That not only fixes the problem, but is more consistent with `--quiet`, I think.

**Comment by DemiMarie** [comment]
> I tried doing `rpmkeys --quiet --import`, but `--quiet` still shows warnings.  Changing the warning to use `RPMLOG_NOTICE` instead of `RPMLOG_WARNING` means that the warning is still emit by default, but can be suppressed through the use of `--quiet`.  That not only fixes the problem, but is more consistent with `--quiet`, I think.

I believe this runs into another problem: `RPMLOG_NOTICE` is sent to stdout, whereas `RPMLOG_WARNING` is sent to stderr.  The output of `rpmkeys -K` is sent via `RPMLOG_NOTICE`, and having it not go to stdout would break lots of programs, including DNF.

**Comment by nwalfield** [comment]
@DemiMarie: Indeed, `RPMLOG_NOTICE` is sent to `stdout`, and `RPMLOG_WARNING` is sent to `stderr`.

I'll have to rethink this.  I'm open to suggestions.

**Comment by nwalfield** [comment]
I've added [a manual check](https://github.com/nwalfield/rpm/commit/82e6e14700960418927dbb9ab77e204d0fd9a1dd#diff-4b55147683ac8fc6a52100fbaa8431a6f978abe919b29aa9ac151b3de0ad47cbR624-R631) to see if the program is in quiet mode:

```
            if (rpmIsNormal()) {
                rpmlog(RPMLOG_WARNING, "%s\n", lints);
            }
```

What do you think?
