### ISSUE TITLE
4.17.0: `%autopatch` do not recognise `-S git` param

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#2077]
Looks like %autopatch do not recognise -S git param.
```console
autopatch: invalid option -- 'S'
RPM: error: test.spec: line 48: Unknown option S in autopatch(vp:m:M:)
Failed to open: 'test.spec', not a valid spec file: can't parse specfile
```
IMO it should be able to to what `%autosetup -S git` does.

**Comment by pmatilai** [comment]
Nope. VCS'es need setting up and cannot be swapped interchangeably, that's why you select it when calling %autosetup and %autopatch uses that.

**Comment by kloczek** [comment]
Looks like it need git metadata ONLY because is used --index option which is IMO pointless as long as after build whole build directory is discarded.
git can apply patch without committing it to metadata.

Issue is that GNU patch still cannot handle uuencoded binary patches used in git test format.
Sometimes before actual %autopatch it is necessary to perform few operations so full `%autopatch -S git` symmetry with `%autosetup -S git` would be really useful.

**Comment by pmatilai** [comment]
If you only want git, then use it by all means. %autopatch requires calling %autosetup and will not gain -S because, see my earlier comment.

**Comment by kloczek** [comment]
> %autopatch requires calling %autosetup and will not gain -S because, see my earlier comment.

That phrase does not make any sense as
```spec
%prep
%autosetup
%autopatch
```
Will cause two times apply the same set of patches.

**Comment by pmatilai** [comment]
How about reading the docs. https://rpm-software-management.github.io/rpm/manual/autosetup.html

**Comment by kloczek** [comment]
> How about reading the docs. https://rpm-software-management.github.io/rpm/manual/autosetup.html

Yep .. it would be really good to have possibility to use `%autopatch -S git_am`.

**Comment by pmatilai** [comment]
Sigh. It just doesn't work that way. The stuff needs *setting up* and that is done by calling %autosetup. With -N if you want to use %autopatch separately.
