### ISSUE TITLE
Trying to rebuild RPM SRPM package on RISC-V Linux 

### ISSUE THREAD

**Issue by billasurendra** [rpm-software-management/rpm#2085]
I have installed rpm package from rpm-4.16.1.3 source code on my RISC-V Linux, after that I am trying to to rebuild rpm SRPM package withe help of **rpmbuild -ba rpm.spec** command. I am getting following errors, I am not able to find the reason and where I have to check completely I am not aware. Can anyone please give me a solution to solve the errors.

Error:
make[7]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/plugins'
make[6]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/plugins'
Making install in tests
make[6]: Entering directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/tests'
make[7]: Entering directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/tests'
make[7]: Nothing to be done for 'install-exec-am'.
make[7]: Nothing to be done for 'install-data-am'.
make[7]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/tests'
make[6]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/tests'
make[5]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3'
make[4]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3'
cp -r ./data/ testing/
for d in dev etc magic tmp var; do if [ ! -d testing/${d} ]; then mkdir testing/${d}; fi; done
for node in urandom stdin stderr stdout null full; do ln -s /dev/${node} testing/dev/${node}; done
for cf in hosts resolv.conf passwd shadow group gshadow mtab ; do [ -f /etc/${cf} ] && ln -s /etc/${cf} testing/etc/${cf}; done
make[3]: *** [Makefile:694: populate_testing] Error 1
make[3]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/tests'
make[2]: *** [Makefile:534: check-am] Error 2
make[2]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3/tests'
make[1]: *** [Makefile:1366: check-recursive] Error 1
make[1]: Leaving directory '/root/rpmbuild/BUILD/rpm-4.16.1.3'
make: *** [Makefile:1666: check] Error 2
+ cat tests/rpmtests.log
cat: can't open 'tests/rpmtests.log': No such file or directory
error: Bad exit status from /usr/var/tmp/rpm-tmp.n99IC8 (%check)

Thanks in advance
Billa Surendra

**Comment by ffesti** [comment]
Sorry for the late answer! The spec file runs the rpm test suite which needs fakechroot. It's possible that it is either not available or not working properly on RISC-V Linux. Note that the current release do use a different technology for isolating the test suite.

I am closing this as it is hanging here for too long to be a meaningful ticket. But feel free if you are still interested and there are still issues.
