### ISSUE TITLE
`%triggerin -- %{name} < %{version}-%{release}` is always triggered on upgrade

### ISSUE THREAD

**Issue by fumiyas** [rpm-software-management/rpm#209]
I want to put a scriptlet into new package for package downgrade to unapply a new feature in new package, but RPM triggers `%triggerin` scriptlet in wrong situation.

RPM SPEC for `baz-1.0-1.old.noarch.rpm` (old package):

```
Summary: Baz
Name: baz
Version: 1.0
Release: 1.old
Group: test group
License: test license
BuildArch: noarch

%description
Baz

%install
mkdir -p %{buildroot}
echo %{version}-%{release} >%{buildroot}/%{name}

%files
/%{name}
```

RPM SPEC for `baz-1.0-2.new.noarch.rpm` (new package):

```
Summary: Baz
Name: baz
Version: 1.0
Release: 2.new
Group: test group
License: test license
BuildArch: noarch

%description
Baz

%post
if [ $1 -eq 2 ]; then
  : ... Apply new feature in 1.0-2.new for upgrade ...
fi

%install
mkdir -p %{buildroot}
echo %{version}-%{release} >%{buildroot}/%{name}

%triggerin -- %{name} < 1.0-2.new
: ... Unapply new feature in 1.0-2.new for downgrade ...
echo "I'm running %%triggerin scriptlet in %{name}-%{version}-%{release}"

%files
/%{name}
```

I think RPM does NOT trigger `%triggerin -- %{name} < 1.0-2.new` above on upgrade, but RPM triggers it:

```console
# rpm -iv baz-1.0-1.old.noarch.rpm
Preparing packages...
baz-1.0-1.old.noarch
# rpm -Uv baz-1.0-2.new.noarch.rpm
Preparing packages...
baz-1.0-2.new.noarch
I'm running %triggerin scriptlet in baz-1-2.new
```

For test purpose, when I rewrite `%triggerin -- %{name} < 1.0-2.new` to `%triggerin -- %{name}`, RPM triggers it twice!!:

```console
# rpm -iv baz-1.0-1.old.noarch.rpm
Preparing packages...
baz-1.0-1.old.noarch
# rpm -Uv baz-1-2.new.noarch.rpm
Preparing packages...
baz-1.0-2.new.noarch
I'm running %triggerin scriptlet in baz-1.0-2.new
I'm running %triggerin scriptlet in baz-1.0-2.new
```

**Comment by fumiyas** [comment]
I found a same issue report:

* upgrade and downgrade scripts - Rpm-list
  * http://lists.rpm.org/pipermail/rpm-list/2009-March/000219.html

**Comment by pavlinamv** [comment]
Case `%triggerin -- %{name} < 1.0-2.new`:

RPM triggers `%triggerin -- %{name} < 1.0-2.new`. It is according to the description in the documentation [1] (_The %triggerin script is also run when your package_ (`baz-1.0-2.new`) _is installed or upgraded, should the target package_ (`baz-1.0-1.old`) _be already installed._)

Case `%triggerin -- %{name}`:

In this case more natural would be running the triggerin scriptlet only once. Note that if `baz-1-3.new
` is the same as `baz-1-2.new` (the only difference is the release number), then after upgrading from `baz-1-2.new` to  `baz-1-3.new` the %triggerin is run three times.

I think that this should be improved to call %triggerin in all cases maximally once.

[1] Fedora documentation  (but it holds generally):
https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch10s02.html

**Comment by ffesti** [comment]
As already pointed out this is indeed the expected behaviourand you can use %triggerun instead. If you do not want to rely on the arguments to the trigger script you can also check some files on disc if to determine the operation you are in.
