### ISSUE TITLE
Port rpm test-suite away from autotest

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2098]
As we're moving towards cmake based build system, having an autotools-based test-suite is a non-starter. We'll need to port the test-suite to something else by 4.20 to be able to drop autotools support then.

What the new test-system should be is not known at this point. As we're moving to cmake, ctest is a potential candidate but it's not clear to me whether it's the best or even reasonable tool for the job, considering rpm's needs. This should likely go hand in hand with #1580 , although technically that's a separate task.

**Comment by pmatilai** [comment]
As it happens, the test-suite is quite happy to run under cmake (see commit c6052a2033b6e580b90f0567f4e8bd85c8dfb13e) as autotest is surprisingly isolated from the rest of the auto-ecosystem. 

Having autoconf as a dependency in a cmake project is not ideal, but since it only participates in testing and not building, it's not that big a deal either. We'll want to get rid of autoconf eventually but it just stopped being a show-stopper issue.

**Comment by dmnks** [comment]
Yup, ctest is nice but I think it's better suited for unit testing, whereas what we need here is CLI testing. Anyways, to get an idea of how cmake looks/works, one does not need to go too far: https://github.com/sclorg/scl-utils/tree/master/tests :smile:

**Comment by dmnks** [comment]
Ugh... I stand corrected. What scl-utils uses is CMocka, not ctest. Apologies :laughing:

**Comment by pmatilai** [comment]
FWIW, ctest does seem capable of doing the kind of thing we do, it's just (again) very non-obvious from the ctest/add_test() documentation. One needs to use properties to tell it what to expect, https://stackoverflow.com/questions/19435375/simple-integration-testing-using-bash-with-cmake-and-ctest

**Comment by pmatilai** [comment]
Actually... since the autotest system integrates so nicely with cmake, there's very little point in this. 
The kind of obscene amount of time and energy as porting would take is better spent elsewhere.
Closing, we can always revisit the decision if it becomes a liability for whatever reason.

**Comment by dmnks** [comment]
Yup, was thinking along the same lines lately. It has its quirks but it works just fine, even in this new container-based setup, and migrating it away would be a colossal amount of work for little to no benefit.
