### ISSUE TITLE
rpm --verify always show Group ownership change in AIX operating system

### ISSUE THREAD

**Issue by ayappanec** [rpm-software-management/rpm#210]
Hi Guys,

By default, AIX has "root:system" ownership for files in contrast to linux where we have "root:root". And there is no group called root in AIX. So accordingly we have the defattr as "-,root,system,-" for the SPEC files in AIX. But this creates problem during rpm --verify where it always shows the Group ownership has changed. 

Looking at the code , i saw the file rpmug.c has the group "root" hardcoded in few places ( in functions 
rpmugGid,  rpmugGname & loadLibs ). I think this where i have to make the fix. 
Any help will be appreciated. Thanks.

**Comment by pmatilai** [comment]
So in AIX, gid 0 is simply called "system" instead of "root"?

**Comment by ayappanec** [comment]
Yes, 

# id
uid=0(root) gid=0(system) groups=0(system),2(bin),3(sys),7(security),8(cron),10(audit),11(lp)

**Comment by ayappanec** [comment]
I made a few changes to the code regarding this issue. One can see the commit here -->https://github.com/aixoss/rpm/commit/92500f6ea814b1d9d35f81faff53b413a6b6cb22

If this is okay, i can go for a pull request. Thanks

**Comment by ayappanec** [comment]
Hi Guys, any update here ?

**Comment by Conan-Kudo** [comment]
@ayappanec I don't have a problem with it. File a PR so that wider audience can see it.

**Comment by ayappanec** [comment]
Thanks @Conan-Kudo . Just opened a PR.

**Comment by pmatilai** [comment]
The build-side should be taken care of now as well  as of commit a56356c30625a2bef60a94d66e06eb9dd01f3c33 and a couple of intermediate dependent patches.
