### ISSUE TITLE
Create binary rpm packages in parallel? (better multiple CPU core utilization)

### ISSUE THREAD

**Issue by kanavin** [rpm-software-management/rpm#211]
Hello, I'd like to ask your opinion on the idea of creating binary rpms in parallel. It seems possible: I looked at packageBinaries() and it has a straightforward for loop with no obvious dependencies between iterations. Each iteration could be in its own thread via pthreads.

The reason I would like to do this is that we use rpm in Yocto project, and
a) making binary rpms is a part of image building process in Yocto; there's generally no common package feed, so a lot of time is spent on building rpms on the local machine.
b) some of the source packages produce a lot of very small binary packages; for instance we package glibc locales, or perl modules separately. In embedded world constraining disk space usage is important, so this has to be done. This makes rpm building really slow - several minutes or more, as it iterates over them one by one.

Opinions?

**Comment by n3npq** [comment]
Yes its quite feasible to package binary *.rpm files in parallel.

The hardest problem is choosing a framework for parallelization: OMP, or pthreads or (in RPM5) yarn.
A general framework for parallelization is needed, with queues and thread pools and output serialization etc, is needed because there are many simple loops in RPM that would benefit from being done in parallel.

FWIW: Using OMP on the rpmbuild loop would be the least intrusive but perhaps hardest to maintain (compared to plain pthreads or yarn from pigz).

(aside)
Before attempting parallelization, there are some costly "sanity checks" on file manifests in rpm build that are quadratic or worse that should be studied and fixed (at least in RPM5: I suspect there are some in RPM4 too but haven't measured recently). Run cache grind on a kernel build (which has lots of files) to see what I am talking about,

**Comment by kanavin** [comment]
NSPR includes thread pools, so I can make an experimental implementation using that:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR/Reference/Thread_Pools

Not really keen on messing about with the low-level pthreads API, it's 2017.

**Comment by n3npq** [comment]
Again ... OPENMP is the least intrusive (but perhaps the most abstract) implementation. OPENMP has queues and pools and is viable even in 2017.

I parallelized the rpm --verify loop over files a few years back using OPENMP.

Here are the top level annotations that were needed:

`#if defined(_OPENMP)
    #pragma omp parallel for private(i) reduction(+:ec)
#endif
    for (i = 0; i < (int)fc; i++) {
        int fflags = fi->fflags[i];
        rpmvf vf;
        int rc;

        /* If not querying %config, skip config files. */
        if (FF_ISSET(qva->qva_fflags, CONFIG) && FF_ISSET(fflags, CONFIG))
            continue;

        /* If not querying %doc, skip doc files. */
        if (FF_ISSET(qva->qva_fflags, DOC) && FF_ISSET(fflags, DOC))
            continue;

        /* If not verifying %ghost, skip ghost files. */
        if (!FF_ISSET(qva->qva_fflags, GHOST) && FF_ISSET(fflags, GHOST))
            continue;

        /* Gather per-file data into a carrier. */
        vf = rpmvfNew(ts, fi, i, omitMask);

        /* Verify per-file metadata. */
        rc = rpmvfVerify(vf, spew);
        if (rc)
            ec += rc;

        (void) rpmvfFree(vf);
        vf = NULL;
    }
`

OTOH, I had to rewrite lib/verify.c to add a per-file rpmvf ("verify file") structure to avoid thread races within rpmfi iterators (which are rather deficient). You may encounter similar problems traversing the packages linked list.

**Comment by simotek** [comment]
I've also just started looking into this as well.

**Comment by kanavin** [comment]
I actually have this working now. The improvements for us (the Yocto project) are quite dramatic, together with the switchover to multithreaded xz compression the process takes several times less for many bigger packages.

I had to do these things:

1) split the binary packaging loop body into its own function

2) set up the task execution and joining with appropriate data structures for handling each task

3) fix a few data races (like Jeff predicted): particularly the shared string pool structure was completely thread unsafe, and there a couple of other issues around copying header data between packages, and usage of static local variables in a couple of places.

I'm going to polish the patches, and will provide a link in a couple of days. If there's interest from upstream maintainers, I can turn it into a pull request.

**Comment by proyvind** [comment]
Best way would be to simply create a pull request from a finalized branch of yours (without unecessary amounts of WIP commits) pushed to a forked rpm repo of yours.

Then it would make sense to rather continue discuss the subject and also the implementation of.

Regardless of upstream maintainter's interest, I can rest assure you that there are others who have interest , making it wortwhile to create a PR for anyways. :)

**Comment by kanavin** [comment]
@proyvind  @simotek There you go, pull request created :)

**Comment by n3npq** [comment]
I'm definitely interested in the patches @RPM5 (even if rather uninterested in a NSPR thread pool: I believe there are better alternatives, like OMP: YMMV).

Let me look at what was needed.

**Comment by n3npq** [comment]
You need to handle the static buildtime/buildhost more carefully: the intent with build time was to have one constant and consistent timestamp everywhere during the build no matter where accessed (first access timestamps the entire build).

Similarly, the build host (which is supposed to be the FQDN of the build host) was cached to avoid (possible) DNS timeouts.

**Comment by pmatilai** [comment]
Forgot there's a also a ticket for this in addition to the PR. This is now solved as of commit 18c92e6fe76df334fed8d5f04b5f40b776daba8c, thanks for your efforts to drive this!
