### ISSUE TITLE
Backport opaque pgpDigParams to 4.18

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2114]
We should backport commit b113a9d729cef5d4f3838efd9d0d666a92846d95 to 4.18.0 prior to final, these APIs have users outside rpm itself.

**Comment by DemiMarie** [comment]
Does this change the ABI in any way?  I need to know for the Rust bindings.

**Comment by pmatilai** [comment]
Eh? Obviously it "changes" the ABI by adding new symbols. See the commit for yourself.
I hope this is not about Rust bindings duplicating struct pgpDigParams_s and thus violating the external opaqueness (I don't know if it does or not, but it wouldn't be the first case of that)

**Comment by nwalfield** [comment]
I think this commit is already part of 4.18.x:

```
$ git branch -r --contains b113a9d
  origin/HEAD -> origin/master
  origin/master
  origin/rpm-4.18.x
```

Am I missing something?

**Comment by nwalfield** [comment]
I'm pretty confident that this is done and this issue should be closed, but I don't seem to be authorized to close this issue.

**Comment by pmatilai** [comment]
Oh, indeed. Thanks.

As for the above note about Rust bindings possibly doing bad things, I was referring to whatever bindings @DemiMarie was talking about, rpm-sequoia obviously does no such thing.
