### ISSUE TITLE
Running a script before uninstall transaction

### ISSUE THREAD

**Issue by sshedi** [rpm-software-management/rpm#2116]
Hi All,

I have a requirement to run a script before an uninstall transaction.
`%pretrans` currently gets triggered for install/upgrade transactions, can we do something similar for uninstall transactions?

For example:

Main package is A, B & C are sub packages of A. B & C are dependent on A.

If I do `dnf erase -y A` or `rpm -e B C A` I want to run some commands before B and C get removed.
I can use `%preun A/B` but I have more than 10 sub packages in this spec and I don't want to add a `%preun` for each sub package and do it once before removal of any of the sub packages.

Is it possible to do so? 

--
Shedi

**Comment by sshedi** [comment]
Hi @pmatilai, can you please help me out?

**Comment by sshedi** [comment]
Thanks @ffesti  for the response. My use case is:

In our kernel spec, we have various sub packages which install modules under /lib/modules/$(uname -r) directory.

If I want to erase running kernel and it's subpackages using `rpm -e` I want to take backup of all modules directory until next boot. I don't want to lose modules of any sub package or main package in the process. So I need a way to run the backup operation before uninstall transaction begins.

**Comment by ffesti** [comment]
May be one central filetrigger could do that for all packages and kernels (obviously then narrowing it down to the running kernel).

**Comment by sshedi** [comment]
Didn't get you, can you please explain a bit more on the central file trigger part?

**Comment by sshedi** [comment]
Thanks a lot, I will give this a try.

**Comment by ffesti** [comment]
Well, as this is the upstream issue tracker I am closing this here. Feel free to ask in the discussions or still in this ticket - even if it is closed.

**Comment by sshedi** [comment]
This method works for me for the time being for my requirements.
Thanks @ffesti for the valuable inputs and for creating https://github.com/rpm-software-management/rpm/issues/2119

Have a nice time ahead.
