### ISSUE TITLE
Add pretransun and posttransun scriptlets

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#2119]
pre and post trans scriptlets are currently only supported for installations. Having uninstall variant would complete that feature set.

ToDo: List actual use cases.

**Comment by mlschroe** [comment]
Why is the header gone? Isn't it in the TE?

**Comment by ffesti** [comment]
Nope, RPM only loads the header when needed -  so save memory - so you can run updates on a 64MB machine...

**Comment by pmatilai** [comment]
So I merrily missed (forgot) that Florian had already started on this while I was on vacation, and started it all from scratch. Oh well.

A more-or-less complete patch in #2177 now.
