### ISSUE TITLE
RFE: allow rpmspec query %{SOURCE#}, %{SOURCEURL#}, %{PATCH#} and %{PATCHURL#} over query format string

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#2134]
Yeah it would be usefull to extend a bit rpmspec to be able to query spec file for tockens like %{SOURCE#}, %{SOURCEURL#}, %{PATCH#} and %{PATCHURL#}
```console
[tkloczko@devel-g2v SPECS]$ rpmspec -q xfce4-whiskermenu-plugin.spec --qf "%{SOURCE0}\n"
error: incorrect format: unknown tag: "SOURCE0"
error: incorrect format: unknown tag: "SOURCE0"
error: incorrect format: unknown tag: "SOURCE0"
[tkloczko@devel-g2v SPECS]$ rpmspec -q xfce4-whiskermenu-plugin.spec --qf "%{PATCH0}\n"
error: incorrect format: unknown tag: "PATCH0"
error: incorrect format: unknown tag: "PATCH0"
error: incorrect format: unknown tag: "PATCH0"
```

**Comment by kloczek** [comment]
Just tested %{URL}
```
[tkloczko@devel-g2v SPECS]$ rpmspec -q xfce4-whiskermenu-plugin.spec --qf "%{URL}\n"
https://gottcode.org/xfce4-whiskermenu-plugin/
https://gottcode.org/xfce4-whiskermenu-plugin/
https://gottcode.org/xfce4-whiskermenu-plugin/
```
Why that kind of query is repeated as many times as it is produces subpackages? 🤔

**Comment by kloczek** [comment]
OK .. I found that it is possible to avoud that kind of results repeated across produced subpackages by specify `--srpm` option.

**Comment by ffesti** [comment]
The error message here is correct: There is no RPM tag named `SOURCE0`. `SOURCE0` is a macro only available within the spec file. The tags are named `SOURCE` and `PATCH` and both contain a list of strings. So the right queries are:

`rpmspec -q --srpm xfce4-whiskermenu-plugin.spec --qf "[%{SOURCE}\n]"`
`rpmspec -q --srpm xfce4-whiskermenu-plugin.spec --qf "[%{PATCH}\n]"`

`rpm --querytags` lists the names of tags for `--qf` so does https://rpm-software-management.github.io/rpm/manual/tags.html

**Comment by kloczek** [comment]
OK thank you.

Just checked and looks like it is not possible to use `"[%{SOURCEURL}\n]"` or `"[%{PATCHURL\n]"`.
Can I produce that somehow? 🤔

**Comment by ffesti** [comment]
Turns out rpmspec in rpm-4.18 has an `--shell` option that allows you to query macros. But 4.18 is not yet final.

**Comment by kloczek** [comment]
How it could be used in that case? 🤔 

Generally issue is tthat `rpmbuild -bp foo.spec -D "%prep %dump"` shows `SOURCEURL#` and `PATCHURL#` data tockens however looks like it is not possoble to query about those data.

BTW when is planned 4.18 release?

**Comment by ffesti** [comment]
well, in the shell all those macros are acually present and you can use normal spec macro syntax to get them expanded.

We already have released 4.18-beta1so if there are not big issues found there will be an RC1 that is then released as final. So this summer/early autumn most likely.

**Comment by kloczek** [comment]
> well, in the shell all those macros are acually present and you can use normal spec macro syntax to get them expanded.

So it is some kind of new mode?
Why those data are not availabel for regular query without that? 🤔 

And if may I use that to ask about yet another question: I need to query sec.rpm about files archived in src.spm checksums. Is it possible to query somehow those data?

**Comment by dcermak** [comment]
> `rpmspec -q --srpm xfce4-whiskermenu-plugin.spec --qf "[%{PATCH}\n]"`

Is there a reason why the patches are listed in reverse order?

**Comment by surfacepatterns** [comment]
I just ran into this issue with `rpmspec` 4.20.0.  [Both `SOURCEURL` and `PATCHURL` are added by the `rpm` library](https://github.com/rpm-software-management/rpm/blob/6cf15a36220c78426e04fb05d7ad54bc797e350a/build/parsePreamble.cc#L332-L335), but `rpmspec` still doesn't support either.

Why was this issue closed?
