### ISSUE TITLE
Handling of tilde in the version comparison

### ISSUE THREAD

**Issue by knqyf263** [rpm-software-management/rpm#214]
Hello, please tell me about the specification of the version comparison.
Is tilde older than blank? Are the following results correct?

```
>>> import rpm
>>> rpm.labelCompare(("0", "", ""), ("0", "1", ""))
-1
>>> rpm.labelCompare(("0", "", ""), ("0", "~", ""))
1
>>> rpm.labelCompare(("0", "~", ""), ("0", "~~", ""))
1
```
Let me know if the way of the version comparison is defined elsewhere.
I searched but I could not find it.

**Comment by ignatenkobrain** [comment]
`~` makes lowering for precedent numbers, so this is expected

**Comment by knqyf263** [comment]
I understand. Thanks!
