### ISSUE TITLE
Include the Sequoia backend in 4.18

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2141]
The Sequoia backend is feature complete and passes all tests (modulo https://github.com/rpm-software-management/rpm/pull/2063).  As discussed in https://github.com/rpm-software-management/rpm/pull/2110 with @pmatilai, the only reason to not include the Sequoia as a non-default backend in 4.18 is that it doesn't implement a few deprecated functions, which would break the ABI (specifically those removed in 87c4eee816a4ddd4291cf1211c0290f3a731be73).  I will implement those functions and submit a PR.  If there are any other blockers to including the Sequoia backend, then it would be good if they were mentioned (or linked to) here.

**Comment by nwalfield** [comment]
The following MRs should probably also be added to the rpm-4.18.x (after they have been reviewed and added to master):

- [ ] https://github.com/rpm-software-management/rpm/pull/2063
- [ ] https://github.com/rpm-software-management/rpm/pull/2066

**Comment by pmatilai** [comment]
The Sequoia backend is now included in the just released 4.18.0-rc1, thanks for your efforts to make this happen! The ci part will have to wait for another release though.

**Comment by nwalfield** [comment]
Thanks!
