### ISSUE TITLE
Add support for the pgpDig family of functions to the Sequoia backend

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2142]
Although these functions are deprecated, they still need to be implemented in 4.18 to avoid breaking the ABI.

See https://github.com/rpm-software-management/rpm/issues/2141

**Comment by nwalfield** [comment]
@pmatilai: All of the functions are relatively straightforward to implement.  The only trickiness is `pgpPrtPkts`, which takes an argument `printing`, which causes the function to print out information about the parsed packets.  I [searched on github](https://github.com/search?q=pgpPrtPkts&type=Code) and it looks like most callers disable printing.  I found two exceptions in the first dozen pages of matches.  There is a command line tool [allows the user to set the printing parameter on the command line](https://github.com/svpv/altrpm/blob/3d70a2c81e1524b93a20b89a43c214f74acb259b/rpmio/tring.c#L10).  And [this python binding](https://github.com/Conan-Kudo/rpm-histfix/blob/8d1ba799231b176fd5df5503228676fc1e682786/python/rpmts-py.c#L429) prints unconditionally.

How exactly should the printing output generated by Sequoia match the current printing output?  Byte for byte?  Just some general diagnostics?  Thanks.

**Comment by nwalfield** [comment]
I just released [version 0.3](https://gitlab.com/sequoia-pgp/rpm-sequoia/-/tags/v0.3) of rpm-sequoia, which includes the necessary support.

**Comment by pmatilai** [comment]
Sorry for the late response, I was on vacation most of the July and then some.

The printing output only ever was diagnostics tool aimed at rpm developers themselves (via bug reports and otherwise), lacking tools like `sq packet dump` back then. It's certainly not worth going into great efforts, we have better tools nowadays and certainly nothing at all relies on that working. If you can trivially replicate `sq packet dump` then great, but even not giving any output at all is perfectly acceptable.

**Comment by nwalfield** [comment]
Thanks for the feedback.  I added a pretty much byte-for-byte compatible implementation, which I validated using [some test data](https://github.com/rpm-software-management/rpm/commit/7163da5a23affcfbf21f466321d93c0d8de1c56d#diff-28935cf4144a9c8502c63470f8dfaee0f833e7ceb5a632fa3949d7c83e692f4cR13).  Given that that [already exists](https://gitlab.com/sequoia-pgp/rpm-sequoia/-/commit/502f7884c755182f5315747805f5a3f7607fae91#b24749917179fb5e3e613ed2a703fcdcc6cdf9da_1259_1275), I'd prefer to either use that, or emit nothing.  Emitted `sq packet dump` style output would be a fair amount of work.

**Comment by DemiMarie** [comment]
What about ripping out the code entirely?  As @pmatilai pointed out, it serves no real purpose nowadays.

**Comment by nwalfield** [comment]
> What about ripping out the code entirely? As @pmatilai pointed out, it serves no real purpose nowadays.

I don't understand your question.  I think I said it is possible to emit nothing.  I was trying to ask @pmatilai what his preference is.

**Comment by nwalfield** [comment]
This has been merged in rpm-4.18.x and doesn't need to be merged into master.  Closing.
