### ISSUE TITLE
Documentation regarding `%bcond_with(out)` is confusing

### ISSUE THREAD

**Issue by septatrix** [rpm-software-management/rpm#2150]
Based on the second sentence in the documentation adding the `--with` switch would enable and option whereas `--without` would disable it. However later on the opposite is stated regarding the respective `%bcond_with(out)` macros:

https://github.com/rpm-software-management/rpm/blob/a7c3886b356c2f3e3e640069623d44d62beabb33/docs/manual/conditionalbuilds.md?plain=1#L49-L54

The following sentence adds to the confusion which states:

> If you want to change whether or not an option is enabled by default, only change `%bcond_with` to `%bcond_without` or vice versa.

This again pairs up "enabled by default" with `%bcond_with` and the "or not" with `%bcond_without`. So which is it now?

**Comment by pmatilai** [comment]
People are forever confused by this, no matter how much we churn the documentation.
`%bcond_with foo` adds an option to enable building with feature foo, whatever it means in a given context. So, since you need an option to build with it, it means the feature is disabled by default. And vice versa. I don't see any contradiction in the documentation.

**Comment by septatrix** [comment]
Oh that actually makes sense. I feel like the "add `--with foobar` option" implies that it is equivalent to adding it to the command line which apparently is not what it does. Maybe something in the spirit of "provides a `--with foobar` flag for building which is absent by default" would make this clearer?

Also the following sentence should probably be flipped then and maybe make it more explicit which one corresponds to which like: "If you want to change whether an option is enabled by default (`%bcond_without`) or not (`%bcond_with`) you can simply swap the macros".

**Comment by pmatilai** [comment]
> I feel like the "add --with foobar option" implies that it is equivalent to adding it to the command line which apparently is not what it does.

But that's exactly what it does. That doing so implies there's a default is kinda just a side-effect. Which is why the bcond_with/without is considered confusing. The new `%bcond` macro is supposed to be less confusing :sweat_smile:

**Comment by pmatilai** [comment]
Anyway, looking at the recently rewritten doc, there's clearly room for further improvement.

**Comment by pmatilai** [comment]
Oh, yeah. Sorry I misread. It *creates* a command-line option. *Using* that option is always up to the user.

**Comment by pmatilai** [comment]
I could've sworn I'd already explained the %bcond_with(out) behavior in the rpm docs in recent years, but between my memory and git, there's not much of a argument as to which one can be trusted. Guess I've been dreaming, and/or gotten confused with explaining this issue so many times in so many different places. The terminology of adding and enabling etc was indeed quite confusing overall, tried to make it more clear and explicit in 8ee98091b7f50cfeab61e069c1cad0c74fa567a8.
Thanks for the report!

**Comment by septatrix** [comment]
Yeah I think that clears it up pretty well, nice edit
