### ISSUE TITLE
Respect XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by hadess** [rpm-software-management/rpm#2153]
rpm looks for `.rpmmacros` in `~/` but should probably look for an `rpmmacros` file in `$HOME/.config` instead.

From https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html:
> `$XDG_CONFIG_HOME` defines the base directory relative to which user-specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.

**Comment by pmatilai** [comment]
It's not a new idea nor a bad one, the last time it was proposed the whole XDG thing was so new I remember being wary whether this new thing'll actually catch on at all :sweat_smile: The "problem" is that rpmrc and macros loading is handled as a simple `PATH` style construct which has no room for extra logic like checking one path only if the other didn't exist, but maybe it can be retrofitted there, and not a whole lot of damage would happen if we just included both in the load path.
