### ISSUE TITLE
Make rpm-sequoia part of the rpm-software-management project on GitHub

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2164]
Currently `rpm-sequoia` is maintained [over here](https://gitlab.com/sequoia-pgp/rpm-sequoia).  The main motivation for using gitlab was that it I could reuse our (Sequoia's) existing CI infrastructure.  Would it make sense to move `rpm-sequoia` to GitHub and make it part of the `rpm-software-management` project?  I think it does since 4.18 will include support for using the Sequoia backend.  Thoughts?

**Comment by pmatilai** [comment]
It'd be welcome here, certainly. A thing like this is good to have close to home, but then rpm-sequoia has two fairly obvious homes :sweat_smile: I think the question is whether it's better from rpm-sequoia maintenance POV, ie whatever works best for you.

**Comment by pmatilai** [comment]
It may well even make sense to have it as a (git) submodule/subtree/similar of rpm. I'm not deeply aware of the technical implications of those, so just a thought.

**Comment by nwalfield** [comment]
> It'd be welcome here, certainly. A thing like this is good to have close to home, but then rpm-sequoia has two fairly obvious homes sweat_smile I think the question is whether it's better from rpm-sequoia maintenance POV, ie whatever works best for you.

Indeed :).  I think rpm is the better home.  I'll investigate moving the project.

> It may well even make sense to have it as a (git) submodule/subtree/similar of rpm. I'm not deeply aware of the technical implications of those, so just a thought.

Interesting idea.  I'll take a look.

**Comment by pmatilai** [comment]
>  I think rpm is the better home. I'll investigate moving the project.

Just say "go" and I'll do the initial setup on this side.

**Comment by nwalfield** [comment]
"go" :D.

I played with the github importer yesterday and it apparently doesn't import issues or PRs.  [not-gitlab-2-github](https://github.com/piceaTech/node-gitlab-2-github) apparently does, but I haven't gotten a change to try it out yet.  On the other hand, the one open issue is easy to move by hand so it is perhaps not worth it.

**Comment by pmatilai** [comment]
Ok then. Should I leave the actual importing to you (if you want to try alternatives) or just let GH do its thing?

**Comment by nwalfield** [comment]
I think the issue history is not worth preserving at this point.  Please just use the GH importer, thanks.

**Comment by pmatilai** [comment]
Okay. There you go: https://github.com/rpm-software-management/rpm-sequoia/

Added you as the maintainer initially, just ping us if this isn't sufficient or something.

**Comment by nwalfield** [comment]
Thanks!

**Comment by nwalfield** [comment]
FYI, the migration is complete.  I've archived the [gitlab project](https://gitlab.com/sequoia-pgp/rpm-sequoia), and setup the github project including the CI.
