### ISSUE TITLE
Why are two identical NEVRA packages output after executing the rpm -q xxx command?

### ISSUE THREAD

**Issue by linux-gcc** [rpm-software-management/rpm#2171]

**Comment by pmatilai** [comment]
That's the wrong question. The question is what happened to cause this anomaly. Sounds like a reinstall aborted in the middle.

**Comment by linux-gcc** [comment]
It seems that I did encounter this problem here when the rpm command execution was interrupted during the upgrade process. But the probability of recurrence of this problem is relatively low. At that time the problem disappeared after executing rpmdb --rebuild. So, I am now wondering why such a problem occurs?
In addition, I see that the following link also mentions the NEVRA duplicate package, I don't know what scene he encountered this problem in?  I don't know why this happens?
https://github.com/rpm-software-management/rpm/issues/1792

**Comment by pmatilai** [comment]
Like said, reinstall aborted in the middle would leave such a situation behind. Ditto for -U --force in recent rpm versions. 4.17.0 had a regression wrt signal handling that might cause lesser than -KILL signals to kill rpm, that might be it. But I don't have a crystal ball.

**Comment by linux-gcc** [comment]
> Like said, reinstall aborted in the middle would leave such a situation behind. Ditto for -U --force in recent rpm versions. 4.17.0 had a regression wrt signal handling that might cause lesser than -KILL signals to kill rpm, that might be it. But I don't have a crystal ball.
If it breaks during the reinstall, will this result in two identical packages in the rpm database? At least the installation time of these two packages should be different, right?

**Comment by pmatilai** [comment]
> If it breaks during the reinstall, will this result in two identical packages in the rpm database?

Isn't that what I just said in the above, twice?

Yes, the install-time will be different. 

Fixup and move on, there's little to see here unless somebody provides a scenario where this will happen in normal usage, which would of course be a rather ugly bug.

**Comment by linux-gcc** [comment]
But what I'm encountering now is that the installation time of both packages is the same, so this problem is very confusing.
In addition, what tools can be used to parse the /var/lib/rpm/Packages information? The data parsed by the db_dump tool does not seem to be readable.

**Comment by pmatilai** [comment]
Um. Let's check the basics: what rpm version are we talking about here? /var/lib/rpm/Packages doesn't even exist in the currently supported versions, BDB support has been dropped.
What does `rpm -q --qf "%{dbinstance} %{nevra}\n" <xxx>` output, for whatever value of xxx produces this for you. And finally, does `rpmdb --rebuilddb` fix it?

**Comment by linux-gcc** [comment]
The rpm version I'm talking about is 4.11.3. I have restored the environment of this problem with rpmdb --rebuilddb, and this problem is more difficult to reproduce.

**Comment by pmatilai** [comment]
Uh, so it's an old, long since unsupported rpm version, with Berkeley DB based database.
The "usual" reason for rpmdb issues is forcefully killing rpm mid-transaction. In particular BDB backend *will* get corrupt in those situations and require --rebuilddb at least.

**Comment by linux-gcc** [comment]
First of all thanks!
Will the old version of rpm be interrupted during the rpm -U upgrade process, will it also cause this package duplication problem?
Why does --rebuilddb fix this problem? Judging from the implementation of the --rebuilddb code, only the entries without RPMTAG_NAME, RPMTAG_VERSION, RPMTAG_RELEASE, RPMTAG_BUILDTIME will be skipped when --rebuilddb BDB? Now when this problem occurs, I can query NAME, VERSION, RELEASE, BUILDTIME, but the tags of the two packages are exactly the same.
In addition, how is the new version of rpm optimized for this problem?

**Comment by pmatilai** [comment]
Interrupting an rpm operation, with the BDB backend, will cause "random" corruption of the database, the most common type of that is indexes getting out of sync. Which can manifest in any number of ways, and rebuilding the database reconstructs those indexes.

**Comment by linux-gcc** [comment]
thanks!
how is the new version of rpm optimized for this problem?

**Comment by linux-gcc** [comment]
At present, this problem should be caused by duplicate entries in all packages in the /var/lib/rpm/Name database (for example: PyYAML
  d\01\00\00\00\00\00\00d\01\00\00\00\00\00\00), however, it is not clear why the /var/lib/rpm/Name file Duplicate entry? Under what circumstances would a duplicate entry result?
In addition, this file looks relatively complete, and all the feelings should not be caused by database corruption.
@pmatilai

**Comment by pmatilai** [comment]
Like said, that version is many years out of support, and so is BDB databases. Can't help you with that, sorry.
