### ISSUE TITLE
rpm-sequoia integration missing in the cmake build

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2173]
Just realized the cmake build introduced in 8c3fb5eb01cae84aca9dac4729e1dce1def59b8c completely missed rpm-sequoia. This needs to be added.

With cmake it may well be possible to (reasonably) integrate the actual build and not just linkage, which would be nice.

**Comment by nwalfield** [comment]
(FYI, I have no cmake experience and don't have time to learn it right now.)

**Comment by pmatilai** [comment]
No worries, this wasn't targeted at you. Just a general reminder, mostly to myself.

**Comment by pmatilai** [comment]
This is kinda hilarious: I'd completely forgotten I had already added Sequoia integration in the cmake introduction commit (8c3fb5eb01cae84aca9dac4729e1dce1def59b8c). I just adjusted that to use the now included pkg-config file and we're good :sweat_smile:
