### ISSUE TITLE
RFE: Allow slicing sources list

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/rpm#2180]
Sometimes, I want to copy all of the sources into the working build directory except the first one. For example, if I have

```
Source0: %{name}-%{version}.tar.gz
Source1: %{name}.service
Source2: %{name}.sysconfig
Source3: %{name}-sysusers.conf
Source4: %{name}.1
```

I could do `cp -a %{sources} .`, but that would also copy the source tarball, which I don't want. Could you consider implementing a simple way to "slice" the sources list so I can run `cp -a sliced_sources_implementation .` and copy every Source except the first? Other ranges should be supported as well, e.g. if a package has multiple source tarballs or some other special case.

In these type of cases, I'd normally directly install these files with `install -Dp %{SOURCEn} %{buildroot}%{_foodir}/bar`, but I would prefer to be able to copy them into the build directory and refer to them by name in `%install`. This feature would eliminate the need manual source numbering (which I find cumbersome) and make specfiles more readable. It would mainly benefit packages that have more than a couple Sources.

**Comment by pmatilai** [comment]
You can always just do something like this (untested, but you'll get the idea):

```
for f in %{sources}; do
    if ${f} != %{SOURCE0} then
        cp ${f} .
    fi
done
```

**Comment by pmatilai** [comment]
Even shorter, using bash arrays:

```
read -r -a SRC <<< "%{sources}"
cp -a ${SRC[@]:1} .
```

Technically it'd be possible to add min and max parameters to the %sources and %patches macros similar to %autopatch, but the added complexity doesn't seem warranted here because there are already tools to achieve this using generally available tools.

**Comment by pmatilai** [comment]
Like noted above, there are various ways to achieve this already. If macro arrays (#1825) ever get implemented, then this might become more relevant/feasible. Closing for now though.
