### ISSUE TITLE
Packaging a fifo with rpm 4.18rc1 seems to hang

### ISSUE THREAD

**Issue by rpurdie** [rpm-software-management/rpm#2195]
With rpm 4.18rc1 we've noticed that dnf seems to hang when installing a package containing a fifo. The hang is from the new openat() call within fsmOpenat() which dnf is calling from librpm.

Changing the condition in rpmPackageFilesInstall() from:
if (!rc && fd == -1 && !S_ISLNK(fp->sb.st_mode)) {
to
if (!rc && fd == -1 && !S_ISLNK(fp->sb.st_mode) && !S_ISFIFO(fp->sb.st_mode)) {

seems to avoid it.

In the interests of full disclosure, this was reproduced in Yocto Project and was within our fakeroot emulation so it is possible there is some kind of bad interaction happening there. I've not tried to reproduce outside our fakeroot environment as yet as that isn't easy for us but I'm guessing you can test that more easily and may want to fix this before 4.18 is released if it is a real issue.

**Comment by pmatilai** [comment]
Ack, thanks for reporting!

**Comment by JetXujing** [comment]
Is it possible to open the FIFO file in non-blocking mode when it is detected?

**Comment by JetXujing** [comment]
> Is it possible to open the FIFO file in non-blocking mode when it is detected?

I find that when opening a file in non-blocking mode, -1 is returned in this case, so this is not a good idea.

**Comment by JetXujing** [comment]
I make a patch to fix it. [https://github.com/rpm-software-management/rpm/pull/2261](url)

**Comment by JetXujing** [comment]
@pmatilai PTAL
