### ISSUE TITLE
The files are not changed during the installation or uninstallation phase

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2202]
Some files are configured with %ghost and %config(noreplace) in spec. As a result, the files will not be replaced after the first installation, even if the package upgraded to a new version, which is expected. In this case, however, the new version of the file is not backed up as .rpmsave or .rpmnew or .rpmorig, which means that the new version of the file is completely lost, which does not seem reasonable.
![image](https://user-images.githubusercontent.com/43668249/191738886-c05cae81-42e1-4923-bd65-a2dbda273b2e.png)

**Comment by pmatilai** [comment]
That's what %ghost means: rpm will not touch it one way or the other.
