### ISSUE TITLE
Turn %prep into a normal build script

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#2205]
%prep is very special. It is first parsed completely and only then are `%setup` and `%patch` replaced. While these two need to do special things they should still be internal macros that are processed right when they are encountered.

One side effect of this is #1870

**Comment by pmatilai** [comment]
There are some "interesting" gotchas in this direction. I have draft patches to turn %patch and %setup into actual macros so they get processed with the normal spec readLine() machinery but as long as the macro engine cannot handle multiple options of the same type, this is a no-go. The other, ahem, specialty is that `%patch1` style syntax will forever need pre-processing to turn it into `%patch 1` basically. Until those two are eliminated, %prep will require that very special processing.

**Comment by voxik** [comment]
> `%patch1` style syntax will forever need pre-processing to turn it into `%patch 1` basically.

:eyes: This is new to me. Could there be warning that `%patch1` is obsolete?

**Comment by pmatilai** [comment]
Yes, and there will be. I actually planned one for 4.18 already but withdrew it, didn't have the energy to fight that battle just now :sweat_smile:

**Comment by ferdnyc** [comment]
Doesn't help that [the only example](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_architecture_support) (end of that section) of `%patch` usage that I can find in the Fedora Packaging Guidelines still uses `%patch0`. Seems this memo really hasn't been distributed widely enough. (News to me, as well.)

Guidelines examples can be corrected easily enough, of course, if the updated syntax is universally preferred/correct. How long has e.g. `%patch 0` worked in RPM, relative to how long `%patch0` has been legal? Is there any extreme legacy use case or whatever reason that doing the equivalent of `s/%patch([0-9]+)/%patch $1/` across the board would be a bad idea? (I'm assuming `%patch0 -p1`, like in that FPG example, is canonically supposed to be `%patch 0 -p1`?)

**Comment by ferdnyc** [comment]
> For some stats, out of 22000+ packages in Fedora, about 6300 have Patch declarations, of which roughly 3500 are still using the `%patch1` style syntax. and a whopping 25 are using other variants, including defaulting to 0 and using a combo of -P and positional arguments etc. The rest are presumably using `%autosetup` (~8700 packages)

Hey, wait... those numbers don't add up. If there are 6300 <code>Patch<var>N</var></code>-packages, and 3525 use <code>%patch<var>N</var></code> or <code>%patch <var>N</var></code>, then at most 2775 are using `%autosetup`.

Or is ~8700 the _total_ number of `%autosetup` packages, including those with no <code>Patch<var>N</var></code> declarations?

(If so, that's also depressing: After all this time, only 39.54% of packages are using `%autosetup`? I know packages using conditional patching can't use it, but at **most** that's the other 2775 with Patch declarations.)

**Comment by pmatilai** [comment]
The %autosetup number is indeed total packages using it, whether they currently have patches or not (because that's a situation that can and does change release by release). This ticket is about %prep though, lets keep the %patch discussion in #2209 (the compat info is already there btw)

**Comment by pmatilai** [comment]
(this is "handsfree" item because the aforementioned, ah, specialty prevents all sorts of interesting developements)

**Comment by jengelh** [comment]
> Hey, wait... those numbers don't add up. If there are 6300 `PatchN`-packages, and 3525 use `%patchN` or `%patch N`, then at most 2775 are using `%autosetup`.

It is possible to utilize both %autosetup and %patch (admittedly somewhat unusual):

```
%autosetup
%if 0%{?somecond}
%patch93 -R
%endif
```
