### ISSUE TITLE
Fix rpm2archive to behave like rpm2cpio (by default)

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2208]
rpm2cpio outputs to stdout, which makes it natural and efficient to use for piping: 'rpm2cpio foo.rpm|cpio -idv'. rpm2archive however behaves very differently by silently creating a .tgz in the directory of the rpm received as argument. This breaks the rule of least surprise really, especially given the long-standing behavior of rpm2cpio.

This causes head-scratching from users (me included), inefficient piping because you then need to use clumsy 'cat foo.rpm|rpm2archive|tar x' instead of 'rpm2archive foo.rpm|tar x', and it means it doesn't feel like the (almost) drop-in replacement of rpm2cpio it should be. Assuming libarchive supports cpio, we could make rpm2archive output that when called as rpm2cpio which would free us to drop rpm2cpio.c.

EDIT: initial description went too far in rpm2cpio replacement

**Comment by yangchenguang94** [comment]
can you review the code  :)

**Comment by dmnks** [comment]
I'm all for making this tool consistent with rpm2cpio (or even replacing the latter as suggested), but how do we handle the current use case of getting a file written to the current directory? Do we care at all?

**Comment by dmnks** [comment]
Answering my own question above... It's easy, we just allow printing to stdout when it's not a terminal, that's it. So when a filename is specified, a file will still be created, no behavioral change there. The associated PR implements that, just needs a bit of polish as noted in the comments there.
