### ISSUE TITLE
Document that `%patch 1` syntax is available and preferred

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#2209]
It would be nice to have the `%patch 1` syntax documented, if this is our future.

BTW I'd be also interested when this was actually introduced, so I know what is the backward compatibility.

P.S. I don't want to hijack #2205 more then I did, so creating separate ticket

**Comment by pmatilai** [comment]
Thanks for filing, seems I had already forgotten how utterly crazy the compat story was. See commit 02b8d8dccc0f045b0ebf81785cf6ad1056cf550e.

**Comment by pmatilai** [comment]
So to be clear, `%patch 1` only works as expected in rpm >= 4.18. Prior to that, it would attempt to apply patches 0 and 1. Go figure :roll_eyes: 

The most compatible form by far is `%patch -P1` which AIUI works in every rpm version out there, only it's not the preferred form for other reasons (the patch numbers should really be positional arguments, and options are, well, options)

**Comment by voxik** [comment]
Seeing your PR and out of curiosity, is there chance to get this into RHEL? That could help with adoption ...

**Comment by pmatilai** [comment]
Feel free to file an RFE on RHEL to have it considered.

**Comment by voxik** [comment]
> Feel free to file an RFE on RHEL to have it considered.

https://bugzilla.redhat.com/show_bug.cgi?id=2161293
