### ISSUE TITLE
PANDOC automake conditional not checked

### ISSUE THREAD

**Issue by stefanbidi** [rpm-software-management/rpm#2229]
I ran into a problem trying to build rpm 4.18.0 on a machine without `pandoc`. Looking at `configure.ac` and `docs/man/Makefile.am` the problems become pretty clear. There's a `AM_CONDITIONAL([PANDOC], [test "$PANDOC" != "no"])` line at the very end of `configure.ac`, but this conditional is never checked in `docs/man/Makefile.am`, `docs/Makefile.am` or really anywhere else.

**Comment by pmatilai** [comment]
Rpm is supposed to be built from release tarballs, where stuff like this is pre-generated and does not require pandoc. 

That said, this was just fixed in https://github.com/rpm-software-management/rpm/commit/1b8f7a182fe917ed5af5086d715cae529540a4d3
