### ISSUE TITLE
File dependency generation regression

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#224]
Commit 8f509d669b9ae79c86dd510c5a4bc5109f60d733 causes file dependencies to be recorded on wrong files. In rpm source directory:

```
[pmatilai@sopuli rpm]$ wget http://ftp.funet.fi/pub/mirrors/fedora.redhat.com/pub/fedora/linux/releases/25/Workstation/source/tree/Packages/p/popt-1.16-7.fc24.src.rpm
[pmatilai@sopuli rpm]$ make -j4 && make install DESTDIR=/tmp/rtest/
[...]
[pmatilai@sopuli rpm]$ rpm -qp --fileprovide $(RPM_CONFIGDIR=/tmp/rtest/usr/lib/rpm ./rpmbuild --rebuild --nocheck popt-1.16-7.fc24.src.rpm 2>&1|grep ^Wrote | head -1|awk '{print $2}')|grep libpopt
/etc/popt.d	libpopt.so.0(LIBPOPT_0)(64bit) libpopt.so.0()(64bit)
/lib64/libpopt.so.0	
/lib64/libpopt.so.0.0.0	
```

After reverting commit git revert 8f509d669b9ae79c86dd510c5a4bc5109f60d733, repeat the steps from make -j4 onwards to get the expected:
```
/lib64/libpopt.so.0	
/lib64/libpopt.so.0.0.0	libpopt.so.0(LIBPOPT_0)(64bit) libpopt.so.0()(64bit)
```

Since package generation is affected this is a blocker to any kind of public release.

**Comment by ignatenkobrain** [comment]
sorry for breaking it =(

**Comment by pmatilai** [comment]
It seems all the dependencies get collected into the first file, ie index 0. So probably the index isn't getting incremented, perhaps because of moving to callbacks (but didn't really look).
