### ISSUE TITLE
The time zone set by the %changelog does not take effect.

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2253]
1. rpmbuild -bb test.spec
```
Name: test
Epoch: 1
Version: 1.0
Release: 3
Group: Testing
License: GPL
Summary: Simple rpm demonstration.
Source0: hello-1.0.tar.gz

%description
Simple rpm demonstration.

%prep

%build

%install
touch  %{buildroot}/test-1

%files
/test-1

%changelog
* Fri May 20 10:48:39 UTC 2022 xujing <xxx@xxx.com>
- test.
```
2. rpm -qp --changes /root/rpmbuild/RPMS/aarch64/test-1.0-3.aarch64.rpm
```
[root@localhost SPECS]# rpm -qp --changes /root/rpmbuild/RPMS/aarch64/test-1.0-3.aarch64.rpm
* Fri 20 May 2022 06:48:39 PM CST xujing <xxx@xxx.com>
- test.
```
3. change time zone to `CST` about changelog as follows:
```
%changelog
* Fri May 20 10:48:39 CST 2022 xujing <xxx@xxx.com>
- test.
```
4. repeat steps 1 and 2. The result is as follows:
```
[root@localhost SPECS]# rpm -qp --changes /root/rpmbuild/RPMS/aarch64/test-1.0-3.aarch64.rpm
* Fri 20 May 2022 06:48:39 PM CST xujing <xxx@xxx.com>
- test.
```

As a result, the time zone set by the %changelog does not take effect.

**Comment by JetXujing** [comment]
I also used gdb for tracking and found that the return para value(time) of `dateToTimet` did not change under different time zone settings.
```
if (dateToTimet(date, &time, &date_words)) {
...
```

**Comment by pmatilai** [comment]
Uh. That's a good question. I assume it only expects abbreviated timezone names, as per `date` command default after which the long format changelog time was modeled (commit 57f94a582602f0353cdb17a02dc12c4461d4f32d). Seems harmless but is anything but as the abbreviations are ambiguous and people use whatever they find convenient, etc (see #739 for the long story)

**Comment by pmatilai** [comment]
Oh and BTW, this is actually a good example of the problems with the timezoned timestamp: we can't currently tell if a timezone abbreviation is valid or not. So it appears it just doesn't work.

**Comment by JetXujing** [comment]
Thank you for your reply, based on the https://github.com/rpm-software-management/rpm/pull/739 discussion, it doesn't seem necessary to revise it.
