### ISSUE TITLE
cmake + lua

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2258]
While investigating [this issue](https://github.com/rpm-software-management/rpm-sequoia/issues/20), I tried to build `rpm` as follows:

```
$ cmake -DENABLE_PYTHON=OFF ..
...
-- Checking for module 'lua'
--   Found lua, version 5.4.2
...
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/rpm/rpm/_build
$ make
...
[ 12%] Building C object rpmio/CMakeFiles/librpmio.dir/rpmlua.c.o
/tmp/rpm/rpm/rpmio/rpmlua.c:3:10: fatal error: 'lua.h' file not found
#include <lua.h>
         ^~~~~~~
1 error generated.
make[2]: *** [rpmio/CMakeFiles/librpmio.dir/build.make:355: rpmio/CMakeFiles/librpmio.dir/rpmlua.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:968: rpmio/CMakeFiles/librpmio.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

This is on a Debian stable system.

This looks like [the error described here](https://stackoverflow.com/questions/7210154/unable-to-find-lua-headers-with-find-package-in-cmake), but I don't know anything about `cmake`.  Perhaps you have a quick fix (but I'll keep investigating).

**Comment by pmatilai** [comment]
Does #2260 fix it for you?

In addition, there's a known issue of Debian shipping multiple versions of Lua, with the version in the pkg-config name, and at least the autotools build typically failed to find any. You seem to be past that, so either "lua" works on Debian nowadays, or you already figured the workaround: edit "pkg_check_modules(LUA lua REQUIRED)" to look for "lua5.4" or so instead of "lua" (we should probably make the lua name a settable variable or something)

**Comment by nwalfield** [comment]
I get further, but I still get a complaint about lua.h being missing:

```
[ 40%] Building C object lib/CMakeFiles/librpm.dir/rpmscript.c.o
/tmp/rpm/rpm/lib/rpmscript.c:7:10: fatal error: 'lua.h' file not found
#include <lua.h>
         ^~~~~~~
1 error generated.
make[2]: *** [lib/CMakeFiles/librpm.dir/build.make:620: lib/CMakeFiles/librpm.dir/rpmscript.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:995: lib/CMakeFiles/librpm.dir/all] Error 2
```

**Comment by pmatilai** [comment]
Doh, there was a copy-paste error, referring to librpmio does not help getting it included in librpm :facepalm: Pushed a fix for that now.

**Comment by nwalfield** [comment]
That solves the lua problem for me.  make check now fails:

```
...
Built target populate_testing
Built target librpmio
Scanning dependencies of target rpmpgppubkeyfingerprint
Building C object tests/CMakeFiles/rpmpgppubkeyfingerprint.dir/rpmpgppubkeyfingerprint.c.o
Linking C executable rpmpgppubkeyfingerprint
Built target rpmpgppubkeyfingerprint
Scanning dependencies of target rpmpgpcheck
Building C object tests/CMakeFiles/rpmpgpcheck.dir/rpmpgpcheck.c.o
Linking C executable rpmpgpcheck
Built target rpmpgpcheck
Scanning dependencies of target check
/bin/sh: 1: ./rpmtests: not found
make[3]: *** [tests/CMakeFiles/check.dir/build.make:78: tests/CMakeFiles/check] Error 127
```

**Comment by pmatilai** [comment]
Also, "make check VERBOSE=1" should give some clues. In particular, this is how the rpmtests script gets generated:

> Scanning dependencies of target check
make[3]: Leaving directory '/root/rpm/_build'
make  -f tests/CMakeFiles/check.dir/build.make tests/CMakeFiles/check.dir/build
make[3]: Entering directory '/root/rpm/_build'
Generating rpmtests
cd /root/rpm/_build/tests && /usr/bin/autom4te --language=autotest -I /root/rpm/tests -o rpmtests rpmtests.at
cd /root/rpm/_build/tests && ./rpmtests -j8
