### ISSUE TITLE
rpmbuild fails when no default value is available for %_smp_build_ncpus

### ISSUE THREAD

**Issue by jordansissel** [rpm-software-management/rpm#2265]
I recently installed Fedora 36 which comes with rpm 4.17.1 and noticed that `rpmbuild` invocations that were working previously now no longer work. (I'll figure out the versions where it /does/ work soon)

A short example is this:

```
# This works
% rpmbuild --quiet --rebuild example-1.0-1.src.rpm

# This does not
% rpmbuild --quiet --rebuild --target whatever example-1.0-1.src.rpm
Building target platforms: whatever
Building for target whatever
xargs: invalid number "%{_smp_build_ncpus}" for -P option
Try 'xargs --help' for more information.
xargs: invalid number "%{_smp_build_ncpus}" for -P option
Try 'xargs --help' for more information.
error: Bad exit status from /var/tmp/rpm-tmp.VlUBaS (%install)
```

Now, the "whatever" target is made-up nonsense, of course, but this failure is new-ish and seems to be that this fails when an unknown platform is targeted.

I'm not an expert in the rpm codebase, but https://github.com/rpm-software-management/rpm/pull/665 might be related. The review comment[1] seems on point for this issue. [1] https://github.com/rpm-software-management/rpm/pull/665#discussion_r275746585

Related issues:
* https://bugzilla.redhat.com/show_bug.cgi?id=1919148
* https://github.com/jordansissel/fpm/issues/1956

**Comment by pmatilai** [comment]
Right, thanks for reporting / reminding us about this.

Looking at it again, the simple and correct fix is to move these definitions from platform to the main macros file: there used to be a reason for it being in the platform macros as it dependend on external, platform dependent tooling, but for many years now it's all been backed up by rpm internal macros which are available on all platforms.
