### ISSUE TITLE
rpmkeys type confusion fails when using the sequoia backend

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2272]
When running the test suite (rpm-4.17.0-alpha-674-ge8e2a121b) using the sequoia backend, I see the following failure:

```
$ make check
...
281: rpmkeys type confusion                          FAILED (rpmsigdig.at:631)
...
ERROR: 472 tests were run,
6 failed (5 expected failures).
75 tests were skipped.
```

**Comment by nwalfield** [comment]
The test is much too strict.  Using the Sequoia backend, this fails as follows:

```
$ ./rpmkeys --import ./tests/testing/data/keys/type-confusion.asc
warning: Certificate 4344591E1964C5FC:
  Policy rejects subkey 185E6146F00650F8: No binding signature at time 2022-11-09T15:08:19Z
```

**Comment by nwalfield** [comment]
This issue would have been caught if the Sequoia backend were tested in CI.

As per https://github.com/rpm-software-management/rpm/issues/2065#issuecomment-1237733334:

> what I'm currently thinking is that once the dust settles a bit, we'll just switch the Sequoia to be the default on CI 

Has the dust settled?  As the sequoia backend will be the default in Fedora 38, is it time to use it in CI?

**Comment by DemiMarie** [comment]
> The test is much too strict. Using the Sequoia backend, this fails as follows:
> 
> ```
> $ ./rpmkeys --import ./tests/testing/data/keys/type-confusion.asc
> warning: Certificate 4344591E1964C5FC:
>   Policy rejects subkey 185E6146F00650F8: No binding signature at time 2022-11-09T15:08:19Z
> ```

Sorry about that.  Without the fix the internal backend segfaults IIRC.

**Comment by nwalfield** [comment]
With #2274 and https://github.com/rpm-software-management/rpm/issues/2269#issuecomment-1308825583, the test is correctly skipped and all of the other tests pass:

```
471 tests behaved as expected.
76 tests were skipped.
Built target check
```
