### ISSUE TITLE
The patch file is lost in src.rpm in some cases.

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2282]
The spec file may contain the following information:
![image](https://user-images.githubusercontent.com/43668249/203216404-eb0ea2ea-b068-48ff-9196-c70427a71cb6.png)

if "xxx" is not defined, the aaa.patch will not be packed into src.rpm. When I download the src.rpm and build in an environment where "xxx" is defined, the build fails, and a message is displayed indicating that there is no aaa.patch.

I think it's reasonable that thesrc.rpm should pack all the files in the SOURCES directory.

**Comment by pmatilai** [comment]
This is a feature. The way the spec parser works, rpm will never see the Patch line at all, just like `#if 0` prevents a compiler from looking at what's inside.

Proper packaging requires that patch and source declarations are unconditional, if conditionals are needed those need to be used when applying.
