### ISSUE TITLE
Add comprehensive information about `%name-%version-%release` comparisons to /docs/manual/spec.md

### ISSUE THREAD

**Issue by Olf0** [rpm-software-management/rpm#2307]
Please add comprehensive information about the details of `%name-%version-%release` comparisons / evaluations to [/docs/manual/spec.md](https://github.com/rpm-software-management/rpm/blob/master/docs/manual/spec.md), as (once publicly) provided at [www.redhat.com/archives/rpm-list/2003-January/msg00182.html](https://www.redhat.com/archives/rpm-list/2003-January/msg00182.html), now (moved behind login-wall) presumably available at [listman.redhat.com/mailman/private/rpm-list/2003-January/msg00182.html](https://listman.redhat.com/mailman/private/rpm-list/2003-January/msg00182.html) (unfortunately not for me, any longer).

I would try to condense this e-mail into one to three paragraphs suited for [/docs/manual/spec.md](https://github.com/rpm-software-management/rpm/blob/master/docs/manual/spec.md), if its content is made available here; plus any relevant follow-up mails in that thread, if there are any.

**Comment by Olf0** [comment]
Well, apparently by what it fundamentally addresses.

But I provided a specific pointer to an extant description (which is far better than "read the source code", AFAIR) and a offer to translate it into something being worth to be called "documentation".
Hence one might argue that this issue supersedes #2102.

Nevertheless, the crucial point is to make this essential piece of information available again.  Neither marking an issue as duplicate or superseded is a step towards this goal.

Or to say it more bluntly: It is obviously and unambiguously detrimental for using RPM that such central information was extremely hard to find in the first place and has become hidden behind a login wall many months ago.
Sigh!

**Comment by pmatilai** [comment]
An article from 2003 would be so far out of date as to be closer to misleading than genuinely useful. There's no argument about the need for documentation, but @xsuchy is right, this is simply a dupe.
