### ISSUE TITLE
cannot use lua libraries in rpm4.14 and later

### ISSUE THREAD

**Issue by hramrach** [rpm-software-management/rpm#2309]
lua5.1 -l 'foobar'
lua5.1: module 'foobar' not found:
	no field package.preload['foobar']
	no file './foobar.lua'
	no file '/usr/local/share/lua/5.1/foobar.lua'
	no file '/usr/local/share/lua/5.1/foobar/init.lua'
	no file '/usr/local/lib/lua/5.1/foobar.lua'
	no file '/usr/local/lib/lua/5.1/foobar/init.lua'
	no file '/usr/share/lua/5.1/foobar.lua'
	no file '/usr/share/lua/5.1/foobar/init.lua'
	no file './foobar.so'
	no file '/usr/local/lib/lua/5.1/foobar.so'
	no file '/usr/lib64/lua/5.1/foobar.so'
	no file rpm --version 
RPM version 4.11.2
 '/usr/local/lib/lua/5.1/loadall.so'
rpm -E "%{lua: require('foobar')}"
error: lua script failed: [string "<lua>"]:1: module 'foobar' not found:
	no field package.preload['foobar']
	no file './foobar.lua'
	no file '/usr/local/share/lua/5.1/foobar.lua'
	no file '/usr/local/share/lua/5.1/foobar/init.lua'
	no file '/usr/local/lib/lua/5.1/foobar.lua'
	no file '/usr/local/lib/lua/5.1/foobar/init.lua'
	no file '/usr/share/lua/5.1/foobar.lua'
	no file '/usr/share/lua/5.1/foobar/init.lua'
	no file './foobar.so'
	no file '/usr/local/lib/lua/5.1/foobar.so'
	no file '/usr/lib64/lua/5.1/foobar.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

lua5.3 -l foobar
lua5.3: module 'foobar' not found:
	no field package.preload['foobar']
	no file '/usr/share/lua/5.3/foobar.lua'
	no file '/usr/share/lua/5.3/foobar/init.lua'
	no file '/usr/lib64/lua/5.3/foobar.lua'
	no file '/usr/lib64/lua/5.3/foobar/init.lua'
	no file './foobar.lua'
	no file './foobar/init.lua'
	no file '/usr/lib64/lua/5.3/foobar.so'
	no file '/usr/lib64/lua/5.3/loadall.so'
	no file './foobar.so'
rpm --version 
RPM version 4.14.3
 rpm -E "%{lua: require('foobar')}"
error: lua script failed: [string "<lua>"]:1: module 'foobar' not found:
	no field package.preload['foobar']
	no file '/usr/lib/rpm//lua/foobar.lua'
	no file '/usr/lib64/lua/5.3/foobar.so'
	no file '/usr/lib64/lua/5.3/loadall.so'
	no file './foobar.so'

lua5.4 -l foobar
lua5.4: module 'foobar' not found:
	no field package.preload['foobar']
	no file '/usr/share/lua/5.4/foobar.lua'
	no file '/usr/share/lua/5.4/foobar/init.lua'
	no file '/usr/lib64/lua/5.4/foobar.lua'
	no file '/usr/lib64/lua/5.4/foobar/init.lua'
	no file './foobar.lua'
	no file './foobar/init.lua'
	no file '/usr/lib64/lua/5.4/foobar.so'
	no file '/usr/lib64/lua/5.4/loadall.so'
	no file './foobar.so'
 rpm --version
RPM version 4.17.1.1
 rpm -E "%{lua: require('foobar')}"
error: lua script failed: [string "<lua>"]:1: module 'foobar' not found:
	no field package.preload['foobar']
	no file '/usr/lib/rpm//lua/foobar.lua'
	no file '/usr/lib64/lua/5.4/foobar.so'
	no file '/usr/lib64/lua/5.4/loadall.so'
	no file './foobar.so'

Note that the C Lua modules are searched but the native modules are not.

It's fine to prepend /usr/lib/rpm//lua/ to lua search path but it's not fine to replace it.

That means that Lua libraries must be duplicated for use with rpm.

**Comment by Conan-Kudo** [comment]
This is by design, as RPM Lua is not _exactly_ a pristine Lua environment and some stuff would conflict with what RPM Lua provides.

**Comment by hramrach** [comment]
What 'stuff' would conflict, specifically?

Why does it not conflict when it's written in C but it does conflict when written in Lua?

**Comment by pmatilai** [comment]
The real bug here may well be that we're looking for the C libraries.
Lua in rpm is not your average Lua interpreter, and we don't want people pulling in arbitrary extensions that may do whoknowswhat.

**Comment by hramrach** [comment]
What is 'average lua interpreter'? 

It's based on liblua, it's the same interpreter as any other.

**Comment by Conan-Kudo** [comment]
We have custom RPM Lua API extensions in the interpreter environment, and custom versions of some modules integrated as well. If this worked before, that was almost certainly a mistake and it shouldn't.

**Comment by Conan-Kudo** [comment]
Also RPM Lua can be used for scriptlets at install-time, and we have no safe way to handle dependencies for that right now (@michel-slm is working on Lua module packaging and dependency generators, which may allow us to revisit that eventually).

**Comment by hramrach** [comment]
Sorry, I don't get what the problem is.

You can explicitly load a lua module, and then it will be searched in the load path.

If you exclude the standard search path it means that already installed lua libraries cannot be explicitly loaded when lua code is running in rpm. That sounds like a bug.

These are not loaded automatically, it requires explicit user action.

Also if the user depends on lua libraries they can add the appropriate dependencies that pull them in on their distribution in question.

**Comment by Conan-Kudo** [comment]
Crashing the RPM process and potentially bricking someone's installation is not acceptable, and that's what would happen if someone screwed up this without safeguards in place.

**Comment by pmatilai** [comment]
Preventing people from using arbitrary libraries from within rpm is exactly the thing we want to prevent, and which is why the path is the way it is. Seems we've missed the C library path though.

**Comment by hramrach** [comment]
How would the rpm process crash?

It requires that a user script loads a library, it cannot crash based on the sole existence of a library.

The load path can be altered from the script anyway, it's just tedious.

Meaning that this does not in practice prevent use of libraries, only makes the use of lua in rpm needlessly tedious.

Sure, excluding '.' from the load path may make sense, but that's about it.

**Comment by pmatilai** [comment]
Yes, and loading is what you'd like to do. Which is exactly the problem.
There are various safeguards to protect the rpm Lua environment in place already, many more needing to be added.

**Comment by Conan-Kudo** [comment]
@hramrach the RPM Lua environment is an in-process interpreter. If it breaks in an unrecoverable way, librpm dies, which kills the whole transaction. It was never intended to be extensible at runtime for this reason.

**Comment by hramrach** [comment]
And what use is lua exactly if you cannot load any libraries?

The language is designed for embedding and is very simplistic which means that it relies on libraries for pretty much anything.

**Comment by hramrach** [comment]
Also it's bad design on RPM's part that when rpm crashes the whole transaction is lost.

Have you ever heard of power outage?

**Comment by pmatilai** [comment]
Yes, it's a poor design from the nineties. It's getting a little out of scope as well.

Rpm ships with the extensions that are expected to be needed in the very specific context of rpm already. Now, if you want something constructive to come out of this, you could explain what it is that you're trying to do that needs something more.

**Comment by hramrach** [comment]
I want to use lua in a rpm spec file.

lua provides very limited capabilities out of the box so I need libraries to do pretty much anything.

With this limited search path I cannot use libraries that are already provided by the system.

**Comment by pmatilai** [comment]
That doesn't answer the question: what are you trying to do?

**Comment by hramrach** [comment]
The problem is more general, though.

Lua in itself provides very little functionality without any libraries.

**Comment by hramrach** [comment]
Like rpm.execute is 4.15+ so I cannot rely on that, need a library.

Capturing the output is not supported at all, need a library.

The lua standard library handles execution by shell but not quoting of arguments (for security of rpm !!!), need a library.

**Comment by DemiMarie** [comment]
For libraries written in Lua, you could copy the code into your spec file.

**Comment by pmatilai** [comment]
The posix module is there since forever and lets you handle that kind of stuff. Also, for capturing output you can just use rpm macro functionality, which is usable from Lua.

**Comment by pmatilai** [comment]
Also, in specs, macros (including Lua) are just a fancy text pre-processor. That puts the expectations into some kind of context.

**Comment by hramrach** [comment]
Right, you can cut & paste the library. And then there is a bug and you need to update all your spec files. Scales really well.

The execute is not there forever:

```
execute(path [, arg1 [,…])
Execute an external command (rpm >= 4.15.0) This is handy for executing external helper commands without depending on the shell. The first argument is the command to execute, followed by optional number of arguments to pass to the command.
```

And capturing output with rpm macro functionality does not handle parameter quoting either, you still need some library for that.

**Comment by pmatilai** [comment]
You still haven't explained what you're actually trying to do, "use lua" or "use library x" doesn't explain anything at all.

What is the problem you are solving with these tools? Like said, rpm macros are nothing but a fancy text pre-processor. Complicated programming doesn't really belong there in the first place.

**Comment by DemiMarie** [comment]
> You still haven't explained what you're actually trying to do, "use lua" or "use library x" doesn't explain anything at all.
> 
> What is the problem you are solving with these tools? Like said, rpm macros are nothing but a fancy text pre-processor. Complicated programming doesn't really belong there in the first place.

In macros I agree, but in scriplets one might well want to be able to e.g. edit complex file formats.
