### ISSUE TITLE
Make rpm fail to install unverified packages

### ISSUE THREAD

**Issue by vityafx** [rpm-software-management/rpm#231]
How can I change `librpm` code so that it will fail to install packages without verified signature?

I have tried to do so in `lib/package.c`, `lib/signature.c`, `rpmio/rpmpgp.c` but it needs a lot of time to understand the code (for me). Could anyone help?

**Comment by ignatenkobrain** [comment]
`VERIFY_SIGNATURE` ?

**Comment by vityafx** [comment]
@ignatenkobrain Could you complete your comment please?

**Comment by pmatilai** [comment]
Configurable signature policies are planned for rpm 4.14, just not there yet.

**Comment by vityafx** [comment]
@pmatilai Are there any plans to release it soon?

**Comment by pmatilai** [comment]
When it's ready...

**Comment by pmatilai** [comment]
This is an issue tracker and there's no actual issue here, just a question. See http://rpm.org/community.html for the appropriate forums for questions and discussion.

**Comment by Ambtripa** [comment]
If the code committed? if not, is there a patch available?
