### ISSUE TITLE
Multiple builds via the BuildArch tag do not work

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#2319]
The documentation is somewhat lacking, but it seems to me that once upon a time specifying multiple elements in BuildArch resulted in multiple builds being done (if the buildarch is deemed compatible).

I think this was broken in 2001 with commit c3835f5ca0e3ea856213a22367233e148ea26550, which changed the code
to always free the BASpecs array and returning the first element. After the change `spec->recursing` will always be set and the code in build.c that would loop over BASpecs is never used.

Should this be made to work again or should we drop support for multiple builds?

**Comment by mlschroe** [comment]
Also, BuildArch seems to only set %_target_cpu. Shouldn't it also change the optflags?

**Comment by pmatilai** [comment]
I really don't remember the behavior from those days, no strong opinion here. Other than agreeing on "it seems pretty broken in many places" that is.

As for optflags - yes, and BuildArch should arguably also (re)load platform macros while at it.

**Comment by ffesti** [comment]
I also don't have too strong of an opinion on that. Only the comment that most build systems may be pretty surprised if suddenly packages from more than one build arch show up. May be we should keep things as they are and just clean up the code.

**Comment by ffesti** [comment]
So I think going back to the old behaviour is just not worth the trouble - even if it may be easy to do code wise. So all that's left is cleaning up the code a little bit. Not keeping a ticket open for stuff like that - otherwise we had tickets for each line of RPM code...
