### ISSUE TITLE
transfiletriggerpostun doesn't work when rpms are removed.

### ISSUE THREAD

**Issue by xiacunshun** [rpm-software-management/rpm#2324]
I found this problem when I uninstall rpms.
https://github.com/systemd/systemd/issues/25682

A similar issue:
https://github.com/rpm-software-management/rpm/commit/f6521c50f6836374a0f7995f8f393aaf36e178ea

**Comment by xiacunshun** [comment]
I got some clues as following:
in lib/rpmtriggers.c:109
`strcmp(prefix, rpmdsN(ds)) == 0`

The  rpmdsN(ds) cannot get the right prefix matching the one we need ( /usr/lib/systemd/system/ ) due to the wrong value ds->N[ds->I] returns.

**Comment by xiacunshun** [comment]
<img width="578" alt="企业微信截图_49269d76-90f1-4c07-b474-b3f026c84dea" src="https://user-images.githubusercontent.com/7437321/207760024-9ed2b111-7df0-4389-98f9-91167ad79e65.png">

**Comment by pmatilai** [comment]
It'd be really helpful if you can turn this into a minimal reproducer that we could then include in the test-suite.

**Comment by xiacunshun** [comment]
> It'd be really helpful if you can turn this into a minimal reproducer that we could then include in the test-suite.

To reproduce:
1.dnf install nghttp2 -y
2.systemctl status nghttpx (inactive)
3.rpm -e nghttp2
4.systemctl status nghttpx (still inactive, but warns that you need to reload daemon).

If the trigger worked, the nghttpx.service will be removed neither.

**Comment by pmatilai** [comment]
And what distro is that on?

**Comment by xiacunshun** [comment]
> And what distro is that on?
> 
> (this is a reproducer, which is a necessary first step, but it's not the kind of minimal reproducer that we'd need for the test-suite)

I tried fedora 37，but the filetriggerpostun is also not called.
I think there's something wrong here.

**Comment by pmatilai** [comment]
I'm not question the existence of a bug, but we need to know the conditions to reproduce it. A bug may exhibit on distro X but not on X+1, for a whole variety of reasons.

**Comment by xiacunshun** [comment]
> I'm not question the existence of a bug, but we need to know the conditions to reproduce it. A bug may exhibit on distro X but not on X+1, for a whole variety of reasons.

ok. I got the iso from https://getfedora.org/. You can download that and use the steps I mentioned above to reproduce.
Although the result is a little different from what I see on OpenCloudOS, the filetriggers of systemd are missing too.

Don't forget to add `-vv` after `rpm -e`, I missed that.
thx.

**Comment by xiacunshun** [comment]
I try to fix this by putting `rpmdsNext` in a circling, and it seems to work.

`diff -uprN rpm-4.17.1.orig/lib/rpmtriggers.c rpm-4.17.1/lib/rpmtriggers.c
--- rpm-4.17.1.orig/lib/rpmtriggers.c   2022-12-16 16:40:08.442304317 +0800
+++ rpm-4.17.1/lib/rpmtriggers.c        2022-12-16 22:53:23.272284885 +0800
@@ -105,15 +105,16 @@ static void addTriggers(rpmts ts, Header
     rpmds triggers = rpmdsNew(trigH, RPMTAG_TRANSFILETRIGGERNAME, 0);
 
     while ((ds = rpmdsFilterTi(triggers, tix))) {
-       if ((rpmdsNext(ds) >= 0) && (rpmdsFlags(ds) & filter) &&
-               strcmp(prefix, rpmdsN(ds)) == 0) {
-           struct rpmtd_s priorities;
+       while (rpmdsNext(ds) >= 0) {
+            if ((rpmdsFlags(ds) & filter) && strcmp(prefix, rpmdsN(ds)) == 0) {
+               struct rpmtd_s priorities;
 
-           if (headerGet(trigH, RPMTAG_TRANSFILETRIGGERPRIORITIES,
+               if (headerGet(trigH, RPMTAG_TRANSFILETRIGGERPRIORITIES,
                        &priorities, HEADERGET_MINMEM)) {
-               rpmtdSetIndex(&priorities, tix);
-               rpmtriggersAdd(ts->trigs2run, headerGetInstance(trigH),
+                   rpmtdSetIndex(&priorities, tix);
+                   rpmtriggersAdd(ts->trigs2run, headerGetInstance(trigH),
                                tix, *rpmtdGetUint32(&priorities));
+                }
            }
        }
        rpmdsFree(ds);`

**Comment by xiacunshun** [comment]
I try to fix this by putting rpmdsNext into a loop, and it seems to work.
But I don't know whether it's the right way.

**Comment by xiacunshun** [comment]
Hi, is there any progress? 
I am now using transfiletriggerun + filetriggerpostun to work around.
`
%transfiletriggerun -- /usr/lib/systemd/system /etc/systemd/system
if test -d "/run/systemd/system"; then
    mkdir -p "%{_localstatedir}/lib/rpm-state/systemd"
    touch "%{_localstatedir}/lib/rpm-state/systemd/needs-reload"
fi

%filetriggerpostun -P 1000100 -- /usr/lib/systemd/system /etc/systemd/system
if test -f "%{_localstatedir}/lib/rpm-state/systemd/needs-reload"; then
    rm -rf "%{_localstatedir}/lib/rpm-state/systemd"
    /usr/lib/systemd/systemd-update-helper system-reload || :
fi
`

**Comment by xiacunshun** [comment]
@pmatilai

**Comment by pmatilai** [comment]
There are 200 tickets in the system, more in distro bugzillas and so on. It will get looked at, in time. In particular, we don't look at bugs during vacation and holidays.

**Comment by xiacunshun** [comment]
> There are 200 tickets in the system, more in distro bugzillas and so on. It will get looked at, in time. In particular, we don't look at bugs during vacation and holidays.

Sorry, I forgot that. =.=

**Comment by pmatilai** [comment]
It's hardly a pity if a bug was already fixed. 

Moral of the story: always test with upstream version to see if something is already fixed, and if reporting an issue on older version, always report the version used because here people will assume the git master unless otherwise stated.
