### ISSUE TITLE
Regression: space handling in %setup

### ISSUE THREAD

**Issue by manfredsc** [rpm-software-management/rpm#2335]
In a package, I have a source file with spaces in it:

Source:         Mobile Atlas Creator %{version}.zip
...
%prep
%setup -q -c -n mobac

This used to work fine, and resulted in:
[   76s] + cd /home/abuild/rpmbuild/BUILD
[   76s] + rm -rf mobac
[   76s] + /usr/bin/mkdir -p mobac
[   76s] + cd mobac
[   76s] + /usr/bin/unzip -qq '/home/abuild/rpmbuild/SOURCES/Mobile Atlas Creator 2.3.0.zip'
[   77s] + STATUS=0

But since rpm 4.18, a new tool rpmuncompress is used. This now gives:
[   38s] + cd /home/abuild/rpmbuild/BUILD
[   38s] + rm -rf mobac
[   38s] + /usr/bin/mkdir -p mobac
[   38s] + cd mobac
[   38s] + /usr/lib/rpm/rpmuncompress -x /home/abuild/rpmbuild/SOURCES/Mobile Atlas Creator 2.3.0.zip
[   38s] error: File /home/abuild/rpmbuild/SOURCES/Mobile: No such file or directory
[   38s] error: Bad exit status from /var/tmp/rpm-tmp.SgyFCX (%prep)

So it seems some argument quoting for rpmuncompress is missing?

**Comment by pmatilai** [comment]
Ack, thanks for reporting.
