### ISSUE TITLE
Add optional Class: attribute into Preamble

### ISSUE THREAD

**Issue by clime** [rpm-software-management/rpm#236]
Hello,

right now, spec files do not have any 'type' identifier, which means, they all need to be treated the same way in a distribution. If they contained a class specifier, there could be two (or more) types of packages, each with a different set of requirements given to them by a distribution standard (e.g. Fedora Packaging Guidelines for Fedora distribution). This might be very useful because with containers, the rpm packages can be constrained less heavily in what they can do in the system. At the same time, it will be useful to mark those packages as having those extended capabilities so that user (and tooling like a package manager) knows what to expect from them. That's why this information should be ideally stored in rpm header to be easily accessible to everyone.

**Comment by ignatenkobrain** [comment]
Why not to add `Provides: rpm(class) = container`?

**Comment by ignatenkobrain** [comment]
Some kind of this has been discussed in #107.. Basically having `Class` or how you name does not make sense for RPM until it should be handling it differently (which doesn't make sense for RPM from simple POV).. In theory it could start changing RPM behaviour like stop adding debuginfo packages and add some different subpackage... But you really need to describe how is that should be useful.

**Comment by Conan-Kudo** [comment]
@clime Also, you could just reuse the `Group:` tag for this purpose. I'm not sure why you need new metadata tags...

**Comment by clime** [comment]
I've made a prototype of what I had in mind: https://pagure.io/lamp and it is just a normal package, in the end. It probably will be able to pass the Fedora standard package review process so the Class attribute is probably not needed.

**Comment by pmatilai** [comment]
Yeah, Group already exists and yet nobody these days sees it as serving anything useful, so adding another classifier tag doesn't seem that productive.
