### ISSUE TITLE
RFE: Additional cli verify options, specifically for config files

### ISSUE THREAD

**Issue by jmakin-godaddy** [rpm-software-management/rpm#2375]
To complement the following verify options:
[--nolinkto] [--nofiledigest] [--nosize] [--nouser] [--nogroup] [--nomtime] [--nomode] [--nordev] [--nocaps]
I would like to suggest the following new options:
[--noconfiglinkto] [--noconfigfiledigest] [--noconfigsize] [--noconfiguser] [--noconfiggroup] [--noconfigmtime] [--noconfigmode] [--noconfigrdev] [--noconfigcaps]

The implementation should be fairly self explanatory, if --noconfigfiledigest is requested, the intended behaviour should be that the filedigest check is not performed for files that are marked as %config

The rationale:
rpm -Va is a quick and powerful way to check that a system is in a good/healthy state.
I wish to use it for system monitoring checks, but the command currently produces too much output to be feasible.
My intended invocation would be rpm -Va --nomtime --noconfigfiledigest --noconfigsize.

I have implemented similar functionality to the above in perl and python scripts and believe this would be a beneficial addition to the rpm cli tool

**Comment by pmatilai** [comment]
Sorry but no, rpm has way too many cli switches as it is.

You can use 'rpm -Va --noconfig' to ignore config files entirely. For finer control over which files to verify, the rpm verify functionality is available in the Python bindings.
