### ISSUE TITLE
Failed to delete files during the rmbuild execution

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2380]
When Non-privileged user was used to build the "rpm" package, the file deletion failed during the final rmbuild cleanup phase. The problem is caused by the lack of write permission on the testing directory.
```
...
[ 209s] Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/abuild/rpmbuild/BUILDROOT/rpm-4.18.0-1.oe1.x86_64
[ 209s] Wrote: /home/abuild/rpmbuild/SRPMS/rpm-4.18.0-1.oe1.src.rpm
[ 209s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/rpm-plugin-systemd-inhibit-4.18.0-1.oe1.x86_64.rpm
[ 209s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/rpm-build-4.18.0-1.oe1.x86_64.rpm
[ 209s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/python3-rpm-4.18.0-1.oe1.x86_64.rpm
[ 209s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/rpm-devel-4.18.0-1.oe1.x86_64.rpm
[ 209s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/rpm-libs-4.18.0-1.oe1.x86_64.rpm
[ 209s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/rpm-4.18.0-1.oe1.x86_64.rpm
[ 209s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/rpm-debugsource-4.18.0-1.oe1.x86_64.rpm
[ 210s] Wrote: /home/abuild/rpmbuild/RPMS/x86_64/rpm-debuginfo-4.18.0-1.oe1.x86_64.rpm
[ 210s] Wrote: /home/abuild/rpmbuild/RPMS/noarch/rpm-help-4.18.0-1.oe1.noarch.rpm
[ 210s] Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.2fUx5e
[ 210s] + umask 022
[ 210s] + cd /home/abuild/rpmbuild/BUILD
[ 210s] + cd rpm-4.18.0
[ 210s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/rpm-4.18.0-1.oe1.x86_64
[ 210s] + RPM_EC=0
[ 210s] ++ jobs -p
[ 210s] + exit 0
[ 210s] Executing(rmbuild): /bin/sh -e /var/tmp/rpm-tmp.jaZtVz
[ 210s] + umask 022
[ 210s] + cd /home/abuild/rpmbuild/BUILD
[ 210s] + rm -rf rpm-4.18.0 rpm-4.18.0.gemspec
[ 210s] rm: cannot remove 'rpm-4.18.0/tests/testing/usr/share/locale/br/LC_MESSAGES/rpm.mo': Permission denied
[ 210s] rm: cannot remove 'rpm-4.18.0/tests/testing/usr/share/locale/ko/LC_MESSAGES/rpm.mo': Permission denied
[ 210s] rm: cannot remove 'rpm-4.18.0/tests/testing/usr/share/locale/uk/LC_MESSAGES/rpm.mo': Permission denied
...
```

**Comment by JetXujing** [comment]
It is confirmed that this problem is caused by b34333fa021c0ee7215714eeef96d1a2843ea08e.

**Comment by pmatilai** [comment]
No, that commit is not the problem, it's just the messenger. 

See https://github.com/rpm-software-management/rpm/issues/1382

**Comment by Geass-LL** [comment]
> No, that commit is not the problem, it's just the messenger.
> 
> See #1382

https://github.com/rpm-software-management/rpm/commit/b34333fa021c0ee7215714eeef96d1a2843ea08e changed the default behavior. Now users running `rpmbuild -ba *spec` will automatically remove the build directory, so many other packages which doesn't have `make clean` in `%check` may fail to build rpm.

**Comment by pmatilai** [comment]
We *could* of course add a recursive chmod to the default %clean to ensure it can be removed, but that seems...

The rpm test-suite is quite a special case and should be treated as such I think.

**Comment by Geass-LL** [comment]
> 

Yes, add a recursive chmod is not a good choice. I prefer to not remove build directory when users don't use `--clean` option.

**Comment by pmatilai** [comment]
Yes, some prefer to keep the builds, but it makes no sense as a default behavior. The *option* is certainly necessary.

**Comment by Geass-LL** [comment]
Now I don't have other idea, thanks!
