### ISSUE TITLE
Opening of package attested available by 'dnf' failing

### ISSUE THREAD

**Issue by Ricky-Tigg** [rpm-software-management/rpm#2381]
```
$ rpm -q rpm
rpm-4.18.0-1.fc37.x86_64
```
Attestation of availability of a package: with `dnf`
```
$ dnf -q rq --repo=fedora libvirt-client
libvirt-client-0:8.6.0-3.fc37.x86_64
```
Hello. Opening of package failing.
```
$ rpm -vv -qip `dnf -q rq --repo=fedora libvirt-client`
error: open of libvirt-client-0:8.6.0-3.fc37.x86_64 failed: No such file or directory
D: Exit status: 1
```
Mention `-p <file>` included [here](http://ftp.rpm.org/max-rpm/s1-rpm-query-parts.html). Option missing from RPM(8), 09 June 2002.

**Comment by pmatilai** [comment]
rpm -qp queries a local .rpm file, 'dnf repoquery' doesn't download one for you.

**Comment by pmatilai** [comment]
Note that Max-rpm hasn't been updated in like twenty years. It's interesting as historical reference, but you don't want to rely on that for documentation.

From rpm (8):

```
       -p, --package PACKAGE_FILE
              Query  an  (uninstalled) package PACKAGE_FILE.  The PACKAGE_FILE
              may be specified as an ftp or http style URL, in which case  the
              package header will be downloaded and queried.  See FTP/HTTP OP‐
              TIONS for information on rpm's ftp and http client support.  The
              PACKAGE_FILE  argument(s),  if not a binary package, will be in‐
              terpreted as an ASCII package manifest unless  --nomanifest  op‐
              tion  is  used.   In manifests, comments are permitted, starting
              with a '#', and each line of a package manifest file may include
              white  space  separated  glob expressions, including URL's, that
              will be expanded to paths that are substituted in place  of  the
              package  manifest  as  additional  PACKAGE_FILE arguments to the
              query.
```

yum-era repoquery could give the actual download url which could've been passed to rpm... but there's not a whole lot of point in that, as 'repoquery -i' provides the same basic info as 'rpm -qi'.

**Comment by Ricky-Tigg** [comment]
How i could miss the presence of that option?  Then unlike what i wrote, "_Option missing from RPM(8), 09 June 2002_", it was present. It would be worth to have an explicit description such as one that takes in account your statement "_rpm -qp queries a local .rpm file_". Would the following formulations be valid?
- _Query  a non-installed package PACKAGE_FILE._ instead of _Query  an  (uninstalled) package PACKAGE_FILE._
- _The PACKAGE_FILE must be available either locally in the system or in remote repository. When hosted in remote repository, it may be specified as an ftp or http style URL_ instead of _ The PACKAGE_FILE may be specified as an ftp or http style URL_.
