### ISSUE TITLE
package after `rpm --delsign` differs from original, unsigned package

### ISSUE THREAD

**Issue by cfm** [rpm-software-management/rpm#2382]
# package after `rpm --delsign` differs from original, unsigned package

## Description

To allow users to reproduce and verify our signed packages locally, we expect the result of `rpm --delsign package.rpm` to be bit-for-bit identical to the original unsigned `package.rpm`.  This assumption held under RPM 4.14 but no longer holds under RPM 4.18.  Is this a regression or a change in the expected behavior of `rpm --delsign`?

## Steps to reproduce

You can use the containerized reproduction in <https://gist.github.com/cfm/3559664c4f496fbb9beeade5f9411e5e>, or manually for some `package.rpm`:

1. `sha256sum package.rpm`
2. Sign `package.rpm`
3. `rpm --delsign package.rpm`
4. `sha256sum package.rpm`

## Expected behavior (RPM 4.14)

The hashes in steps (1) and (4) match.

## Actual behavior (RPM 4.18)

The hashes in steps (1) and (4) do not match.

## Comments

The containerized reproduction in <https://gist.github.com/cfm/3559664c4f496fbb9beeade5f9411e5e> gives you 60 seconds to grab `{before,after}.rpm` from the failing case.  [diffoscope reports:]

```diff
--- a/before.rpm
+++ b/after.rpm
│┄ Format-specific differences are supported for RPM archives but no file-specific differences were detected; falling back to a binary diff.
```

[diffoscope reports:]: https://github.com/rpm-software-management/rpm/files/10668792/ucvrhqkppzba.txt

**Comment by cfm** [comment]
Thanks, @mlschroe.  Does that hypothesis hold given that #1326's offending 3255273ae0fabd03c9738249a29c9c1e15f28f64 was introduced in RPM 4.14, which behaves as we expect?

**Comment by pmatilai** [comment]
#1326 behavior depends on the architecture of the package vs host used to delete the signature, but there seems to be another bug here, I can easily reproduce with a locally built package: it seems the signature reserved space doesn't get restored to the original value after --delsign. Offhand, I can't think of any particular change in that area since 4.14.x so I guess we're in for some bisecting...

**Comment by pmatilai** [comment]
Didn't test but commit 5c279fb149a44a1bc4d19e11c3c01942732b8486 seems likely, just based on the commit message it probably doesn't consider the --delsign case at all.

**Comment by cfm** [comment]
Thanks for confirming and investigating this, @pmatilai.
