### ISSUE TITLE
Non-adequate 'curl' command defined in the rpm configuration

### ISSUE THREAD

**Issue by Ricky-Tigg** [rpm-software-management/rpm#2384]
**rpm v.**: 4.18.0-1.fc37.x86_64

Hello. Steps to reproduce; to be applied to a **non-installed** package, here `libvirt-client` for instance.

Ensure that a correct value for`--repo` is set according to the OS you are working with. 

`URL0=https://nic.funet.fi/pub/Linux/INSTALL/fedora/linux/releases/$(rpm -E %fedora)/Everything/$(uname -i)/os/Packages/l/$(dnf -q rq --repo=fedora libvirt-client).rpm`

An adequate curl command to handle `URL0` is `curl -O $URL0`. Then it leads to display what is queried accordingly. However as indicated by the following output, a non-adequate curl command was defined by default in the rpm configuration.
```
$ rpm -vvqip $URL0
curl: (22) The requested URL returned error: 404
error: open of https://nic.funet.fi/pub/Linux/INSTALL/fedora/linux/releases/37/Everything/x86_64/os/Packages/l/libvirt-client-0:8.6.0-3.fc37.x86_64.rpm failed: No such file or directory
D: Exit status: 1
```

**Comment by pmatilai** [comment]
This has nothing to do with curl or rpm, and everything to do with a filename that doesn't exist:

```
libvirt-client-0:8.6.0-3.fc37.x86_64.rpm
               ^^
```

Rpm filenames don't carry epoch numbers, by old tradition.
