### ISSUE TITLE
RPM install lock forever if trying to install a pipe file

### ISSUE THREAD

**Issue by jmrcpn** [rpm-software-management/rpm#2393]
Version 4.18.0 stay put while installing a package while 4.17.1 is able to install 
(the very same package) without trouble. 
(this is a fresh install in both case, not an update... on the same system) 

The problem was pin point about creating a pipe file
with 4.17.1 the creation result is
prw------- 1 nullmailer nullmailer   0 Feb 14 23:09 trigger
while with 4.18.0 the result is
p--------- 1 root       root         0 Feb 14 23:15 'trigger;63ec5c79'
As previously stated, rpm install is lock forever.

strace show
;-------------------
.........
fchown(11, 93, 53)                      = 0
fchmod(11, 0700)                        = 0
utimensat(11, NULL, [{tv_sec=1676434544, tv_nsec=0} /* 2023-02-14T23:15:44-0500 */, {tv_sec=1676434544, tv_nsec=0} /* 2023-02-14T23:15:44-0500 */], 0) = 0
write(2, "D: ", 3D: )                      = 3
write(2, "Plugin: calling hook fsm_file_pr"..., 57Plugin: calling hook fsm_file_prepare in fsverity plugin
) = 57
write(2, "D: ", 3D: )                      = 3
write(2, "fsverity skipping non regular: p"..., 93fsverity skipping non regular: path /var/spool/nullmailer/tmp dest /var/spool/nullmailer/tmp
) = 93
write(2, "D: ", 3D: )                      = 3
write(2, "Plugin: calling hook fsm_file_pr"..., 52Plugin: calling hook fsm_file_prepare in ima plugin
) = 52
close(11)                               = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
mknodat(12, "trigger;63ec5c79", S_IFIFO|000) = 0
openat(12, "trigger;63ec5c79", O_RDONLY|O_NOCTTY|O_NOFOLLOW
;------------------------
Hoping that help

**Comment by pmatilai** [comment]
Yes, this is a known regression in 4.18, see #2195. It's fixed in git master already and will be fixed in 4.18.1 in nearish future.
