### ISSUE TITLE
Check signatures in the code

### ISSUE THREAD

**Issue by vityafx** [rpm-software-management/rpm#240]
How can I check in the `librpm` code whether a package in the transaction has signatures at all and if it does, print it's key id?

**Comment by n3npq** [comment]
Signatures are stored in a tag in a package header. So one retrieves a tag from a header, and then parses out the keyid from the OpenPGP format.

The harder issue is that there are up to 4 (or perhaps more) possible tags where signatures might be stored, and that even if a signature with a keyid may not (or cannot in the case of header+payload signatures) be verified.

You can find the 4 tags that may have to be examined by looking at the --queryformat string used by rpm --info (which displays the keyid) stored in /usr/lib/rpm. Doing a --queryformat is likely the most efficient extraction of a keyid when writing scripts, through bindings, or even  writing C code.

**Comment by pmatilai** [comment]
Sorry but this is an issue tracker, not a support forum. See http://rpm.org/community.html
