### ISSUE TITLE
Distinguish whether a signature failure is due to legacy crypto or a bad signature

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2402]
See https://bugzilla.redhat.com/show_bug.cgi?id=2170878#c15 for details.

`rpm-sequoia` could easily try to validate a signature using two different policies ([here](https://github.com/rpm-software-management/rpm-sequoia/blob/main/src/lib.rs#L574)): the system policy and a legacy policy.  If the signature doesn't validate with the system policy, but does with the legacy policy, it could return a different error.  @panu: Is this something that would be useful?

**Comment by pmatilai** [comment]
Being able to differentiate failure due to policy vs actually bad signature would be *hugely* useful from a user perspective.

**Comment by pmatilai** [comment]
We could probably get away with abusing RPMRC_NOTTRUSTED for the general case of valid-but-rejected signatures, that alone would be sufficient for sanely failures from already installed vs to-be-installed software. Expiry would be another similar case (from rpm POV).

**Comment by nwalfield** [comment]
@panu: Please take a look at https://github.com/rpm-software-management/rpm-sequoia/pull/31 and let me know what you think.  In particular, `rpm-sequoia` emits warnings on `stderr`.  Is that reasonable?  If not, how should we communicate this to the user.

**Comment by pmatilai** [comment]
Messages on stderr will get lost/detached from the context in various scenarios, I don't know how helpful (or not) those would be in practise. 

With a different error code, we can at least *hint* at the issue (some sufficiently broad "signature on X is no longer valid" style message, depending on the context) from librpm side with an rpmlog() message. Which is a whole lot more than they get now.

**Comment by nwalfield** [comment]
To be clear: this change returns a different error code *and* prints something on stderr.

I think the diagnostics would show up when the user directly invokes `rpm`, which is what the reporter did [here](https://bugzilla.redhat.com/show_bug.cgi?id=2170878#c0) .  I think you are right that in other cases, the message would get lost, but if they don't harm in those cases, it seems like a net win.

Ideally, rpm-sequoia would have a way to call `rpmlog`, but that's not yet the case.

What should we do?

**Comment by pmatilai** [comment]
> To be clear: this change returns a different error code and prints something on stderr.

Yup, understood. Just musing whether breaking the principle (of not printing to stderr) is worth the added information, and in the bugzilla case I don't think it really is. Key import is one place where it would make a big difference ... but mostly just for the internal parser which verifies on import. 

I'd leave the stderr out for now. This is already quite an improvement, we just need to add the relevant rpm side checks for the "new" return code (NOTTRUSTED is ages old technically, but it's never been used for anything)

**Comment by pmatilai** [comment]
...but of course, printing to stderr for additional diagnostics when eg RPM_TRACE is set is totally fine.

**Comment by nwalfield** [comment]
I'll adjust the patch, thanks for the feedback.

**Comment by nwalfield** [comment]
I added https://github.com/rpm-software-management/rpm-sequoia/commit/9fd8f7de9e1cf98ff11ec246189488696ca714ea , which returns `NOTTRUSTED` when a signature verifies using legacy crypto, but not using the configured policy.  I'm not going to make a release until rpm adopts this.  Let me know if and how I can help.

**Comment by nwalfield** [comment]
Thanks for testing, panu.  One thing (and sorry for hijacking this issue), we decided to have [a dedicated configuration for rpm-sequoia](https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/merge_requests/129#note_1297002360), which enables 1024 bit DSA and SHA-1.  I'm going to add that first (try `rpm-sequoia.config`, if that is not present, fallback to `sequoia.config`), and then make a release.  If you have any thoughts, please let me know.

**Comment by pmatilai** [comment]
This was done in rpm-sequoia 1.3.0 and didn't actually need changes to rpm code, closing.
