### ISSUE TITLE
configuration flag --with-lua cannot detect .pc file named lua5X.pc

### ISSUE THREAD

**Issue by NicholasBHubbard** [rpm-software-management/rpm#2407]
I needed to compile my own rpm with `--with-lua` support as my system (slackware) ships with rpm configured with the `--without-lua-support` flag. However, the Lua that my system provides (actually slackbuilds.org provides) is version 5.1.5, but the `--with-lua-support` flag requires at least version 5.2. Fortunately (I thought) my system also provides a package named `lua52` that installs Lua version 5.2.4. So I removed the old `lua` package and installed this package, but to my surprise when I went to compile rpm with the `--with-lua` support I got the same error as before:

```
checking for lua >= 5.2... no
configure: error: lua not present or too old (--without-lua to disable)
```

It turns out that the problem was that `pkg-config` only looks for a file named `lua.pc` in `$PKG_CONFIG_PATH`, but this `lua52` package only installs a file into `$PKG_CONFIG_PATH` named `lua52.pc` (and a symlink from this file named `lua5.2.pc`). I was able to solve this problem by symlinking the `lua52.pc` file to `lua.pc`. After creating this symlink I was able to build rpm with the `--with-lua` flag just fine.

[Here](https://slackbuilds.org/repository/15.0/development/lua52/?search=lua52) is a link to the `lua52` slackbuild.

I do not know if any other systems could be effected by this, but it would be nice if `.pc` files with names such as `lua52.pc` could be found automatically.

**Comment by pmatilai** [comment]
This should be fixed by commit 49befbc12381e95c2dacab50284ff32328a4ef99, from 4.19.0-beta (not yet released) onwards. As for older versions, just patch configure.ac to look at the name you want.
