### ISSUE TITLE
GPG key interpreted as PGP key

### ISSUE THREAD

**Issue by Ricky-Tigg** [rpm-software-management/rpm#2410]
Hello. A **non-manually** created fake RPM package is reported as follows
```
$ rpm -qi gpg-pubkey-5323552a-6112bcdc | awk 'NF' | sed -n '1,17p;$p'
Name        : gpg-pubkey
Version     : 5323552a
Release     : 6112bcdc
Architecture: (none)
Install Date: Sat Nov  5 11:14:03 2022
Group       : Public Keys
Size        : 0
License     : pubkey
Signature   : (none)
Source RPM  : (none)
Build Date  : Tue Aug 10 20:52:28 2021
Build Host  : localhost
Packager    : Fedora (37) <fedora-37-primary@fedoraproject.org>
Summary     : Fedora (37) <fedora-37-primary@fedoraproject.org> public key
Description :
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: rpm-4.18.0
-----END PGP PUBLIC KEY BLOCK-----
```
Despite the mention _gpg_ as part of the package name and what it is suggesting to us and indicating to the running OS, it is interpreted as _PGP_. What could cause that misinterpretation?

**Comment by nwalfield** [comment]
OpenPGP (sometimes just abbreviated as PGP, the first OpenPGP implementation before there was OpenPGP) is an IETF standard.  gpg is an implementation of the OpenPGP standard.  Sometimes people call OpenPGP certificates and keys GPG certificates and keys, because GPG is a well-known implementation.

Does that answer your question?

**Comment by Ricky-Tigg** [comment]
Certainly; thus no issue in the traditional sense.

**Comment by pmatilai** [comment]
Yep, the actual issue here (there *is* one) is that we're calling those keys gpg-anything, when they should be openpgp-pubkey. But renaming would break a lot of 3rd party tooling, and we'd really rather get rid of those entries in the package db to begin with.

**Comment by Ricky-Tigg** [comment]
Along with that unconventional issue, the user is probably left with an unknown: _How to determine how or by who the Red Hat GPG/DSA key was imported?_ Could it be me that imported a such package?
```
$ rpm -qa --scripts gpg-pubkey* --qf '%{version}-%{release} %{packager}\n'
5323552a-6112bcdc Fedora (37) <fedora-37-primary@fedoraproject.org>
ba3c3a2c-5eb88cc6 https://packagecloud.io/shiftkey/desktop (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>
```
I understand that so-called _fake_ package is created in order to satisfy a non-critical dependency. Then it would be expected to have as output here a package it is required by. However it is not so. That's confusing.
```
$ rpm -q --whatrequires gpg-pubkey-5323552a-6112bcdc
no package requires gpg-pubkey-5323552a-6112bcdc
```

**Comment by pmatilai** [comment]
gpg-pubkey can only be imported through 'rpmkeys --import' or the API counterpart, which is what eg dnf does. Package scriptlets can't generally do this, it's blocked by the transaction lock.

And yes, there's potential for treating pubkeys as dependency for signed packages (that use-case is one of the reasons they are in the db - AIUI, added long before my time).
