### ISSUE TITLE
RFE: Pre-validate (all) header data for semantic consistency

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#242]
The common theme in tickets #135, #136, #137, #138 and #139 is that the datatype of a valid tag is changed to something incompatible, such as an integer tag is changed to string, which then causes crash-and-burn in various places, many of which are not able to return an error even if they bothered to check for the types etc.

Mandatory signature checking makes this less of an issue, or rather shift the issue to key management. But optimally rpm should not crash on invalid data, even with --nosignature/--nodigest. The signature header data is fairly thoroughly validated before use, we should have something similar for the main header. Piles of more data to deal with, and many conditionals like if tag X is there then otherwise optional Y must be present too etc, but validating our used tags are type sane etc could be considered a starting point at least.

**Comment by n3npq** [comment]
As long as --nosignature and --nodigest are commonly used everywhere -- including in depsolvers -- you can setup an internal table to associate the data type with the tag and never access the field in the header.

**Comment by pmatilai** [comment]
Tag type sanity checking was added in commit dfd236d8b41a60f6bfad75db55f07b9617d191ad, which helps weed out some of the cases. There are undoubtedly cases where inter-related tags can be off and cause us to crash and burn despite all the added sanity checks to rpmfi & friends, but "everything" is a hopeless cause without some fundamental change of how things are done. Might as well close this...
