### ISSUE TITLE
Stop checking the "signature type" and "rpm package format version" in the Lead structure

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/rpm#2423]
This is a forwards compatibility issue with current versions of `rpm` regarding the future RPMv6 - `rpm` still currently reads these fields and checks their values, and thus will fail to parse packages produced with a zeroed out "Lead" section.

https://github.com/rpm-software-management/rpm/blob/4afe2d14d33db82ccb41c0a8d5eb1a4db90762fc/lib/rpmlead.c#L98-L105

**Comment by pmatilai** [comment]
Yup. There's no promise that any old rpm version will be able to handle v6 packages. Rpm is backwards, not forwards compatible.

Quoting the [roadmap announcement](https://github.com/rpm-software-management/rpm/discussions/2015):
> It also means that the last v4 release is expected to handle v6 packages to a large degree.

**Comment by dralley** [comment]
Right, but that says that (at least one) v4 release will be able to handle v6 packages to a large degree, and this is a preresquisite.

**Comment by pmatilai** [comment]
It will be handled, in time. The v6 spec is but a very early draft at this point.

**Comment by dralley** [comment]
Given that the `Lead` has been deprecated for so long, is there any reason to not go ahead and remove the checks now?  I can submit a PR.

**Comment by pmatilai** [comment]
Removing the code is not the issue. Don't rush it, thanks.
