### ISSUE TITLE
How to install rpm-python package from git to source compiled Python's pip

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpm#244]
I can see below pip packages are installed on my Fedora 25.

```
$ /usr/bin/pip list | grep rpm
rpm-python (4.13.0.1)

$ /usr/bin/pip3 list | grep rpm
rpm-python (4.13.0.1)
```

However I want to install the pip package (https://github.com/rpm-software-management/rpm/tree/master/python/rpm) for my source compiled Python 3.6.1 from git directly.

```
$ which python3
/usr/local/python-3.6.1/bin/python3
```

Is it possible to install it?

I succeeded to install `rpm` command itself by below way.
So, it there this kind of `make` task?

```
$ git clone git@github.com:rpm-software-management/rpm.git
$ cd rpm 
$ ./autogen.sh --noconfigure
$ ./configure --prefix="$(pwd)/dist"
$ make
$ make install
$ ./dist/bin/rpm --version
RPM version 4.13.90
```

Thanks.

**Comment by ignatenkobrain** [comment]
Sorry, this is not support forum. But check how bindings are built in fedora packaging, that should help you.

**Comment by junaruga** [comment]
Sorry I will take care of not using here as the support forum.
Thanks for the information! I will take a look of the fedora packaging.
