### ISSUE TITLE
Accessing macro parameter from lua fails with "attempt to index a nil value (global 'opt')"

### ISSUE THREAD

**Issue by rhabacker** [rpm-software-management/rpm#2446]
The documentation at https://github.com/rpm-software-management/rpm/blob/master/docs/manual/lua.md mentions how to get macro options as

``` 
%foo(a:b) %{lua:
if opt.b then
...
```

but this does not work on openSUSE Leap 15.4 with rpm with version:
```
rpm --version
RPM version 4.14.3
```
Running such a macro returns this error:
```
error: lua script failed: [string "<lua>"]:2: attempt to index a nil value (global 'opt')
```

# How to reproduce
1. Paste the following macro, mentioned in the documentation, into a file:
```
cat << EOF > test.macros
%foo(a:b) %{lua:
if opt.b then
   print('do b')
else
   print('or not')
end
if opt.a == 's' then
   print('do s')
end
if #arg == 0 then
   print('no arguments :(')
else
   for i = 1, #arg do
      print(arg[i])
   end
end
}
EOF
```
2. then run 
```
$ rpm --eval='%{load:test.macros} %foo -axxx=yyy -b  dsdsd'
error: lua script failed: [string "<lua>"]:2: attempt to index a nil value (global 'opt')
```

**Comment by pmatilai** [comment]
From said documentation, emphasis added:

> Parametric Lua macros receive their options and arguments as two local tables opt and arg, where opt holds processed option values keyed by the option character, and arg contains arguments numerically indexed. These tables are always present regardless of whether options or arguments were actually passed to simplify use. (**rpm >= 4.17**)

So no, it wont work in 4.14.

**Comment by rhabacker** [comment]
Thanks for clarification. 

I saw this paragraph, but I understood it to mean that the minimal version only refers to the last sentence and that it may only need adjustments.
