### ISSUE TITLE
Check for 'gettext' during configure script

### ISSUE THREAD

**Issue by rwhitworth** [rpm-software-management/rpm#245]
Output from configure script is invalid when gettext is not installed.  Installing gettext after the fact also doesn't resolve the problem until configure is re-ran.  I believe the configure script should detect when gettext is missing and error appropriately.

**Comment by n3npq** [comment]
Did you build with --disable-nls? There is no way for RPM configure to guess whether uninstalled get text is bug of a feature: YMMV, everyone's does.

```
 ./configure --help | grep nls
  --disable-nls           do not use Native Language Support
```

**Comment by pmatilai** [comment]
Rpm simply does what gettext documentation recommends:
```
AM_GNU_GETTEXT([external])
```

If you dont have/want gettext, use --disable-nls as explained in the above.  I dont see anything to fix here...
