### ISSUE TITLE
Document "dribbles" in the format reference

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/rpm#2462]
The only way to find a description of "dribbles" currently, if you do not know what it they are already, is to look at individual commit messages e.g. [0] and read between the lines.  I recommend putting some kind of description somewhere in the documentation.

[0] https://github.com/rpm-software-management/rpm/commit/34c2ba3c6a80a778cdf2e42a9193b3264e08e1b3

**Comment by dralley** [comment]
On an unrelated note but re: that commit message in question, it would also be kind of nice nice to write down known "quirks" that show up in the wild, perhaps with RPM samples, all collected in one place?  

> Further, there are otherwise legit packages in the wild that are signed by something that places the signatures outside the signature region (samplesin https://github.com/rpm-software-management/rpm/issues/270 and RhBug:1514190 are from Intel, maybe they're using a home-grown signing software) and also rpm5 is actually relying on a padding tag to be
outside the region as it's used for the actual padding between the signature and main header..

**Comment by pmatilai** [comment]
The IMA signatures and their journey from there to here are a tragic mess, just opened up a new ticket to remind me: #2865
