### ISSUE TITLE
x86-64-v3, x86-64-v3 detection must take XCR0 into account

### ISSUE THREAD

**Issue by fweimer-rh** [rpm-software-management/rpm#2463]
The current logic is based solely on CPUID. This is not correct because it does not verify that the software stack (firmware/hypervisor/kernel) supports YMM and ZMM registers. For that, it is necessary to read the XCR0 register using the XGETBV instruction.

**Comment by pmatilai** [comment]
@Vogtinator

**Comment by Vogtinator** [comment]
The OSXSAVE bit should be effective for that. glibc doesn't do anything else either.

**Comment by Vogtinator** [comment]
That indicates it uses it even for XMM, i.e. SSE might also not be available?

There's even more fun: If OSXSAVE isn't set, then xgetbv raises #UD.

However, this part can be implemented in a slightly nicer way by using compiler runtime support, which hopefully meanwhile does it correctly...:

```
diff --git a/lib/rpmrc.c b/lib/rpmrc.c
index 66ce947ae..22659e086 100644
--- a/lib/rpmrc.c
+++ b/lib/rpmrc.c
@@ -790,11 +790,13 @@ static int get_x86_64_level(void)
     const unsigned int op_1_ecx_lv3 = bit_FMA | bit_MOVBE | bit_OSXSAVE | bit_AVX | bit_F16C;
     const unsigned int op_7_ebx_lv3 = bit_BMI | bit_AVX2 | bit_BMI2;
     if (level == 2 && (op_1_ecx & op_1_ecx_lv3) == op_1_ecx_lv3 && (op_7_ebx & op_7_ebx_lv3) == op_7_ebx_lv3
-        && (op_80000001_ecx & bit_LZCNT))
+        && (op_80000001_ecx & bit_LZCNT)
+        && __builtin_cpu_supports("avx2"))
         level = 3;
 
     const unsigned int op_7_ebx_lv4 = bit_AVX512F | bit_AVX512DQ | bit_AVX512CD | bit_AVX512BW | bit_AVX512VL;
-    if (level == 3 && (op_7_ebx & op_7_ebx_lv4) == op_7_ebx_lv4)
+    if (level == 3 && (op_7_ebx & op_7_ebx_lv4) == op_7_ebx_lv4
+        && __builtin_cpu_supports("avx512f"))
         level = 4;
 
     return level;
```

Opinions? For GCC this is documented, for clang it is not...

If this is acceptable, I'll make a PR with proper explanation.
