### ISSUE TITLE
Improve linting for signature packet processing

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm#2483]
I did some investigating based on [this report sent to fedora devel](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/EAWVXA5IM3GXEF57SCLD644JU5OU26UR):

Installing one of the intel packages results in:

```
$ LD_PRELOAD=$HOME/rpm-sequoia/target/release/librpm_sequoia.so RPM_TRACE=0 ~/rpm/b/rpm -i /var/cache/dnf/oneAPI-8fe830815acb32cb/packages/intel-oneapi-common-licensing-2023.1.0-2023.1.0-43473.noarch.rpm 
error: /var/cache/dnf/oneAPI-8fe830815acb32cb/packages/intel-oneapi-common-licensing-2023.1.0-2023.1.0-43473.noarch.rpm: Header RSA signature: BAD (package tag 268: invalid OpenPGP signature)
error: /var/cache/dnf/oneAPI-8fe830815acb32cb/packages/intel-oneapi-common-licensing-2023.1.0-2023.1.0-43473.noarch.rpm cannot be installed
```

That's a pretty bad error message.  Using `RPM_TRACE`, I see:

```
$ LD_PRELOAD=$HOME/rpm-sequoia/target/release/librpm_sequoia.so RPM_TRACE=1 ~/rpm/b/rpm -i /var/cache/dnf/oneAPI-8fe830815acb32cb/packages/intel-oneapi-common-licensing-2023.1.0-2023.1.0-43473.noarch.rpm
...
_pgpPrtParams: -> error: Failure: Signature Packet
...
```

So the error is in `pgpPrtParams`.  Should we add a linting parameter to `pgpPrtParams` as we're doing for `pgpVerifySignature`?

**Comment by pmatilai** [comment]
Oh, right. I see no reason not to. I'd much rather add these all in one go than one now and another in three months :smile:
