### ISSUE TITLE
Verification of PAYLOADDIGESTALT is broken

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/rpm#2486]
There are two components to this

1) `rpm -v --checksig` (also without -v) seems to exclude any digests which fail to verify so long as an "equivalent" one does verify.  This seems to apply even when using `--define "_pkgverify_level all"`.  This [may](https://github.com/rpm-software-management/rpm/pull/880/files#diff-3496c36651db166fa48735c0d33ef48c537c18003e272e3381c16e637fc0d8dcR486-R500) have been intentional?

2) `rpm` appears to fail to verify PAYLOADDIGESTALT in situations where the payload is compressed but because of (1) there is no way to tell, it is hidden from `--checksig` output completely.   Presumably, the at verification time the digest which is checked against the value stored in PAYLOADDIGESTALT is accidentally being computed against the compressed payload bits rather than the uncompressed payload.

 * If the payload is configured to be uncompressed (`w.ufdio`) when the package is built, then both digests will be checked and successfully verify and be shown in the output of `-v --checksig`
 * If you use compression but manually modify PAYLOADDIGESTALT to match PAYLOADDIGEST, then both digests will be checked and successfully verify and be shown in the output of `-v --checksig`
 * If you use compression and manually swap the values of PAYLOADDIGEST and PAYLOADDIGESTALT in the RPM header, then it will successfully verify the package using only PAYLOADIGESTALT and not displaying anything for the payload digest.
 * If you manually modify the package so that both values are wrong, or leave the real expected value of PAYLOADDIGESTALT intact, then both digests will appear in the output as having failed to verify.  Also, the error output shows that the expected values are the same for PAYLOADDIGEST and PAYLOADDIGESTALT

**Comment by dralley** [comment]
To reproduce:

specfile

```
Name:           rpm-test
Version:        0
License:        LGPL
Release:        0
Summary:        ""

#BuildRequires:

%description

%build
cat > hello-world.sh <<EOF
#!/usr/bin/bash
echo Hello world
EOF

%install
mkdir -p %{buildroot}/usr/bin/
install -m 755 hello-world.sh %{buildroot}/usr/bin/hello-world.sh

%clean

%files
/usr/bin/hello-world.sh

%changelog
```

Build with `--define "_binary_payload w.ufdio"`

Inspect `rpm -v --checksig --define "_pkgverify_level all"` output:

```
    Header RSA signature: NOTFOUND
    Header DSA signature: NOTFOUND
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 ALT digest: OK
    Payload SHA256 digest: OK
    RSA signature: NOTFOUND
    DSA signature: NOTFOUND
    MD5 digest: OK

```
Note that the ALT digest is present. Rebuild with some kind of compression, try again:

```
    Header RSA signature: NOTFOUND
    Header DSA signature: NOTFOUND
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    RSA signature: NOTFOUND
    DSA signature: NOTFOUND
    MD5 digest: OK
```

Note that it isn't present.  Inspect the header with `rpm -qp --xml` to make sure it is present there:

```
...
  <rpmTag name="Payloaddigest">
	<string>ba21f4cb197179798065399a1551af2727e41efe56daed73ce869549b1280dd0</string>
  </rpmTag>
  <rpmTag name="Payloaddigestalgo">
	<integer>8</integer>
  </rpmTag>
  <rpmTag name="Payloaddigestalt">
	<string>5ac031cfaded6e79dcb59b44946fc24c40e7d775e3ba020a7b4cb66238c4771f</string>
  </rpmTag>
</rpmHeader>
```

Skipping ahead to what happens if you somehow produce a package where both checksums are incorrect, you can see that the checksum that `rpm` is calculating at verification-time for PAYLOADDIGESTALT is the same as the one for PAYLOADDIGEST.


![Screenshot from 2023-04-15 23-33-44](https://user-images.githubusercontent.com/2751996/232265068-2ac78d88-e807-4e87-92b0-acaccdd44e37.png)

If you do the same thing in a different way by instead writing to the package a PAYLOADDIGESTALT that matches PAYLOADDIGEST, then it verifies OK.

**Comment by dralley** [comment]
@DemiMarie @pmatilai

**Comment by DemiMarie** [comment]
@dralley RPM does not decompress the payload when verifying signatures and digests.  That would massively increase its attack surface.  Therefore, failing to verify `PAYLOADDIGESTALT` is expected.

**Comment by dralley** [comment]
Sure, but in that case it should not look for PAYLOADDIGESTALT at all.  Otherwise you'd just be comparing it against a value that it will not match most of the time.

**Comment by pmatilai** [comment]
The case of payloaddigestalt is for uncompressed payload: you can take a compressed payload from a package, uncompress it and replace the compressed payload in the package, and it'll work. There's no reason not to.

**Comment by dralley** [comment]
Ok.
