### ISSUE TITLE
%autosetup -a1 -a2 failed to extract all tarball

### ISSUE THREAD

**Issue by luyatshimbalanga** [rpm-software-management/rpm#2495]
On this example from blender.spec
```
Source0:        https://download.%{name}.org/source/%{name}-%{version}.tar.xz
Source1:        https://projects.%{name}.org/%{name}/%{name}-addons/archive/v%{version}.tar.gz#/%{name}-addons-%{version}.tar.gz
Source2:        https://projects.%%{name}.org/%{name}/%{name}-addons-contrib/archive/v%{version}.tar.gz#/%{name}-addons-contrib-%{version}.tar.gz
..snip...
mkdir scripts/addons
for d in addons addons-contrib; do
    mv %{name}-$d/* scripts/addons
    # wipe .gitea and .github
    rm -r %{name}-$d
done
```

`%autosetup -p1 -a1 -a2` failed to extract all referenced tarball. Workaround is to use `setup q -a1 -2` following by `autopatch -p1`.
Tested on Fedora 38 running on RPM version 4.18.1.

**Comment by kloczek** [comment]
Known issue https://github.com/rpm-software-management/rpm/issues/1204

**Comment by gotmax23** [comment]
It would be nice if rpm's argument parser could have a way to accept repeated flags

**Comment by kloczek** [comment]
Nevertheless it is possible to hadle such cases by:
```spec
%setup -q -a1 -a2
%autopatch
```

**Comment by pmatilai** [comment]
That wont work, %autopatch needs an accompanying %autosetup to set it up.
What you can do though (in rpm >= 4.18) is

```
%autosetup -N -T
%__rpmuncompress -x %{SOURCE1}
%__rpmuncompress -x %{SOURCE2}
...
%autopatch
```

And of course, it would be nice if macros handled multiple instances of the same argument. That's ticket #546.
