### ISSUE TITLE
Either the "legacy header merge" code or the documentation is incorrect

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/rpm#2498]
The signature tags `RPMSIGTAG_PAYLOADSIZE` and `RPMSIGTAG_LONGARCHIVESIZE` both claim to be *uncompressed* payload sizes in the comments alongside the definitions.  There are also main header tags `RPMTAG_ARCHIVESIZE` and `RPMTAG_LONGARCHIVESIZE` which the documentation describes as being *compressed* payload sizes.

```
    RPMSIGTAG_PAYLOADSIZE = 1007,/*!< internal uncompressed payload size (32bit) in bytes. */
    RPMSIGTAG_LONGARCHIVESIZE = RPMTAG_LONGARCHIVESIZE, /*!< internal uncompressed payload size (64bit) in bytes. */

    RPMTAG_LONGARCHIVESIZE	= RPMTAG_SIG_BASE+15,	/* l */
    RPMTAG_ARCHIVESIZE		= 1046,	/* i */
```

> Archivesize | 1046 | int32 | (Compressed) payload size.
> Longarchivesize | 271 | int64 | (Compressed) payload size when > 4GB.

(from https://github.com/rpm-software-management/rpm/blob/master/docs/manual/tags.md#scalar-types)

In the "legacy header merge" code, the signature header tag `RPMSIGTAG_PAYLOADSIZE` is inserted into the main header as `RPMTAG_ARCHIVESIZE` and the signature header tag `RPMSIGTAG_LONGARCHIVESIZE` is inserted into the main header as `RPMTAG_LONGARCHIVESIZE` if the main header tags are not present.  (sidenote: I gather from https://github.com/rpm-software-management/rpm/pull/1688 that these tags aren't *supposed* to be present in the main header, but I don't really understand why, given that's where the payload digest is, and it has no need to be mutable?)

https://github.com/rpm-software-management/rpm/blob/e9caa60d668c8ae6a9cc83dba7f45792757eac46/lib/package.c#L34-L108

Anyway, that means that either the documentation or the header merge code is wrong.  Because if you fetch the `RPMTAG_ARCHIVESIZE` tag from the header, it would seem that in most cases that value will come from `RPMSIGTAG_PAYLOADSIZE`, and that value is the uncompressed size, contrary to the documentation.

You can see this in practice - when printed with `rpm -qp --xml`, the value for `Archivesize` is larger than the entire package file (because the package file has a compressed payload).

EL7 package

```
[dalley@thinkpad rpm-rs]$ rpm -qp --xml test_assets/389-ds-base-devel-1.3.8.4-15.el7.x86_64.rpm | rg -i -C 2 archivesize
warning: test_assets/389-ds-base-devel-1.3.8.4-15.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
	<integer>4294967295</integer>
  </rpmTag>
  <rpmTag name="Archivesize">
	<integer>510164</integer>
  </rpmTag>
[dalley@thinkpad rpm-rs]$ ls -la test_assets/
.....
.....
-rw-r--r--. 1 dalley dalley 277288 Apr  7 16:43 389-ds-base-devel-1.3.8.4-15.el7.x86_64.rpm
```

Fedora 38 package

```
[dalley@thinkpad rpm-rs]$ rpm -qp --xml zlib-1.2.13-3.fc38.x86_64.rpm | rg -i -C 2 archivesize
warning: zlib-1.2.13-3.fc38.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID eb10b464: NOKEY
	<integer>4294967295</integer>
  </rpmTag>
  <rpmTag name="Archivesize">
	<integer>213472</integer>
  </rpmTag>
[dalley@thinkpad rpm-rs]$ ls -la
.....
.....
-rw-r--r--.  1 dalley dalley 96890 Apr 16 11:26 zlib-1.2.13-3.fc38.x86_64.rpm
```

Or in repository metadata

```
  <size archive="31268" installed="29632" package="26692" />
  <size archive="75000" installed="73919" package="61844" />
  <size archive="73816" installed="73108" package="29696" />
```

```

**Comment by dralley** [comment]
It looks probable that nothing has written a "correct" `RPMTAG_ARCHIVESIZE` tag since 2007.  Given that nobody noticed, is there any reason to keep this stuff in rpm v6?

**Comment by dralley** [comment]
Ok: *elsewhere* the documentation claims those tags are the uncompressed sizes

>RPMTAG_LONGARCHIVESIZE - uncompressed payload size

https://github.com/rpm-software-management/rpm/blob/c21885e6b0e3045dc165d4d7be1911987a9cec9b/docs/manual/large_files.md#64-bit-tags

So maybe it's just the documentation that is wrong

**Comment by dralley** [comment]
Should this be looking at `RPMTAG_LONGSIZE` instead? https://github.com/rpm-software-management/rpm/blob/13e89c6ae5ff9cb20b0721e80732e7cde55da96c/lib/psm.c#L666

**Comment by pmatilai** [comment]
Thanks for reporting.

Looks like a doc bug. The tag descriptions in 50324700562aa6204d93b1e4e9ae9776ecdeeedb are little more than a brain-dump and given the sheer number of different size tags, evolved over time (payload vs archive naming etc) and the original purpose long lost in history, it's no big surprise there may be errors in it. Archivesize must of course be the *archive* size, ie the file sizes + archive format overhead.

As for why some of it is in the signature and some in the main header, it's historical but also practical - the payload digest in the main header is a very recent (in rpm timescale) addition and is painful to put there. But now that the code to do that exists, some of these sizes could and should indeed be moved to the main header. In v6 that is.

**Comment by dralley** [comment]
Thanks.  What is the expected use case of providing the uncompressed archive size?  Repository metadata exposes it, but frankly I don't understand why, it doesn't seem like particularly useful information.
