### ISSUE TITLE
4.18.90: build fails with `-D WITH_INTERNAL_OPENPGP=ON -D WITH_OPENSSL=ON`

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#2507]
Looks like some library (probably `gpgme`) dependency checking is missing when source tree is configured with `-D WITH_INTERNAL_OPENPGP=ON -D WITH_OPENSSL=ON`.
I see only openssl detection in
https://github.com/rpm-software-management/rpm/blob/93ee7d9c6164467608094a7e0652a0e3d84a6715/rpmio/CMakeLists.txt#L14C1-L17

Result is that librpmio is underlinked:
```console
[ 37%] Linking C executable rpm
/usr/bin/cmake -E cmake_link_script CMakeFiles/rpm.dir/link.txt --verbose=1
/usr/bin/gcc -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -DNDEBUG -Wl,--gc-sections -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--build-id=sha1 CMakeFiles/rpm.dir/rpm.c.o CMakeFiles/rpm.dir/cliutils.c.o -o rpm  -Wl,-rpath,/home/tkloczko/rpmbuild/BUILD/rpm-4.18.90/x86_64-redhat-linux-gnu/lib:/home/tkloczko/rpmbuild/BUILD/rpm-4.18.90/x86_64-redhat-linux-gnu/rpmio: lib/librpm.so.10.0.0 rpmio/librpmio.so.10.0.0 /usr/lib64/libpopt.so
/usr/bin/ld: rpmio/librpmio.so.10.0.0: undefined reference to `pgpPrtPkts'
/usr/bin/ld: rpmio/librpmio.so.10.0.0: undefined reference to `pgpNewDig'
/usr/bin/ld: rpmio/librpmio.so.10.0.0: undefined reference to `pgpDigGetParams'
/usr/bin/ld: rpmio/librpmio.so.10.0.0: undefined reference to `pgpFreeDig'
collect2: error: ld returned 1 exit status
```

**Comment by ffesti** [comment]
These are all removed functions. See "Removed APIs" on http://rpm.org/wiki/Releases/4.19.0

May be you build tree is not 100% clean. Leftover files from the autotools era can mess things up. Try checking out the tree from scratch.

**Comment by kloczek** [comment]
Moment so intention is to abandon handle by rpm handle PGP signatures using openssl routines? 🤔

**Comment by ffesti** [comment]
No, those are RPM APIs that got removed. There are newer ones to be used instead. RPM itself should build without those errors. Only software using these functions of the RPM API need adjusting.

**Comment by kloczek** [comment]
OK .. so it some unfinished wotk on that transition.
Thanks for clarification 😃

**Comment by kloczek** [comment]
> The openssl backend builds just fine. Like @ffesti said, you have some cruft in your source and/or build tree that's causing the failure.

Moment so what kind of cmake params I need to pass to 4.18.90 to build with openssl? 🤔 

BTW looks like currently is used kind of messy versioning/tagging.
On http://ftp.rpm.org/releases/testing/ latest (test) release is 4.18.90 and there is no such tab in git repo and latest one is `rpm-4.19.0-alpha`.
If that is wat was used to generate rpm-4.18.90.tar.bz2 it should eb used `rpm-4.18.90`.
If you want to use alpha/beta/rc convention IMO you should consider use Gnome convention like `rpm-4.19.0.alpha` -> `rpm-4.19.0.beat` -> `rpm-4.19.0.rc` -> `rpm-4.19.0.0` (https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235)
As well IMO it would be good to drop `rpm-` prefix in git tags to be able directly use autogenerated from git tag tar ball as input source resource.

**Comment by kloczek** [comment]
God to know that issue of tagging/versioning in in WIP state 😋 
Thx 👍 

What about how to build 4.18.90 with openssl? 🤔

**Comment by pmatilai** [comment]
As per INSTALL:

```
wget http://ftp.rpm.org/releases/testing/rpm-4.18.90.tar.bz2
tar xf rpm-4.18.90.tar.bz2
cd rpm-4.18.90
mkdir _build
cd _build/
cmake -D WITH_INTERNAL_OPENPGP=ON -D WITH_OPENSSL=ON ..
make
```

Whether or not you use _build directory has no effect on the outcome.
I guess a confused ccache (from timewarps or such) could cause such issues too.

**Comment by kloczek** [comment]
> As per INSTALL:
> 
> ```
> wget http://ftp.rpm.org/releases/testing/rpm-4.18.90.tar.bz2
> tar xf rpm-4.18.90.tar.bz2
> cd rpm-4.18.90
> mkdir _build
> cd _build/
> cmake -D WITH_INTERNAL_OPENPGP=ON -D WITH_OPENSSL=ON ..
> make
> ```

Please have a look one more time on the ticket description.
Exactly those two params I've been using and with those two build fails.
Did you try to reproduce this issue? 🤔

**Comment by pmatilai** [comment]
Sigh. That's copy-pasted from my terminal from a *successful* build.

You have some local messup on your system. Purge ccache cache, something.

**Comment by kloczek** [comment]
I'm not using ccache.

Build env is performed inside LXC zone which has been created out of only BuldRequires.
The same effect I have outside LXC zone.
Did you check 'cmake -L" output to check what exactly have been set by cmake? 🤔

**Comment by dmnks** [comment]
I just checked the official alpha tarball and there were no grep matches for `pgpPrtPkts` in it. Please double-check your local copy, there must be some leftovers as mentioned previously.

**Comment by pmatilai** [comment]
> Are you sure?

Yes, I'm bloody sure. How about you, have you actually thought to double-check your results? I didn't think so.
