### ISSUE TITLE
OpenPGP: Function `pgpParsePkts` missing length argument

### ISSUE THREAD

**Issue by jrohel** [rpm-software-management/rpm#2513]
The `pgpParsePkts` function does not have a `armorlen` argument. Instead, it requires a null-terminated input buffer. It assumes that the input is a C string.

It's not a blocker for me. I made a workaround, I copy the buffer from the user to the temporary buffer, where I add the terminating zero character. It's not ideal, it costs extra memory and CPU time.

So a tip for an extension/new API.

**Comment by pmatilai** [comment]
This doesn't seem like something worth doing on its own, but I mentioned this as another consideration whenever the grand crypto API redesign happens in #2041.
