### ISSUE TITLE
OpenPGP: How to get `can_sign` info?

### ISSUE THREAD

**Issue by jrohel** [rpm-software-management/rpm#2515]
GpgMe provides a lot of information (attributes) about keys/subkeys - `revoked`, `expired`, `can_sign`, ....
So far we have used `can_sign` in the librepo library. How to get this information via librpm API?

**Comment by pmatilai** [comment]
I'm afraid none of that info is exposed as such in the rpm API.
That said, since rpm >= 4.18 rpm only returns signing capable subkeys and in the first place, so you if you restrict version to rpm 4.18 and newer, you can just do "can_sign = TRUE".

**Comment by jrohel** [comment]
>so you if you restrict version to rpm 4.18 and newer, you can just do "can_sign = TRUE".

That's exactly what I'm doing. I was just afraid of returning a false positive. But if since rpm >= 4.18 rpm only returns signing capable subkeys it's fine.
I should just change my comment in the librepo code:
"TODO[jrohel]: Set the current value instead of TRUE" -> "rpm returns only signing capable subkeys"

**Comment by pmatilai** [comment]
I guess the remaining thing here is to explicitly document the rpm API behavior wrt this.
