### ISSUE TITLE
RFE: %{rpmversion} macro

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#2523]
Would it be possible to expose a macro with the version of RPM, itself? So I could do `%if v"0%{?rpm_version}" >= v"4.19" ...`.

Thanks.

**Comment by pmatilai** [comment]
If only all RFE's were this easy... (we'd get bored silly :laughing: )

Seems a bit crazy we haven't had such an obvious thing, thanks for the suggestion.
Called it %{rpmversion} without the underscore for consistency with the rest of the builtins though.

Just out of curiosity, what (apparent 4.19 feature) you're conditionalizing? Usually there's some more direct way than comparing versions...

**Comment by hroncok** [comment]
A number of % signs to escape a literal % sign in the file list. RPM 4.17 and 4.18 needed 8 of them, 4.19 is sane and only needs 2.

**Comment by pmatilai** [comment]
Heh, that really drives home that the glob effort by @dmnks was well worth it.

And okay, I don't think there's a "good" way to detect that, but that did inspire #2256.

**Comment by dmnks** [comment]
Yeah, it seems like the proposed `%rpmversion` macro would indeed be a good fit for SPEC syntax changes in general. Having a separate version for the SPEC format might perhaps come in handy in the future, too, but not sure.

**Comment by hroncok** [comment]
https://github.com/rpm-software-management/rpm/pull/2256 ? Did you mean https://github.com/rpm-software-management/rpm/pull/2526 ?

**Comment by pmatilai** [comment]
Argh, #2526 of course :facepalm:

**Comment by hroncok** [comment]
Could you please add this to 4.19 as well?

**Comment by dmnks** [comment]
Yup, this will find its way into 4.19 in Beta (planned for ~ end of month).
