### ISSUE TITLE
A coredump may occur when the RPM package is installed

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2543]
When I try to add a plugin that uses strcmp, a core occurs. The stack is as follows:
```
#0 ...
#1 rpmpluginsCallFsmFilePost()
#2 fsmDoMkdir()
#3 ensureDir()
#4 rpmPackageFilesInstall()
#5 rpmpsmUnpack()
...
#13 rpmInstall()
#14 main()
```

I tried to analyze it and found that the second parameter `fi` of rpmpluginsCallFsmFilePost() was NULL. As a result, rpmfiDN(fi) returned NULL, and abspath() returned NULL. As a result, the third parameter `apath` of hookFunc is empty, and a coredump may occur when there is no security check. abpath() is introduced in 6dd62720fe84f7e2ad902c915b952fc0b29e3dcd. I found that the third parameter of hookFunc is not null before 6dd62720fe84f7e2ad902c915b952fc0b29e3dcd. I do not understand the processing intention when `fi` is null. Is this reasonable?

**Comment by pmatilai** [comment]
Yes, fi can intentionally and legitimately be NULL, see
https://rpm-software-management.github.io/rpm/manual/plugins#per-file-hooks

That case is simply something you need to handle in your plugin.

**Comment by pmatilai** [comment]
Oh but that's not really what you're talking about, it's path argument whose behavior changed in that commit that is the issue. In case of rpmpluginsCallFsmFilePost() when fi is NULL, ie unowned directory.

And the real issue there is that the rpmpluginsCallFsmFilePost() call was never updated to pass the absolute path in that commit.
