### ISSUE TITLE
Adding ZSTD (or other FSE compressor)

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#256]
There are (at least) 3 new FSE compression formats that have been released in
the past few years: zstd (Facebook),  brotli (Google), lzfse (Apple).

The new compressors have better compression ratios and speed than gzip/zlib.

And while the compression ratio is still not as good as XZ/LZMA, the decompression speed (which is mostly rate determining for RPM installation), of zstd is considerably faster than XZ/LZMA.

One or more of these implementations might be useful for RPM.

(aside)
There's an implementation for RPM+ZSTD available here: [http://rpm5.org/files/rpm/rpm-5.4/SNAPSHOT/rpm-5.4.18-0.20170718.src.rpm](url) that can be adapted to RPM4. I can/will do the patch if there is sufficient interest.

**Comment by n3npq** [comment]
Here are URL's for zstd, brotli, and lzfse"
- [https://github.com/facebook/zstd.git](url)
- [https://github.com/google/brotli.git](url)
- [https://github.com/lzfse/lzfse.git](url)

**Comment by Conan-Kudo** [comment]
@n3npq Ooh, this looks very nice!

**Comment by n3npq** [comment]
A (lightly tested) RPM+ZSTD patch. You will need RPM_CHECK_LIB() from the acinclude.m4 comment #2 on issue #255.

[rpm_zstd.patch.gz](https://github.com/rpm-software-management/rpm/files/1160163/rpm_zstd.patch.gz)

**Comment by n3npq** [comment]
This patch is now committed at https://github.com/rpm5/rpm/commit/debde46a23c5a942d017026903020eb3b389d91c
