### ISSUE TITLE
Migrate away from SemaphoreCI Classic

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2569]
From https://semaphoreci.com/blog/semaphore-classic-deprecation:

> However, we are excited to announce that Semaphore Classic will be discontinued by September 30, 2023.

It's an interesting way to put it. Okay, maybe their engineers *are* excited to be finally rid of a legacy platform that's pain to support, I can totally symphatize with *that*. At any rate, we need to move our business elsewhere before that.

Reading further into the announcement, they'll be introducing "brownouts" to the service starting from beginning of September, so we'll want to be out by then. So, we have a deadline here: migrate away from SemaphoreCI Classic before September 1st.

**Comment by wiktor-k** [comment]
Hi,

I think using Docker directly would solve this problem (as then you can use fedora as a base image).

There are at least two approaches:
  - docker buildx (if you need to build for multiple architectures), an example: https://github.com/wiktor-k/paperboy/blob/main/.github/workflows/docker.yml#L17
  - official docker action (if simple docker build suffices): https://www.docker.com/blog/first-docker-github-action-is-here/

It seems you already have a Dockerfile: https://github.com/rpm-software-management/rpm/blob/master/ci/Dockerfile

Do you just need to run that on GitHub actions? If so I think I could lend a hand :)

**Comment by dralley** [comment]
You can use Fedora as a base image with Github Actions too - of course the VM will still be Ubuntu, but all of the commands can run inside of a container image of your choosing.

https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#defining-the-container-image

**Comment by dmnks** [comment]
Thanks everyone for the input! We went with GH Actions in the end (#2598).

**Comment by dmnks** [comment]
I've also changed the *required* check to be the newly added GH workflow instead of SemaphoreCI.

This has resulted in all the open PRs to be stuck on "Waiting for status to be reported", due to those branches not being rebased on top of master and thus missing a workflow file. That means the respective PR authors will need to rebase their branches themselves, however that's what we actually want, due to the recent test-suite rework, anyway.

**Comment by dmnks** [comment]
One more note: I'll keep the SemaphoreCI check in place for a little while, just to have something to compare to in case of any unexpected failures in the new GH workflow.

**Comment by pmatilai** [comment]
For the record, we pulled the plug on SemaphoreCI builds on Sep 1st.
