### ISSUE TITLE
Source RPMs should have ARCH set to src

### ISSUE THREAD

**Issue by davide125** [rpm-software-management/rpm#2601]
Right now source RPMs get an ARCH tag set to the architecture of the machine the package was built on (e.g. `i686`). We should set it to `src` instead, both for clarity and to help with build reproducibility.

**Comment by pmatilai** [comment]
Sorry but no. Source rpm headers reflect the architecture and the environment they were built on, and various tooling actually *relies* on that. This by design, and we can't go changing it just because people assume differently (this comes up every second year or so).

We'd have to come up with an entirely new source archive format that is designed from the go to be arch independent.

**Comment by keszybz** [comment]
Please reconsider.

The current behaviour is just not useful. The tooling that relies on this, if any, should be adjusted. This part of behaviour is not useful, and in fact we go to large efforts to work around it, for example by buiding srpms on all architectures and checking that they are indeed identical. Let's make this process easier.

**Comment by NeilHanlon** [comment]
Agreed with @keszybz here. The tooling can (and should) be updated. If anything, it should be done to prove that building SRPMs on different platforms is indeed deterministic.

**Comment by pmatilai** [comment]
ARCH is just the tip of the iceberg, there are all those arch-dependent build-dependencies and whatnot that need to be recorded someplace for the buildsystems that rely on this all. 

The src.rpm is what it is and can't be changed this fundamentally. I totally get that people are expecting it to be some arch-independent thing but it's not, and we can't change that fundamental fact. Period. If you want an arch-independent source carrier format, it'll need to be something else.

**Comment by keszybz** [comment]
Actually, srpm are *almost* arch-independent. I know of two issues: the ARCH tag, and BuildRequires. But Fedora packaging guidelines actually forbid archful BuildRequires (https://docs.fedoraproject.org/en-US/packaging-guidelines/#_buildrequires_and_isa, "SRPMs need to be architecture independent"). It is true that sometimes we get slightly different BuildRequires on different architectures, but in fact nobody wants this, this is just an unfortunate side effect of how the srpm is constructed. What we *want* is srpms which are arch-independent and can be used to build the rpm on any other architecture. Is there some other dependency on the arch?

**Comment by NeilHanlon** [comment]
> Actually, srpm are _almost_ arch-independent. I know of two issues: the ARCH tag, and BuildRequires. But Fedora packaging guidelines actually forbid archful BuildRequires (https://docs.fedoraproject.org/en-US/packaging-guidelines/#_buildrequires_and_isa, "SRPMs need to be architecture independent"). It is true that sometimes we get slightly different BuildRequires on different architectures, but in fact nobody wants this, this is just an unfortunate side effect of how the srpm is constructed. What we _want_ is srpms which are arch-independent and can be used to build the rpm on any other architecture. Is there some other dependency on the arch?

I have a similar question. I spent some time yesterday attempting to hunt down what build forge depends on this (undocumented) dependency on src RPMs being arch-dependent, and was not able to determine where any of Koji/OBS/Peridot/ALBS/mock/rpmbuild depend on the assumption that the srpm is built on a specific arch.

I am genuinely interested in learning more about this requirement as I am struggling to understand what components depend on a specific arch for srpms.

**Comment by keszybz** [comment]
> You can do many nasty things with %ifarch, e.g. not include some patch on an architecture. (But is is probably against the packaging guidelines of any distribution.)

Exactly. You *could* do this, but it doesn't make sense. Fedora packaging guidelines strongly forbid this, and probably so does everybody else who bothered to document this. So the question is whether we need to inconvenience actual users to support things that are not useful and are just a historical accident.

**Comment by pmatilai** [comment]
Different architectures having different buildrequires is not an "accident" you can swipe under the carpet.

Like said, I get that people want an arch-independent source format. But nibbling away bits and pieces from src.rpm is not going to turn it into one, it would only hurt the uses that rely on the *design* of src.rpm carrying arch-specific data. So, it needs to be something else.

One could imagine a "bare source rpm" format that basically only carries the name, version and release and the source file metadata in its header (although technically, even those are still subject to arbitrary arch-specific macro expansion). Which basically leaves you with good old tarballs...

**Comment by keszybz** [comment]
> One could imagine a "bare source rpm" format that basically only carries the name, version and release and the source file metadata in its header 

OK, can we do this and then switch the Fedora&derivatives ecosystem to this?
