### ISSUE TITLE
Making the `Optflags` and `Spec` fields in the SRPM empty for reproducibility

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#2602]
As part of the production of SRPMs, RPM injects the C/C++ compiler flags into the `Optflags` tag and a processed spec file into the `Spec` tag.

As we can't reasonably use the `Optflags` and `Spec` tags effectively for builds and it creates issues when `noarch` packages are built on different host architectures, would it be possible to make these fields empty? That way there's less weird content to deal with when verifying reproducibility and we can save some space on package header generation.

**Comment by pmatilai** [comment]
So no, RPMTAG_SPEC is not going away. It was just introduced, and it has already proven quite useful, for one to diagnose build issues in ways that were previously simply impossible.
On the contrary, ability to rebuild from RPMTAG_SPEC *without* reparsing the original spec would be a neat thing to have, for reproducability.

I symphatize with wanting a more reproducable source archive format, but cannibalizing the existing src.rpm is not the way to do get that.
