### ISSUE TITLE
RFE: allow overriding buildtime and hostname via environment variable

### ISSUE THREAD

**Issue by keszybz** [rpm-software-management/rpm#2603]
`rpm` embeds the build time and host into output headers. This is very useful to figure out when and where the build was done. But when trying to trying to reproduce an earlier rpm build, we want to override those to the value that was used in the previous build.

Please add something like `RPM_BUILDTIME` and `RPM_BUILDHOST`. When those variables would be set, rpm should use them instead of the actual values. Prior art exists with `SOURCE_DATE_EPOCH`.

(Or switches to `rpmbuild`. Or maybe both? The exact interface doesn't matter.)

**Comment by kloczek** [comment]
You can do that by `rpmbuild --define "%_buildhost <hostname>" <other_params>` or you can put permanentny line in ~/.rpmmacros like "%_buildhost <hostname>".

**Comment by dralley** [comment]
As far as BUILDHOST goes, rather than using a default value, it would be better to just disinclude the tag IMO.

**Comment by keszybz** [comment]
> As far as BUILDHOST goes, rather than using a default value, it would be better to just disinclude the tag IMO.

That is certainly an option. But people consider both BUILDTIME and BUILDHOST very useful for figuring out where/when/who exactly build a package. For example, even in Fedora infrastructure which tries to keep things very uniform, builders vary in hardware capabilities and other setup. So at the technical level, I'm weakly on the side of keeping them, but I know that if we were to try to drop those fields, it'd cause a huge discussion, and it's just not worth having that.

**Comment by dralley** [comment]
Yes, `BUILDTIME` at the very least is [complicated](https://github.com/rpm-software-management/rpm/issues/2527).  I'm not sure what infrastructure might rely on `BUILDHOST` being present, though.

**Comment by JanZerebecki** [comment]
For reproducible builds in OpenSUSE the `BUILDHOST` is set to the string `reproducible` via `%_buildhost`. The tag is not needed to get its benefit as there is an alternative way: make sure the build host is printed in the build logs (logs do not need to be reproducible), archive the logs of all builds, then for looking it up find the build log from the rpm version.

**Comment by cgwalters** [comment]
> But people consider both BUILDTIME and BUILDHOST very useful for figuring out where/when/who exactly build a package.

For Fedora using Koji, there is always exactly one Koji build for a given NEVRA, and the server side metadata contains the build host.

**Comment by ffesti** [comment]
OK, given that the `BUILDHOST` can already be set via `%_buildhost` what is still missing here? Or can we just close this ticket?

**Comment by ffesti** [comment]
Guess not. Feel free to re-open if we missed something and there is really something that needs doing.

**Comment by Conan-Kudo** [comment]
> For reproducible builds in OpenSUSE the `BUILDHOST` is set to the string `reproducible` via `%_buildhost`. The tag is not needed to get its benefit as there is an alternative way: make sure the build host is printed in the build logs (logs do not need to be reproducible), archive the logs of all builds, then for looking it up find the build log from the rpm version.

@JanZerebecki Just FYI, neither SUSE nor openSUSE do this currently. Logs are lost for old builds generally. So is most of the build environment information. And for openSUSE Leap, the situation is much worse: the stuff provided from SLE has no public records at all of the build.

**Comment by mlschroe** [comment]
SLE has the slsa provenance files.
