### ISSUE TITLE
Document new test-suite backend

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#2611]
Add a bit more text to `tests/README.md` about the new test-suite layout from #2559 and while at it, write a short howto on test writing, too. A file describing the mktree interface (`mktree.README`) may also be helpful. Lastly, a Known issues section wouldn't hurt either since we have at least two known, intermittent false positive failures, as mentioned in #2470.

**Comment by dmnks** [comment]
For now, let's just focus on the user side of things in the `README.md` file. The internal architecture of the test suite will be described later, perhaps together with a "how to write a test" section.

**Comment by pmatilai** [comment]
As discussed separately, dropping the milestone afterall: this is basically developer-only docs, and developers are expected to be looking at git master, not release tarball. So it's not critical that this documentation makes it to rc.

**Comment by dmnks** [comment]
Yup, thanks for bringing us back to sanity here :smile: It really can wait, more so that we're still planning some changes to the test suite implementation.
