### ISSUE TITLE
Duplicate lines? %transfiletriggerun

### ISSUE THREAD

**Issue by jn64** [rpm-software-management/rpm#2613]
I noticed these duplicate lines and couldn't see a reason why it exists:

https://github.com/rpm-software-management/rpm/blob/224095542246e762617d38e2096fdeba13d266e3/build/parseSpec.c#L75-L76

**Comment by pmatilai** [comment]
Yep, it's a pretty obvious accidental duplicate (even if harmless), innocuously sitting there for eight years.
Thanks for spotting and reporting.

**Comment by jn64** [comment]
I found it via rpm-spec-mode for Emacs; the duplication was reproduced there 8 years ago... incidentally, by the author of the indentation fix here :)

https://github.com/stigbjorlykke/rpm-spec-mode/blame/c1c38050c48ea330c7cea632b8785d66daeefb2b/rpm-spec-mode.el#L255
