### ISSUE TITLE
Eliminate --pkgid and --hdrid commandline switches

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2633]
As pointed out by @dralley in https://github.com/rpm-software-management/rpm/discussions/2374#discussioncomment-6826927: we support indexed db queries for "pkgid" and "hdrid", which are actually backed by SIGMD5 and SHA1HEADER tags. These aren't really security sensitive because they're just an identifier in this context, but both will be gone in the v6 format, so we need to eliminate these indexes based on obsolete crypto, and if pkgid/hdrid concepts are to be preserved (I don't know anybody using them so dunno), figure out something that doesn't have an expiration date like the crypto functionality nowadays.

### AC:
- --pkgid and --hdrid cli switches and corresponding documentation is removed
- RPMDBI_SIGMD5 and RPMDBI_SHA1HEADER are documented as deprecated

**Comment by dralley** [comment]
>(I don't know anybody using them so dunno)

@Conan-Kudo I believe you may have mentioned in the past that the MD5 headers (pkgid) are used in some build systems?

**Comment by Conan-Kudo** [comment]
Yes. I think Koji did at one point, and OBS does last I checked.

**Comment by pmatilai** [comment]
Yes various places show them because ... it's there. And course, for the longest time that was the only checksum kind of thing that we had on the payload.

**Comment by pmatilai** [comment]
This is basically three different but related parts:
- the db indexes themselves
- the --hdrid and --pkgid query flags
- RPMTAG_PKGID and RPMTAG_HDRID tag aliases

Then there's also RPMTAG_SOURCEPKGID that's still md5 but that is a separate topic and needs a separate ticket too.

**Comment by pmatilai** [comment]
Split the pkgid/hdrid tag aliases to a separate ticket too, they're not actually used for the database operation: #3330

**Comment by pmatilai** [comment]
And, from there we get to something resembling an AC:
- RPMDBI_SIGMD5 and RPMDBI_SHA1HEADER indexes are not generated for new databases. In existing databases, stale references must not be left behind.
- --hdrid and --pkgid cli switches are removed - in my >= 20 years of rpm, I've yet to see anybody actually use these

**Comment by dmnks** [comment]
>     * --hdrid and --pkgid cli switches are removed - in my >= 20 years of rpm, I've yet to see anybody actually use these

Is the removal of these two switches settled then? Also, isn't the new #3330 related to this in a way? I.e. if we end up keeping the aliases, shouldn't we also keep the CLI switches?

**Comment by dmnks** [comment]
Well, OK, that's why you were asking for feedback in the first place (while you also justified the removal) :smile:

**Comment by dmnks** [comment]
I also think that removing obscure functionality makes sense unless we know of some users (and we don't here). It can always be added back in the future if there's enough interest...

**Comment by pmatilai** [comment]
The PKGID and HDRID tags are not used for the index generation, or query. The db index uses RPMDBI_SIGMD5 and RPMDBI_SHA1HEADER, which "happen to be" equivalent to RPMTAG_SIGMD5 and RPMTAG_SHA1HEADER.
so the PKGID and HDRID tags could be removed and I think rpm would still compile and work, something external may be using those though.

So while they appear related, they're much less so than you'd initially think - I too thought it was more closely bound.

**Comment by dmnks** [comment]
Oh, looking at the code here too, you're right.

**Comment by pmatilai** [comment]
So in other words, its two practically unused tags, practically unused cli-switches, backed by two practically unused db indexes :facepalm: :laughing: 

We could keep --pkgid and --hdrid without the indexes and just do a brute-force search, but there seems little point in preserving this functionalty. Who wants to query the db based on an header hash they likely don't know even exists in the first place?

**Comment by dmnks** [comment]
Yup, makes sense now, thanks :smile: As for the first AC point:
> In existing databases, stale references must not be left behind.
This part still sounds quite vague (to me)...

**Comment by pmatilai** [comment]
> > In existing databases, stale references must not be left behind.
> 
> This part still sounds quite vague (to me)...

Basically that means in existing databases, we need to keep updating the indexes. Minimally, we need to update the index on package removal. If we just drop the code, we could leave orphans in the index. If we actually cared about this functionality we'd require maintining the index for new items on existing dbs too, but since we dont, just taking care of orphans seems enough to me. Whether it actually makes sense to implement it that way or preserve both, I don't know, I haven't really looked (trying to play brave :smile: )

**Comment by pmatilai** [comment]
Hmm. On a second thought: we could simply just remove the query switches for now, and leave the db indexes to die of old age, and bury in rpm 7.0. That preserves them for existing databases and in new ones they'll eventually just grow empty because the data is not there. These indexes are not expensive to maintain in any way, and actually trying to remove them is far more tricky than just letting them be.

**Comment by pmatilai** [comment]
So... that would make an AC something like: 

- --pkgid and --hdrid cli switches and corresponding documentation is removed
- RPMDBI_SIGMD5 and RPMDBI_SHA1HEADER are documented as deprecated

That would let us off the hook with minimal effort, this isn't a very interesting item from v6 perspective.

**Comment by dmnks** [comment]
Ack, this looks like the right amount of effort for such a tiny thing, indeed.
