### ISSUE TITLE
4.18.99: no test suite?🤔

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#2648]
Just started refreshing my rpm package with rpm to latest version and found that despite run cmake with `ENABLE_TESTSUITE=ON` ctest is not able to run any test units
```console
+ cd rpm-4.18.99
+ /usr/bin/ctest --test-dir x86_64-redhat-linux-gnu --output-on-failure --force-new-ctest-process -j48 /usr/bin/chmod -R a+rwX .
Internal ctest changing into directory: /home/tkloczko/rpmbuild/BUILD/rpm-4.18.99/x86_64-redhat-linux-gnu
Test project /home/tkloczko/rpmbuild/BUILD/rpm-4.18.99/x86_64-redhat-linux-gnu
No tests were found!!!
```

**Comment by dmnks** [comment]
We don't support ctest. The test suite is run with `make check`, see the [README](https://github.com/rpm-software-management/rpm/blob/master/tests/README.md).

**Comment by dmnks** [comment]
Also, the `ENABLE_TESTSUITE` option no longer has any effect. The test suite is enabled based on whether the host has the necessary test dependencies (Bubblewrap or Podman/Docker) or not.

This is, sadly, not yet documented. We're planning to do fix that.

**Comment by kloczek** [comment]
> We don't support ctest. The test suite is run with `make check`, see the [README](https://github.com/rpm-software-management/rpm/blob/master/tests/README.md).

(just humble question)
OK but why? 🤔

**Comment by dmnks** [comment]
Let me revert the question: What makes you think we *should* support ctest? Just because we use cmake?

**Comment by kloczek** [comment]
Because ctest is standard cmake tool and it is supported directly by cmake files allowing OOTB for example parallelisation of ctest units execution (it allows as well exclude some exact units paralel execution https://www.scivision.dev/cmake-resource-lock-ctest/ .. .if it was the cause of not choosing ctest).
Why to maintain own test suite framework? 🤔

**Comment by dmnks** [comment]
> Why to maintain own test suite framework? 🤔

Oh, and it's not our *own* test framework, I'm not sure where you've that impression.

**Comment by kloczek** [comment]
Still execution of that test suite script IMO should be done over ctest.
This would allow easier migration to execute units over ctest.

**Comment by dmnks** [comment]
Please suggest that in the ticket I linked above, together with the exact reason why you think it would be better. Thanks!
