### ISSUE TITLE
RFE: Make `%setup` work with archives regardless of inner structure

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#2664]
In a conversation in [`#devel:fedoraproject.org`](https://matrix.to/#/#devel:fedoraproject.org) with @penguinpee, I realized that there's a potential quality of life improvement we could look into making around `%setup`: Making it so we don't ever need to use `-n`.

It started with asking about how to pass in `--strip-components=1` to `%setup`, and I realized something: now that libarchive exists, it would be possible for us to have a universal unarchiver program with RPM that can give us the ability to automatically handle extracting archives properly, regardless of what the name of the top level directory is or whether there is even one at all.

For some prior art, Debian's packaging tooling can do this, and it uses that to 1) extract the tarball into a `name-version` directory, and 2) blow away `debian` directory of an upstream tarball if it exists so its own version can be unpacked in-tree.

Obviously, we don't need to do the second thing, but the first thing would be extremely useful. Note that because of compatibility concerns, we'd probably want this new behavior in a new macro.

**Comment by Conan-Kudo** [comment]
Note that because of compatibility concerns, we'd probably want this new behavior in a new macro.

**Comment by pmatilai** [comment]
Right, this closely relates to #2078 as well. 

Libarchive is currently an optional dependency, but a hard dep wouldn't be the end of the world.

**Comment by Conan-Kudo** [comment]
> Note that because of compatibility concerns, we'd probably want this new behavior in a new macro.

We could make `%autosetup` use this behavior by default when `-n` isn't present, though. It's a "do-what-I-mean" change that would be beneficial for most.

**Comment by penguinpee** [comment]
> We could make `%autosetup` use this behavior by default when `-n` isn't present, though. It's a "do-what-I-mean" change that would be beneficial for most.

That would bring it in line with the way `%forgeautosetup` behaves. I assume that would be beneficial to both.

**Comment by teknoraver** [comment]
@Conan-Kudo how libarchive can help in detect if the archive needs to be extracted as is or in a subdirectory?
Is there a]is some function to detect it, or we need to inspect the archive to see if the root entry has just one entry?

**Comment by Conan-Kudo** [comment]
I believe we have to inspect it to check.

**Comment by teknoraver** [comment]
In simple words the logic will be: if the archive contains a single entry extract it as is, otherwise create an entry like $name-$version?

**Comment by Conan-Kudo** [comment]
Yup.

**Comment by Conan-Kudo** [comment]
Not quite. If it contains a single entry, strip it. Always create the directory `%name-%version` and extract into it.

**Comment by teknoraver** [comment]
I have a draft change in https://github.com/teknoraver/rpm/tree/libarchive2

Most of the work needed to be done in `rpmuncompress`, I added a `-p` flag which does the following:
```
$ tar vtf source-singleroot.tar.gz
drwxr-xr-x root/root         0 2024-01-16 19:13 source-xxxxxxxxxx/
-rw-r--r-- root/root        32 2024-01-16 19:13 source-xxxxxxxxxx/file1
-rw-r--r-- root/root     33886 2024-01-16 19:13 source-xxxxxxxxxx/file2
drwxr-xr-x root/root         0 2024-01-16 19:13 source-xxxxxxxxxx/dir1/
-r--r--r-- root/root       210 2024-01-16 19:13 source-xxxxxxxxxx/dir1/file3

$ tar vtf source-noroot.tar.gz
drwxr-xr-x root/root         0 2024-01-16 19:13 dir1/
-r--r--r-- root/root       210 2024-01-16 19:13 dir1/file3
-rw-r--r-- root/root        32 2024-01-16 19:13 file1
-rw-r--r-- root/root     33886 2024-01-16 19:13 file2

$ ll
total 28
-rw-r--r--. 1 teknoraver teknoraver 10324 Jan 16 19:14 source-noroot.tar.gz
-rw-r--r--. 1 teknoraver teknoraver 10520 Jan 16 19:14 source-singleroot.tar.gz
-rw-r--r--. 1 teknoraver teknoraver   649 Jan 15 20:54 test.spec

$ ~/rpm/usr/lib/rpm/rpmuncompress -x -v -p source-1.0.0 source-singleroot.tar.gz
mkdir 'source-1.0.0' ;  /usr/bin/gzip -dc  'source-singleroot.tar.gz' | /usr/bin/tar -xvvof -  -C 'source-1.0.0' --strip-components=1
-rw-r--r-- root/root        32 2024-01-16 19:13 source-xxxxxxxxxx/file1
-rw-r--r-- root/root     33886 2024-01-16 19:13 source-xxxxxxxxxx/file2
drwxr-xr-x root/root         0 2024-01-16 19:13 source-xxxxxxxxxx/dir1/
-r--r--r-- root/root       210 2024-01-16 19:13 source-xxxxxxxxxx/dir1/file3

$ find source-1.0.0 -ls
    92341      0 drwxr-xr-x   1 teknoraver teknoraver       28 Jan 16 19:16 source-1.0.0
    92342      4 -rw-r--r--   1 teknoraver teknoraver       32 Jan 16 19:13 source-1.0.0/file1
    92343     36 -rw-r--r--   1 teknoraver teknoraver    33886 Jan 16 19:13 source-1.0.0/file2
    92344      0 drwxr-xr-x   1 teknoraver teknoraver       10 Jan 16 19:13 source-1.0.0/dir1
    92345      4 -r--r--r--   1 teknoraver teknoraver      210 Jan 16 19:13 source-1.0.0/dir1/file3

$ ~/rpm/usr/lib/rpm/rpmuncompress -x -v -p source-2.0.0 source-noroot.tar.gz
mkdir 'source-2.0.0' ;  /usr/bin/gzip -dc  'source-noroot.tar.gz' | /usr/bin/tar -xvvof -  -C 'source-2.0.0'
drwxr-xr-x root/root         0 2024-01-16 19:13 dir1/
-r--r--r-- root/root       210 2024-01-16 19:13 dir1/file3
-rw-r--r-- root/root        32 2024-01-16 19:13 file1
-rw-r--r-- root/root     33886 2024-01-16 19:13 file2

$ find source-2.0.0 -ls
    92346      0 drwxr-xr-x   1 teknoraver teknoraver       28 Jan 16 19:17 source-2.0.0
    92347      0 drwxr-xr-x   1 teknoraver teknoraver       10 Jan 16 19:13 source-2.0.0/dir1
    92348      4 -r--r--r--   1 teknoraver teknoraver      210 Jan 16 19:13 source-2.0.0/dir1/file3
    92349      4 -rw-r--r--   1 teknoraver teknoraver       32 Jan 16 19:13 source-2.0.0/file1
    92350     36 -rw-r--r--   1 teknoraver teknoraver    33886 Jan 16 19:13 source-2.0.0/file2
```

**Comment by teknoraver** [comment]
Done in #2859

**Comment by pmatilai** [comment]
Oh, yup, this can be closed now. Thanks again!
