### ISSUE TITLE
Fail test image build on cmake failure

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#2667]
A failure to build rpm (and install it into the podman image) should make the whole process fail, otherwise the tests will be run and wonder where the rpm binary went, like here: https://github.com/rpm-software-management/rpm/actions/runs/6195864740/job/16821378763

**Comment by pmatilai** [comment]
I've no idea about the GH actions magic and how feasible this is, but if possible, it would be good to separate the environment building and rpm compilation steps into stages that can individually fail + stop the train.

**Comment by Conan-Kudo** [comment]
The container environment is reused for each step in a "job", but each job is separate.

**Comment by dmnks** [comment]
Turns out that a step that fails terminates the whole job, of course, so it's not a matter of configuration but rather a bug in the `mktree` script which currently doesn't terminate on a failed `make install`. Working on a fix.
