### ISSUE TITLE
Strange doc

### ISSUE THREAD

**Issue by korpe1** [rpm-software-management/rpm#2673]
What this means? "the package can be safely removed without removing /bin/sh"?

> A virtual package with
> 
>     Provides: /bin/sh
> 
> differs from a package that has /bin/sh in the %files list in that the package can be safely removed without removing /bin/sh.

Source: https://rpm-software-management.github.io/rpm/manual/dependencies.html#provides

**Comment by encukou** [comment]
Would this be a better wording?

> differs from a package that has /bin/sh in the %files list. For example, rpm will not remove `/bin/sh` when the package is uninstalled.
