### ISSUE TITLE
elfdeps not available on Mac OS, rpmbuild now fails 

### ISSUE THREAD

**Issue by elecharny** [rpm-software-management/rpm#2682]
While ```rpmbuild``` was working for a while on **Mac OS**, it's not anymore the case. we now get errors like:

```
error : Cannot execute /usr/local/Cellar/rpm/4.18.1/lib/rpm/elfdeps : No such file or directory
```

The ```elfdeps``` tool is not available on **Mac OS**, as trying to install ```elfutils``` ends with 👍 

```
elfutils: Linux is required for this software.
Error: elfutils: An unsatisfied requirement failed this build.
```

**Comment by pmatilai** [comment]
We don't provide builds or packaging for any platform. You need to report that to whoever maintains that build/package.

**Comment by elecharny** [comment]
@pmatilai Fine. Should I understand that the elfdeps depedency is platform dependent?

**Comment by pmatilai** [comment]
That question doesn't really make sense in the upstream context because there's no "elfdeps dependency" anywhere.

Building the elfdeps tool requires the libelf library. I'm not aware of it being a Linux-only thing but that doesn't much.
