### ISSUE TITLE
rpm --import url shows non-specific error message when curl is not available

### ISSUE THREAD

**Issue by andrii-suse** [rpm-software-management/rpm#2683]
Snippet below first shows that import command works successfully, then it shows generic error message when curl is uninstalled from the system
```
# rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
# echo $?
0
# rpm -e curl
# rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
error: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB: import read failed(2).
# rpm -vvv --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
ufdio:       1 reads,    19077 total bytes in 0.000005 secs
error: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB: import read failed(2).
```

rpm should e.g. show exact failing command, at least when verbosity is increased.

**Comment by pmatilai** [comment]
Seems we've duped this ticket by ourselves, but since that's the one with more discussion by now, closing this in favor of #3041

**Comment by pmatilai** [comment]
Ehm, except that was a PR not ticket.
