### ISSUE TITLE
Wrong src RPM deps parsing by rpmbuild

### ISSUE THREAD

**Issue by socketpair** [rpm-software-management/rpm#2690]
`rpm -qRp /home/fedora/rpmbuild/SRPMS/frr-8.5.2-2.1696341206.16.8ff8ce50.utm.src.rpm`:

gives the following:

```
...
perl-XML-LibXML
perl-generators
python3-devel
...
```

That's OK.  Nothing about pkgconfig.

Now, try to build it:

`rpmbuild --verbose --debug -rr /home/fedora/rpmbuild/SRPMS/frr-8.5.2-2.1696341206.16.8ff8ce50.utm.src.rpm`

```
Last login: Tue Oct  3 14:43:10 UTC 2023 on pts/0
Installing /home/fedora/rpmbuild/SRPMS/frr-8.5.2-2.1696341206.16.8ff8ce50.utm.src.rpm
D: loading keyring from rpmdb
D: PRAGMA secure_delete = OFF: 0
D: PRAGMA case_sensitive_like = ON: 0
D:  read h#       1 
Header SHA256 digest: OK
Header SHA1 digest: OK
D: added key gpg-pubkey-5323552a-6112bcdc to keyring
D: /home/fedora/rpmbuild/SRPMS/frr-8.5.2-2.1696341206.16.8ff8ce50.utm.src.rpm: Header SHA256 digest: OK
D: /home/fedora/rpmbuild/SRPMS/frr-8.5.2-2.1696341206.16.8ff8ce50.utm.src.rpm: Header SHA1 digest: OK
D:   install: frr-8.5.2-2.1696341206.16.8ff8ce50.utm.x86_64 has 13 files
D: create     100644  1 (1000,1000)  1364 0000-remove-babeld-and-ldpd.patch;651c292f
D: create     100644  1 (1000,1000)  1740 0002-enable-openssl.patch;651c292f
D: create     100644  1 (1000,1000)  6746 0003-disable-eigrp-crypto.patch;651c292f
D: create     100644  1 (1000,1000)  3619 0004-fips-mode.patch;651c292f
D: create     100644  1 (1000,1000)   870 0005-remove-grpc-test.patch;651c292f
D: create     100644  1 (1000,1000)  1619 0007-ideco-route-table.patch;651c292f
D: create     100644  1 (1000,1000)9881857 frr-8.5.2.tar.gz;651c292f
D: create     100644  1 (1000,1000)   185 frr-sysusers.conf;651c292f
D: create     100644  1 (1000,1000)    26 frr-tmpfiles.conf;651c292f
D: create     100644  1 (1000,1000)  1633 frr.fc;651c292f
D: create     100644  1 (1000,1000)  4177 frr.if;651c292f
D: create     100644  1 (1000,1000) 16037 frr.spec;651c292f
D: create     100644  1 (1000,1000)  3511 frr.te;651c292f
setting SOURCE_DATE_EPOCH=1696204800
D: ========== +++ frr-8.5.2-2.1696341206.16.8ff8ce50.utm x86_64/linux 0x0
.......
D:  read h#     474 
Header V4 RSA/SHA256 Signature, key ID 5323552a: OK
Header SHA256 digest: OK
Header SHA1 digest: OK
D:  Requires: perl-generators                               YES (db provides)
D:  Requires: pkgconfig(systemd)                            NO    <<<<======================================
D:  read h#     480 
Header V4 RSA/SHA256 Signature, key ID 5323552a: OK
Header SHA256 digest: OK
Header SHA1 digest: OK
D:  Requires: python3-devel                                 YES (db provides)
...
error: Failed build dependencies:
	pkgconfig(systemd) is needed by frr-8.5.2-2.1696341206.16.8ff8ce50.utm.x86_64
```

So, WHY? From one point of view it's not in dependencies, from another – it is.

RPM version 4.18.1

File is attached. Sorry for zip. GitHub does not allow attaching just rpm.

[frr-8.5.2-2.1696341206.16.8ff8ce50.utm.src.zip](https://github.com/rpm-software-management/rpm/files/12793803/frr-8.5.2-2.1696341206.16.8ff8ce50.utm.src.zip)

**Comment by socketpair** [comment]
Moreover, I don't understand how it appears in this srpm file. This file was made in our build scripts.

**Comment by pmatilai** [comment]
The dependencies recorded in an src.rpm are only valid for the environment (including any cli-switches) it was generated in. It's entirely possible to end up with something quite different on a spec reparse, which is what happens on any build.

As for pkg-config deps, I see this in the spec, which makes me wonder:

```
# .........
# BuildRequires:  pkgconfig(systemd)
# BuildRequires: selinux-policy-devel
```

I can't reproduce any pkgconfig deps appearing in the build, and I can't imagine rpm hallucinating them up either (this is certainly not AI :sweat_smile: ). I suggest you double check your findings.

**Comment by pmatilai** [comment]
BTW, it's also technically possible to (externally) rewrite the specfile after launching a build on it, and end up with wildly different in the src.rpm than what the build was launched with. It would be a nasty thing to do of  course, but technically possible, and could explain oddities like this when external build scripts are involved.

**Comment by socketpair** [comment]
@pmatilai Commented things – are my lines – I did not remove after experiments. Yes, our scripts build `.src.rpm` from `.spec` file and then (in the same environment) install build deps. The problem that `rpmbuild -rr` says about missing deps, but `dnf builddep` does not install them (does not see them).

**Comment by pmatilai** [comment]
The one thing -bs and -br *will* disagree with is dynamic buildrequires from %generate_buildrequires. I don't see that in the src.rpm but I don't know what macros and stuff you may have locally.

**Comment by pmatilai** [comment]
I suggest you try reproducing it in a different environment. A clean container image or such.

**Comment by pmatilai** [comment]
Oh, I see it now. Try 'rpmspec --parse frr.spec' to see how it looks to rpm, and it becomes quite clear.

The pkgconf(systemd) dependency comes from the `%{?selinux_requires}` macro. And if rpmbuild -bs is executed in an environment where that macro is not defined then it will miss those defines and no error message will be emitted because it's a conditional macro like that.

No bug here.

**Comment by socketpair** [comment]
@pmatilai I always run everything in a clear environment. i.e. in the container, yes.

Does `rpmbuild -rr` re-parse .spec-file ? Thought it does not.

**Comment by socketpair** [comment]
@pmatilai sorry for bash script, but I want just show what happens in our build script:

```bash
    unpriv rpmbuild "${defines[@]}" -bs "$spec_file" --rmspec
    srpm=("$RPMBUILD"/SRPMS/*.src.rpm)
    while :; do
        unpriv rpmbuild "${defines[@]}" -rr "$srpm" && exit_code=0 || exit_code=$?
        case "$exit_code" in
            0)
                break
                ;;
            11)
                reqsrpm=("$RPMBUILD"/SRPMS/*.buildreqs.nosrc.rpm)
                if [ -f "$reqsrpm" ]; then
                    install_deps "$reqsrpm"
                    rm -f "$reqsrpm"
                else
                    install_deps "$srpm"
                fi
                ;;
            *)
                echo "rpmbuild -rr FAILED code $exit_code" >&2
                exit 42
                ;;
        esac
    done
```

And on this package it falls into endless loop. Note, environment is exactly the same on both rpmbuild runs.

**Comment by socketpair** [comment]
@pmatilai sorry for not explaining clearly. Seems it is another bug. When `-rr` says error about missing deps but does not generate `.buildreqs.nosrc.rpm` in some conditions. In generally – yes, it works as expected. Especially on pyproject srpms, where 3-5 iterations are possible.

**Comment by socketpair** [comment]
Interesting... `-rr --nodeps` rewrites .src.rpm in a way that `dnf` INSTALLS `pkgconfig(systemd)` afterwards.

**Comment by pmatilai** [comment]
Rpm doesn't use the dependencies recorded into an src.rpm in any circumstance, the spec is always reparsed. I don't know what the difference between rpmbuild -bs and -br is in your environment, but that's where the issue is.

**Comment by socketpair** [comment]
@pmatilai there are no difference. Really. I have provided part of the shell script. Tell me how to debug, please. I strongly consider there is a bug in RPM, but con not knock it down.

**Comment by socketpair** [comment]
Seems I figured out. After installing deps from file generated by `-bs` some macroses appear. that's what is changed in environment.

So the bug is: not generating `.buildreqs.nosrc.rpm`. If it was generated, bug would not happen.

**Comment by socketpair** [comment]
Seems dup of #797

**Comment by socketpair** [comment]
#781
