### ISSUE TITLE
SourceRequires and %source tags

### ISSUE THREAD

**Issue by huakim** [rpm-software-management/rpm#2709]
Please, add SourceRequires: tag and %source for fetching and generating sources for  source rpms

**Comment by FrostyX** [comment]
This is "closed as completed", was it really implemented? Would be very helpful for
https://forge.fedoraproject.org/packaging/guidelines/issues/1132

**Comment by dmnks** [comment]
It's not implemented, the ticket was closed by the reporter right away. Maybe open a new one (with some more details if possible)?

**Comment by dmnks** [comment]
In the meantime, fixing the closure resolution as per above (thanks).
