### ISSUE TITLE
Test-data not updated in test-suite

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2725]
When you change something in tests/data, it doesn't get automatically refreshed into the actual test-root (mktree.output I guess). Makes it painful to work on (new) tests when you change something and then nothing seems to happen.

Technically we're missing dependencies on all the data/ stuff on the check target, but we never had those, instead we just unconditionally copied the data over every time. That seems to have gotten lost in the fakechroot -> inception swapover.

**Comment by dmnks** [comment]
Ack, this must be a bug then, will fix, thanks!
