### ISSUE TITLE
built-in sysusers.d support fails to parse config files?

### ISSUE THREAD

**Issue by decathorpe** [rpm-software-management/rpm#2741]
I'm packaging something that uses sysusers.d config snippet for the first time, and I'm getting this error from RPM (?) after a successful build:

```
error: lua script failed: [string "add_sysuser"]:16: invalid sysuser type: #Type
  3<        (%lua)
  2<      (%add_sysuser)
```

It appears that the sysusers.d config snippet parser fails to parse (or rather, ignore) comments?

The line starting with `#Type`  is from the sysusers.d documentation:
https://www.freedesktop.org/software/systemd/man/latest/sysusers.d.html

**Comment by pmatilai** [comment]
Yup, this appears to be a bug, comments need to be accepted.
Also reported at https://bugzilla.redhat.com/show_bug.cgi?id=2246236 but thanks for filing upstream, it's far more convenient for us.
