### ISSUE TITLE
_debugsource_packages sometimes crashes due to non-existing debugsourcefiles.list

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#279]
Partially found in #277, although I think it makes sense to track it here separately.

```
Processing files: gdb-debugsource-8.0-17.fc27.x86_64
RPM build errors:
error: Could not open %files file /builddir/build/BUILD/gdb-8.0/debugsourcefiles.list: No such file or directory
    Could not open %files file /builddir/build/BUILD/gdb-8.0/debugsourcefiles.list: No such file or directory
```

**Comment by rpm-maint** [comment]
On Tue, 2017-07-25 at 15:11 -0700, Igor Gnatenko wrote:
> Partially found in #277, although I think it makes sense to track it here separately.
> 
> ```
> Processing files: gdb-debugsource-8.0-17.fc27.x86_64
> RPM build errors:
> error: Could not open %files file /builddir/build/BUILD/gdb-8.0/debugsourcefiles.list: No such file or directory
>     Could not open %files file /builddir/build/BUILD/gdb-8.0/debugsourcefiles.list: No such file or directory
> ```

See http://lists.rpm.org/pipermail/rpm-maint/2017-July/006072.html

**Comment by xsuchy** [comment]
This still happens to me on F29 (with most recent rpm). With exactly the same errors. The weird thing is that I am not alone, it happens to some participant of rpm packaging workshop too. The weird part is that when I generate src.rpm and then build it in mock, it passes without a problem.

**Comment by xsuchy** [comment]
My system tries to execute:
```
/usr/lib/rpm/find-debuginfo.sh -l4 --strict-build-id -m -i --build-id-seed 1.1-15.fc29 --unique-debug-suffix -1.1-15.fc29.x86_64 --unique-debug-src-base enum-1.1-15.fc29.x86_64 --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 -S debugsourcefiles.list /home/msuchy/rpmbuild/BUILD/enum-1.1
```
Which interestingly results to `BUILDDIR=-l4` and then it goes wrong.

**Comment by pmatilai** [comment]
Interesting. That -l4 is supposed to be -j4, and apparently find-debuginfo just takes anything unknown as the builddir.

@xsuchy , what does ```rpm --eval "%{_smp_mflags}"``` output on that system?

**Comment by xsuchy** [comment]
Got it. It is because:
```
rpm --eval '%{?_smp_mflags}'
-l4
```
which for Makefile has semantics:
```
       -l [load], --load-average[=load]
            Specifies  that  no  new jobs (commands) should be started if there are others jobs running and the load average is at least load (a floating-point
            number).  With no argument, removes a previous load limit.
```
But find-debuginfo.sh does not recognize it and interpet it differently.

I will open new issue for that.

**Comment by xsuchy** [comment]
I filed:
https://github.com/rpm-software-management/rpm/issues/630
