### ISSUE TITLE
Adding an LMDB backend to RPM

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#281]
There have been years of vitriol about Berkeley DB and numerous suggested database replacements for RPM.

LMDB is perhaps the best choice because LMDB is most similar to Berkeley DB in API and design.

Attached is a patch to add an LMDB backend to RPM.

I will supply an updated lmdb.c implementation as certain plateau's are achieved.

The first plateau is the ability to iterate through all packages retrieving headers: DONE.

[rpm+lmdb-20170726.patch.gz](https://github.com/rpm-software-management/rpm/files/1176900/rpm.lmdb-20170726.patch.gz)

[lmdb.c-20170726.gz](https://github.com/rpm-software-management/rpm/files/1176907/lmdb.c-20170726.gz)

**Comment by mlschroe** [comment]
Well, "most similar to Berkeley DB" is maybe not the perfect way to choose a database ;)

Anyway, another database backend to test is good to have. Thanks for spending your time on this!

**Comment by n3npq** [comment]
One has to factor in the context of "choice": I'm tired of years of belly aching about RPM databases from the uninformed. That's a very different context than "most similar".

The flaws in the rpmdb implementation have nothing whatsoever to do with what database implementation is chosen.

**Comment by n3npq** [comment]
Next plateau: Retrieve header from secondary -> primary lookup: DONE.

(stoopid brain fart from rescoping the byte swapped hdrNum with an address in a MDB_val)

[lmdb.c-20170726.1.gz](https://github.com/rpm-software-management/rpm/files/1177633/lmdb.c-20170726.1.gz)

Now for package management queries and installations ... then start with configuration/conversion dreariness.

**Comment by n3npq** [comment]
Next plateau: Ensure --query/--install/--rebuilddb are functional: DONE

(there are fundamental design flaws (and bugs) with the current RPM+BDB: there is no concept of "durability" as in ACID that can be discussed meaningfully for starters.)

On to conversion: there's almost no reason to deal with configuration (but I'll twiddle up some knobs for the clueless to benchmark and feel importantly impotent ...

[lmdb.c-20170726.2.gz](https://github.com/rpm-software-management/rpm/files/1178076/lmdb.c-20170726.2.gz)

**Comment by n3npq** [comment]
Next plateau: Convert a BDB -> LMDB database.

Two simple scripts to assist with the conversion.

[bdbexport.sh.gz](https://github.com/rpm-software-management/rpm/files/1180126/bdbexport.sh.gz)

[lmdbimport.sh.gz](https://github.com/rpm-software-management/rpm/files/1180129/lmdbimport.sh.gz)

Note that you will need mdb_dump/mdb_load/mdb_stat executables, which seem not to be included in the CentOS7/Fedorable lmdb packages for whatever reason.

The only subtlety -- and the same issue exists with RPM+BDB, but unseen because hash rather than btree is used -- in the conversion is byte swabbing the primary keys in Packages.

And finally, here is the patch to RPM and the lib/backend/lmdb.c file:

[rpm+lmdb.patch.gz](https://github.com/rpm-software-management/rpm/files/1180172/rpm.lmdb.patch.gz)

[lmdb.c.gz](https://github.com/rpm-software-management/rpm/files/1180173/lmdb.c.gz)

The LMDB implementation has been deliberately left heavily insturmented with debugging in order to diagnose issues. There's more that could be done to simplify the code: I have deliberately chosen a rather simplistic/redundant style while studying what return codes need to be handled.

Assuming there is any interest in RPM+LMDB: judging from the time scale of NDB adoption, I am expecting a merge in 2019, and perhaps a discussion of adoption in Fedora in 2020, and perhaps a deployment in Fedora 40.

We shall see ...

... but I'm done with the RPM+LMDB issue for now. Have fun!

**Comment by n3npq** [comment]
In order to run queries as non-root, there are three minor changes:

1) lock.mdb (an 8Kb file) needs to be 0666, other perms as expected.

2) don't bother retrying mdb_env_open(): I added this line to display errors as well:
```
rpmlog(RPMLOG_ERR, "lmdb: %s(%s/lock.mdb): %s\n", __FUNCTION__, dbhome, mdb_strerror(rc));
```

3) this 1-liner needs to be added in mdb_dbi_open() to create a RDONLY txn:
```
    unsigned tflags = access(dbhome, W_OK) ? MDB_RDONLY : 0;
```

With those changes (and an /etc/popt alias to hide the goopy cmdline)
```
rpm	alias	--lmdb -D '_db_backend lmdb' --dbpath=/var/lib/lmdb
```

I see the following timings on whatever I happen to have installed on CentOS7:

```
$ /usr/bin/time ./rpm -qa > /dev/null
3.25user 0.13system 0:03.38elapsed 100%CPU (0avgtext+0avgdata 22820maxresident)k
0inputs+0outputs (0major+9477minor)pagefuls 0swaps

$ /usr/bin/time ./rpm --lmdb -qa > /dev/null
2.19user 0.07system 0:02.26elapsed 100%CPU (0avgtext+0avgdata 166940maxresident)k
0inputs+8outputs (0major+47059minor)pagefuls 0swaps

```

Much simpler (and more reliable) than what BDB does to read as non-root.

However, I expect that something similar could be done with BDB and permissions on the environment if anyone really cared.

**Comment by n3npq** [comment]
One last comparison: RPM5 uses BerkeleyDB too, but with different tunables than RPM4.

Here's essentially the same measurement as the previous comment:
```
1.15user 0.87system 0:02.11elapsed 96%CPU (0avgtext+0avgdata 584900maxresident)k
240inputs+390776outputs (7major+355303minor)pagefaults 0swaps
```

I add this comment to squelch BerkeleyDB haters from taking my measurements and claiming

```"LMDB is Newer! Better! Faster! than BDB."```

I suspect the tunable that makes a huge difference is mmapsize (RPM5 sets this to 256Mb).

**Comment by n3npq** [comment]
For completeness, here is the same measurement with RPM+NDB:
```
$ /usr/bin/time ./rpm -qa --ndb > /dev/null
3.25user 0.13system 0:03.38elapsed 100%CPU (0avgtext+0avgdata 17664maxresident)k
0inputs+0outputs (0major+8164minor)pagefaults 0swaps
```

**Comment by n3npq** [comment]
After adding equivalent disabling of fsync and its ilk to mdb_env_open():
```
        eflags |= MDB_FIXEDMAP;
#ifndef HACK
        eflags |= MDB_WRITEMAP;
        eflags |= MDB_NOMETASYNC;
        eflags |= MDB_MAPASYNC;
        eflags |= MDB_NOSYNC;
        eflags |= MDB_NOTLS;
        eflags |= MDB_NOMEMINIT;
#endif
```

here are --rebuilddb measurements:
```
[jbj@ji rpm]$ sudo /usr/bin/time ./rpmdb --rebuilddb --lmdb 
30.96user 2.34system 0:37.48elapsed 88%CPU (0avgtext+0avgdata 1681104maxresident)k
173264inputs+457336outputs (356major+458600minor)pagefuls 0swaps

[jbj@ji rpm]$ sudo /usr/bin/time ./rpmdb --rebuilddb
23.44user 3.38system 0:31.06elapsed 86%CPU (0avgtext+0avgdata 1859212maxresident)k
48inputs+399976outputs (1major+442773minor)pagefuls 0swaps

[jbj@ji rpm]$ sudo /usr/bin/time ./rpmdb --rebuilddb --ndb
23.56user 2.89system 0:36.97elapsed 71%CPU (0avgtext+0avgdata 1854456maxresident)k
193896inputs+390064outputs (1major+431505minor)pagefaults 0swaps
```

**Comment by n3npq** [comment]
Ah, I missed this comment in lmdb.h (and the order of mdb_txn_commit() and mdb_cursor_close() are incorrectly reversed in lmdb_dbiCursorFree())
```
        /** @brief Close a cursor handle.
         *
         * The cursor handle will be freed and must not be used again after this call.
         * Its transaction must still be live if it is a write-transaction.
         * @param[in] cursor A cursor handle returned by #mdb_cursor_open()
         */
```

I will fix when I rip out the debugging instrumentation in lmdb.c ...

**Comment by n3npq** [comment]
This patch and single lmdb.c file  to implement  RPM+LMDB are ready for review and merging AFAIK.

[rpm+lmdb.patch.gz](https://github.com/rpm-software-management/rpm/files/1185378/rpm.lmdb.patch.gz)

[lmdb.c.gz](https://github.com/rpm-software-management/rpm/files/1185380/lmdb.c.gz)

**Comment by hyc** [comment]
Why are you using FIXEDMAP? That's going to lead to portability issues.

**Comment by n3npq** [comment]
I used MDB_FIXEDMAP because that's what you used in mtest.c ;-) Np other reason.

**Comment by hyc** [comment]
OK, best to turn it off. We were experimenting with it in OpenLDAP because we wanted to store pointer-based structures with live pointers and not need explicit serialization/deserialization. (I.e., all pointers in the struct just point to other parts of the mmap'd object.) It's a pretty specialized use case, and quite fragile in the face of growing map sizes.

**Comment by n3npq** [comment]
The final patch (with minor changes) is is now committed at https://github.com/rpm5/rpm/commit/528925bd9967d9b741787df56e46a5c83c7a54aa

**Comment by pmatilai** [comment]
Merged as of commit ed9de1992f5e1c23e8d8dbd61325a1e0070f2c72. Thank you!

**Comment by vitan** [comment]
@n3npq hi, buddy,

I am tasting the fresh lmdb+rpmdb , but blocked by the following trouble, which u said above.

```
lock.mdb (an 8Kb file) needs to be 0666, other perms as expected.
```

any good suggestion on keeping lock.mdb perm 0666. The perm of lock.mdb maybe reverted back on my environment.

**Comment by n3npq** [comment]
There are lots of ways to perform a chmod(2) call to ensure non-root lock access.

The best solution is to move lock.mdb out of /var/lib/rpm (which is also the best solution for using locks with Berkeley DB when non-root). I deliberately avoided attempting that implementation because the discussion will surely take months, it's a bike shed sort of issue.

One could also create an easily auditable 10 line program that is setuid root (or setgid rpm if /var/lib/rpm were owned by group rpm with 0775 permissions) that was exec'd as a helper by rpm.
This too should be attempted with Berkeley DB, rather than the insanity of not using locks with non-root access to /var/lib/rpm.

**Comment by vitan** [comment]
One could also create an easily auditable 10 line program that is setuid root (or setgid rpm if /var/lib/rpm were owned by group rpm with 0775 permissions) 
-----------------------------------------------
but how to audit it?

I am evaluating a dirty solution: watch the perm change of lock.mdb by a crontab or inotify.

**Comment by n3npq** [comment]
I was referring to a security audit of a setuid helper program, not auditing whether lock.mdb is 0666.

The helper should be exec'd while opening, after checking whether an existing file already has 0666 permissions.

There is also the corner case(s) of a non-existent lock.mdb file, or an ill-formed lock.mdb file, which would need to be handled: one approach would be to save a copy of the initial lock.mdb if 8Kb of zero isn't enough.

**Comment by vitan** [comment]
```
There is also the corner case(s) of a non-existent lock.mdb file, or an ill-formed lock.mdb file, which would need to be handled: one approach would be to save a copy of the initial lock.mdb if 8Kb of zero isn't enough.
```

thanks for your reminder

**Comment by n3npq** [comment]
The other approach is to fix whatever is in your environment (umask?) that is changing 0666 perms.

What is changing perms on lock.mdb from 0666?

**Comment by vitan** [comment]
is it a good solution to hack the lmdb code?

**Comment by vitan** [comment]
```bash
#rpm -qa
error: lmdb:	rc(-30796) = mdb_dbi_open(): MDB_CORRUPTED: Located page was wrong type
error: cannot open Packages index using lmdb -  (-30796)
error: cannot open Packages database in /var/lib/rpm
```

maybe here is not a right place on the above error. lmdb crashed since the error. any good idea to recover it, besides backup&restore the data.mdb?

**Comment by n3npq** [comment]
Using kill -9 is never a good idea with a database.

If you are going to hack on lmdb.c, then see the rudimentary debugging in one of the earlier versions that I used when writing the code.

Save a copy of /var/lib/rpm just in case. Then try doing rpm -v -v --rebuilddb. If that doesn't fix, then regenerate from BerkeleyDB, or a backup.

**Comment by vitan** [comment]
about corrupted rpmdb restore, please refer https://access.redhat.com/solutions/23743
