### ISSUE TITLE
Enhance the recoverability and location of database exceptions

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2828]
Background:
During the daily use of the RPM, the RPM database is abnormal. However, the cause is unknown. In some cases, the `rpm --rebuilddb` cannot ensure the complete recovery of the database. For recoverability and locatability, I think database backup functionality can be added for the following reasons:
1. If the database is abnormal after a command is executed, you can use the backup database directory to construct a scenario where the problem occurs, facilitating fault locating.
2. We can replace the abnormal directory with the normal database that is backed up before.

I have a preliminary solution idea:
1. A configuration switch is added to control whether to enable this feature.
2. Add the configuration to determine the location of the backup database directory and the number of database directories to run the backup.
3. Back up the database directory after the installation/uninstallation/upgrade transaction is complete, and the backup database is controlled by .rpm.lock.

I think it's meaningful to consider adding this feature. If so, I can work out a patch based on my ideas.

**Comment by JetXujing** [comment]
In addition, can we provide a command or script to quickly determine whether the database is damaged? At present, there seems to be no concise way to judge, generally by `rpm -qa` to roughly judge.

**Comment by ffesti** [comment]
There is `rpmdb --verifydb`. With the new rpmdb backends (sqlite and ndb) issues with the database should be incredibly rare compared to the old bdb days. If you are still experience rpmdb issues you are likely doing something wrong. May be disable measures that still are left over from the bdb times e.g. rebuilding the rpmdb on reboot or in a cron job.

If this doesn't solve the issue we much rather find and solve this issue properly than putting this band aid on.

**Comment by JetXujing** [comment]
In fact, the most difficult thing is that the database is suddenly damaged, generally don't know what caused the damage(may be a power outage or a kill process, etc.), so it is difficult to locate and repair.

**Comment by ffesti** [comment]
So is there an actual breakage you are seeing regularly? What database back end are you using?

**Comment by JetXujing** [comment]
I'm using ndb database, I often encounter the following problems: 1. The problem of verification failure; 2. A rpm package cannot be queried by running the "rpm -qa" command, but can be queried by running the "rpm -q" command. Sometimes, the "rpm --rebuilddb" command can be used to rectify the fault. Sometimes, the "rpm --rebuilddb" command cannot be used.

**Comment by JetXujing** [comment]
I'm sorry I don't have any good ideas. I just thought of backing up the database.

**Comment by ffesti** [comment]
Nah, I am not asking to do more. I am wondering if you should do less.
I am also wondering what version of RPM you are using.
You can try switching to the sqlite backend, although I don't have any information about the ndb backend being less reliable.
If you encounter breakage regularly there is definetely something wrong on your side. Feedback of users running hundreds of thousands machines indicate that the rpm database is very stable since we moved away from bdb.

**Comment by mlschroe** [comment]
Just as datapoint: SUSE switched to ndb a couple of years ago and I've not heard of any problems with the ndb database.

**Comment by JetXujing** [comment]
Actually, the ndb database is seldom faulty. There is a high probability that the database is abnormal due to abnormal power-off or abnormal mount directory.
If you think it is not appropriate to back up the database, you can consider closing the issue.

**Comment by pmatilai** [comment]
Um, what exactly do you mean by "database being abnormal" then?

**Comment by JetXujing** [comment]
I think the database is abnormal because the verification fails when I run the rpm command, or the "rpm -qa" command cannot find the kernel package, but the "rpm -q" command can find the kernel package. According to the result, the problem is caused by the database. However, this does not mean that the problem is caused by the internal logic of the database. It may be caused by the sudden shutdown, or the /var/ directory is the mount directory.

**Comment by pmatilai** [comment]
> I think the database is abnormal because the verification fails when I run the rpm command, 

You mean 'rpm --verify'? What errors?

> or the "rpm -qa" command cannot find the kernel package, but the "rpm -q" command can find the kernel package. According to the result, the problem is caused by the database. 

If -qa doesn't match with -q then the indexes are out of sync, ie the database is indeed inconsistent then. That can happen with ndb, but AIUI it should also detect that and fix itself. Except of course if it can't, ie you run queries as an unprivileged user who cannot write to the rpmdb.

The sqlite backend is transactional so you're never supposed to see such a state there, it's all handled transparently by sqlite. So if you have an environment where rpm gets forcibly killed at random times a lot then that may be something to try out. However, rpm is NOT suited well for such an environment. At all. Rpm WILL leave orphan files around if such things happen, and there's currently no attempt to try to track them.

**Comment by JetXujing** [comment]
> You mean 'rpm --verify'? What errors?
No,
