### ISSUE TITLE
%missingok is undocumented

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/rpm#2833]
%config(missingok) is documented, however, %missingok is not.  Presumably there is at minimum a lot of overlap, but it is unclear if there are any distinctions in when and how they should be used. 

vattrtest.spec only tests %missingok, can I presume that they are equivalent in function?  Is one or the other considered better syntax?

Or does %config(missingok) also set the flag marking a file as configuration, while %missingok does not?  If so, when is that useful?

**Comment by pmatilai** [comment]
There's just one flag for it all (`RPMFILE_MISSINGOK`) so `%config(missingok)` equals `%config %missingok`. The standalone `%missingok` was only added in 2016 (8efe51e8c24b7739f0bf7680e21083c8964633f5)  so relatively late.
