### ISSUE TITLE
Documentation refers to %prein and %postin, which do not seem to be supported

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/rpm#2834]
In a few select spots the documentation refers to %prein and %postin, but I tried these and they do not appear to work.

I expect it means %pre and %post, the names of which admittedly break the pattern followed by the other scriptlet types.

Am I missing something or is this a mistake?

**Comment by dralley** [comment]
Unrelated, but this line found in the scriptlet documentation seems rather out of date :)

>  The %pre script executes just before the package is to be installed. It is the rare package that requires anything to be done prior to installation; none of the 350 packages that comprise Red Hat Linux Linux 4.0 make use of it.

**Comment by pmatilai** [comment]
They're just copy-paste/thinkos because the tags have the *in part, but %pre and %post don't.

**Comment by pmatilai** [comment]
And yup, most of rpm documentation is either really old, or really recent, with a circa 20 year gap in between. I try to leave some old stuff around just for the historical context/curiosity, but that statement about %pre rarity is just wrong and needs to go.

**Comment by pmatilai** [comment]
OTOH, %pre should become rare again once the native user/group handling starts getting actually used.

**Comment by pmatilai** [comment]
Oh and thanks for reporting! Mistakes like this in the "canonical" docs are pretty bad, sorry for taking so long to deal with the silly thing.
