### ISSUE TITLE
Improve build determinism (replace soft dependencies with strict ones)

### ISSUE THREAD

**Issue by kanavin** [rpm-software-management/rpm#2855]
This is a followup to https://github.com/rpm-software-management/rpm/pull/2852/

There is still a number of soft dependencies in https://github.com/rpm-software-management/rpm/blob/master/CMakeLists.txt:

```
find_package(BZip2)
find_package(Iconv)
...
pkg_check_modules(ZSTD IMPORTED_TARGET libzstd>=1.3.8)
pkg_check_modules(LIBELF IMPORTED_TARGET libelf)
pkg_check_modules(LIBDW IMPORTED_TARGET libdw)
pkg_check_modules(LIBLZMA IMPORTED_TARGET liblzma>=5.2.0)
```

Then, the respective build options get enabled depending on whether or not these components were found on the build system.

I believe it's better to make them strict (add REQUIRED parameter), and (optionally) wrap them in cmake options (like was just done for readline support), if there are situations where they should be disabled. I can write the patch, but wanted first to confirm what would be preferred.

**Comment by dmnks** [comment]
Oh, sure! This looks useful. Please go ahead and submit a PR, we'll take it from there. Thanks!
