### ISSUE TITLE
Update Runtime scriptlets section in manual

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#2867]
Funnily enough, we currently don't document how scriptlets receive their arguments when called. We do touch upon that in the [triggers](https://rpm-software-management.github.io/rpm/manual/triggers.html) chapter, however this should be documented for file triggers (as part of #2755) as well as normal scriptlets (`%pre`, `%post`, etc.), too, since they (mostly) all share the same semantics.

The Fedora packaging guide might be a good source of inspiration as it includes a nice table which summarizes the arguments: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_syntax

**Comment by pmatilai** [comment]
Yep. The gaps in our documentation are so enormous they're difficult to see.

**Comment by dmnks** [comment]
While at it, I realized the whole [Runtime scriptlets](https://rpm-software-management.github.io/rpm/manual/spec.html#runtime-scriptlets) section needs to be rewrtiten and updated so I'll do that as part of this ticket.

**Comment by dmnks** [comment]
Let's just cover this as part of #2860, closing now.

**Comment by dmnks** [comment]
Fixing up the closure reason (to "not planned").
