### ISSUE TITLE
Split Perl dependency generators into a separate repo

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#2873]
Split the Perl dependency generators into a separate GitHub repository managed by our organization. This will make it far easier for the community to maintain and is in the spirit of https://github.com/rpm-software-management/rpm/pull/1607, and more generally, of https://github.com/rpm-software-management/rpm/discussions/2747.

We need to make sure to preserve the git history when migrating it, though.

There are a couple of pending PRs for these Perl scripts that should be migrated to the new repo once it's ready, namely:
* https://github.com/rpm-software-management/rpm/pull/2586
* https://github.com/rpm-software-management/rpm/pull/2609

**Comment by stoecker** [comment]
Thanks for going forward with this.

Can you add Tina (perlpunk) and me to the new repo, so we can continue there?

For openSUSE we're way into switching to the proper perl version system (currently all packages with conflict-free updates in the last year are switched) and will start soon switching all packages (causing version conflicts temporary). It would be a major help when we wouldn't need a temporary step with manual provides to do so.

**Comment by pmatilai** [comment]
FWIW, I think we should follow the [Python lead](https://github.com/rpm-software-management/python-rpm-packaging) and call it perl-rpm-packaging to allow for all sorts of helper material to live there and not just macros/scripts and the like. A bit of consistency is a nice bonus.

**Comment by pmatilai** [comment]
And here goes: https://github.com/rpm-software-management/perl-rpm-packaging

The rest is up to the Perl community. If/when you need help with permission matters, please file tickets in https://github.com/rpm-software-management/org-admin .
