### ISSUE TITLE
Noarch RPMs that contain EBPF binaries code incorrectly fail with "Arch dependent binaries in noarch package"

### ISSUE THREAD

**Issue by socketpair** [rpm-software-management/rpm#2875]
Noarch RPMs that contain EBPF binaries code incorrectly fail with "Arch dependent binaries in noarch package"

EBPF is really noarch binary.

**Comment by pmatilai** [comment]
Okay, managed to produce one by myself:

> [pmatilai🎩︎localhost ~]$ clang -target bpf  -c bpf.c -o bpf.o
> [pmatilai🎩︎localhost ~]$ file bpf.o 
> bpf.o: ELF 64-bit LSB relocatable, eBPF, version 1 (SYSV), not stripped

So it's an architecture by itself, speced to be always 64bit: https://www.ietf.org/archive/id/draft-thaler-bpf-elf-00.html so any "coloring" (meaning 32/64bitness in rpm) is just wrong. Luckily it should also be trivial to fix.

**Comment by socketpair** [comment]
Fixed both in rpmbuild and in rpmlint ?

**Comment by pmatilai** [comment]
I don't know what rpmlint does, it's a separate project.
