### ISSUE TITLE
RPM 4.19.x bugfix release

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2878]
There are some pretty nasty bugs in 4.19.1 still, I think we should put out an expedited bugfix release to address at least these regressions:
- https://github.com/rpm-software-management/rpm/pull/2843
- https://github.com/rpm-software-management/rpm/pull/2818

Other, less nasty stuff:
- https://github.com/rpm-software-management/rpm/pull/2814
- https://github.com/rpm-software-management/rpm/pull/2806

Plus a whole pile of various build-related fixes:
- https://github.com/rpm-software-management/rpm/pull/2812
- https://github.com/rpm-software-management/rpm/pull/2856
- https://github.com/rpm-software-management/rpm/pull/2852
- https://github.com/rpm-software-management/rpm/pull/2848

That's just from the top of my head, there's almost certainly more. As these are all bugfixes only, it might make sense to call it 4.19.1.1 rather than 4.19.2 (but that's just numbers...)

**Comment by dmnks** [comment]
Ack, thanks for creating the ticket!

**Comment by dmnks** [comment]
>     * [Print full path if file removal fails #2806](https://github.com/rpm-software-management/rpm/pull/2806)

Just FTR, this one already is in 4.19.1.
