### ISSUE TITLE
RPM+NDB should implement ndb_dump/ndb_load/ndb_stat for database dumps.

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#289]
Converting databases is painful, particularly if both forward/backward conversions are desired.

BerkeleyDB has a set of utilities to do this conversion, LMDB uses an almost identical set of utilities.

While rpmdb --importdb/--exportdb are a high performing KISS  improvement on the BDB-style dump/load, there are still needs to display key<->value pairs in human readable (i.e. not just hex/binary) format.

The LMDB licensed mdb_dump/mdb_load utilities could be swiped and modified to handle NDB pretty easily to provide a well-understood (and used by libvirt iirc) common import/export/format.

**Comment by mlschroe** [comment]
Wouldn't it be better if rpmdb gets dump/load/stat options?

**Comment by n3npq** [comment]
Bundling into rpmdb would be fine: just there needs to be a common interchange format. E.g. libvirt uses db_dump and is opposed to NDB because it lacks an equivalent. The textual non-hex format is occasionally useful as well (but with digests/signatures one cannot just edit the database).

**Comment by n3npq** [comment]
FWIW, there are other markups that could be usefully added to rpmdb, like CUDF (or other SAT solver inputs).

The real issue is compatibility with commonly used external tools, not so much whether the output markup is implemented in an existing rpmdb executable or a separate ndb_dump utility.
