### ISSUE TITLE
A duplicate code

### ISSUE THREAD

**Issue by pkopylov** [rpm-software-management/rpm#2904]
https://github.com/rpm-software-management/rpm/blob/34cb5ee92276058f68f6d3fb1c345b22992c28a8/lib/rpmfi.c#L332

This row duplicates the settings of the i variable for several lines above.

**Comment by ffesti** [comment]
This is suspicious as they assign different values. @pmatilai do you want to have a closer look? 

Could be a rebasing artifact between fb13f7fd9e and 318efbaec8. Probably by changing the order those two are aplied.

**Comment by pmatilai** [comment]
Yeah, could be a rebase incident. It's dead code anyhow.

Not exactly a bug, but thanks for reporting.
