### ISSUE TITLE
RPM uses pragma case_sensitive_like which is deprecated from sqlite 3.44

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2925]
### Discussed in https://github.com/rpm-software-management/rpm/discussions/2924

<div type='discussions-op-text'>

<sup>Originally posted by **vbrahmajosyula1** February 22, 2024</sup>
sqlite 3 deprecates pragma_case_sensitive_like from 3.44 https://www.sqlite.org/changes.html.
Following patch introduced case_sensitive_like in RPM.
https://github.com/rpm-software-management/rpm/commit/bea298986d796900dd94de42dec98fb194df1ff8
</div>

Seems we need to do something about it. Bug is weird label for this but we don't have anything really appropriate for this.

**Comment by mlschroe** [comment]
We don't use LIKE anymore since commit c9380471adfa9fb06ace251a5f02b348507db345, so maybe we
can just remove the pragma?

**Comment by pmatilai** [comment]
Oh. I had no recollection whatsoever of that change :flushed: 

Indeed, we can then just remove the pragma. Thanks @mlschroe for pointing that out.
