### ISSUE TITLE
Non parametric macro inconsistency

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#2932]
I stumbled over this:
```
$ rpm --eval '%{?_libdir:foo}'
foo
$ rpm --eval '%{_libdir:foo}'
/usr/lib64
```
Should those two both return `foo`?

**Comment by mlschroe** [comment]
There are good reasons to leave it the way it is, I just wanted to point out that there's a somewhat undocumented difference.

**Comment by pmatilai** [comment]
Why should the latter return anything else than an error?

**Comment by mlschroe** [comment]
True. I'm fine with leaving it the way it is.
