### ISSUE TITLE
Check packages for consistency when opening them 

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#2937]
There are several assumptions abut how a proper package looks like and those are checked in rpmbuild but rpm itself does often not enforce them on reading. This can create problems when packages are being created with 3rd party tools. This is also a potential security risk (although having manipulate packages passing signature checks is already a game over).

Properties that should be checked are:

* Legal characters and name patterns for dependencies, NERVA, etc
* Number of tag entries match in related tags (files, dicts, dependencies, ...)
*  File flags match the file types
* ...

See #2906 for the initial discussion about flags

**Comment by pmatilai** [comment]
This would actually be more like a long-term project than an individual ticket you can just fix, because it's just enormous.

**Comment by pmatilai** [comment]
This is a duplicate of #3146, closing.
