### ISSUE TITLE
rpmbuild sometimes is killed by SIGPIPE with bad dependency generator sciptlets

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#2949]
This is a bit of a corner case, but I just received a bug report that builds sometimes terminate for a specific package. It turned out the package contained this little gem:
```
%define __perllib_provides /bin/true
```
Anyway, I don't think rpm should be killed by this. Once upon a time getOutputFrom() had code that made it ignore SIGPIPE, but it seems it was removed in commit 375a6b5630b8e37e1d3f0c7ecbe10fe460c4d420

This is probably not urgent to fix, just filing so that you know about this race.

**Comment by mlschroe** [comment]
For reference: https://bugzilla.suse.com/show_bug.cgi?id=1220213

**Comment by pmatilai** [comment]
Oh, that sounds a whole lot like https://github.com/rpm-software-management/rpm/issues/2470

**Comment by pmatilai** [comment]
The flaky test-case is:

```cat << EOF > "${RPMTEST}"/tmp/bad.req
#!/bin/sh
echo 'bad = *'
EOF
chmod a+x "${RPMTEST}"/tmp/bad.req

runroot rpmbuild -bb --quiet \
                --define "__script_requires /tmp/bad.req" \
                /data/SPECS/shebang.spec
```

The common theme being a tiny generator that outputs little to nothing.
