### ISSUE TITLE
rpm generators only run when either a magic or path rule is set

### ISSUE THREAD

**Issue by dcermak** [rpm-software-management/rpm#2951]
`static int matches` from `rpmfc.c` implies that rpm provides & requires generators only run when either `__NAME_magic` or `__NAME_path` is set: https://github.com/rpm-software-management/rpm/blob/3ad98187cc64a88d2d31d181d10bef5eef6274b7/build/rpmfc.c#L794

Yet, the documentation https://rpm-software-management.github.io/rpm/manual/dependency_generators.html#file-attributes only mentions that "While technically all of them are optional, typically two or more of them are present to form a meaningul attribute". Which of these is correct, the source or the documentation?

**Comment by ffesti** [comment]
This is both correct. All are optional but nothing will happen unless you have both matching files and a generator for a dependency. A file attribute that does nothing still is legal.

**Comment by ffesti** [comment]
*sigh*
