### ISSUE TITLE
Lua equivalent to `%{echo:...}` and similar

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#2967]
Currently the way to get some information from Lua macro is quite clumsy. One needs to do something like:

~~~
%define foo() %{lua:
  rpm.expand("%{echo: some output}")
}
~~~

Would it be possible to make it easier, e.g. something like this would be more convenient:
~~~
%define foo() %{lua:
  rpm.echo("some output")
}
~~~

Or maybe just:

~~~
%define foo() %{lua:
  echo("some output")
}
~~~

**Comment by mlschroe** [comment]
You can already do:
```
macros.echo({"hello world"})
```

**Comment by voxik** [comment]
Oh. Interesting, the for the tip 👍 Nevertheless, I was not able to figure that out myself, therefore it would deserve to be documented if that is the right approach.

**Comment by voxik** [comment]
TBH figuring out `rpm.expand("%{echo: some output}")` is also not that straight forward. I was able to find such example at least.

**Comment by pmatilai** [comment]
Accessing rpm macros through the `macros` table *is* documented in https://rpm-software-management.github.io/rpm/manual/lua.html
