### ISSUE TITLE
rpm2archive -f pax cannot handle utf8 filenames

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#2972]
It fails because it want to convert the filenames to utf8:

$ echo $LC_CTYPE
de_DE@euro
$ rpm2archive  /usr/src/packages/RPMS/x86_64/empty-3.0.0-1.x86_64.rpm > /dev/null
Error writing archive: Can't translate pathname './fooöo' to UTF-8 (84)

**Comment by mlschroe** [comment]
In this case archive_write_header() returns ARCHIVE_WARN, which is treated as error in rpm2archive. OTOH I don't think libarchive should mess with the file names, maybe it makes sense to set the hdrcharset to `BINARY` for pax. But that adds a "hdrcharset=BINARY" attribute that GNU tar complains about.

**Comment by mlschroe** [comment]
Oh, and the error handling in rpm2archive is completely broken...

**Comment by mlschroe** [comment]
Btw, it cannot handle UTF8 filenames as well, as it checks the current locale which is not initialized and thus 7 bit ascii...

**Comment by mlschroe** [comment]
I find it very surprising that bsdtar's output depends on the current locale, but that seems to be the case:
```
$ echo hello > micro_µ
$ bsdtar -cf - . | bsdtar -tf -
./
./micro_µ
$ LC_CTYPE=de_DE@euro bsdtar -cf - . | bsdtar -tf -
./
./micro_Âµ
$ LC_CTYPE=de_DE@euro bsdtar --options hdrcharset=BINARY -cf - . | bsdtar -tf -
./
./micro_µ
```

**Comment by mlschroe** [comment]
It's not much work to not use libarchive for writing. The only two formats that can be used for archive writing are cpio and pax (all the others have too many limitations). Writing cpio is easy and writing a pax tar file is also not hard (reading a tar file is where it gets really messy because of all the different implementations).

Is that something you would be interested in?

**Comment by pmatilai** [comment]
rpm2archive could use some love for sure, but I'd rather not teach it about format internals, that's just the kind of thing I'd rather outsource to somebody else - like libarchive. If it doesn't do what we want it to do, then lets at least look at fixing it instead of doing it in rpm, it'd benefit way more people too.

As for the encoding, I think here's a case for RPMTAG_ENCODING: if that's present and says utf-8 (upstream rpm will never put anything else there) we can safely assume utf-8. Anything else is a legacy case and if the easiest solution is to just say "BINARY" encoding then that's fine with me. Or does "GNU tar complains" mean it actually fails entirely rather than just warn?

**Comment by mlschroe** [comment]
And this is about file names, I think "upstream rpm" treats those pretty much as binary as they are created by the build process and not part of the spec file.

**Comment by pmatilai** [comment]
Right. So the warning would only be seen by folks who run rpm2archive to convert legacy rpms to tar - ie a rare corner case really. A harmless warning from gnu tar in that case is quite acceptable to me at least.

**Comment by mlschroe** [comment]
Why "legacy"? Does the current code reject non-utf8 file names?

**Comment by pmatilai** [comment]
It does, by default. For many years now.

**Comment by mlschroe** [comment]
That makes things a bit easier, so we just need to teach libarchive that it should accept utf8. I'll adapt the title of this issue ;-)

**Comment by mlschroe** [comment]
I'll open a pull request for this.

**Comment by ffesti** [comment]
Looks like this didn't get closed although the patch is already upstream for quite a while. Closing now.
