### ISSUE TITLE
Make -C the default for BuildOption(prep)

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#2998]
See https://github.com/rpm-software-management/rpm/discussions/2997#discussioncomment-8915180

It would make sense to make `-C` the default option for `BuildOption(prep)`, so packages utilizing the Declarative builds feature don't have to pass custom `-n` to it. (Using custom `-n` is also used as an example in the documentation for `BuildOption(prep)`, so that will need a different example.)

**Comment by pmatilai** [comment]
Oh yup, thanks for filing this! The auto directory patch landed just after the buildsystem work so it kinda went under the radar, but it should complement the buildsystem work very nicely indeed.

**Comment by hroncok** [comment]
Thanks.

I noticed the `BuildOption(prep)` documentation was not updated in that PR.

**Comment by pmatilai** [comment]
Oh, thanks for pointing that out! I didn't even remember we have that in the documentation (although it was written by me, so ... age doesn't come alone as they say around here)

**Comment by pmatilai** [comment]
Doubly more embarrassing as you mentioned that in the ticket description :laughing: 
Will fix.

**Comment by pmatilai** [comment]
Maybe not the greatest example but at least something: https://github.com/rpm-software-management/rpm/commit/5d4a476d14998f8f7ebc7e0c15a5263ca7803f5d
