### ISSUE TITLE
perl.prov does not handle perl's "package Package::Name 1.05" with version declarations

### ISSUE THREAD

**Issue by shlomif** [rpm-software-management/rpm#301]
Hi!

No provides are generated for the «package $name $version» syntax that is supported in newer versions of perl 5 and is used by the new https://metacpan.org/search?q=Dist%3A%3AZilla%3A%3APath . Can support to it be added? One should also note that there is now a  `package Pack { ... }` syntax as well.

**Comment by ignatenkobrain** [comment]
https://github.com/rpm-software-management/rpm/pull/237

RPM 4.14 supports this. I would recommend you to open bug against your distribution to backport that particular patch.

**Comment by shlomif** [comment]
Thanks @ignatenkobrain ! Note that rpm 4.14 does not appear to have been released yet, but I guess we can try backporting the patch.
