### ISSUE TITLE
It is currently not possible to completely disable rpm own debuginfo generation code

### ISSUE THREAD

**Issue by simo5** [rpm-software-management/rpm#3057]
**Describe the bug**
I have spent some time trying to create a completely custom debuginfo file for a package I maintain.

Currently it is not possible to do so. Even disabling the custom package template and the whole debug_package machinery via `%global debug_package %{nil}` if rpm build see a package named `%{name}-debuginfo` it will always interfere with the build process of that package. 

Namely the code will disregard any file list provide by either the %files section or via __find_debuginfo script and will instead process to reconstruct a new file list by searching for files named *-%{name}-%version}.%{release}.debug

**To Reproduce**
1. Disable debug package creation
2. Add an explicit %{name}-debuginfo package
3. Try to include arbitrary files in it

Please link or attach the packages or spec files involved.

**Expected behavior**
When debug package creation is disabled the "main" debuginfo package file lists should not be tampered with.

**Additional context**
At the moment the only workaround I found was to create a fake subpackage and debuginfo subpackage and that allows me to include whatever content I need, but this is not a good solution.

**Comment by judovana** [comment]
hi! It seems those fixes are present in 4.20 but not in 4.1.x, right?  

> **Additional context** At the moment the only workaround I found was to create a fake subpackage and debuginfo subpackage and that allows me to include whatever content I need, but this is not a good solution.

@simo5  may you please elaborate/link  your workaround for my education? Am fighting  something similar, and am running out of ideas.

**Comment by simo5** [comment]
@judovana it is not complicated, because the debug info extraction was "broken" on the "main" package I created subpackages instead, so in the spec (this is a library that ships only .so files)  I have something like:

```
%global debug_package %{nil}

Name: mylib
Version: 1.2.3
Release: %autorelease
[..]
Requires: %{name}-so = %{version}-%{release}

[..]

%files
%doc README.md

%files so
%attr(0755,root,root) %{_libdir}/mylib.so

%files so-debuginfo -f debuginfo.list

%files so-debugsource -f debugsourcefiles.list

```

The correct debug*.list files are currently generated by a script independently from the rpm internal extraction script

**Comment by judovana** [comment]
hi! Thanx for confirmation. I had deducted similar approach, but it failed elsewhere.  After more elaborations enourraged by your example it worked fine. TY!
