### ISSUE TITLE
Dynamic spec generation depends on %setup (for no good reason)

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3063]
While poking around with debuginfo stuff, ran into the fact that %specpartsdir is generated from  %setup, which limits its usefulness somewhat. Most real-world packages of course do have %setup but now with %builddir, there's no reason to limit specparts to those packages.

Should probably create it at the same time as %builddir itself to ensure its always there.

**Comment by Conan-Kudo** [comment]
So this is similar to #3042 (and probably really just a more generic version of that issue).
