### ISSUE TITLE
if-else rich dependency always installs the if leg

### ISSUE THREAD

**Issue by keszybz** [rpm-software-management/rpm#3082]
**Describe the bug**
The docs say:
> `if` - requires the first operand to be fulfilled if the second is (reverse implication)
> `if else` - same as above but requires the third operand to be fulfilled if the second is not

I added the following to `redhat-rpm-macros`:
> `Requires: (add-determinism if python3-libs else add-determinism-nopython)`

When I install the package I get:
```console
$ mock -r fedora-rawhide-x86_64 --uniqueext=a -i /var/tmp/redhat-rpm-config-289-1.fc41.noarch.rpm
...
Upgrading:                                                                 
 redhat-rpm-config             noarch 289-1.fc41     @commandline 183.5 KiB
   replacing redhat-rpm-config noarch 288-1.fc41     fedora       183.3 KiB
Installing dependencies:                                                   
 add-determinism               x86_64 0.2.0-1.fc41   fedora         2.6 MiB
 expat                         x86_64 2.6.2-1.fc41   fedora       280.8 KiB
 libb2                         x86_64 0.98.1-11.fc40 fedora        42.2 KiB
 mpdecimal                     x86_64 2.5.1-9.fc40   fedora       200.9 KiB
 python-pip-wheel              noarch 24.0-2.fc41    fedora         1.5 MiB
 python3-libs                  x86_64 3.12.3-2.fc41  fedora        40.9 MiB
 tzdata                        noarch 2024a-5.fc41   fedora         1.6 MiB
```

`python3-libs` is being installed, which means that was *not* installed previously. I expected `add-determinism-nopython` would be installed instead.

(When changed to
> `Requires: (add-determinism if python3-libs)`

then `add-determinism` is not installed:
```console
$ mock -r fedora-rawhide-x86_64 --uniqueext=a -i /var/lib/mock/fedora-rawhide-x86_64-a/result/redhat-rpm-config-289-1.fc41.noarch.rpm
...
Upgrading:                                                             
 redhat-rpm-config             noarch 289-1.fc41 @commandline 183.5 KiB
   replacing redhat-rpm-config noarch 288-1.fc41 fedora       183.3 KiB
Transaction Summary:
 Upgrading:         1 packages
 Replacing:         1 packages
```
)

**Comment by keszybz** [comment]
https://src.fedoraproject.org/fork/zbyszek/rpms/redhat-rpm-config/commits/post-build-reproducibility-debug is the branch. The middle commit shows the unexpected behaviour and the third one is for debugging.

**Comment by mlschroe** [comment]
This is not a rpm issue. rpm just checks if all dependencies are fulfilled, it does not choose packages. So you would need to take this to the dnf people who will tell you to ask the libsolv folks.

Anyway, what happens is that your dependency is basically telling the solver "either install add-determinism-nopython or install both python3-libs and add-determinism". Both are valid solutions and the solver is free to pick the one it likes. You could try to add a "Suggests: add-determinism-nopython" to give it a hint that it should prefer the nopython variant.

**Comment by keszybz** [comment]
Thanks. You are completely right, I misunderstood what is part of the stack is doing what.

I added the Suggests as suggested, and it works. Thanks again.
