### ISSUE TITLE
RFC: standard macro syntax for macro files

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#309]
Currently macro files have too simple syntax: name and value... For example, you can't undefine macro, you can't do some conditions and so on. Which makes macro files not that useful.

One day, @pmatilai said that it would be good to have same syntax everywhere.

**Comment by n3npq** [comment]
You need to provide better examples, not statements of deficiencies with "macro files" (which are presumably the files where RPM configuration is defined).

In some sense you are asking a "library" (i.e. macro files) to be able to reconfigure to satisfy "application" (i.e. rpmbuild ) needs.

A better example please.

**Comment by pmatilai** [comment]
The declarative macro files are fine the way they are, we don't want spec parser-style complex conditionals in rpm configuration.

A more productive path might be having a kind of include path that you could use from specs, think of eg `%include <python3>`. I think there's a bug/ticket for something like that someplace but can't seem to find it atm. Anyway, closing this one as I don't see us changing the macro file syntax.
