### ISSUE TITLE
`%patchlist` should have a way to group patches

### ISSUE THREAD

**Issue by berolinux** [rpm-software-management/rpm#3109]
In a few contexts, it is necessary to make a difference between a few groups of patches that have to be applied at a different time, under different conditions, or in a different subdirectory.
Using the traditional `Patch1234:` tags, this is possible with `%autopatch -m ...` / `%autopatch -M`, e.g.

```
Patch0: https://github.com/upstream-project/pull/1234.patch
Patch1: https://github.com/upstream-project/pull/1235.patch
Patch100: https://github.com/other-project/pull/5678.patch
Patch101: https://github.com/other-project/pull/5679.patch
[...]
%autopatch -M 99
cd evil-internalized-copies-of-3rd-party-libs/other-project
%autopatch -m 100
```

(And yes, the correct fix for this is to not use the bundled copy - but it's not always possible, e.g. if the internalized version is modified)

With `%patchlist`, there is currently no way [at least none that I'm aware of, if it exists, it needs to be documented] to mark which patches should belong to which group. It would be nice to be able to do something like

```
%patchlist
https://github.com/upstream-project/pull/1234.patch
https://github.com/upstream-project/pull/1235.patch
100:https://github.com/other-project/pull/5678.patch
https://github.com/other-project/pull/5679.patch
```

where the added `100:` for the first patch from `other-project` would increment the internal counter to 100, so
`1234.patch` would be `0`, `1235.patch` would be 1, `5678.patch` would be `100` and `5679.patch` would be `101`.

**Comment by pmatilai** [comment]
Automatic patch numbering (whether %patchlist or unnumbered patches) and manual patch application based on them is a recipe for disaster that's best avoided IMO.

The raison d'être of %patchlist is to minimize boilerplate in the common case where you just want to apply all patches.  If you need precise control over patch numbers, better do so explicitly. One possible solution for this is to use manual Patch5123: numbering for those patches you need conditions on, just pick a sufficiently large starting number so the list doesn't clash (but it'll error out if that hapens).

**Comment by pmatilai** [comment]
I'd rather see something like multiple %patchlists whose application can be controlled by something else. Patch numbers don't really cut it :sweat_smile:

**Comment by pmatilai** [comment]
Closing in favor of #3110, but thanks for the initiative.
