### ISSUE TITLE
%mkbuilddir breaks the %generate_buildrequires implementation in mock

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#3121]
**Describe the bug**

RPM 4.20 breaks all Fedora packages with %generate_buildrequires (when built in mock, koji, etc.).

The error looks like this:

```
Executing(%generate_buildrequires): /bin/sh -e /var/tmp/rpm-tmp.nQJoQh
+ umask 022
+ cd /builddir/build/BUILD/python-cffi-1.16.0-build
+ cd cffi-1.16.0
/var/tmp/rpm-tmp.nQJoQh: line 34: cd: cffi-1.16.0: No such file or directory
```

**To Reproduce**

```
mock -r fedora-rawhide-x86_64 --addrepo 'https://download.copr.fedorainfracloud.org/results/pmatilai/rpm-snapshot/fedora-rawhide-$basearch/' init
mock -r fedora-rawhide-x86_64 --addrepo 'https://download.copr.fedorainfracloud.org/results/pmatilai/rpm-snapshot/fedora-rawhide-$basearch/' --update
mock --verbose -r fedora-rawhide-x86_64 --addrepo 'https://download.copr.fedorainfracloud.org/results/pmatilai/rpm-snapshot/fedora-rawhide-$basearch/' -Nn python-cffi-1.16.0-4.fc41.src.rpm 
```

`python-cffi-1.16.0-4.fc41.src.rpm ` was generated from the Fedora Rawhide package by `fedpkg srpm`, no changes.

**Expected behavior**

The build should work, as it did with RPM 4.19.

**Output**

```
...
DEBUG: Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '903169f1656745f3a76286ffeebf52ee', '-D', '/var/lib/mock/fedora-rawhide-x86_64/root', '-a', '-u', 'mockbuild', '--capability=cap_ipc_lock', '--bind=/tmp/mock-resolv.not1p4a8:/etc/resolv.conf', '--bind=/dev/btrfs-control', '--bind=/dev/mapper/control', '--bind=/dev/fuse', '--bind=/dev/loop-control', '--bind=/dev/loop0', '--bind=/dev/loop1', '--bind=/dev/loop2', '--bind=/dev/loop3', '--bind=/dev/loop4', '--bind=/dev/loop5', '--bind=/dev/loop6', '--bind=/dev/loop7', '--bind=/dev/loop8', '--bind=/dev/loop9', '--bind=/dev/loop10', '--bind=/dev/loop11', '--console=pipe', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=C.UTF-8', '--resolv-conf=off', 'bash', '--login', '-c', '/usr/bin/rpmbuild -br --noprep --noclean --target x86_64 --nodeps /builddir/build/SPECS/python-cffi.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8', 'SYSTEMD_NSPAWN_TMPFS_TMP': '0', 'SYSTEMD_SECCOMP': '0'} and shell False
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1706227200
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.rsmzU0
+ umask 022
+ cd /builddir/build/BUILD/python-cffi-1.16.0-build
+ test -d /builddir/build/BUILD/python-cffi-1.16.0-build
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /builddir/build/BUILD/python-cffi-1.16.0-build
+ /usr/bin/rm -rf /builddir/build/BUILD/python-cffi-1.16.0-build
+ /usr/bin/mkdir -p /builddir/build/BUILD/python-cffi-1.16.0-build
+ /usr/bin/mkdir -p /builddir/build/BUILD/python-cffi-1.16.0-build/SPECPARTS
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%generate_buildrequires): /bin/sh -e /var/tmp/rpm-tmp.wyDFnL
+ umask 022
+ cd /builddir/build/BUILD/python-cffi-1.16.0-build
+ cd cffi-1.16.0
/var/tmp/rpm-tmp.wyDFnL: line 34: cd: cffi-1.16.0: No such file or directory
```

**Environment**
 - OS / Distribution: Fedora 41
 - Version: rpm-5.99.90-0.git16959.1.fc41 (also with 4.19.91-1.fc41 from Fedora distgit), mock-5.5-1.fc39

**Additional context**

Mock pretty much does this:

```
rpmbuild -br --noclean
rpmbuild -br --noprep --noclean (REPEAT UNTIL NECCESSARY)
rpmbuild -ba --noprep
``` 

But the new `%mkbuilddir` section `rm`s the prepped sources:

```
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.rsmzU0
...
+ /usr/bin/rm -rf /builddir/build/BUILD/python-cffi-1.16.0-build
```

Hence, `--noprep` does not work the way it did (mock assumes sources are already prepped by the previous rpmbuild round).

**Comment by dmnks** [comment]
Note that a dupe was filed just minutes before this one: #3120. Funny timing, isn't it? :smile:

**Comment by praiskup** [comment]
Hehe, this is a complete coincidence (no prior talk with Miro about this) - I just debugged two FTBFSs the Python team opened (weeks ago) against the packages I maintain.  Kudos the Python team can explore these problems before they even land Rawhide!

**Comment by pmatilai** [comment]
As I said in #3120, my first reaction was: we have --noprep? :flushed: 
Git reveals the following:

```
commit 4f69f8b482e1bd61d5a7e1c8214e2ebc6cb66c5d
Author: David Greaves <david@dgreaves.com>
Date:   Tue May 26 12:31:51 2015 +0200

    rpmbuild: Add "--noprep" to not execute %prep stage
```

So, no wonder I didn't remember that option because I wasn't doing rpm in 2015. Those couple of years are this annoying blank in my memory, all sorts of surprises creep up from there :laughing:

**Comment by pmatilai** [comment]
Thanks BTW @hroncok and @praiskup for the detailed reports!

**Comment by dmnks** [comment]
Seconded, these were almost unusually detailed and actionable, thanks guys!

**Comment by hroncok** [comment]
From @pmatilai at #3121:

> I can see why mock would use such a thing, but I'm not really comfortable with that (or the option itself) because it seems that mock is now driving the build and not rpmbuild. And this means any changes to rpmbuild are even more difficult than they are otherwise.

Where would be the best place to discuss this further?

**Comment by pmatilai** [comment]
I'm not sure there's much to do about that now, the ship sailed a long ago.

**Comment by pmatilai** [comment]
The biggest issue here was really that there were no tests on --noprep whatsoever, so when I wasn't even aware of the feature... luckily this was easy enough to sort out. *knocks wood*
