### ISSUE TITLE
adding `exit 0` in %install makes debuginfo to not generate

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#315]
While debugging some problem in MBS (https://pagure.io/fm-orchestrator) I found that it replaces `%check` with `exit 0` which is wrong and so on, but luckily it was right after `%install` section.

Build was failing because find-debuginfo.sh was not run at all. I think this is a bug in RPM.

**Comment by ignatenkobrain** [comment]
In case you want to see buildlog... 
[ninja-build-mock-stderr.log](https://github.com/rpm-software-management/rpm/files/1272852/ninja-build-mock-stderr.log.txt)

**Comment by proyvind** [comment]
No, it's not an rpm bug.

For each stage there's a set of macros of what to run before, during, after etc.
These expanded macros needs to be expanded, so when ie. %install is invoked, it's an macro expanded shell script of %install that forks and returns.
Placing exit at the end of %install in the spec, doesn't mean at the end of macro expanded %install shell script, so what happens is simply that the shell where find-debuginfo.sh is executed from, exits before any of that happens.

'exit 0' is not the right way to skip %check.

**Comment by ffesti** [comment]
Yes. Don't do that!
