### ISSUE TITLE
`%{_builddir}` has different values in different contexts

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/rpm#3151]
**Describe the bug**

In ruby.spec, we are using `%{_builddir}` on several places. E.g. [here](https://src.fedoraproject.org/rpms/ruby/blob/677893973e5e3cac2a1eb8a691aad6f5feccf69c/f/ruby.spec#_977-978):

~~~
# Check RubyGems version.
[ "`make -C %{_vpath_builddir} -s runruby TESTRUN_SCRIPT='%{_builddir}/%{buildsubdir}/bin/gem -v' | tail -1`" == '%{rubygems_version}' ]
~~~

which expands to

~~~
++ make -C redhat-linux-build -s runruby 'TESTRUN_SCRIPT=/builddir/build/BUILD/ruby-3.3.1-build/ruby-3.3.1/bin/gem -v'
++ tail -1
+ '[' 3.5.9 == 3.5.9 ']'
~~~

But also on other places, such as [local generator setup](https://src.fedoraproject.org/rpms/ruby/blob/677893973e5e3cac2a1eb8a691aad6f5feccf69c/f/ruby.spec#_242-245):

~~~
%global __local_generator_requires make -C %{_builddir}/%{buildsubdir}/%{_vpath_builddir} -s runruby TESTRUN_SCRIPT="--enable-gems %{SOURCE9}"
%global __local_generator_provides make -C %{_builddir}/%{buildsubdir}/%{_vpath_builddir} -s runruby TESTRUN_SCRIPT="--enable-gems %{SOURCE10}"
%global __local_generator_conflicts make -C %{_builddir}/%{buildsubdir}/%{_vpath_builddir} -s runruby TESTRUN_SCRIPT="--enable-gems %{SOURCE11}"
%global __local_generator_path ^%{gem_dir}/specifications/.*\.gemspec$
~~~

However, this expands differently and results in errors:

~~~
Processing files: ruby-default-gems-3.3.1-8.fc41.noarch
make: *** /builddir/build/BUILD/ruby-3.3.1/redhat-linux-build: No such file or directory.  Stop.
~~~

The full logs can be found [here](https://koji.fedoraproject.org/koji/buildinfo?buildID=2461729)

**Expected behavior**
The `%{_builddir}` is consistent.

**Environment**
rpm-4.19.91-8.fc41.x86_64

**Comment by pmatilai** [comment]
Unfortunately there's no way to make it consistent without breaking the rest of the world too.

**Comment by pmatilai** [comment]
Hmm. Maybe, maybe we could actually work around this by *undefining* %{_builddir} for the early spec parse. Basically, grab the initial value before actual entry to the spec, undefine %_builddir and then set it to the final value at end of preamble parse when we know it. That would let the %global case still work (there are more than a handful of them in fedora, and no doub telsewhere)

**Comment by voxik** [comment]
> The real issue here is using %global.

Experimenting with `%define` was my next step. Thank you for confirming.

> Hmm. Maybe, maybe we could actually work around this by undefining %{_builddir} for the early spec parse.

If the `%{_builddir}` macro was not defined at that stage, it would be likely easier to identify.

I am also unsure if I am supposed to use `%{builddir}` instead of the `%{_builddir}`

**Comment by pmatilai** [comment]
Yeah it would be easier to identify, but more importantly you wouldn't even need to care about this because then it's just yet another undefined macro that'll fall through the %global unscatched, among the rest of them (eg %{buildsubdir} is only defined when %setup is executed). The whole thing gets re-expanded much later anyhow.

**Comment by pmatilai** [comment]
> I am also unsure if I am supposed to use %{builddir} instead of the %{_builddir}

We probably need to clarify this in the docs. The short answer is that it's perfectly okay to keep using %{_builddir}. It's always the same value as %{builddir} in rpm >= 4.20, the separate %{builddir} is to let you know it's the new behavior, eg %{builddir} is always yours, %{_builddir} may be shared between multiple packages (when building with older rpm).

**Comment by pmatilai** [comment]
I'm going to try and see if this can't be worked around behind the scenes, because ruby.spec is by no means the only case of this. Thanks for reporting!

**Comment by voxik** [comment]
> Hmm, except that %{builddir} gets only defined now after parsing the preamble and specs commonly put most of their macros there, so it's not perhaps ideal just now.

Just FTR, because `%{builddir}` is defined later, it also might serve as a workaround. Just tried that.

But I'll likely go with `%define` / `%{_builddir}`, because it has better backward compatibility if I am not mistaken.

**Comment by pmatilai** [comment]
Yeah %{builddir} would indeed work because it's indeed defined, it's just incompatible with anything < 4.20. %define with %{_builddir} is compatible and correct, yes.
