### ISSUE TITLE
RPM 4.20 introduces special characters in build dir

### ISSUE THREAD

**Issue by nikic** [rpm-software-management/rpm#3159]
The new build directory handling in RPM 4.20 includes the full package NVR in the build directory. If the NVR includes `~` (which is commonly used for `~beta`, `~rc` etc), that means you now have a special character in the build directory. Tests may not be prepared to deal with this. I've encountered two instances of this now and while one was easy to fix, the other one is not (fixing it would come with significant externalities).

So I have two questions here:
 * Is these some easy way to avoid the special character in a specific RPM (without changing the NVR)?
 * Might it make sense to sanitize the embedded NVR to avoid special characters in general? Like replace `~` with `.tilde.` or something?

**Comment by pmatilai** [comment]
Oh... this would be (another) unforeseen consequence of the builddir changes.
Thanks for the report! As it happens https://bugzilla.redhat.com/show_bug.cgi?id=2290987 was far more obvious, having first seen this one.

I think we'll need to sanitize the path somehow.
