### ISSUE TITLE
Relocatable packages with plain `/` in `%files` can't be installed as regular user

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#3173]
**Describe the bug**
An attempt to install a relocatable package as a regular user that was built from a spec file that contains
```
Prefix: /
%files
%{prefix}
```
results in a failure.

**To Reproduce**
1. Build the following package:
```
Name:           reproducer
Version:        0.0.1
Release:        1%{?dist}
Summary:        Reproducer for JIRA 
License:        GPL
Prefix:         /

%description
%{summary}.

%install
mkdir -p $RPM_BUILD_ROOT/foo
touch $RPM_BUILD_ROOT/foo/bar

%files
%{prefix}

%changelog
* Wed Mar 13 2024 root
- 
```
2. Install the package locally as non-root user:
```
$ rpm -Uhv --prefix $PWD/RPMROOTDIR --dbpath $PWD/RPMDB /path/to/reproducer.rpm
```

**Actual behavior**
```
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:reproducer-0.0.1-1               ################################# [100%]
error: unpacking of archive failed on file [...]/RPMROOTDIR//: cpio: chmod failed - Device or resource busy
error: reproducer-0.0.1-1.x86_64: install failed
```

**Expected behavior**
No failure, package gets installed successfully.

**Environment**
 - OS / Distribution: RHEL-8 and later
 - Version: RPM 4.16.1.3

**Additional context**
This is a regression introduced with the fsm rework to use the `*at()` family of calls that was made to address the symlink CVEs (#1919).

The root cause seems to be this:

When processing the payload files, we eventually call `fsmSetmeta()` for the top-level directory `/` which obviously fails for a regular user. This happens despite us already being (via `di.dirfd`) in the right top-level directory `$PWD/RPMROOTDIR`, because `fp->fpath` is set to `/` there and when we pass it to `fchownat(2)`, since the path is absolute, `di.dirfd` is ignored by the function (as per specification).

One fix that works (but I haven't yet thought about its consequences) is simply making sure `fp->fpath` is never an absolute path, i.e. replacing the `/` with a `.`, like so:

```diff
diff --git a/lib/fsm.c b/lib/fsm.c
index 20b270cf5..938a2db1d 100644
--- a/lib/fsm.c
+++ b/lib/fsm.c
@@ -78,7 +78,7 @@ static int fsmClose(int *wfdp);
 static char * fsmFsPath(rpmfi fi, const char * suffix)
 {
     const char *bn = rpmfiBN(fi);
-    return rstrscat(NULL, *bn ? bn : "/", suffix ? suffix : "", NULL);
+    return rstrscat(NULL, *bn ? bn : ".", suffix ? suffix : "", NULL);
 }
 
 static int fsmLink(int odirfd, const char *opath, int dirfd, const char *path)
```

With that patch applied, removing the package afterwards yields a warning (due to the `/` path being attempted to be removed, i.e. a similar case) so that will need attention too.

This use case comes from a RHEL customer and was filed as https://issues.redhat.com/browse/RHEL-28967.

**Comment by pmatilai** [comment]
> When processing the payload files, we eventually call fsmSetmeta() for the top-level directory / which obviously fails for a regular user. This happens despite us already being (via di.dirfd) in the right top-level directory $PWD/RPMROOTDIR, because fp->fpath is set to / there and when we pass it to fchownat(2), since the path is absolute, di.dirfd is ignored by the function (as per specification).

Oh... what fun. It's basically a gotcha of the *at() APIs I never considered at all. So your suggestion to replace "/" with "." seems like the right thing to do, the code is not really wanting to touch real "/" all, it's just getting thrown off by the "/" basename. As per the API spec.

With the relative path, the removal case is not failing because it tries to remove the real "/" but because of this:
`D:  fsmRmdir (8 .) Invalid argument` 
Ie "." is not a valid argument to unlinkat() . 

https://stackoverflow.com/questions/76844005/how-to-get-unlinkatdir-fd-at-removedir-to-work talks about this: the gotcha is in the rmdir(2) manual:
> EINVAL pathname has .  as last component.

This seems pretty annoying. We must never try to create or remove the real "/" - the old code had specific check on creation but at least as of 4.17 actually tried to remove "/" on erasure, which is wrong no matter what the package says. The current code doesn't need the test on creation, but it would need to check against removal. But, in this case we should remove the RPMROOTDIR we created because the package owns it and older rpm versions did remove it. But, because "." is not acceptable it seems we'd need to go one directory upwards. Which might be a bit tricky to to fit there. Maybe it needs a special case in fsmRmdir(), as ugly as that seems.

**Comment by dmnks** [comment]
Thanks for the suggestions! Indeed, going one directory upwards would've been the solution (and I had a working patch for that already)... except then I realized the root cause was actually a bit different. We weren't populating the package's dirname list (when processing relocations) correctly as we didn't insert the *parent* of the relocation target into it. With any other prefixes, this already worked fine, just not with the sole `/`. Fixed in #3223.

As for the "don't even try to remove `/`", that's a separate issue that I'll patch separately later (it's easy, just need to re-check something).

**Comment by pmatilai** [comment]
Ohh... nice find, and a brave man to touch the relocation code :smile:

**Comment by pmatilai** [comment]
It's also a good example of the importance of finding the *real* root cause. If a fix looks convoluted and doesn't feel right, it probably isn't.

**Comment by dmnks** [comment]
Truly. If after several iterations of trying to make it less hacky you still have this feeling of "this just doesn't feel right", then it probably isn't right :smile: 

Here's a short backstory:

My initial patch was about keeping the parent fd opened during the tree walk we normally do in `ensureDir()`, and then using *that* fd to remove the relocated root directory at the end. The patch wasn't big and it worked fine so I was going to just submit that as a PR. But it kept bugging me since it felt wrong to have to do this dance in the fsm logic itself just to accommodate for this one (almost niche) use case.

Only then something clicked in me: Why does this work fine when relocating anything other than the root itself (e.g. `/foo` instead of `/`)? That led me to the realization: "Oh, the parent of the relocation target somehow *is* makes its way to the file list (and gets processed in fsm normally) in these cases, that seems suspicious!" :smile:
