### ISSUE TITLE
sb in lhs and rhs

### ISSUE THREAD

**Issue by newrow** [rpm-software-management/rpm#3185]
https://github.com/rpm-software-management/rpm/blob/c00d8a0ed32169baf82cd0a34ffd1c9377b09c38/lib/rpmvs.c#L443

https://github.com/rpm-software-management/rpm/blob/c00d8a0ed32169baf82cd0a34ffd1c9377b09c38/lib/rpmvs.c#L445

both operands are sb

I guess it should be like

    sb->* - sa->*

**Comment by ffesti** [comment]
OK, turn out we have an older ticket for this also: #1057

**Comment by pmatilai** [comment]
Closing as duplicate of #1057
