### ISSUE TITLE
When some of the mandatory %buildsystem_* macros is undefined, the error is confusing

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#3190]
**Describe the bug**
https://github.com/rpm-software-management/rpm/blob/775acf13850373c16d4b0d02a1970339c381f19b/build/parseSpec.c#L965-L971

Currently, all of `%buildsystem_name_conf`, `%buildsystem_name_build`, and `%buildsystem_name_install` need to be defined for the buildsystem to function.

This matches the [documentation](https://rpm-software-management.github.io/rpm/manual/buildsystem.html) which says those are mandatory.

When one of the macros is missing, I get:

```
error: line X: Unknown buildsystem: name
```

This is a confusing error. I would pretty much prefer to see something like:

```
error: line X: Misconfigured buildsystem: name (required parametric macro %buildsystem_name_conf not defined)
```

**To Reproduce**

1. Define `%buildsystem_foo_build` and `%buildsystem_foo_install`, omit `%buildsystem_foo_conf`
2. Try building a package with `BuildSystem: foo`
3. Error encountered: `Unknown buildsystem: foo`

Alternatively:

1. Don't define anything
2. Try building a package with `BuildSystem: foo`
3. Error encountered: `Unknown buildsystem: foo`

**Expected behavior**
The buildsystem is known, just badly defined. This should be a different error message.

**Environment**
 - OS / Distribution: Fedora 41
 - Version rpm-4.19.92-1.fc41

See also https://github.com/rpm-software-management/rpm/discussions/3191 (the reason I got this error in the first place was that I don't need a `%conf` section).

**Comment by ffesti** [comment]
Well, as you quoted above there is a more descriptive debug message. The message you are getting is for packagers and assumes that RPM is configured properly. There the only way for this going wrong is the packager trying a build system that doesn't exist.

If you are developing your own build system you can use -v to get the more detailed message. While not showing them by default may confuse you it is the right thing for normal packagers. They should not try to define a macro but realize that they either have a typo in the buil system name or that the build system is not available in their (release of the) distribution.

**Comment by ffesti** [comment]
But may be we can detect incomplete build systems and give a different error for those.

**Comment by hroncok** [comment]
That's what I had in mind. Buildsystem does not exist and buildsystem is incompletely defined are two distinct errors in my head.

**Comment by hroncok** [comment]
Thank you!
