### ISSUE TITLE
%prep working directory different when using --build-in-place in Fedora 40 vs Fedora Rawhide

### ISSUE THREAD

**Issue by DaanDeMeyer** [rpm-software-management/rpm#3208]
**Describe the bug**

Something is still different between rpm from Fedora 40 and rpm from Fedora Rawhide when it comes to `--build-in-place`:

Fedora 40:

```
➜  mkosi git:(cache) ✗ mkosi -r 40 --debug-shell -f
Create subvolume '/home/daandemeyer/.cache/mkosi/mkosi-workspace-4b0haoi_/root'
‣ Building default image
Create subvolume '/home/daandemeyer/.cache/mkosi/mkosi-workspace-d39y103x/root'
‣  Copying cached trees
Create snapshot of '/home/daandemeyer/projects/mkosi/mkosi.cache/fedora~40~x86-64.cache' in '/home/daandemeyer/.cache/mkosi/mkosi-workspace-d39y103x/root'
‣  Running build script /home/daandemeyer/projects/mkosi/mkosi.conf.d/30-selinux/mkosi.build.chroot…
++ '[' 0 = 0 ']'
++ echo --nocheck
+ env --chdir=selinux-policy rpmbuild -bb --build-in-place --nocheck --define '_topdir /var/tmp' --define '_sourcedir rpm' --define '_rpmdir /work/packages' --define '_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm' rpm/selinux-policy.spec
setting SOURCE_DATE_EPOCH=1720483200
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.JV8ykS
+ umask 022
+ cd /work/src/selinux-policy
+ ls
COPYING  Changelog  Changelog.old  INSTALL  Makefile  README  README.md  Rules.modular  Rules.monolithic  VERSION  base.conf  build.conf  config  doc  man  packit.yaml  plans  policy  rpm  scripts  support  tmp
```

Fedora Rawhide:

```
➜  mkosi git:(cache) ✗ mkosi -r rawhide --debug-shell -f
Create subvolume '/home/daandemeyer/.cache/mkosi/mkosi-workspace-tgzzecju/root'
‣ Building default image
Create subvolume '/home/daandemeyer/.cache/mkosi/mkosi-workspace-mvzellct/root'
‣  Copying cached trees
Create snapshot of '/home/daandemeyer/projects/mkosi/mkosi.cache/fedora~rawhide~x86-64.cache' in '/home/daandemeyer/.cache/mkosi/mkosi-workspace-mvzellct/root'
‣  Running build script /home/daandemeyer/projects/mkosi/mkosi.conf.d/30-selinux/mkosi.build.chroot…
++ '[' 0 = 0 ']'
++ echo --nocheck
+ env --chdir=selinux-policy rpmbuild -bb --build-in-place --nocheck --define '_topdir /var/tmp' --define '_sourcedir rpm' --define '_rpmdir /work/packages' --define '_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm' rpm/selinux-policy.spec
Building target platforms: noarch
Building for target noarch
setting SOURCE_DATE_EPOCH=1720483200
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.M95J37
+ umask 022
+ cd /var/tmp/BUILD/selinux-policy-41.7-build
+ test -d /var/tmp/BUILD/selinux-policy-41.7-build
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /var/tmp/BUILD/selinux-policy-41.7-build
+ /usr/bin/rm -rf /var/tmp/BUILD/selinux-policy-41.7-build
+ /usr/bin/mkdir -p /var/tmp/BUILD/selinux-policy-41.7-build
+ /usr/bin/mkdir -p /var/tmp/BUILD/selinux-policy-41.7-build/SPECPARTS
+ /usr/bin/ln -s /work/src/selinux-policy /var/tmp/BUILD/selinux-policy-41.7-build/selinux-policy-41.7
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.AwsOez
+ umask 022
+ cd /var/tmp/BUILD/selinux-policy-41.7-build
+ ls
SPECPARTS  selinux-policy-41.7
```

The %prep section that's being executed:

```
%prep
%autosetup -p 1 -n %{name}-%{commit}
```

**To Reproduce**
1. Try to build the selinux-policy rpm from Rawhide on both Fedora 40 and Fedora rawhide

https://src.fedoraproject.org/rpms/selinux-policy/blob/rawhide/f/selinux-policy.spec

**Expected behavior**

The working directory in the %prep section is the same for both Fedora 40 and Fedora Rawhide 

**Output**

See above

**Environment**

See above

**Comment by DaanDeMeyer** [comment]
Somewhat related, specifying `_sourcedir` as a relative directory is also broken with rpm 4.20:

```
Building target platforms: noarch
Building for target noarch
setting SOURCE_DATE_EPOCH=1721952000
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.FddfFZ
+ umask 022
+ cd /var/tmp/BUILD/selinux-policy-41.11-build
+ test -d /var/tmp/BUILD/selinux-policy-41.11-build
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /var/tmp/BUILD/selinux-policy-41.11-build
+ /usr/bin/rm -rf /var/tmp/BUILD/selinux-policy-41.11-build
+ /usr/bin/mkdir -p /var/tmp/BUILD/selinux-policy-41.11-build
+ /usr/bin/mkdir -p /var/tmp/BUILD/selinux-policy-41.11-build/SPECPARTS
+ /usr/bin/ln -s /work/src/selinux-policy /var/tmp/BUILD/selinux-policy-41.11-build/selinux-policy-41.11
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.nWBlbf
+ umask 022
+ cd /var/tmp/BUILD/selinux-policy-41.11-build
+ tar -C policy/modules/contrib -xf rpm/container-selinux.tgz
tar: rpm/container-selinux.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
error: Bad exit status from /var/tmp/rpm-tmp.nWBlbf (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.nWBlbf (%prep)
```

**Comment by pmatilai** [comment]
Relative _foodir for the build stuff was never supported by rpm, it just happened to work in various cases in the past (see #3128, we're considering on making it explicit). The new intermediate build directory in >= 4.20 just means it happens to work for far fewer cases.

I tend to agree that the directory contents should be the same after %setup (which is what does the `cd` to the directory the unpacked sources are in), but then --build-in-place doesn't actually honor any of %setup. So this probably needs an extra 'cd %{buildsubdir}' someplace, I just don't know where. %setup cannot both affect and not affect the result :smile:

**Comment by DaanDeMeyer** [comment]
> Relative _foodir for the build stuff was never supported by rpm, it just happened to work in various cases in the past (see https://github.com/rpm-software-management/rpm/issues/3128, we're considering on making it explicit). The new intermediate build directory in >= 4.20 just means it happens to work for far fewer cases.

Makes sense, I'll make sure to use absolute paths everywhere then

**Comment by pmatilai** [comment]
So this issue is really at the heart of the problem with --build-in-place.

Working on #3216 (see PR #3252)  kinda convinced me that --build-in-place should probably *imply* skipping %prep, because that actually offers a way to make sense out of this all. For an in-place build, it's not enough to skip just %setup (like it currently does) because there may be patches getting applied with %patch or manual git/patch/whatnot invocations, and we can't support that in an in-place operation. A spec *could* be doing something else in %prep too, but it's a case of trying to eat and keep the cake: it doesn't work, even in the digital world.

Having in-place build imply skipping %prep would no doubt break some existing things, but it'd give us a well-defined behavior that we can actually support, the existing behavior is broken and unfixable, only of course existing users have adapted to make their stuff work with those quirks.

**Comment by DaanDeMeyer** [comment]
> So this issue is really at the heart of the problem with --build-in-place.
> 
> Working on #3216 (see PR #3252) kinda convinced me that --build-in-place should probably _imply_ skipping %prep, because that actually offers a way to make sense out of this all. For an in-place build, it's not enough to skip just %setup (like it currently does) because there may be patches getting applied with %patch or manual git/patch/whatnot invocations, and we can't support that in an in-place operation because an rpmbuild is by definition a repeatable process. A spec _could_ be doing something else in %prep too, but attempting to automagically do some parts of %prep in some situations and skip others is a case of trying to eat and keep the cake: it doesn't work, even in the digital world.
> 
> Having in-place build imply skipping %prep would no doubt break some existing things, but it'd give us a well-defined behavior that we can actually support, the existing behavior is broken and unfixable, only of course existing users have adapted to make their stuff work with those quirks.

I can make that work I think.

**Comment by pmatilai** [comment]
It just occurred to me that another possibility could be defining build-in-place as to override the main %prep section, but allow appended sections to be executed as normal for other actions. This would probably help share a spec between a "normal" and in-place build. For example:

```
%prep
%autosetup

%prep -a
# nuke an accidental binary in dist tarball
rm -f bin/blob
```

With that scenario, an in-place build of the spec would skip the main %prep with %autosetup (by placing an empty script there) but still execute the -a section to do another action. This seems to allow for much more flexibility at some cost to ambiguity and options for abuse (like placing %setup in %prep -a section), but that could be declared an operator error I guess.

**Comment by DaanDeMeyer** [comment]
> It just occurred to me that another possibility could be defining build-in-place as to override the main %prep section, but allow appended sections to be executed as normal for other actions. This would probably help share a spec between a "normal" and in-place build. For example:
> 
> ```
> %prep
> %autosetup
> 
> %prep -a
> # nuke an accidental binary in dist tarball
> rm -f bin/blob
> ```
> 
> With that scenario, an in-place build of the spec would skip the main %prep with %autosetup (by placing an empty script there) but still execute the -a section to do another action. This seems to allow for much more flexibility at some cost to ambiguity and opportunities for misuse (like placing %setup in %prep -a section), but that could be declared an operator error I guess.

So I had a quick look, and I guess skipping %prep would cause issues with the selinux-policy spec when using build in place:

```

%prep
%autosetup -p 1 -n %{name}-%{commit}
tar -C policy/modules/contrib -xf %{SOURCE35}

mkdir selinux_config
for i in %{SOURCE1} %{SOURCE2} %{SOURCE3} %{SOURCE4} %{SOURCE5} %{SOURCE6} %{SOURCE8} %{SOURCE14} %{SOURCE15} %{SOURCE17} %{SOURCE18} %{SOURCE19} %{SOURCE20} %{SOURCE22} %{SOURCE23} %{SOURCE25} %{SOURCE26};do
 cp $i selinux_config
done
```

So having a way to still have a %prep would indeed be quite useful to I could propose moving everything but %autosetup to a separate %prep.

**Comment by pmatilai** [comment]
Yup, that selinux.spec snippet was what pretty much inspired that %prep -a idea.

One open question there is: where does %{SOURCEn} come from with --build-in-place? (this goes beyond just %prep of course). Using the normal %_sourcedir seems very wrong for that, and of course you mentioned manually overriding it.

If %prep is just plain skipped then that copy loop would need to be moved to %build. Whether that belongs to %prep or %build gets into the splitting hairs department :smile: Ultimately I think a spec will need to generally be at least somewhat aware of build-in-place to support that mode, there's just too many things that can differ for any spec to be usable otherwise.

**Comment by DaanDeMeyer** [comment]
> Yup, that selinux.spec snippet was what pretty much inspired that %prep -a idea.
> 
> One open question there is: where does %{SOURCEn} come from with --build-in-place? (this goes beyond just %prep of course). Using the normal %_sourcedir seems very wrong for that, and of course you mentioned manually overriding it.
> 
> If %prep is just plain skipped then that copy loop would need to be moved to %build. Whether that belongs to %prep or %build gets into the splitting hairs department 😄 Ultimately I think a spec will need to generally be at least somewhat aware of build-in-place to support that mode, there's just too many things that can differ for any spec to be usable otherwise.

Yeah that's fine for me. Though I have been entertaining the idea to at some point try to build the entirety of KDE from source with rpmbuild and having to adapt every single KDE spec would be a bit heavy. Maybe at some point guidelines could be published that lead to specs that are triviailly usable with `--build-in-place`.

Related to that, being able to override the version and release from the rpmbuild CLI when using --build-in-place would also be very useful. Currently I have to hack that into each spec manually.

**Comment by dmnks** [comment]
The way I look at "build in place" mode is that it's an *alternative*, built-in `%prep` stage, one that replaces the internal build directory with a symlink to the current directory. Therefore, if we implemented "build in place" as a shell script that can be changed by the packager, that would cover such special cases. Is that an crazy idea?

**Comment by pmatilai** [comment]
Pretty much the same thought occurred to me, so I don't think it's crazy (or then we both are :laughing: )
But what we do for in-place builds is mostly an internal affair, our built-in alternative for in-place would be an empty shell script. And then there's the issue of how to actually express the packager overridden alternative in the spec or on cli.

There may well be something worth further investigation in that direction, but it's not something we can achieve for 4.20.

**Comment by pmatilai** [comment]
Eh, scratch the above, or at least some of it.

The built-in in-place alternative %prep is indeed exactly that one symlink that is currently hardwired in the code. And thinking along that path is exactly how I landed on the %prep -a idea, but I think talking about it in terms of an alternative makes it easier to explain/understand. It also would be cleaner in some ways at least.

**Comment by dmnks** [comment]
Oops, I was in the middle of writing a reply but you were quicker :smile: Anyway, my original thinking was this:

If there's a way to (easily) turn the logic that makes in-place special (now I understand it's just the symlink creation, right?) into a shell script, then we could turn the whole problem into the more general "support replacing %prep with a custom script". Then, we could just ship a "sample" variant that does this in-place, with `--build-in-place` becoming just a shorthand for a whatever the more general CLI/spec mechanism for expressing this would be. Note that I'm intentionally being vague here as I don't have a specific idea either :smile: 

That said, in a way, `%prep -a` is *exactly* that, i.e. a way to extend (an already defined) scriptlet. So yep, we're thinking along the same lines here, this is mostly just a matter of semantics and how we define the feature, which is kinda the point of this discussion, I guess :smile:

**Comment by dmnks** [comment]
> But, treating it as an alternative to %prep means that we cannot honor --noprep at all for in-place builds because we _depend_ on that symlink being there. So that seems like a counter-argument to exposing the mechanism to the packager. It's such a wonderfully wacko setup in all.

Oh, indeed... Sigh :smile:

**Comment by dmnks** [comment]
Also, the whole idea about "make this into a script!" is just a special case of the more general discussion that led to the introduction of the prepend/append modes for scriptlets. If we were to support replacing scriptlets at build time with user-supplied ones, we should do it across the board, not just specifically for `%prep`, I guess.

**Comment by pmatilai** [comment]
%prep is the only thing needing a wholly different action with build-in-place though.

Ignoring the possibility of replacement for now, I really like the idea of build-in-place really just overriding the %prep with the internal piece of shell-script that creates the symlink. Then we could make --noprep actually mean the thing everywhere: you *have to* let %prep run once, and --noprep is only a legit option for consequent runs with --short-circuit or similar.

But what is probably the most profilic user of --build-in-place - the kernel upstream packaging - expects --build-in-place --noprep to work. We work around that by dealing with the build-in-place setup inside %mkbuilddir (see eg #3252), but it semantically really should be a %prep thing. Argh.

**Comment by pmatilai** [comment]
...

Automatically disabling the spec %prep would be a step in the right direction though: that means eg the upstream kernel spec usage *can drop* the --noprep clause. It's only there now because it wouldn't work otherwise with the spec they have, and that goes for any "normal" spec %prep that hasn't been particularly tuned to build-in-place operation.

**Comment by dmnks** [comment]
... but the answer to that is "just use the new append mode", I guess. Or, move that logic to %build...

**Comment by pmatilai** [comment]
Had a look at doing something fancier here, and quickly came to the conclusion that it's not something we can get into just now. So lets go with the simple "skip %prep" logic, it's at least in the right direction if we want to make the mechanism more elaborate/replaceable later since people can now drop --noprep with --build-in-place.
