### ISSUE TITLE
rpmsign broken: error: sign_hash failed

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#3214]
Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=2297927:

```
# rpm -q rpm
rpm-4.19.92-2.fc41.x86_64
# rpmsign --addsign --signfiles --fskpath=/etc/keys/privkey_evm.pem /root/rpmbuild/RPMS/noarch/rpm-ima-sign-test-1-1.noarch.rpm
/root/rpmbuild/RPMS/noarch/rpm-ima-sign-test-1-1.noarch.rpm:
error: sign_hash failed
error: signFile failed
```

This is a regression compared to
```
# rpm -q rpm
rpm-4.19.91-13.fc41.x86_64
[root@vm-10-0-186-98 tmp.UFeskSJtgO]# rpmsign --addsign --signfiles --fskpath=/etc/keys/privkey_evm.pem /root/rpmbuild/RPMS/noarch/rpm-ima-sign-test-1-1.noarch.rpm
/root/rpmbuild/RPMS/noarch/rpm-ima-sign-test-1-1.noarch.rpm:
hash(sha256): 562eb1111ef3e3c2ec9c60e53b27af259ff984f31a804d97bfd49df13e843128
evm/ima signature: 264 bytes
```

FYI, This is identical scenario as in the previously reported bug https://bugzilla.redhat.com/show_bug.cgi?id=2291183 although the error message is not entirely identical.

The test case source is available at https://github.com/RedHat-SP-Security/keylime-tests/blob/main/functional/install-rpm-with-ima-signature/test.sh with IMA keys being generated here https://github.com/RedHat-SP-Security/keylime-tests/blob/main/Library/test-helpers/lib.sh#L1494

Reproducible: Always

Steps to Reproduce:
1. attempt to sign RPM file using --signfiles
2.
3.
Actual Results:  
Failure

Expected Results:  
Signing succeeds.

Reproducible: Always

**Comment by pmatilai** [comment]
This looks more like a regression in ima-evm-tools while deprecating the sign_hash() function we use than anything in rpm, when the related code in rpm hasn't changed at all. Issues should be investigated at least enough to confirm them before moving upstream.

Closing this one, if I'm wrong we can always reopen later.
