### ISSUE TITLE
RFE: add a test(s) for IMA signing

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3237]
IMA is actually used by distros now, we should cover it in our tests.
Testing the IMA plugin may be undoable in a container, but at least we should test that signing works.

We can probably base on these, they're GPL v2.1:
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/functional/install-rpm-with-ima-signature/test.sh
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/Library/test-helpers/lib.sh#L1494

**Comment by dmnks** [comment]
Indeed, I'm just not sure if this is doable in containers. But maybe there's a way (finding out will be part of this ticket).

**Comment by pmatilai** [comment]
As the description says: we may not be able to the the plugin (ie installation), but signing doesn't require any fancy kernel stuff.

**Comment by dmnks** [comment]
One quick way to test IMA file signatures:

```
openssl ecparam -name secp256k1 -genkey -noout -out privkey.pem
rpmsign --addsign --signfiles --fskpath=./privkey.pem /path/to/your/package.rpm
rpm -qp --qf "[%{filenames} %{filesignatures}\n]" /path/to/your/package.rpm
```
