### ISSUE TITLE
Document using Sequoia for signing

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3248]
Turns out that using Sequoia for signing rpm's is pretty straightforward, basically:

```
%_gpg_name <KEYID>
%__gpg /usr/bin/sq
%__gpg_sign_cmd %{__gpg} %{__gpg} sign \
        %{?_gpg_name:--signer-key %{_gpg_name}} \
        --detached -o %{shescape:%{?__signature_filename}} \
        %{?__plaintext_filename:-- %{shescape:%{__plaintext_filename}}}
```

A key difference to gpg is the keyid (pun not entirely unintentional): where gpg takes a rather freeform string and tries to match it to a key, Sequoia requires an exact keyid or fingerprint.

We should at least document this, but also have a look at making our signing more tool-agnostic. Several error messages hardwire "gpg" even if configured to do something else.

@nwalfield FYI

**Comment by nwalfield** [comment]
> We should at least document this, 

I think documenting how to sign with `sq` is a great idea in particular given that [`sq` will be shipped with RHEL 10](https://bugzilla.redhat.com/show_bug.cgi?id=2305965).

> A key difference to gpg is the keyid (pun not entirely unintentional): where gpg takes a rather freeform string and tries to match it to a key, Sequoia requires an exact keyid or fingerprint.

I would say that this limitation is a "feature."  It would be annoying if someone specified their email address, later inadvertently imported a key with the same address, and the wrong key was used when signing a package.  It's probably not a security issue, but it would be a bit annoying to debug.

> We should at least document this, but also have a look at making our signing more tool-agnostic.  Several error messages hardwire "gpg" even if configured to do something else.

Yeah, I agree that would be good.

@pmatilai: I'm not sure what other input might be useful.  So, if you are looking for something else, please ask :).

**Comment by pmatilai** [comment]
> I think documenting how to sign with sq is a great idea in particular given that [sq will be shipped with RHEL 10](https://bugzilla.redhat.com/show_bug.cgi?id=2305965).

Yup, that's how I ended up being asked about it :smile: 

And FWIW, I don't think the need to specify exact keyid is any issue at all, I was always a bit surprised just how loosely GPG lets you get away with there.

**Comment by pmatilai** [comment]
Ended up with much more than just documentation because ... it felt like if we document the above in rpm, we'll be stuck with the bad _gpg_fu names forever. Comments on naming etc totally welcome, I'm not particularly extatic about the new macro names in the PR, its just something to avoid getting hung up on a name.

**Comment by nwalfield** [comment]
I added a few comments to [the commit](https://github.com/pmatilai/rpm/commit/7e29b2101ae73d09eefbe93d0b019e57c6cbbdb5).  I don't know why they aren't showing up here.  In short, they are just a few minor suggestions.

**Comment by pmatilai** [comment]
Yeah comments to commits are a bit of a black hole, better to use the GH review thing (don't be shy, you're absolutely welcome to do that, even for minor suggestions :smile: )
