### ISSUE TITLE
Dependency generator documentation doesn't mention %__NAME_suggests etc

### ISSUE THREAD

**Issue by tomhughes** [rpm-software-management/rpm#325]
The dependency generator documentation (at http://rpm.org/user_doc/dependency_generators.html) doesn't mention the macros for the new dependency types, eg `%__NAME_suggests`.

**Comment by pmatilai** [comment]
Thanks for pointing this out, fixed now by https://github.com/rpm-software-management/rpm-web/commit/ba78ee300a39a75c56760d675e02ce0d5a5478a9

I opened up the issue tracker on rpm-web too so in the future website issues can be reported there directly.
