### ISSUE TITLE
rpm-4.20 announce should speak about API changes

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#3273]
https://rpm.org/wiki/Releases/4.20.0 doesn't list any API changes.
But : 
- the internal OpenPGP parser has been removed so rpm/rpmpgp.h saw a lot of changes
- there's a new rpmdsIsSysuser() function
- there's a new rpmMacroBuf class with the associated API
- …

This should be listed.

**Comment by pmatilai** [comment]
Fixed in https://github.com/rpm-software-management/rpm-web/commit/0d042f64aaffddc54e301bda5e5f2eb257ca9ee7
