### ISSUE TITLE
264: rpmsign --addsign                               FAILED (rpmsigdig.at:461)

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#3277]
**Describe the bug**
When I use OBS to build rpm, the "rpmsign --addsign" fails, but the manual execution succeeds.

When I manually import the private key, I found that user input was required, probably because of the gpg version.
```
[root@localhost ~]# gpg2 --import data/keys/*.secret
gpg: key A72B7D4F62837BEA: "Alice Lovelace <alice@example.org>" not changed
gpg: key A72B7D4F62837BEA: secret key imported
gpg: WARNING: key A72B7D4F62837BEA contains preferences for unavailable
algorithms on these user IDs:
gpg:          "Alice <alice@example.org>": preference for compression algorithm 3
gpg:          "Alice Lovelace <alice@example.org>": preference for compression algorithm 3
gpg: it is strongly suggested that you update your preferences and
gpg: re-distribute this key to avoid potential algorithm mismatch problems

Set preference list to:
     Cipher: AES256, AES192, AES, 3DES
     AEAD:
     Digest: SHA512, SHA384, SHA256, SHA224, SHA1
     Compression: ZLIB, ZIP, Uncompressed
     Features: MDC, AEAD, Keyserver no-modify
Really update the preferences? (y/N)

Key not changed so no update needed.
gpg: key 4344591E1964C5FC: "rpm.org RSA testkey <rsa@rpm.org>" not changed
gpg: key 4344591E1964C5FC: secret key imported
gpg: WARNING: key 4344591E1964C5FC contains preferences for unavailable
algorithms on these user IDs:
gpg:          "rpm.org RSA testkey <rsa@rpm.org>": preference for compression algorithm 3
gpg: it is strongly suggested that you update your preferences and
gpg: re-distribute this key to avoid potential algorithm mismatch problems

Set preference list to:
     Cipher: AES256, AES192, AES, 3DES
     AEAD:
     Digest: SHA512, SHA384, SHA256, SHA224, SHA1
     Compression: ZLIB, ZIP, Uncompressed
     Features: MDC, AEAD, Keyserver no-modify
Really update the preferences? (y/N)

Key not changed so no update needed.
gpg: Total number processed: 2
gpg:              unchanged: 2
gpg:       secret keys read: 2
gpg:  secret keys unchanged: 2
```

In fact, before https://github.com/rpm-software-management/rpm/commit/ee2f59cc1770f6eb4493a59710e9ef749725da46 is mearged, the test case is successful (although gpg still requires user input), but after https://github.com/rpm-software-management/rpm/commit/ee2f59cc1770f6eb4493a59710e9ef749725da46 is mearged, the test case fails. 

I found the "*.secret" used in the use case to import the private key, which I don't think is very reasonable, because the different-creation-times.secret in https://github.com/rpm-software-management/rpm/commit/ee2f59cc1770f6eb4493a59710e9ef749725da46 is obviously irrelevant to the signature and should explicitly specify the private key to use.
https://github.com/rpm-software-management/rpm/blob/c5878f4684aa300c1bdb921bd780ef30d7e5f4cb/tests/rpmsigdig.at#L920

After the test, if rpm.org-rsa-2048-test.secret is specified, the test case can be executed successfully in OBS.

**Comment by pmatilai** [comment]
Out of curiosity: what gpg version is this? I've never seen such behavior from it in the tests.

**Comment by JetXujing** [comment]
> Out of curiosity: what gpg version is this? I've never seen such behavior from it in the tests.

[root@localhost SPECS]# gpg --version
gpg (GnuPG) 2.4.3
libgcrypt 1.10.2-unknown
Copyright (C) 2023 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /root/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB
