### ISSUE TITLE
The test cases of "rpm -e and verify colored files removed 2.{1,2}"  seem meaningless

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#3295]
Why are the following two test cases expected to fail? I see that the test case is introduced because of https://github.com/rpm-software-management/rpm/issues/1800. I think people expect to see that the test case is successfully executed (that is, "missing /usr/bin/hello" is displayed in the command output). The test case is expected to fail because the https://github.com/rpm-software-management/rpm/issues/1800 problem has not been resolved.
https://github.com/rpm-software-management/rpm/blob/5688de1c0fd1a4a938dca02efea122457c64401a/tests/rpme.at#L234
https://github.com/rpm-software-management/rpm/blob/5688de1c0fd1a4a938dca02efea122457c64401a/tests/rpme.at#L259

I think the test cases is unreasonable, and they simply give the expected results on the basis of errors. In other words, if the https://github.com/rpm-software-management/rpm/issues/1800 problem is fixed later, these two test cases may fail, but in fact, this is the expected normal result, and the test cases should be modified. In this case, the existence of the test cases is meaningless.

**Comment by dmnks** [comment]
> Why are the following two test cases expected to fail?

Because of: 066c00c908cb2616bae63a2bbc0f6078a694e808

> The test case is expected to fail because the #1800 problem has not been resolved.

Yes, that's very much the case, #1800 is not yet fixed. Once it is fixed, these tests will be "enabled" (i.e. the `AT_XFLAIL_IF`s will be removed).

> I think the test cases is unreasonable, and they simply give the expected results on the basis of errors. In other words, if the #1800 problem is fixed later, these two test cases may fail, but in fact, this is the expected normal result, and the test cases should be modified. In this case, the existence of the test cases is meaningless.

I don't follow. How are the test cases "unreasonable"?

**Comment by JetXujing** [comment]
Oh, I see, I didn't think about it: AT_XFAIL_IF will be removed if https://github.com/rpm-software-management/rpm/issues/1800 is fixed.

**Comment by dmnks** [comment]
Oh, understood now, no worries.
