### ISSUE TITLE
brp-remove-la-files won't remove symlink files

### ISSUE THREAD

**Issue by fundawang** [rpm-software-management/rpm#3304]
`scripts/brp-remove-la-files` now only removes files which are declared as libtool library files. But in `libpng`, it installed two files: `libpng16.la` and `libpng.la`, and `libpng.la` is a symlink towards `libpng16.la`. Thus, `libpng.la` won't get removed due to it is not match against current script.

**Comment by ffesti** [comment]
Looking at the code and the history it looks like it always just matched against regular files. We probably could add another run that matches symlinks only before deleting the regular files. That way we can check the files being linked to to be proper libtool library files.

**Comment by ffesti** [comment]
Can you please test if the PR linked above fixes your issue? Thanks!

**Comment by fundawang** [comment]
> Can you please test if the PR linked above fixes your issue? Thanks!

Yes, it works as expected.
