### ISSUE TITLE
Mass-rename all relevant sources to a C++ extension

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3316]
4.20 release is nigh (#3271) so as outlined in #3103, the time to do a mass-rename is closing in, this is simply a ticket to allow tracking + planning it. And maybe discuss a bit too.

The main "issue" here is deciding which suffix to use. From what I've seen, .cpp looks like the most common one for modern c++ code and would be in line with dnf5 which doesn't hurt either.

The other question is headers: we'll be dealing with plain C headers from here to eternity, so it seems like it'd be helpful to differentiate what is meant for C vs C++ consumption. .hpp seems like a consisntent and logical suffix there, and also what dnf5 uses. Not that it dictates in any way, but doesn't hurt either because it's a neighbor team really.

### AC: 
- C++ sources are renamed to `.cc` and C++ -only (ie those without __cplusplus guards) to `.hh`. Exempt from this rename are
  - python/
  - plugins/
  - lib/backend/ndb/rpm*.*
  - misc/
- hacks to force cmake to use C++ compiler on .c sources are removed
- a freshly configured tree builds, tarball creation works and the test-suite passes

Edit: the initial plan was to use cxx/hxx to match the common variable naming in build systems but the result is not something we can stand looking day after day. Seriously.

**Comment by pmatilai** [comment]
I don't think I've ever come across a .cxx/.hxx extension in any project that I've looked at, but that is a totally fair point.

**Comment by Conan-Kudo** [comment]
CMake itself uses it, and when I first learned C++, I used it for my stuff too. 😅

**Comment by Conan-Kudo** [comment]
You can also use `.c++`/`.h++` if you're feeling bold... 😛 

All the valid extension types are listed [on the Wikipedia page for the language](https://en.wikipedia.org/wiki/C%2B%2B).

**Comment by dmnks** [comment]
I'm also more accustomed to seeing `.cpp/.hpp` but Neal's point about the `CXXFLAGS` is valid. Also, it seems like `.cxx/.hxx` is ever so slightly more common (historically) on UNIX whereas `.cpp/.hpp` on Windows (based on a quick search on the interwebz). I also kinda like the more minimalistic `.cc/.hh` or even `.C/.H` :smile: 

That said, `.c++/.h++` rubs me the wrong way for some reason :sweat_smile:

**Comment by Conan-Kudo** [comment]
I'm not a fan of `.cc`/`.hh` simply because it looks like it's associated with the traditional UNIX C compiler binary `cc`.

**Comment by dmnks** [comment]
Oh, I've just realized that the `xx` is actually the slanted `++` :smile: I see what they did there.

**Comment by dmnks** [comment]
> I'm not a fan of `.cc`/`.hh` simply because it looks like it's associated with the traditional UNIX C compiler binary `cc`.

Oh, yup. It's also just two characters and somehow that feels wrong. Like, how many file extensions are there with only two characters...

> And case sensitive extensions are evil. No. 😭

Yeah, that was mostly a joke, please don't choose those :smile:

**Comment by Conan-Kudo** [comment]
Also note that C++ modules will use `.ixx`, and if we ever get around to using them for an RPM C++ API interface (in some indeterminate time in the future), it would be nice if everything lined up for it.

**Comment by pmatilai** [comment]
> Also note that C++ modules will use .ixx

Where is that stated? Based on quick googling around, .ixx seems to be a Visual Studio specific extension. Both gcc and clang have/accept their own litanies (.cppm, .ccm, .cxxm, .c++m and whatnot) :zany_face:

**Comment by Conan-Kudo** [comment]
Oh geez, okay whatever, strike that as a reason. 😵 

Still, I stand by my original rationale for cxx/hxx.

**Comment by pmatilai** [comment]
Yup, cxx/hxx has the significant benefit that it's the only version with some actual, concrete rationale to back it :laughing: 

I was a little surprised to see the core guidelines recommending .cpp and .h. .cpp is common enough not to raise eyebrows, but .h? Why on earth would one NOT want to differentiate from plain C headers?

**Comment by Conan-Kudo** [comment]
It's somewhat rare these days to have mixed C/C++ headers in a single project, so I can see why they say that. That doesn't mean I agree with it. 😃

**Comment by dmnks** [comment]
> Why on earth would one NOT want to differentiate from plain C headers?

Isn't that to have a single header file for both C and C++ usage, assuming that you'd wrap the C++ only bits with `__cplusplus`?

**Comment by pmatilai** [comment]
> cxx/hxx has the significant benefit that it's the only version with some actual, concrete rationale to back it

Once you put it down this way... it'd seem foolish to do anything else really. So .cxx and .hxx it is. Thanks for the input!
Note that .hxx for *C++ only* headers - so at this point nothing in include/rpm will change.

**Comment by dmnks** [comment]
> We have a specific reason to not mix the headers: we don't want to make our C++ API public anytime soon. Having C++ in separate headers also helps editors do syntax highlighting and the like.

Indeed, if it quacks, it's a duck. No point in pretending otherwise :smile:

**Comment by pmatilai** [comment]
Added an AC to the description - lets try to get that habbit rolling too :smile:

**Comment by Conan-Kudo** [comment]
> > cxx/hxx has the significant benefit that it's the only version with some actual, concrete rationale to back it
> 
> Once you put it down this way... it'd seem foolish to do anything else really. So `.cxx` and `.hxx` it is. Thanks for the input! Note that .hxx for _C++ only_ headers - so at this point nothing in include/rpm will change.

Makes sense to me! Let's do it!

**Comment by pmatilai** [comment]
I'm in the middle of doing this, and seeing all these exes in practise... its just SO EYE-BLEEDING UGLY that I cannot imagine living with this from here on:

```
        manifest.cxx manifest.hxx package.cxx
        poptALL.cxx poptI.cxx poptQV.cxx psm.cxx query.cxx
        rpmal.cxx rpmal.hxx rpmchecksig.cxx rpmds.cxx rpmds_internal.hxx
        rpmfi.cxx rpmfi_internal.hxx
        rpmgi.hxx rpmgi.cxx rpminstall.cxx rpmts_internal.hxx
        rpmlead.cxx rpmlead.hxx rpmps.cxx rpmprob.cxx rpmrc.cxx
        rpmte.cxx rpmte_internal.hxx rpmts.cxx rpmfs.hxx rpmfs.cxx
```

**Comment by pmatilai** [comment]
Making you all cross-eyed is one thing, but those exes actually obscure relevant information: whether a file is a header or a source gets all but lost in there.

**Comment by pmatilai** [comment]
For a side-by-side comparison of the same thing:

```
fprint.cxx fprint.hxx tagname.cxx rpmtd.cxx tagtbl.inc
cpio.cxx cpio.hxx depends.cxx order.cxx formats.cxx tagexts.cxx fsm.cxx fsm.hxx
```

```
fprint.cpp fprint.hpp tagname.cpp rpmtd.cpp tagtbl.inc
cpio.cpp cpio.hpp depends.cpp order.cpp formats.cpp tagexts.cpp fsm.cpp fsm.hpp
```

```
fprint.cc fprint.hh tagname.cc rpmtd.cc tagtbl.inc
cpio.cc cpio.hh depends.cc order.cc formats.cc tagexts.cc fsm.cc fsm.hh
```

Those of us who work on this on daily basis need to think of their health, both mental and physical. There's just no comparison between those three, we'll take the last one and run with it. It's actually a pretty common choice - for example gcc uses .cc/.hh.

**Comment by dmnks** [comment]
Truly, we've needed to see this from another perspective to notice. Nothing wrong with adapting plans accordingly.

**Comment by pmatilai** [comment]
And nothing in this world prepared me for the onslaught of those exes in the masses. It's just a wall of blur in practise.
