### ISSUE TITLE
Random failures from "rpmsign --addsign sequoia" tests

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3317]
Seeing random failures from the newly adde "rpmsign --addsign sequoia" tests, it always passes for me locally but in CI it sometimes fails with:

```
stderr:
error: unexpected argument '-o' found

  tip: to pass '-o' as a value, use '-- -o'

Usage: sq sign [OPTIONS] [FILE]

For more information, try '--help'.
error: /usr/bin/sq exec failed (2)
```

Eg here: https://github.com/rpm-software-management/rpm/actions/runs/10955725509/job/30420223350

If you encounter, just try rebuilding. We'll look at it as soon as we can.

**Comment by pmatilai** [comment]
Okay so this turns out to be a difference between sequoia-sq versions: on the failing runs it's sequoia-sq 0.38 and on successful runs 0.37, this is a very recent update supplied to Fedora.

Seems that whether intentionally or not, sequoia-sq 0.38 dropped support for -o option in sign, and that breaks our usage unfortunately. @nwalfield any idea if this was intentional?

**Comment by pmatilai** [comment]
Oh, actually, it's not just -o, it's *all* short options that have gotten axed there. So we can work around this easily enough by switching to --output.

**Comment by nwalfield** [comment]
sq's API is not yet stable. The good news is that we're going to release 1.0 by the end of the year and then we'll maintain a stable API. Until then, we are polishing the CLI and will likely break something else. Sorry in advance!

**Comment by pmatilai** [comment]
Ack, thanks for the clarification. We can live with short-term instability especially when we know it's coming.
The timing on this was quite something, the -o usage only landed in git master just last week or so :smile:
