### ISSUE TITLE
Problem with --signfiles for files that are hardlinked together

### ISSUE THREAD

**Issue by patrickc25000** [rpm-software-management/rpm#333]
We have encountered a problem when performing an RPM update while Integrity Measurement Architecture (IMA) signatures are applied to the files. In other words, we are having a problem with the "--signfiles" support in the RPM package.

When we install a new glibc RPM on a system with SELinux and IMA enabled, we are seeing appraise errors with 3 files. Looking at an strace (see attached), I see that the files are referenced different from the normal sequence (i.e. of open, lsetxattr of security.ima, lsetxattr of security.selinux, rename) and instead, there is a hard link call made before the open. Taking just one of these files that results in an appraise error, namely /usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8, and looking for references to it and some related files (i.e. /usr/libexec/getconf/POSIX_V6_LP64_OFF64;59d3a6c8 and /usr/libexec/getconf/POSIX_V7_LP64_OFF64), I see the following summary: 

Create POSIX_V6 temp file and rename as POSIX_V6 regular file and hard link POSIX_V7 temp file to POSIX_V6 regular file and rename POSIX_V7 temp file as POSIX_V7 regular file and hard link XBS5 temp file to POSIX_V6 regular file and open XBS5 temp file and then set security.ima on the XBS5 temp file. Since the set of security.ima is done after the open and the open will not be creating a file since it has a hard link to an existing file at that point, the open will encounter an appraise error (in this strace, just resulting in a log entry) since the security.ima signature will not be found.

Below are the relevant entries within the strace to support the problem summary above: 

write(2, "create     100755  3 (   0,   0)"..., 89create     100755  3 (   0,   0)     0 /usr/libexec/getconf/POSIX_V6_LP64_OFF64;59d3a6c8
open("/usr/libexec/getconf/POSIX_V6_LP64_OFF64;59d3a6c8", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 30
lstat("/usr/libexec/getconf/POSIX_V6_LP64_OFF64", {st_mode=S_IFREG|0755, st_size=26648, ...}) = 0
lstat("/usr/libexec/getconf/POSIX_V6_LP64_OFF64", {st_mode=S_IFREG|0755, st_size=26648, ...}) = 0
removexattr("/usr/libexec/getconf/POSIX_V6_LP64_OFF64", "security.capability") = -1 ENODATA (No data available)
rename("/usr/libexec/getconf/POSIX_V6_LP64_OFF64;59d3a6c8", "/usr/libexec/getconf/POSIX_V6_LP64_OFF64") = 0
write(2, "create     100755  3 (   0,   0)"..., 89create     100755  3 (   0,   0)     0 /usr/libexec/getconf/POSIX_V7_LP64_OFF64;59d3a6c8
link("/usr/libexec/getconf/POSIX_V6_LP64_OFF64", "/usr/libexec/getconf/POSIX_V7_LP64_OFF64;59d3a6c8") = 0
lstat("/usr/libexec/getconf/POSIX_V7_LP64_OFF64", {st_mode=S_IFREG|0755, st_size=26648, ...}) = 0
lstat("/usr/libexec/getconf/POSIX_V7_LP64_OFF64", {st_mode=S_IFREG|0755, st_size=26648, ...}) = 0
removexattr("/usr/libexec/getconf/POSIX_V7_LP64_OFF64", "security.capability") = -1 ENODATA (No data available)
rename("/usr/libexec/getconf/POSIX_V7_LP64_OFF64;59d3a6c8", "/usr/libexec/getconf/POSIX_V7_LP64_OFF64") = 0
write(2, "create     100755  3 (   0,   0)"..., 85create     100755  3 (   0,   0) 26648 /usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8
link("/usr/libexec/getconf/POSIX_V6_LP64_OFF64", "/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8") = 0
open("/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 30
chown("/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8", 0, 0) = 0
chmod("/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8", 0755) = 0
utimensat(AT_FDCWD, "/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8", {{1506436625, 0}, (1506436625, 0}}, AT_SYMLINK_NOFOLLOW) = 0
lsetxattr("/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8", "security.ima", "...", 265, 0) = 0
lsetxattr("/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8", "security.selinux", "system_u:object_r:bin_t:s0", 27, 0) = 0
write(2, "lsetfilecon: (/usr/libexec/getco"..., 90lsetfilecon: (/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8, system_u:object_r:bin_t:s0)
lstat("/usr/libexec/getconf/XBS5_LP64_OFF64", {st_mode=S_IFREG|0755, st_size=26648, ...}) = 0
lstat("/usr/libexec/getconf/XBS5_LP64_OFF64", {st_mode=S_IFREG|0755, st_size=26648, ...}) = 0
removexattr("/usr/libexec/getconf/XBS5_LP64_OFF64", "security.capability") = -1 ENODATA (No data available)
rename("/usr/libexec/getconf/XBS5_LP64_OFF64;59d3a6c8", "/usr/libexec/getconf/XBS5_LP64_OFF64") = 0

As you can see in the sequence above, an open of an existing file (because it is a hard link) is made before the lsetxattr call to add the IMA signature and this is the problem. Note, although the open of the existing file is performed with the O_TRUNC option, by design, the IMA support in the kernel appraises the file (i.e. validates the signature) before the truncation of the file.

**Comment by Conan-Kudo** [comment]
@patrickc25000 What version of RPM are you encountering this? And what distribution?

**Comment by pmatilai** [comment]
I can see how hardlinks could be a problem (because they *are* quite different from everything else) but... you're saying the reason IMA appraisal fails is that the file was changed after its creation, right? And not for example because the file has a number of hardlinks already?

Anyway, the way rpm does hardlinks right now is problematic in more ways than just this one and changing it to behave more sensibly (create the file with the content first like any other file, and only then create the hardlinks) will fix this too. So this is just all the more reason to change it...

**Comment by patrickc25000** [comment]
Conan-Kudo,
The problem can be seen in version 4.13.0-6 from the Redhat Enterprise Linux 7 distribution.

**Comment by stefanberger** [comment]
@pmatilai Is the problem limited to the fsmMkfile() function? I suppose this is where the hard links are created. Would the solution be to do things in a different order in that function ?

**Comment by stefanberger** [comment]
@pmatilai Is there a  reason that in case of hard links the file gets written only after all the hard links have been created? It looks a bit complicated ...

**Comment by stefanberger** [comment]
The problem seems to be that only the last entry has the file content... so the empty file that's created first cannot be written since the RPM entry currently being processed doesn't have the data. Then a couple of hard links may get created and only the last entry (hardlink) found there has the content that can then be written out.

**Comment by stefanberger** [comment]
@patrickc25000 I will have to patch the rpm package you are using with these patches and have you test it...

**Comment by pmatilai** [comment]
Merged #342 which should resolve this in a way that can be backported to stable branches too, thanks @stefanberger !

We'll still want to eventually change the order of things to create the hardlinks last but that's less urgent with this.

**Comment by stefanberger** [comment]
@pmatilai Would it be possible to have these 4 patches applied to the latest rpm built for Fedora 26 and later?

**Comment by pmatilai** [comment]
Fedora 27 will get this fix once updated to rpm 4.14.1 (should be within next few weeks), and I guess I'll need to do another bugfix release for 4.13.x soonish too so that'd be the route into Fedora.
