### ISSUE TITLE
Redo lib/package.c stashKeyid() and rpmsinfo_s.keyid to use long KeyId

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#3333]
### AC:

* The "seen keyid" tracking uses long KeyIDs

**Comment by pmatilai** [comment]
I split the dynamic storage part off to #3336, it's out of scope for the "don't use short keyids for anything" task (which is why I called it no-priority item). AC acked.

**Comment by ffesti** [comment]
One way to solve both at the same time would be adding `rpmtsLogOnce()` or something similar that would solve the general problem of omitting (or downgrading) log messages after the first one. There are several more use cases for such an mechanism. There is nothing special about this case here.

**Comment by pmatilai** [comment]
Let's just do the obvious minimal change for this now: changing this to use the full keyid hex string is less than 10 lines of code, and lets us tick one off another short keyid ticket off the list, we're quite near to be able to close that chapter already. We can ponder more creative solutions once later.

**Comment by pmatilai** [comment]
I can submit a PR for this if you like.

**Comment by ffesti** [comment]
Nah, I'll be able to hack that 2 loc myself.

**Comment by pmatilai** [comment]
No question about that, but I basically already have that here as a side-effect of poking at stuff.

**Comment by ffesti** [comment]
Sure, then just commit and push.
