### ISSUE TITLE
keyring only allows unique key IDs

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#3334]
Key IDs (even long ones) can have collisions - especially when an attacker tries to generate them on purpose. The right behavior is to try all keys with matching key IDs and see if one is able to verify the signature.

**Comment by ffesti** [comment]
AC:

* rpmKeyring can store multiple keys with the same key ID
* The verification code loops over the keys and ignores the ones not actually matching the signature

**Comment by nwalfield** [comment]
For some test data, see https://github.com/skeeto/pgpcollider

**Comment by pmatilai** [comment]
> The verification code loops over the keys and ignores the ones not actually matching the signature

This is a bit vague. In a case where one key eventually matches, that's obvious. But what about failure? If there's no matching keyid at all, that'd be NOKEY as now, but if there are multiple yet nothing actually matches then we only get a FAIL I guess.

**Comment by ffesti** [comment]
Yes, the code loops over all they and stops if one verifies the signature. If none does we just use the last one (random key) to produce the error messages. This is less than ideal as the messages for the other key(s) could be more meaningful. But the return codes of pgpVerifySignature() don't seem very helpful in making a better decision.

Also having a failure of a signature with multiple candidates that all fail seems like a very rare occasion and I might be fine with the error message being correct enough.

**Comment by ffesti** [comment]
Toying around with the test cases I wonder if the opposite is actually what we want. If there are only keys that do not actually match you'd want to issue a NOKEY response. But for that we'd need to actually understand which key is the matching one - if any.

We do get an meaningful error message from the back end if signature and pubkey don't match up though.

**Comment by pmatilai** [comment]
If we can differentiate between NOKEY and FAIL in the case of multiple keyid matches then of course that's what we should do. It wasn't clear to me that we could.

**Comment by pmatilai** [comment]
So ideally:
- ok is OK
- no matching keyids at all is NOKEY
- matching keyids but wrong key is NOKEY
- broken signature is FAIL

**Comment by ffesti** [comment]
OK, may be I should have worded this better. We get a meaningful human readable message from the backend. But not a meaningful return code. So while the user is getting the right idea what the issue might be I don't think we want to parse that message to figure out whether the pubkey is matching.

**Comment by pmatilai** [comment]
Right - looking at the testcases:
> Certificate 42655A75156B3DE0 does not contain key 94706F8DA571389E8642BDFD42655A75156B3DE0 or it is not valid

Says right there, the backend doesn't know FAIL/NOKEY either because, like I assumed, it's not possible to differentiate the two. So scratch the "ideally" above, this is just a FAIL but the Sequoia error message makes it clear it can be one of the two things.

**Comment by pmatilai** [comment]
And, I still think we should output those errors for each key we tried in case nothing matched.

**Comment by pmatilai** [comment]
So basically I think the AC would be:
- no matching keyids at all returns NOKEY
- all matching keyids are tried
  - a positive verification returns OK 
  - otherwise output errors for all keys we tried with, return FAIL

**Comment by ffesti** [comment]
OK, the code does that now. Don't have a test case with more than one failing key yet. Guess we could arrange that by damaging the signature. Having 3 keys sharing a key ID does not seem like a realistic thing to get in our life time.

**Comment by pmatilai** [comment]
Ack. Maybe somebody will one day lend us a bit of compute time on their quantum computer to produce a multi-keyid testcase :sweat_smile:
