### ISSUE TITLE
Unknown keyid warning is tied to process lifetime

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3336]
rpmReadPackageFile() logs a warning on the first encounter of an unknown key id. The "seen keyid?" is currently tied to process lifetime, but that's not entirely right: while many tools in the stack like rpm itself, dnf etc only ever perform one transaction in a process, this should be tracked on per transaction/keyring level: a shell- or daemon like process can run multiple transactions to multiple chroots, and technically the warning should reoccur for each, unless they use a common keyring. Which suggests keyring is the right place to hook this. This is a low priority item.

**Comment by ffesti** [comment]
Looks like `rpmKeyringVerifySig*` could easily deal with this. Unfortunately there isn't a good way to return the information. Sure we could add something like RPMRC_NOKEY_REPEATED and RPMRC_NOTTRUSTED_REPEATED as a return value. But that breaks the API for users being unaware and requires fixing our own callers to take these values into account. There are about half a dozen places so it is not that difficult to do, but I wonder if this is just too much of an disruption.

The alternative would be adding something like stashKeyId to the keyring - probably with a better name.
