### ISSUE TITLE
Implement an abstact keystore API

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3342]
The support for rpmdb and fs keystores are currently buried in lib/rpmts.c special case code, for historical reasons.
We should add a proper keystore API that supports import, delete and read operations on different backends of choice, and move the relevant parts of the existing code there.

**Comment by ffesti** [comment]
Needs to account for #3338, #3339, #3340, #3347

**Comment by pmatilai** [comment]
AC proposal (or what I have in mind here anyhow):
- the keystore is a new abstract class
- the keystore implements three methods: load, import and delete:
  - rpmRC keystore:Load(rpmtxn txn, rpmKeyring keyring)
  - rpmRC keystore:Import(rpmtxn txn, rpmPubkey key)
  - rpmRC keystore:Delete(rpmtxn txn, rpmPubkey key)
- existing rpmdb and fs keystores are ported to the this class

**Comment by pmatilai** [comment]
...which is pretty close to what we already have, but having it in a self-sufficient class instead of integer to hold the type should allow for "rebuild" type operation as well.

It's also super minimal, we'll probably want an iterator for the contents later but as this is an internal-only API it can evolve more freely.

**Comment by pmatilai** [comment]
Except that the method names are a disaster :laughing: because 2/3 conflict with C++ keywords and "load" is just as generic so you never know. Changing these to
- load_keys
- import_key
- delete_key
