### ISSUE TITLE
Refuse to create transaction elements from headers with no RPMTAG_ARCH

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3344]
gpg-pubkey pseudo-packages are a special case that (intentionally) lack the ARCH tag. This allegedly differentiates them from real packages and kinda implies they can only appear through rpmtsImportHeader(), but actually the special casing in rpmte.c lets anybody create a package with RPMTAG_ARCH stripped and install it.

**Comment by pmatilai** [comment]
This ticket was filed while were planning to entirely eliminate the rpmdb keystore from 6.0 already, but since that changed...

Just dropping the conditional as the PR does will also prevent people from uninstalling pre-existing gpg-pubkey packages via traditional means. I'm not sure what to think about that - on one hand it seems okay because you can't install them through the regular means either, but it'll break all manner of documentation and usages if that's the case.

**Comment by ffesti** [comment]
There are basically two options here:

Either still allow erasing only. This should probably give a warning pointing people to rpmkeys.

Or just don't allow this but give a meaningful error message pointing people to rpmkeys. This will also require adjusting documentation for RPM v6.

**Comment by ffesti** [comment]
Guess we should adjust the documentation no matter what.

**Comment by pmatilai** [comment]
Our own documentation should be up to date, there are zero references to gpg-pubkey in the manuals since bd907b0c50d0d25c00d76f5aac6d548456fad4f21Gq, the problem is all the other docs and "recipes" out there on the net.

So maybe we should allow erase, but warn with a message pointing at rpmkeys --delete.

**Comment by pmatilai** [comment]
Outright refusing is tempting, but maybe it's too abrupt a change... so yeah, lets go with the warning.

**Comment by pmatilai** [comment]
So basically the AC is:
- creating rpmte's without arch or os fails
- except that removing gpg-pubkey packages succeeds but produces a warning message, pointing uses to rpmkeys --delete instead

**Comment by pmatilai** [comment]
Ehm, to summarize discussion from chat. There are actually two different sides to this:
- all *packages* should have arch and os, and trying to install packages without them should fail
- gpg-pubkey headers in the rpmdb are *not packages*, should not have arch or os tags, and it shouldn't be possible to install them via the transaction machinery. Removing too should go through the keystore, but for a transition period I we should allow 'rpm -e gpg-pubkey'.
