### ISSUE TITLE
rpmKeyringAddKey() should add subkeys too

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3350]
Subkey support was added as a bit of an afterthought, and one of the ways is shows is callers are expected to deal with subkeys manually. This makes no sense, rpmKeyringAddKey() should just add all the subkeys along with its subkeys.

**Comment by ffesti** [comment]
AC:

* rpmKeyringModify handles subkeys in all modes (RPMKEYRING_ADD, RPMKEYRING_DELETE, RPMKEYRING_REPLACE). User don't need to pass subkeys at all.
* All code passing subkeys to the keyring thoughout the code base is adjusted to only pass the primary key.

**Comment by ffesti** [comment]
OK; this turns out to be much more complicated as it looks at first glance. Linking the the primary and subkeys together creates reference loops that prevent them ever to get freed. Locking gets in the way of fixing this easily. nrefs need to move out of the normal locks and be implemented as std::atomic instead before this can go anywhere.

**Comment by pmatilai** [comment]
The refcounting locks are indeed broken there, always were. The main mutex is for the contents, refcounting is a different matter. We could probably just toss the nref locks out of the airlock and nothing would break...

One of the tools in solving loops is using weak dependencies. If all the keys and their subkeys are owned by the keyring from the go, then that alone guarantees they wont vanish up in the air, and then they don't need a thousand cross-references. And, I don't think we actually need primary key->subkey links for anything, just the subkey -> primary key link we already have.  The way this is all going it seems that we should just phase out all subkey business outside the keyring/key code itself. We can support rpmGetSubkeys() as long as it's there by just looking up the subkeys based on the primary key by brute force - it's not performance critical in any way.

**Comment by ffesti** [comment]
With [Turn nrefs into atomic_int](https://github.com/rpm-software-management/rpm/pull/3370) merged this can get another try.

**Comment by ffesti** [comment]
OK, last time around I ran into trouble when trying to attach the sub keys to the primary keys. But as nothing seems to use the subkeys outside of the keyring there isn't really a good reason to do so. So I am currently just adding (and removing) the subkeys from the keyring without changing anything else in the data structures.
