### ISSUE TITLE
RFE: add rpmkeys --export for exporting the ASCII armored key material

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3366]
Sprung from the discussion in #3332:

gpg-pubkey packages have the key ASCII armor in description, but going forward we'll need some other means of access.
rpmkeys --export seems like a obvious place to put this functionality.

### AC:
 - Add rpmkeys --export [FINGERPRINT ...]
 - Outputs the ASCII armored keys to stdout

**Comment by ffesti** [comment]
OK, adding this to `rpmkeys` is rather easy now that we have `matchingKeys` in place. One issue that goes beyond this ticket is the disconnect between rpmkeyring.h and rpmPubkey on one side and rpmpgp.h on the other. The later works either on pgpDigParams - which rpmPubkey can return - or the raw packet data and length. The later is stored in the rpmPubkey object of the primary keys but is not exported. SO the question is do we add a function to retrieve the blob or do we basically attach the functions in rpmpgp.h to the rpmPubkey data structure?

**Comment by ffesti** [comment]
For the record: There is currently a way to do this with the current API by getting `rpmPubkeyBase64` and then decoding it again. But this is rather silly.

**Comment by ffesti** [comment]
AC:

* Add `rpmkeys --export [FINGERPRINT ...]`
* Outputs the ASCII armored keys to stdout

**Comment by pmatilai** [comment]
> SO the question is do we add a function to retrieve the blob or do we basically attach the functions in rpmpgp.h to the rpmPubkey data structure?

Add higher level accessor functions to the rpmPubkey, for the stuff that we absolutely have to have, UserID being one such obvious thing. But lets not add stuff just because there happens to be a pgp-level thing now, that low-level stuff is largely just historical happenstance.
