### ISSUE TITLE
rpmkeys --list and --delete must work for unloadable keys

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3375]
Given how fast crypto stuff becomes obsolete and even inaccessible these days, a key imported today might not be loadable at all in a few years. There needs to be a way to get rid of such keys without resorting to 'rm -rf' tactics, and to be deletable they need to be listable. For rpmdb keystore, the gpg-pubkey headers can be alternatively removed through the transaction API, thus side-skirting the issue, but that's not really a sane design.

So rpmkeys needs to have means to list the underlying keystore contents (presumably by fingerprint) without even trying to load them, and it needs to be able to delete a key found this way. And of course to do that it'll need corresponding APIs in librpm.

**Comment by pmatilai** [comment]
By load I basically mean rpmPubkeyNew() and all that it ends up checking.

I don't have a detailed plan for this, but I'd expect a keystore to be able to locate the contained signature blobs by a fingerprint, whether they're just files on disk or something fancier.

**Comment by pmatilai** [comment]
Actually, it might well be enough just to provide a switch to purge the keystore entirely.
The contents in an rpm keystore are of low value, you can always reimport the bits you need, so nuking isn't such a horrible thing. But it needs to be an rpm provided primitive, not people 'rm -rf'ing around stuff. We got allergic of *that* during the Berkeley DB days :confounded:

**Comment by ffesti** [comment]
Or just drop all key that you can't load.

**Comment by pmatilai** [comment]
Yeah, I just realized (afk) that I'm full of shit on this one :laughing: 

The *user story* is that there needs to be a way to purge keys that don't load for whatever reason, the problem with this ticket is the overly technical description that is going into the weeds. A nicely rpm'ish way to achieve this is a "rebuild" of the keystore, which we basically need for #3347 anyhow. I'll note this as a case in that ticket instead.
