### ISSUE TITLE
rpmbuild -bs leaves an unnecessary name-version-build directory behind

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3382]
Reported by @decathorpe in https://github.com/rpm-software-management/rpm/discussions/3381:

Running `rpmbuild -bs <spec>` leaves behind an empty name-version-build directory. If we need to create the dir, we should at least clean up afterwards (and cleaning up might be easier than trying to avoid creating)

**Comment by voxik** [comment]
To me, this might be [`fedpkg` thing](https://bugzilla.redhat.com/show_bug.cgi?id=2293671), but I won't mind if this is going to be fixed on RPM side.

**Comment by decathorpe** [comment]
`fedpkg srpm` just does call `rpmbuild -bs` (with some additional --defines) under the hood, though? So I don't think this can entirely be "fixed" in fedpkg (and adding a workaround there won't fix uses of plain `rpmbuild -bs`).

**Comment by pmatilai** [comment]
It's not a fedpkg thing, it's just that in the "traditional" ~/rpmbuild/{SPECS,BUILD,...} layout the directory gets created out of sigh, whereas fedpkg overrides all those to the current directory.

It's a bug in rpmbuild. No need to speculate. There are ... somewhere over a hundred different combinations this stuff be invoked, and this one got overlooked.

**Comment by pmatilai** [comment]
And what a bug it was! Not the proudest day of my career :laughing: 

Thanks a lot for reporting @decathorpe !

**Comment by decathorpe** [comment]
eh, we've all forgot to add `break` in switch statements before, I think :) thank you for tracking it down!

**Comment by voxik** [comment]
I hope this will get backported into 4.20.

**Comment by pmatilai** [comment]
Of course.
