### ISSUE TITLE
Default to test-suite disabled in release tarballs?

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm#3388]
To compile RPM from source, one shouldn't need any development tools installed. Right now, we default to the test-suite being enabled and thus requiring Podman or Docker to be installed during cmake configuration.

This is easily disabled with `-DENABLE_TESTSUITE=OFF` of course (and is even documented as such in [INSTALL](https://github.com/rpm-software-management/rpm/blob/master/INSTALL)) but it's probably just an unnecessary road [bump](https://github.com/rpm-software-management/rpm/discussions/3387).

Alternatively, we could default to `OFF` entirely (not just in release tarballs).

**Comment by dmnks** [comment]
As for how a different cmake default configuration in release tarballs would be achieved (without having to carry forward a patch on the stable branches forever), I'm not sure, but it should be possible.

**Comment by pmatilai** [comment]
Right, just disable to OFF by default. The current container-based form isn't something you casually run as unit tests at the end of build.

**Comment by pmatilai** [comment]
(that's another topic: we should really have unit tests too and not just these integration tests, but that's another topic :sweat_smile: )

**Comment by dmnks** [comment]
> Right, just disable by default everywhere. The current container-based form isn't something you casually run as unit tests at the end of build.

Yup, agreed. That said, this would mean you'd need to supply `-DENABLE_TESTSUITE=ON` every time you (re)create a `_build` directory. For me, it'd be the only cmake option, actually. So I wonder how annoying it'd get over time...

**Comment by dmnks** [comment]
OK then, it's perhaps not as common of a use case to rely on the defaults then :smile:

**Comment by dmnks** [comment]
I'll probably add a short note to the Discussions so that people aren't surprised when the `make check` target suddenly doesn't exist :sweat_smile:

**Comment by dmnks** [comment]
Lol. Among the first people being really surprised about missing make targets is our very own CI :smile: I forgot to update *that*.
