### ISSUE TITLE
error in the docs (at rpm.org): exclamation mark is missing

### ISSUE THREAD

**Issue by imz** [rpm-software-management/rpm#339]
When reading <http://rpm.org/user_doc/macros.html>, an exclamation mark is missing:

    There are also provisions for including text if flag was present using “%{-f:X}”. This macro expands to (the expansion of) X if the flag was present. The negative form, “%{-f:Y}”, expanding to (the expansion of) Y if -f was not present, is also supported.

whereas <http://ftp.rpm.org/api/4.4.2.2/macros.html> is correct at this place:

    There are also provisions for including text if flag was present using "%{-f:X}". This macro expands to (the expansion of) X if the flag was present. The negative form, "%{!-f:Y}", expanding to (the expansion of) Y if -f was *not* present, is also supported.

**Comment by pmatilai** [comment]
Fixed now, thanks for reporting.

In the future, please report website issues to the website tracker instead:
https://github.com/rpm-software-management/rpm-web/issues

**Comment by imz** [comment]
Thanks! Fixed with <https://github.com/rpm-software-management/rpm-web/commit/cd2596d9e1ee216af7d5df13065bce645bc5fcce#diff-c323ef9ffdb92d6d5e0c5b5d607aecf6>
