### ISSUE TITLE
error: Failed to initialize NSS library

### ISSUE THREAD

**Issue by zoujiaqing** [rpm-software-management/rpm#340]
```bash
root@freebsd:~ # /usr/local/rpm/bin/rpmbuild -bb curl.spec
error: Failed to initialize NSS library
```

I install rpm in my FreeBSD 11.1 from source code.
rpm version:
```bash
root@freebsd:~ # /usr/local/rpm/bin/rpmbuild --version
RPM version 4.13.0.1
```

other package version:
```bash
nspr-4.17.0
nss-3.33
db-5.3.28
lua-5.3.4
```

**Comment by pmatilai** [comment]
It's not an rpm bug. As the error message says, NSS initialization is failing and that's what you need to fix. NSS is "special" in that it's not enough to just link to it, some of the critical pieces are dlopen()'ed and not finding its components is a likely reason for failure. strace it to get more clues.

**Comment by zoujiaqing** [comment]
谢谢

**Comment by Conan-Kudo** [comment]
@zoujiaqing If you want to avoid that issue, you can try using beecrypt crypto backend instead of NSS.
