### ISSUE TITLE
RFE: add support for SHA-3

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#3436]
The [post-quantum signatures](https://github.com/openpgp-pqc/draft-openpgp-pqc/blob/main/draft-ietf-openpgp-pqc.md) are all SHA-3 based, rpm needs to recognize them. As the actual crypto comes from rpm-sequoia or rpmpgp_legacy, the rpm side of this is little more than adding a couple of enums but it still needs to be done.

Besides PQ signatures, we'll want to be able to move to stronger digest for our own purposes too, sooner or later.

**Comment by pmatilai** [comment]
AFAICS SHA-3 in rpm-sequoia depends on the [crypto-refresh](https://gitlab.com/sequoia-pgp/sequoia/-/tree/crypto-refresh) branch to land in main Sequoia first.

**Comment by nwalfield** [comment]
That's correct.  We plan to add support for 9580 to sequoia-openpgp 2.0, which is due out early next year.  Note: 2.0 will not include support for PQC, because it is not yet standardized.

**Comment by pmatilai** [comment]
Nothing in rpm v6 depends on SHA-3 so this isn't critical for us, it's more of a "HDTV-ready" type of thing :smile:
