### ISSUE TITLE
RFE: Macronized opts for parmaetric macros (i.e. %foo(%{myopts}) ...)

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#3440]
**Describe the bug**

I'd like to reuse a set of options between several macros.

```
%_options abc
%foo(%{_options}) ...
%bar(%{_options}) ...
%baz(%{_options}) ...
```

Unfortunately, this is not possible with RPM 4.20 or lower. The string is taken literally. Using `%{expand:%{_options}}` makes no difference -- it just defines options for `-e`, `-x`, `-p`...

Similarly, if I use an expression within, all charracters of that expression are taken as literal values (e.g. `foo(%[1 ? "abc" : "def"])` allows all of `-abcdef` but also e.g. `-?`, `-[` or `-"` as option.

**To Reproduce**

```
$ rpm --define '_options abc' --define 'foo(%{_options}) ...' --eval '%foo -a' --eval '%foo -o'
```

**Expected behavior**

```
foo: invalid option -- 'o'
error: Unknown option a in foo(abc)
```

**Output (actual behavior)**

```
foo: invalid option -- 'a'
error: Unknown option a in foo(%{_options})
```

**Environment**
 - OS / Distribution: Fedora 41 or older
 - Version rpm-4.20.0-1.fc41 or older

**Comment by pmatilai** [comment]
Sorry but no, that gets too weird and unpredictable. If you want to avoid manual repetition, maybe generate the macro file from a template or something.
