### ISSUE TITLE
systemd 257 defines a new modifier ! for u entries

### ISSUE THREAD

**Issue by keszybz** [rpm-software-management/rpm#3450]
https://github.com/systemd/systemd/commit/2ec7977e1b100c1717d95417e6d825fbf939f7b3 defines `u!`, and https://github.com/systemd/systemd/commit/a4c0528f14 adds it to all `u` lines used by systemd. 

I'll revert this change in systemd config to do the build, but inevitably other projects are going to start using this. Rpm needs to be adjusted to support this.

**Comment by pmatilai** [comment]
Ack, thanks for the heads-up.
