### ISSUE TITLE
rpm -qi curl  core file generation with low root partition space

### ISSUE THREAD

**Issue by jinwanqiashaokao** [rpm-software-management/rpm#3451]
**Describe the bug**
When the root partition has very little space remaining, executing the command rpm -qi curl generates a core file like core-rpm-2958434-1731736615. The reason for this behavior is not clear. It is suspected that the limited space on the root partition may cause issues with memory allocation, file system I/O, or dependencies.

**To Reproduce**
1. When the root partition has very little space remaining
2. rpm -qi 

Please link or attach the packages or spec files involved.

**Expected behavior**
Prompts for insufficient space

**Output**
If applicable, add copy of the output on the command line or a screenshots to help explain your problem.

**Environment**
 - OS / Distribution: centos 8
 - Version rpm-4.14.3-24.0.1

**Additional context**

**Comment by pmatilai** [comment]
It's failing somewhere inside Berkeley DB.

Rpm 4.14 is years out of upstream support by now, and upstream doesn't even support Berkeley DB based rpmdb anymore. And, the BDB in Centos is well over a decade out of their upstream support. 

Supporting that is up to the individual distros, rpm.org upstream cannot help.
