### ISSUE TITLE
rpm 4.20 triggers a dac_read_search capability request

### ISSUE THREAD

**Issue by zpytela** [rpm-software-management/rpm#3468]
**Describe the bug**
sudo rpm --rebuilddb
executed by a non-root user finishes successfully, but generates AVC denials.

**To Reproduce**
$ sudo rpm --rebuilddb
$ sudo ausearch -i -m avc -ts recent

**Expected behavior**
No error and no AVC Denial.

**Output**
type=PROCTITLE msg=audit(11/25/2024 09:52:51.327:230) : proctitle=/usr/bin/rpmdb --rebuilddb 
type=PATH msg=audit(11/25/2024 09:52:51.327:230) : item=0 name=~/.config/rpm/rpmrc nametype=UNKNOWN cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(11/25/2024 09:52:51.327:230) : cwd=/home/user1 
type=SYSCALL msg=audit(11/25/2024 09:52:51.327:230) : arch=x86_64 syscall=access success=no exit=EACCES(Permission denied) a0=0x55cc5de60a70 a1=R_OK a2=0xffffffffffffff70 a3=0x40 items=1 ppid=1120 pid=1121 auid=user1 uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=pts2 ses=3 comm=rpmdb exe=/usr/bin/rpmdb subj=unconfined_u:unconfined_r:rpmdb_t:s0-s0:c0.c1023 key=(null) 
type=AVC msg=audit(11/25/2024 09:52:51.327:230) : avc:  denied  { dac_override } for  pid=1121 comm=rpmdb capability=dac_override  scontext=unconfined_u:unconfined_r:rpmdb_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:rpmdb_t:s0-s0:c0.c1023 tclass=capability permissive=0 
type=AVC msg=audit(11/25/2024 09:52:51.327:230) : avc:  denied  { dac_read_search } for  pid=1121 comm=rpmdb capability=dac_read_search  scontext=unconfined_u:unconfined_r:rpmdb_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:rpmdb_t:s0-s0:c0.c1023 tclass=capability permissive=0 

**Environment**
rpm-4.20.0-1.fc42.x86_64
Seems to be an effect of
https://github.com/rpm-software-management/rpm/issues/2153

**Additional context**
If original user's config is taken into account, denials will always be audited given that default homedir permissions are 0700.

**Comment by ffesti** [comment]
Yeah, rpm looks into your $HOME directory for rpmrc files. It has "always" done that so this is unrelated to the ticket mentioned above.

The issue here is that the environment is not set properly. This is done "on purpose" by sudo. To fix this you can use the `-H` or `-i` parameter or configure sudo to `always_set_home` or `env_reset`. See the man pages of `sudo` and `sudoers` for details.

So this is basically a usage error and there is nothing rpm can really do about it. Closing.

**Comment by dmnks** [comment]
Shouldn't `sudo` change the `$HOME` directory for the process it runs, though?

**Comment by dmnks** [comment]
This might also be just a matter of (`sudo`) configuration. @zpytela, haven't you changed that on your system?

**Comment by pmatilai** [comment]
Hmm, something here doesn't add up. Like @dmnks pointed out elsewhere, `sudo sh -c 'echo $HOME'` does return `root` without any extra switches, in so rpm should also do the right thing. And, looking at `sudo strace -o /tmp/rebuild.log rpm --rebuilddb` output, I see 

> newfstatat(AT_FDCWD, "/root/.config/rpm", 0x7ffeb3ea6200, AT_SYMLINK_NOFOLLOW) = -1 EACCES (Permission denied)
newfstatat(AT_FDCWD, "/root/.config/rpm/rpmrc", 0x7ffeb3ea6200, AT_SYMLINK_NOFOLLOW) = -1 EACCES (Permission denied)
> access("~/.config/rpm/rpmrc", R_OK)     = -1 EACCES (Permission denied)

But these are for root as you'd expect, and they also should be allowed.

**Comment by dmnks** [comment]
Yup, @ffesti actually pointed that out in his reply - this looks like a configuration issue of sudo/sudoers, where the default seems to be changed to inherit the `$HOME` and/or the environment itself, so I'd check that first.
