### ISSUE TITLE
RFE: make possible to pass multiple dirs to `_*dir` macro

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#352]
Most of the time I have to do `-D "_sourcedir $(pwd)"` and it is really annoying that I can't set _sourcedir to something like `%{_topdir}/SOURCES:%(pwd)` and RPM would search for both directories. Like a PATH, LD_LIBRARY_PATH are working.

**Comment by n3npq** [comment]
(aside)
There are ways to configure rpmbuild to do everything in the current directory. I have published my macros configure file multiple times in the past 15 years.

Adding multiple directories and a search path to existing macros like _sourcedir adds complexity for not much gain, and is quite at odds with rpm' goal of "reproducible builds" when identically named but differing files are found in multiple locations.

There are also issues unpacking *.src.rpm files: which directory to use?

**Comment by n3npq** [comment]
(aside)
There are ways to configure rpmbuild to do everything in the current directory. I have published my macros configure file multiple times in the past 15 years.

Adding multiple directories and a search path to existing macros like _sourcedir adds complexity for not much gain, and is quite at odds with rpm' goal of "reproducible builds" when identically named but differing files are found in multiple locations.

There are also issues unpacking *.src.rpm files: which directory to use?

**Comment by pmatilai** [comment]
NAK for paths, it creates more problems than it solves.

Having rpm default to a modern dist-git style layout (or a trivial one-liner way to enable it) would be more useful.
