### ISSUE TITLE
rpmidxGetInternal(): leak on realloc() failure

### ISSUE THREAD

**Issue by sourcejedi** [rpm-software-management/rpm#357]
When realloc() fails the original allocation remains, and should be freed at some point.

Can rpmidxGetInternal() be converted to xrealloc() ?  I'm unsure because there might be a deliberate reason, e.g. why we still have 130 references directly to malloc() and not xmalloc().

```
@@ -927,16 +927,14 @@ static int rpmidxGetInternal(rpmidxdb idxdb, const unsigned char *key, unsigned
 	}
 	if (keyoff != x)
 	    continue;
 	if ((nhits & 15) == 0) {
 	    if (!hits) {
-		hits = malloc(16 * sizeof(unsigned int));
+		hits = xmalloc(16 * sizeof(unsigned int));
 	    } else {
-		hits = realloc(hits, (nhits + 16) * sizeof(unsigned int));
+		hits = xrealloc(hits, (nhits + 16) * sizeof(unsigned int));
 	    }
-	    if (!hits)
-		return RPMRC_FAIL;
 	}
 	data = le2ha(ent + 4);
 	ovldata = (data & 0x80000000) ? le2ha(idxdb->slot_mapped + idxdb->nslots * 8 + 4 * h) : 0;
 	hits[nhits++] = decodedata(idxdb, data, ovldata, &datidx);
 	hits[nhits++] = datidx;
```

**Comment by pmatilai** [comment]
Not sure where you're pulling that 130 malloc() references from, certainly there aren't that many of them. I see something ~34 actual malloc() calls in the code.

The typical use of malloc()/realloc() (as opposed to rpm's wrappers) comes from code originally developed outside rpm, including ndb. Using them isn't forbidden, it's just that in case non-rpm allocators are used, they need to check for and handle errors. Which code originating outside rpm usually does, including ndb.

Sure it could be converted to xmalloc()/xrealloc() and remove some then redundant error checking, 
@mlschroe any thoughts/preferences wrt that?

**Comment by sourcejedi** [comment]
I just counted from the top-level, using `git grep malloc | wc -l` (v.s. xmalloc).  ~30 direct references to malloc() looks right for lib/.

**Comment by pmatilai** [comment]
I suggest you take a look at the 'git grep malloc' output yourself before feeding to wc -l. Just FWIW.

**Comment by pmatilai** [comment]
@mlschroe ping, mind if we change ndb to use the rpm "native" xmalloc() etc that never fail?

**Comment by mlschroe** [comment]
No, that's fine. We can also remove the code that is not needed in rpm (i.e. the non-rpmxdb code in rpmidx).

**Comment by pmatilai** [comment]
Okay, changed to the x* versions and now redundant error handling removed. Hopefully didn't break anything, but it *seems* really straightforward...
