### ISSUE TITLE
Request to apply IMA signatures to files even if deemed a configuration file

### ISSUE THREAD

**Issue by patrickc25000** [rpm-software-management/rpm#364]
While using the relatively new "--signfiles" rpm option (i.e. rpm --addsign [--signfiles] PACKAGE), I found that IMA signatures for non-executable configuration files, as indicated by the RPM packager, were not applied as part of an RPM upgrade (and I assume installation) even though the signatures for these configuration files were in the metadata for the RPM package. Conceptually, IMHO, the author of the IMA policy in place for the system should be determining what files are appraised (and therefore need  IMA signatures affixed to them) and not the packager of an RPM. If the author of the IMA policy wants to appraise certain files of an RPM package, whether they are configuration files or not, why shouldn't they be allowed to do this and allowed to use RPM to update the appraised files. On some systems, for example embedded systems or appliances like a smart phone, where these configuration files are not allowed to be altered (i.e. are immutable), the owner of the system should be allowed to specify an IMA policy that protects these immutable configuration files from alteration. Of course, if the author of the IMA policy cannot prevent the configuration file from being updated, for example, the IMA policy is running on a system which is open and users can logon and edit configuration files or if the post install script of the RPM updates the configuration file, and many more examples, then the author of the IMA policy cannot list the file as being appraised since for their use of the RPM, the configuration file is mutable. 

Therefore, could the RPM IMA signature support be changed so that the RPM updating code treats the configuration file(s) like any other file and sets an IMA signature on them. The signature is an extended attribute of course (i.e. security.ima) and therefore ignored if the configuration file is not in the IMA policy as being appraised (which given how the code works today, the configuration file cannot be in the IMA policy because appraisal will fail due to the signature missing).

Thank you.

**Comment by stefanberger** [comment]
A potential side-effect of having signatures applied to configuration files is that the configuration files may be modified by the user or programs / post-installation scripts and the signature on these files may become invalid or be removed as part of the modification of the configuration file. That 'a file installed by an RPM will have the correct signature' will therefore not be true for those configuration files.

**Comment by stefanberger** [comment]
This PR https://github.com/rpm-software-management/rpm/pull/374 now addresses the issue.

**Comment by n3npq** [comment]
I have read #364, the basis of which is a belief that security policies like ima should be set by the end user, not the packager.

An imperfect implementation in rpm to generate ima signatures that are invalid when %config files are altered seems a pointless mechanism to generate useless false positives.

**Comment by n3npq** [comment]
I have read #364, the basis of which is a belief that security policies like ima should be set by the end user, not the packager.

An imperfect implementation in rpm to generate ima signatures that are invalid when %config files are altered seems a pointless mechanism to generate useless false positives.

**Comment by pmatilai** [comment]
Yeah it's a bit strange - those "config files" are not supposed to be changed then they're not really config files, are they? Anyway, commit 99887fec108110f0c85c060fcce48d13f807d058 added a mode where you can sign the configs too if you so wish.
