### ISSUE TITLE
RFE: Allow automating %setup arguments

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#368]
`%setup` is a wonderful macro but it shows its age. Massive software ecosystems (such as GitHub) no longer release software in archives that conform to the conventions `%setup` expect.

Nowadays spec writers need to spend a lot of time adapting spec headers to new release conventions, and they are usually tripped by the little `%setup` bit which is not in the same part of the spec but needs adaptation too.

**I'd like rpm to define a magic variable** (for example, `%{setupargs}`) with the following semantics:
if `%{setupargs}` is non nil
  and `%setup` is called without arguments in the spec
 **`%setup` takes the content of `%{setupargs}` as arguments**

**Benefits**:

- easy to define setup arguments in the same place as the rest of the header munging. No more “Drat I forgot to change `%setup`” (I know it's traditional, but really?)
- easy to automate `%setup` behavior in a macro such as
https://fedoraproject.org/wiki/Forge-hosted_projects_packaging_automation
- really safe: difficult to trigger accidentally, easy to remediate (both by adding `%setup` arguments manually or by setting `%{setupargs}` to `%{nil}` or `""`). To be completely safe, a warning can be added when `%{setupargs}`  is set

**Risks**:

Changing the behaviour of an historical macro such as `%setup` is scary, but the proposed way is really safe and conservative

**Difficulty**:

Seems rather easy to do for an rpm expert, in other words a quick win.

**Comment by ignatenkobrain** [comment]
I would love to see `%{_setup_args}` along with `%{_patch_args}`

**Comment by n3npq** [comment]
The literal request to append %setup_args (or %patch_args, same deal) to %setup/%patch is utterly trivial configuration: overload the existing %setup or %patch macros-in-C with any macro definition you wish.

Meanwhile, that isn't going to do anything very useful since neither %setup nor %patch is a single command: both are used to generate multiple lines of shell script, and simply overriding arguments does not provide sufficient scoping hints to tell how/where the overrides are to be inserted.

The tricky problem isn't %setup_args either, but rather the side-effect of setting the buildsubdir. You can already write other multi line macros that expand to whatever you wish, the problem being that you will also need an additional "cd %buildsubdir" at the beginning of %build/%install/%check scriptlets since not using %setup will not set set %buildsubdir.

Any rational attempt to change %setup will have to change the generated shell script template. Devising a new template requires explicit design and examples, not just an RFE for (entirely unspecified) additional arguments with a loose claim of "showing its age".

**Comment by nim-nim** [comment]
I know it's utterly unglamorous, but the basic need is quite simple
- be able to append `-c` to `%setup` from the start of the specfile when a software publishing service produces sources archives without inner topdir
- be able to append  `-n computed-value` from the start of the when a software publishing service produces sources archives not named `%{name}-%{version}` (computed-value will *not* be computed by `%setup`, it does not need to be smart about it)

The second case probably covers 90% of the needs, the first 5%, and the other 5% are too uncommon to need automation

**Comment by n3npq** [comment]
@nim-nim: you can likely already do this, provided you have some means to overload %setup before the invocation in the spec file.

Macros are expanded before %setup is processed. So a definition like

%define setup %%setup -c -n whatever

will append (actually interpose, but you can use a parameterized macro if necessary to eat existing arguments/options).

You can also load the definition from macro configuration, and add %{?_setup_args} if that floats your boat.

**Comment by nim-nim** [comment]
That works, thanks, I didn't know about this syntax before !

`rpm.define("setup %%setup %{?setupargs}")`

I don't understand 'use a parameterized macro if necessary to eat existing arguments/options' however. Can you provide a simple example?

**Comment by n3npq** [comment]
Read about parametrized macros in rpm installed docs (used to be /usr/share/doc/rpm-X.Y/macros, perhaps still is).

Basically a parameterized macro will parse all options/arguments to EOL into she'll-like transient macro names.

**Comment by n3npq** [comment]
The example is

%define setup() %%setup %{?_setup_args}

**Comment by n3npq** [comment]
Finally -- overloading %setup like above is a hackers pathway away from reproducible builds into insanity. JMNSHO ...

(aside)
The real problem -- never well supported, but entirely achievable -- is

How to build from a VCS checkout (not a tarball) with minimal hassle?

This requires additional paraders like URL, authentication, repository name, branch, and checkout identifier (to name just a few of the additional parameters required).

All of the above additional parameters can be mapped into a SourceN: URL ... see what Maven does.

Parsing the URL and writing the script that does, say git clone or git pull would be _FAR_ more useful than overloading %setup.

**Comment by nim-nim** [comment]
Thank you for the additional info! I will look at it.

I'm not overly interested in building directly from VCS since that's security hell (both from the auth POW and the protocol filtering POW). Supporting building from github/gitlab/whatever https auto-tarballs is good enough for me.

In fact it's already way too powerful, as the downside of working at commit granularity is no one properly checks each commit and code explodes right and left as stuff it depends on moves in uncontrolled way. I'll take a release, or even a tag, any day over a commit, let alone a commit not from the main branch.

VCS have not make release engineering obsolete, they've just helped devs run away from consequences faster. But someone still needs to deploy in the end and that someone takes all the accumulated technical debt in the figure at once.

**Comment by n3npq** [comment]
@nim-nim OTOH, note that builds on a public branch (i.e. no authorization), downloaded through https/ssh (so small chance of maliciously modified),  on a tagged/documented check-in located in an upstream VCS repository, are entirely maintainable, as well as being consistent with RPM's goals of "reproducible builds".

Overloading %setup/%patch convolutes a reproducible build with obscure rpm macro configuration.

In fact, many slow-releasing upstream projects are already released through snapshot tar balls as above. The only difference with existing practice in packaging is through conventions in NVR naming to indicate a pre-release, and the tyranny of manually moving, say, a specific checkin forward by editing a maven-like SourceN: URL (as opposed to preparing a pre-release tarball, which can certainly be done already to simplify rpm packaging using %setup without overloading).

But perhaps I misunderstand the goals described here: [https://fedoraproject.org/wiki/Forge-hosted_projects_packaging_automation](url)

**Comment by nim-nim** [comment]
Well, the macro I'm working on for Fedora already pretty much does "builds on a public branch, downloaded through https,  on a tagged/documented check-in located in an upstream VCS repository"

It does not use a magic URL but clear commit/tag variables like other git-oriented tools like godep do (I don't want to be in the business of creating magic urls only to parse them, separate fields are much better)

It does not allow builds from branches as some tools because the tip of a branch moves so that's not reproducible. The packager has to specify a tag or commit hash.

It uses plain https not ssh as Internet ssh does not work in restricted networks, and relies on the public scm autoarchives not the scm itself (that would be trickier to maintain and autoarchives are cleaner)

It is already as safe as it can be, except for %{dist} and %setup munging.

Making %{dist} safe is just a matter of adding a %{?distprefix} placeholder to the default Fedora definition

Making %setup safe is a little more tricky (but that only matters for the few packages that need to call %setup several times in a row, which is already deep black magic for most packagers).

Since the automation macro already knows on what file it needs to apply specific %setup arguments (it's %{_sourcedir}/%{archivename}.%{archiveext}) maybe it's possible to redefine %setup just in this case? Where do %setup store its file argument? Is it possible to do something like:

%global setup() {
%if ??? == "%{_sourcedir}/%{archivename}.%{archiveext}"
   %%setup %{?_setup_args}
%else
 %%setup
%end
}

**Comment by n3npq** [comment]
FYI: %setup permits multiple tar balls be unpacked into a buildsubdir.

Using a parameterized %setup() strips off arguments.

At some point, you are better off just not using %setup at all. Expand into shell commands that unpack (or checkout) whatever you wish.

There's also little reason why you cannot write a tool outside of rpm that creates a (possibly signed) tarball that Just Works with rpm.

**Comment by Conan-Kudo** [comment]
To @n3npq's point, that's pretty much what I did internally for some of our workflows.

**Comment by nim-nim** [comment]
Ok, I'm closing this one for now. Thanks everyone
