### ISSUE TITLE
Human readable size in --queryformat

### ISSUE THREAD

**Issue by SanketDG** [rpm-software-management/rpm#375]
Currently the size displayed in `rpm -qa --queryformat '%{SIZE} %{NAME} \n' | sort -n -r | head -10` with `{SIZE}` is not human-readable at all.

**Comment by herrold** [comment]
How so? 

[screenshot](http://gallery.herrold.com/stuff/rpm-qf.png)

**Comment by Conan-Kudo** [comment]
I think @SanketDG is referring to the fact the size can't be configured to show human representation of storage usage. That is, equivalent to what [`ls -hl`](https://www.mankier.com/1/ls#-h) does.

**Comment by andreas-schwab** [comment]
... | numfmt --field 1 --to=iec

**Comment by pmatilai** [comment]
Yeah the request is "obviously" for kilos/megs/gigs sizes, but I too find calling large positive integers "not human readable at all" strange, they're perfectly normal numbers afterall. Sure we could add a format extension to allow "human readable" formatting for numeric fields, there are many more possibly large numbers in packages than just %{SIZE}.

**Comment by SanketDG** [comment]
Yeah sorry, if it sounds wrong, I just took the idea from other tools that have done this, `ls` for example:

```
       -h, --human-readable
              with -l and/or -s, print human readable sizes (e.g., 1K 234M 2G)
```

**Comment by ffesti** [comment]
This could be done by adding a new format e.g.

rpm -qa --queryformat '%{SIZE:human} %{NAME} \n'

in lib/formats.c

Not sure if "human" is really the best name (it still might be).
