### ISSUE TITLE
RFE: '!=' vercmp operator

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#376]
I just realized that there is no simple way of doing `!=` except by `Requires: (foo < 1 with foo > 1)`. That would be nice to support :/

**Comment by n3npq** [comment]
Use Conflicts: with ==.

**Comment by n3npq** [comment]
FWIW, there are no negated dependencies at all in RPM4. E.g. Requires: !foo == bar being rendered as Conflicts: foo == bar (with similar for other operators).

**Comment by ignatenkobrain** [comment]
@n3npq no, conflicts is different because it blocks installation of multiple versions, but I want what exactly my Requires statement in OP does but in a nicer form.

**Comment by n3npq** [comment]
Um, perhaps, because an unspecified R is defined to match all releases.

But you need to distinguish between the operation != (which will have to do set complements) and negated dependency operations (which solely negates the boolean return of a dependency assertion).

**Comment by ffesti** [comment]
Ehm, this looks very wrong to me: 
`Requires: (foo < 1 with foo > 1)`
Requires a package that does provide a version of foo smaller than 1 and at the same time a version of foo that is bigger than 1. That is not the same as  `Requires: foo != 1`. `Requires: ( foo < 1 or foo > 1)` is.

Also I want to see an actual use case before even considering this.

**Comment by ffesti** [comment]
The longer I think about this RFE the more I think it is a bad idea. I am closing this now. Feel free to reopen if there is a good use case and includes a spec file of an existing package.

**Comment by ignatenkobrain** [comment]
@ffesti I found out today why I wanted that. I want to have way of telling RPM that X conflicts with any other version of Y, but it doesn't require it.

**Comment by ffesti** [comment]
And you really can't be bothered writing
Conflicts: ( Y < 1.2.3 or Y > 1.2.3 )
or
Conflicts: Y < 1.2.3
Conflicts: Y > 1.2.3
?
Sorry, while valid still not a good enough use case.
