### ISSUE TITLE
Moving from rpm-3.0.X to latest version 4.13.0.2

### ISSUE THREAD

**Issue by sangameshss** [rpm-software-management/rpm#384]
Hi All,

What is the best way to move from rpm-3.0.x to latest version 4.13.0.2 ?
If we have rpm packages installed in a machine using rpm-3 then want to move to latest version what is the best practices we need to follow ?

Looks like rpm-3 supports db1 format(.rpm) and latest version of rpm uses Berkely db and latest rpm doesn't supports reading db1. Does my assumption is correct ?

Thanks,
Sangamesh

**Comment by n3npq** [comment]
Yes, db1 is no longer supported in rpm (for like the last 15y).

Meanwhile -- if you _REALLY_ insist on rpm database compatibility -- you could possibly do the conversion by installing several (perhaps 3, possibly 2) versions of rpm and doing rpm --rebuilddb.

You would be in for some serious backporting efforts to assemble the needed rpm versions on a single platform however. Its likely easier to just upgrade the operating system and rebuild all packages needed.

**Comment by sangameshss** [comment]
Hi Jeff,

Thanks a lot for the information.

On the first option of using rpm--rebuilddb, i did check the release note of some of the rpm versions-4 from which reading both db's are supported. Looks like from rpm-4.0.2 to 4.4.2.3 we can use --rebuilddb to make it compatible. As you mentioned we can try these versions and see which one would work.

On second option i haven't  completely got the context.
You mean to say that first we need to update the OS and then reinstall all the required rpm packages ?
Or during update process we created some sort of virtual packages and then install them ?

Thanks,
Sangamesh

**Comment by Conan-Kudo** [comment]
@sangameshss 

You can probably make it so that rpm 4.4.2.3 and rpm 4.14.1 is installed in parallel with some trickery. Then use rpm 4.4.2.3 to migrate rpm3 db to rpm4, then use rpm 4.14.1 to migrate you to the latest.

**Comment by sangameshss** [comment]
Thanks Neal for the information.

I was able to compile 4.4.2.3 and ran --rebuilddb but rpm -qa returns nothing.
Let me know if i am missing any steps here ?

# rpm --version
RPM version 4.4.2.3

# ls /var/lib/rpm
conflictsindex.rpm  groupindex.rpm      packages.rpm        requiredby.rpm
fileindex.rpm       nameindex.rpm       providesindex.rpm   triggerindex.rpm


# rpm -vv --rebuilddb
D: rebuilding database /var/lib/rpm into /var/lib/rpmrebuilddb.8257776
D: creating directory /var/lib/rpmrebuilddb.8257776
D: opening old database with dbapi 3
D: opening  db environment /var/lib/rpm/Packages create:cdb:mpool
D: opening  db index       /var/lib/rpm/Packages create mode=0x0
D: locked   db index       /var/lib/rpm/Packages
D: opening new database with dbapi 3
D: opening  db environment /var/lib/rpmrebuilddb.8257776/Packages create:mpool
D: opening  db index       /var/lib/rpmrebuilddb.8257776/Packages create mode=0x102
D: closed   db index       /var/lib/rpm/Packages
D: closed   db environment /var/lib/rpm/Packages
D: closed   db index       /var/lib/rpmrebuilddb.8257776/Packages
D: closed   db environment /var/lib/rpmrebuilddb.8257776/Packages
D: removing directory /var/lib/rpmrebuilddb.8257776
D: May free Score board(0)

# ls /var/lib/rpm
Packages            groupindex.rpm      providesindex.rpm
conflictsindex.rpm  nameindex.rpm       requiredby.rpm
fileindex.rpm       packages.rpm        triggerindex.rpm

# rpm -qa

#

Thanks,
Sangamesh

**Comment by pmatilai** [comment]
There's a convertdb1 tool in 4.4.x sources that supposedly can convert, dunno, never used.

But, this is not a supported thing nor is this a support forum to begin with, this is a bug tracker. Closing.
