### ISSUE TITLE
python-macro-helper should not have shebang and x flag

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#387]
Looking at 7ac3f07ac41a2760ed6dae65e63fe0b49aec6f6c the `%{_rpmconfigdir}/python-macro-helper` file is always invoked with `%{__python}` and thus doesn't need a shebang and an executable flag. Since `%{__python}` can be redefined, having a hardcoded  `/usr/bin/python` shebang that is never used is misleading.

**Comment by hroncok** [comment]
Also, this makes the rpmb-build package in fedora require python2: https://bugzilla.redhat.com/show_bug.cgi?id=1538657

**Comment by pmatilai** [comment]
Fixed in commit faf7d87fda3456382cf161ff11a2ad8e00ae4ab0, thanks for the report
