### ISSUE TITLE
RFE: implement wrapper for posix.fork()+posix.exec()

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#389]
Many of packages which use filetriggers (e.g glibc and systemd) use following construction:

```lua
pid = posix.fork()
if pid == 0 then
  assert(posix.exec("/foo/bar"))
elseif pid > 0 then
  posix.wait(pid)
end
```

this is just not user friendly and we could implement something like `rpm.execute([args])` which would do all this boring things. Another option is definitely to create macro for this (like `%rpm_lua_execute`), but it's probably not user-friendly.

**Comment by fweimer** [comment]
It might also be nice to use `posix_spawn`, which can be implemented more efficiently that the usual `fork`/`execve` sequence.

**Comment by n3npq** [comment]
These are RFE's for the lua posix module (and should be implemented/patched there), not for RPM.

**Comment by ignatenkobrain** [comment]
@n3npq except that RPM doesn't use lua posix module... It implements its own.

**Comment by ignatenkobrain** [comment]
Submitted #390 for this.

**Comment by n3npq** [comment]
@ignatenkobrain: Um not, implements, but embeds.

lposix.c was a concatenation of the lua posix module available at the time.

Note the "posix." name spacing. 

Perhaps it's time to upgrade the lua posix module and eliminate bloat?

**Comment by pmatilai** [comment]
rpm.execute() added in commit 18e792340e33eade01967d01d5801f1ae9e0ad33
