### ISSUE TITLE
Should python(abi) be provided by the interpreter or something else?

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#395]
https://github.com/rpm-software-management/rpm/blob/b60a086213b5f0ffd68b445e51d205eb1ac64396/scripts/pythondistdeps.py#L129-L134

I believe this adds `python(abi) == 2.7` for Fedora's `python2-libs`, because it owns `/usr/lib64/python2.7/lib-dynload/Python-2.7.14-py2.7.egg-info`. However, it was always the case that only the package that owns `/usr/bin/python2.7` provides `python(abi) == 2.7`:

https://github.com/rpm-software-management/rpm/blob/b60a086213b5f0ffd68b445e51d205eb1ac64396/scripts/pythondeps.sh#L11-L17

This in fact makes  `python2-libs` satisfy the requirement on `python(abi) == 2.7` without bringing in `python2` (and `/usr/bin/python2.7`). This was [reported as a problem](https://bugzilla.redhat.com/show_bug.cgi?id=1412432).

Now I can fix the problem in several ways:

 * require `python2` from `python2-libs` (adds a dependency that's not always needed, but mostly it is)
 * filter `python(abi) == 2.7` by some exclude macro (meh...)
 * move the `Python-2.7.14-py2.7.egg-info` into `python2` package
 * remove the entire section of `pythondistdeps.py`

Before I proceed, I'd like to know why is this code there and what should `python(abi)` actually mean – is it the interpreter, or not? Thanks for clarifying this.

cc @Conan-Kudo, @proyvind, @ffesti

**Comment by n3npq** [comment]
The python(abi) requirement was originally invented to associate a *.py script in a package with an interpreter package. Most of the Requires: are automatically generated from *.py files (which ultimately determines how the Provides: should be added).

Detailed dependency semantics involving embedded interpreters and libraries and interpreter sub-packaging are largely ad hoc and de facto, so there really isn't any right or wrong, only what "works".

**Comment by hroncok** [comment]
Well then I suppose the code segment should be removed. (Or replaced with search for the executable, if `pythondeps.sh` provides generator should eventually die out.)

**Comment by Conan-Kudo** [comment]
@hroncok I would suggest moving the egg info to the interpreter package.

As for the `python(abi)` Provides/Requires, it's still useful for non-setuptools based things, since pythondistdeps only works with distutils/setuptools-based installs.

**Comment by ffesti** [comment]
Sorry for not being more helpful but we as rpm upstream does not really know what is best for Python packaging. So any solution that works for the Python packaging community is fine with us. Closing.
