### ISSUE TITLE
Need to update http://rpm.org/about.html

### ISSUE THREAD

**Issue by leemgs** [rpm-software-management/rpm#396]
We need to update some contents of http://rpm.org/about.html. 
Note that MeeGo was replaced by Tizen in 2012.

* before:
`<a href="http://meego.com/">Meego</a>`

* after:
`<a href="http://www.tizen.org/">Tizen</a>`

**Comment by Conan-Kudo** [comment]
@leemgs that's in https://github.com/rpm-software-management/rpm-web

**Comment by pmatilai** [comment]
Yeah in the future, please report website issues to rpm-web, but fixed now, thanks for pointing it out. 
While at it, made the website bugreport link a bit more prominent in the contribution page.
