### ISSUE TITLE
RFE: rpm should permit a means to add arbitrary tags to packages

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#413]
The current means to add a tag into rpmtag.h and deploy through a release can take months to accomplish.

The necessary time to add a tag to rpm could be shortened to minutes by using the hash of the tag name string (properly canonicalized) within a reserved space (like 0x4000000 -> 0x7fffffff).

The obvious default type of the tag as string (or string array) avoids any need to coerce integers/octets into a display format, and permits existing header retrieval APIs to be used.

**Comment by stephan57160** [comment]
Would it be possible to query those tags, via RPM query itself ?
Thinking of something like 
  rpm -qp --qf '%{applicationspecifictag}\n' ./application.rpm

**Comment by n3npq** [comment]
Depends on the implementation: the existing implementation in RPM5 permits configured arbitrary tags to be used in query formats
