### ISSUE TITLE
RFE: Verify tag types explicitly when loading a header

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#414]
The existing low level sanity test on tag data type in a header checks only that the data type is within range.

What is *NOT* not checked is that a header tag has the expected type. An unexpected data type can cause many issues at higher API levels.

Replacing (and possibly backporting) the existing sanity range check using the expected type is a necessary precursor to any improvement to data typing in rpm, and also -- if done while a header is being loaded -- hardens *.rpm headers from fuzzing attacks and makes high level checks on type unnecessary when accessing header tag data.

**Comment by pmatilai** [comment]
Yup, obviously. I remember looking but don't remember why I didn't actually do this in the mass-refactoring prior to 4.14, maybe the todo-note just fell of the overflowing table, so to speak. So thanks for the reminder.
