### ISSUE TITLE
find-debuginfo.sh expects ELF-files to be executable

### ISSUE THREAD

**Issue by avsej** [rpm-software-management/rpm#422]
https://github.com/rpm-software-management/rpm/blob/2456c128948ac4ade1dbd4a61198a278c23e40be/scripts/find-debuginfo.sh#L331-L335

It is perfectly fine when the application or library has ELF modules which do not have executable bit, but the script will ignore them, and will not extract debug information there.

The outcomes are:

* debug symbols leak into the main packages
* the library packages, which ship only shared objects, have to explicitly mark them as executables, otherwise the build process will fail as it cannot extract any debug info, and will complain about empty `-debuginfo` and `-debugsource` subpackages. That in turn might force packager to skip building debug packages.

**Comment by mhatle** [comment]
My understanding is that this was done as way to allow the package maintainer to PREVENT debug processing.  There are numerous cases, where the debugedit split/strip behavior can trigger problems.  So by using the executable flag, it was easy to disable special processing for those items.

**Comment by avsej** [comment]
OK. thanks. Not a bug then. I can fix it in the spec
