### ISSUE TITLE
RFE: Expose _RPMVSF_NOSIGNATURES and _RPMVSF_NODIGESTS

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/rpm#440]
Mock is using (for ages):

```
    import rpm
    ts = rpm.TransactionSet('/')
    flags = (rpm._RPMVSF_NOSIGNATURES | rpm._RPMVSF_NODIGESTS)                                                                                       
    ts.setVSFlags(flags)
```

And pylint gives me warnings that: Access to a protected member _RPMVSF_NOSIGNATURES and _RPMVSF_NODIGESTS of a client class.

I was ignoring that for ages.  But today, I decided to do something about it :)

Can you please expose those constants without that underscore? I.e., document it and say it can be used in other code outside of the class?
Of course, keeping the original constant for some transitional period would be nice.

**Comment by n3npq** [comment]
The right place to fix conflicting names/usages between C and Python is in rpm python's init.py.

FWIW, each of those values is just a bit mask, you could easily create names in mock.

As easily, you could stop disabling signature/digest checking.

**Comment by xsuchy** [comment]
> FWIW, each of those values is just a bit mask, you could easily create names in mock.

Yes, but then I had to think about it if ever that constant change. I really want to use constant from rpm.

**Comment by n3npq** [comment]
Then use the constant in rpm (w the leading underscore that means something different to Python than C) to create whatever name you wish in init.py.

**Comment by n3npq** [comment]
Again: you could easily stop disabling signature/digest checks in mock.

**Comment by xsuchy** [comment]
> Then use the constant in _rpm
> Again: you could easily stop disabling signature/digest checks in mock.

Yes. I can do both very easily. But I am asking in this issue whether the correct solution should be to do the change at https://github.com/rpm-software-management/rpm/blob/master/python/rpm/__init__.py#L44 as those constants clearly have use outside of the file.

**Comment by pmatilai** [comment]
No problemo exposing these, on the contrary. As soon as somebody figures out a nice suitable naming theme for them... just stripping the leading underscore would lead to naming conflict on RPMVSF_NOPAYLOAD. RPMVSF_MASK_NODIGEST or something, and might as well change the C-side to use them too as it'll make things more obvious.

**Comment by n3npq** [comment]
Sure it's easy to remove an underscore to adapt to picky pylint.

Here are several reasons for not doing so:

1) this is ancient legacy code copied from yum, whose devels wished speed and considered header digest/signature checking slow. In fact, disabling file digests is far more expensive. Been there forever too.

2) there is already means to set a macro to change the default vsf policy. That has been there forever too, set before creating a transaction.

3) signature/digest verification needs to be per-system (or per-chroot, per-vm), not per-application. There is also no attempt in the mock code to make the policy configurable, the policy values are hard wired.

**Comment by pmatilai** [comment]
@n3npq : and all that has absolutely nothing to do with this perfectly legit RFE, so why don't you just give it a rest, okay?
