### ISSUE TITLE
[feature request] autopatch to handle scm same as autosetup 

### ISSUE THREAD

**Issue by xambroz** [rpm-software-management/rpm#442]
Hello,
I am packaging a project which has makefiles configs etc in .gitignore. I was hoping to use the autosetup with option -N (to not process the patches), then remove the .gitignore (to track even automakes and configuration files which are for some reason ignored by the upstream) and then %autopatch -S git.
Unfortunately the %autopatch macro is not capable of handling the SCM the same way as %autosetup.

Please any chance to add the SCM support to %autopatch to be able to continue where the %autosetup -N stopped? Ideally resulting together in the same as "%autosetup -S git" alone.

Thank you
Michal Ambroz

**Comment by pmatilai** [comment]
Like @ascherer pointed out, this already works and very much intentionally so, you just need to initialize the scm with %autosetup. It would've been simpler to embed patch application to %autosetup directly but they're separated exactly to support such needs, so closing this one.

Of course it's possible there are bugs, but in that case we'll need an actual reproducer for the issue.
