### ISSUE TITLE
rpm sign fwrite failed for large file through expect

### ISSUE THREAD

**Issue by ChrisJergens** [rpm-software-management/rpm#443]
Hello,
I have been using expect with rpm addsign for a few years, never really had a problem with it. But recently my teams introduced a new package which is quite large, 905Mb big.  And when the sign script runs this always fails, and I can only find this error.
error: /var/tmp/rpm-tmp.YgXyPZ: Fwrite failed:
Which I believe comes from sign/rpmgensig.c copyFile

I have no problems signing this large file manually, but through expect it always fail. The leftover file in /var/tmp is always 880 bytes short.  I sign tons of files every day without a problem.

Any clues or help about what might be causing this would be very much appreciated.  Thank you.

**Comment by ChrisJergens** [comment]
Of course just after I pull my hair out, I found the issue.
Expect has default timeout of 10 seconds for a command, and this is the first time any package signing has taken that long.  Signing this big file takes ~16 seconds.
So I've added 'set timeout 30' to my expect script, and signing completes without error.  Eureka.

**Comment by ffesti** [comment]
Note that since rpm-4.12.0 signing large packages should be faster if 
%__gpg_reserved_space 4096
is set in the macros file. This reserves room for the signature so the package file does not need to be rewritten. You may want to consider updating the rpm version used on your signing server.
