### ISSUE TITLE
"rpmbuild -tb" does not recognize tar.xz format

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#448]
As it ins in subject:
```
$ rpmbuild -tb tvision-0.8.0.tar.xz; file tvision-0.8.0.tar.xz; rpmbuild --version
error: Failed to read spec file from tvision-0.8.0.tar.xz
tvision-0.8.0.tar.xz: XZ compressed data
RPM version 4.14.1
```

**Comment by pmatilai** [comment]
That's not at all what I'm seeing:

[pmatilai@sopuli tvision]$ rpmbuild -tb tvision-0.8.0.tar.xz
error: Bad source: /tmp/tvision/tvision-0.8.0.tar.gz: No such file or directory
[pmatilai@sopuli tvision]$

So no problem extracting the spec, only the Source0: tarball name specified in tvision.spec.in doesn't match. What do you get with ```rpm --eval "%{uncompress:tvision-0.8.0.tar.xz}"```?

**Comment by pmatilai** [comment]
...actually make that ```rpm --eval '%{uncompress:tvision-0.8.0.tar.xz} | %{__tar} xOvof - --wildcards "*.spec" 2>&1'```, and also what happens if you pipe the above to 'sh' (the spec is what you're supposed to get but clearly not...)

**Comment by kloczek** [comment]
OK. It was my my fault :)
Closing.
