### ISSUE TITLE
RFE: use kernel/keyutils key rings as a backing store for rpm keyrings

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#454]
One of the problems with having secrets like passwords/privkeys within application memory is the risk of loss through a segfault core dump or /dev/mem /proc snooping.

Complete opaque isolation to prevent loss can be attempted with TPM and/or other attached hardware, or by handing off signing to helpers like gpg which have their own means to protect against secret loss.

There is still the problem of how to convey a password/privkey from RPM to another device: the password will be resident within RPM memory.

One way to minimize the risk of secrets being snooped while resident in RPM memory is to use keyutils and linux kernel key rings. The keyrings can be used to pass values to/from rpm execution, and the time that the secrets are present in rpm memory can be minimized by accessing/using/erasing the secret within a more limited scope than the entire lifetime of an rpm process, simplifying audits and minimizing risk.

The keyutils interface is quite simple, and the few places where passwords (or pubkeys) are stored in RPM could/should be replaced with an access/use/erase implementation.

I can supply code pointers or even an implementation if interested.

**Comment by ignatenkobrain** [comment]
@n3npq if you have patch, please send a PR. This is something what would be interesting to see.

**Comment by n3npq** [comment]
You can script up an example using the executable provided with keyutils.

The keyutils API is pleasantly simple.

keyutils is used in RPM5 to save the password passed to gpg for signing as well as a store for pubkeys: doing an implementation is far simpler than designing the namespace and going through an informed security audit
