### ISSUE TITLE
RFE: actually implement --nomanifest* while installing packages.

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#458]
This is an extension of #437 ... I apologize for not being sufficiently specific before.

There are 2 code paths that will read manifest files recursively.

One (newer) code path uses lib/rpmgi.c and honors a query/verify disabler.

The other (older) code path is through lib/rpminstall.c needs to handle the same disabler.

See the original RFE for the reasons why there needs to be a disabler for reading manifests.

**Comment by pmatilai** [comment]
Like said in #437, it IS handled, added way way back in commit 
0e6c5e890460224f455c0ef9e516ea675b00208d:

```
[pmatilai@sopuli ~]$ echo no_such_file > junk
[pmatilai@sopuli ~]$ rpm -Uvh junk 
error: open of no_such_file failed: No such file or directory
[pmatilai@sopuli ~]$ rpm -Uvh --nomanifest junk 
error: junk cannot be installed
[pmatilai@sopuli ~]$ rpm -i --nomanifest junk 
error: junk cannot be installed
```

If you have a case that is *actually* not working, a reproducer please.

**Comment by pmatilai** [comment]
...actually, make that: If you have a case that is actually not working, reopen with a reproducer please.

**Comment by n3npq** [comment]
We are working at cross purposes afaict.

Your test case adds a non-existent file to a manifest called junk.

Add a path to an existing *.rpm in order to test whether --nomanifest disables the reading of a package contained in a manifest.

**Comment by n3npq** [comment]
There is no attempt to test the bit set by --nomanifest at lib/rpminstall.c lineno 550.

See the equivalent code that reads manifests in lib/rpmgi.c for the test that needs to be done.

Another part of this bug is that afaict, "nomanifest" is in the query/verify table which SHOULD scope to only query/verify modes, but the option is being parsed by install modes. His isn't the first time that POPT used by rpm has leakage issues because of table nesting.

**Comment by pmatilai** [comment]
Eh? And what's this then?
https://github.com/rpm-software-management/rpm/blob/master/lib/rpminstall.c#L359

**Comment by n3npq** [comment]
Thank you for pointing out where the test for --nomanifest is performed.

I do suggest that all the code in rpminstall.c is in need of simplification for clarity.

**Comment by pmatilai** [comment]
> I do suggest that all the code in rpminstall.c is in need of simplification for clarity.

No disagreement there. It hasn't seen much love since 2009 when Rakesh Pandit refactored it a bit.

**Comment by n3npq** [comment]
You might try code reviews before doing pull requests in the future.
