### ISSUE TITLE
RFE: implement configurable policy for features used in packages

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#460]
ParseRCPOT() already has logic to control in which tags rich dependencies can be used.

The mechanism needs to be exposed through rpmbuild invocation/configuration so that legacy compatible packages without rich dependencies can be easily built, without risk of tainting with rich dependencies.

Failing the build when rich dependencies are encountered gives packagers a means to control for desired output.

**Comment by ffesti** [comment]
Not quite sure if I understand this correctly. If you want the build to fail if a new mechanism like rich deps are used I'd rather use a more general mechanism that can enforce compatibility with older rpm versions and not limit it to rich deps.
But the first sentence implies that this is about keeping the old behaviour for package that built without rich deps in the past but are now rebuild with rich deps. Do you have some examples?

**Comment by ignatenkobrain** [comment]
Agree with Florian here. If you want to fail build to ensure compatibility with older versions of RPM, there needs to be generic mechanism to do so.

**Comment by n3npq** [comment]
No. This RFE is about failing a build that uses rich dependencies by using a option or configuration macro exposing logic already implemented to set a default to permit a builder to safely loop over a mass rebuild without risk of producing packages tainted with rich dependencies.

See the other RFE if you wish (as I do) to discuss more general mechanisms to integrate compatibility.

**Comment by n3npq** [comment]
To make the implementation crystal clear:

1) make the allow_richdeps disabler in parseRCPOT() global

2) add a rpmbuild option --norichdeps to set the value of allow_richdeps to -1

3) initialize allow_richdeps from a configuration macro like %_rpmbuild_permit_richdeps with expected values -1, 0, 1

4) change the tests in parseRCPOT() to globally disable richdeps parsing when allow_richdeps is less than 1. You -- of course -- will have to change the logic in the case to not override the allow_richdeps value if already set.

5) configure the macro to -1, or add --norichdeps when invoking, and builds of specfilesrunning that use richdeps will always fail.

That simple disabler can be done quickly and easily, permitting builds using latest rpmbuild that can build specfiles that may (or may not) use richdeps.

I suspect you will need a mechanism like this if you are ever going to succeed back porting, not only EL7, but everywhere. Build masters need a simple control function to instantiated a "no rich depsolver please" policy

**Comment by n3npq** [comment]
You can extend the mechanism with a bit mask, and add the thundering herd of specific --norichdepsinrequires if you want finer control of which tags might use richdeps, and document and test.

But you still are going to need a global mechanism to implement a "no richdeps please" policy in order to give build masters control over mass rebuilds using newer rpm+richdeps on rpm-richdeps systems like EL7 that are attempting builds of specfiles+richdeps from latest Fedora.
