### ISSUE TITLE
RFE: implement chained builds by recursively build-and-install in rpmbuild

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#465]
Package builds are increasingly complex, often requiring multiple prerequisites to be present before attempting a given build. When the prerequisites are newer (or otherwise incompatible) with the system provided  packages, this usually requires what is called a chained build with a large number of components -- build system, depsolvers, repositories, etc -- cooperating to achieve a successful build.

This RFE proposes adding the ability to install just built packages as a post operation after a successful build, and a means to recursively invoke rpmbuild on either a manifest or multiple arguments that are first topologically sorted and then executed sequentially.

All the necessary operations to recursively perform a chained build already exist in rpm.

**Comment by ignatenkobrain** [comment]
the unsolvable problem here is that it won't have necessary permissions to install RPMs. And this doesn't help because it doesn't know runtime provides before build. And if it does, it's stupid to build-seewhatcanbebuilt-build-etc.

In any case, this should not be in RPM.

**Comment by n3npq** [comment]
Running rpmbuild as root, dropping perms through the build, and switching back to root for installation is neither rocket science, nor "unsolvable"

You claim this should not be in rpm without supplying any reason.

**Comment by n3npq** [comment]
Rpmbuild certainly checks that build dependencies are satisfied before starting a build (unless disabled), and that check can be done before every link in a chained build to verify that the just installed previous build does indeed supply provides that satisfy new build requirements.

I do not understand your claim "... It doesn't know runtime provides before build". Can you please clarify?
