### ISSUE TITLE
Add --ignoresize by default

### ISSUE THREAD

**Issue by sajig** [rpm-software-management/rpm#468]
I was try to install some packages in stateless os using rpm command. But it fails with filesystem space issue. I want to add --ignoresize in the rpm while installing or upgrading the rpm. 
I have tried with alias and shell wrapper, but the vendor tools are failing on both occasion.

Could I get some guidance to recompile the rpm package to add --ignoresize by default.

**Comment by n3npq** [comment]
Did you try to use a POPT alias for rpm in /etc/popt? See many examples in /usr/lib/rpm/rp popt.

**Comment by sajig** [comment]
Popt is new to me. Thanks for pointing it out.

I tried popt now (rpm alias -i -i --ignoresize)but ran into another issue. Vendor tool is using rpm -qpi and --ignoresize wont work with query(-q).

**Comment by n3npq** [comment]
Yes: rpm has multiple per-mode meanings for the -i short option.

Use the long option name instead.

FWIW, the only known usage case for --install,-i in rpm is the kernel package: every other usage should be with --update,-U, which will be treated identically to --install if there is no older package with the same name.

**Comment by sajig** [comment]
Thank You.

I think I need to talk to HPE vendor to update their binary to fix this issue.
