### ISSUE TITLE
Maximum-RPM repo is missing

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#470]
When moving to GitHub the old rpm.org web page went off line. Looks like http://rpm.org/git/max-rpm.git/ went with it.

**Comment by ffesti** [comment]
Well, just fixed that right away. https://github.com/rpm-software-management/maximum-rpm
I hope there are no changes missing as this is a copy of my private repo

**Comment by n3npq** [comment]
There are other (and better) repositories for both the original rpm.org web site and max-rpm than your private copy.

**Comment by ffesti** [comment]
Yeah, that's what I suspected. Do you have a link? I could not find them right away.
