### ISSUE TITLE
License of python-rpm-generators

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#471]
Hi, we have three files in Fedora's python-rpm-generators:

 * [python.attr](https://src.fedoraproject.org/rpms/python-rpm-generators/blob/master/f/python.attr)
 * [pythondeps.sh](https://src.fedoraproject.org/rpms/python-rpm-generators/blob/master/f/pythondeps.sh)
 * [pythondistdeps.py](https://src.fedoraproject.org/rpms/python-rpm-generators/blob/master/f/pythondistdeps.py)

[pythondistdeps.py](https://src.fedoraproject.org/rpms/python-rpm-generators/blob/master/f/pythondistdeps.py) is clearly marked as being licensed under LGPL 2.1 or later.

The other two files are pretty simple yet they lack license information, so I assume [rpm's COPYING](https://github.com/rpm-software-management/rpm/blob/master/COPYING) apply (that would be just GPL2 (or later?), as those files are not in the lib subdirectory).

Given the nature of the files and their simplicity, can we make Fedora's python-rpm-generators licensed as LGPL 2.1 or later?

**Comment by hroncok** [comment]
@Conan-Kudo @ignatenkobrain @soig @scop @proyvind ?

**Comment by ignatenkobrain** [comment]
I would like to have it licensed as the rest of RPM stuff (IIRC GPLv2+), but I'm fine with whatever @ffesti or @pmatilai come up.

**Comment by scop** [comment]
LGPLv2.1(+) or GPLv2(+) is fine with me.

**Comment by ffesti** [comment]
Please just license those two files as GPLv2+. There is not point in having those scripts as LGPL. It's not like anyone is going to link to them.
