### ISSUE TITLE
BUG: $1 and $2 arguments passed to scriptlets go awry for renamed package upgrades

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#474]
From https://stackoverflow.com/questions/48070042/how-to-detect-upgrade-when-an-rpm-that-obsoletes-another-rpm-is-being-installed

The practice of adding a Provides: oldname to satisfy dependencies when renaming a package has unintended consequences for the package count arguments passed to scriptlets: the count is based on the package N, not the Provides: oldname.

Rather than trying to detect package renaming -- a rather rare event -- and adjust the arguments passed to scriptlets, I'd suggest that the better fix would be to devise a means to differentiate between erase-while-upgrading and erase-while-removing that is by far the most common need to test package counts.

**Comment by ignatenkobrain** [comment]
You mean erase-while-obsoleting?

**Comment by n3npq** [comment]
No. Scriptlets use $1 in %preun/%postun to determine whether a package is being upgraded or erased: name those two distinct logic paths however you choose.
