### ISSUE TITLE
RFC: permit erasures to be mixed into install/upgrade transactions

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#475]
While it is possible to specify both install and erase packages in the same transaction when using rpm libraries/bindings, there is no means to use the rpm CLI to do the same.

I would suggest using (or reserving) the following single leading character in CLI arguments:

* '@' use the contents as a manifest file

* '-' use as a package name to add an erase element to an install transaction

* '+' use as a package file name to add an install element to an erase transaction

* '=' (reserved for depsolver goal)

**Comment by ignatenkobrain** [comment]
This sounds useful, although no one requested this in last 6 years as far as I know. Because all this handled in higher-level tools.

**Comment by n3npq** [comment]
No one has asked for the functionality largely for historical reasons.

Unlike Debian depsolvers, which make heavy use of conflicts to direct an upgrade including removal of conflicting packages, rpm based depsolvers typically treat a conflicts as a full stop error, displaying enough information for a user to manually remove the conflict and restart an upgrade.

The ability to handle both upgrades and erasures in the same transaction is well supported by rpm libraries, but there is no means within rpm to test functionality that already is being used by higher level tools.

This RFE supplies some argument markup in order to be able to test/use already implemented functionality.

**Comment by pmatilai** [comment]
Supporting multiple operations from the cli has been a low-prio item on my todo for 10+ years, but no implementation has materialized... probably because there just isn't that big demand for it. It's a would-be-nice though.

**Comment by n3npq** [comment]
If you like the suggested argument markup, then a patch is possible.
