### ISSUE TITLE
RFE: permit rpm to be invoked as a simple REPL shell

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#477]
This RFE suggests creating a DSL (with commands like "install", "query", etc) to process multiple commands from a single executable invocation.

**Comment by ignatenkobrain** [comment]
IMO this should be done in high-level tools (like dnf) instead.

**Comment by n3npq** [comment]
If rpm supplied a simple REPL, exposed in the API, then there would be no need to reimplement the same REPL stack (usually imperfectly) in multiple applications, in multiple implementation languages.

**Comment by pmatilai** [comment]
And yet those applications would still need to implement their own since they operate on a different level (repo contents instead of local rpms). Supporting multiple operations from the command like (ala #451 ) is the more rpm-like way of doing it anyway.
