### ISSUE TITLE
How to change a header value of something in the base and in the package file itself?

### ISSUE THREAD

**Issue by vityafx** [rpm-software-management/rpm#478]
I need a way to change header tag value both inside a package file and in the database. How can I do that?

Should I use `headerWrite`? Or there is anything else I need to do?

**Comment by n3npq** [comment]
Change the spec file, rebuild, and reinstall is the short answer.

**Comment by vityafx** [comment]
Thanks, but I need to do that in a separate binary or to patch the rpm. So the question is only about doing it in C.

**Comment by n3npq** [comment]
See what rpm does. You will need to read/load the header, remove the immutable region, modify the tag value you wish to change, reestablish the immutable region, recalculate checksums, and rewrite the package or replace the header in the rpmdb.

There is no simple API to do that.

**Comment by vityafx** [comment]
Thanks much for the info. I am looking at https://github.com/rpm-software-management/rpm/blob/master/sign/rpmgensig.c#L505 for the reference, I am right?

**Comment by vityafx** [comment]
@n3npq I looked at the code and found that for doing this I must pass the rpm lead structure but I can't because the header file (rpmLead structure and corresponding functions) are not exported (installed into the system). Can I just skip the rpmLead somehow?

**Comment by vityafx** [comment]
@n3npq 

It turns out I also need `rpmReadSignature` function which is not exported but mentioned in old rpm guide from 2005. I decided to read the file like that:

1. Read the lead structure.
2. Read the signature header.
3. Read the package header.

I can do 1. and 3. now but I don't see a way to read signature header, is there any?

**Comment by n3npq** [comment]
See rpmReadPackageFile() in lib/package.c for the replacement interface.

The code has been refactored to perform all I/O first and then load data structures in order to interpose signature and digest checking on sections of a package file before loading.

The original interface -- which had to run on i486 machines with limited memory -- performed checks on the fly to avoid having header blobs coresident in memory.

**Comment by vityafx** [comment]
@n3npq Could you help me please?

```c
static int readPackage(const char *packageFileName)
{
    int ret = 0;

    const FD_t fd = Fopen(packageFileName, "r+.ufdio");
    if (fd == NULL || Ferror(fd)) {
        fprintf(stderr, _("%s: open failed: %s\n"), packageFileName, Fstrerror(fd));
        ret = 1;
        goto exit;
    }

    /* Read rpm lead */
    char *msg = NULL;
    if (rpmLeadRead(fd, NULL, &msg) != RPMRC_OK) {
        fprintf(stderr, _("Unable to read rpm lead from %s: %s\n"), packageFileName, msg);
        ret = 2;
        goto exit;
    }

    struct hdrblob_s sigblob;
    if (hdrblobRead(fd, 1, 0, RPMTAG_HEADERSIGNATURES, &sigblob, &msg)) {
        fprintf(stderr, _("Could not read signature header from %s: %s\n"), packageFileName, msg);
        ret = 3;
        goto exit;
    }

    struct hdrblob_s blob;
    if (hdrblobRead(fd, 1, 1, RPMTAG_HEADERIMMUTABLE, &blob, &msg)) {
        fprintf(stderr, _("Could not read header from %s: %s\n"), packageFileName, msg);
        ret = 5;
        goto exit;
    }

    Header sigh = NULL;
    if (hdrblobImport(&sigblob, 0, &sigh, &msg)) {
        fprintf(stderr, _("Could not parse signature header from %s: %s\n"), packageFileName, msg);
        ret = 4;
		goto exit;
    }


    Header h = NULL;
    if (hdrblobImport(&blob, 0, &h, &msg)) {
        fprintf(stderr, _("Could not parse header from %s: %s\n"), packageFileName, msg);
        ret = 6;
		goto exit;
    }

    if (!sigh || !h) {
        fprintf(stderr, "PARASHA");
        ret = 7;
        goto exit;
    }
    // whenever I try to read any header value I receive (none) or (null) here, but pointers are not null (the check above ensure they are not)
}
```

**Comment by vityafx** [comment]
@n3npq Could you tell me please, what am I doing wrong here?

```c
static int readPackage(const char *packageFileName)
{
    int ret = 0;

    const FD_t fd = Fopen(packageFileName, "r+.ufdio");
    if (fd == NULL || Ferror(fd)) {
        fprintf(stderr, _("%s: open failed: %s\n"), packageFileName, Fstrerror(fd));
        ret = 1;
        goto exit;
    }

    /* Read rpm lead */
    char *msg = NULL;
    if (rpmLeadRead(fd, NULL, &msg) != RPMRC_OK) {
        fprintf(stderr, _("Unable to read rpm lead from %s: %s\n"), packageFileName, msg);
        ret = 2;
        goto exit;
    }

    struct hdrblob_s sigblob;
    if (hdrblobRead(fd, 1, 0, RPMTAG_HEADERSIGNATURES, &sigblob, &msg)) {
        fprintf(stderr, _("Could not read signature header from %s: %s\n"), packageFileName, msg);
        ret = 3;
        goto exit;
    }

    struct hdrblob_s blob;
    if (hdrblobRead(fd, 1, 1, RPMTAG_HEADERIMMUTABLE, &blob, &msg)) {
        fprintf(stderr, _("Could not read header from %s: %s\n"), packageFileName, msg);
        ret = 5;
        goto exit;
    }

    Header sigh = NULL;
    if (hdrblobImport(&sigblob, 0, &sigh, &msg)) {
        fprintf(stderr, _("Could not parse signature header from %s: %s\n"), packageFileName, msg);
        ret = 4;
		goto exit;
    }


    Header h = NULL;
    if (hdrblobImport(&blob, 0, &h, &msg)) {
        fprintf(stderr, _("Could not parse header from %s: %s\n"), packageFileName, msg);
        ret = 6;
		goto exit;
    }

    if (!sigh || !h) {
        fprintf(stderr, "Pointers are null.\n");
        ret = 7;
        goto exit;
    }
    unloadImmutableRegion(h, RPMTAG_HEADERIMMUTABLE);
}
```

**Comment by n3npq** [comment]
The general flow looks correct (but I didn't write this code, nor do I use RPM4 very much, so I cannot debug this for you).

There is no exit statement, so the code snippet you supplied obviously will not compile, so it's hard to tell what is wrong given incomplete code.

I'd expect a fail error return if the header pointer being returned is NULL.

You should be able to capture the lead if you add a pointer in the rpmLeadRead() call that can be reused when rewriting the package even though the lead structure is opaque.

The msg pointer may have to be free'd if non-null (but those memory leaks are on error pathways and won't matter much).

**Comment by vityafx** [comment]
Thanks very much for the help. There are a lot of thins which prevented me from doing what I need, though I managed to do it eventually. As a sort of thanks, here is what I had problem with and what needed to do:

Problems:
1. I don't need to remove immutability from headers for modifying them. Even if I had needed, it would have segfaulted all the time in `qsort` call somewhere in `headerGet`.
2. I don't need to mimick `lib/pack.c` or `sig/rpmgensig.c`'s package modifier functions because all of these manipulations are not applicable just for changing some header tag value. The reason of that is that the function which is called in both of these places, `rpmGenerateSignature` uses `rpmtd` inside it and I found (after spending a lot of time, of course) that it actually writes more than needed, all the time, and corrupts the header located after it (I got header read errors - bad magic all the time). I decided not to use this at all and to regenerate header's SHA1 hash and manually putting it inside my signature header with just `headerDel`/`headerPutString` functions without any `rpmtd` objects and everything worked fine.

I needed to patch an existing rpm by adding a certificate inside it. It seemed to be an easy task but the code in the rpm looks very complicated to me and I spent like 2+ weeks doing this easy thing: adding a header enum value and patching and rpm. I wish the librpm be not so useless for developers (it is just like nothing for a developer because he can't do anything with it).

Thank you again for spending time on my questions.

**Comment by n3npq** [comment]
No problems.

You have likely appended your certificate to the immutable region, which SHOULD work fine, but perhaps isn't exactly what you want. Note that you originally asked for how to change a tag value, and at least one interpretation of your request forces regeneration of the plaintext (aka the immutable region) used in digests and signatures, and that adds layers of complexity to the operation.

RPM was designed as a secure delivery system from vendor to customer for a reproducible build, not as some means to attach additional information to package metadata (which is what everyone seems to want and expect these days).

So yes the available methods in rpm libraries are mind numbingly complex, bridging digest/signature generation and verification, public key retrieval, and more. The rpmtd layer, which attempts to cache values for performance in a uniform manner, is designed for efficient retrieval, not for modification to the underlying memory used by a loaded header.

**Comment by vityafx** [comment]
@n3npq I have found that if I append something to the rpm header and then delete it to restore old package file state, the size is not the same as it was, for example, before putting certificate the size is 28944, after putting certificate - 33450, after removing certificate - 31*** bytes. Why is that? How can I delete it and put the package file back into the original state?

I perform headerDel and headerPut operations only for deleting and putting certificate respectively. Could it be the signature that is recalculated for correcting SHA1Header checksum in the signature header? I believe this is it.
