### ISSUE TITLE
BUG: hdrblobImport() leaks memory if hdrp argument is NULL

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#487]
SSIA, near line 966.

The memory stealing that follows leaks blob memory as well.

**Comment by ignatenkobrain** [comment]
Pull Request?

**Comment by pmatilai** [comment]
The if is just a leftover from refactoring, this is internal interface with no callers who'd benefit from supporting NULL hdrp. Remove if -> leak gone.
