### ISSUE TITLE
RFE: teach rpm to supply a backtrace when exiting abnormally

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#493]
Glibc provides a routine to unwind the stack (including symbols when available iirc). This RFE is a suggestion to display the stack when exiting abnormally on certain signals.

RPM -- and an rpmdb in particular -- is expected to Just Work in spite of
* itchy trigger fingers using 'kill -9' when rpm is "hung"
* power failures and random reboots
* rpmlib being used as part of complex application stacks, including net-snmp, gdb, Python, perl, etc
* segfaults caused by programmer error or damaged data input

In many cases, an rpmdb can become "corrupted" and rpm becomes unusable, increasing the difficulty of using standard tools like gdb or strace to diagnose a problem. One way to avoid some of those difficulties would be to have rpm provide a stack backtrace when exiting abnormally (whatever that might mean, but I envision tying the backtrace to certain signal handlers)

**Comment by ignatenkobrain** [comment]
If you have patch - please submit PR.
