### ISSUE TITLE
RFE: use exceptions within macro expansion to deliver errors out of band

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#495]
RPM macro expansion (and queries and rpmlog, but those aren't this RFE) would benefit from being able to deliver errors to callers out-of-band through an exception, rather than in-band by writing error messages into the returned buffer or relying on stdout/stderr.

There are 2 approaches:

* in C using setjmp/longjmp to copy an error message back to the caller from deep within a calling stack

* in C++ using the exception framework provided by the language

There is also a need to impedance match popen(3) and lua  (or other embedded interpreter) exceptions into whichever framework is chosen to handle macro expansion exceptions (but those should be separate RFEs as well)

**Comment by ignatenkobrain** [comment]
I wonder what this RFE is about. I mean what's the use-case for those exceptions?

**Comment by n3npq** [comment]
Delivering an error with rpm --expand '%ifarch' is one usage case for exceptions that you are surely familiar with since you reported the issue.

**Comment by n3npq** [comment]
The other impetus for adding exceptions is so the caller can provide a context (including files and linenos when appropriate) for a failed expansion. Adding a try...catch wrapper in the rpmbuild parser permits the parser to supply detailed error information without changing the existing API rather drastically.

The other class of errors better handled by exceptions is diversions using %(...) to call popen(3).
Errors are delivered through stderr: replacing popen(3) to capture stderr and throw an exception provides a mechanism to deliver an error and details to the caller using try ... catch

**Comment by pmatilai** [comment]
C++ doesn't seem like much of an option when you're stuck with C, but the thought of using setjmp/longjmp makes C++ seem almost attractive ;)

I'm more tempted by some sort of callback mechanism, and perhaps ability to register extensions to macro.c to allow at least some of the spec %foo directives to be actual macros.
