### ISSUE TITLE
RFE: handle lists/tuples within macro expansions

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#503]
There are three archetypal forms in computer languages: scalars, lists/tuples/arrays, and maps.

RPM macros only implement scalar key:value assignments. This RFE is a suggested extension to permit macro values to add syntax to expand a stack into a list with a common separator.

The suggested syntax uses a form like %{@F:S} where F is a stack of items created using %define, and S is a separator (like space or comma) to be used between items.

The expansion output should be FIFO (I.e. reversed stack pop order) like (digits represent the order of definition)

1S2S3S...N

Code supplied on request.

**Comment by n3npq** [comment]
Adding %{split:...} and %{join:...} primitives as syntactical sugar for multiple %define operations, implemented through argv routines, are obvious extensions to handling tuples within macro instantiation and expansion.

**Comment by ignatenkobrain** [comment]
Well, send a PR. Submitting gazillions of RFEs doesn't help without patches.

**Comment by n3npq** [comment]
We have had this discussion before: I have no reason to believe that any code I submit will be accepted, and I have multiple instances to indicate that any code I submit will be rejected.

Hence RFEs for comments, of which so far there are almost zero comments.

**Comment by n3npq** [comment]
I can/will point you to the 20-30 lines of code in rpm5 and tell you where to put them in rpm4 rpmio/macro.c if you wish to "play".

There is too little interest for me to justify the work involved in a PR however: the functionality has been mentioned before in rpm.org issues in the past year.

**Comment by ignatenkobrain** [comment]
> I can/will point you to the 20-30 lines of code in rpm5 and tell you where to put them in rpm4 rpmio/macro.c if you wish to "play".

So point me to.

> before in rpm.org issues in the past year

Sorry, you are opening so many of them so I just can't keep up with reading all of them ;)

**Comment by n3npq** [comment]
Get a copy of RPM5 rpmio/macro.c (the cvs is browsable at http://rpm5.org even if the interface is clunky).

Look for "stackarray", the variable that controls the functionality.
There are basically 3 uses:
1) initialize to zero
2) set by parsing/detecting a %{M:S} construct
3) if stackarray is set, then call expandFIFO() to convert a stack to a list

The locations to add that code in RPM4 should be obvious ... let me check.

**Comment by ffesti** [comment]
The macro stacks are a internal implementation detail that we really do not want to expose as part of the syntax - further than it is already. In the future we may change the way macro definitions work to something sane like local name spaces. Adding this feature would make such changes to the macro engine much harder as it encourages people to rely on the stack semantics.

As a side note: Evaluating this RFE would have been easier if the introduction would have been talking about stacks and their role in the macro engine instead of completely unrelated data types. Arrays may be something actually worth considering but are - as far as I understand - completely off topic here.

**Comment by n3npq** [comment]
I'd rather work on code as well.

I understand workload and the need for community transparency.

However, the delays on submitted patches are beginning to be measured in months and years.

The comments are unhelpful to submitters as well, and are usually one of the following:
0) where is the PR/documentation/test case?
1) features from RPM5 are an explicit non-goal (your often repeated policy) so NIH.
2) literal/narrower interpretation of an issue or discussion in order to close.

You have discarded serious patches that I have submitted to your code.
Other RFE's are taking more than a year to even be commented on.
Your commits (like today) are often incomplete.

**Comment by Conan-Kudo** [comment]
> You have discarded serious patches that I have submitted to your code.

This is not true. Both zstd and LMDB support are major contributions that have been merged into rpm.org from you. If nothing else, this proves that we're willing to take proposed code. Just please do the modicum of effort and propose a patch via a pull request so we can look at it, test it, and maybe even merge it. :)

> Other RFE's are taking more than a year to even be commented on.
Your commits (like today) are often incomplete.

Give them a bit of a break, there's only two of them working on it. And for what it's worth, at least @ffesti is fairly accessible and easy enough to talk to about stuff. You of all people should know how difficult it is to manage this kind of thing.

**Comment by n3npq** [comment]
@Conan-Kudo: we differ on what a serious patch is: both zstd and LMDB were shooting fish in a barrel. 

Give them a bit of a break ... from what? Ignoring issues takes zero effort.

I am not on iirc, it's a waste of time for me.
