### ISSUE TITLE
RFE: define NEVRA macro identifiers dynamically while processing each binary package

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#504]
In build/pack.c packageBinaries() there is a loop through the link list of binary packages to produce.

rpmbuild should push/pop the common identification macros (like %name/%version etc) for use by helpers invoked during packaging.

**Comment by n3npq** [comment]
Yes it solves all issues with side-effect macro definitions of tags used multiple times (like Summary: defining %summary).

**Comment by pmatilai** [comment]
Patches welcome.
