### ISSUE TITLE
RFE: rpm needs two i18n domains, one for executables, the other for libraries

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#505]
Increasingly, rpm libraries are used by bindings, or linked by other applications.

In order for I18n to be useful, there appears to be a need to use a 2nd PO file exclusively for library strings, and to consistently use dgettext, not gettext, to do substitution with an explicit translation domain when compiling libraries.

Yes very not fun.

**Comment by n3npq** [comment]
The recommended solution in gettext documentation is separate domains for executables and libraries. This avoids bloat if/when libraries are packaged separately from executables. The efforts of translation teams are perhaps simplified by having two smaller domains: the mostly error messages in rpm i18n are largely from executables, not the library. There are also many rpm executable only code paths through the library that could also be handled in the executable rather than the library domain.

At a minimum, one needs to use dgettext, not gettext, to specifically include the domain in which to look up the string.

**Comment by pmatilai** [comment]
Got a patch?

BTW if you find GH's pull requests cumbersome, good old patches-by-email to rpm-maint list are perfectly welcome.

**Comment by n3npq** [comment]
Without some goal, I cannot do a patch.

Possible goals are:

1) minimal effort: use the existing domain but change to use dgettext() with explicit domain everywhere.

2) minimal size for library domain: use a different marker for the library domain, tuned to code paths used by, say, rpm-python.

**Comment by pmatilai** [comment]
Um, 1. is what already happens, quoting system.h:
```
# define _(Text) dgettext (PACKAGE, Text)
```
Is there an actual issue you're experiencing somewhere? I don't much care for hypothetical tickets.
