### ISSUE TITLE
RFE: POPT aliases supplied by rpmpopt should be documented as such, not as options

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#512]
RPM makes extensive use of POPT aliases: there are easily 2-3 problems solved recently with a POPT alias.

The review process for patch acceptance usually involves a comment/suggestion to update the man page.

Adding a separate "POPT aliases" section to the rpm man page that was populated using a diversion in nroff using the help strings in rpmpopt would automate the doco maintenance and ensure that the man page always agrees with default configuration delivered by rpm.

**Comment by n3npq** [comment]
The diversion could be as simple as extracting the section on POPT aliases from rpm --help and including in the man page section. Retrofit nroff man doc markup if you wish prettier documentation.

(aside)
The master copy of rpm man pages was written using docbook markup that can generate man pages in many formats, not just nroff, in the interest of automating the document workflow process. Automating the documentation of POPT aliases is a similar suggestion.

**Comment by pmatilai** [comment]
Users want stuff documented where they can logically find it, whether something is an alias or not is a just a totally uninteresting implementation detail to them. Grouping documentation by the underlying implementation as opposed to the functionality doesn't help users to find it, on the contrary. NAK.

**Comment by n3npq** [comment]
Users will logically look in man pages to find documentation yes.

Documenting the ability to extend rpm options for convenience is useful for both users and developers.

Knowing that some modes in rpm are implemented by execing, say, rpmsign, using POPT functionality, where the well-documented ability to specify a gpg key is not passed to rpmsign correctly, might be more informative than saying "deprecated" when the bug report comes in.

These are several real world issues reported in last year that documenting POPT aliases might have helped solve.
