### ISSUE TITLE
RFC: please reopen issue #458: the checkin you cited is not present in the github browsable code

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#514]
There  is no way to reopen an issue closed by a repository owner (per Google search)

See details at issue #458: basically there is no indication of the commit you cited in the code that can be browsed at github.

The checkin looks correct, but it is impossible to tell what is happening.

**Comment by pmatilai** [comment]
Geez yes the code has been refactored a bit. Again, provide an actual reproducer if you think there's something wrong, I don't have time for "but I don't see that code so it must be wrong" theories.
