### ISSUE TITLE
RFE: eliminate Fopen and rpmio everywhere in RPM code

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#515]
While assessing whether I should submit a patch to simplify rpminstall.c to use an rpmgi argument iterator, I find that it is no longer possible to query a package on the network.

The intent of the refactoring in rpminstall.c and rpmgi.c clearly indicates a desire to remove rpmio from rpm entirely. That is an entirely sane idea: the usage case for rpm is entirely different these days.

If glibc were to provide a means to retrieve the original pointer used to replace read/write/lseek/close operations with stdio fp, then there is no need for. FD_t and wrappers everywhere in RPM.

Instead a FILE *fp getter would return a pointer to the original vectors which would be followed by all the information currently contained in a FD_t. The returned pointer to the vectors could then be cast to a structure carrying digest/compression etc information.

Rpmio extensions to, say, pass the compression level, or choose the type of vectors, would be reimplemented as setters on the private data structure that can be retrieved from a fp.

The goal would be to always use stdio routines, thereby simplifying the RPM I/O functionality.

**Comment by n3npq** [comment]
Entirely equivalent to the scheme above, and perhaps more general, is a glibc RFE for the ability to attach an opaque vector to a FILE * fp. The scheme originally outlined could possibly be done without any significant change to glibc internals: the ability to retrieve an opaque pointer from an fp is what is needed to eliminate Fopen and rpmio everywhere in rpm.

This can also be done with a registration mapping outside of glibc that associates FD_t private info with an fp pointer.

**Comment by pmatilai** [comment]
Eliminating rpmio never was a goal, eliminating networking was. We're not interested in a glibc-specific solution to what is essentially a non-problem.

**Comment by n3npq** [comment]
Your comment makes no sense.

RPMIO depends on glibc functionality.

You cannot be uninterested in glibc-specific solutions without also being uninterested in replacing RPMIO with stdio

Replacing RPMIO with stdio routines was the entire point of this RFE.
