### ISSUE TITLE
"Warning, not replacing comp_dir" ... "encoded as DW_FORM_string. Replacement too large."

### ISSUE THREAD

**Issue by ghost** [rpm-software-management/rpm#518]
Hello. I'm hitting the following warning(several times) while compiling firefox.spec (from `dnf download --source firefox`) using command `$ time rpmbuild -bb -v -- ~/rpmbuild/SPECS/firefox.spec`:

Warning, not replacing comp_dir '/home/user/rpmbuild/BUILD/firefox-61.0.2/objdir/media/ffvpx/libavcodec/x86/' prefix ('/home/user/rpmbuild/BUILD/firefox-61.0.2' -> '/usr/src/debug/firefox-61.0.2-1.fc28.x86_64') encoded as DW_FORM_string. Replacement too large.

The code for the warning is here:
https://github.com/rpm-software-management/rpm/blob/b7ab1d1d6f2f1adc6ddfae51773d70b9ba08b883/tools/debugedit.c#L1507-L1533

In my case `orig_len`(40) seems to be 3 characters too short than `new_len`(43).

Is the workaround simply just using another username that's 3 chars longer? (since I'm new to fedora/rpm/rpmbuild, this'd be my way of increasing the path length(orig_len) by 3 chars)
Is there some other, perhaps more idiomatic, workaround?

```bash
$ rpmbuild --version
RPM version 4.14.1
$ rpm -q rpm-build
rpm-build-4.14.1-9.fc28.x86_64
$ cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)
```

If I understand correctly, my not fixing this warning will prevent gdb from finding the source files if I ever gdb firefox, correct? (assuming the `~/rpmbuild/` dir is deleted, or I'm installing the resulting RPMs on another machine)

**Comment by pmatilai** [comment]
Oh, we still have some debugedit bugs open. Debugedit has been split to a separate upstream project at https://sourceware.org/debugedit/, please take this there if still relevant.
