### ISSUE TITLE
RFE: bringing LMDB out of experimental state

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#520]
This RFE is an attempt to document two important remaining known issues that need to be solved to use LMDB in production.

The issues are:

* file path indices may exceed limits imposed on the size of keys by LMDB

The solution was already suggested by Howard Chu in Fedora bugzilla: use a hash on the directory name instead of the actual directory name. The hash computation of the directory name can be handled in the LMDB backend without more pervasive changes (though there are space and I/O and consistency benefits to using a directory name hash everywhere)

* header instances used as keys into Packages need to become big endian for btree functionality

A balanced tree expects big endian integer keys so that keys will be equally distributed. Using little endian keys will cause key pile ups that void algorithmic guarantees.

If there are other known LMDB implementation issues, please add.

There are of course further issues converting user databases everywhere, but those issues cannot be blamed on the backend chosen to replace Berkeley DB.

**Comment by pmatilai** [comment]
Renamed the ticket to reflect the actual cause.

Patches for both items would be considered.

**Comment by pmatilai** [comment]
Hmm, there actually was a patch in #287 regarding the big endian key thing, lost in the RFE flood.
