### ISSUE TITLE
RFE: rpm --import no longer permits importing GPG pubkeys from SKS key servers

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#523]
Reproducer:

rpm --import 0x12345678

**Comment by Conan-Kudo** [comment]
Was this ever supposed to work? It'd be nice if it did, but I don't remember being able to import from key servers ever...

**Comment by n3npq** [comment]
the ability to download pubkeys through HKP from SKS key servers most definitely "worked".

And still "works" afaik now that confusions induced by sloppily implemented lib/rpminstall.c have been clarified: it was not at all clear reading that code what was desired at rpm.org.

**Comment by n3npq** [comment]
There are certainly failure modes if firewalls or chroot's prohibit accessing SKS ports.

That is not a failure of the code in RPM.
