### ISSUE TITLE
BUG: network support is limited to install/upgrade

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#524]
At one point in time, the rpm CLI supported URLs everywhere that file arguments were permitted.

Refactoring to remove network support has now limited the places where URLs are permitted.

E.g. It is not possible to do "rpm --query http://host/package.rpm" any more.

Either document that URLs are permitted only with install/upgrade or finish removing network access everywhere in RPM.

**Comment by pmatilai** [comment]
Stop spreading this FUD and try it before filing.

```
[pmatilai@sopuli ~]$ rpm -qpi http://ftp.funet.fi:80/pub/mirrors/fedora.redhat.com/pub/fedora/linux/releases/28/Server/x86_64/os/Packages/a/awstats-7.7-2.fc28.noarch.rpm
Name        : awstats
Version     : 7.7
Release     : 2.fc28
Architecture: noarch
Install Date: (not installed)
Group       : Applications/Internet
Size        : 7160007
License     : GPLv3+
Signature   : RSA/SHA256, Wed 07 Feb 2018 05:34:36 AM EET, Key ID e08e7e629db62fb1
Source RPM  : awstats-7.7-2.fc28.src.rpm
Build Date  : Wed 07 Feb 2018 05:32:31 AM EET
Build Host  : buildvm-aarch64-14.arm.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://awstats.sourceforge.net
Summary     : Advanced Web Statistics
Description :
Advanced Web Statistics is a powerful and featureful tool that generates
advanced web server graphic statistics. This server log analyzer works
from command line or as a CGI and shows you all information your log contains,
in graphical web pages. It can analyze a lot of web/wap/proxy servers like
Apache, IIS, Weblogic, Webstar, Squid, ... but also mail or ftp servers.

This program can measure visits, unique vistors, authenticated users, pages,
domains/countries, OS busiest times, robot visits, type of files, search
engines/keywords used, visits duration, HTTP errors and more...
Statistics can be updated from a browser or your scheduler.
The program also supports virtual servers, plugins and a lot of features.

With the default configuration, the statistics are available:
http://localhost/awstats/awstats.pl

```

**Comment by n3npq** [comment]
Instead of accusing me of spreading FUD, you might help me understand where the download has been implemented.

I have read that code path multiple times, and do not see any indication of download in rpmqv.c nor lib/query.c.

Meanwhile, this RFE was about handling CLI arguments and downloads consistently with network access and URLs, initiated by trying to understand how to simplify lib/rpminstall.c.

Other examples (if my query example is flawed by not being able to detect the download), would also include rpmbuild and rpmsign and rpmkeys, all of which also take file arguments that might be replaced with a URL download.

Can you point me to where/how you wish downloads to occur, starting with query, so that I might attempt to send an acceptable patch?

**Comment by n3npq** [comment]
Ah "network support" is now limited to "download to a tempfile and use that instead".

The duplicated code in lib/rpminstall.c is what was misleading me as to what the rpm.org intentions were and are.

I can now see how to generate a patch to clean up lib/rpminstall.c to use rpmgi

I will close out the other issues I raised which were all derivative on guessing what the intentions were, and what/how a patch might be acceptable, based on what is in lib/rpminstall.c

**Comment by n3npq** [comment]
One issue that needs to be addressed is lack of "network support" (as in the ability to download files with a curl/wget helper) in an environment where networking is deliberately not configured or limited by firewalls or other security protections as in mock/Koji chroot's.

Most of the realities of how/where rpm is used are entirely unsolvable within rpm. Well duh.

There are two issues that I can see that remain however:

* how to express rpm dependencies on helpers like curl dynamically so that, say, rpm does not pick up a boatload of mostly useless prerequisites to ensure functionality through static dependencies.
(hint: probe dependencies on curl/wget file paths, either for existence, or slightly better, on executability)

* reworking the macro helper glue to provide a better message if functionality is unavailable
