### ISSUE TITLE
RFE: make source less special

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#539]
So, I can set SOURCE0, SOURCE1, etc as normal rpm variables in the spec, and spectool will be happy, and download the corresponding sources.

HOWEVER rpmbuild won't be happy at all and will complain the spec does not contain any Source tag

This is a PITA as it means setting SOURCEX values from macros is not natural (when you have a macro that computes several variables, including SOURCEX values):
 1. you need to generate a SourceX:  line for the initial assignation
 2. if for whatever reason you need to rewrite it, then you need to perform normal variable assignation as otherwise rpm will complain of multiple  SOURCEX lines

SOURCEX would be really more convenient to manage as a normal variable,

**Comment by n3npq** [comment]
Yes computing SourceN: spec file directives from %SOURCEN macros is an unnatural act.

The macros are generated when the directive is parsed and not vice vesa.

Whatever you are requesting (it's not clear) seems odd and unnatural.

**Comment by pmatilai** [comment]
How spectool behaves is hardly relevant. There's quite a bit more going on than just defining a macro behind Source/Patch directive processing that I don't see going anywhere. Maybe a more likely scenario would be further Lua-bindings into the build-side of things so you could call some spec.addSource() style function to add sources from macros. But that's just wild speculation for now.

**Comment by Conan-Kudo** [comment]
spectool itself is pretty much a problem to begin with. As the maintainer of the tool, I don't even like its existence all that much. I'd much rather try to figure out a way for rpm itself to handle that functionality in a reasonably sane manner, but the major complication is that we don't have a good way to enforce source validation in rpm such that arbitrarily downloading sources through rpm would be somewhat safe.

**Comment by Conan-Kudo** [comment]
The problem with programmatically adding/removing sources within the spec file means that it's not necessarily guaranteed that sources+spec maps directly to a source package. If we're trying to maintain a reproducible collection of inputs to give a set of outputs, it would be madness to allow mutations in this manner.

**Comment by nim-nim** [comment]
that's a bit of a strawman, that assumes spec + source is sufficient to reproduce things

In the real life it's been known for a long time that the inputs needed to reproduce is every single package installed in the build env. Starting with the macro packages used.

(just try to rpmbuild -bs a Fedora spec on Suse without redhat-rpm-macros for example)

Given the same set of macros, yes rpmbuild -bs will produce the same srpm, unless you intentionally write logic in your macros that produces variable result. But you can already do that today, without this RFE

**Comment by pmatilai** [comment]
Note that you can already programmatically add sources and patches: just generate the corresponding spec lines with macros, whether embedded Lua or something else is up to you. There are no plans to add any other means of adding sources for now, so closing.

**Comment by nim-nim** [comment]
That is completely unhelpful.

You can generate all you want you **will** have human packagers in the loop (because upstreams are imprefect, so human intervention **is** required). And as soon as you have humans in the loop you can **not** rely on everything being generated by your code, and being able to avoid rpm warts this way. You have to fix those warts too.
