### ISSUE TITLE
%requires_eq breaks building in non-English locale

### ISSUE THREAD

**Issue by anoopcs9** [rpm-software-management/rpm#541]
Raising this issue based on [1] on Fedora:

> The reason is %requires_eq macro is buggy:

> #LC_ALL="C" echo 'libldb' | xargs -r rpm -q --qf 'Requires: %{name} = %{epoch}:%{version}\n' | sed -e 's/ (none):/ /' -e 's/ 0:/ /' | grep -v "is not"
balíček libldb není nainstalován

> While correct command is:

> #echo 'libldb' | LC_ALL=C xargs -r rpm -q --qf 'Requires: %{name} = %{epoch}:%{version}\n' | sed -e 's/ (none):/ /' -e 's/ 0:/ /' | grep -v "is not"

> The LC_ALL redefintion must be moved to the "xargs" command.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1597701

**Comment by pmatilai** [comment]
Ugh, the things we have in our source tree. Calling rpm from within rpm was never a good idea (because there's no guarantee it'll actually work in various chroot setups) and here we have an upstream macro doing just that, somehow I've never noticed.

Not argument over LC_ALL placement, just noting that this macro shouldn't really exist to begin with.

**Comment by mlschroe** [comment]
I don't get your chroot argument. The macro only makes sense if it's called from rpmbuild, it's purpose is the generate a requires matching an installed rpm.

**Comment by pmatilai** [comment]
Well, chroot build environments typically get populated with the rpm on the outside of the buildroot. There's no guarantee that the rpm/rpmbuild *in* the buildroot is capable of accessing the rpmdb at all.

**Comment by mlschroe** [comment]
But the rpmdb tends to be in the buildroot as well - you don't want to mess with the system's rpmdb...

**Comment by Conan-Kudo** [comment]
The problem is definitely obvious in cases where you've bootstrapped a SLE11 or RHEL5 system using Fedora or openSUSE. In those cases, the inner rpm is completely useless, since the rpmdb is in the newer format rather than the older one.

**Comment by mlschroe** [comment]
(And that's why SUSE's build script doesn't use the "outer" rpm for bootstrapping. IMHO the only sane way to do it.)

**Comment by Conan-Kudo** [comment]
Well, the way obs-build does it requires it to know exactly the correct way to unpack and manually set up enough for rpm itself, then it uses it going forward.

Mock's variant of this feature bootstraps using outer rpm enough to run target system's package manager to then build a new chroot for that.

Both methods work to solve "that" problem. But if you're not poking the rpmdb, you don't really need to bother with it.

**Comment by n3npq** [comment]
And there is no --root with rpmbuild

**Comment by n3npq** [comment]
FWIW, %_dbpath should be explicitly passed into the rpm query invocation in %requres_eq, principle of least surprise.

**Comment by n3npq** [comment]
Even better would be to add a macro primitive that calls headerFormat() with a configurable format. It's kinda silly that rpm needs to invoke itself

**Comment by pmatilai** [comment]
Buildsystems aside, the issue itself is rather obvious. Fixed in 33276849b143f73776811a1fd0f92d9972a43207, thanks for the report!

**Comment by anoopcs9** [comment]
@pmatilai Do I have to make an additional request to get the backport done into stable branch?
