### ISSUE TITLE
RPM build errors:  Bad exit status from /var/tmp/rpm-tmp.yBCKHX (%prep)

### ISSUE THREAD

**Issue by bmohanty-git** [rpm-software-management/rpm#543]
[root@rh63-41-103 newLinuxBuild]# rpmbuild -bb ~/rpmbuild/SPECS/myproject.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.yBCKHX
+ umask 022
+ cd /root/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ $'\r'
: command not foundCKHX: line 30: 
error: Bad exit status from /var/tmp/rpm-tmp.yBCKHX (%prep)

I am trying to generate a rpm from myproject.spec and myproject-1.9.0.tar.gz file
but getting this error. Kindly help.

**Comment by ignatenkobrain** [comment]
well, show use your spec file.

but my guess would be that you have DOS line endings in spec. try `dos2unix myproject.spec`
