### ISSUE TITLE
RFE: useful lua errors

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#545]
Right now rpm prints out lua syntax errors with line numbers, but forgets to print the macro in which those lines can be found

When several lua macros call each other finding the one which is erroring becomes quite tricky. rpm only points out the top macro name

For example

```specfile
%luamacro() %{lua:
-- lots of processing
print( rpm.expand("%anotherluamacro") .. "\\n")
```

rpm will notify there is an error in %luamacro if %anotherluamacro has a syntax error, instead of notifying the error is in line x of %anotherluamacro

**Comment by n3npq** [comment]
Expecting rpm to provide trackbacks with appropriate line numbers through multiple invocations of lua (and shell) is way out of scope for rpm.

Please provide an explicit example of a usage case where your debugging might have benefitted from better diagnostics, as well as a positive suggestion for what might be implemented in rpm to simplify your debugging needs.

**Comment by pavlinamv** [comment]
Agree. The error message does not help a lot. Some additional info containing whole %anotherluamacro can improve the situation.

**Comment by pmatilai** [comment]
The top macro name you're seeing is simply the line in the spec. Try --trace (or in older versions that don't support it, --eval '%trace') for more advanced macro debugging.

**Comment by nim-nim** [comment]
Thanks for the pointer!

However that does not help a lot when you are mass building in mock (the general case nowadays), and the only debugging help are mock logs, and mock has already cleaned up all rpm temporary files

**Comment by pmatilai** [comment]
Nod. Makes me think that perhaps we should default to macro tracing on when building packages, at least in non-quiet mode.

**Comment by pmatilai** [comment]
This is broader than just Lua, rpm should really print out a "traceback" on macro errors. There's even some code to do that but I guess its not working as it should (shock horror)
