### ISSUE TITLE
RFE: Provide option for %setup to strip path parts in tarballs

### ISSUE THREAD

**Issue by ascherer** [rpm-software-management/rpm#548]
`%patch` provides option `-pN` that gets promoted to `patch` with the same name.

I propose a similar option `-pN` for `%setup` that gets promoted to `tar` as its option `--strip-component=N` (available both in Linux and BSD tar).

**Comment by n3npq** [comment]
Changing %patch creates a bigger legacy compatibility problem than any "fix" solves.

If you truly think that %patch needs to be improved, the please prototype an entirely new macro-in-C implementation and add whatever you wish to see.

For starters, %patch in rpm is forced to carry options that were changed in patch(1) a long time ago.

And %patch does not permit specifying the myriad incompatible options of multiple incompatible decompressors that did not exist last century.

But forget changing %patch, replace with a new and different macro that does whatever you wish.

**Comment by n3npq** [comment]
Ditto %setup: prototype an entirely different implementation with whatever improvements you wish to see instead of adding tortured additional syntax to the existing implementations of %setup and %patch.

**Comment by ascherer** [comment]
Hand over to PR #558.
