### ISSUE TITLE
RFE: Provide macronized default option(s) for %setup

### ISSUE THREAD

**Issue by ascherer** [rpm-software-management/rpm#549]
`%patch` is supplied with `%_default_patch_flags` from `macros.in`.

A similar macro `%_default_tar_flags` may be useful when `%__tar` is invoked by `%setup` "behind the scenes". A possible setting in `macros.in` might be `--keep-old-files` (`-k`).

**Comment by n3npq** [comment]
There are no tar flags that I can think of that might be set globally through configuration, unlike patch, where kernel packagers in Fedora wished tighter control of fuzz.

Keeping old files makes sense only if untarring into a populated directory, almost never the case with rpm builds.

**Comment by ascherer** [comment]
Hand over to PR #557.
