### ISSUE TITLE
how to resolve the libavcodec and libavformat dependencies during rpm installation.

### ISSUE THREAD

**Issue by bmohanty-git** [rpm-software-management/rpm#552]
#rpm -ivh telemetry-1.9.0-8.x86_64.rpm
error: Failed dependencies:
        libavcodec.so.52()(64bit) is needed by telemetry-1.9.0-8.x86_64
        libavcodec.so.52(LIBAVCODEC_52)(64bit) is needed by telemetry-1.9.0-8.x86_64
        libavcodec.so.53()(64bit) is needed by telemetry-1.9.0-8.x86_64
        libavcodec.so.53(LIBAVCODEC_53)(64bit) is needed by telemetry-1.9.0-8.x86_64
        libavformat.so.52()(64bit) is needed by telemetry-1.9.0-8.x86_64
        libavformat.so.52(LIBAVFORMAT_52)(64bit) is needed by telemetry-1.9.0-8.x86_64
        libavformat.so.53()(64bit) is needed by telemetry-1.9.0-8.x86_64
        libavformat.so.53(LIBAVFORMAT_53)(64bit) is needed by telemetry-1.9.0-8.x86_64

**Comment by ignatenkobrain** [comment]
Sorry, not the RPM business. Use dnf/yum.
