### ISSUE TITLE
Generate dependency on setuptools if entrypoints are used

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#555]
If I understand correctly, when installing anything with setuptools which has entrypoints, it will use `pkg_resources` to lokate library. And since python doesn't depend on setuptools, this breaks.

This has been reported somewhere over IRC to me.

**Comment by Conan-Kudo** [comment]
This is true (I've written tools that work this way), but I'm not sure setuptools provides us the ability to introspect that...

**Comment by hroncok** [comment]
fixed in https://github.com/rpm-software-management/rpm/issues/664 ?

**Comment by ffesti** [comment]
Looks like it. Closing.
