### ISSUE TITLE
RFE: set version to 0 when not present instead of erroring

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#559]
rpmbuild should set `Version` to 0 by itself when not present in the spec, instead of complaining

0 *is* the default version used in specs when none exists

The current system forces the creation of countless useless
```
Version: 0
```
lines

Those lines then confuse inexperienced packagers, who start editing them instead of changing `Release`, resulting in the creation of new `Epoch`s when not caught in time

**Comment by n3npq** [comment]
The default value of version is "" (the null string", not 0 (zero).

**Comment by pmatilai** [comment]
It's not that the software doesn't have *some* version in such a situation, it's just that the long-standing practise is to cram that info into the Release tag which is completely wrong.
The right way to deal with such situations is to use the tilde operator, eg 
```
Version: 0~git1234"
```

Defaulting to Version 0 would only encourage continuing to abuse the Release field for the purpose. Sorry but no.
