### ISSUE TITLE
Tests are failing in master

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#560]
```
+/usr/local/lib/rpm/brp-compress: line 8: 1: /usr: syntax error: operand expected (error token is "/usr")
```

**Comment by pmatilai** [comment]
Yeah, Monday brainfart in 5e65f92b53ca07c6e30921688c1b84d0a6b41db7, now fixed in 0e2b8a390e9c9b01920812a65ebd88e0fbad4d3a (reverted + pushed to be able to use the patch as-is individually)
