### ISSUE TITLE
RFE: Autotrim leading and ending empty lines in description, shrink multiple intermediary empty lines to one, also %{text: }

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#566]
When packaging something that needs multiple subpackages, one will usually reuse part of the description. To reduce maintenance shores (fixing multiple copies when an error is detected) this common block is typically  put in an expanded rpm variable.

```specfile
%global common_description %{expand:
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
}
[…]
%description sub1
%{common_description}

This package provides sub1 functionnality.
[…]
%description sub2
%{common_description}

This package provides sub2 functionnality.
```

That works but the drawback is that the resulting descriptions will be full on leading and ending empty lines, with many intermediate empty lines (the sub descriptions can be conveyed in an expand themselves). I know someone could be extra careful on where the expand starts and ends but who has the time to do this? (and that would force splitting the first text line in the middle of a 80 char run)

Please autotrim leading and ending empty lines in description, shrink multiple intermediary empty lines to one, they provide no info to end users.

**Comment by Conan-Kudo** [comment]
There's already a `%{shrink:...}` clause for this.

**Comment by nim-nim** [comment]
Yes there is such a clause. It does you no good if it’s not applied by default to descriptions.

**Comment by Conan-Kudo** [comment]
Why would we apply it by default? It doesn't make sense to, since we go out of our way to leave that formatting alone, since we don't know what the content in it would be.

**Comment by nim-nim** [comment]
What exactly is the contend in an empty duplicated line?

**Comment by nim-nim** [comment]
Anyway `%{shrink:...}` is no good for this.

What you'd want is something similar to

```sh
sed 's|^[[:blank:]]*$||g' |  sed '/^$/N;/^\n$/D' | sed '/./,$!d' | tac | sed '/./,$!d' | tac | fold -s
```
in a `%{text:...}` verb which is applied automatically to descriptions

**Comment by ffesti** [comment]
We really don't want to get into the business of string formatting and text layout. Closing.
