### ISSUE TITLE
Support filenames with spaces in filelists

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#568]
So, sometimes my  upstreams mix files with spaces in their release archives.

That’s  unfortunately inevitable when packaging things made by creatuve people that live in the Apple world.

Unfortunately, that breaks rpm every single time, requiring manual hunting of the problem file and renaming. Please fix rpm so things like

```specfile
%doc 'Bodoni Specimen.pdf'
```
just work as everyone expects them to.

**Comment by ascherer** [comment]
Try `%{quote:Bodoni Specimen.pdf}`. (Off the top of my hat.)

**Comment by nim-nim** [comment]
Alas the following filelist
```specfile
%doc %{quote:NeoHellenic Specimen.pdf}
%doc %{quote:OFL-FAQ.txt}
```
only results in

```shell
+ export LC_ALL=C
+ LC_ALL=C
+ export DOCDIR
+ /usr/bin/mkdir -p /var/lib/builder/rpmbuild/BUILDROOT/gfs-neohellenic-fonts-20090918-15.fc30.x86_64/usr/share/doc/gfs-neohellenic-fonts
+ cp -pr $'\037NeoHellenic' /var/lib/builder/rpmbuild/BUILDROOT/gfs-neohellenic-fonts-20090918-15.fc30.x86_64/usr/share/doc/gfs-neohellenic-fonts
cp: cannot stat ''$'\037''NeoHellenic': No such file or directory
+ :
+ cp -pr $'Specimen.pdf\037' /var/lib/builder/rpmbuild/BUILDROOT/gfs-neohellenic-fonts-20090918-15.fc30.x86_64/usr/share/doc/gfs-neohellenic-fonts
cp: cannot stat 'Specimen.pdf'$'\037': No such file or directory
+ :
+ cp -pr $'\037OFL-FAQ.txt\037' /var/lib/builder/rpmbuild/BUILDROOT/gfs-neohellenic-fonts-20090918-15.fc30.x86_64/usr/share/doc/gfs-neohellenic-fonts
cp: cannot stat ''$'\037''OFL-FAQ.txt'$'\037': No such file or directory
```
```

**Comment by pmatilai** [comment]
Double quotes is what %files has always supported, and it works for %doc too nowadays.
In rpm < 4.11, %doc quoting differed from everything else as it was passed to shell and people used all sorts of creative hacks...

**Comment by nim-nim** [comment]
Of course Panu is right and the one kind of quoting I had forgotten to check was the right one. *sigh* Thanks and sorry for the noise.
