### ISSUE TITLE
BUG Broken check for Name/Summary/Source0 existence

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#572]
RPM version 4.14.2

rpmbuild has a safety feature where it checks if basic tags like  *Name/Summary/Source0* are defined while processing a spec. Unfortunately, the check is not placed correctly in the control flow.

So if you have a rpm macro that does something like:

```specfile
 %{lua:
-- If %{name} does not exist yet this this the first subpackage, that should own the package name
  if (not forcesub) and (forcemain or (rpm.expand("%{name}") == "%{name}")) then
    print('\\nName: ')
  else
    print('\\n%package   -n ')
  end
  print(packagename .. "\\n")
  print("Summary: " .. summary .. "\\n")
```

`rpmbuild` will fail and complain `Name` is not defined

Then if you force a manual `Name:` it will complain `Summary:` is not defined

Then if you supply `Summary` manually, it will process the macros, and fail **again** because this time it has noticed the macro `Summary` definition, there are two of them now, and that’s one too many for it.

Please move all the safety checks for tag existence just before `%prep` processing, **after** every macro call written before `%prep` in the spec file has been processed.

**Comment by nim-nim** [comment]
You have 3 reproducers in
https://copr.fedorainfracloud.org/coprs/nim/rpm.572/builds/

The problem test is on line 80 of the macros.fonts file shipped in fonts-rpm-macros built as part of fontpackages.

copr logs are not interesting, the fact rpmbuild -bs fails makes copr completely blow up. copr was fed srpms built on a system without the problem test (so the specs are known to work)

**Comment by jasontibbitts** [comment]
It would be far more useful if you could simply provide a few short specfiles which illustrate the problem you are having.  I don't think you can reasonably expect the upstream RPM developers (or anyone else, really) to dig through that copr URL to try and figure out what in there might actually show them the problem you are describing.

**Comment by pmatilai** [comment]
@nim-nim , a reproducer is not a link to some random site somewhere, like @jasontibbitts notes we're not going to chase around stuff like that. Provide a minimal reproducer in this ticket if you want this to be looked at.

**Comment by ignatenkobrain** [comment]
I think this has been long enough in waiting-for-info state. Closing.
