### ISSUE TITLE
RFE OptionalBuildRequires

### ISSUE THREAD

**Issue by vries** [rpm-software-management/rpm#577]
Say I have a package A build with optional feature B, which depends on package B:
`BuildRequires:  B-devel
`

Now I find out that A doesn't work with B version >= x.

The simplest way to express this is to use:
`BuildRequires:  B-devel < x
`
but that makes the build fail for distros that have B >= x.

What I want is to enable B for distros where it works, and to disable it for distros where it doesn't work.

I have the option of mapping B version x to distro version y, and use:
```
%if 0%{distro_version} < y
BuildRequires:  B-devel
%endif
```
but I'd like to have an option to make this work without distro mapping.

So something along the lines of:
`OptionalBuildRequires:  B-devel < x
`
which works as BuildRequires but doesn't make the build fail if the package is not present.

**Comment by vries** [comment]
> You're basically asking for `BuildRecommends`?

You're referring to ["BuildRecommends proposal"](https://www.redhat.com/archives/rpm-list/2001-June/msg00193.html). Thanks for pointing that out.

Indeed, that looks very similar.

There is a difference though: the BuildRecommends tag naming suggest that using the dependency is the desirable situation, and therefore the proposal adds options "--pedantic" (as well as "--quiet"), and generates an error with "--pedantic".

The OptionalBuildRequires tag expresses a take it or leave it approach, and would generate a note when not including the dependency, but would not result in an error.

So the difference is in policy of how to handle the absence of the dependency.

**Comment by pmatilai** [comment]
There's a use-case here alright, but I've a feeling the solution is something quite different.

**Comment by ffesti** [comment]
The issue here is that we do not actually want a weak dependency. The build should not depend on some package availability in the direct sense. We probably want to bind the dependency to something more robust.

**Comment by xsuchy** [comment]
We already have two possibilites how to handle this:

1) DynamicBuildRequies https://fedoraproject.org/wiki/Changes/DynamicBuildRequires
2) Bootstrap https://docs.fedoraproject.org/en-US/packaging-guidelines/#bootstrapping

**Comment by ffesti** [comment]
As stated above we'd rather not have weak/optional BuildDependencies. Having predictable builds is a value on it's own. Closing.
