### ISSUE TITLE
Get installed packages from RPM DB

### ISSUE THREAD

**Issue by alonrolnik** [rpm-software-management/rpm#578]
I'm trying to get installed packages from some Docker image and need to do it without using/install rpm. I know that today rpm store it data in /var/lib/rpm inside Berkeley DB files. When I read the Packages file I see binary data. Is it possible to extract the data in human readable format (text) straight from the DB files?

Thanks.

**Comment by ffesti** [comment]
First: This is the issue tracker for RPM. Your problem does not qualify as a ticket here. Questions like this should go to the rpm-list mailing list or the #rpm.org IRC channel (http://rpm.org/community.html)

To your actual question: That depends a lot on what you actually mean. Many things are possible but may be not for you. The rpmdb is not meant to be read without rpm. It contains RPM headers which are binary in nature and while you could read them with other code than rpm itself - and people have done that - this is not encouraged.

You can get the names of the packages - and the names only - from the keys of /var/lib/rpm/Name.

You may want to consider to create the list of package during build time of the container as rpm should be available then - assuming you are building them yourself.
