### ISSUE TITLE
RFE: Please allow empty lines in %{lua: } blocks

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#580]
Right now if you let a single empty line pass within a `%{lua: }` block `rpmbuild` will fail with the completely unintuitive *unterminated macro* error. Unintuitive because the block is clearly terminated with a `}`, the `rpmbuild` parser just gives up at the first empty line before reaching this point.

Even when you know the current `rpmbuild` behaviour it manages to trip you every once in a while.

And even when you know the current `rpmbuild` behaviour and manage to avoid the breakage it results in completely unreadable complex `%{lua:  }` blocks since you can not use empty lines to aerate them when necessary.

**Comment by ignatenkobrain** [comment]
Please provide a reproducer.

**Comment by pmatilai** [comment]
You're supposed use \ line-continuations for multi-line macros, it's even documented:
http://rpm.org/user_doc/macros

I've seen %{expand: ...} (ab)used similarly for creating "blocks" where you don't need line-continuations, but that's undocumented behavior.

**Comment by nim-nim** [comment]
Well here you have an example where `%{lua:` is used for a lua block not to abuse anything, and it would be completely weird and un-intuitive to have to escape the single empty line and not all the other end of lines.

However I should also say that having to sprinkle `\`s all over your macro code is a major PITA, and I’m not surprised `%{expand:` is massively used to force the parser to ingest plain readable code. In fact I’m quite sure the only reason everyone is not doing it is that so few packagers are aware of this `%{expand:`property. 

So from a pure user friendliness POW, it’s not an abuse at all and it would be great to fix the remaining “empty lines need escaping” wart. And maybe even add a `%{code:` container that does no variable expansion at all and just retains the “forget about `\`s” property.

**Comment by pmatilai** [comment]
If skipping line-continuations within %{} is allowed then probably those empty lines should be allowed too. However the examples here are only talking about arguments to built-in macros, whereas there's a more generic case here, and needs further thought.

**Comment by pmatilai** [comment]
This actually got fixed by #1606 .
