### ISSUE TITLE
RFE: Please add a standard way to dump spec variable definitions to macro files in %prep

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#581]
Sometimes macro packages need the macro definitions they ship in their  own spec file, before `%prep` is evaluated. This has led over the years to many workarounds, to try solving this chicken-and-egg problem (sed from spec à la fedora-release, shadow shell variables à la fontpackages,  artificial split-up of macro projects in several srpms that result in build ordering problems, etc)

Since, as seen in
https://github.com/rpm-software-management/rpm/issues/571
reading from sources to the spec does not work, I'll try to do it in reverse, ie write the spec values to macro files in `%prep`

So I'll probably add the following to my macro stash (since I have several packages that need it, probably as a redhat-rpm-macros PR). But it would be much better is something similar was provided by rpm itself

```lua
-- Writes the content of a list of rpm variables to a macro spec file.
-- The target file must contain the corresponding anchors.
-- For example writevars({"foo","bar"},myfile) will replace:
--   @@FOO@@ with the rpm evaluation of %{foo} and
--   @@BAR@@ with the rpm evaluation of %{bar}
-- in myfile
local function writevars(rpmvars, macrofile)
  for _, rpmvar in ipairs(rpmvars) do
    print("sed -i 's\x1d" .. string.upper("@@" .. rpmvar .. "@@") ..
                   "\x1d" .. rpm.expand(  "%{" .. rpmvar .. "}" ) ..
                   "\x1dg' " .. macrofile .. "\n")
  end
end
```

**Comment by nim-nim** [comment]
And the PR has been submitted:
https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/46

**Comment by ffesti** [comment]
Looks like successor the the PR above got merged into redhat-rpm-config. Closing.
