### ISSUE TITLE
RFE: please add a way to get the unexpanded content of a rpm variable

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#582]
As seen in
https://github.com/rpm-software-management/rpm/issues/581

when you want to write some variable definition to a macro file, it gets expanded by rpm. That usually does not matter but unfortunately, in some cases, you really really want the expansion to occur when the file definition is evaluated later, and not at the time you write this file (for example, in fedora-release, you don’t want the `%{?distprefix}` in `%{dist}` to be evaluated by the fedora-release spec, but by the other specs that read it).

You can more or less workaround this by peppering your macro definitions with `%`s before writing to the file but:

* the syntax is awkward, tricky to write and maintain
* that makes the result unusable in the spec that writes the macro file, so you you end up writing the same definition twice, once with added `%`s for the macro file and once without them for the spec itself. And as a result you introduce potential bugs if someone forgets to update both definitions at the same time

Please add a syntax construct (and its lua equivalent like rpm.expand) to access first-level, unexpanded rpm variable contents.

**Comment by ignatenkobrain** [comment]
Just put enough `%%` in there. It seems quite invasive change without much benefit.

**Comment by pmatilai** [comment]
Actually I think this is a perfectly legit request, it's not something you can currently do regardless of how many %-escapes you add and not invasive at all. Something along the lines of:
```
 %{body:<name>} 
```
...but I'm not particularly happy about the name "body" so other suggestions welcome.

**Comment by ignatenkobrain** [comment]
@pmatilai `%{unexpand:…}`?

**Comment by pmatilai** [comment]
%{unexpand:…} is not terrible, but it makes me think of unexpanding that has already been expanded, which is not what it's about. %{body:...} has the benefit that it's the same exact term we use in documentation, so people know exactly what it is.

**Comment by ffesti** [comment]
What about "literal", "quote" or "quoted"?

**Comment by pmatilai** [comment]
Quote/quoting is something entirely different (we already have %{quote:...} btw)

Still thinking %{body:..} is the least worst so far.

**Comment by pmatilai** [comment]
One fairly obvious choice here would be %{noexpand:...} as the direct opposite of %{expand:...}.

**Comment by mlschroe** [comment]
Is the argument a macro name or some generic string? I.e. is it `%{body:_builddir}` which should then return ` %{_topdir}/BUILD`? Or is it `%{noexpand:%_builddir}` which then should only do one level of expansion? I find the latter a bit weird.

**Comment by pmatilai** [comment]
Good question, which I think settles the name as well: the argument is a macro name, so it's not the opposite of %{expand:...} at all but a specific thing that in rpm terminology is known as the macro body, so why make this any more complicated... lets just call it %{body:...} and be done with it.

**Comment by pmatilai** [comment]
...and perhaps there should be that primitive to entirely suppress macro expansion (as per the %{literal:...} suggestion in #1049, which simply expands to its literal, unexpanded argument. But as literal is a macro type now, maybe that should be called %{verbatim:...} instead. Dunno.
