### ISSUE TITLE
RFE/RFC add support for %{yaml: }

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#583]
RPM spec files are an hybrid between declarative and imperative syntax.

That's a wonderful design that weathered well the test of time but, the state of the art progressed a lot since rpm syntax was defined.

The imperative shell part of spec files has already been completed with `%{lua: }` blocks that work wonderfully for complex specs¹.

The declarative part however is still stuck in 1990’s land. And pretty much every packaging system written nowadays eschews this syntax for json or yaml (flatpack is just the latest example, they got the declarative part right, even though their imperative sections are a trainwreck).

Please add a `%{yaml: }' mode with a default mapping to rpm Tags and variable names, that allows declaring all the variable and Tag lists before `%prep` with a modern syntax without all the quirks of the historical rpm syntax. That would allow, like `%{lua: }` before, a progressive transition to a better syntax without hurting packager habits or requiring a big bang rewrite of all existing specs.

¹ They could do so much more if they were not pre-evaluated, but I digress

**Comment by nim-nim** [comment]
It could probably also be combined in some clever way with https://github.com/rpm-software-management/rpm/issues/573

**Comment by Conan-Kudo** [comment]
You're basically trying to ask for a new input build recipe format without actually directly saying it. 

It would actually be easier to design a base input format that is YAML with spec macro overloads then it would be to add brittle YAML to a shell oriented spec file. That said, I'm personally not much of a fan of YAML, but if we're going to talk about reviving the concept of an alternative build recipe format, let's be up front about it...

**Comment by nim-nim** [comment]
I'm not sure rpm specs are shell oriented or not, the scriplets parts, sure, the header/variable parts look more evolved custom config that any specific way to do it to me.

And I have no problem with the scripts parts, they work well and are efficient, I don't see the point of changing them.

What I don't like at all is the variable/Tags/metadata declarations where one is always hitting quirks and idiosyncrasies and badly defined behaviour and misplaced rpm assertions:
 * global vs define
 * Tag vs variable

Those differences and stupid quirks exist only because the rpm custom variable syntax makes no provision for structure, and you need structure to express scoping, so structure was bolted on (badly) via lots of implicit rules and naming workarounds. With lots of asserts to try to glue it all together and prevent the kludge pile from falling apart.

So no, I'm definitely **not** asking for a new  spec-wide input build recipe format, I'm asking for an alternative clean and regular way to express variables and their scope. Optional way that can be mixed and matched with existing syntax like lua has been progressively added to specs, **not** big-bang change everything rpm5-style changes.

Yaml was invented to express structured variable lists, and ansible shows it can be mixed cleanly with shell code when you are careful to use the yaml part for variables only.

**Comment by pmatilai** [comment]
> Please add a %{yaml: }' mode with a default mapping to rpm Tags and variable names, that allows declaring all the variable and Tag lists before %prep with a modern syntax without all the quirks of the historical rpm syntax.
[...]
> So no, I'm definitely not asking for a new spec-wide input build recipe format, I'm asking for an alternative clean and regular way to express variables and their scope. Optional way that can be mixed and matched with existing syntax like lua has been progressively added to specs

You're asking to have your cake and eat it too. Sorry, that's just not possible.

The quirks are an inseparable part of how the spec parser works, you can't just magically throw in a section that is somehow quirk-free but does all the same things. You need a new spec syntax that is actually designed that way instead of implementation driven.

You mention %{lua:..} in specs as something good and nice, but it's actually one giant quirk in itself.
