### ISSUE TITLE
RFE/RFC Add support for %{md: }

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#584]
The desktop people keep inventing new ways to expose software descriptions to users without actually reading rpm package descriptions (last iteration: appstream files).

In theory upstreams are supposed to provide those files, in practice this is massive overreach. Lots of upstreams do not give a fig about desktop people inventions so Linux packagers are getting nagged to write those descriptions for desktop tools.

And since packagers already invested quite a lot of effort in their package descriptions, it would be nice to be able to reuse them. Unfortunately rpm descriptions are not quite up to the task: they're plain text, without the minimum of structure required to render things prettily in GUI tools (at minima: clear paragraph breaks and lists, probably bold and italic too). That's what markdown was invented for.

Please add a `%{md: }` operator, that could be used in package `%descriptions`, to provide rpm with structured text. The result could then be mapped within rpm to plain text, something prettier in GUI tools, and one could write macros to convert it to appstream format or whatever the desktop guys invent next.

That would also make it easier for packagers to copy the md descriptions projects like to publish on github/gitlab/pagure nowadays, without spending a lot of time converting to plain text manually.

**Comment by Conan-Kudo** [comment]
The _whole_ point of Markdown is that they are supposed to legible without formatting. That is, it's typesetting that isn't awful and looks fine without processing.

There's not a lot of reason I can see for introducing a weird tag for this, especially since I can do things like paragraph breaks and lists in there. I've seen my fair share of CommonMark style Markdown in `%description`, so I don't think anything needs to change here...

**Comment by nim-nim** [comment]
Nope, the whole point of Markdown it that it can be used to express formatting without complex formatting syntax. It's definitely **not** end-user legible without some (slight) processing.

And if you say you're able do do formatting without those: just try to convert the result to an appstream description. You'll find out quickly you need some stronger typed syntax than existing free-flow text.

**Comment by nim-nim** [comment]
But anyway, it could be done with asciidoc syntax if you prefer. I don't care much as long as paragraph breaks, lists, and probably bold and italic are unambiguously specified and can be converted to other formats without brittle heuristics. And probably support stripping of `  from descriptyions since they are somewhat popular in tech md/adoc languages.

**Comment by Conan-Kudo** [comment]
I don't prefer asciidoc, I think markdown is fine, but I just don't know why anything special is needed for it...

**Comment by pmatilai** [comment]
NAK, description and friends are simply plain text, asciidoc and markdown are equally legit there if the packager so chooses. Neither might be particularly *pretty* to view without extra formatting but still *readable*, that's the whole point of those formats.  Rpm itself is not in the business of pretty-printing, that the information is viewable suffices fine.
