### ISSUE TITLE
RFE Please provide a way to specify a different summary and description for srpm and rpm sharing a name

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#592]
I have a set of packages with a clearly defined subpackage split: each subpackage has a clear function distinct from the others. Reviewers feel that one of those subpackages is slightly more important than the others and that the srpm should be named after it.

However that totally breaks summaries and descriptions: if I use spec-wide summary/description for the subpackage, it includes things in other subpackages, if I keep its clear functional description, the srpm summary/description gets deceitful.

Please provide a way to attach separate summary/description to the srpm and the subpackage that shares its name

**Comment by ffesti** [comment]
Sorry, this is just too niche. Closing.
