### ISSUE TITLE
License of find-lang.sh is ambiguous around modification

### ISSUE THREAD

**Issue by spotrh** [rpm-software-management/rpm#595]
Because I enjoy resolving 20 year old licensing issues... :)

The existing license on find-lang.sh reads:

```
#findlang is copyright (c) 1998 by W. L. Estes <wlestes@uncg.edu>

#Redistribution and use of this software are hereby permitted for any
#purpose as long as this notice and the above copyright notice remain
#in tact and are included with any redistribution of this file or any
#work based on this file.
```

This license, like many early FOSS licenses, is ambiguous about its support for modification. It also does not carry any sort of warranty disclaimer. I have reached out to Mr. Estes, who has given permission via email for this work to be relicensed under a modern permissive license, specifically, MIT (https://opensource.org/licenses/MIT). I can provide copies of this correspondence upon request. He has clarified that permitting modification of this file was his original intent, however, it is still worth changing this license to prevent others from copying it elsewhere.

In the twenty years or so that this code has been in RPM, the following contributors seem to have made copyrightable contributions to it:

@proyvind @pmatilai @scop @ffesti @jnovy @arekm 

If each of them are okay with relicensing this work under MIT, I would recommend that this happen. I can make a PR if needed.

**Comment by scop** [comment]
- [x] @scop ok with relicensing under MIT

**Comment by arekm** [comment]
I'm ok with relicensing to MIT.

**Comment by jnovy** [comment]
I'm fine with MIT as well.

Jindrich

**Comment by pmatilai** [comment]
Relicensing to MIT is fine by me too.

**Comment by ffesti** [comment]
Fine with me!

**Comment by proyvind** [comment]
I'm fine with whatever

**Comment by pmatilai** [comment]
> If each of them are okay with relicensing this work under MIT, I would recommend that this happen. I can make a PR if needed.

Seems we now have everybody's ack for the license change. @spotrh , a PR would be nice since you know the details best. And would actually feel more comfortable about accepting it after seeing Mr Estes email about the subject.

**Comment by ffesti** [comment]
Ok, looks like this has stalled. 

@spotrh  can you please post the email from Mr Estes? I'll take care of the PR and everything else after that.

You might want to have a quick look at 9ba41db49f2f74465de1fa35e4b6127bc34c4106 to check if we need permission from @pavlinamv but I guess that's not enough to be copy rightable.

**Comment by pmatilai** [comment]
Hmm? Commit 9ba41db is from @vuntz, whose ack we seem to also be missing here. And then there's commit e9c13c6565cf4782d1f73255ee9144dd9bd2aca7 from @pavlinamv .

**Comment by vuntz** [comment]
> Hmm? Commit [9ba41db](https://github.com/rpm-software-management/rpm/commit/9ba41db49f2f74465de1fa35e4b6127bc34c4106) is from @vuntz, whose ack we seem to also be missing here. And then there's commit [e9c13c6](https://github.com/rpm-software-management/rpm/commit/e9c13c6565cf4782d1f73255ee9144dd9bd2aca7) from @pavlinamv .

No problem on my side for relicensing to MIT.

**Comment by ffesti** [comment]
@spotrh : If you are not comfortable posting the mail from Mr Estes here you can also forward it to pmatilai or myself.

**Comment by pmatilai** [comment]
Hmm, ping?

**Comment by spotrh** [comment]
Unfortunately, as I have changed jobs, I no longer have access to the emails in my redhat.com account. While I am happy to swear to the accuracy of my statement above, I can not provide evidence to that fact.

**Comment by spotrh** [comment]
That said, this is him: https://www.linkedin.com/in/willestes/
