### ISSUE TITLE
[rpmbuild] - Can we specify multiple version requirements in .spec file

### ISSUE THREAD

**Issue by spkesan** [rpm-software-management/rpm#598]
Hi,

Currently my .spec file for my tools build contains python requirement as 
```
Requires: python
```
But this seems to sometimes not work on Amazon Linux, where by default `python` installed is `v2.7.13/14` . This creates problem when trying to install my package. (even though `/usr/bin/python` is present)
As a workaround, I just manually install python again using `yum install python`, which installs `python v2.6.9`. 
I have tried `Requires: python >= 2.6`, but still it doesn't seem to fix this issue.
Can you suggest something.

**Comment by ignatenkobrain** [comment]
it's hard to guess what problem you are hitting. But you can specify `Requires: (python >= 2.6 with python < 2.7)`

**Comment by spkesan** [comment]
Can i do something like `Requires: (python >= 2.6 or python <= 2.7)` ?
I need this: check for `python 2.6` or `python 2.7`, use whichever one is available`
I already tried `Requires: python >= 2.6`, it doesn't seem to work.

If i check `which python`, it shows `/usr/bin/python` and `python --version` shows `Python 2.7.13`.
But it doesn't seem to work. 
```
error: Failed dependencies:
	python is needed by MYPACKAGENAME
```
My current spec file has :
`Requires: python`
But as soon as I install python-2.6.9, the package installs properly.

**Comment by ignatenkobrain** [comment]
that's not a problem of RPM, that's problem of you not using yum/dnf. Sorry.

**Comment by pmatilai** [comment]
I know precisely nothing about Amazon Linux, but this sounds like the Python 2.7.x version on that platform is not packaged as "python" but something else. 'rpm -qf /usr/bin/python' ought to tell you what that something else is. Doesn't sound like an rpm bug though.
