### ISSUE TITLE
how to install rpm parallelly

### ISSUE THREAD

**Issue by SRCxiaojin** [rpm-software-management/rpm#603]
now rpm is installed one by one, code below:
while (**_(p = rpmtsiNext(pi, 0)) != NULL_**) {
	int failed;

	rpmlog(RPMLOG_DEBUG, "========== +++ %s %s-%s 0x%x\n",
		rpmteNEVR(p), rpmteA(p), rpmteO(p), rpmteColor(p));

	if (!(rpmtsFlags(ts) & RPMTRANS_FLAG_NOCONTEXTS)) {
	    rpmtsSELabelInit(ts, 0);
	}
	failed = rpmteProcess(p, rpmteType(p));
	if (failed) {
	    rpmlog(RPMLOG_ERR, "%s: %s %s\n", rpmteNEVRA(p),
		   rpmteTypeString(p), failed > 1 ? _("skipped") : _("failed"));
	    rc++;
	}
	(void) rpmdbSync(rpmtsGetRdb(ts));
    }

is there a way of modifing code , then let rpm can run parallelly?
thank you

**Comment by pmatilai** [comment]
No.
