### ISSUE TITLE
pythondistdeps.py: use rich deps for semantically versioned dependencies

### ISSUE THREAD

**Issue by decathorpe** [rpm-software-management/rpm#612]
While setuptools doesn't support range-versioned dependencies (something like `^2.0`), they can be expressed by using something like `'requests>=2.18,<3.0'`.

Currently, this is parsed into two separate dependencies, like `requests >= 2.18` and `requests < 3.0`, where a rich dependency should be used to avoid issues: `requests >= 2.18 with requests < 3.0`

CC: @Conan-Kudo

**Comment by ffesti** [comment]
Looks like this is fixed in #951 
Please re-open if there are still issues left.
