### ISSUE TITLE
Weak dependencies do not allow qualifiers

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#624]
Right now only requires allows using qualifiers like pre, post, preun, postun, pretrans posttrans. This was correct in the past. But now we are using those for ordering, too. So it make sense now to also qualify weak dependencies with the time they are needed/wanted in the transaction to make use of this information in ordering.

Shuffling the case statements in  handlePreambleTag may already do the trick, although someone should probably check the ordering code.

**Comment by pmatilai** [comment]
This should've been closed by commit ddbf30cf96a33319805b362b01d8a6fdfe7dea9c but GH doesn't recognize the Resolves: tag used in the message.

**Comment by pmatilai** [comment]
Erm, though this was already merged but the PR is still open afterall, reopening for the time being.

**Comment by pmatilai** [comment]
Reopening, this never actually worked or it has regressed:

> $ rpmbuild -bb simple.spec 
error: line 8: Unknown tag: Recommends(meta): fu
