### ISSUE TITLE
Mangle inter-package dependencies

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#627]
Imagine that the package you are building, contains following binary packages:

* util-linux (depends on libsmartcols.so.1)
* libsmartcols (provides libsmartcols.so.1)

I believe in 99.(9)% of cases you really want to have libsmartcols installed as a provider and not something else what happen to provide libsmartcols.so.1.

In Fedora Packaging Guidelines is written: if this happens, you must also add `Requires: libsmartcols%{?_isa} = EVR`.

The idea is that if one of the dependency is provided by any other package generated by this source package, then it would be replaced by reference to a package with exact EVR.

---

This has been implemented in ALT here: http://git.altlinux.org/gears/r/rpm-build.git?p=rpm-build.git;a=blob_plain;f=build/interdep.c;hb=HEAD. That code does different things and hard to read, but that is where we can steal some ideas.

**Comment by ignatenkobrain** [comment]
cc @wladmis @ldv-alt

**Comment by pmatilai** [comment]
Took me a while to figure out what you're really asking for here.

I think the more generic issue is (semi-)automatic, strong dependencies between sub-packages, to avoid those ubiquitous and tedious ```Requires: %{name} = %{version}-%{release}``` manual dependencies between sub-packages.

**Comment by ignatenkobrain** [comment]
Is there anything better than `Requires: %{name}%{?_isa} = %{?epoch:%{epoch}:}%{version}-%{release}` available?

**Comment by wladmis** [comment]
> This has been implemented in ALT here: http://git.altlinux.org/gears/r/rpm-build.git?p=rpm-build.git;a=blob_plain;f=build/interdep.c;hb=HEAD. That code does different things and hard to read, but that is where we can steal some ideas.

In that part of code the following happens (A, B and C are subpackages of one package):

- strong intersubpackage dependencies are automatically generated  (if A requires foo, and B provides foo, then a strong dependency on B is added to A);
- redundant dependencies are optimized away (if A requires B and foo, and B provides foo, the foo requirement is optimized away from A);
- strong transitive dependencies are optimized away (if A requires B and C, and B requires C, then C dependency is optimized away from A).

The benefit of these is simplifying of manual maintainer work and reducing the size of package headers and, as a result, repo indices.

**Comment by ignatenkobrain** [comment]
I've submitted this: https://fedoraproject.org/wiki/Changes/Automatic_strict_inter-package_dependencies

**Comment by wladmis** [comment]
> I've submitted this: https://fedoraproject.org/wiki/Changes/Automatic_strict_inter-package_dependencies

> pkgconfig(graphene-1.0) is provided by graphene-devel (coming from the same subpackage), so it can be dropped entirely

This looks a bit ambiguous, it may be understood as you propose to drop pkgconfig(graphene-1.0) from package provides as well. Obviously you should not drop any provided dependency from package. I would explicitly mention that this all about required dependency. And maybe it will be fair to add some mention about ALT experience of this behavior.

**Comment by Conan-Kudo** [comment]
> And maybe it will be fair to add some mention about ALT experience of this behavior.

This was also behavior in OpenMandriva, too.

**Comment by pmatilai** [comment]
> I've submitted this: https://fedoraproject.org/wiki/Changes/Automatic_strict_inter-package_dependencies

@ignatenkobrain , not cool. Please withdraw that. We only have a beginnings of discussion at upstream, no decision to actually go ahead and implement it, much less an implementation. This is NOT a time to submit Fedora features.

**Comment by ignatenkobrain** [comment]
> This is NOT a time to submit Fedora features.

So when is the time? Submitting change proposals help to gather feedback from community and get additional people on board for discussions.

Unless you don't want any external people to be involved, implement something and then wait another 10 years for adoption, we should go with change **proposals** early.

Also since it is change proposal, it does not have to be implemented.

**Comment by pmatilai** [comment]
This is not how we roll as you should know perfectly well, please respect that. Asking for external feedback (eg on distro devel forums) ideas is of course fine, a change proposal is quite something else. 

If you want to see things done differently, start by talking to us. Stepping over upstream to drive your own view of how things should be done is not appreciated. To put it really, really mildly.

But this discussion doesn't belong in this ticket either.

**Comment by nim-nim** [comment]
> The idea is that if one of the dependency is provided by any other package generated by this source package, then it would be replaced by reference to a package with exact EVR.

I'm pretty sure this would break a lot of rpm bootstrapping and re-layouting scenarii. They often rely on replacing some (but not all) of the subpackages, produced by a srpm, by subpackages produced by another srpm.

**Comment by pmatilai** [comment]
I agree that it's just absurd packagers need to manually add dependencies for such a common case, but I don't really think adding yet more dependencies is the solution. I filed the idea on a more generic level as #1105, lets continue there.
