### ISSUE TITLE
Define milestones for major and minor releases

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#636]
For external people and other contributors it is not visible when next release of RPM will happen and what features will be there.

GitHub provides "Milestone" feature, so could you create 4.15 milestone and assign Pull Requests and Issues which are planned for that release? And possibly setting some date too.

For example, in libsolv there is `1.0` milestone: https://github.com/openSUSE/libsolv/milestone/1

**Comment by pmatilai** [comment]
We used to do this (milestones) back in the Trac days but it didn't seem worth a whole lot to anybody.

Doesn't mean we couldn't try it, I do understand the problem of rpm.org plans being opaque to the outside when they tend to be opaque on the inside as well...

**Comment by ignatenkobrain** [comment]
@pmatilai so what can we do to make it better? Should I go ahead and create 4.15 milestone and put PRs and issues there (the ones I think should be done for 4.15)?

**Comment by pmatilai** [comment]
Please don't, a wishlist maintained by the community wont provide the answers you're after.
This would be something that the core team would need to commit to, and actually do.

**Comment by pmatilai** [comment]
Oh, there was a ticket for this. Closing, as we are actually using milestones now, or at least, trying to.
