### ISSUE TITLE
Python generators: Fails to add != dependency

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#639]
nbsphinx 0.4.2 has:

```python
    install_requires=[
        'docutils',
        'jinja2',
        'nbconvert!=5.4',
        'traitlets',
        'nbformat',
        'sphinx>=1.6',
    ],
```

The resulting dependencies are:

```
python3.7dist(docutils)
python3.7dist(jinja2)
python3.7dist(nbformat)
python3.7dist(sphinx) >= 1.6
python3.7dist(traitlets)
```

Note that `nbconvert` is missing entirely. It should probably be added as a boolean require on smaller or larger version.

**Comment by Conan-Kudo** [comment]
@hroncok You mean `nbconvert`? I see `python3.7dist(nbformat)` in there...?

**Comment by Conan-Kudo** [comment]
@hroncok How would we translate `'nbconvert!=5.4'`?

Would we go with `Requires: (python3.7dist(nbconvert) < 5.4 with python3.7dist(nbconvert) > 5.4)`?

Or would we enable Conflicts generation and translate this into the following?

```specfile
Requires: python3.7dist(nbconvert)
Conflicts: python3.7dist(nbconvert) = 5.4
```

**Comment by ignatenkobrain** [comment]
Now I finally remember why I opened https://github.com/rpm-software-management/rpm/issues/376

**Comment by hroncok** [comment]
Yrs, nbconvert, edited. I don't think conflicts would be good, does the version equivalency work for e.g. 5.4.1? I'd need to check how != works in this case with pip.

**Comment by hroncok** [comment]
Also with would not work here, but or would.

**Comment by hroncok** [comment]
Ok, pip behavior:

Latest nbconvert version now is 5.4.1. 5.4.5 exists as well.

 * `pip install 'nbconvert!=5.4'` installs 5.4.1
 * `pip install 'nbconvert!=5.4.1'` installs 5.4.0
 * `pip3 install 'nbconvert<5.4.1'` installs 5.4.0
 * `pip3 install 'nbconvert<5.4.1,!=5.4'` installs 5.3.1

So for pip, 5.4 is the same as 5.4.0 but not the same as 5.4.(anything).

For rpm on the other hand, 5.4 < 5.4.0.

So to answer the original question, this should be:


    Requires: (python3.7dist(nbconvert) < 5.4 or python3.7dist(nbconvert) >= 5.4.0.0.0.0.0)

Ideally with infinite number of zeros :(

**Comment by hroncok** [comment]
Or, the provides generator should chop any leading zeros. That is even better beccasue it would avoid stuff like this:

https://src.fedoraproject.org/rpms/python-flake8/blob/aa80b5f09c9aaf77a95c7b7f7cb81c368636af7b/f/python-flake8.spec#_59

**Comment by hroncok** [comment]
https://packaging.pypa.io/en/latest/utils/#packaging.utils.canonicalize_version

**Comment by hroncok** [comment]
I have a fix in https://github.com/hroncok/rpm/tree/canonicalize_version but github 500s on creating the PR.

**Comment by hroncok** [comment]
https://github.com/rpm-software-management/rpm/pull/757
