### ISSUE TITLE
RFE: Store built binary rpms info in source rpm

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#642]
Originally requested at http://lists.rpm.org/pipermail/rpm-ecosystem/2019-March/000717.html by Pat Riehecky, copied here verbatim:

> Would it make sense for a source rpm to have a generated 'Provides:' for any %package defined within the spec?
>
> For example (actual syntax to be determined by folks smarter than myself):
>
> $ rpm -qp --provides man-db-2.8.4-4.fc30.src.rpm
> rpmbuild(man-db)
> rpmbuild(man-db-cron)
> $
>
> I'd expect it to 'provide' all the %packages (even ones masked for your specific arch so that we don't deal with executing macros at query and whatnot). 

The actual syntax would likely be different but the request is perfectly reasonable: we store the dependencies and all sorts of other information of that particular build into the src.rpm as it is, why not include the generated packages too (which can also vary a lot between builds).

**Comment by pmatilai** [comment]
After thinking about it a bit more over breakfast, there are multiple scenarios that people might want to use that information for. In addition to name, EVR should certainly be included, because it can vary between subpackages. Ditto with arch. Storing the generated binary package name is one straightforward option, all it needs is one new string array tag (provides doesn't seem right for the purpose for several reasons). The obvious downside is that you need to parse the string to access individual components, and it doesn't normally include epoch which you'd probably want to know. The other option would be to add separate name, evr and arch tags for the purpose, which is added complexity and you might still need to parse the evr into its sub-components.

In the meanwhile I remembered the reverse version of this RFE: to include source package NEVR in the binaries (https://bugzilla.redhat.com/show_bug.cgi?id=1008387). That shares the same problems as using the actual binary name would have - the binary name is configurable and thus not reliable, and normally doesn't include epoch at all. 

If we add one, I think we should add the other one too, and sharing the same predictable format.
Parsing these things is not rocket science and everybody does it already anyway so I suppose the single tag variant would do fine as long as it's something that can be reliably parsed. NEVRA seems like an obvious choice but I could be convinced otherwise.

**Comment by ignatenkobrain** [comment]
I think this is quite complex thing, because once we get automatic subpackages generation, you will face same problem as with BuildRequires generator... That your sourcerpm is incomplete until you build whole thing....

Not saying that it is impossible, but I don't see it very useful in long-term perspective.

**Comment by pmatilai** [comment]
There's now a potential implementation in #891

**Comment by pmatilai** [comment]
This already got merged (commit  75ec16e660e784d7897b37cac1a2b9b135825f25), just forgot to close the ticket.
