### ISSUE TITLE
%transfiletriggerin does not return file list

### ISSUE THREAD

**Issue by tpgxyz** [rpm-software-management/rpm#644]
Hi,

i've a script in lua:
`%transfiletriggerin -P 900901 -p <lua> -- /usr/share/foo`

foo.spec file installs many files in /usr/share/foo
I'd like to catch that all the files which are now installed by foo.rpm using lua script in %transfiletriggerin
I've tired to carch arg[] from 0 to 6 and none of them returned file list.
Even stdin is empty

```
%transfiletriggerin -P 900901 -p <lua> -- /usr/share/foo
v=io.read()
print(v)
```
I've tried poorly documented rpm.next_file
```
%transfiletriggerin -P 900901 -p <lua> -- /usr/share/foo
a = rpm.next_file()
while a do
 print(a)
 a = rpm.next_file()
 end
print("")
io.flush()
```
Above returned list of files existing in /usr/share/foo already, not those which are about to be installed in foo.rpm

Looking for a help.

**Comment by pmatilai** [comment]
With -p <lua> file triggers, rpm.next_file() is the right thing to do, -p <lua> scriptlets are not forked currently so the stdin is that of rpm itself.

What rpm version is this? File triggers are known to be rather buggy prior to rpm 4.13.1 (and I'm quite positive there are more lurking still)

**Comment by tpgxyz** [comment]
@pmatilai I'm running here rpm-4.14.2.1-7.x86_64
rpm.next_file() throws files from path given in here %transfiletriggerin -P 900901 -p <lua> -- /usr/share/foo
not from actually installed rpm file index

**Comment by pmatilai** [comment]
Right, this rings a bell: those pre-existing files invoke triggers on purpose, see https://github.com/rpm-software-management/rpm/issues/386
But you should really be getting both the pre-existing and ones from the current transaction. IIRC.

**Comment by tpgxyz** [comment]
@pmatilai Sorry i can not confirm that rpm.next_file() returns files from current transaction. Maybe this is because my triggers dir is different that install dir ?

```
%transfiletriggerin -P 900901 -p -- /usr/share/foo
--   returns files that already exists in /usr/share/foo and one file which is installed in current transaction
```

foo.rpm does carry more files in different directory, but these are not listed on above call, which is quite important to me.

**Comment by tpgxyz** [comment]
Anyways i've fixed this. Error was on my side. Thanks for your time.

https://github.com/OpenMandrivaAssociation/systemd/commit/d56fdec906b2d7f60512962260f3fe2300ec5017
