### ISSUE TITLE
Specialdirs get zero as file verify flags

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#655]
processSpecialDir() does this at the end to add the special dir to the file list:
```
FileEntryFree(&fl->cur);
FileEntryFree(&fl->def);
copyFileEntry(&sd->entries[0].defEntry, &fl->def);
````

`FileEntryFree(&fl->cur)` sets `fl->cur.verifyFlags` to zero.

**Comment by pmatilai** [comment]
Fixed by commit 966863911c872405ee36b4eb8bcbfdbfd76e9431
