### ISSUE TITLE
RFE: BuildProvides generator

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#657]
This is a follow up on issue #104 (which is awesome, please ship it!)

For most projects, issue #104 is going to simplify things a lot and will be sufficient by itself.

However it won’t be sufficient for complex projects. We’ve all forgotten that those projects can build multiple objects, some of which are used by others during the build process. I’m thinking of the kind of project with multiple `SourceX` archives in input, and multiple rpm subpackages in output. 

To generate accurate `BuildRequires` for those projects, you need to take into account all to-be-built elements, and remove them from the `BuildRequires` list. Right now, because listing `BuildRequires` is a completely manual process, the filtering is done implicitly by the packager, by  running an imaginatory dep engine, and removing self-provided stuff from the `BuildRequires` list.

`BuildRequires` generators however won't have any imagination. And it would be needlessly complex and unreliable to make them reimplement a parallel dep engine¹. The simplest technical solution would be to use the same mechanism rpm uses for `Requires` generator output: don’t make generators worry about other bits in the package, let rpm auto-remove corresponding `Provides` when they are included in the package itself.

Technically, that just means creating a new `BuildProvides` category, and make it reuse most of the code written for `BuildRequires` in issue #104.

This is similar, but not identical, to issue #642:
* issue #642 deals with `Provides` as they exist at the end of the build process, while `BuildProvides` exist as a projection at the end of `%prep`
* some of the `BuildProvides` may never be shipped in the final produced subpackages, because they are not useful except as intermediary building steps of this particular project. Also, I expect bootstrapping builds to use quite a lot of private build objects, because the clean production objects won't be provided by other packages before the bootstrapping is finished².

¹ [this commit](https://pagure.io/modist/c/cfb70e4615167864cf8054e598c663bc92e52e61) is an example of all the complexity involved in transforming a `BuildRequires` generator from a single-object utility to a multiple-objects utility. And, the result is langage-specific: it won’t work in presence of other `BuildRequires` generators.

² Actually, I’m confident that `BuildRequires` + `BuildProvides` generators will remove huge blocks of bootstrapping ifdefery from specs, reducing most of it to source massaging logic in `%prep`

**Comment by Conan-Kudo** [comment]
We don't even _have_ `BuildProvides` as it is...

**Comment by nim-nim** [comment]
Yes, I know, it's a next step kind of thing, the usefulness of `BuildProvides` is not really evident, until you start generating `BuildRequires` automatically.

**Comment by ignatenkobrain** [comment]
Everything what you need to do is to check what is going to be built during %generate_buildrequires and filter that out.
