### ISSUE TITLE
should document -q

### ISSUE THREAD

**Issue by Nick-Levinson** [rpm-software-management/rpm#662]
Both info rpm and man rpm are missing entries defining -q although they show that -q can be used.

**Comment by pmatilai** [comment]
Um, there's:
```
   QUERYING AND VERIFYING PACKAGES:
       rpm {-q|--query} [select-options] [query-options]
```
and
```
   QUERY OPTIONS
       The general form of an rpm query command is

       rpm {-q|--query} [select-options] [query-options]
```
To me that says quite clearly that -q is an alternative to --query, and that query is, well, query. So I dont know what you think is missing.

**Comment by Nick-Levinson** [comment]
The pipe in the context means mutual exclusivity, not identicalness of meaning. While identicalness of meaning (when redundancy is disallowed) produces mutual exclusivity, mutual exclusivity does not produce identicalness of meaning. Already, info rpm explicitly describes both -v and --verbose options and man rpm-misc describes -d and --debug options.

The --query option is also undefined in the info files. To consider it obvious would mean applying that to various other options as well, but it's more useful to describe even obvious-seeming options so that we are clear on parameters of an option. If it has limitations, a clear definition will say what they are; if it does not have limitations, the description will assure users that an unexpected result is not due to limitations inherent to the option.

**Comment by pmatilai** [comment]
Upstream rpm doesn't *have* any info files, so I cannot comment on contents of those.
Other than that, I guess we'll just have to agree to disagree, I don't know how to make it any more obvious in the manual, in the structure that rpm manual uses.
