### ISSUE TITLE
Python generators: Add setuptools dependency for console_script entry points

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#664]
Almost no upstream specifies setuptools in install_requires. I guess that it is pretty straight forward upstream that if you pip install stuff, you already got setuptools installed.

However, [the console_scripts entry points](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) are de-facto standard now and they import from pkg_resources (part of setuptools).

Packages with console_scripts entry points need setuptools on runtime.

It is possible to see console_scripts entry points metadata and hence it is possible to require setuptools for packages with entry_points.

Example: https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/YR6OG5CULN42R5FPKHWUASEGDWMABC5K/

**Comment by hroncok** [comment]
Example metadata:

```
$ cat %{buildroot}%{python3_sitelib}/fedpkg-1.36-py3.7.egg-info/entry_points.txt 
[console_scripts]
fedpkg = fedpkg.__main__:main
fedpkg-stage = fedpkg.__main__:main
```

Other possibility:

```
$ grep EASY-INSTALL-ENTRY-SCRIPT %{buildroot}%{bindir}/*
# EASY-INSTALL-ENTRY-SCRIPT: 'fedpkg==1.36','console_scripts','fedpkg'
```

**Comment by ignatenkobrain** [comment]
is it possible knowing that using pkg_resources API?

**Comment by hroncok** [comment]
Yes, working on it.
