### ISSUE TITLE
Outdated mono-find-provides

### ISSUE THREAD

**Issue by mavit** [rpm-software-management/rpm#673]
The `/usr/lib/rpm/mono-find-provides` script bundled with RPM hasn't been updated for a long time.  A more recent version of this script can be found in the [Mono sources](https://github.com/mono/mono/blob/master/scripts/mono-find-provides.in), and, on Fedora at least, this newer version is installed in `/usr/bin` by the `mono-devel` package.

We could copy and paste a newer version of the script into RPM, but I wonder whether this script belongs in RPM at all?  Since the script calls the `monodis` binary, it will only work when the `mono-devel` package is installed.  This being the case, we might as well use the version of the script included with `mono-devel`.

If this seems reasonable, I will prepare a pull request.

**Comment by mavit** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1700892

**Comment by pmatilai** [comment]
We've been expunging things that are only in rpm due to historical reasons, and language specific things certainly classify. Thanks for the pointer, everybody will be much better off with an upstream maintained dependency generator, submitted as PR #676
