### ISSUE TITLE
Reject %pretrans scripts that are not lua

### ISSUE THREAD

**Issue by ffesti** [rpm-software-management/rpm#714]
There is no way to run a %pretrans script that relies on anyhting but lua as it will run on an empty system for new installs. RPM should just reject to create such scriptlet in the first place.

**Comment by pmatilai** [comment]
Well, technically it's perfectly okay to have a package that's only installable after the OS installation, not all packages live in repositories and get installed as a part of system installation. We also do handle this correctly for almost a decade - such a package fails cleanly pre-transaction dependency check if part of initial install but succeeds in a later transaction (commit c0eb82dd1f2102f2b4899c1e7232086c41d2e805).

In addition, many depsolvers do multiple smaller transactions instead of one big mutha and this is not an issue for them. /me thinks it'd be wrong to reject, but a warning might be in order.

**Comment by ffesti** [comment]
Well, we should at least issue a warning that the package cannot be installed on an empty system.
This issue is kinda worsened by the fact that this will not create a dependency issue but rather an ordering problem that is more or less ignored up to the point where the script fails.

**Comment by pmatilai** [comment]
> This issue is kinda worsened by the fact that this will not create a dependency issue but rather an ordering problem that is more or less ignored up to the point where the script fails.

Um, what do you mean? It *is* a dependency issue, a package with /bin/sh (or similar) %pretrans scriptlet will fail in empty root like this:
```
[root@sopuli ~]# rpm -Uvh --root /srv/test /home/pmatilai/rpmbuild/RPMS/noarch/pretrans-0.1-1.noarch.rpm
error: Failed dependencies:
	/bin/sh is needed by pretrans-0.1-1.noarch
[root@sopuli ~]# 
```

**Comment by ffesti** [comment]
Well, but it will not fail if you install the bash package with it. Still the pretrans scriptlet won't work.

**Comment by pmatilai** [comment]
Yes it will, that's the whole point. If it doesn't, then we've broken something.

**Comment by pmatilai** [comment]
Nope, still works as expected...
```
[root@sopuli Packages]# rpm --root /srv/test -Uvh b/bash-4.4.19-2.fc28.x86_64.rpm g/glibc-2.27-8.fc28.x86_64.rpm g/glibc-common-2.27-8.fc28.x86_64.rpm n/ncurses-libs-6.1-4.20180224.fc28.x86_64.rpm n/ncurses-base-6.1-4.20180224.fc28.noarch.rpm f/filesystem-3.8-2.fc28.x86_64.rpm b/basesystem-11-5.fc28.noarch.rpm s/setup-2.11.3-1.fc28.noarch.rpm t/tzdata-2018d-1.fc28.noarch.rpm f/fedora-release-28-1.noarch.rpm g/glibc-langpack-en-2.27-8.fc28.x86_64.rpm f/fedora-repos-28-1.noarch.rpm f/fedora-gpg-keys-28-1.noarch.rpm l/libselinux-2.7-13.fc28.x86_64.rpm l/libsepol-2.7-6.fc28.x86_64.rpm p/pcre2-10.31-4.fc28.x86_64.rpm  /home/pmatilai/rpmbuild/RPMS/noarch/pretrans-0.1-1.noarch.rpm
warning: b/bash-4.4.19-2.fc28.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 9db62fb1: NOKEY
error: Failed dependencies:
	/bin/sh is needed by pretrans-0.1-1.noarch
```
This is what commit c0eb82dd1f2102f2b4899c1e7232086c41d2e805 is all about.

**Comment by jasontibbitts** [comment]
This would probably be better as an rpmlint check, except then it might be ignored.

Certainly from RPM's perspective, having a %pretrans scriptlet written in shell or anything else is perfectly valid.  Only a distro like Fedora which cares about every package being installable into an empty filesystem would want to reject it, and it would still be OK for someone building their own packages.  So even if an option/flag/magic macro existed, Fedora would have to think twice about setting it by default (though I think in the end we would want to do so, even if it means anyone building custom packages that doesn't care would have to turn it off manually).

Is there any part of the rpm-build process where a distro could hook in basic checks on scriptlets?  Would it be reasonable to have one?

**Comment by Conan-Kudo** [comment]
@jasontibbitts In Mageia and OpenMandriva, rpmlint is executed as a post-build check through rpmbuild itself, like so:

```rpmspec
%_build_pkgcheck_set /usr/bin/rpmlint -f %{_sourcedir}/%{name}.rpmlintrc
%_build_pkgcheck_srpm /usr/bin/rpmlint -f %{_sourcedir}/%{name}.rpmlintrc
%_nonzero_exit_pkgcheck_terminate_build 1
```

But you could configure anything, I suppose.

**Comment by ffesti** [comment]
Moved to rpmlint as https://github.com/rpm-software-management/rpmlint/issues/396
