### ISSUE TITLE
missing popt Requires in rpm.pc

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#724]
Looks like in generated rpm.pc is missing "Requires: popt".
In installed rpmlib.h is "#include <popt.h>".

**Comment by kloczek** [comment]
BTW do you know where is popt git repo?

**Comment by ignatenkobrain** [comment]
Well, technically it is there:

```
15:Libs.private: -lpopt -lrt -lpthread -llzma -ldb -lbz2 -lz   -llua -lm -ldl 
```

**Comment by pmatilai** [comment]
The superfluous include is removed now (commit 74033a316520aa7877f62e39296f293b7d4493e0), thanks for pointing that out.
Linking to popt is entirely optional for API users though, so the private libs is the right place for it.

**Comment by pmatilai** [comment]
> BTW do you know where is popt git repo?

As of roughly 15 minutes ago, thanks to @Conan-Kudo 's cvs conversion effort, there is one now here: https://github.com/rpm-software-management/popt

**Comment by kloczek** [comment]
BTW it would be really good to make new popt release :)

**Comment by Conan-Kudo** [comment]
That's probably going to be a while. We'll need to figure out what the distros are doing to popt, clean them up, and integrate them into the git repo before we consider making a new release.

**Comment by pmatilai** [comment]
For the time being, our plans with popt are limited to giving it a home and a place where people can file bugs and submit patches and see what happens.
