### ISSUE TITLE
Possible regression: BUILDSTDERR: double free or corruption (fasttop)

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#742]
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/fapolicyd-0.8.9-2.fc31.ppc64le
Wrote: /builddir/build/RPMS/fapolicyd-debugsource-0.8.9-2.fc31.ppc64le.rpm
Wrote: /builddir/build/RPMS/fapolicyd-0.8.9-2.fc31.ppc64le.rpm
Wrote: /builddir/build/RPMS/fapolicyd-debuginfo-0.8.9-2.fc31.ppc64le.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.N9kdZs
+ umask 022
+ cd /builddir/build/BUILD
+ cd fapolicyd-0.8.9
+ /usr/bin/rm -rf /builddir/build/BUILDROOT/fapolicyd-0.8.9-2.fc31.ppc64le
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
BUILDSTDERR: double free or corruption (fasttop)
Child return code was: -6
```

This has happened with fapolicyd on ppc64le and i686. https://koji.fedoraproject.org/koji/taskinfo?taskID=35461042

**Comment by ignatenkobrain** [comment]
And with deltarpm on i686.

**Comment by ignatenkobrain** [comment]
After many hours, I can confirm it is related to the generation of packages in parallel. I think this is something related to this:

* `packageBinaries` calls into `packageBinary` in parallel
* `packageBinary` calls into `processScriptFiles`
* `processScriptFiles` calls into `addFileToTag`
* `addFileToTag` is calling `rpmPushMacro(spec->macros, "__file_name", NULL, fn, RMIL_SPEC);`

I suppose that gets executed multiple times in parallel breaking some of following calls..


I don't know =(

**Comment by pmatilai** [comment]
Ok, thanks for all the hunting and testing!
That it's only happening on i686 and ppc64le is trying to tell me something but not sure what that something is.

I would be surprised if it's that macro pushing and popping as that's one of the rare places that *are* actually thread-protected in rpm, I'd expect it to be something in the build side (a pointer in the spec maybe) where things are... well, as I said in the commit message introducing it, walking on thin ice.

**Comment by ignatenkobrain** [comment]
I think after all it happens everywhere. It is just more often on those arches

**Comment by pmatilai** [comment]
Ok, that'd make more sense. Do you have a pointer to a build that failed similarly on some other arch?

**Comment by ignatenkobrain** [comment]
x86_64 - https://koji.fedoraproject.org/koji/taskinfo?taskID=35463720
aarch64 - https://koji.fedoraproject.org/koji/taskinfo?taskID=35463728
armv7hl - https://koji.fedoraproject.org/koji/taskinfo?taskID=35463725

I think I just did not manage to get it failed on s390x :)

**Comment by pmatilai** [comment]
Okay, that removes any doubts then.

**Comment by pmatilai** [comment]
Hmm, looking at it closer, the macro thing does indeed seem suspicious. Even if the macro-side thread protection was bugfree, the line number thing is a global value and multiple threads changing it concurrently wouldn't make *sense* at all.

**Comment by pmatilai** [comment]
For the record, commit afe4989ca88d8e8fe9317f696f4a66aa7ae37498 was required too to really fix this.
