### ISSUE TITLE
How to enforce rpm install and upgrade to fail if rpm is not signed

### ISSUE THREAD

**Issue by Ambtripa** [rpm-software-management/rpm#750]
Is there a way to force rpm -i or -U to fail if rpm is not signed with gpg key? if not how to enable it.

**Comment by pmatilai** [comment]
Starting with rpm 4.14.2, yes. See https://rpm.org/wiki/Releases/4.14.2

**Comment by Ambtripa** [comment]
Which option i have to use to enforce install to fail if rpm is not signed.
