### ISSUE TITLE
Parallel rpmfc thread-safety - libmagic may fork helpers

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#756]
When using MAGIC_COMPRESS (as rpmfc does), libmagic may fork helper executables to deal with decompressing files. Since commit 41f0e214f2266f02d6185ba11f797716de8125d4 we are running the classifier in threads, and mixing fork() and threads tends to mean trouble.

Filing this ticket as a reminder to look into and deal with it one way or the other: use of MAGIC_COMPRESS dates back to 2009 (commit c3770c9404ffa2fcfbe0869dd7fbdb73466a637a), predating the current customizable classifier and availability of path based rules. Looking into compressed files was necessary for at least font provide extraction but we could trivially use paths for that now instead.

**Comment by pmatilai** [comment]
For the record, there have been some reports of builds hanging during classification on systems with large number of CPUs using file 5.36 which where fixed by updating to 5.37. Another workaround is to set %_smp_build_nthreads to a smaller number, ultimately 1 to make the whole classification run in serial as it always used to.

**Comment by kanavin** [comment]
TBH, this seems like a serious enough issue in 4.15.0 release, that parallel file classification should be simply disabled for the time being, with a 4.15.0.1 issued to include that.

**Comment by pmatilai** [comment]
TBH, the thought of reverting the whole damn threading business has crossed my mind more than once by now, it is (quite expectedly) proving painful. I've resisted the temptation so far...

The thing is that this hasn't been an issue on Fedora *at all*, AFAIK. If we just disable without understanding where the difference comes from, it'll still be there the next time we try enabling it.
Instead it's the parallel binary package creation that has been the source of problems there, and I've been considering disabling that on 32bit architectures entirely.

**Comment by pmatilai** [comment]
Anyway, there *will* be a bugfix release to 4.15.x soonish, there's a handful of fairly critical things that needs addressing. I mean, it is a .0 release...

**Comment by kanavin** [comment]
I dug a bit deeper: the issue happens when libmagic calls out to external executables, which isn't implemented in a thread-safe way, and locks up. Enabling internal compression support (done via linking to libraries) makes the issue go away.

**Comment by pmatilai** [comment]
Yup, at least one such issue has just been addressed here: https://github.com/file/file/commit/81f15c2b

**Comment by pmatilai** [comment]
Based on internal testing, the above seems to have cured the remaining cases, so considering closed.
