### ISSUE TITLE
RFE: rpmbuild -br --i-really-want-src-rpm

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#760]
I have some scripts which operate on packages to generate their (build)dependency tree for Fedora Modularity stuff. It relies on normal binary and source RPMs for dependency information. However, with dynamic BuildRequires, I need a way to rebuild sourcerpms with some macros defined. And I found out that there is no way to get src.rpm with dynamic buildrequires without installing them.

So I had to do something like

```diff
diff --git a/build/build.c b/build/build.c
index dec7d9608..c1f28b8f5 100644
--- a/build/build.c
+++ b/build/build.c
@@ -213,10 +213,12 @@ static int doBuildRequires(rpmSpec spec, int test)
        *packageDependencies(spec->sourcePackage, RPMTAG_REQUIRENAME),
        spec->sourcePackage->header);
 
+#if 0
     parseRCPOT(spec, spec->sourcePackage,
               "rpmlib(DynamicBuildRequires) = 4.15.0-1",
               RPMTAG_PROVIDENAME, 0, RPMSENSE_FIND_PROVIDES | RPMSENSE_RPMLIB,
               addReqProvPkg, NULL);
+#endif
     rc = RPMRC_MISSINGBUILDREQUIRES;
 
  exit:
@@ -305,6 +307,8 @@ static rpmRC buildSpec(rpmts ts, BTA_t buildArgs, rpmSpec spec, int what)
                (rc == RPMRC_MISSINGBUILDREQUIRES))
            rc = doCheckBuildRequires(ts, spec, test);
        if (rc == RPMRC_MISSINGBUILDREQUIRES) {
+           rc = RPMRC_OK;
+#if 0
            if (what & RPMBUILD_DUMPBUILDREQUIRES) {
                /* Create buildreqs package */
                char *nvr = headerGetAsString(spec->packages->header, RPMTAG_NVR);
@@ -318,6 +322,7 @@ static rpmRC buildSpec(rpmts ts, BTA_t buildArgs, rpmSpec spec, int what)
            } else {
                rc = RPMRC_OK;
            }
+#endif
        } else if (rc) {
            goto exit;
        }
```

and use `rpmbuild -rr -D "_module_build 1" --nodeps /path/to/srpm` and it does what I need.

So what I want is to say "I am expert, I know src.rpm will have all dynamic dependencies, just give me src.rpm and not buildreqs.nosrc.rpm.".

**Comment by ignatenkobrain** [comment]
I had conversation yesterday with @ffesti over IRC about this and we need to add something like `--noverifydeps`.

I'll send PR this week.

**Comment by pmatilai** [comment]
What's wrong with --nodeps, which we already have?
If it's not suitable for whatever reason, you'll need to come up with something better than --noverifydeps as the name.

**Comment by ignatenkobrain** [comment]
@pmatilai `-br --nodeps` generates buildreqs.nosrc.rpm which indicates that there are some generated deps, but list might be incomplete. But in some cases when you know what you are doing, you want to tell RPM, I have all dependencies, neither I want you to check it and I really want src.rpm, not buildreqs.nosrc.rpm. Changing behavior of `--nodeps` is bad, because that would mean, there is no way to generate buildreqs.nosrc.rpm for mock for example.

**Comment by pmatilai** [comment]
I'm not fond of these --do-foo-except-in-this-one-special-case-do-bar style options, they rarely make sense in the big picture.
One possibility might be reusing --force for the purpose. It's wired to something else but maybe it could be special-cased in combination of -br --nodeps. Or if that isn't feasible, I'd rather have --force-srpm or such which might be applicable to more cases than just this.

**Comment by ignatenkobrain** [comment]
@pmatilai true, Ithink --force would make sense for this.

**Comment by pmatilai** [comment]
Yeah, --force as a cli-switch makes sense for the case, it's just the existing API-side wiring to RPMSPEC_FORCE that has other side-effects which you'd not want for this case, so whether it's reasonably straightforward or even possible to use it for this purpose is another question.

**Comment by ignatenkobrain** [comment]
I think using RPMSPEC_FORCE is fine for this case because normally people would not do it. Only if they know what they are doing.
