### ISSUE TITLE
RFE: Make it easier to use new rpmbuild features

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#761]
`%patchlist` is one of these things. It does not affect final binary rpm, but is very convenient in spec file.

However, you really need to wait until all distros would get this feature before using it.

It would be nice if rpmbuild would have some way of defining minimum compatible version of RPM and produce binary packages according to them. Some kind of splitting rpmbuild to its own thing.

I understand that this is not something what can be done in few months, but this would be very helpful in the long-term.

**Comment by pmatilai** [comment]
Binary package compatibility is tracked via rpmlib() dependencies, and those depend on settings used by the build environment (such as payload compression flags) and features used by the package (such as rich dependencies or file triggers), and if a package relies on features available in a new rpm then rpm cannot magically make it work with older ones.  If you don't use the new package-level features you can still relatively easily build packages that are installable on rpm 4.4.x and older.

Features that are solely rpmbuild-side are quite rare, almost always the build-side features reflect something in the runtime-side of things. Splitting rpmbuild to a separate project is just not going to happen, its way way too painful with little gain. With rpm deployments, a fair amount of patience is required ;)
