### ISSUE TITLE
rpm cannot parse conditional: error: unmatched (

### ISSUE THREAD

**Issue by hramrach** [rpm-software-management/rpm#775]
%if 1 && ( 2 || 
                3 )
%endif

error: unmatched (
error: /home/michal/kernel-source/test.spec:1: bad %if condition

%if 1 && ( 2 || \\
                3 )
%endif

error: parse error in expression
error: unmatched (
error: /home/michal/kernel-source/test.spec:2: bad %if condition

%if 1 && ( 2 || 3 )
%endif

<no errors>

Clearly the line continuation \ moves the error to the next line but does not allow parsing the condition.

**Comment by pavlinamv** [comment]
Please, should the second %if look like this (I added \ at the end of the first line)?

%if 1 && ( 2 || \\
3 )
%endif

**Comment by hramrach** [comment]
There should be only one \ but github does not display it.

**Comment by pavlinamv** [comment]
Thank you

**Comment by pavlinamv** [comment]
Fixed in commit 5f4fdce3041b80ef26e3a87db07ecdbd2041a9b2

**Comment by hramrach** [comment]
Thanks for the fix. The 4.14.2.1 version I use does not use the lineType classification. I suppose this will be fixed in 4.15. Due to non-trivial amount of custom macros upgrading is going to take a while.
