### ISSUE TITLE
rpm and rpmbuild manpages assume vendor=redhat

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#779]
The rpm/rpmbuild manpages contain ` /usr/lib/rpm/redhat/rpmrc` and `/usr/lib/rpm/redhat/macros` as default path elements.

**Comment by Conan-Kudo** [comment]
It probably makes sense to make autotools patch this with `RPMCANONVENDOR` at configure time...

**Comment by pmatilai** [comment]
Simple(r) fix proposal in PR #850

**Comment by mlschroe** [comment]
Fine with me ;)
