### ISSUE TITLE
Add a %cnl (continue next line) marker

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#787]
Sometimes rpm variables need contain long lines of things
https://src.fedoraproject.org/rpms/golang-sigs-k8s-kustomize/blob/master/f/golang-sigs-k8s-kustomize.spec#_20

and reviewers, prompted by rpmdevtool, will ask to break those lines to less than 80 columns

Unfortunately there is no easy way to break this kind of line without introducing line breaks in the variable content, that will then break shell and rpm macro code, and require the rewrite of basic macro code like `%if "%{?foo}" != ""`  into exotic contructs
https://src.fedoraproject.org/rpms/redhat-rpm-config/c/b8797dcd025c34ee9495c30ad86c193445b63df9

it would be nice if there was a marker that told the rpm parser a line continues on the next line, but the linebreak is not significant.

(`%{shrink:}` will remove the linebreak but also munge other whitespace in the line, so it does not work as a solution)

**Comment by pavlinamv** [comment]
You can use %{shrink:...} this way:
```%global godocs         docs examples code-of-conduct.md %{shrink:\```
```                       }README.md```
"godocs" will be defined:
```xdocs examples code-of-conduct.md README.md```

**Comment by nim-nim** [comment]
@pavlinamv: that should work, thanks for the idea!

However, it is so smart and unintuitive, I doubt many will thing about it. A clean marker (even if it's just an alias) would be better. Is that something that could be added to official rpm macros or do I need to push it `redhat-rpm-config` side?

**Comment by nim-nim** [comment]
@pavlinamv scrap it, it can not be aliased just within a macro file, because it depends on the next line starting just after the marker. Or is there a way to eat this next line safely?

**Comment by pavlinamv** [comment]
I am sorry, but I do not know any way how to do it.

**Comment by mlschroe** [comment]
Here's another solution:
```
%global godocs docs examples code-of-conduct.md %dnl\
README.md
```
This uses the new %dnl macro to eat away the newline generated by the trailing `\`.

**Comment by ffesti** [comment]
Looks like there are solutions already there. While they are not that beautiful it still beats adding another special case.
