### ISSUE TITLE
pkgconfigdeps.sh and versions with spaces

### ISSUE THREAD

**Issue by jasontibbitts** [rpm-software-management/rpm#789]
I noticed a package (verilator) in Fedora that provides "2018-03-17".  Turns out that it installs a pkgconfig file which contains `Version: 3.922 2018-03-17`, which causes `pkgconfigdeps.sh -P` to output `pkgconfig(verilator) = 3.922 2018-03-17`.

Looking through various documents about pkgconfig files, I don't see where spaces are forbidden in a version string.  So I'm not really sure if this is a bug in the software, the packaging, or pkgconfigdeps.sh.

**Comment by ignatenkobrain** [comment]
This is awful... And yes, I don't see any place which would say that spaces are forbidden. However, I don't know how pkgconf or such would compare such versions... @kaniini?

**Comment by kaniini** [comment]
spaces are not valid in the version string.  this will parse as 3.922 in comparisons.

in a dependency list,

```
Depends: verilator = 3.922 2018-03-17
```

will parse as:

```
[
  ["verilator", "=", "3.922"],
  ["2018-03-17"]
]
```

hope that helps.

**Comment by kaniini** [comment]
I think it may make sense to change pkgconf to explicitly strip anything after a whitespace character in the version.  that would solve this issue and also make sure other automatic generators don't do something bad when they encounter something ridiculous like this.  I'll release 1.6.3 today with such a change if you all agree?

**Comment by Conan-Kudo** [comment]
That sounds good to me.

**Comment by kaniini** [comment]
pkgconf 1.6.3 will warn when malformed versions are provided:

```
kaniini@nanabozho:~/pkgconf$ ./pkgconf --validate tests/lib1/malformed-version.pc 
tests/lib1/malformed-version.pc:2: warning: malformed version field with whitespace, trimming to [3.922]
```

since this is a problem with malformed files, and we have a fix pending in pkgconf, i think we can close this ticket

**Comment by jasontibbitts** [comment]
Thanks, all.  In the meantime the bizarre extra Provides: bit doesn't really hurt anything.

One interesting side effect is that I'm not sure anything in Fedora would actually ever validate any of the installed pkgconf files.  I wonder if this is a reasonable candidate for a brp script.  (It occurs to me that the same could be said for desktop files, instead of requiring that it be done manually in the specfiles as is currently done.)  Would `pkgconf --validate` exit nonzero in this case?  Is there a way to make it do so?  It's probably better not to avoid parsing the output.

**Comment by ignatenkobrain** [comment]
FYI: I built new version of pkgconf in Rawhide.

**Comment by kaniini** [comment]
pkgconf doesn't exit nonzero on warnings.  just on fatal errors.  I could add a flag to make --validate stricter.

**Comment by pmatilai** [comment]
Hmm, we could probably quite easily support per-generator customizable character blacklist. That could be used to catch whitespace if/when it doesn't make sense for eg pkgconfig.

**Comment by ffesti** [comment]
Looks like this got  fixed in pkgconf as far as rpm is concerned. Closing.
