### ISSUE TITLE
rpm --rebuilddb outputs error on NFS

### ISSUE THREAD

**Issue by ChenQi1989** [rpm-software-management/rpm#796]
On NFS, 'rpm --rebuilddb' would output an error and leave an empty directory /var/lib/rpmold.xxxx in system.

error: could not delete old database at /var/lib/rpmold.335

Although the exit status is 0, I think we should do something about it.

Maybe we should move the /var/lib/rpmold.xxx/.nfsXXXX file to another place before before the rmdir operation?

**Comment by ChenQi1989** [comment]
I'd like to know if rpm community treats it as a bug or a desired behaviour.

**Comment by pmatilai** [comment]
I don't think this is "desired behavior". The thing is, rpmdb on NFS has never been really supported in the first place.

**Comment by ffesti** [comment]
Looks like these .nfsXXXX files are from deleted but not yet closed files: http://nfs.sourceforge.net/#faq_d2
We'd need to check if there is a easy way to get this file closed before the rmdir.

**Comment by ffesti** [comment]
This may only be a symptom of an actual bug as all files to the old db should actually get closed.

**Comment by ffesti** [comment]
If this is an issue with `rpm --rebuilddb` not closing some file properly, we should fix that. Otherwise we probably won't put much work into the bdb backend that it on its way to be replaced.

**Comment by ffesti** [comment]
Fix by 38c03ddb18e86c84d89af695f72442d8365eb64e

**Comment by pmatilai** [comment]
This was fixed in #1313 but forgotten to close. 
Thanks for reporting!
