### ISSUE TITLE
DynamicBuildRequires: error: Dependency tokens must begin with alpha-numeric, '_' or '/': [last line of spec]

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#801]
Here is a somewhat weird error with dynamic buildrequires on Fedora 31. The reproducer is a bit complicated, sorry about that.

1. Install mock that knows how to loop over DynamicBuildRequires - you can build it from here: https://src.fedoraproject.org/rpms/mock/pull-request/8 ([rawhide scratchbuild](https://koji.fedoraproject.org/koji/taskinfo?taskID=36608730), [f30 scratchbuild](https://koji.fedoraproject.org/koji/taskinfo?taskID=36608769))

2. Download [pyproject-rpm-macros-0-4.fc31](https://koji.fedoraproject.org/koji/buildinfo?buildID=1336950) (only in the f31-rebuild tag for now)

3. Initialize Fedora rawhide mock, install package from step 2 (pyproject-rpm-macros) into the mock.

4. Build the SRPM from the enclosed spec file in the mock from step 3 (get sources from the Source URL):

```
$ mock -r fedora-rawhide-x86_64 --no-clean --no-cleanup-after --enablerepo=local ~/rpmbuild/SRPMS/python-pluggy-0.12.0-1.fc30.src.rpm
```

```spec
%global pypi_name pluggy
Name:           python-%{pypi_name}
Version:        0.12.0
Release:        1%{?dist}
Summary:        The plugin manager stripped of pytest specific details

License:        MIT
URL:            https://github.com/pytest-dev/pluggy
Source0:        %{pypi_source}

BuildArch:      noarch
BuildRequires:  pyproject-rpm-macros

%description
%{summary}.


%package -n python3-%{pypi_name}
Summary:        %{summary}
%{?python_provide:%python_provide python3-%{pypi_name}}

%description -n python3-%{pypi_name}
%{summary}.


%prep
%autosetup -p1 -n %{pypi_name}-%{version}


%generate_buildrequires
%pyproject_buildrequires -r


%build
%pyproject_wheel


%install
%pyproject_install


%files -n python3-%{pypi_name}
%doc README.rst
%license LICENSE
%{python3_sitelib}/%{pypi_name}/
%{python3_sitelib}/%{pypi_name}-%{version}.dist-info/

```

The build.log has:

```
error: line 46: Dependency tokens must begin with alpha-numeric, '_' or '/': /usr/lib/python3.7/site-packages/pluggy-0.12.0.dist-info/

error: line 46: Dependency tokens must begin with alpha-numeric, '_' or '/': /usr/lib/python3.7/site-packages/pluggy-0.12.0.dist-info/

error: line 46: Dependency tokens must begin with alpha-numeric, '_' or '/': /usr/lib/python3.7/site-packages/pluggy-0.12.0.dist-info/

error: line 46: Dependency tokens must begin with alpha-numeric, '_' or '/': /usr/lib/python3.7/site-packages/pluggy-0.12.0.dist-info/
```

In the last run of `%generate_buildrequires` before it goes to `%build`. The errors seem to be nonfatal. The `/usr/lib/python3.7/site-packages/pluggy-0.12.0.dist-info/` line is the last line of spec (expanded).

**Comment by ignatenkobrain** [comment]
Interestingly, I can't reproduce outside of mock…
