### ISSUE TITLE
_missing_doc_files_terminate_build may be ignored

### ISSUE THREAD

**Issue by tcely** [rpm-software-management/rpm#807]
https://github.com/rpm-software-management/rpm/blob/c7e0b61c05878868300653d5892425c6c41fdba0/build/files.c#L2346-L2375

https://github.com/rpm-software-management/rpm/blob/c7e0b61c05878868300653d5892425c6c41fdba0/build/files.c#L2365

https://github.com/rpm-software-management/rpm/blob/c7e0b61c05878868300653d5892425c6c41fdba0/build/files.c#L2373
Given lines 2365 and 2373. How can `rc` be non-zero when every `cp` command has ` ||:` appended?

**Comment by pmatilai** [comment]
Thanks for the report. Fix proposed in PR #849
