### ISSUE TITLE
Provide function for $optflags manipulation

### ISSUE THREAD

**Issue by marxin** [rpm-software-management/rpm#814]
As the follow up of https://github.com/rpm-software-management/rpm/pull/813
I would like to have rpm macros that will do operations on `%optflags`:

Example:
- `%filter-out-optflags '-flto=auto'`
- `%append-if-to-optflags '-flto=auto' '-ffat-lto-objects'`

I found the example how currently we do it e.g. in MozillaFirefox:
```
%{expand:%%global optflags %(echo "%optflags"|sed -e s/i586/i686/) -march=i686 -mtune=generic}
```

Which is quite ugly and I bet multiple packages suffer from the same issue. Gentoo has a reasonable API for that:
https://devmanual.gentoo.org/eclass-reference/flag-o-matic.eclass/index.html

@pmatilai Is it realistic to come up with the functionality?

**Comment by marxin** [comment]
Adding @scarabeusiv

**Comment by marxin** [comment]
and @DimStar77

**Comment by scarabeusiv** [comment]
I can imagine 2 operations:

`%remove_optflags 'undesirable'`
`%replace_optflags 'oldval' 'newval'`

Which would cover your usecases (because appendif is mostly replace if you also add the oldval to newval)

**Comment by scarabeusiv** [comment]
Question is how much pain it would be to create the flagomatic eclass in m4....

**Comment by marxin** [comment]
> `%remove_optflags 'undesirable'`
> `%replace_optflags 'oldval' 'newval'`

Then we can have just the simple one. Following works for me:
```
$ rpm --define "%optflags -flto=auto -O2" --define "%replace_optflags() %global optflags %(echo %optflags | sed s/%{?1}/%{?2}/)" --eval '%replace_optflags "-flto=auto"' --eval 'optflags=%optflags'

optflags= -O2
rpm --define "%optflags -flto=auto -O2" --define "%replace_optflags() %global optflags %(echo %optflags | sed s/%{?1}/%{?2}/)" --eval '%replace_optflags "-O2" "-O3"' --eval 'optflags=%optflags'

optflags=-flto=auto -O3
```

Thoughts?

**Comment by voxik** [comment]
I would probably prefer `add`/`remove` combination, which would be more work on one side, but IMHO better then "replace by nothing" to remove flag.

But I like the idea.

**Comment by ffesti** [comment]
This is much too specialized. May be some generic way to alter predefined macros in the spec...
