### ISSUE TITLE
Add builtin macro %undefine_all 

### ISSUE THREAD

**Issue by pavlinamv** [rpm-software-management/rpm#820]
A builtin macro 
```%undefine macro_name``` 
removes the last defined _'macro_name'_ from defined macros. But it still leaves all older definitions of the macro _'macro_name'_. So as @pmatilai wrote in #115 - "macros stack so undefining doesn't guarantee said macro actually goes away". 

Thus I think that it will be usefull to have a builtin macro that undefines all defined macros with the particular name. So after using it, no macro with the chosen name remains.

I am not sure regarding the name of the builtin macro.

**Comment by pmatilai** [comment]
The thought has crossed my mind too, but there's a reason such a thing is not implemented: it breaks the stack semantics, which various parts of rpm rely on.

**Comment by pavlinamv** [comment]
Please, how it breaks the stack semantics?

**Comment by pavlinamv** [comment]
> Please, how does it break the stack semantics?

I am asking because I think that it is easy to implement such a builtin macro.
E.g. popMacro() can be changed such that it returns 1 if an macro was deleted and 0 if no macro was deleted. After that it will be easy to call popMacro() in some function similar to doUndefine() until popMacro() returns 0.

**Comment by pmatilai** [comment]
I gave you some hints already, I'm not going to spell it all out for you, why don't you think about it by yourself a bit?

 It'd indeed be trivial to implement, and looks like an easy solution to a common problem on first sight, but in the bigger picture such an operator would be harmful to rpm in more than one way. I can think of 3-4 offhand.
