### ISSUE TITLE
Cannot leave comments after %endif

### ISSUE THREAD

**Issue by ernestask** [rpm-software-management/rpm#829]
https://github.com/rpm-software-management/rpm/pull/625 broke a rather reasonable use case, i.e.

```
%if %{with foo}
...
%else # with foo
```

Not even our friendly neighborhood https://github.com/rpm-software-management/rpm/commit/44180fc7400ea8e67a13c5581459ad13f1d14103 can be used.

What would be the proposed replacement for that, one that doesn’t disconnect the macro with the comment?

**Comment by pavlinamv** [comment]
From Fedora documentation [1]: "_To include comments in the spec file, use a # character at the start of the line._" 
So the text "# with foo" in line
```%else # with foo```
is not a valid comment. If you need to use a comment near %else, you can write e.g.:

``` 
%if %{with foo}
...
%else
# with foo
```

[1] https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/Packagers_Guide/chap-Packagers_Guide-Spec_File_Reference-Comments.html

**Comment by ernestask** [comment]
But that’s just Fedora documentation, not RPM documentation, so it’s really you who sets the restrictions, because you own the parser.

And notice how I mentioned not disconnecting the comment, because, if you do that, you introduce additional overhead when moving/removing. One has to be more careful to not leave a stray `# with foo` comment without an `%endif` macro to accompany it.

Regardless, we still have the `%dnl` macro, but now we’re getting into the territory of special-casing things.

**Comment by ernestask** [comment]
Okay, my bad here. I was getting build errors, but seems that it’s because a test was failing prior. The output confused me.

**Comment by mmathesius** [comment]
I'd really like to see this addressed.

I recently started getting such warnings from a package spec I maintain. It has several levels of nested `%if`s and cases where the `%if` and corresponding `%else`/`%endif` are separated by many lines. It's really helpful to be able to match up the conditionals with a simple connected comment. Even the C source code for the spec parser that is reporting this warning makes use of a [comment on an `#endif` line](https://github.com/rpm-software-management/rpm/blob/0488fdc927e6d31a0af55646fe51effe9592cb26/build/parseSpec.c#L813)!

Also, note that the above referenced Fedora documentation describing spec file comments goes on to mention "inline comments"--so somebody was thinking about comments that didn't start at the beginning of a line.

**Comment by ernestask** [comment]
To be fair, the C grammar is such that the comments are completely discarded by the lexer, if I’m not mistaken. However, I could not find any official formal grammar for spec files, so I’m thinking that it’s just cobbled together to make things work. The problem is exacerbated by shell commands in certain sections, which allow you to, say, create an ad-hoc shell script with a shebang. Is that a comment as far as the lexer/parser/whatever is concerned? Seems rather context-dependent, but there might be more corner cases like this.

**Comment by pmatilai** [comment]
Rpm has only ever supported comments at the beginning of a spec line, ie *lines starting with #*, but like @ernestask points out, much of the spec is actually shell-script where comments are allowed anywhere in the line so it's easy to get mixed up with expectations.

Anything else appearing to work as a comment has been accidental, as in: bugs in the spec parser, 
see the discussion in #625 for a freak show of side-effects that this particular bug has allowed. Also note that what was added is just a warning, if a build is failing it's failing for some other reason.

Eliminating such quirks is in everybody's best interest, but I agree in this case it outlaws a useful pattern. The constructive solution to the problem would be supporting spec #-comments at arbitrary positions, just like the shell does.

**Comment by pavlinamv** [comment]
> The constructive solution to the problem would be supporting spec #-comments at arbitrary positions, just like the shell does.

Supporting spec #-comments at arbitrary positions can potentially cause some problems. That is why I looked  into spec files and search for occurrences of #. There are several types of interesting lines:

1/ **#** used in define (in quotes or before backslash, ...)
```
   %define coolkey_module "CoolKey PKCS #11 Module"
   %global auto_register_macro_post() # create it if it doesn't already exist \
```

2/ **#** used in a script that does not denote a comment
```
sed -i -e '/^#!/ c #!%{__perl}' bin/podspell
%{_bindir}/echo -e "\e[101m -=#=- Tests disabled -=#=- \e[0m"
```

3/ **#** used in a changelog:
```   
Ticket #321 - krbExtraData is being null modified and replicated on each ssh login
```

**Comment by pmatilai** [comment]
Never said it'd be easy to retrofit. But basically
1) Macros are handled by the macro engine, not spec. The macro body is always literal and must remain so, so that auto_register_macro_post() macro would essentially emit a #-comment line.
2) Comments in build-scriptlets are shell comments, not rpm's not concern.
3) Do comments belong to changelog at all? I don't think so... we could probably simply disable them there entirely and nobody would notice.

**Comment by ernestask** [comment]
As far as 3 goes, does anything other than text belong there?

**Comment by pavlinamv** [comment]
3. agree with @pmatilai, changelog entries can be without comments.

**Comment by pmatilai** [comment]
After much procrastination and head-scratching: sanity requires that comments after %endif must be allowed, just like they're allowed in C pre-processor after which the %if-%endif support in spec is largely modelled. And if we allow them after %endif we generally need to allow them elsewhere too, so this opens the door for generally supporting comments outside beginning of line.

**Comment by ernestask** [comment]
Since this had somewhat become stuck - where would one start implementing this/what potential pitfalls are there in making this happen?

I could probably re-read the thread and get enough context, but maybe something changed in the meantime.
