### ISSUE TITLE
Ternary op discussions

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#852]
Here are some points to discuss:

1) The ternary op currently uses the same logic as rpmExprBool to evaluate if the condition is true or not. But the other logical operators (!, &&, ||) only work with integers. We should make this consistent, either by changing ternary to only accept integers or by changing the other ops to also accept strings.

2) There probably should be a test that makes sure the true and false part of a ternary op have the same type. I.e. the `%test ? 2 : "foo"` should not be allowed.

3) Does it make sense to have variants with missing parts?
```

%foo ? %bar         Use alternate value
                    Return %bar if %foo is true, otherwise 0 or ""
                    (probably not so interesting, it's easy to write `: 0` or `: ""`)
%foo ?: %bar        Use default value
                    Return %foo if %foo is true, otherwise %bar
```

**Comment by mlschroe** [comment]
(We can also go the perl/python/... way and change the || operator so that it no longer returns a bool, but the first true term. I.e. `"%foo" || "bar"`.)

**Comment by pmatilai** [comment]
As for 3), I think both variants would be kinda nice to have.
In particular, people are used to ```%foo ? %bar``` from macros, and might be even a bit surprised if that doesn't work. And default value case of ```%foo ?: %bar``` is quite a common pattern, so why not?

**Comment by mlschroe** [comment]
With the referenced pull request you can use && and || for alternate/default:

`%foo && %bar` is `%bar` if `%foo` is true, otherwise `0`
`%foo || %bar` is `%foo` if `%foo` is true, otherwise `%bar`

I think people are somewhat more used to this than the degenerate `?` and `?!` forms that aren't used in any other programming language.

**Comment by pmatilai** [comment]
Kinda funny, I'm not familiar with that form at all.  Not that it means much, except that maybe I'm not the best judge here :)

I can certainly live without ```?``` and ```?:```, for the latter I know gcc supports it but I don't recall ever using it. So it's not exactly of life-support importance...
