### ISSUE TITLE
Phasing out header+payload digests and signatures

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#863]
This came up in #861, but deserves a topic of its own, and also needs to be laid out where people can see it:

The so-called "v3" header+payload digests and signatures in rpm have been on their slower-than-sloth way out ever since header-only digests/signatures were added in rpm v4 around the turn of the millenium, but without them there hasn't been any means to verify the payload without unpacking it, and so they've lingered on.

rpm 4.14 added a separate digest on the compressed payload. Unlike the v3 elements, the payload digest is stored in the immutable main header instead of signature header, so it's guarded by header-only digests/signatures making modification non-trivial and with signed packages, impossible. So there's now the means to perform strong verification of both the header and the payload independently of each other.

This means we can finally start phasing out the v3 digests and signatures for real. For one, it means that signing could technically be done without looking at the payload at all, making it much faster. It would also help the deltarpm case as discussed in #861. I'd like to say "simpler code" too, but rpm probably needs to carry support for the v3 stuff for another decade more for compatibility reasons, so that's not right around the corner. We have to start someplace though, and I think that something should be changing rpmsign only create header-only signatures by default, and add a cli-switch to enable them for those who need it.

I'm sure I'm forgetting half a dozen things from my braindump, but it's a start at least.
Thoughts?

**Comment by mlschroe** [comment]
The open build service project uses the pkgid (aka hdr+payload md5) as package identifier.

**Comment by mlschroe** [comment]
There's also the well-known `rpm -q --pkgid XXX` query option ;)

**Comment by pmatilai** [comment]
Right, md5 is still used for various other things too (I think koji uses it too for similar id purposes) because it's the only thing that absolutely universally is there, and probably will need to remain for a long time still. Dropping the signatures is the more interesting and beneficial case though - md5 can be recalculated anytime, but not so with signatures (thinking about the compressed/uncompressed payload case)
