### ISSUE TITLE
Default to 64bit size tags in headers

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#864]
Another topic inspired by the deltarpm discussion in #861 :

Rpm has supported 64bit file sizes since 4.6.0, but has only used them when actually required to do so in the name of backwards compatibility and minimal disruption. The downside is that since few packages are big enough to actually invoke this path, all sorts of pesky bugs lurk in and near the rarely crossed 32/64 bit border. What makes it worse is when the sizes mix and match, for example a large package requiring 64bit payload sizes can still consist of individual files using 32bit sizes. And when files/packages grow that one final byte over the limit, a number of these things will suddenly use different tags. I haven't looked but I wouldn't be surprised if deltarpm doesn't handle that case, and at any rate it'd probably be happier without having to handle it.

It's 2019, I think we could afford 64bit sizes everywhere.

There would of course need to be configurables to enable 32bit sizes for backwards compatibility for those who need it, but every rpm version released in the last 10 years can handle this. Only rpm <= 4.4.x cannot, and that means the largely EOL era of RHEL-5 and contemporaries.

Thoughts?

**Comment by ignatenkobrain** [comment]
+1 to default to 64bit size tags.

**Comment by pmatilai** [comment]
Just for reference: https://rpm.org/devel_doc/large_files.html

**Comment by mlschroe** [comment]
I don't think deltarpm uses size information from the header.

So you want to only put the 64bit versions in the header and add a macro check so that it puts in both the 32bit and the 64bit versions for people that need compatibility?

**Comment by mlschroe** [comment]
Ok, it does use the file sizes. No 64bit support for files at the moment, though.

**Comment by pmatilai** [comment]
The compat option cannot have any 64bit tags, because rpm <= 4.4.x barfs headers containing them. So the compat option would be either: do what we do now and only use 64bit sizes when required, or simply always use 32bit tags and error out if 64bit sizes are required. The latter might actually be a more constructive behavior for those seeking compatibility at this point.

**Comment by ffesti** [comment]
Dependency Flags have nearly all 32 bits used up. So converting them to 64 would also make them future prove.

**Comment by pmatilai** [comment]
Done in #3017
