### ISSUE TITLE
Arch Specific runtime dependencies for sub package builds

### ISSUE THREAD

**Issue by mohanboddu** [rpm-software-management/rpm#865]
From https://pagure.io/releng/issue/7553

```
Please first read trough https://pagure.io/packaging-committee/issue/691

We have been approached by this question:

I have an noarch package foo
it has (implicitly noarch) subpackage foo-extra, it has a runtime dependency on extra package (that is not available on xyz arch)
How do I proceed to exclude the foo-extra subpackage from being build/available on the xyz arch?

Do I need to switch both the main package and the subpackage to be arched?

In FPC, we have some ideas about how it should work, however, we don't know how it actually is implemented.

Thanks
```

Filing this ticket as [suggested](https://pagure.io/releng/issue/7553#comment-517054)

**Comment by pmatilai** [comment]
I think this is a compose problem, not rpm problem: it'd be wrong for rpm to encode some arch-specific knowledge into that noarch package, when that arch-limitation could go away at any time (by that extra package becoming available on that arch). Another line of thought is what dnf did initially and simply hide packages with broken dependencies.

**Comment by pmatilai** [comment]
As per above, I don't think this is really an rpm issue, closing.
