### ISSUE TITLE
error: Illegal char '*' (0x2a) in: 1.4.* does not stop the build

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#881]
In Fedora rawhide with rpm 4.15.0-1, when a dependency generator generates invalid requires (e.g. `Requires: python3.8dist(wrapt) = 1.11.*`), there is an error in the log:

```
error: Illegal char '*' (0x2a) in: 1.4.*
error: Illegal char '*' (0x2a) in: 1.11.*
```

But this does not stop the build. I consider that dangerous behavior. Errors should not pass silently (and this is pretty silent, considering you need to know what you are looking for to find it).

**Comment by pmatilai** [comment]
Yup, the error code simply gets dismissed in the bowels of rpmfc. 
It's also not the only bug that kind...

**Comment by hroncok** [comment]
Thanks.
