### ISSUE TITLE
Get rid of automake in favour of CMake or meson

### ISSUE THREAD

**Issue by KOLANICH** [rpm-software-management/rpm#887]

**Comment by pmatilai** [comment]
And why would we want to consider such a thing?

**Comment by KOLANICH** [comment]
Because noone likes autotools.

**Comment by pmatilai** [comment]
No-one? You're absolutely sure about that?
You're talking to somebody who happens to prefer the devil he knows to those he doesn't.

Whether somebody likes them or not is irrelevant, autotools get the job done and there we have better things to do than fix what ain't broken, such as the endless pile of things that *are* broken in rpm. 

Patches might be considered. Getting stuff to build under X, Y or Z is not that big of a deal, but  there's > 13K lines worth of autotools based test-suite that would need porting.

**Comment by Conan-Kudo** [comment]
While I don't particularly like autotools (and generally prefer CMake to it myself), the large amount of autotest usage in this codebase for the test suite is a huge impairment for migrating to anything else. I don't expect it to change unless we dedicated time to change all this, and it might not be worth it right now to do that.

**Comment by pmatilai** [comment]
Seems I need to clarify the statement wrt this, I see I've said "patches might be considered" but that sends an entirely wrong message really.

Besides the tests, and the fact that autotools is the devil *I* know and prefer, rpm sits really early in the bootstrap chain, and adding significant extra burden there is not acceptable. If glibc or gcc adopt some non-autotools based build-system, then it might be the time to reconsider. Until then, the matter is not open for discussion.
