### ISSUE TITLE
../rpmio/rpmlua.h:5:10: fatal error: lauxlib.h: No such file or directory

### ISSUE THREAD

**Issue by KOLANICH** [rpm-software-management/rpm#888]
```
depbase=`echo parsePreamble.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H   -I.. -I.. -I../include/ -I../misc  -D_REENTRANT -Wall -Wpointer-arith -Wmissing-prototypes -Wstrict-prototypes  -fno-strict-aliasing -fstack-protector -Wempty-body -fopenmp -g -O2 -MT parsePreamble.lo -MD -MP -MF $depbase.Tpo -c -o parsePreamble.lo parsePreamble.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I.. -I.. -I../include/ -I../misc -D_REENTRANT -Wall -Wpointer-arith -Wmissing-prototypes -Wstrict-prototypes -fno-strict-aliasing -fstack-protector -Wempty-body -fopenmp -g -O2 -MT parsePreamble.lo -MD -MP -MF .deps/parsePreamble.Tpo -c parsePreamble.c  -fPIC -DPIC -o .libs/parsePreamble.o
In file included from parsePreamble.c:15:
../rpmio/rpmlua.h:5:10: fatal error: lauxlib.h: No such file or directory
```

The distro is Ubuntu eoan, liblua5.3-dev is installed, `configure.ac` was modified to find it using pkg-config. The configure flags are: `--with-lua`.

**Comment by pmatilai** [comment]
Where's lauxlib.h on the system? My crystal ball seems broken today. 

rpm simply expects lua includes to be in the compilers include path, so either it's not present at all, or it's not in the path, that's all there is to it. If it's not on the path you need to tell rpm about it. You're talking about a modified source so I can't tell you how to fix it, but the standard way to pass additional include paths would be appending CPPFLAGS="-I/some/path" to the configure line.

**Comment by KOLANICH** [comment]
>Where's lauxlib.h on the system? My crystal ball seems broken today.

```bash
pkg-config --cflags-only-I lua5.3
-I/usr/include/lua5.3
ls -l /usr/include/lua5.3
total 60
-rw-r--r-- 1 root root  8432 Nov 23  2015 lauxlib.h
-rw-r--r-- 1 root root 14833 May 30  2016 lua.h
-rw-r--r-- 1 root root   191 Dec 23  2004 lua.hpp
-rw-r--r-- 1 root root 21503 Apr  8  2019 luaconf.h
-rw-r--r-- 1 root root  1173 Feb  6  2014 lualib.h
```

As I have said, I have replaced `lua` with `lua5.3` in https://github.com/rpm-software-management/rpm/blob/master/configure.ac#L968 .

**Comment by mlschroe** [comment]
I used the following patch to fix the build:
```
--- ./build/Makefile.am.orig    2019-10-02 13:12:00.031823903 +0000
+++ ./build/Makefile.am 2019-10-02 13:13:09.743668564 +0000
@@ -10,6 +10,9 @@ AM_CPPFLAGS += @WITH_NSS_INCLUDE@
 AM_CPPFLAGS += @WITH_MAGIC_INCLUDE@
 AM_CPPFLAGS += @WITH_POPT_INCLUDE@
 AM_CPPFLAGS += -I$(top_srcdir)/misc
+if WITH_LUA
+AM_CPPFLAGS += @LUA_CFLAGS@
+endif
```

**Comment by mlschroe** [comment]
(That's also what `Makefile.am` in the `lib` directory does)

**Comment by pmatilai** [comment]
Oh, right... I didn't remember we use pkg-config to find Lua in the first place, I thought the initial comment was about changing configure to do so, but it's only about changing the "target". And yes in that case it's rpm's responsibility to pass LUA_CFLAGS around.

On that note, one shouldn't have to *edit* configure.ac to do anything normal, the ---with-lua test should support passing in a custom name as an argument (ie --with-lua=lua5.3). A PR from somebody who can actually test it would be welcome, I can't easily test such things (which is why the problem exists in the first place)

**Comment by KOLANICH** [comment]
@mlschroe, thanks. But the fix doesn't work. I don't mean that the patch cannot be applied, I have applied it manually. I mean I still get the same error.
1. if the conditional is present, `-I/usr/include/lua5.3`  is not added into the makefile
2. I have removed the conditional. Even though the makefile contains `-I/usr/include/lua5.3` I still get the error.

**Comment by pmatilai** [comment]
Oh, *now* I see the problem: commit 62bd62286aa888c60145daf315a938dd87eadc89 added the lauxlib.h include to the rpmlua.h header which used to be independent of lua headers, and thus gets included from places where LUA_CFLAGS are not enabled. Will fix.

**Comment by pmatilai** [comment]
Should be fixed by #893 (doesn't help with the pkgconfig module name though)

**Comment by KOLANICH** [comment]
Thanks, it really fixes this.

**Comment by pmatilai** [comment]
Excellent. Thanks for testing and confirming.

**Comment by pmatilai** [comment]
Oh, and thanks for reporting too.
