### ISSUE TITLE
rpmbuild sh: /usr/bin/python: No such file or directory

### ISSUE THREAD

**Issue by chrismaes87** [rpm-software-management/rpm#919]
when running `rpmbuild` on an os which does not have `python2` installed, then `/usr/bin/python` is not present and many (about 12) errors are shown:

     sh: /usr/bin/python: No such file or directory

The build seems to run fine, but I don't know what might not work. I have this issue on **centos8**.

Running `rpmbuild --rebuild` on one package did not produce this problem, but that might just depend on the format, what is being packaged, ...

**Comment by pmatilai** [comment]
This has been addressed in rpm >= 4.15 in the only way available to rpm: by removing the offending macros and helpers (see commit ba85c95963f9b62f237c0442f6b5aca3e355fa83).
Beyond that it's a packaging problem, both at the distro and user end: in the python 2 vs 3 world, unversioned python invocation doesn't work.

**Comment by praiskup** [comment]
See also: https://github.com/rpm-software-management/rpm/issues/424
