### ISSUE TITLE
Cannot set Build Date from changelog anymore

### ISSUE THREAD

**Issue by bmwiedemann** [rpm-software-management/rpm#932]
This is a regression over 4.14.2
and not from #785 

I do set
```
%_buildhost reproducible
%source_date_epoch_from_changelog Y
%clamp_mtime_to_source_date_epoch Y
%use_source_date_epoch_as_buildtime Y
```

and I can see with `rpm -qpvl` that the file mtimes are correctly adjusted, but the Build Date header gets the current time with 4.15, where it got the changelog date with 4.14.2

I think commit fa303d5ba6bef5b4a44b884c6dadadc27b594caa broke setting `RPMTAG_BUILDTIME` from `SOURCE_DATE_EPOCH` when that is only parsed from the first changelog entry later.

**Comment by bmwiedemann** [comment]
CC @kanavin @ffesti because you worked on that patch 2 years ago (yes, openSUSE is slow to adopt new major rpm versions)

**Comment by kanavin** [comment]
Possibly, but the patch is still valid, as it makes the data thread-safe. I really have no idea about where and how changelong date is used, so you need to figure out why it isn't working anymore by reading code.

**Comment by mlschroe** [comment]
(openSUSE is not slow to adopt new major versions. rpm-4.15 was released 2019-09-26, it is in the Factory staging project since 2019-10-02.)

**Comment by Conan-Kudo** [comment]
> (openSUSE is not slow to adopt new major versions. rpm-4.15 was released 2019-09-26, it is in the Factory staging project since 2019-10-02.)

To be fair, that's a relatively new thing. And being in staging still doesn't mean it's in openSUSE itself yet. The gap _is_ closing though...

The lag between upstream and openSUSE for rpm 4.14 was 3 months (2017-10-12 to 2018-01-13).

For rpm 4.13, the lag was 4 months (2016-11-03 to 2017-03-03).

**Comment by bmwiedemann** [comment]
OK, so I was just annoyed that it took over 2 years from the commit to me finding this issue and #934 .
With 4.15-alpha only out in 2019-06, it is probably fairer to say, that rpm upstream could improve there.

**Comment by pmatilai** [comment]
Rarely used features with no associated tests will inevitably sometimes regress, it's just a fact of life.

**Comment by pmatilai** [comment]
Ehh... so there's been this distant alarm ringing in my head all the way since introducing %use_source_date_epoch_as_buildtime in #785. 

There's supposed to be a test for this stuff, and #785 should've broken it but didn't, and that's the alarm in my head:

```
# Reproducably build and verify a package
AT_SETUP([rpmkeys -Kv <unsigned> 2])
```
As it happens, commit e20527ae07e0a72eb8133d3ab5c2ddef2b5d6b39 cut off the wings of that test without realizing in one of the case the actual values of the checksums were an all-important part of the test. And hence commit fa303d5 (and later #785 again) were able to silently break things.

**Comment by pmatilai** [comment]
...which is just a long-winded way to say it's ultimately my fault that this got broken, apologies for that.
