### ISSUE TITLE
Problem with FreeBSD and xargs

### ISSUE THREAD

**Issue by wichtounet** [rpm-software-management/rpm#948]
Hi, 

Since this commit 09d181d78c16e1751779586c606e85c11f360407, `rpmbuild` will have issues on FreeBSD. `xargs` does not have a -d option on FreeBSD. 

Would it be possible to make this conditionally if it's not FreeBSD?
Or simply disable this for FreeBSD like it is for Darwin?

Thanks

**Comment by pmatilai** [comment]
All these find/xargs combos should really be using -print0/-0 instead for weird character safety. Those are not standard :astonished: but then neither is -d, and -0 does exist on FreeBSD too.

**Comment by ffesti** [comment]
A quick search turns up find-debuginfo.sh which also has xargs -d in it.
