### ISSUE TITLE
Build fails on: "invalid utf-8 encoding in Classdict: TrueType Font data"

### ISSUE THREAD

**Issue by janvanmansum** [rpm-software-management/rpm#952]
# RPM
* Platform: MacOS Mojave: 10.14.6 (18G1012)
* RPM version: 4.15.1

# Steps to reproduce problem
1. Clone https://github.com/DANS-KNAW/issue-rpm-font-problem
2. Run `./rpmbuild.sh` in the project directory

# Problem
I get the following error:
```
./rpmbuild.sh
~/git/test/issue-rpm-font-problem/rpmbuild/SPECS ~/git/test/issue-rpm-font-problem
warning: Could not canonicalize hostname: XXXX
Processing files: font-rpm-1.0-1.noarch
Provides: font-rpm = 1.0-1
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Checking for unpackaged file(s): /usr/local/Cellar/rpm/4.15.1/lib/rpm/check-files /Users/XXXX/git/test/issue-rpm-font-problem/rpmbuild/BUILDROOT/font-rpm-1.0-1.x86_64
error: Package font-rpm: invalid utf-8 encoding in Classdict: TrueType Font data, 19 tables, 1st "FFTM", 15 names, Microsoft, language 0x409, Digitized data copyright � 2010-2011, Google Corporation.Open SansBoldAscender - Open Sans Bold - Illegal byte sequence


RPM build errors:
    Could not canonicalize hostname: XXXX
    Package font-rpm: invalid utf-8 encoding in Classdict: TrueType Font data, 19 tables, 1st "FFTM", 15 names, Microsoft, language 0x409, Digitized data copyright � 2010-2011, Google Corporation.Open SansBoldAscender - Open Sans Bold - Illegal byte sequence
~/git/test/ssue-rpm-font-problem
```
# Analysis / observations / questions
* This problem did not occur in the previous versions of `rpm`. I think the previous version I had installed was `4.14.2.1`.
* The font metadata does seem to have a malencoded copyright sign. Why does rpm try to retrieve the font metadata anyway? rpm doesn't seem to use the file name as a hint, because the problem also occurs if you rename the font file (`rpmbuild/BUILDROOT/font-rpm-1.0-1.x86_64/var/www/html/OpenSans-Bold.ttf`) to something else.
* Could this issue have something to do with the item "Fix non-deterministic RPMTAG_CLASSDICT order (#934, regression in 4.15.0)" in the [release notes](https://rpm.org/wiki/Releases/4.15.1)?
* You could say that this is not an issue with rpm, if the font file metadata is incorrect, but in any case I think this problem should not be more than a warning.

**Comment by ffesti** [comment]
Yes, making invalid encoding an error is a new thing. RPM is using libmagic (from the `file` utility) to classify files. That's where this data comes from.
The reason to make this an error is that modern updaters use the data from the rpm header and display them as unicode strings (especially when using the Python bindings but also in general). Enforcing valid UTF-8 makes sure this always works properly.

There is 
```
# Should invalid utf8 encoding in package metadata terminate a build?
%_invalid_encoding_terminates_build 1
```
in the macros file. To switch this back to a warning set the macro to 0. But be better fix would be changing the font file.

**Comment by janvanmansum** [comment]
👍 Thanks a lot! I was already busy implementing a clumsy work-around, but turning on this switch is much easier. Also, I'll see if I can file an issue with the creators of the font.
