### ISSUE TITLE
RFE: allow setting rpm variable, named with other variables

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#960]
I’d like to be able to declare rpm variables, with a name constructed from other rpm variables

```rpmspec
%global something%{suffix} value
```
Because I need to pass info from `%build` to `%install`, and `%build` may execute the same operation for multiple subpackages.

The current way to do that is to write things to a file in `%build` and read it in `%install`, but that is excessively cumbersome (cumbersome enough I’m now doing build operations in `%install` just to avoid this pain).

Please just relax the stupid assert that freaks out if it sees a variable in the new variable name.

**Comment by mlschroe** [comment]
Wouldn't `%expand` work here? (Note that `suffix` is already used in rpm...)
```
%{expand:%%global something%{suff} value}
```

**Comment by nim-nim** [comment]
@mlschroe Thank you that works (even if it’s not too intuitive)

Unfortunately the end result did not work out, due to the usual differences in evaluation time between the rpm and shell layer :( So I guess it’s back to doing things in the wrong section, or using a file to pass data, for me.
