### ISSUE TITLE
Document: "rpmbuild -br" always returns 11 when "--nodeps" is used

### ISSUE THREAD

**Issue by hrnciar** [rpm-software-management/rpm#963]
Hello,

I have encountered problem with rpmbuild -br and dependencies during dynamic buildrequires. It returns 11 even though all dependencies are satisfied.

How to reproduce:

I have this .spec file:
[dummy-pkg.spec.txt](https://github.com/rpm-software-management/rpm/files/3911787/dummy-pkg.spec.txt)

When you install all dependencies (copr-cli, star), it shoudln't return 11 but it does.
`/usr/bin/rpmbuild -br --target x86_64 --nodeps /tmp/dummy-pkg.spec`

Thank you

**Comment by ignatenkobrain** [comment]
That's because of --nodeps. it does not check deps, so it always wants to give you nosrc.rpm

**Comment by praiskup** [comment]
Do we have to bind the nosrc.rpm with exit status 11?

**Comment by dmnks** [comment]
Discussed here: https://github.com/rpm-software-management/mock/issues/434#issuecomment-576703484

**Comment by dmnks** [comment]
I think we should reconsider this one. Returning `RPMBUILD_MISSINGBUILDREQUIRES` when `--nodeps` is in effect [doesn't seem](https://github.com/rpm-software-management/mock/issues/434#issuecomment-577086572) right.

**Comment by dmnks** [comment]
Note: Based on a chat with @praiskup, a fix (if any) should not happen until mock has fixed (worked around this) itself, otherwise we would run a risk of breaking it.

**Comment by hrnciar** [comment]
Mock was updated, so this is not blocked anymore.

**Comment by dmnks** [comment]
As discussed with @ffesti on IRC today, we'd rather keep this behavior as is, although a point can be made both ways, i.e. in favor of the exit code 11 with `--nodeps` (to signal *unchecked* dynamic deps) as well as in favor of a different exit code (since deps weren't checked per user's request). So, closing this now. If you still wish to have this changed, please open a new issue describing the use case.

**Comment by praiskup** [comment]
Shouldn't we at least document somewhere what the exit status 11 means then?  Ie why
we are returning that value?

**Comment by dmnks** [comment]
Well, that's a good point. Reopening and rewording the title to implement a man page update. Thank you, Pavel!

**Comment by dmnks** [comment]
Actually looking closely at the `rpmbuild(8)` man page, it seems we don't specify any exit codes there at the moment. So I'm wondering if it really is worth documenting them for this particular use case (`-br --nodeps`) only.

There could be a separate section called `EXIT CODES` or similar where `RPMRC_MISSINGBUILDREQUIRES` (code 11) would be described, but it still feels a bit awkward to only have that and not the others.

@ffesti, do we have a plan to document exit codes across RPM at all?

**Comment by dmnks** [comment]
Had a quick chat on IRC with @ffesti and he said it's actually just three outcomes that rpmbuild may return; success (0), error (1) or missing build deps (11), in which case adding all three into the man page would be worthwhile. I'll skim through the code to double-check and go ahead with that.

**Comment by dmnks** [comment]
Possibly related: https://github.com/rpm-software-management/rpm/issues/1304

**Comment by praiskup** [comment]
> or missing build deps (11)

Yes, and we return 11 also when `--nodeps` is specified (no matter if all build requires are installed).

**Comment by ignatenkobrain** [comment]
> no matter if all build requires are installed

because rpmbuild does not check them because `--nodeps` is specified :) So for rpmbuild none are installed.

**Comment by dmnks** [comment]
> > no matter if all build requires are installed
> 
> because rpmbuild does not check them because `--nodeps` is specified :) So for rpmbuild none are installed.

Which does not necessarily mean that they are *missing*. But yeah, we still return 11, to "signal" that the deps weren't checked and some *might* be missing.

**Comment by praiskup** [comment]
> So for rpmbuild none are installed.

I don't see any practical reason to exit status 11 in such case.  That's why I filled this issue originally.

Since we aren't entirely consistent here, we should document that exit status 11 might be result of the `--nodeps` option.
