### ISSUE TITLE
4.15.1: rpm cannot replace directory by file on upgrade

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#964]
I made some test unit for that issue.
test-replace-directory-1.0 package has in /mnt/file directory with /mnt/file/file file. Than 2.0 has only /mnt/file file.

Here is result:

<pre>[root@barrel RPMS]# rpm -ivh test-replace-directory-1.0-1.x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:test-replace-directory-1.0-1     ################################# [100%]

[root@barrel RPMS]# rpm -Uvh test-replace-directory-2.0-1.x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
	file /mnt/file from install of test-replace-directory-2.0-1.x86_64 conflicts with file from package test-replace-directory-1.0-1.x86_64
</pre>

```
Summary:        test package
Name:           test-replace-directory
Version:        1.0
Release:        1
License:        Test

%description
Test package.

%prep

%build

%install
%__mkdir_p %{buildroot}/mnt/file
> %{buildroot}/mnt/file/file

%files
/mnt/file
```
```
Summary:        test package
Name:           test-replace-directory
Version:        2.0
Release:        1
License:        Test

%description
Test package.

%prep

%build

%install
%__mkdir_p %{buildroot}/mnt
> %{buildroot}/mnt/file

%files
/mnt/file

```

**Comment by pmatilai** [comment]
Yes, this is essentially the same limitation as directory <-> symlink replacement. The conflict is intentionally raised to avoid bad things during transaction, see commit 00d82f1322c6dbf471f61bca7a5cc347fc2fca0a for details.
