### ISSUE TITLE
``make check`` failing on Fedora

### ISSUE THREAD

**Issue by phi-gamma** [rpm-software-management/rpm#977]
The testsuite reports numerous failures on unrelated tests that
look rather innocuous, e. g. “SIGPIPE from install scriptlet”
from ``rpmio.at``. The common theme appears to be failure of
recursive directory operations inside a *fakechroot* environment.
From the log:

    +mkdir: cannot create directory '/build/BUILDROOT/sigpipe-1.0-1.x86_64': No such file or directory
    +error: Bad exit status from /usr/local/var/tmp/rpm-tmp.LG7gAJ (%install)
    +    Bad exit status from /usr/local/var/tmp/rpm-tmp.LG7gAJ (%install)

Indeed, while simple directory operations work inside the chroot
recursive ones don’t:

    $ MAGIC="/magic/magic" FAKECHROOT_BASE=$(pwd)/testing fakechroot mkdir /foo
    $ MAGIC="/magic/magic" FAKECHROOT_BASE=$(pwd)/testing fakechroot mkdir -p /foo/bar/baz
    mkdir: cannot create directory ‘/foo/bar’: No such file or directory

To reproduce: ``autoreconf -f -i && ./configure && make -j check``.

System: FC 30, with stock fakechroot 2.19. The
``tests/rpmtests.log`` is too large for *fpaste* so please let me
know what specific information you need.

**Comment by pmatilai** [comment]
Are there symlinks in the path to the repository? In other words, in the checkout directory, do ```pwd``` and ```realpath .``` agree on the path?

**Comment by phi-gamma** [comment]
Yes, there are indeed symlinks in the path. Without them the
operations succeed. So does ``make check``. Thanks!

Is that a general assumption about the test suite? If so I wonder
if it could be enforced by bailing out early if it is unmet.

**Comment by pmatilai** [comment]
That's just a random limitation / bug in fakechroot AFAIK.

**Comment by phi-gamma** [comment]
Ah, nevermind then. Not going to open that can of bugs.

**Comment by pmatilai** [comment]
Yup. OTOH if this turns out to be a recurring bug then at some point it will be easier to add a check than explain. We'll see :)
