### ISSUE TITLE
Berkeley DB not disabled with --disable-bdb

### ISSUE THREAD

**Issue by stefanbidi** [rpm-software-management/rpm#983]
The problem is fairly trivial: `lib/backend/db3.c` gets included in the build even when `--disable-bdb` is used. I'm trying to build with lmdb only.

The fix is equally trivial: `have_bdb="no"` needs to be moved outside of the AS_IF statement in configure.ac.

    --- configure.ac.orig	2019-12-21 11:05:18.388254060 -0500
    +++ configure.ac	2019-12-21 11:05:46.143625687 -0500
    @@ -537,11 +537,11 @@
                   [enable_bdb="$enableval"],
                   [enable_bdb=yes])
     
    +have_bdb="no"
     AS_IF([test "x$enable_bdb" != "xno"], [
       if [ test -x db/dist/configure ]; then
         have_bdb="internal"
       else
    -    have_bdb="no"
         AC_CHECK_HEADERS([db.h],[
           AC_PREPROC_IFELSE([
             AC_LANG_SOURCE([

**Comment by Conan-Kudo** [comment]
This should be fixed in #979.

**Comment by Conan-Kudo** [comment]
@stefanbidi Can you try with the current git master? This should be fixed now.

**Comment by pmatilai** [comment]
Since the fix that went into git is exactly what was proposed here as a verified fix I think we can safely close this now.
