### ISSUE TITLE
Python requires generator: Cannot chain different ops: or + with

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#995]
The new version of Python requires generator fails with complicated expressions.

cc @gordonmessmer @Conan-Kudo @ignatenkobrain 

Examples:

## Matplotlib

https://koschei.fedoraproject.org/package/python-matplotlib?collection=f32

Requirement: `pyparsing>=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6`

```
Cannot chain different ops: (python3.8dist(pyparsing) >= 2.0.1 with python3.8dist(pyparsing) < 2.1.2 or python3.8dist(pyparsing) >= 2.1.2.0 with python3.8dist(pyparsing) < 2.1.6 or python3.8dist(pyparsing) >= 2.1.6.0 with python3.8dist(pyparsing) < 2.0.4 or python3.8dist(pyparsing) >= 2.0.4.0)
```

## Sphinx

https://koschei.fedoraproject.org/package/python-sphinx?collection=f32

Requirement: `babel>=1.3,!=2.0`

```
Cannot chain different ops: (python3.8dist(babel) < 2 or python3.8dist(babel) >= 2.0 with python3.8dist(babel) >= 1.3)
```

## ara

https://koschei.fedoraproject.org/package/ara?collection=f32

Requirement: `pbr!=2.1.0,>=2.0.0`

```
Cannot chain different ops: (python3.8dist(pbr) >= 2 with python3.8dist(pbr) < 2.1 or python3.8dist(pbr) >= 2.1.0)
```

**Comment by hroncok** [comment]
We would need to put the or pairs into parenthesis, correct?

**Comment by hroncok** [comment]
I'm testing a fix. If it works, will submit a PR.

**Comment by hroncok** [comment]
My fix does this:

```
(python3.8dist(pyparsing) >= 2.0.1 with (python3.8dist(pyparsing) < 2.1.2 or python3.8dist(pyparsing) >= 2.1.2.0) with (python3.8dist(pyparsing) < 2.0.4 or python3.8dist(pyparsing) >= 2.0.4.0) with (python3.8dist(pyparsing) < 2.1.6 or python3.8dist(pyparsing) >= 2.1.6.0))

(python3.8dist(babel) >= 1.3 with (python3.8dist(babel) < 2 or python3.8dist(babel) >= 2.0))

(python3.8dist(pbr) >= 2 with (python3.8dist(pbr) < 2.1 or python3.8dist(pbr) >= 2.1.0))
```

**Comment by hroncok** [comment]
https://github.com/rpm-software-management/rpm/pull/996

**Comment by gordonmessmer** [comment]
Does rpm offer an interface to determine whether or not a dependency expression is valid, either on a command line or in python's "rpm" module?  Or is building an rpm the only available test?

**Comment by Conan-Kudo** [comment]
The RPM Python API may provide a way to build such a tool that could be incorporated into [`rpmdevtools`](https://pagure.io/rpmdevtools), but there's currently no such tool.

**Comment by gordonmessmer** [comment]
The RPM Python API would be ideal if I could use it to determine if an expression were valid.  I would think dsSingle would do that, but it does not seem to care whether the second arg is a valid expression or not.
